// Version: 1.0020
// AI генератор на текст — РЕАЛЕН инструмент чрез БЕЗПЛАТЕН keyless ендпойнт.
// Източник: Pollinations Text API (безплатен, БЕЗ ключ, БЕЗ акаунт, с CORS).
//   GET  https://text.pollinations.ai/<URL-кодиран промпт>
//   POST https://text.pollinations.ai/  { "messages":[{role,content}], "model":"openai" }
// И двата режима връщат чист текст (text/plain). Тук ползваме GET с
// encodeURIComponent върху целия промпт — най-съвместимо и без тяло.
// Напълно БЕЗ ключ, БЕЗ регистрация, БЕЗ billing, БЕЗ tracking.
//
// Huawei 3.1 (11.09.2026, тестерите са в Китай → „Connection error"): заявката минава през
// core/announce-gen.js — ПРЯКО → при грешка през Pupikes relay → при пак грешка ВГРАДЕН офлайн
// резерв (шаблон за известие по въведения текст; за „Обобщи" — извличащо обобщение на устройството).
// Никога само „грешка" без резултат. Таймаут през Promise.race (БЕЗ AbortController).

import { t, register, getLang } from '../core/i18n.js';
import { askAI, offlineAnnouncement, offlineSummary } from '../core/announce-gen.js';

register({
  ai_title: { bg:'AI генератор на текст', ru:'AI-генератор текста', uk:'AI-генератор тексту', en:'AI text generator', de:'KI-Textgenerator', fr:'Générateur de texte IA', es:'Generador de texto IA', 'es-MX':'Generador de texto IA', it:'Generatore di testo IA', pt:'Gerador de texto IA', ar:'مولّد نصوص بالذكاء الاصطناعي', hi:'AI टेक्स्ट जेनरेटर', ja:'AIテキスト生成', ky:'AI текст генератору', 'zh-Hant':'AI 文字產生器' },
  ai_mode_label: { bg:'Режим', ru:'Режим', uk:'Режим', en:'Mode', de:'Modus', fr:'Mode', es:'Modo', 'es-MX':'Modo', it:'Modalità', pt:'Modo', ar:'الوضع', hi:'मोड', ja:'モード', ky:'Режим', 'zh-Hant':'模式' },
  ai_mode_write: { bg:'Напиши', ru:'Напиши', uk:'Напиши', en:'Write', de:'Schreiben', fr:'Écrire', es:'Escribir', 'es-MX':'Escribir', it:'Scrivi', pt:'Escrever', ar:'اكتب', hi:'लिखें', ja:'作成', ky:'Жаз', 'zh-Hant':'撰寫' },
  ai_mode_summarize: { bg:'Обобщи', ru:'Обобщи', uk:'Узагальни', en:'Summarize', de:'Zusammenfassen', fr:'Résumer', es:'Resumir', 'es-MX':'Resumir', it:'Riassumi', pt:'Resumir', ar:'لخّص', hi:'सारांश', ja:'要約', ky:'Жыйынтыкта', 'zh-Hant':'摘要' },
  ai_mode_translate: { bg:'Преведи', ru:'Переведи', uk:'Переклади', en:'Translate', de:'Übersetzen', fr:'Traduire', es:'Traducir', 'es-MX':'Traducir', it:'Traduci', pt:'Traduzir', ar:'ترجم', hi:'अनुवाद', ja:'翻訳', ky:'Котор', 'zh-Hant':'翻譯' },
  ai_mode_explain: { bg:'Обясни', ru:'Объясни', uk:'Поясни', en:'Explain', de:'Erklären', fr:'Expliquer', es:'Explicar', 'es-MX':'Explicar', it:'Spiega', pt:'Explicar', ar:'اشرح', hi:'समझाएं', ja:'説明', ky:'Түшүндүр', 'zh-Hant':'解釋' },
  ai_translate_to: { bg:'Преведи на', ru:'Перевести на', uk:'Перекласти на', en:'Translate to', de:'Übersetzen nach', fr:'Traduire vers', es:'Traducir a', 'es-MX':'Traducir a', it:'Traduci in', pt:'Traduzir para', ar:'ترجم إلى', hi:'इसमें अनुवाद करें', ja:'翻訳先', ky:'Котор', 'zh-Hant':'翻譯成' },
  ai_prompt_label: { bg:'Твоята заявка', ru:'Твой запрос', uk:'Твій запит', en:'Your request', de:'Deine Anfrage', fr:'Ta demande', es:'Tu solicitud', 'es-MX':'Tu solicitud', it:'La tua richiesta', pt:'Sua solicitação', ar:'طلبك', hi:'आपका अनुरोध', ja:'リクエスト', ky:'Сенин сурамың', 'zh-Hant':'你的請求' },
  ai_prompt_ph: { bg:'Напиши кратко стихотворение за морето…', ru:'Напиши короткое стихотворение о море…', uk:'Напиши короткий вірш про море…', en:'Write a short poem about the sea…', de:'Schreibe ein kurzes Gedicht über das Meer…', fr:'Écris un court poème sur la mer…', es:'Escribe un breve poema sobre el mar…', 'es-MX':'Escribe un breve poema sobre el mar…', it:'Scrivi una breve poesia sul mare…', pt:'Escreva um poema curto sobre o mar…', ar:'اكتب قصيدة قصيرة عن البحر…', hi:'समुद्र पर एक छोटी कविता लिखें…', ja:'海についての短い詩を書いて…', ky:'Деңиз жөнүндө кыска ыр жаз…', 'zh-Hant':'寫一首關於大海的短詩…' },
  ai_btn_generate: { bg:'Генерирай', ru:'Сгенерировать', uk:'Згенерувати', en:'Generate', de:'Generieren', fr:'Générer', es:'Generar', 'es-MX':'Generar', it:'Genera', pt:'Gerar', ar:'أنشئ', hi:'जेनरेट करें', ja:'生成', ky:'Түзүү', 'zh-Hant':'產生' },
  ai_btn_copy: { bg:'Копирай', ru:'Копировать', uk:'Копіювати', en:'Copy', de:'Kopieren', fr:'Copier', es:'Copiar', 'es-MX':'Copiar', it:'Copia', pt:'Copiar', ar:'نسخ', hi:'कॉपी करें', ja:'コピー', ky:'Көчүрүү', 'zh-Hant':'複製' },
  ai_hint: { bg:'Текстът се генерира от безплатна AI услуга (без ключ и акаунт): пряко → през Pupikes relay → без интернет: вградени офлайн шаблони.', ru:'Текст генерирует бесплатный ИИ-сервис (без ключа и аккаунта): напрямую → через Pupikes relay → без интернета: встроенные офлайн-шаблоны.', uk:'Текст генерує безкоштовний ШІ-сервіс (без ключа й акаунта): напряму → через Pupikes relay → без інтернету: вбудовані офлайн-шаблони.', en:'Text is generated by a free AI service (no key or account): direct → via the Pupikes relay → without internet: built-in offline templates.', de:'Der Text wird von einem kostenlosen KI-Dienst erzeugt (ohne Schlüssel und Konto): direkt → über das Pupikes-Relay → ohne Internet: eingebaute Offline-Vorlagen.', fr:'Le texte est généré par un service IA gratuit (sans clé ni compte) : direct → via le relais Pupikes → sans internet : modèles hors ligne intégrés.', es:'El texto lo genera un servicio de IA gratuito (sin clave ni cuenta): directo → a través del relay Pupikes → sin internet: plantillas integradas sin conexión.', 'es-MX':'El texto lo genera un servicio de IA gratuito (sin clave ni cuenta): directo → a través del relay Pupikes → sin internet: plantillas integradas sin conexión.', it:'Il testo è generato da un servizio IA gratuito (senza chiave né account): diretto → tramite il relay Pupikes → senza internet: modelli offline integrati.', pt:'O texto é gerado por um serviço de IA gratuito (sem chave nem conta): direto → através do relay Pupikes → sem internet: modelos offline integrados.', ar:'يُنشأ النص بخدمة ذكاء اصطناعي مجانية (بدون مفتاح أو حساب): مباشرة ← عبر وسيط Pupikes ← بدون إنترنت: قوالب مدمجة دون اتصال.', hi:'टेक्स्ट मुफ़्त AI सेवा से बनता है (बिना कुंजी या खाते): सीधे → Pupikes रिले के माध्यम से → बिना इंटरनेट: अंतर्निर्मित ऑफ़लाइन टेम्पलेट।', ja:'テキストは無料のAIサービスが生成します（キー・アカウント不要）：直接 → Pupikesリレー経由 → インターネットなし：内蔵オフラインテンプレート。', ky:'Текстти акысыз AI кызматы түзөт (ачкычсыз жана аккаунтсуз): түз → Pupikes relay аркылуу → интернетсиз: камтылган офлайн үлгүлөр.', 'zh-Hant':'文字由免費 AI 服務產生（無需金鑰或帳號）：直連 → 經 Pupikes 中繼 → 無網路時：內建離線範本。' },
  ai_err_no_prompt: { bg:'Въведи заявка.', ru:'Введи запрос.', uk:'Введи запит.', en:'Enter a request.', de:'Anfrage eingeben.', fr:'Saisis une demande.', es:'Ingresa una solicitud.', 'es-MX':'Ingresa una solicitud.', it:'Inserisci una richiesta.', pt:'Insira uma solicitação.', ar:'أدخل طلبًا.', hi:'अनुरोध दर्ज करें।', ja:'リクエストを入力してください。', ky:'Сурам киргиз.', 'zh-Hant':'請輸入請求。' },
  ai_generating: { bg:'Генерирам…', ru:'Генерирую…', uk:'Генерую…', en:'Generating…', de:'Wird generiert…', fr:'Génération…', es:'Generando…', 'es-MX':'Generando…', it:'Generazione…', pt:'Gerando…', ar:'جارٍ الإنشاء…', hi:'जेनरेट हो रहा…', ja:'生成中…', ky:'Түзүлүүдө…', 'zh-Hant':'產生中…' },
  ai_err_timeout: { bg:'Услугата не отговори навреме. Опитай отново.', ru:'Сервис не ответил вовремя. Попробуй снова.', uk:'Сервіс не відповів вчасно. Спробуй ще раз.', en:'The service did not respond in time. Try again.', de:'Der Dienst hat nicht rechtzeitig geantwortet. Versuche es erneut.', fr:'Le service n’a pas répondu à temps. Réessaie.', es:'El servicio no respondió a tiempo. Inténtalo de nuevo.', 'es-MX':'El servicio no respondió a tiempo. Inténtalo de nuevo.', it:'Il servizio non ha risposto in tempo. Riprova.', pt:'O serviço não respondeu a tempo. Tente novamente.', ar:'لم تستجب الخدمة في الوقت المناسب. حاول مرة أخرى.', hi:'सेवा ने समय पर जवाब नहीं दिया। फिर से प्रयास करें।', ja:'サービスが時間内に応答しませんでした。もう一度お試しください。', ky:'Кызмат убагында жооп берген жок. Кайра аракет кыл.', 'zh-Hant':'服務未及時回應。請重試。' },
  ai_err_offline: { bg:'Няма връзка / услугата не отговаря. Опитай отново, когато си онлайн.', ru:'Нет связи / сервис не отвечает. Попробуй снова, когда будешь онлайн.', uk:'Немає зв’язку / сервіс не відповідає. Спробуй знову, коли будеш онлайн.', en:'No connection / the service is not responding. Try again when you are online.', de:'Keine Verbindung / der Dienst antwortet nicht. Versuche es erneut, wenn du online bist.', fr:'Pas de connexion / le service ne répond pas. Réessaie une fois en ligne.', es:'Sin conexión / el servicio no responde. Inténtalo de nuevo cuando estés en línea.', 'es-MX':'Sin conexión / el servicio no responde. Inténtalo de nuevo cuando estés en línea.', it:'Nessuna connessione / il servizio non risponde. Riprova quando sei online.', pt:'Sem conexão / o serviço não responde. Tente novamente quando estiver online.', ar:'لا يوجد اتصال / الخدمة لا تستجيب. حاول مرة أخرى عندما تكون متصلاً.', hi:'कोई कनेक्शन नहीं / सेवा जवाब नहीं दे रही। ऑनलाइन होने पर फिर प्रयास करें।', ja:'接続なし／サービスが応答しません。オンライン時に再試行してください。', ky:'Байланыш жок / кызмат жооп бербейт. Онлайн болгондо кайра аракет кыл.', 'zh-Hant':'無連線／服務無回應。連線後請重試。' },
  ai_copied: { bg:'Копирано.', ru:'Скопировано.', uk:'Скопійовано.', en:'Copied.', de:'Kopiert.', fr:'Copié.', es:'Copiado.', 'es-MX':'Copiado.', it:'Copiato.', pt:'Copiado.', ar:'تم النسخ.', hi:'कॉपी किया गया।', ja:'コピーしました。', ky:'Көчүрүлдү.', 'zh-Hant':'已複製。' },
  ai_via_relay: { bg:'Отговор през Pupikes relay.', ru:'Ответ через Pupikes relay.', uk:'Відповідь через Pupikes relay.', en:'Answer via the Pupikes relay.', de:'Antwort über das Pupikes-Relay.', fr:'Réponse via le relais Pupikes.', es:'Respuesta a través del relay Pupikes.', 'es-MX':'Respuesta a través del relay Pupikes.', it:'Risposta tramite il relay Pupikes.', pt:'Resposta através do relay Pupikes.', ar:'الإجابة عبر وسيط Pupikes.', hi:'Pupikes रिले के माध्यम से उत्तर।', ja:'Pupikesリレー経由の応答。', ky:'Pupikes relay аркылуу жооп.', 'zh-Hant':'透過 Pupikes 中繼的回覆。' },
  ai_via_offline: { bg:'Услугата е недостъпна — резултатът е от вградените офлайн шаблони. Редактирай го свободно.', ru:'Сервис недоступен — результат из встроенных офлайн-шаблонов. Свободно редактируй.', uk:'Сервіс недоступний — результат із вбудованих офлайн-шаблонів. Вільно редагуй.', en:'The service is unreachable — the result comes from built-in offline templates. Edit it freely.', de:'Dienst nicht erreichbar — Ergebnis aus eingebauten Offline-Vorlagen. Frei bearbeitbar.', fr:'Service injoignable — résultat issu des modèles hors ligne intégrés. Modifie-le librement.', es:'Servicio no disponible — el resultado viene de plantillas integradas sin conexión. Edítalo libremente.', 'es-MX':'Servicio no disponible — el resultado viene de plantillas integradas sin conexión. Edítalo libremente.', it:'Servizio non raggiungibile — risultato dai modelli offline integrati. Modificalo liberamente.', pt:'Serviço inacessível — o resultado vem dos modelos offline integrados. Edite-o livremente.', ar:'الخدمة غير متاحة — النتيجة من القوالب المدمجة دون اتصال. عدّلها بحرية.', hi:'सेवा उपलब्ध नहीं — परिणाम अंतर्निर्मित ऑफ़लाइन टेम्पलेट से है। इसे स्वतंत्र रूप से संपादित करें।', ja:'サービスに接続できません。結果は内蔵オフラインテンプレートから生成されました。自由に編集してください。', ky:'Кызмат жеткиликсиз — натыйжа камтылган офлайн үлгүлөрдөн. Эркин оңдо.', 'zh-Hant':'服務無法連線，結果來自內建離線範本，可自由編輯。' },
  ai_copy_denied: { bg:'Копирането не е разрешено.', ru:'Копирование не разрешено.', uk:'Копіювання не дозволено.', en:'Copying is not allowed.', de:'Kopieren ist nicht erlaubt.', fr:'La copie n’est pas autorisée.', es:'No se permite copiar.', 'es-MX':'No se permite copiar.', it:'La copia non è consentita.', pt:'A cópia não é permitida.', ar:'النسخ غير مسموح.', hi:'कॉपी करना अनुमत नहीं है।', ja:'コピーは許可されていません。', ky:'Көчүрүүгө уруксат жок.', 'zh-Hant':'不允許複製。' }
});

export const title = t('ai_title');

// Готови шаблони: подсказват на потребителя какво да поиска.
// labelKey → превод на етикета в селекта; tpl/id остават непроменени.
const MODES = [
  { id: 'write', labelKey: 'ai_mode_write', tpl: (t) => t },
  { id: 'summarize', labelKey: 'ai_mode_summarize', tpl: (t) => `Обобщи накратко следния текст:\n\n${t}` },
  { id: 'translate', labelKey: 'ai_mode_translate', tpl: (t) => t /* спец. обработка с избор на език */ },
  { id: 'explain', labelKey: 'ai_mode_explain', tpl: (t) => `Обясни просто и ясно:\n\n${t}` }
];

// 15-те езика на екосистемата (както public/translations). За превод на всеки от тях.
// label → видим в селекта (преведен); name → име на езика в промпта (на руски, за модела).
const TARGET_LANGS = [
  { key: 'ai_lng_en', code: 'en', name: 'английски' },
  { key: 'ai_lng_bg', code: 'bg', name: 'български' },
  { key: 'ai_lng_ru', code: 'ru', name: 'руски' },
  { key: 'ai_lng_uk', code: 'uk', name: 'украински' },
  { key: 'ai_lng_de', code: 'de', name: 'немски' },
  { key: 'ai_lng_fr', code: 'fr', name: 'френски' },
  { key: 'ai_lng_es', code: 'es', name: 'испански' },
  { key: 'ai_lng_es_mx', code: 'es-MX', name: 'мексикански испански' },
  { key: 'ai_lng_it', code: 'it', name: 'италиански' },
  { key: 'ai_lng_pt', code: 'pt', name: 'португалски' },
  { key: 'ai_lng_ar', code: 'ar', name: 'арабски' },
  { key: 'ai_lng_hi', code: 'hi', name: 'хинди' },
  { key: 'ai_lng_ja', code: 'ja', name: 'японски' },
  { key: 'ai_lng_ky', code: 'ky', name: 'киргизки' },
  { key: 'ai_lng_zh', code: 'zh-Hant', name: 'традиционен китайски' }
];

register({
  ai_lng_en: { bg:'Английски', ru:'Английский', uk:'Англійська', en:'English', de:'Englisch', fr:'Anglais', es:'Inglés', 'es-MX':'Inglés', it:'Inglese', pt:'Inglês', ar:'الإنجليزية', hi:'अंग्रेज़ी', ja:'英語', ky:'Англисче', 'zh-Hant':'英語' },
  ai_lng_bg: { bg:'Български', ru:'Болгарский', uk:'Болгарська', en:'Bulgarian', de:'Bulgarisch', fr:'Bulgare', es:'Búlgaro', 'es-MX':'Búlgaro', it:'Bulgaro', pt:'Búlgaro', ar:'البلغارية', hi:'बल्गेरियाई', ja:'ブルガリア語', ky:'Болгарча', 'zh-Hant':'保加利亞語' },
  ai_lng_ru: { bg:'Руски', ru:'Русский', uk:'Російська', en:'Russian', de:'Russisch', fr:'Russe', es:'Ruso', 'es-MX':'Ruso', it:'Russo', pt:'Russo', ar:'الروسية', hi:'रूसी', ja:'ロシア語', ky:'Орусча', 'zh-Hant':'俄語' },
  ai_lng_uk: { bg:'Украински', ru:'Украинский', uk:'Українська', en:'Ukrainian', de:'Ukrainisch', fr:'Ukrainien', es:'Ucraniano', 'es-MX':'Ucraniano', it:'Ucraino', pt:'Ucraniano', ar:'الأوكرانية', hi:'यूक्रेनी', ja:'ウクライナ語', ky:'Украинче', 'zh-Hant':'烏克蘭語' },
  ai_lng_de: { bg:'Немски', ru:'Немецкий', uk:'Німецька', en:'German', de:'Deutsch', fr:'Allemand', es:'Alemán', 'es-MX':'Alemán', it:'Tedesco', pt:'Alemão', ar:'الألمانية', hi:'जर्मन', ja:'ドイツ語', ky:'Немисче', 'zh-Hant':'德語' },
  ai_lng_fr: { bg:'Френски', ru:'Французский', uk:'Французька', en:'French', de:'Französisch', fr:'Français', es:'Francés', 'es-MX':'Francés', it:'Francese', pt:'Francês', ar:'الفرنسية', hi:'फ़्रेंच', ja:'フランス語', ky:'Французча', 'zh-Hant':'法語' },
  ai_lng_es: { bg:'Испански', ru:'Испанский', uk:'Іспанська', en:'Spanish', de:'Spanisch', fr:'Espagnol', es:'Español', 'es-MX':'Español', it:'Spagnolo', pt:'Espanhol', ar:'الإسبانية', hi:'स्पेनिश', ja:'スペイン語', ky:'Испанча', 'zh-Hant':'西班牙語' },
  ai_lng_es_mx: { bg:'Испански (Мексико)', ru:'Испанский (Мексика)', uk:'Іспанська (Мексика)', en:'Spanish (Mexico)', de:'Spanisch (Mexiko)', fr:'Espagnol (Mexique)', es:'Español (México)', 'es-MX':'Español (México)', it:'Spagnolo (Messico)', pt:'Espanhol (México)', ar:'الإسبانية (المكسيك)', hi:'स्पेनिश (मेक्सिको)', ja:'スペイン語（メキシコ）', ky:'Испанча (Мексика)', 'zh-Hant':'西班牙語（墨西哥）' },
  ai_lng_it: { bg:'Италиански', ru:'Итальянский', uk:'Італійська', en:'Italian', de:'Italienisch', fr:'Italien', es:'Italiano', 'es-MX':'Italiano', it:'Italiano', pt:'Italiano', ar:'الإيطالية', hi:'इतालवी', ja:'イタリア語', ky:'Италянча', 'zh-Hant':'義大利語' },
  ai_lng_pt: { bg:'Португалски', ru:'Португальский', uk:'Португальська', en:'Portuguese', de:'Portugiesisch', fr:'Portugais', es:'Portugués', 'es-MX':'Portugués', it:'Portoghese', pt:'Português', ar:'البرتغالية', hi:'पुर्तगाली', ja:'ポルトガル語', ky:'Португалча', 'zh-Hant':'葡萄牙語' },
  ai_lng_ar: { bg:'Арабски', ru:'Арабский', uk:'Арабська', en:'Arabic', de:'Arabisch', fr:'Arabe', es:'Árabe', 'es-MX':'Árabe', it:'Arabo', pt:'Árabe', ar:'العربية', hi:'अरबी', ja:'アラビア語', ky:'Арапча', 'zh-Hant':'阿拉伯語' },
  ai_lng_hi: { bg:'Хинди', ru:'Хинди', uk:'Гінді', en:'Hindi', de:'Hindi', fr:'Hindi', es:'Hindi', 'es-MX':'Hindi', it:'Hindi', pt:'Hindi', ar:'الهندية', hi:'हिन्दी', ja:'ヒンディー語', ky:'Хиндче', 'zh-Hant':'印地語' },
  ai_lng_ja: { bg:'Японски', ru:'Японский', uk:'Японська', en:'Japanese', de:'Japanisch', fr:'Japonais', es:'Japonés', 'es-MX':'Japonés', it:'Giapponese', pt:'Japonês', ar:'اليابانية', hi:'जापानी', ja:'日本語', ky:'Жапончо', 'zh-Hant':'日語' },
  ai_lng_ky: { bg:'Киргизки', ru:'Киргизский', uk:'Киргизька', en:'Kyrgyz', de:'Kirgisisch', fr:'Kirghize', es:'Kirguís', 'es-MX':'Kirguís', it:'Kirghiso', pt:'Quirguiz', ar:'القيرغيزية', hi:'किर्गिज़', ja:'キルギス語', ky:'Кыргызча', 'zh-Hant':'吉爾吉斯語' },
  ai_lng_zh: { bg:'Китайски (традиционен)', ru:'Китайский (традиционный)', uk:'Китайська (традиційна)', en:'Chinese (Traditional)', de:'Chinesisch (traditionell)', fr:'Chinois (traditionnel)', es:'Chino (tradicional)', 'es-MX':'Chino (tradicional)', it:'Cinese (tradizionale)', pt:'Chinês (tradicional)', ar:'الصينية (التقليدية)', hi:'चीनी (पारंपरिक)', ja:'中国語（繁体字）', ky:'Кытайча (салттуу)', 'zh-Hant':'中文（繁體）' }
});

// Построява промпта за дадения режим (за превод — с избрания целеви език).
function buildPrompt(mode, raw, langName) {
  if (mode.id === 'translate') {
    return `Преведи следния текст на ${langName} език. Върни САМО превода — без оригинала, ` +
      `без обяснения и без кавички:\n\n${raw}`;
  }
  return mode.tpl(raw);
}

// Офлайн резерв по режим: „Напиши"/„Обясни"/„Преведи" → шаблон за известие с въведения текст
// като предмет (за „Преведи" — на целевия език); „Обобщи" → извличащо обобщение на устройството.
function offlineFallback(mode, raw, langCode) {
  if (mode.id === 'summarize') return offlineSummary(raw, 3);
  const lang = mode.id === 'translate' ? langCode : getLang();
  return offlineAnnouncement({ title: raw }, 'product', 'friendly', lang);
}

function esc(s) {
  return String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
}

export function render(root) {
  root.innerHTML = `
    <div class="tool-card">
      <label>${esc(t('ai_mode_label'))}</label>
      <select id="aiMode">
        ${MODES.map((m, i) => `<option value="${i}">${esc(t(m.labelKey))}</option>`).join('')}
      </select>
      <div id="aiLangRow" style="display:none">
        <label style="margin-top:12px">${esc(t('ai_translate_to'))}</label>
        <select id="aiLang">
          ${TARGET_LANGS.map((l, i) => `<option value="${i}">${esc(t(l.key))}</option>`).join('')}
        </select>
      </div>
      <label style="margin-top:12px">${esc(t('ai_prompt_label'))}</label>
      <textarea id="aiPrompt" rows="4" placeholder="${esc(t('ai_prompt_ph'))}"></textarea>
      <button class="btn" id="aiBtn">${esc(t('ai_btn_generate'))}</button>
      <button class="btn sec" id="aiCopy" style="display:none">${esc(t('ai_btn_copy'))}</button>
      <div class="status" id="aiStatus"></div>
      <div class="out-block" id="aiOut" style="display:none;white-space:pre-wrap"></div>
      <p class="hint" style="margin-top:10px">
        ${esc(t('ai_hint'))}
      </p>
    </div>
  `;

  const $ = (s) => root.querySelector(s);
  const statusEl = $('#aiStatus');
  const setStatus = (kind, msg) => { statusEl.className = 'status show ' + kind; statusEl.textContent = msg; };
  const hideStatus = () => { statusEl.className = 'status'; };

  let busy = false;

  async function generate() {
    if (busy) return;
    const raw = $('#aiPrompt').value.trim();
    if (!raw) { setStatus('err', t('ai_err_no_prompt')); return; }
    const mode = MODES[parseInt($('#aiMode').value, 10) || 0];
    const lang = TARGET_LANGS[parseInt($('#aiLang').value, 10) || 0] || TARGET_LANGS[0];
    const prompt = buildPrompt(mode, raw, lang.name);

    busy = true;
    const btn = $('#aiBtn');
    btn.disabled = true;
    $('#aiCopy').style.display = 'none';
    $('#aiOut').style.display = 'none';
    setStatus('work', t('ai_generating'));

    // Пряко → relay → офлайн резерв. Таймаут 20 с на стъпка (Promise.race, без AbortController).
    let answer = '', via = 'direct';
    try { const r = await askAI(prompt, 20000); answer = r.text; via = r.via; }
    catch (e) { answer = offlineFallback(mode, raw, lang.code); via = 'offline'; }
    if (via === 'direct') hideStatus(); else setStatus(via === 'offline' ? 'ok' : 'work', t('ai_via_' + via));
    const o = $('#aiOut');
    o.style.display = 'block';
    o.textContent = answer;
    $('#aiCopy').style.display = 'block';
    btn.disabled = false;
    busy = false;
  }

  // Полето за целеви език се показва само в режим „Преведи".
  const langRow = $('#aiLangRow');
  function syncLangRow() {
    const mode = MODES[parseInt($('#aiMode').value, 10) || 0];
    langRow.style.display = (mode && mode.id === 'translate') ? 'block' : 'none';
  }
  $('#aiMode').addEventListener('change', syncLangRow);
  syncLangRow();

  $('#aiBtn').addEventListener('click', generate);
  $('#aiCopy').addEventListener('click', async () => {
    const text = $('#aiOut').textContent;
    try {
      await navigator.clipboard.writeText(text);
      setStatus('ok', t('ai_copied'));
      setTimeout(hideStatus, 1500);
    } catch (_) {
      setStatus('err', t('ai_copy_denied'));
    }
  });
}
