// Version: 1.0015
// i18n.js — преводен слой за Pupikes Toolkit на 15-те езика. Дефолт руски.
import { LANGUAGES } from './languages.js';

const LS_KEY = 'servicestoolkit.lang';
const DEFAULT_LANG = 'ru';
const FALLBACK_LANG = 'en';
const RTL = ['ar'];

const STR = {
  pick_lang: { bg:'Избери език', ru:'Выберите язык', uk:'Виберіть мову', en:'Choose language', de:'Sprache wählen', fr:'Choisir la langue', es:'Elegir idioma', 'es-MX':'Elegir idioma', it:'Scegli la lingua', pt:'Escolher idioma', ar:'اختر اللغة', hi:'भाषा चुनें', ja:'言語を選択', ky:'Тилди тандаңыз', 'zh-Hant':'選擇語言' },
  lang_btn: { bg:'🌐 Език', ru:'🌐 Язык', uk:'🌐 Мова', en:'🌐 Language', de:'🌐 Sprache', fr:'🌐 Langue', es:'🌐 Idioma', 'es-MX':'🌐 Idioma', it:'🌐 Lingua', pt:'🌐 Idioma', ar:'🌐 اللغة', hi:'🌐 भाषा', ja:'🌐 言語', ky:'🌐 Тил', 'zh-Hant':'🌐 語言' },
  start_app: { bg:'Стартирай', ru:'Запустить', uk:'Запустити', en:'Start', de:'Starten', fr:'Démarrer', es:'Iniciar', 'es-MX':'Iniciar', it:'Avvia', pt:'Iniciar', ar:'ابدأ', hi:'शुरू करें', ja:'開始', ky:'Баштоо', 'zh-Hant':'開始' },
  home_sub: { bg:'Полезни офлайн инструменти — всичко работи на устройството.', ru:'Полезные офлайн-инструменты — всё работает на устройстве.', uk:'Корисні офлайн-інструменти — усе працює на пристрої.', en:'Handy offline tools — everything runs on your device.', de:'Praktische Offline-Tools — alles läuft auf dem Gerät.', fr:'Outils hors-ligne pratiques — tout fonctionne sur l’appareil.', es:'Útiles herramientas sin conexión — todo funciona en el dispositivo.', 'es-MX':'Útiles herramientas sin conexión — todo funciona en el dispositivo.', it:'Comodi strumenti offline — tutto gira sul dispositivo.', pt:'Ferramentas offline úteis — tudo roda no dispositivo.', ar:'أدوات مفيدة دون اتصال — كل شيء يعمل على جهازك.', hi:'उपयोगी ऑफ़लाइन टूल — सब कुछ डिवाइस पर चलता है।', ja:'便利なオフラインツール — すべて端末上で動作。', ky:'Пайдалуу оффлайн куралдар — баары түзмөктө иштейт.', 'zh-Hant':'實用的離線工具 — 一切都在裝置上執行。' },
  search_ph: { bg:'Търси инструмент…', ru:'Поиск инструмента…', uk:'Пошук інструмента…', en:'Search a tool…', de:'Werkzeug suchen…', fr:'Rechercher un outil…', es:'Buscar herramienta…', 'es-MX':'Buscar herramienta…', it:'Cerca uno strumento…', pt:'Buscar ferramenta…', ar:'ابحث عن أداة…', hi:'टूल खोजें…', ja:'ツールを検索…', ky:'Куралды издөө…', 'zh-Hant':'搜尋工具…' },
  no_matches: { bg:'Няма съвпадения.', ru:'Совпадений нет.', uk:'Збігів немає.', en:'No matches.', de:'Keine Treffer.', fr:'Aucun résultat.', es:'Sin coincidencias.', 'es-MX':'Sin coincidencias.', it:'Nessuna corrispondenza.', pt:'Sem correspondências.', ar:'لا نتائج.', hi:'कोई मिलान नहीं।', ja:'一致なし。', ky:'Дал келүү жок.', 'zh-Hant':'沒有相符項目。' },
  online_tag: { bg:'онлайн', ru:'онлайн', uk:'онлайн', en:'online', de:'online', fr:'en ligne', es:'en línea', 'es-MX':'en línea', it:'online', pt:'online', ar:'متصل', hi:'ऑनलाइन', ja:'オンライン', ky:'онлайн', 'zh-Hant':'線上' },
  back: { bg:'Назад', ru:'Назад', uk:'Назад', en:'Back', de:'Zurück', fr:'Retour', es:'Atrás', 'es-MX':'Atrás', it:'Indietro', pt:'Voltar', ar:'رجوع', hi:'वापस', ja:'戻る', ky:'Артка', 'zh-Hant':'返回' },
  loading: { bg:'Зареждам…', ru:'Загрузка…', uk:'Завантаження…', en:'Loading…', de:'Laden…', fr:'Chargement…', es:'Cargando…', 'es-MX':'Cargando…', it:'Caricamento…', pt:'Carregando…', ar:'جارٍ التحميل…', hi:'लोड हो रहा…', ja:'読み込み中…', ky:'Жүктөлүүдө…', 'zh-Hant':'載入中…' },
  load_error: { bg:'Грешка при зареждане на инструмента:', ru:'Ошибка загрузки инструмента:', uk:'Помилка завантаження інструмента:', en:'Error loading the tool:', de:'Fehler beim Laden des Werkzeugs:', fr:'Erreur de chargement de l’outil :', es:'Error al cargar la herramienta:', 'es-MX':'Error al cargar la herramienta:', it:'Errore nel caricamento dello strumento:', pt:'Erro ao carregar a ferramenta:', ar:'خطأ في تحميل الأداة:', hi:'टूल लोड करने में त्रुटि:', ja:'ツールの読み込みエラー:', ky:'Куралды жүктөөдө ката:', 'zh-Hant':'載入工具時發生錯誤：' },

  t_qr_name: { bg:'QR код', ru:'QR-код', uk:'QR-код', en:'QR code', de:'QR-Code', fr:'Code QR', es:'Código QR', 'es-MX':'Código QR', it:'Codice QR', pt:'Código QR', ar:'رمز QR', hi:'QR कोड', ja:'QRコード', ky:'QR код', 'zh-Hant':'QR 碼' },
  t_qr_desc: { bg:'Генерирай и разчети QR кодове', ru:'Создавай и сканируй QR-коды', uk:'Створюй і скануй QR-коди', en:'Generate and read QR codes', de:'QR-Codes erstellen und lesen', fr:'Générer et lire des codes QR', es:'Genera y lee códigos QR', 'es-MX':'Genera y lee códigos QR', it:'Genera e leggi codici QR', pt:'Gere e leia códigos QR', ar:'أنشئ واقرأ رموز QR', hi:'QR कोड बनाएं और पढ़ें', ja:'QRコードの生成と読み取り', ky:'QR коддорду түзүү жана окуу', 'zh-Hant':'產生與讀取 QR 碼' },
  t_pwcrypt_name: { bg:'Криптиране на текст', ru:'Шифрование текста', uk:'Шифрування тексту', en:'Text encryption', de:'Textverschlüsselung', fr:'Chiffrement de texte', es:'Cifrado de texto', 'es-MX':'Cifrado de texto', it:'Cifratura del testo', pt:'Cifragem de texto', ar:'تشفير النص', hi:'टेक्स्ट एन्क्रिप्शन', ja:'テキスト暗号化', ky:'Текстти шифрлөө', 'zh-Hant':'文字加密' },
  t_pwcrypt_desc: { bg:'AES-256-GCM с парола — прати криптиран текст навсякъде', ru:'AES-256-GCM с паролем — отправляйте зашифрованный текст куда угодно', uk:'AES-256-GCM з паролем — надсилайте зашифрований текст будь-куди', en:'AES-256-GCM with a password — send encrypted text anywhere', de:'AES-256-GCM mit Passwort — verschlüsselten Text überallhin senden', fr:'AES-256-GCM avec mot de passe — envoyez du texte chiffré partout', es:'AES-256-GCM con contraseña — envía texto cifrado a cualquier sitio', 'es-MX':'AES-256-GCM con contraseña — envía texto cifrado a cualquier lugar', it:'AES-256-GCM con password — invia testo cifrato ovunque', pt:'AES-256-GCM com palavra-passe — envie texto cifrado para qualquer lado', ar:'AES-256-GCM بكلمة مرور — أرسل نصاً مشفراً إلى أي مكان', hi:'पासवर्ड के साथ AES-256-GCM — एन्क्रिप्टेड टेक्स्ट कहीं भी भेजें', ja:'パスワード付きAES-256-GCM — 暗号化テキストをどこへでも', ky:'Сырсөз менен AES-256-GCM — шифрленген текстти каалаган жерге жөнөт', 'zh-Hant':'使用密碼的 AES-256-GCM — 將加密文字傳送到任何地方' },
  t_pwhash_name: { bg:'Хешове, кодиране, парола за сайт', ru:'Хеши, кодирование, пароль для сайта', uk:'Хеші, кодування, пароль для сайту', en:'Hashes, encoding, site password', de:'Hashes, Kodierung, Website-Passwort', fr:'Hachages, encodage, mot de passe de site', es:'Hashes, codificación, contraseña de sitio', 'es-MX':'Hashes, codificación, contraseña de sitio', it:'Hash, codifica, password per sito', pt:'Hashes, codificação, palavra-passe de site', ar:'تجزئة، ترميز، كلمة مرور للموقع', hi:'हैश, एन्कोडिंग, साइट पासवर्ड', ja:'ハッシュ・エンコード・サイト用パスワード', ky:'Хэш, коддоо, сайт үчүн сырсөз', 'zh-Hant':'雜湊、編碼、網站密碼' },
  t_pwhash_desc: { bg:'SHA-256/384/512, HMAC, Base64/Hex/URL, детерминирана парола от главна', ru:'SHA-256/384/512, HMAC, Base64/Hex/URL, детерминированный пароль из главного', uk:'SHA-256/384/512, HMAC, Base64/Hex/URL, детермінований пароль із головного', en:'SHA-256/384/512, HMAC, Base64/Hex/URL, deterministic password from a master', de:'SHA-256/384/512, HMAC, Base64/Hex/URL, deterministisches Passwort aus Master', fr:'SHA-256/384/512, HMAC, Base64/Hex/URL, mot de passe déterministe depuis un maître', es:'SHA-256/384/512, HMAC, Base64/Hex/URL, contraseña determinista desde una maestra', 'es-MX':'SHA-256/384/512, HMAC, Base64/Hex/URL, contraseña determinista desde una maestra', it:'SHA-256/384/512, HMAC, Base64/Hex/URL, password deterministica da una principale', pt:'SHA-256/384/512, HMAC, Base64/Hex/URL, palavra-passe determinística a partir de uma mestra', ar:'SHA-256/384/512، HMAC، Base64/Hex/URL، كلمة مرور حتمية من رئيسية', hi:'SHA-256/384/512, HMAC, Base64/Hex/URL, मास्टर से निश्चित पासवर्ड', ja:'SHA-256/384/512、HMAC、Base64/Hex/URL、マスターからの決定的パスワード', ky:'SHA-256/384/512, HMAC, Base64/Hex/URL, башкыдан детерминдик сырсөз', 'zh-Hant':'SHA-256/384/512、HMAC、Base64/Hex/URL、由主密碼決定的密碼' },
  t_pwbrowsers_name: { bg:'Пароли от браузъри', ru:'Пароли из браузеров', uk:'Паролі з браузерів', en:'Browser passwords', de:'Browser-Passwörter', fr:'Mots de passe des navigateurs', es:'Contraseñas de navegadores', 'es-MX':'Contraseñas de navegadores', it:'Password dei browser', pt:'Palavras-passe dos browsers', ar:'كلمات مرور المتصفحات', hi:'ब्राउज़र पासवर्ड', ja:'ブラウザのパスワード', ky:'Браузер сырсөздөрү', 'zh-Hant':'瀏覽器密碼' },
  t_pwbrowsers_desc: { bg:'Износ/внос по табове (телефон/компютър, 7 браузъра) + проверка на CSV', ru:'Экспорт/импорт по вкладкам (телефон/компьютер, 7 браузеров) + проверка CSV', uk:'Експорт/імпорт за вкладками (телефон/комп’ютер, 7 браузерів) + перевірка CSV', en:'Export/import by tabs (phone/computer, 7 browsers) + CSV check', de:'Export/Import nach Tabs (Telefon/Computer, 7 Browser) + CSV-Prüfung', fr:'Export/import par onglets (téléphone/ordinateur, 7 navigateurs) + vérification CSV', es:'Exportar/importar por pestañas (teléfono/ordenador, 7 navegadores) + comprobación CSV', 'es-MX':'Exportar/importar por pestañas (teléfono/computadora, 7 navegadores) + comprobación CSV', it:'Esporta/importa per schede (telefono/computer, 7 browser) + verifica CSV', pt:'Exportar/importar por separadores (telemóvel/computador, 7 browsers) + verificação CSV', ar:'تصدير/استيراد حسب التبويبات (هاتف/حاسوب، 7 متصفحات) + فحص CSV', hi:'टैब से निर्यात/आयात (फ़ोन/कंप्यूटर, 7 ब्राउज़र) + CSV जाँच', ja:'タブ別エクスポート/インポート（スマホ/PC、7ブラウザ）＋CSV検査', ky:'Табдар боюнча экспорт/импорт (телефон/компьютер, 7 браузер) + CSV текшерүү', 'zh-Hant':'依分頁匯出/匯入（手機/電腦，7 種瀏覽器）＋CSV 檢查' },
  t_pwfaq_name: { bg:'FAQ: забравена парола / ключ / ключалка', ru:'FAQ: забытый пароль / ключ / замок', uk:'FAQ: забутий пароль / ключ / замок', en:'FAQ: forgotten password / key / lock', de:'FAQ: Passwort / Schlüssel / Schloss vergessen', fr:'FAQ : mot de passe / clé / cadenas oublié', es:'FAQ: contraseña / llave / cerradura olvidada', 'es-MX':'FAQ: contraseña / llave / cerradura olvidada', it:'FAQ: password / chiave / lucchetto dimenticati', pt:'FAQ: palavra-passe / chave / cadeado esquecidos', ar:'الأسئلة الشائعة: نسيت كلمة المرور / المفتاح / القفل', hi:'FAQ: भूला पासवर्ड / चाबी / ताला', ja:'FAQ：パスワード・鍵・ロックを忘れた', ky:'FAQ: унутулган сырсөз / ачкыч / кулпу', 'zh-Hant':'FAQ：忘記密碼／鑰匙／鎖' },
  t_pwfaq_desc: { bg:'Законни начини за възстановяване: официални източници + най-новото от мрежата (с линк)', ru:'Законные способы восстановления: официальные источники + свежее из сети (со ссылкой)', uk:'Законні способи відновлення: офіційні джерела + найновіше з мережі (з посиланням)', en:'Lawful recovery: official sources + latest from the web (with links)', de:'Legale Wiederherstellung: offizielle Quellen + Neues aus dem Netz (mit Links)', fr:'Récupération légale : sources officielles + nouveautés du web (avec liens)', es:'Recuperación legal: fuentes oficiales + lo último de la web (con enlaces)', 'es-MX':'Recuperación legal: fuentes oficiales + lo último de la web (con enlaces)', it:'Recupero legale: fonti ufficiali + novità dal web (con link)', pt:'Recuperação legal: fontes oficiais + o mais recente da web (com ligações)', ar:'استرداد قانوني: مصادر رسمية + الأحدث من الويب (مع روابط)', hi:'वैध रिकवरी: आधिकारिक स्रोत + वेब से ताज़ा (लिंक सहित)', ja:'合法的な復旧：公式ソース＋ウェブ最新（リンク付き）', ky:'Мыйзамдуу калыбына келтирүү: расмий булактар + тармактан жаңылары (шилтеме менен)', 'zh-Hant':'合法恢復：官方來源＋網路最新（附連結）' },
  t_pwstr_name: { bg:'Анализатор на пароли', ru:'Анализатор паролей', uk:'Аналізатор паролів', en:'Password analyzer', de:'Passwort-Analyse', fr:'Analyseur de mots de passe', es:'Analizador de contraseñas', 'es-MX':'Analizador de contraseñas', it:'Analizzatore password', pt:'Analisador de palavras-passe', ar:'محلل كلمات المرور', hi:'पासवर्ड विश्लेषक', ja:'パスワード分析', ky:'Сырсөз анализатору', 'zh-Hant':'密碼分析器' },
  t_pwstr_desc: { bg:'Ентропия, време за разбиване, слабости, проверка в изтекли бази', ru:'Энтропия, время взлома, слабости, проверка в утечках', uk:'Ентропія, час злому, слабкості, перевірка у витоках', en:'Entropy, crack time, weaknesses, leak check', de:'Entropie, Knackzeit, Schwächen, Leak-Prüfung', fr:'Entropie, temps de cassage, faiblesses, fuites', es:'Entropía, tiempo de descifrado, debilidades, filtraciones', 'es-MX':'Entropía, tiempo de descifrado, debilidades, filtraciones', it:'Entropia, tempo di cracking, debolezze, violazioni', pt:'Entropia, tempo de quebra, fraquezas, fugas', ar:'الإنتروبيا، زمن الكسر، نقاط الضعف، فحص التسريبات', hi:'एन्ट्रॉपी, क्रैक समय, कमज़ोरियाँ, लीक जाँच', ja:'エントロピー、解読時間、弱点、漏洩確認', ky:'Энтропия, бузуу убактысы, алсыздыктар, агып кетүү текшерүү', 'zh-Hant':'熵、破解時間、弱點、外洩檢查' },
  t_pwphr_name: { bg:'Парола-фраза', ru:'Парольная фраза', uk:'Парольна фраза', en:'Passphrase', de:'Passphrase', fr:'Phrase de passe', es:'Frase de contraseña', 'es-MX':'Frase de contraseña', it:'Passphrase', pt:'Frase-passe', ar:'عبارة مرور', hi:'पासफ़्रेज़', ja:'パスフレーズ', ky:'Сырсөз-фраза', 'zh-Hant':'密語' },
  t_pwphr_desc: { bg:'Случайни думи на 6 езика — лесна за помнене, много силна', ru:'Случайные слова на 6 языках — легко запомнить, очень надёжно', uk:'Випадкові слова 6 мовами — легко запам’ятати, дуже надійно', en:'Random words in 6 languages — memorable and very strong', de:'Zufallswörter in 6 Sprachen — merkbar und sehr stark', fr:'Mots aléatoires en 6 langues — mémorisable et très forte', es:'Palabras aleatorias en 6 idiomas — fácil de recordar y muy fuerte', 'es-MX':'Palabras aleatorias en 6 idiomas — fácil de recordar y muy fuerte', it:'Parole casuali in 6 lingue — memorabile e molto forte', pt:'Palavras aleatórias em 6 idiomas — memorável e muito forte', ar:'كلمات عشوائية بـ6 لغات — سهلة التذكر وقوية جداً', hi:'6 भाषाओं में यादृच्छिक शब्द — याद रखने योग्य और बहुत मज़बूत', ja:'6言語のランダム単語 — 覚えやすく非常に強力', ky:'6 тилде кокус сөздөр — эстөө оңой, абдан күчтүү', 'zh-Hant':'6 種語言的隨機單字 — 好記且非常強' },
  t_pwbulk_name: { bg:'Пакетни пароли + политика', ru:'Пакет паролей + политика', uk:'Пакет паролів + політика', en:'Bulk passwords + policy', de:'Passwort-Stapel + Richtlinie', fr:'Mots de passe en lot + politique', es:'Contraseñas en lote + política', 'es-MX':'Contraseñas en lote + política', it:'Password in blocco + policy', pt:'Palavras-passe em lote + política', ar:'كلمات مرور بالجملة + سياسة', hi:'बल्क पासवर्ड + नीति', ja:'一括パスワード＋ポリシー', ky:'Топтоп сырсөздөр + саясат', 'zh-Hant':'批次密碼＋政策' },
  t_pwbulk_desc: { bg:'До 100 пароли по правила, проверени, износ CSV', ru:'До 100 паролей по правилам, проверены, экспорт CSV', uk:'До 100 паролів за правилами, перевірені, експорт CSV', en:'Up to 100 passwords by policy, checked, CSV export', de:'Bis zu 100 Passwörter nach Richtlinie, geprüft, CSV-Export', fr:'Jusqu’à 100 mots de passe selon une politique, vérifiés, export CSV', es:'Hasta 100 contraseñas por política, comprobadas, exportación CSV', 'es-MX':'Hasta 100 contraseñas por política, comprobadas, exportación CSV', it:'Fino a 100 password per policy, verificate, esportazione CSV', pt:'Até 100 palavras-passe por política, verificadas, exportação CSV', ar:'حتى 100 كلمة مرور وفق سياسة، مفحوصة، تصدير CSV', hi:'नीति के अनुसार 100 तक पासवर्ड, जाँचे हुए, CSV निर्यात', ja:'ポリシーに沿って最大100件、チェック済み、CSV出力', ky:'Саясат боюнча 100гө чейин сырсөз, текшерилген, CSV экспорт', 'zh-Hant':'依政策最多 100 組密碼，已檢查，匯出 CSV' },
  t_password_name: { bg:'Генератор на пароли', ru:'Генератор паролей', uk:'Генератор паролів', en:'Password generator', de:'Passwortgenerator', fr:'Générateur de mots de passe', es:'Generador de contraseñas', 'es-MX':'Generador de contraseñas', it:'Generatore di password', pt:'Gerador de senhas', ar:'مولّد كلمات المرور', hi:'पासवर्ड जेनरेटर', ja:'パスワード生成', ky:'Сырсөз генератору', 'zh-Hant':'密碼產生器' },
  t_password_desc: { bg:'Силни пароли с 9 метода', ru:'Надёжные пароли, 9 методов', uk:'Надійні паролі, 9 методів', en:'Strong passwords, 9 methods', de:'Starke Passwörter, 9 Methoden', fr:'Mots de passe forts, 9 méthodes', es:'Contraseñas fuertes, 9 métodos', 'es-MX':'Contraseñas fuertes, 9 métodos', it:'Password forti, 9 metodi', pt:'Senhas fortes, 9 métodos', ar:'كلمات مرور قوية، ٤ طرق', hi:'मज़बूत पासवर्ड, 9 तरीके', ja:'強力なパスワード・9方式', ky:'Күчтүү сырсөздөр, 9 ыкма', 'zh-Hant':'強密碼，9 種方式' },
  t_calc_name: { bg:'Калкулатори', ru:'Калькуляторы', uk:'Калькулятори', en:'Calculators', de:'Rechner', fr:'Calculatrices', es:'Calculadoras', 'es-MX':'Calculadoras', it:'Calcolatrici', pt:'Calculadoras', ar:'حاسبات', hi:'कैलकुलेटर', ja:'計算ツール', ky:'Эсептегичтер', 'zh-Hant':'計算機' },
  t_calc_desc: { bg:'Заем, ДДС, лихва, проценти', ru:'Кредит, НДС, проценты', uk:'Кредит, ПДВ, відсотки', en:'Loan, VAT, interest, percentages', de:'Kredit, MwSt., Zinsen, Prozente', fr:'Prêt, TVA, intérêts, pourcentages', es:'Préstamo, IVA, interés, porcentajes', 'es-MX':'Préstamo, IVA, interés, porcentajes', it:'Prestito, IVA, interessi, percentuali', pt:'Empréstimo, IVA, juros, percentagens', ar:'قرض، ضريبة، فائدة، نسب', hi:'ऋण, वैट, ब्याज, प्रतिशत', ja:'ローン・税・利息・割合', ky:'Насыя, КНС, пайыз', 'zh-Hant':'貸款、增值稅、利息、百分比' },
  t_text_name: { bg:'Текстови инструменти', ru:'Текстовые инструменты', uk:'Текстові інструменти', en:'Text tools', de:'Text-Werkzeuge', fr:'Outils de texte', es:'Herramientas de texto', 'es-MX':'Herramientas de texto', it:'Strumenti di testo', pt:'Ferramentas de texto', ar:'أدوات النصوص', hi:'टेक्स्ट टूल', ja:'テキストツール', ky:'Текст куралдары', 'zh-Hant':'文字工具' },
  t_text_desc: { bg:'Брояч, форматиране, Base64', ru:'Счётчик, форматирование, Base64', uk:'Лічильник, форматування, Base64', en:'Counter, formatting, Base64', de:'Zähler, Formatierung, Base64', fr:'Compteur, mise en forme, Base64', es:'Contador, formato, Base64', 'es-MX':'Contador, formato, Base64', it:'Contatore, formattazione, Base64', pt:'Contador, formatação, Base64', ar:'عدّاد، تنسيق، Base64', hi:'काउंटर, फ़ॉर्मेटिंग, Base64', ja:'カウント・整形・Base64', ky:'Эсептегич, форматтоо, Base64', 'zh-Hant':'計數、格式化、Base64' },
  t_image_name: { bg:'Компресор на снимки', ru:'Сжатие изображений', uk:'Стиснення зображень', en:'Image compressor', de:'Bildkompressor', fr:'Compresseur d’images', es:'Compresor de imágenes', 'es-MX':'Compresor de imágenes', it:'Compressore immagini', pt:'Compressor de imagens', ar:'ضاغط الصور', hi:'इमेज कंप्रेसर', ja:'画像圧縮', ky:'Сүрөт кысуу', 'zh-Hant':'圖片壓縮' },
  t_image_desc: { bg:'Намали JPEG / PNG / WebP', ru:'Уменьши JPEG / PNG / WebP', uk:'Зменши JPEG / PNG / WebP', en:'Shrink JPEG / PNG / WebP', de:'JPEG / PNG / WebP verkleinern', fr:'Réduire JPEG / PNG / WebP', es:'Reduce JPEG / PNG / WebP', 'es-MX':'Reduce JPEG / PNG / WebP', it:'Riduci JPEG / PNG / WebP', pt:'Reduza JPEG / PNG / WebP', ar:'صغّر JPEG / PNG / WebP', hi:'JPEG / PNG / WebP छोटा करें', ja:'JPEG / PNG / WebP を縮小', ky:'JPEG / PNG / WebP кичирейтүү', 'zh-Hant':'縮小 JPEG / PNG / WebP' },
  t_pdf_name: { bg:'PDF инструменти', ru:'PDF-инструменты', uk:'PDF-інструменти', en:'PDF tools', de:'PDF-Werkzeuge', fr:'Outils PDF', es:'Herramientas PDF', 'es-MX':'Herramientas PDF', it:'Strumenti PDF', pt:'Ferramentas PDF', ar:'أدوات PDF', hi:'PDF टूल', ja:'PDFツール', ky:'PDF куралдары', 'zh-Hant':'PDF 工具' },
  t_pdf_desc: { bg:'Сливане, разделяне, воден знак', ru:'Объединение, разделение, водяной знак', uk:'Об’єднання, поділ, водяний знак', en:'Merge, split, watermark', de:'Zusammenführen, teilen, Wasserzeichen', fr:'Fusionner, diviser, filigrane', es:'Unir, dividir, marca de agua', 'es-MX':'Unir, dividir, marca de agua', it:'Unisci, dividi, filigrana', pt:'Juntar, dividir, marca d’água', ar:'دمج، تقسيم، علامة مائية', hi:'मर्ज, विभाजन, वॉटरमार्क', ja:'結合・分割・透かし', ky:'Бириктирүү, бөлүү, суу белгиси', 'zh-Hant':'合併、分割、浮水印' },
  t_pdfc_name: { bg:'Свиване на PDF', ru:'Сжатие PDF', uk:'Стиснення PDF', en:'PDF compress', de:'PDF komprimieren', fr:'Compresser PDF', es:'Comprimir PDF', 'es-MX':'Comprimir PDF', it:'Comprimi PDF', pt:'Comprimir PDF', ar:'ضغط PDF', hi:'PDF संपीड़न', ja:'PDF圧縮', ky:'PDF кысуу', 'zh-Hant':'PDF 壓縮' },
  t_pdfc_desc: { bg:'Растеризира страниците за по-малък размер', ru:'Растрирует страницы для меньшего размера', uk:'Растеризує сторінки для меншого розміру', en:'Rasterizes pages for a smaller size', de:'Rastert Seiten für kleinere Größe', fr:'Rastérise les pages pour réduire la taille', es:'Rasteriza páginas para reducir tamaño', 'es-MX':'Rasteriza páginas para reducir tamaño', it:'Rasterizza le pagine per ridurre la dimensione', pt:'Rasteriza páginas para reduzir o tamanho', ar:'يحوّل الصفحات إلى صور لتصغير الحجم', hi:'छोटे आकार हेतु पेज रास्टराइज़ करता है', ja:'ページをラスタライズして縮小', ky:'Барактарды кичирейтүү үчүн растрлайт', 'zh-Hant':'點陣化頁面以縮小體積' },
  t_crypto_name: { bg:'Крипто графики', ru:'Крипто-графики', uk:'Крипто-графіки', en:'Crypto charts', de:'Krypto-Charts', fr:'Graphiques crypto', es:'Gráficos cripto', 'es-MX':'Gráficos cripto', it:'Grafici cripto', pt:'Gráficos cripto', ar:'مخططات الكريبتو', hi:'क्रिप्टो चार्ट', ja:'暗号資産チャート', ky:'Крипто графиктер', 'zh-Hant':'加密貨幣圖表' },
  t_crypto_desc: { bg:'RSI, Fibonacci, BTC/ETH по периоди (Binance/CoinGecko)', ru:'RSI, Фибоначчи, BTC/ETH по периодам (Binance/CoinGecko)', uk:'RSI, Фібоначчі, BTC/ETH за періоди (Binance/CoinGecko)', en:'RSI, Fibonacci, BTC/ETH over periods (Binance/CoinGecko)', de:'RSI, Fibonacci, BTC/ETH über Zeiträume (Binance/CoinGecko)', fr:'RSI, Fibonacci, BTC/ETH par périodes (Binance/CoinGecko)', es:'RSI, Fibonacci, BTC/ETH por periodos (Binance/CoinGecko)', 'es-MX':'RSI, Fibonacci, BTC/ETH por periodos (Binance/CoinGecko)', it:'RSI, Fibonacci, BTC/ETH per periodi (Binance/CoinGecko)', pt:'RSI, Fibonacci, BTC/ETH por períodos (Binance/CoinGecko)', ar:'RSI، فيبوناتشي، BTC/ETH عبر الفترات (Binance/CoinGecko)', hi:'RSI, फिबोनाची, BTC/ETH अवधि अनुसार (Binance/CoinGecko)', ja:'RSI・フィボナッチ・BTC/ETH 期間別（Binance/CoinGecko）', ky:'RSI, Фибоначчи, BTC/ETH мезгилдер боюнча (Binance/CoinGecko)', 'zh-Hant':'RSI、費波那契、BTC/ETH 各週期（Binance/CoinGecko）' },
  t_fx_name: { bg:'Валутни курсове', ru:'Курсы валют', uk:'Курси валют', en:'Currency rates', de:'Wechselkurse', fr:'Taux de change', es:'Tipos de cambio', 'es-MX':'Tipos de cambio', it:'Tassi di cambio', pt:'Taxas de câmbio', ar:'أسعار العملات', hi:'मुद्रा दरें', ja:'為替レート', ky:'Валюта курстары', 'zh-Hant':'匯率' },
  t_fx_desc: { bg:'Конвертор и курсове на живо', ru:'Конвертер и курсы в реальном времени', uk:'Конвертер і курси в реальному часі', en:'Converter and live rates', de:'Umrechner und Live-Kurse', fr:'Convertisseur et taux en direct', es:'Conversor y tasas en vivo', 'es-MX':'Conversor y tasas en vivo', it:'Convertitore e tassi live', pt:'Conversor e taxas ao vivo', ar:'محوّل وأسعار حية', hi:'कन्वर्टर और लाइव दरें', ja:'コンバーターとライブレート', ky:'Конвертер жана түз курстар', 'zh-Hant':'換算器與即時匯率' },
  t_auth_name: { bg:'Authenticator (2FA)', ru:'Authenticator (2FA)', uk:'Authenticator (2FA)', en:'Authenticator (2FA)', de:'Authenticator (2FA)', fr:'Authenticator (2FA)', es:'Authenticator (2FA)', 'es-MX':'Authenticator (2FA)', it:'Authenticator (2FA)', pt:'Authenticator (2FA)', ar:'Authenticator (2FA)', hi:'Authenticator (2FA)', ja:'Authenticator (2FA)', ky:'Authenticator (2FA)', 'zh-Hant':'Authenticator (2FA)' },
  t_auth_desc: { bg:'2FA кодове, пароли, портфейли — шифриран сейф', ru:'2FA-коды, пароли, кошельки — шифрованное хранилище', uk:'2FA-коди, паролі, гаманці — шифроване сховище', en:'2FA codes, passwords, wallets — encrypted vault', de:'2FA-Codes, Passwörter, Wallets — verschlüsselter Tresor', fr:'Codes 2FA, mots de passe, portefeuilles — coffre chiffré', es:'Códigos 2FA, contraseñas, carteras — bóveda cifrada', 'es-MX':'Códigos 2FA, contraseñas, carteras — bóveda cifrada', it:'Codici 2FA, password, portafogli — cassaforte cifrata', pt:'Códigos 2FA, senhas, carteiras — cofre cifrado', ar:'رموز 2FA وكلمات مرور ومحافظ — خزنة مشفّرة', hi:'2FA कोड, पासवर्ड, वॉलेट — एन्क्रिप्टेड वॉल्ट', ja:'2FAコード・パスワード・ウォレット — 暗号化保管庫', ky:'2FA коддор, сырсөздөр, капчыктар — шифрленген сейф', 'zh-Hant':'2FA 代碼、密碼、錢包 — 加密保險庫' },
  t_vid_name: { bg:'Видео конвертор', ru:'Видео конвертер', uk:'Відео конвертер', en:'Video converter', de:'Video-Konverter', fr:'Convertisseur vidéo', es:'Conversor de vídeo', 'es-MX':'Conversor de video', it:'Convertitore video', pt:'Conversor de vídeo', ar:'محوّل الفيديو', hi:'वीडियो कन्वर्टर', ja:'動画コンバーター', ky:'Видео конвертер', 'zh-Hant':'影片轉換器' },
  t_vid_desc: { bg:'MP4 ↔ WebM / AVI / MOV / MKV / GIF, на устройството', ru:'MP4 ↔ WebM / AVI / MOV / MKV / GIF, на устройстве', uk:'MP4 ↔ WebM / AVI / MOV / MKV / GIF, на пристрої', en:'MP4 ↔ WebM / AVI / MOV / MKV / GIF, on-device', de:'MP4 ↔ WebM / AVI / MOV / MKV / GIF, auf dem Gerät', fr:'MP4 ↔ WebM / AVI / MOV / MKV / GIF, sur l’appareil', es:'MP4 ↔ WebM / AVI / MOV / MKV / GIF, en el dispositivo', 'es-MX':'MP4 ↔ WebM / AVI / MOV / MKV / GIF, en el dispositivo', it:'MP4 ↔ WebM / AVI / MOV / MKV / GIF, sul dispositivo', pt:'MP4 ↔ WebM / AVI / MOV / MKV / GIF, no aparelho', ar:'MP4 ↔ WebM / AVI / MOV / MKV / GIF، على الجهاز', hi:'MP4 ↔ WebM / AVI / MOV / MKV / GIF, डिवाइस पर', ja:'MP4 ↔ WebM / AVI / MOV / MKV / GIF、端末内で', ky:'MP4 ↔ WebM / AVI / MOV / MKV / GIF, түзмөктө', 'zh-Hant':'MP4 ↔ WebM / AVI / MOV / MKV / GIF，於裝置上' },
  t_snd_name: { bg:'Звуков конвертор', ru:'Аудио конвертер', uk:'Аудіо конвертер', en:'Sound converter', de:'Audio-Konverter', fr:'Convertisseur audio', es:'Conversor de sonido', 'es-MX':'Conversor de sonido', it:'Convertitore audio', pt:'Conversor de áudio', ar:'محوّل الصوت', hi:'साउंड कन्वर्टर', ja:'音声コンバーター', ky:'Аудио конвертер', 'zh-Hant':'音訊轉換器' },
  t_snd_desc: { bg:'Телефонни звукови формати → MP4 / MP3 / WAV / OGG', ru:'Телефонные аудиоформаты → MP4 / MP3 / WAV / OGG', uk:'Телефонні аудіоформати → MP4 / MP3 / WAV / OGG', en:'Phone audio formats → MP4 / MP3 / WAV / OGG', de:'Telefon-Audioformate → MP4 / MP3 / WAV / OGG', fr:'Formats audio du téléphone → MP4 / MP3 / WAV / OGG', es:'Formatos de audio del teléfono → MP4 / MP3 / WAV / OGG', 'es-MX':'Formatos de audio del teléfono → MP4 / MP3 / WAV / OGG', it:'Formati audio del telefono → MP4 / MP3 / WAV / OGG', pt:'Formatos de áudio do telefone → MP4 / MP3 / WAV / OGG', ar:'صيغ صوت الهاتف ← MP4 / MP3 / WAV / OGG', hi:'फ़ोन ऑडियो फ़ॉर्मेट → MP4 / MP3 / WAV / OGG', ja:'電話の音声フォーマット → MP4 / MP3 / WAV / OGG', ky:'Телефон аудио форматтары → MP4 / MP3 / WAV / OGG', 'zh-Hant':'手機音訊格式 → MP4 / MP3 / WAV / OGG' },
  t_pdfd_name: { bg:'PDF към Word', ru:'PDF в Word', uk:'PDF у Word', en:'PDF to Word', de:'PDF zu Word', fr:'PDF vers Word', es:'PDF a Word', 'es-MX':'PDF a Word', it:'Da PDF a Word', pt:'PDF para Word', ar:'PDF إلى Word', hi:'PDF से Word', ja:'PDF から Word', ky:'PDF → Word', 'zh-Hant':'PDF 轉 Word' },
  t_pdfd_desc: { bg:'Извлича текста и прави .docx файл', ru:'Извлекает текст и создаёт файл .docx', uk:'Витягує текст і створює файл .docx', en:'Extracts the text into a .docx file', de:'Extrahiert den Text in eine .docx-Datei', fr:'Extrait le texte vers un fichier .docx', es:'Extrae el texto a un archivo .docx', 'es-MX':'Extrae el texto a un archivo .docx', it:'Estrae il testo in un file .docx', pt:'Extrai o texto para um arquivo .docx', ar:'يستخرج النص إلى ملف ‎.docx', hi:'टेक्स्ट निकालकर .docx फ़ाइल बनाता है', ja:'テキストを .docx に抽出', ky:'Текстти .docx файлга чыгарат', 'zh-Hant':'將文字擷取為 .docx 檔' },
  t_pw_name: { bg:'Price Watch — следи цени', ru:'Price Watch — следи за ценами', uk:'Price Watch — стеж за цінами', en:'Price Watch — track prices', de:'Price Watch — Preise beobachten', fr:'Price Watch — suivre les prix', es:'Price Watch — vigila precios', 'es-MX':'Price Watch — vigila precios', it:'Price Watch — monitora i prezzi', pt:'Price Watch — acompanhe preços', ar:'Price Watch — راقب الأسعار', hi:'Price Watch — कीमतें देखें', ja:'Price Watch — 価格を監視', ky:'Price Watch — бааларды байкоо', 'zh-Hant':'Price Watch — 追蹤價格' },
  t_pw_desc: { bg:'Прагове на крипто/валути с известия', ru:'Пороги на крипто/валюты с уведомлениями', uk:'Пороги на крипто/валюти зі сповіщеннями', en:'Crypto/currency thresholds with alerts', de:'Krypto-/Währungsschwellen mit Alarmen', fr:'Seuils crypto/devises avec alertes', es:'Umbrales cripto/divisas con avisos', 'es-MX':'Umbrales cripto/divisas con avisos', it:'Soglie cripto/valute con avvisi', pt:'Limites cripto/moedas com alertas', ar:'حدود للكريبتو/العملات مع تنبيهات', hi:'क्रिप्टो/मुद्रा सीमाएं और सूचनाएं', ja:'暗号資産・通貨のしきい値と通知', ky:'Крипто/валюта чектери жана билдирүүлөр', 'zh-Hant':'加密貨幣／貨幣門檻與通知' },
  t_watch20_name: { bg:'Наблюдавай 20 валути', ru:'Следи за 20 валютами', uk:'Стеж за 20 валютами', en:'Watch 20 currencies', de:'20 Währungen beobachten', fr:'Surveiller 20 devises', es:'Vigila 20 monedas', 'es-MX':'Vigila 20 monedas', it:'Monitora 20 valute', pt:'Acompanhe 20 moedas', ar:'راقب ٢٠ عملة', hi:'20 मुद्राएं देखें', ja:'20通貨を監視', ky:'20 валютаны байкоо', 'zh-Hant':'監看 20 種貨幣' },
  t_watch20_desc: { bg:'Прагове с известие и звук за до 20 двойки', ru:'Пороги с уведомлением и звуком до 20 пар', uk:'Пороги зі сповіщенням і звуком до 20 пар', en:'Alert + sound thresholds for up to 20 pairs', de:'Schwellen mit Hinweis und Ton für bis zu 20 Paare', fr:'Seuils avec alerte et son pour 20 paires', es:'Umbrales con aviso y sonido para hasta 20 pares', 'es-MX':'Umbrales con aviso y sonido para hasta 20 pares', it:'Soglie con avviso e suono fino a 20 coppie', pt:'Limiares com aviso e som para até 20 pares', ar:'حدود مع تنبيه وصوت حتى ٢٠ زوجًا', hi:'20 जोड़ियों तक अलर्ट + ध्वनि सीमाएं', ja:'最大20ペアの通知・音しきい値', ky:'20 жупка чейин эскертүү жана үн чеги', 'zh-Hant':'最多 20 組的提醒與聲音門檻' },
  t_scraper_name: { bg:'Web скрапер', ru:'Веб-скрапер', uk:'Веб-скрапер', en:'Web scraper', de:'Web-Scraper', fr:'Scraper web', es:'Web scraper', 'es-MX':'Web scraper', it:'Web scraper', pt:'Web scraper', ar:'كاشط ويب', hi:'वेब स्क्रैपर', ja:'ウェブスクレイパー', ky:'Веб скрапер', 'zh-Hant':'網頁擷取器' },
  t_scraper_desc: { bg:'Извличане на заглавие/текст/връзки', ru:'Извлечение заголовка/текста/ссылок', uk:'Витяг заголовка/тексту/посилань', en:'Extract title/text/links', de:'Titel/Text/Links extrahieren', fr:'Extraire titre/texte/liens', es:'Extraer título/texto/enlaces', 'es-MX':'Extraer título/texto/enlaces', it:'Estrai titolo/testo/link', pt:'Extrair título/texto/links', ar:'استخراج العنوان/النص/الروابط', hi:'शीर्षक/टेक्स्ट/लिंक निकालें', ja:'タイトル/本文/リンクを抽出', ky:'Аталыш/текст/шилтемелерди алуу', 'zh-Hant':'擷取標題／文字／連結' },
  t_ai_name: { bg:'AI генератор на текст', ru:'AI-генератор текста', uk:'AI-генератор тексту', en:'AI text generator', de:'KI-Textgenerator', fr:'Générateur de texte IA', es:'Generador de texto IA', 'es-MX':'Generador de texto IA', it:'Generatore di testo IA', pt:'Gerador de texto IA', ar:'مولّد نصوص بالذكاء الاصطناعي', hi:'AI टेक्स्ट जेनरेटर', ja:'AIテキスト生成', ky:'AI текст генератору', 'zh-Hant':'AI 文字產生器' },
  t_ai_desc: { bg:'Пиши, обобщавай, превеждай (безплатно)', ru:'Пиши, обобщай, переводи (бесплатно)', uk:'Пиши, узагальнюй, перекладай (безкоштовно)', en:'Write, summarize, translate (free)', de:'Schreiben, zusammenfassen, übersetzen (gratis)', fr:'Écrire, résumer, traduire (gratuit)', es:'Escribe, resume, traduce (gratis)', 'es-MX':'Escribe, resume, traduce (gratis)', it:'Scrivi, riassumi, traduci (gratis)', pt:'Escreva, resuma, traduza (grátis)', ar:'اكتب، لخّص، ترجم (مجانًا)', hi:'लिखें, सारांश, अनुवाद (मुफ़्त)', ja:'作成・要約・翻訳（無料）', ky:'Жаз, жыйынтыкта, котор (акысыз)', 'zh-Hant':'撰寫、摘要、翻譯（免費）' }
};

let current = detect();
// Език по локала на устройството (навигатора) → наш код от 15-те; '' ако няма съвпадение.
function deviceLang() {
  var SUP = ['bg','ru','uk','en','de','fr','es','es-MX','it','pt','ar','hi','ja','ky','zh-Hant'];
  function pick(tag) {
    if (!tag) return ''; var low = String(tag).toLowerCase();
    if (low.indexOf('zh') === 0) return 'zh-Hant';           // наличен е само традиционен китайски
    if (low.indexOf('pt') === 0) return 'pt';
    if (low.indexOf('es') === 0) return (low.indexOf('mx') > -1 || low.indexOf('419') > -1 || low.indexOf('us') > -1) ? 'es-MX' : 'es';
    var two = low.slice(0, 2);
    for (var i = 0; i < SUP.length; i++) if (SUP[i] === two) return SUP[i];
    return '';
  }
  try {
    var arr = (navigator.languages && navigator.languages.length) ? navigator.languages : [navigator.language || navigator.userLanguage || navigator.browserLanguage || ''];
    for (var i = 0; i < arr.length; i++) { var m = pick(arr[i]); if (m) return m; }
  } catch (e) {}
  return '';
}
function detect() { try { const s = localStorage.getItem(LS_KEY); if (s && STR.back[s] != null) return s; } catch (e) {} return deviceLang() || DEFAULT_LANG; }
export function hasLangChosen() { try { return !!localStorage.getItem(LS_KEY); } catch (e) { return false; } }
export function getLang() { return current; }
export function setLang(c) { if (STR.back[c] == null) return; current = c; try { localStorage.setItem(LS_KEY, c); } catch (e) {} applyDir(); }
export function isRTL() { return RTL.indexOf(current) > -1; }
export function applyDir() { try { document.documentElement.setAttribute('dir', isRTL() ? 'rtl' : 'ltr'); document.documentElement.setAttribute('lang', current); } catch (e) {} }
// Инструментите регистрират своите низове сами (за да не пипат този файл едновременно).
export function register(dict) { for (const k in dict) STR[k] = dict[k]; }
export function t(key) { const r = STR[key]; if (!r) return key; if (r[current] != null) return r[current]; if (r[DEFAULT_LANG] != null) return r[DEFAULT_LANG]; if (r[FALLBACK_LANG] != null) return r[FALLBACK_LANG]; return key; }
export function tf(key, ...vals) { let s = t(key); vals.forEach((v, i) => { s = s.replace(new RegExp('\\{' + i + '\\}', 'g'), String(v)); }); return s; }
export { LANGUAGES };
