// Version: 1.0021
// „Вериги от инструменти" (обединено приложение, 11.09.2026): изходът на един инструмент е вход на следващия.
// Всеки инструмент записва резултата си като ФАЙЛ на устройството (или го копира в клипборда), а следващият
// го отваря от избора на файл / го поставя. Лентата в горния край на всеки инструмент води стъпка по стъпка
// (main.js: renderTool чете активната верига от sessionStorage и показва подсказката за текущата стъпка).
// 6 ГОТОВИ вериги по ситуация + СВОИ вериги (име + избрани стъпки от всички инструменти; localStorage).
import { esc } from '../core/ui.js';
import { t, tf, register } from '../core/i18n.js';
import { tools, GROUPS } from '../core/registry.js';
import { iconHTML } from '../core/icons.js';

export const ACTIVE_KEY = 'st.chain.active.v1';   // sessionStorage: { name, steps:[{tool, hint}], idx }
const MINE_KEY = 'st.chains.mine.v1';              // localStorage: [{ id, name, steps:[tool ids] }]

register({
  ch_ready: { bg:'Готови вериги', ru:'Готовые цепочки', uk:'Готові ланцюжки', en:'Ready chains', de:'Fertige Ketten', fr:'Chaînes prêtes', es:'Cadenas listas', 'es-MX':'Cadenas listas', it:'Catene pronte', pt:'Cadeias prontas', ar:'سلاسل جاهزة', hi:'तैयार चेन', ja:'既製チェーン', ky:'Даяр чынжырлар', 'zh-Hant':'現成工具鏈' },
  ch_mine: { bg:'Моите вериги', ru:'Мои цепочки', uk:'Мої ланцюжки', en:'My chains', de:'Meine Ketten', fr:'Mes chaînes', es:'Mis cadenas', 'es-MX':'Mis cadenas', it:'Le mie catene', pt:'As minhas cadeias', ar:'سلاسلي', hi:'मेरी चेन', ja:'自分のチェーン', ky:'Менин чынжырларым', 'zh-Hant':'我的工具鏈' },
  ch_how: { bg:'Как работи: всеки инструмент записва резултата си като файл на устройството (или го копира), а следващият го отваря от избора на файл. Лентата отгоре те води стъпка по стъпка.', ru:'Как это работает: каждый инструмент сохраняет результат как файл на устройстве (или копирует его), а следующий открывает его через выбор файла. Панель сверху ведёт шаг за шагом.', uk:'Як це працює: кожен інструмент зберігає результат як файл на пристрої (або копіює його), а наступний відкриває його через вибір файлу. Панель угорі веде крок за кроком.', en:'How it works: each tool saves its result as a file on the device (or copies it), and the next tool opens it from the file picker. The bar at the top guides you step by step.', de:'So funktioniert es: Jedes Werkzeug speichert sein Ergebnis als Datei auf dem Gerät (oder kopiert es), das nächste öffnet es über die Dateiauswahl. Die Leiste oben führt Schritt für Schritt.', fr:'Fonctionnement : chaque outil enregistre son résultat en fichier sur l’appareil (ou le copie), et l’outil suivant l’ouvre via le sélecteur de fichiers. La barre en haut vous guide étape par étape.', es:'Cómo funciona: cada herramienta guarda su resultado como archivo en el dispositivo (o lo copia) y la siguiente lo abre desde el selector de archivos. La barra superior te guía paso a paso.', 'es-MX':'Cómo funciona: cada herramienta guarda su resultado como archivo en el dispositivo (o lo copia) y la siguiente lo abre desde el selector de archivos. La barra superior te guía paso a paso.', it:'Come funziona: ogni strumento salva il risultato come file sul dispositivo (o lo copia) e il successivo lo apre dal selettore file. La barra in alto ti guida passo dopo passo.', pt:'Como funciona: cada ferramenta guarda o resultado como ficheiro no dispositivo (ou copia-o) e a seguinte abre-o no seletor de ficheiros. A barra no topo guia-o passo a passo.', ar:'كيف يعمل: تحفظ كل أداة نتيجتها كملف على الجهاز (أو تنسخها)، وتفتحها الأداة التالية من منتقي الملفات. الشريط العلوي يرشدك خطوة بخطوة.', hi:'यह कैसे काम करता है: हर टूल अपना परिणाम डिवाइस पर फ़ाइल के रूप में सहेजता है (या कॉपी करता है), और अगला टूल उसे फ़ाइल चयनकर्ता से खोलता है। ऊपर की पट्टी आपको चरण दर चरण ले जाती है।', ja:'仕組み：各ツールは結果を端末にファイルとして保存（またはコピー）し、次のツールがファイル選択から開きます。上部のバーがステップごとに案内します。', ky:'Кантип иштейт: ар бир курал натыйжасын түзмөккө файл кылып сактайт (же көчүрөт), кийинкиси аны файл тандоодон ачат. Үстүңкү тилке кадам сайын жетектейт.', 'zh-Hant':'運作方式：每個工具把結果儲存為裝置上的檔案（或複製），下一個工具再從檔案選擇器開啟。頂端的導引列會一步步帶你完成。' },
  ch_start: { bg:'Започни веригата', ru:'Начать цепочку', uk:'Почати ланцюжок', en:'Start chain', de:'Kette starten', fr:'Lancer la chaîne', es:'Iniciar cadena', 'es-MX':'Iniciar cadena', it:'Avvia catena', pt:'Iniciar cadeia', ar:'ابدأ السلسلة', hi:'चेन शुरू करें', ja:'チェーンを開始', ky:'Чынжырды баштоо', 'zh-Hant':'開始工具鏈' },
  ch_steps: { bg:'{0} стъпки', ru:'{0} шагов', uk:'{0} кроків', en:'{0} steps', de:'{0} Schritte', fr:'{0} étapes', es:'{0} pasos', 'es-MX':'{0} pasos', it:'{0} passi', pt:'{0} passos', ar:'{0} خطوات', hi:'{0} चरण', ja:'{0} ステップ', ky:'{0} кадам', 'zh-Hant':'{0} 個步驟' },
  ch_new: { bg:'Нова верига', ru:'Новая цепочка', uk:'Новий ланцюжок', en:'New chain', de:'Neue Kette', fr:'Nouvelle chaîne', es:'Nueva cadena', 'es-MX':'Nueva cadena', it:'Nuova catena', pt:'Nova cadeia', ar:'سلسلة جديدة', hi:'नई चेन', ja:'新しいチェーン', ky:'Жаңы чынжыр', 'zh-Hant':'新工具鏈' },
  ch_name: { bg:'Име на веригата', ru:'Название цепочки', uk:'Назва ланцюжка', en:'Chain name', de:'Name der Kette', fr:'Nom de la chaîne', es:'Nombre de la cadena', 'es-MX':'Nombre de la cadena', it:'Nome della catena', pt:'Nome da cadeia', ar:'اسم السلسلة', hi:'चेन का नाम', ja:'チェーン名', ky:'Чынжырдын аты', 'zh-Hant':'工具鏈名稱' },
  ch_name_ph: { bg:'напр. Фактура за клиент', ru:'напр. Счёт для клиента', uk:'напр. Рахунок для клієнта', en:'e.g. Invoice for a client', de:'z. B. Rechnung für einen Kunden', fr:'ex. Facture pour un client', es:'p. ej. Factura para un cliente', 'es-MX':'p. ej. Factura para un cliente', it:'es. Fattura per un cliente', pt:'ex. Fatura para um cliente', ar:'مثال: فاتورة لعميل', hi:'उदा. ग्राहक के लिए चालान', ja:'例：顧客向け請求書', ky:'мис. Кардар үчүн эсеп', 'zh-Hant':'例如：客戶發票' },
  ch_add_step: { bg:'+ Добави стъпка', ru:'+ Добавить шаг', uk:'+ Додати крок', en:'+ Add step', de:'+ Schritt hinzufügen', fr:'+ Ajouter une étape', es:'+ Añadir paso', 'es-MX':'+ Agregar paso', it:'+ Aggiungi passo', pt:'+ Adicionar passo', ar:'+ إضافة خطوة', hi:'+ चरण जोड़ें', ja:'+ ステップを追加', ky:'+ Кадам кошуу', 'zh-Hant':'+ 新增步驟' },
  ch_save: { bg:'Запази веригата', ru:'Сохранить цепочку', uk:'Зберегти ланцюжок', en:'Save chain', de:'Kette speichern', fr:'Enregistrer la chaîne', es:'Guardar cadena', 'es-MX':'Guardar cadena', it:'Salva catena', pt:'Guardar cadeia', ar:'حفظ السلسلة', hi:'चेन सहेजें', ja:'チェーンを保存', ky:'Чынжырды сактоо', 'zh-Hant':'儲存工具鏈' },
  ch_delete: { bg:'Изтрий', ru:'Удалить', uk:'Видалити', en:'Delete', de:'Löschen', fr:'Supprimer', es:'Eliminar', 'es-MX':'Eliminar', it:'Elimina', pt:'Eliminar', ar:'حذف', hi:'हटाएँ', ja:'削除', ky:'Өчүрүү', 'zh-Hant':'刪除' },
  ch_remove: { bg:'махни', ru:'убрать', uk:'прибрати', en:'remove', de:'entfernen', fr:'retirer', es:'quitar', 'es-MX':'quitar', it:'rimuovi', pt:'remover', ar:'إزالة', hi:'हटाएँ', ja:'外す', ky:'алып салуу', 'zh-Hant':'移除' },
  ch_empty: { bg:'Още нямаш свои вериги. Натисни „Нова верига", избери име и подреди стъпките от всички 55 инструмента.', ru:'Своих цепочек пока нет. Нажми «Новая цепочка», задай имя и выстрой шаги из всех 55 инструментов.', uk:'Своїх ланцюжків ще немає. Натисни «Новий ланцюжок», задай назву й вибудуй кроки з усіх 55 інструментів.', en:'No chains of your own yet. Tap “New chain”, name it and arrange steps from all 55 tools.', de:'Noch keine eigenen Ketten. Tippe auf „Neue Kette“, benenne sie und ordne Schritte aus allen 55 Werkzeugen an.', fr:'Pas encore de chaîne personnelle. Touchez « Nouvelle chaîne », nommez-la et ordonnez les étapes parmi les 55 outils.', es:'Aún no tienes cadenas propias. Pulsa «Nueva cadena», ponle nombre y ordena pasos de las 55 herramientas.', 'es-MX':'Aún no tienes cadenas propias. Pulsa «Nueva cadena», ponle nombre y ordena pasos de las 55 herramientas.', it:'Nessuna catena personale ancora. Tocca «Nuova catena», dalle un nome e ordina i passi tra i 55 strumenti.', pt:'Ainda não tem cadeias próprias. Toque em «Nova cadeia», dê-lhe um nome e ordene passos de entre as 55 ferramentas.', ar:'لا توجد سلاسل خاصة بك بعد. اضغط «سلسلة جديدة» وسمّها ورتّب الخطوات من بين 55 أداة.', hi:'अभी आपकी अपनी कोई चेन नहीं है। “नई चेन” दबाएँ, नाम दें और सभी 55 टूल में से चरण क्रम में लगाएँ।', ja:'自分のチェーンはまだありません。「新しいチェーン」を押して名前を付け、55のツールからステップを並べましょう。', ky:'Өз чынжырларың азырынча жок. «Жаңы чынжыр» дегенди бас, ат кой жана 55 куралдан кадамдарды ирети менен кош.', 'zh-Hant':'還沒有自訂工具鏈。點「新工具鏈」，命名並從 55 個工具中安排步驟。' },
  ch_need: { bg:'Дай име и поне 2 стъпки.', ru:'Укажи имя и минимум 2 шага.', uk:'Вкажи назву й щонайменше 2 кроки.', en:'Give a name and at least 2 steps.', de:'Name und mindestens 2 Schritte angeben.', fr:'Indiquez un nom et au moins 2 étapes.', es:'Pon un nombre y al menos 2 pasos.', 'es-MX':'Pon un nombre y al menos 2 pasos.', it:'Inserisci un nome e almeno 2 passi.', pt:'Indique um nome e pelo menos 2 passos.', ar:'أدخل اسماً وخطوتين على الأقل.', hi:'नाम और कम से कम 2 चरण दें।', ja:'名前と2つ以上のステップが必要です。', ky:'Ат жана кеминде 2 кадам бер.', 'zh-Hant':'請輸入名稱並至少加入 2 個步驟。' },
  ch_pick: { bg:'— избери инструмент —', ru:'— выбери инструмент —', uk:'— вибери інструмент —', en:'— pick a tool —', de:'– Werkzeug wählen –', fr:'– choisir un outil –', es:'— elige una herramienta —', 'es-MX':'— elige una herramienta —', it:'— scegli uno strumento —', pt:'— escolha uma ferramenta —', ar:'— اختر أداة —', hi:'— टूल चुनें —', ja:'— ツールを選択 —', ky:'— курал танда —', 'zh-Hant':'— 選擇工具 —' },
  // 6 готови вериги: име + подсказка за всяка стъпка
  ch1_name: { bg:'Хартия → защитен PDF', ru:'Бумага → защищённый PDF', uk:'Папір → захищений PDF', en:'Paper → protected PDF', de:'Papier → geschütztes PDF', fr:'Papier → PDF protégé', es:'Papel → PDF protegido', 'es-MX':'Papel → PDF protegido', it:'Carta → PDF protetto', pt:'Papel → PDF protegido', ar:'ورق ← PDF محمي', hi:'कागज़ → सुरक्षित PDF', ja:'紙 → 保護PDF', ky:'Кагаз → корголгон PDF', 'zh-Hant':'紙本 → 受保護 PDF' },
  ch1_s1: { bg:'Снимай или избери страниците и ги свий', ru:'Сними или выбери страницы и сожми их', uk:'Зніми або вибери сторінки і стисни їх', en:'Shoot or pick the pages and shrink them', de:'Seiten fotografieren oder wählen und verkleinern', fr:'Photographiez ou choisissez les pages et réduisez-les', es:'Fotografía o elige las páginas y redúcelas', 'es-MX':'Fotografía o elige las páginas y redúcelas', it:'Fotografa o scegli le pagine e riducile', pt:'Fotografe ou escolha as páginas e reduza-as', ar:'صوّر الصفحات أو اخترها ثم صغّرها', hi:'पन्नों की फ़ोटो लें या चुनें और छोटा करें', ja:'ページを撮影または選択して縮小', ky:'Барактарды тартып же тандап, кичирейт', 'zh-Hant':'拍攝或選擇頁面並縮小' },
  ch1_s2: { bg:'Събери снимките в един PDF (раздел „Снимки")', ru:'Собери фото в один PDF (вкладка «Фото»)', uk:'Збери фото в один PDF (вкладка «Фото»)', en:'Combine the photos into one PDF (“Photos” tab)', de:'Fotos zu einem PDF zusammenfassen (Reiter „Fotos“)', fr:'Réunissez les photos en un PDF (onglet « Photos »)', es:'Reúne las fotos en un PDF (pestaña «Fotos»)', 'es-MX':'Reúne las fotos en un PDF (pestaña «Fotos»)', it:'Unisci le foto in un PDF (scheda «Foto»)', pt:'Junte as fotos num PDF (separador «Fotos»)', ar:'اجمع الصور في ملف PDF واحد (تبويب «الصور»)', hi:'फ़ोटो को एक PDF में जोड़ें (“फ़ोटो” टैब)', ja:'写真を1つのPDFにまとめる（「写真」タブ）', ky:'Сүрөттөрдү бир PDFге чогулт («Сүрөттөр» өтмөгү)', 'zh-Hant':'把照片合併成一個 PDF（「照片」分頁）' },
  ch1_s3: { bg:'Свий PDF-а, за да е лек за изпращане', ru:'Сожми PDF, чтобы легко отправить', uk:'Стисни PDF, щоб легко надіслати', en:'Compress the PDF so it is light to send', de:'PDF komprimieren, damit es leicht zu senden ist', fr:'Compressez le PDF pour l’envoyer facilement', es:'Comprime el PDF para enviarlo ligero', 'es-MX':'Comprime el PDF para enviarlo ligero', it:'Comprimi il PDF per inviarlo leggero', pt:'Comprima o PDF para o enviar leve', ar:'اضغط ملف PDF ليصبح خفيفاً للإرسال', hi:'भेजने के लिए PDF को हल्का करें', ja:'送りやすいようにPDFを圧縮', ky:'Жөнөтүүгө жеңил болсун деп PDFти кысып ал', 'zh-Hant':'壓縮 PDF 以方便傳送' },
  ch1_s4: { bg:'Запечатай PDF-а за твоя затворен кръг', ru:'Запечатай PDF для своего закрытого круга', uk:'Запечатай PDF для свого закритого кола', en:'Seal the PDF for your closed circle', de:'PDF für deinen geschlossenen Kreis versiegeln', fr:'Scellez le PDF pour votre cercle fermé', es:'Sella el PDF para tu círculo cerrado', 'es-MX':'Sella el PDF para tu círculo cerrado', it:'Sigilla il PDF per la tua cerchia chiusa', pt:'Sele o PDF para o seu círculo fechado', ar:'اختم ملف PDF لدائرتك المغلقة', hi:'अपने बंद समूह के लिए PDF सील करें', ja:'クローズドサークル向けにPDFを封印', ky:'PDFти жабык чөйрөң үчүн мөөрлө', 'zh-Hant':'為你的封閉圈子封存 PDF' },
  ch2_name: { bg:'Оферта за клиент', ru:'Предложение для клиента', uk:'Пропозиція для клієнта', en:'Offer for a client', de:'Angebot für einen Kunden', fr:'Offre pour un client', es:'Oferta para un cliente', 'es-MX':'Oferta para un cliente', it:'Offerta per un cliente', pt:'Proposta para um cliente', ar:'عرض لعميل', hi:'ग्राहक के लिए ऑफ़र', ja:'顧客向けオファー', ky:'Кардар үчүн сунуш', 'zh-Hant':'客戶報價' },
  ch2_s1: { bg:'Напиши текста на офертата (тип × тон, на нужните езици)', ru:'Напиши текст предложения (тип × тон, на нужных языках)', uk:'Напиши текст пропозиції (тип × тон, потрібними мовами)', en:'Write the offer text (type × tone, in the needed languages)', de:'Angebotstext schreiben (Typ × Ton, in den nötigen Sprachen)', fr:'Rédigez le texte de l’offre (type × ton, dans les langues voulues)', es:'Escribe el texto de la oferta (tipo × tono, en los idiomas necesarios)', 'es-MX':'Escribe el texto de la oferta (tipo × tono, en los idiomas necesarios)', it:'Scrivi il testo dell’offerta (tipo × tono, nelle lingue necessarie)', pt:'Escreva o texto da proposta (tipo × tom, nas línguas necessárias)', ar:'اكتب نص العرض (النوع × النبرة، باللغات المطلوبة)', hi:'ऑफ़र का टेक्स्ट लिखें (प्रकार × लहजा, ज़रूरी भाषाओं में)', ja:'オファー文を作成（種類×トーン、必要な言語で）', ky:'Сунуштун текстин жаз (түрү × үнү, керектүү тилдерде)', 'zh-Hant':'撰寫報價文字（類型 × 語氣，所需語言）' },
  ch2_s2: { bg:'Постави текста в PDF и сложи печат (раздел „Текст" / „Печат")', ru:'Помести текст в PDF и поставь штамп (вкладки «Текст» / «Штамп»)', uk:'Постав текст у PDF і додай штамп (вкладки «Текст» / «Штамп»)', en:'Put the text into a PDF and add a stamp (“Text” / “Stamp” tabs)', de:'Text in ein PDF setzen und Stempel hinzufügen (Reiter „Text“ / „Stempel“)', fr:'Mettez le texte en PDF et ajoutez un tampon (onglets « Texte » / « Tampon »)', es:'Pon el texto en un PDF y añade un sello (pestañas «Texto» / «Sello»)', 'es-MX':'Pon el texto en un PDF y agrega un sello (pestañas «Texto» / «Sello»)', it:'Metti il testo in un PDF e aggiungi un timbro (schede «Testo» / «Timbro»)', pt:'Coloque o texto num PDF e adicione um carimbo (separadores «Texto» / «Carimbo»)', ar:'ضع النص في PDF وأضف ختماً (تبويبا «النص» / «الختم»)', hi:'टेक्स्ट को PDF में डालें और मुहर लगाएँ (“टेक्स्ट” / “मुहर” टैब)', ja:'テキストをPDFにしてスタンプを追加（「テキスト」/「スタンプ」タブ）', ky:'Текстти PDFге кой жана мөөр бас («Текст» / «Мөөр» өтмөктөрү)', 'zh-Hant':'把文字放進 PDF 並加上印章（「文字」/「印章」分頁）' },
  ch2_s3: { bg:'Направи QR към линка на офертата за визитката или плаката', ru:'Сделай QR со ссылкой на предложение для визитки или плаката', uk:'Зроби QR із посиланням на пропозицію для візитівки чи плаката', en:'Make a QR to the offer link for a business card or poster', de:'QR mit dem Angebotslink für Visitenkarte oder Plakat erstellen', fr:'Créez un QR vers le lien de l’offre pour une carte de visite ou une affiche', es:'Crea un QR con el enlace de la oferta para una tarjeta o cartel', 'es-MX':'Crea un QR con el enlace de la oferta para una tarjeta o cartel', it:'Crea un QR con il link dell’offerta per biglietto da visita o manifesto', pt:'Crie um QR com a ligação da proposta para cartão de visita ou cartaz', ar:'أنشئ رمز QR لرابط العرض لبطاقة عمل أو ملصق', hi:'बिज़नेस कार्ड या पोस्टर के लिए ऑफ़र लिंक का QR बनाएँ', ja:'名刺やポスター用にオファーリンクのQRを作成', ky:'Визитка же плакат үчүн сунуштун шилтемесине QR жаса', 'zh-Hant':'為名片或海報製作報價連結的 QR' },
  ch3_name: { bg:'Нов акаунт — сигурно', ru:'Новый аккаунт — безопасно', uk:'Новий обліковий запис — безпечно', en:'New account — safely', de:'Neues Konto – sicher', fr:'Nouveau compte – en sécurité', es:'Cuenta nueva — con seguridad', 'es-MX':'Cuenta nueva — con seguridad', it:'Nuovo account — in sicurezza', pt:'Conta nova — em segurança', ar:'حساب جديد — بأمان', hi:'नया खाता — सुरक्षित रूप से', ja:'新しいアカウントを安全に', ky:'Жаңы аккаунт — коопсуз', 'zh-Hant':'安全地建立新帳號' },
  ch3_s1: { bg:'Провери старата парола: ентропия, време за разбиване, изтичания', ru:'Проверь старый пароль: энтропия, время взлома, утечки', uk:'Перевір старий пароль: ентропія, час зламу, витоки', en:'Check the old password: entropy, crack time, leaks', de:'Altes Passwort prüfen: Entropie, Knackzeit, Leaks', fr:'Vérifiez l’ancien mot de passe : entropie, temps de cassage, fuites', es:'Comprueba la contraseña antigua: entropía, tiempo de descifrado, filtraciones', 'es-MX':'Comprueba la contraseña antigua: entropía, tiempo de descifrado, filtraciones', it:'Controlla la vecchia password: entropia, tempo di cracking, fughe', pt:'Verifique a senha antiga: entropia, tempo de quebra, fugas', ar:'افحص كلمة المرور القديمة: الإنتروبيا، زمن الكسر، التسريبات', hi:'पुराना पासवर्ड जाँचें: एंट्रॉपी, क्रैक समय, लीक', ja:'古いパスワードを確認：エントロピー、解読時間、漏洩', ky:'Эски сырсөздү текшер: энтропия, бузуу убактысы, агып кетүүлөр', 'zh-Hant':'檢查舊密碼：熵值、破解時間、外洩' },
  ch3_s2: { bg:'Генерирай нова силна парола (9 метода)', ru:'Сгенерируй новый надёжный пароль (9 методов)', uk:'Згенеруй новий надійний пароль (9 методів)', en:'Generate a new strong password (9 methods)', de:'Neues starkes Passwort erzeugen (9 Methoden)', fr:'Générez un nouveau mot de passe fort (9 méthodes)', es:'Genera una contraseña nueva y fuerte (9 métodos)', 'es-MX':'Genera una contraseña nueva y fuerte (9 métodos)', it:'Genera una nuova password forte (9 metodi)', pt:'Gere uma senha nova e forte (9 métodos)', ar:'أنشئ كلمة مرور قوية جديدة (9 طرق)', hi:'नया मज़बूत पासवर्ड बनाएँ (9 तरीके)', ja:'新しい強力なパスワードを生成（9つの方式）', ky:'Жаңы күчтүү сырсөз түз (9 ыкма)', 'zh-Hant':'產生新的強密碼（9 種方法）' },
  ch3_s3: { bg:'Шифровай бележката с данните за достъп (AES-256)', ru:'Зашифруй заметку с данными доступа (AES-256)', uk:'Зашифруй нотатку з даними доступу (AES-256)', en:'Encrypt the note with the access details (AES-256)', de:'Notiz mit den Zugangsdaten verschlüsseln (AES-256)', fr:'Chiffrez la note avec les identifiants (AES-256)', es:'Cifra la nota con los datos de acceso (AES-256)', 'es-MX':'Cifra la nota con los datos de acceso (AES-256)', it:'Cifra la nota con i dati di accesso (AES-256)', pt:'Cifre a nota com os dados de acesso (AES-256)', ar:'شفّر الملاحظة التي تحوي بيانات الدخول (AES-256)', hi:'एक्सेस विवरण वाले नोट को एन्क्रिप्ट करें (AES-256)', ja:'アクセス情報のメモを暗号化（AES-256）', ky:'Кирүү маалыматы бар жазууну шифрле (AES-256)', 'zh-Hant':'加密含登入資料的筆記（AES-256）' },
  ch3_s4: { bg:'Добави кода за двустепенна защита в удостоверителя', ru:'Добавь код двухфакторной защиты в аутентификатор', uk:'Додай код двофакторного захисту в автентифікатор', en:'Add the two-factor code to the authenticator', de:'Zwei-Faktor-Code zum Authenticator hinzufügen', fr:'Ajoutez le code à deux facteurs dans l’authentificateur', es:'Añade el código de dos factores al autenticador', 'es-MX':'Agrega el código de dos factores al autenticador', it:'Aggiungi il codice a due fattori nell’autenticatore', pt:'Adicione o código de dois fatores ao autenticador', ar:'أضف رمز التحقق بخطوتين إلى المصادق', hi:'दो-चरणीय कोड को ऑथेंटिकेटर में जोड़ें', ja:'二要素コードを認証アプリに追加', ky:'Эки баскычтуу кодду аутентификаторго кош', 'zh-Hant':'把兩步驟驗證碼加入驗證器' },
  ch4_name: { bg:'Инвентар вкъщи', ru:'Домашний инвентарь', uk:'Домашній інвентар', en:'Home inventory', de:'Haushaltsinventar', fr:'Inventaire de la maison', es:'Inventario del hogar', 'es-MX':'Inventario del hogar', it:'Inventario di casa', pt:'Inventário de casa', ar:'جرد المنزل', hi:'घर की इन्वेंटरी', ja:'家庭内の在庫', ky:'Үйдөгү инвентарь', 'zh-Hant':'家庭物品清單' },
  ch4_s1: { bg:'Снимай вещите и свий снимките', ru:'Сфотографируй вещи и сожми фото', uk:'Сфотографуй речі та стисни фото', en:'Photograph the items and shrink the photos', de:'Gegenstände fotografieren und Fotos verkleinern', fr:'Photographiez les objets et réduisez les photos', es:'Fotografía los objetos y reduce las fotos', 'es-MX':'Fotografía los objetos y reduce las fotos', it:'Fotografa gli oggetti e riduci le foto', pt:'Fotografe os objetos e reduza as fotos', ar:'صوّر الأغراض وصغّر الصور', hi:'चीज़ों की फ़ोटो लें और छोटा करें', ja:'品物を撮影して写真を縮小', ky:'Буюмдарды сүрөткө тартып, сүрөттөрдү кичирейт', 'zh-Hant':'拍攝物品並縮小照片' },
  ch4_s2: { bg:'Създай етикети: име, място, снимка, срок', ru:'Создай этикетки: название, место, фото, срок', uk:'Створи етикетки: назва, місце, фото, термін', en:'Create labels: name, place, photo, due date', de:'Etiketten anlegen: Name, Ort, Foto, Frist', fr:'Créez des étiquettes : nom, lieu, photo, échéance', es:'Crea etiquetas: nombre, lugar, foto, fecha', 'es-MX':'Crea etiquetas: nombre, lugar, foto, fecha', it:'Crea etichette: nome, posto, foto, scadenza', pt:'Crie etiquetas: nome, local, foto, prazo', ar:'أنشئ ملصقات: الاسم، المكان، الصورة، الموعد', hi:'लेबल बनाएँ: नाम, जगह, फ़ोटो, तारीख़', ja:'ラベルを作成：名前・場所・写真・期限', ky:'Этикеткаларды түз: аты, орду, сүрөтү, мөөнөтү', 'zh-Hant':'建立標籤：名稱、位置、照片、期限' },
  ch4_s3: { bg:'Генерирай QR кодове за всички етикети наведнъж', ru:'Сгенерируй QR-коды для всех этикеток сразу', uk:'Згенеруй QR-коди для всіх етикеток одразу', en:'Generate QR codes for all labels at once', de:'QR-Codes für alle Etiketten auf einmal erzeugen', fr:'Générez les codes QR de toutes les étiquettes d’un coup', es:'Genera códigos QR para todas las etiquetas a la vez', 'es-MX':'Genera códigos QR para todas las etiquetas a la vez', it:'Genera i codici QR di tutte le etichette in una volta', pt:'Gere códigos QR para todas as etiquetas de uma vez', ar:'أنشئ رموز QR لكل الملصقات دفعة واحدة', hi:'सभी लेबल के QR कोड एक साथ बनाएँ', ja:'すべてのラベルのQRコードを一括生成', ky:'Бардык этикеткалар үчүн QR коддорду бир жолу түз', 'zh-Hant':'一次產生所有標籤的 QR 碼' },
  ch4_s4: { bg:'Подреди QR кодовете N на лист и отпечатай („N на лист")', ru:'Разложи QR-коды по N на лист и распечатай («N на лист»)', uk:'Розклади QR-коди по N на аркуш і роздрукуй («N на аркуш»)', en:'Arrange the QR codes N per sheet and print (“N per sheet”)', de:'QR-Codes N pro Blatt anordnen und drucken („N pro Blatt“)', fr:'Disposez les QR N par feuille et imprimez (« N par feuille »)', es:'Coloca los QR N por hoja e imprime («N por hoja»)', 'es-MX':'Coloca los QR N por hoja e imprime («N por hoja»)', it:'Disponi i QR N per foglio e stampa («N per foglio»)', pt:'Disponha os QR N por folha e imprima («N por folha»)', ar:'رتّب رموز QR بعدد N في الورقة واطبع («N في الورقة»)', hi:'QR कोड को प्रति शीट N लगाएँ और प्रिंट करें (“प्रति शीट N”)', ja:'QRを1枚にN個並べて印刷（「1枚にN個」）', ky:'QR коддорду бир баракка N кылып жайгаштырып, басып чыгар («Баракка N»)', 'zh-Hant':'把 QR 碼每頁 N 個排版並列印（「每頁 N 個」）' },
  ch5_name: { bg:'Голяма покупка', ru:'Крупная покупка', uk:'Велика покупка', en:'Big purchase', de:'Große Anschaffung', fr:'Gros achat', es:'Compra grande', 'es-MX':'Compra grande', it:'Grande acquisto', pt:'Compra grande', ar:'شراء كبير', hi:'बड़ी ख़रीद', ja:'大きな買い物', ky:'Чоң сатып алуу', 'zh-Hant':'大額採購' },
  ch5_s1: { bg:'Виж колко часа живот струва покупката', ru:'Посмотри, сколько часов жизни стоит покупка', uk:'Подивись, скільки годин життя коштує покупка', en:'See how many hours of life the purchase costs', de:'Sieh, wie viele Lebensstunden der Kauf kostet', fr:'Voyez combien d’heures de vie coûte l’achat', es:'Mira cuántas horas de vida cuesta la compra', 'es-MX':'Mira cuántas horas de vida cuesta la compra', it:'Guarda quante ore di vita costa l’acquisto', pt:'Veja quantas horas de vida custa a compra', ar:'انظر كم ساعة من حياتك يكلّف الشراء', hi:'देखें ख़रीद में ज़िंदगी के कितने घंटे लगते हैं', ja:'その買い物が人生の何時間分か確認', ky:'Сатып алуу канча саат өмүргө туурарын көр', 'zh-Hant':'看看這筆購買要花掉多少小時的人生' },
  ch5_s2: { bg:'Планирай кога ще я имаш (цел, вноски, срок)', ru:'Спланируй, когда она будет твоей (цель, взносы, срок)', uk:'Сплануй, коли вона буде твоєю (ціль, внески, строк)', en:'Plan when you will have it (goal, instalments, deadline)', de:'Planen, wann du es hast (Ziel, Raten, Frist)', fr:'Planifiez quand vous l’aurez (objectif, versements, échéance)', es:'Planifica cuándo la tendrás (meta, cuotas, plazo)', 'es-MX':'Planifica cuándo la tendrás (meta, cuotas, plazo)', it:'Pianifica quando l’avrai (obiettivo, rate, scadenza)', pt:'Planeie quando a terá (meta, prestações, prazo)', ar:'خطّط متى ستمتلكه (الهدف، الأقساط، الموعد)', hi:'योजना बनाएँ कब मिलेगी (लक्ष्य, किस्तें, समय)', ja:'いつ手に入るか計画（目標・積立・期限）', ky:'Качан ээ болоруңду пландаштыр (максат, төлөмдөр, мөөнөт)', 'zh-Hant':'規劃何時能擁有（目標、分期、期限）' },
  ch5_s3: { bg:'Отдели плик за нея в бюджета', ru:'Выдели под неё конверт в бюджете', uk:'Виділи під неї конверт у бюджеті', en:'Set aside an envelope for it in the budget', de:'Einen Umschlag dafür im Budget anlegen', fr:'Réservez-lui une enveloppe dans le budget', es:'Reserva un sobre para ella en el presupuesto', 'es-MX':'Reserva un sobre para ella en el presupuesto', it:'Riserva una busta nel budget', pt:'Reserve um envelope no orçamento', ar:'خصّص له مظروفاً في الميزانية', hi:'बजट में उसके लिए एक लिफ़ाफ़ा अलग रखें', ja:'予算に専用の封筒を用意', ky:'Бюджетте ага конверт бөл', 'zh-Hant':'在預算中為它預留一個信封' },
  ch5_s4: { bg:'Следи цената и получи известие при спад', ru:'Следи за ценой и получи уведомление при снижении', uk:'Стеж за ціною й отримай сповіщення при зниженні', en:'Watch the price and get a notification when it drops', de:'Preis beobachten und bei Preisfall benachrichtigt werden', fr:'Surveillez le prix et soyez averti quand il baisse', es:'Vigila el precio y recibe un aviso cuando baje', 'es-MX':'Vigila el precio y recibe un aviso cuando baje', it:'Segui il prezzo e ricevi una notifica quando scende', pt:'Acompanhe o preço e receba um aviso quando baixar', ar:'راقب السعر واحصل على إشعار عند انخفاضه', hi:'क़ीमत पर नज़र रखें और गिरने पर सूचना पाएँ', ja:'価格を監視して値下がり時に通知', ky:'Баасын байкап, түшкөндө билдирме ал', 'zh-Hant':'追蹤價格，降價時收到通知' },
  ch6_name: { bg:'Видео за социалните мрежи', ru:'Видео для соцсетей', uk:'Відео для соцмереж', en:'Video for social media', de:'Video für soziale Netzwerke', fr:'Vidéo pour les réseaux sociaux', es:'Vídeo para redes sociales', 'es-MX':'Video para redes sociales', it:'Video per i social', pt:'Vídeo para redes sociais', ar:'فيديو لوسائل التواصل', hi:'सोशल मीडिया के लिए वीडियो', ja:'SNS向け動画', ky:'Социалдык тармактар үчүн видео', 'zh-Hant':'社群媒體影片' },
  ch6_s1: { bg:'Отрежи или свий видеото, извади звука', ru:'Обрежь или сожми видео, извлеки звук', uk:'Обріж або стисни відео, витягни звук', en:'Trim or shrink the video, extract the audio', de:'Video schneiden oder verkleinern, Ton extrahieren', fr:'Coupez ou réduisez la vidéo, extrayez le son', es:'Recorta o reduce el vídeo, extrae el audio', 'es-MX':'Recorta o reduce el video, extrae el audio', it:'Taglia o riduci il video, estrai l’audio', pt:'Corte ou reduza o vídeo, extraia o áudio', ar:'قصّ الفيديو أو صغّره واستخرج الصوت', hi:'वीडियो काटें या छोटा करें, ऑडियो निकालें', ja:'動画をトリム/縮小し、音声を抽出', ky:'Видеону кесип же кичирейтип, үнүн бөлүп ал', 'zh-Hant':'剪輯或縮小影片、擷取音訊' },
  ch6_s2: { bg:'Обработи гласа: шумопотискане, ефекти, нормализация', ru:'Обработай голос: шумоподавление, эффекты, нормализация', uk:'Оброби голос: шумозаглушення, ефекти, нормалізація', en:'Process the voice: denoise, effects, normalise', de:'Stimme bearbeiten: Rauschen entfernen, Effekte, Normalisieren', fr:'Traitez la voix : débruitage, effets, normalisation', es:'Procesa la voz: reducción de ruido, efectos, normalización', 'es-MX':'Procesa la voz: reducción de ruido, efectos, normalización', it:'Elabora la voce: riduzione rumore, effetti, normalizzazione', pt:'Trate a voz: redução de ruído, efeitos, normalização', ar:'عالج الصوت: إزالة الضجيج، مؤثرات، تسوية', hi:'आवाज़ संसाधित करें: शोर हटाना, प्रभाव, सामान्यीकरण', ja:'音声を加工：ノイズ除去、エフェクト、ノーマライズ', ky:'Үндү иштет: ызы-чууну басуу, эффекттер, нормалдаштыруу', 'zh-Hant':'處理人聲：降噪、效果、正規化' },
  ch6_s3: { bg:'Напиши текста за поста на нужните езици', ru:'Напиши текст поста на нужных языках', uk:'Напиши текст допису потрібними мовами', en:'Write the post text in the needed languages', de:'Beitragstext in den nötigen Sprachen schreiben', fr:'Rédigez le texte du post dans les langues voulues', es:'Escribe el texto de la publicación en los idiomas necesarios', 'es-MX':'Escribe el texto de la publicación en los idiomas necesarios', it:'Scrivi il testo del post nelle lingue necessarie', pt:'Escreva o texto da publicação nas línguas necessárias', ar:'اكتب نص المنشور باللغات المطلوبة', hi:'पोस्ट का टेक्स्ट ज़रूरी भाषाओं में लिखें', ja:'投稿文を必要な言語で作成', ky:'Посттун текстин керектүү тилдерде жаз', 'zh-Hant':'以所需語言撰寫貼文文字' },
  ch6_s4: { bg:'QR към публикацията за плаката или визитката', ru:'QR на публикацию для плаката или визитки', uk:'QR на публікацію для плаката чи візитівки', en:'QR to the post for a poster or business card', de:'QR zum Beitrag für Plakat oder Visitenkarte', fr:'QR vers la publication pour affiche ou carte de visite', es:'QR a la publicación para cartel o tarjeta', 'es-MX':'QR a la publicación para cartel o tarjeta', it:'QR al post per manifesto o biglietto da visita', pt:'QR para a publicação para cartaz ou cartão', ar:'رمز QR للمنشور لملصق أو بطاقة عمل', hi:'पोस्टर या कार्ड के लिए पोस्ट का QR', ja:'ポスターや名刺用に投稿へのQR', ky:'Плакат же визитка үчүн жарыялоого QR', 'zh-Hant':'為海報或名片製作貼文 QR' },
});

export const title = 'Tool chains';

// Готовите вериги: инструмент + ключ на подсказката за стъпката
export const READY = [
  { id: 'ch1', name: 'ch1_name', steps: [['image', 'ch1_s1'], ['pdfo', 'ch1_s2'], ['pdfc', 'ch1_s3'], ['sealed', 'ch1_s4']] },
  { id: 'ch2', name: 'ch2_name', steps: [['campaigns', 'ch2_s1'], ['pdfo', 'ch2_s2'], ['qr-style', 'ch2_s3']] },
  { id: 'ch3', name: 'ch3_name', steps: [['pw-strength', 'ch3_s1'], ['password', 'ch3_s2'], ['pw-crypt', 'ch3_s3'], ['authenticator', 'ch3_s4']] },
  { id: 'ch4', name: 'ch4_name', steps: [['image', 'ch4_s1'], ['labels', 'ch4_s2'], ['qr-batch', 'ch4_s3'], ['pdfo', 'ch4_s4']] },
  { id: 'ch5', name: 'ch5_name', steps: [['life', 'ch5_s1'], ['planner', 'ch5_s2'], ['budget', 'ch5_s3'], ['pricewatch', 'ch5_s4']] },
  { id: 'ch6', name: 'ch6_name', steps: [['videos', 'ch6_s1'], ['sound', 'ch6_s2'], ['campaigns', 'ch6_s3'], ['qr', 'ch6_s4']] },
];

function loadMine() { try { return JSON.parse(localStorage.getItem(MINE_KEY) || '[]') || []; } catch (e) { return []; } }
function saveMine(list) { try { localStorage.setItem(MINE_KEY, JSON.stringify(list)); } catch (e) {} }
const toolOf = (id) => tools.find((x) => x.id === id);

// Активиране на верига: записва я в sessionStorage и отваря първия инструмент.
export function startChain(name, steps) {
  const st = { name, steps: steps.map((s) => ({ tool: s[0], hint: s[1] || '' })), idx: 0 };
  try { sessionStorage.setItem(ACTIVE_KEY, JSON.stringify(st)); } catch (e) {}
  location.hash = '#/tool/' + st.steps[0].tool;
}
export function activeChain() { try { return JSON.parse(sessionStorage.getItem(ACTIVE_KEY) || 'null'); } catch (e) { return null; } }
export function clearChain() { try { sessionStorage.removeItem(ACTIVE_KEY); } catch (e) {} }

function stepsHTML(steps) {
  return `<div class="ch-steps">${steps.map((s, i) => { const tl = toolOf(s[0]); return `<span class="ch-step"><span class="ch-n">${i + 1}</span>${tl ? iconHTML(tl.icon) : ''}<span>${esc(tl ? t(tl.name) : s[0])}</span></span>`; }).join('<span class="ch-arrow">→</span>')}</div>`;
}

export function render(root) {
  root.innerHTML = `
    <style>
      .ch-tabs{display:flex;gap:6px;margin-bottom:12px}
      .ch-card{background:var(--bg-2);border:1px solid var(--line);border-radius:12px;padding:12px;margin-bottom:10px}
      .ch-card h3{font-size:1em;margin-bottom:6px}
      .ch-steps{display:flex;flex-wrap:wrap;gap:4px 6px;align-items:center;margin:6px 0 10px}
      .ch-step{display:inline-flex;align-items:center;gap:4px;font-size:.8em;background:var(--bg-3);border-radius:8px;padding:3px 7px}
      .ch-step svg{width:14px;height:14px;color:var(--accent-2)}
      .ch-n{font-weight:700;color:var(--accent-2)}
      .ch-arrow{color:var(--text-dim);font-size:.8em}
      .ch-row{display:flex;gap:8px;align-items:center}
      .ch-row .btn{width:auto;flex:1}
      .ch-list{display:flex;flex-direction:column;gap:6px;margin:8px 0}
      .ch-item{display:flex;align-items:center;gap:8px;font-size:.9em}
      .ch-item .rm{margin-inline-start:auto;color:var(--text-dim);font-size:.8em;cursor:pointer}
      .ch-sel{width:100%;padding:8px;border-radius:8px;border:1px solid var(--line);background:var(--bg-3);color:var(--text)}
    </style>
    <div class="tabs ch-tabs" id="chTabs"><button class="tab active" data-tab="ready">${esc(t('ch_ready'))}</button><button class="tab" data-tab="mine">${esc(t('ch_mine'))}</button></div>
    <p class="hint" style="margin:0 0 12px">${esc(t('ch_how'))}</p>
    <div id="chBody"></div>`;
  const body = root.querySelector('#chBody');
  let tab = 'ready';
  root.querySelectorAll('#chTabs .tab').forEach((b) => b.addEventListener('click', () => { tab = b.dataset.tab; root.querySelectorAll('#chTabs .tab').forEach((x) => x.classList.toggle('active', x === b)); draw(); }));

  function drawReady() {
    body.innerHTML = READY.map((c) => `<div class="ch-card" data-ch="${c.id}"><h3>${esc(t(c.name))} <span class="hint" style="display:inline">· ${esc(tf('ch_steps', c.steps.length))}</span></h3>${stepsHTML(c.steps)}<button class="btn" data-start="${c.id}">${esc(t('ch_start'))}</button></div>`).join('');
    body.querySelectorAll('[data-start]').forEach((b) => b.addEventListener('click', () => { const c = READY.find((x) => x.id === b.dataset.start); startChain(t(c.name), c.steps); }));
  }

  // Свои вериги: списък + форма (име + стъпки от всички инструменти, групирани по раздел)
  let editing = null; // { name, steps: [tool ids] }
  function drawMine() {
    const mine = loadMine();
    let html = '';
    if (editing) {
      const opts = GROUPS.map((g) => `<optgroup label="${esc(t('grp_' + g))}">${tools.filter((x) => x.group === g).map((x) => `<option value="${x.id}">${esc(t(x.name))}</option>`).join('')}</optgroup>`).join('');
      html += `<div class="ch-card"><label>${esc(t('ch_name'))}</label><input id="chName" placeholder="${esc(t('ch_name_ph'))}" value="${esc(editing.name)}" />
        <div class="ch-list" id="chList">${editing.steps.map((id, i) => { const tl = toolOf(id); return `<div class="ch-item"><span class="ch-n">${i + 1}</span>${tl ? iconHTML(tl.icon).replace('<svg', '<svg style="width:16px;height:16px;color:var(--accent-2)"') : ''}<span>${esc(tl ? t(tl.name) : id)}</span><span class="rm" data-rm="${i}">✕ ${esc(t('ch_remove'))}</span></div>`; }).join('')}</div>
        <select class="ch-sel" id="chPick"><option value="">${esc(t('ch_pick'))}</option>${opts}</select>
        <div class="ch-row" style="margin-top:8px"><button class="btn sec" id="chAdd">${esc(t('ch_add_step'))}</button><button class="btn" id="chSave">${esc(t('ch_save'))}</button></div>
        <div class="hint" id="chMsg"></div></div>`;
    } else {
      html += `<button class="btn" id="chNew" style="margin-bottom:10px">${esc(t('ch_new'))}</button>`;
    }
    html += mine.length ? mine.map((c) => `<div class="ch-card"><h3>${esc(c.name)} <span class="hint" style="display:inline">· ${esc(tf('ch_steps', c.steps.length))}</span></h3>${stepsHTML(c.steps.map((id) => [id, '']))}<div class="ch-row"><button class="btn" data-start="${c.id}">${esc(t('ch_start'))}</button><button class="btn sec" data-del="${c.id}">${esc(t('ch_delete'))}</button></div></div>`).join('')
      : (editing ? '' : `<div class="hint">${esc(t('ch_empty'))}</div>`);
    body.innerHTML = html;
    const nb = body.querySelector('#chNew'); if (nb) nb.addEventListener('click', () => { editing = { name: '', steps: [] }; drawMine(); });
    body.querySelectorAll('[data-start]').forEach((b) => b.addEventListener('click', () => { const c = mine.find((x) => x.id === b.dataset.start); if (c) startChain(c.name, c.steps.map((id) => [id, toolOf(id) ? toolOf(id).desc : ''])); }));
    body.querySelectorAll('[data-del]').forEach((b) => b.addEventListener('click', () => { saveMine(mine.filter((x) => x.id !== b.dataset.del)); drawMine(); }));
    if (editing) {
      const nameEl = body.querySelector('#chName'); nameEl.addEventListener('input', () => { editing.name = nameEl.value; });
      body.querySelector('#chAdd').addEventListener('click', () => { const v = body.querySelector('#chPick').value; if (!v) return; editing.name = nameEl.value; editing.steps.push(v); drawMine(); });
      body.querySelectorAll('[data-rm]').forEach((x) => x.addEventListener('click', () => { editing.name = nameEl.value; editing.steps.splice(+x.dataset.rm, 1); drawMine(); }));
      body.querySelector('#chSave').addEventListener('click', () => {
        editing.name = nameEl.value.trim();
        if (!editing.name || editing.steps.length < 2) { body.querySelector('#chMsg').textContent = t('ch_need'); return; }
        const list = loadMine(); list.push({ id: 'c' + Date.now().toString(36), name: editing.name, steps: editing.steps }); saveMine(list); editing = null; drawMine();
      });
    }
  }
  function draw() { if (tab === 'ready') drawReady(); else drawMine(); }
  draw();
}
