// Version: 1.0021
// howto-i18n.js — надписите на екрана „Видео инструкция" на 15-те езика.
// Запис: 'bg|ru|uk|en|de|fr|es|es-MX|it|pt|ar|hi|ja|ky|zh-Hant' (разделител „|", точно 15 части).
import { register } from '../core/i18n.js';

const ORDER = ['bg', 'ru', 'uk', 'en', 'de', 'fr', 'es', 'es-MX', 'it', 'pt', 'ar', 'hi', 'ja', 'ky', 'zh-Hant'];
const RAW = {
  ht_banner: 'Това е примерна инструкция — разгледай стъпките, пусни прегледа или изнеси видео, GIF и лист.|Это пример инструкции — посмотрите шаги, запустите просмотр или сохраните видео, GIF и лист.|Це приклад інструкції — перегляньте кроки, запустіть перегляд або збережіть відео, GIF і аркуш.|This is a sample guide — look through the steps, play the preview or export a video, GIF and sheet.|Das ist eine Beispiel-Anleitung — sieh dir die Schritte an, starte die Vorschau oder exportiere Video, GIF und Blatt.|Ceci est un tutoriel d’exemple — parcourez les étapes, lancez l’aperçu ou exportez vidéo, GIF et fiche.|Esta es una guía de ejemplo: revisa los pasos, reproduce la vista previa o exporta vídeo, GIF y hoja.|Esta es una guía de ejemplo: revisa los pasos, reproduce la vista previa o exporta video, GIF y hoja.|Questa è una guida di esempio: guarda i passaggi, avvia l’anteprima o esporta video, GIF e scheda.|Este é um guia de exemplo — veja os passos, reproduza a prévia ou exporte vídeo, GIF e folha.|هذا دليل تجريبي — تصفّح الخطوات أو شغّل المعاينة أو صدّر فيديو وGIF وورقة.|यह एक नमूना गाइड है — चरण देखें, पूर्वावलोकन चलाएँ या वीडियो, GIF और शीट सहेजें।|これはサンプルの手順です — ステップを確認し、プレビュー再生や動画・GIF・シートの書き出しができます。|Бул үлгү нускама — кадамдарды карап, алдын ала көрүүнү ойнотуңуз же видео, GIF жана баракты сактаңыз.|這是範例教學 — 瀏覽步驟、播放預覽，或匯出影片、GIF 與說明單。',
  ht_sample_tag: 'ПРИМЕР|ПРИМЕР|ПРИКЛАД|SAMPLE|BEISPIEL|EXEMPLE|EJEMPLO|EJEMPLO|ESEMPIO|EXEMPLO|مثال|नमूना|サンプル|ҮЛГҮ|範例',
  ht_sample_del: '🗑 Изтрий примера и започни своя|🗑 Удалить пример и начать свою|🗑 Видалити приклад і почати свою|🗑 Delete the sample and start your own|🗑 Beispiel löschen und eigene beginnen|🗑 Supprimer l’exemple et créer le vôtre|🗑 Borrar el ejemplo y empezar la tuya|🗑 Borrar el ejemplo y empezar la tuya|🗑 Elimina l’esempio e crea la tua|🗑 Apagar o exemplo e começar o seu|🗑 احذف المثال وابدأ دليلك|🗑 नमूना हटाएँ और अपना शुरू करें|🗑 サンプルを削除して自分の手順を作る|🗑 Үлгүнү өчүрүп, өзүңүздүкүн баштаңыз|🗑 刪除範例並開始製作自己的',
  ht_play: '▶ Преглед на урока|▶ Просмотр урока|▶ Перегляд уроку|▶ Play the lesson|▶ Lektion abspielen|▶ Lire la leçon|▶ Ver la lección|▶ Ver la lección|▶ Riproduci la lezione|▶ Ver a aula|▶ تشغيل الدرس|▶ पाठ चलाएँ|▶ レッスンを再生|▶ Сабакты көрүү|▶ 播放教學',
  ht_stop: '⏹ Спри прегледа|⏹ Остановить просмотр|⏹ Зупинити перегляд|⏹ Stop the preview|⏹ Vorschau stoppen|⏹ Arrêter l’aperçu|⏹ Detener la vista previa|⏹ Detener la vista previa|⏹ Ferma l’anteprima|⏹ Parar a prévia|⏹ إيقاف المعاينة|⏹ पूर्वावलोकन रोकें|⏹ プレビューを停止|⏹ Көрүүнү токтотуу|⏹ 停止預覽',
  ht_total: 'Дължина на урока: {0} сек. · стъпки: {1}|Длина урока: {0} сек. · шагов: {1}|Тривалість уроку: {0} с · кроків: {1}|Lesson length: {0} s · steps: {1}|Länge: {0} s · Schritte: {1}|Durée : {0} s · étapes : {1}|Duración: {0} s · pasos: {1}|Duración: {0} s · pasos: {1}|Durata: {0} s · passaggi: {1}|Duração: {0} s · passos: {1}|مدة الدرس: {0} ث · الخطوات: {1}|पाठ की अवधि: {0} से. · चरण: {1}|長さ: {0} 秒 · ステップ: {1}|Узактыгы: {0} сек. · кадамдар: {1}|長度：{0} 秒 · 步驟：{1}',
  ht_tpl: 'Шаблон|Шаблон|Шаблон|Template|Vorlage|Modèle|Plantilla|Plantilla|Modello|Modelo|القالب|टेम्पलेट|テンプレート|Шаблон|範本',
  ht_tpl_repair: 'Ремонт|Ремонт|Ремонт|Repair|Reparatur|Réparation|Reparación|Reparación|Riparazione|Reparo|إصلاح|मरम्मत|修理|Оңдоо|維修',
  ht_tpl_recipe: 'Рецепта|Рецепт|Рецепт|Recipe|Rezept|Recette|Receta|Receta|Ricetta|Receita|وصفة|रेसिपी|レシピ|Рецепт|食譜',
  ht_tpl_product: 'Продукт / ревю|Товар / обзор|Товар / огляд|Product / review|Produkt / Test|Produit / avis|Producto / reseña|Producto / reseña|Prodotto / recensione|Produto / análise|منتج / مراجعة|उत्पाद / समीक्षा|製品 / レビュー|Буюм / сын-пикир|產品 / 評測',
  ht_tpl_exercise: 'Упражнение|Упражнение|Вправа|Exercise|Übung|Exercice|Ejercicio|Ejercicio|Esercizio|Exercício|تمرين|व्यायाम|エクササイズ|Көнүгүү|運動',
  ht_tpl_hint: 'Шаблонът дава цветове, музика и подсказки за надписите. При примера — сменя и примера.|Шаблон задаёт цвета, музыку и подсказки для подписей. В примере — меняет и пример.|Шаблон задає кольори, музику й підказки для підписів. У прикладі — змінює й приклад.|The template sets colours, music and caption hints. In the sample it also swaps the sample.|Die Vorlage bestimmt Farben, Musik und Texthinweise. Im Beispiel wechselt sie auch das Beispiel.|Le modèle définit couleurs, musique et suggestions de texte. Dans l’exemple, il change aussi l’exemple.|La plantilla define colores, música y sugerencias de texto. En el ejemplo, también cambia el ejemplo.|La plantilla define colores, música y sugerencias de texto. En el ejemplo, también cambia el ejemplo.|Il modello imposta colori, musica e suggerimenti per le didascalie. Nell’esempio cambia anche l’esempio.|O modelo define cores, música e sugestões de legenda. No exemplo, também troca o exemplo.|يحدد القالب الألوان والموسيقى واقتراحات النصوص. في المثال يغيّر المثال أيضًا.|टेम्पलेट रंग, संगीत और कैप्शन सुझाव तय करता है। नमूने में यह नमूना भी बदलता है।|テンプレートで色・音楽・字幕の候補が決まります。サンプルではサンプル自体も切り替わります。|Шаблон түстөрдү, музыканы жана жазуу боюнча кеңештерди берет. Үлгүдө үлгүнү да алмаштырат.|範本決定顏色、音樂與字幕提示；在範例中也會切換範例。',
  ht_lang: 'Език на надписите и гласа|Язык подписей и голоса|Мова підписів і голосу|Language of captions and voice|Sprache für Texte und Stimme|Langue des textes et de la voix|Idioma de textos y voz|Idioma de textos y voz|Lingua di testi e voce|Idioma das legendas e da voz|لغة النصوص والصوت|कैप्शन और आवाज़ की भाषा|字幕と音声の言語|Жазуулардын жана үндүн тили|字幕與語音語言',
  ht_f_title: 'Заглавие на урока|Название урока|Назва уроку|Lesson title|Titel der Lektion|Titre de la leçon|Título de la lección|Título de la lección|Titolo della lezione|Título da aula|عنوان الدرس|पाठ का शीर्षक|レッスンのタイトル|Сабактын аталышы|教學標題',
  ht_f_sub: 'Подзаглавие (празно = автоматично)|Подзаголовок (пусто = автоматически)|Підзаголовок (порожньо = автоматично)|Subtitle (empty = automatic)|Untertitel (leer = automatisch)|Sous-titre (vide = automatique)|Subtítulo (vacío = automático)|Subtítulo (vacío = automático)|Sottotitolo (vuoto = automatico)|Subtítulo (vazio = automático)|عنوان فرعي (فارغ = تلقائي)|उपशीर्षक (खाली = स्वचालित)|サブタイトル（空欄＝自動）|Кошумча аталыш (бош = автоматтык)|副標題（留空＝自動）',
  ht_f_outro: 'Текст на финалния екран|Текст финального экрана|Текст фінального екрана|Final screen text|Text des Abschlussbildes|Texte de l’écran final|Texto de la pantalla final|Texto de la pantalla final|Testo della schermata finale|Texto da tela final|نص الشاشة الأخيرة|अंतिम स्क्रीन का पाठ|最後の画面のテキスト|Акыркы экрандын тексти|結尾畫面文字',
  ht_steps: 'Стъпки ({0})|Шаги ({0})|Кроки ({0})|Steps ({0})|Schritte ({0})|Étapes ({0})|Pasos ({0})|Pasos ({0})|Passaggi ({0})|Passos ({0})|الخطوات ({0})|चरण ({0})|ステップ（{0}）|Кадамдар ({0})|步驟（{0}）',
  ht_empty: 'Още няма стъпки. Снимай или избери клипове и снимки — всеки файл става отделна стъпка.|Шагов пока нет. Снимите или выберите клипы и фото — каждый файл станет отдельным шагом.|Кроків ще немає. Зніміть або виберіть кліпи й фото — кожен файл стане окремим кроком.|No steps yet. Shoot or pick clips and photos — each file becomes a separate step.|Noch keine Schritte. Filme oder wähle Clips und Fotos — jede Datei wird ein eigener Schritt.|Aucune étape. Filmez ou choisissez des clips et photos — chaque fichier devient une étape.|Aún no hay pasos. Graba o elige clips y fotos: cada archivo será un paso.|Aún no hay pasos. Graba o elige clips y fotos: cada archivo será un paso.|Nessun passaggio. Riprendi o scegli clip e foto: ogni file diventa un passaggio.|Ainda não há passos. Grave ou escolha clipes e fotos — cada arquivo vira um passo.|لا توجد خطوات بعد. صوّر أو اختر مقاطع وصورًا — كل ملف يصبح خطوة.|अभी कोई चरण नहीं। क्लिप और फ़ोटो लें या चुनें — हर फ़ाइल एक अलग चरण बनेगी।|まだステップがありません。クリップや写真を撮影・選択すると、1ファイルが1ステップになります。|Азырынча кадам жок. Клип же сүрөт тартыңыз же тандаңыз — ар бир файл өзүнчө кадам болот.|尚無步驟。拍攝或選擇影片與照片 — 每個檔案就是一個步驟。',
  ht_add: '➕ Добави клипове/снимки|➕ Добавить клипы/фото|➕ Додати кліпи/фото|➕ Add clips/photos|➕ Clips/Fotos hinzufügen|➕ Ajouter clips/photos|➕ Añadir clips/fotos|➕ Agregar clips/fotos|➕ Aggiungi clip/foto|➕ Adicionar clipes/fotos|➕ أضف مقاطع/صورًا|➕ क्लिप/फ़ोटो जोड़ें|➕ クリップ/写真を追加|➕ Клип/сүрөт кошуу|➕ 新增影片/照片',
  ht_shoot: '📷 Снимай стъпка|📷 Снять шаг|📷 Зняти крок|📷 Shoot a step|📷 Schritt aufnehmen|📷 Filmer une étape|📷 Grabar un paso|📷 Grabar un paso|📷 Riprendi un passaggio|📷 Gravar um passo|📷 صوّر خطوة|📷 चरण शूट करें|📷 ステップを撮影|📷 Кадамды тартуу|📷 拍攝步驟',
  ht_shoot_clip: '🎥 Заснеми клип|🎥 Снять клип|🎥 Зняти кліп|🎥 Record a clip|🎥 Clip aufnehmen|🎥 Filmer un clip|🎥 Grabar un clip|🎥 Grabar un clip|🎥 Registra una clip|🎥 Gravar um clipe|🎥 صوّر مقطعًا|🎥 क्लिप रिकॉर्ड करें|🎥 クリップを撮影|🎥 Клип тартуу|🎥 錄製影片',
  ht_step: 'Стъпка {0}|Шаг {0}|Крок {0}|Step {0}|Schritt {0}|Étape {0}|Paso {0}|Paso {0}|Passo {0}|Passo {0}|الخطوة {0}|चरण {0}|ステップ {0}|Кадам {0}|步驟 {0}',
  ht_caption_ph: 'Надпис: какво се прави в тази стъпка…|Подпись: что делается на этом шаге…|Підпис: що робиться на цьому кроці…|Caption: what happens in this step…|Text: was in diesem Schritt passiert…|Texte : ce qui se passe à cette étape…|Texto: qué se hace en este paso…|Texto: qué se hace en este paso…|Testo: cosa si fa in questo passaggio…|Legenda: o que acontece neste passo…|النص: ماذا يحدث في هذه الخطوة…|कैप्शन: इस चरण में क्या होता है…|字幕：このステップで行うこと…|Жазуу: бул кадамда эмне жасалат…|字幕：這個步驟要做什麼…',
  ht_dur: 'Секунди на екрана|Секунд на экране|Секунд на екрані|Seconds on screen|Sekunden im Bild|Secondes à l’écran|Segundos en pantalla|Segundos en pantalla|Secondi a schermo|Segundos na tela|ثوانٍ على الشاشة|स्क्रीन पर सेकंड|表示秒数|Экрандагы секунд|顯示秒數',
  ht_clip_from: 'Откъс от секунда|Фрагмент с секунды|Фрагмент із секунди|Clip starts at second|Ausschnitt ab Sekunde|Extrait à partir de (s)|Fragmento desde el segundo|Fragmento desde el segundo|Spezzone dal secondo|Trecho a partir do segundo|المقطع يبدأ من الثانية|क्लिप इस सेकंड से|切り出し開始（秒）|Үзүндү секунддан|片段起點（秒）',
  ht_mark: '✏ Отбележи върху кадъра|✏ Отметить на кадре|✏ Позначити на кадрі|✏ Mark on the frame|✏ Im Bild markieren|✏ Annoter l’image|✏ Marcar en la imagen|✏ Marcar en la imagen|✏ Segna sul fotogramma|✏ Marcar na imagem|✏ ضع علامات على اللقطة|✏ फ़्रेम पर निशान लगाएँ|✏ 画面に書き込む|✏ Кадрга белги коюу|✏ 在畫面上標註',
  ht_mark_done: '✓ Готово|✓ Готово|✓ Готово|✓ Done|✓ Fertig|✓ Terminé|✓ Listo|✓ Listo|✓ Fatto|✓ Pronto|✓ تم|✓ हो गया|✓ 完了|✓ Даяр|✓ 完成',
  ht_ann_arrow: '➜ Стрелка|➜ Стрелка|➜ Стрілка|➜ Arrow|➜ Pfeil|➜ Flèche|➜ Flecha|➜ Flecha|➜ Freccia|➜ Seta|➜ سهم|➜ तीर|➜ 矢印|➜ Жебе|➜ 箭頭',
  ht_ann_circle: '◯ Кръг|◯ Круг|◯ Коло|◯ Circle|◯ Kreis|◯ Cercle|◯ Círculo|◯ Círculo|◯ Cerchio|◯ Círculo|◯ دائرة|◯ घेरा|◯ 円|◯ Тегерек|◯ 圓圈',
  ht_ann_line: '▁ Подчертай|▁ Подчеркнуть|▁ Підкреслити|▁ Underline|▁ Unterstreichen|▁ Souligner|▁ Subrayar|▁ Subrayar|▁ Sottolinea|▁ Sublinhar|▁ تسطير|▁ रेखांकित करें|▁ 下線|▁ Астын сызуу|▁ 底線',
  ht_undo: '↶ Отмени|↶ Отменить|↶ Скасувати|↶ Undo|↶ Rückgängig|↶ Annuler|↶ Deshacer|↶ Deshacer|↶ Annulla|↶ Desfazer|↶ تراجع|↶ पूर्ववत|↶ 元に戻す|↶ Артка кайтаруу|↶ 復原',
  ht_clear: '✕ Изчисти|✕ Очистить|✕ Очистити|✕ Clear|✕ Leeren|✕ Effacer|✕ Borrar|✕ Borrar|✕ Cancella|✕ Limpar|✕ مسح|✕ साफ़ करें|✕ 消去|✕ Тазалоо|✕ 清除',
  ht_ann_hint: 'Плъзни с пръст върху кадъра, за да нарисуваш. Отметките се изрисуват постепенно във видеото.|Проведите пальцем по кадру, чтобы нарисовать. В видео отметки прорисовываются постепенно.|Проведіть пальцем по кадру, щоб намалювати. У відео позначки промальовуються поступово.|Drag your finger over the frame to draw. Marks are drawn in gradually in the video.|Mit dem Finger über das Bild ziehen, um zu zeichnen. Im Video erscheinen die Markierungen nach und nach.|Glissez le doigt sur l’image pour dessiner. Dans la vidéo, les annotations se tracent progressivement.|Desliza el dedo sobre la imagen para dibujar. En el vídeo, las marcas se dibujan poco a poco.|Desliza el dedo sobre la imagen para dibujar. En el video, las marcas se dibujan poco a poco.|Trascina il dito sul fotogramma per disegnare. Nel video i segni appaiono gradualmente.|Arraste o dedo sobre a imagem para desenhar. No vídeo, as marcas aparecem aos poucos.|اسحب إصبعك على اللقطة للرسم. تظهر العلامات تدريجيًا في الفيديو.|चित्र बनाने के लिए फ़्रेम पर उंगली खींचें। वीडियो में निशान धीरे-धीरे बनते हैं।|指でなぞって描きます。動画では印が少しずつ描かれます。|Тартуу үчүн кадрдын үстүнөн манжаңызды жылдырыңыз. Видеодо белгилер акырындап пайда болот.|用手指在畫面上拖曳即可繪製；影片中標註會逐步畫出。',
  ht_up: 'Нагоре|Выше|Вище|Move up|Nach oben|Monter|Subir|Subir|Su|Subir|للأعلى|ऊपर|上へ|Жогору|上移',
  ht_down: 'Надолу|Ниже|Нижче|Move down|Nach unten|Descendre|Bajar|Bajar|Giù|Descer|للأسفل|नीचे|下へ|Төмөн|下移',
  ht_remove: 'Премахни|Удалить|Видалити|Remove|Entfernen|Supprimer|Quitar|Quitar|Rimuovi|Remover|إزالة|हटाएँ|削除|Өчүрүү|移除',
  ht_rec: '🎙 Запиши глас|🎙 Записать голос|🎙 Записати голос|🎙 Record voice|🎙 Stimme aufnehmen|🎙 Enregistrer la voix|🎙 Grabar voz|🎙 Grabar voz|🎙 Registra la voce|🎙 Gravar voz|🎙 سجّل صوتك|🎙 आवाज़ रिकॉर्ड करें|🎙 音声を録音|🎙 Үн жаздыруу|🎙 錄製語音',
  ht_rec_stop: '⏹ Спри записа ({0} сек.)|⏹ Остановить запись ({0} с)|⏹ Зупинити запис ({0} с)|⏹ Stop recording ({0} s)|⏹ Aufnahme stoppen ({0} s)|⏹ Arrêter ({0} s)|⏹ Detener ({0} s)|⏹ Detener ({0} s)|⏹ Ferma ({0} s)|⏹ Parar ({0} s)|⏹ إيقاف التسجيل ({0} ث)|⏹ रिकॉर्डिंग रोकें ({0} से.)|⏹ 録音停止（{0} 秒）|⏹ Токтотуу ({0} сек.)|⏹ 停止錄音（{0} 秒）',
  ht_speak: '🔊 Прочети надписа|🔊 Прочитать подпись|🔊 Прочитати підпис|🔊 Read the caption|🔊 Text vorlesen|🔊 Lire le texte|🔊 Leer el texto|🔊 Leer el texto|🔊 Leggi il testo|🔊 Ler a legenda|🔊 اقرأ النص|🔊 कैप्शन पढ़ें|🔊 字幕を読み上げ|🔊 Жазууну окуу|🔊 朗讀字幕',
  ht_rec_tts: '🔊→🎙 Запиши синтеза|🔊→🎙 Записать синтез|🔊→🎙 Записати синтез|🔊→🎙 Record the synth voice|🔊→🎙 Sprachausgabe aufnehmen|🔊→🎙 Enregistrer la synthèse|🔊→🎙 Grabar la voz sintética|🔊→🎙 Grabar la voz sintética|🔊→🎙 Registra la sintesi|🔊→🎙 Gravar a voz sintética|🔊→🎙 سجّل الصوت المُركّب|🔊→🎙 संश्लेषित आवाज़ रिकॉर्ड करें|🔊→🎙 合成音声を録音|🔊→🎙 Синтезди жаздыруу|🔊→🎙 錄下合成語音',
  ht_voice_len: '▶ Глас {0} сек.|▶ Голос {0} с|▶ Голос {0} с|▶ Voice {0} s|▶ Stimme {0} s|▶ Voix {0} s|▶ Voz {0} s|▶ Voz {0} s|▶ Voce {0} s|▶ Voz {0} s|▶ صوت {0} ث|▶ आवाज़ {0} से.|▶ 音声 {0} 秒|▶ Үн {0} сек.|▶ 語音 {0} 秒',
  ht_voice_del: 'Изтрий гласа|Удалить голос|Видалити голос|Delete voice|Stimme löschen|Supprimer la voix|Borrar voz|Borrar voz|Elimina voce|Apagar voz|احذف الصوت|आवाज़ हटाएँ|音声を削除|Үндү өчүрүү|刪除語音',
  ht_sound: 'Звук и формат|Звук и формат|Звук і формат|Sound and format|Ton und Format|Son et format|Sonido y formato|Sonido y formato|Audio e formato|Som e formato|الصوت والتنسيق|ध्वनि और फ़ॉर्मेट|音と形式|Үн жана формат|聲音與格式',
  ht_voice: 'Гласов коментар|Голосовой комментарий|Голосовий коментар|Voice-over|Sprachkommentar|Commentaire vocal|Comentario de voz|Comentario de voz|Commento vocale|Narração|تعليق صوتي|वॉइस-ओवर|ナレーション|Үн менен түшүндүрмө|語音旁白',
  ht_voice_mine: 'Моите записи (влизат във видеото)|Мои записи (входят в видео)|Мої записи (входять у відео)|My recordings (go into the video)|Meine Aufnahmen (kommen ins Video)|Mes enregistrements (dans la vidéo)|Mis grabaciones (van en el vídeo)|Mis grabaciones (van en el video)|Le mie registrazioni (nel video)|Minhas gravações (entram no vídeo)|تسجيلاتي (تدخل في الفيديو)|मेरी रिकॉर्डिंग (वीडियो में जाती हैं)|自分の録音（動画に入る）|Менин жазууларым (видеого кирет)|我的錄音（放進影片）',
  ht_voice_tts: 'Синтез на реч — чете надписите при прегледа|Синтез речи — читает подписи при просмотре|Синтез мовлення — читає підписи під час перегляду|Speech synthesis — reads captions in the preview|Sprachausgabe — liest die Texte in der Vorschau|Synthèse vocale — lit les textes dans l’aperçu|Síntesis de voz: lee los textos en la vista previa|Síntesis de voz: lee los textos en la vista previa|Sintesi vocale — legge i testi nell’anteprima|Síntese de voz — lê as legendas na prévia|تركيب الكلام — يقرأ النصوص أثناء المعاينة|वाक् संश्लेषण — पूर्वावलोकन में कैप्शन पढ़ता है|音声合成 — プレビューで字幕を読み上げ|Кеп синтези — көрүүдө жазууларды окуйт|語音合成 — 預覽時朗讀字幕',
  ht_voice_none: 'Без глас|Без голоса|Без голосу|No voice|Ohne Stimme|Sans voix|Sin voz|Sin voz|Senza voce|Sem voz|بدون صوت|बिना आवाज़|音声なし|Үнсүз|無語音',
  ht_voice_hint: 'За синтеза във видеото: „🔊→🎙 Запиши синтеза" при стъпката (телефонът чете, микрофонът записва).|Чтобы синтез попал в видео: «🔊→🎙 Записать синтез» у шага (телефон читает, микрофон записывает).|Щоб синтез потрапив у відео: «🔊→🎙 Записати синтез» біля кроку (телефон читає, мікрофон записує).|To put the synth voice into the video: “🔊→🎙 Record the synth voice” on a step (the phone reads, the mic records).|Für die Sprachausgabe im Video: „🔊→🎙 Sprachausgabe aufnehmen" beim Schritt (Telefon liest, Mikrofon nimmt auf).|Pour mettre la synthèse dans la vidéo : « 🔊→🎙 Enregistrer la synthèse » sur l’étape (le téléphone lit, le micro enregistre).|Para poner la voz sintética en el vídeo: «🔊→🎙 Grabar la voz sintética» en el paso (el teléfono lee y el micrófono graba).|Para poner la voz sintética en el video: «🔊→🎙 Grabar la voz sintética» en el paso (el teléfono lee y el micrófono graba).|Per mettere la sintesi nel video: «🔊→🎙 Registra la sintesi» sul passaggio (il telefono legge, il microfono registra).|Para colocar a voz sintética no vídeo: “🔊→🎙 Gravar a voz sintética” no passo (o telefone lê, o microfone grava).|لإدخال الصوت المُركّب في الفيديو: «🔊→🎙 سجّل الصوت المُركّب» عند الخطوة (الهاتف يقرأ والميكروفون يسجّل).|संश्लेषित आवाज़ वीडियो में डालने के लिए: चरण पर “🔊→🎙 संश्लेषित आवाज़ रिकॉर्ड करें” (फ़ोन पढ़ता है, माइक रिकॉर्ड करता है)।|合成音声を動画に入れるには、ステップの「🔊→🎙 合成音声を録音」（端末が読み上げ、マイクが録音）。|Синтезди видеого киргизүү үчүн: кадамдагы «🔊→🎙 Синтезди жаздыруу» (телефон окуйт, микрофон жазат).|要把合成語音放進影片：在步驟按「🔊→🎙 錄下合成語音」（手機朗讀、麥克風錄音）。',
  ht_music: 'Фонова музика (генерира се в апа)|Фоновая музыка (создаётся в приложении)|Фонова музика (створюється в застосунку)|Background music (generated in the app)|Hintergrundmusik (in der App erzeugt)|Musique de fond (générée dans l’appli)|Música de fondo (generada en la app)|Música de fondo (generada en la app)|Musica di sottofondo (generata nell’app)|Música de fundo (gerada no app)|موسيقى خلفية (تُولَّد في التطبيق)|पृष्ठभूमि संगीत (ऐप में बनता है)|BGM（アプリ内で生成）|Фон музыкасы (колдонмодо түзүлөт)|背景音樂（於 App 內生成）',
  ht_music_none: 'Без музика|Без музыки|Без музики|No music|Keine Musik|Sans musique|Sin música|Sin música|Senza musica|Sem música|بدون موسيقى|बिना संगीत|音楽なし|Музыкасыз|無音樂',
  ht_music_calm: 'Спокойна|Спокойная|Спокійна|Calm|Ruhig|Calme|Tranquila|Tranquila|Calma|Calma|هادئة|शांत|穏やか|Токтоо|平靜',
  ht_music_upbeat: 'Бодра|Бодрая|Бадьора|Upbeat|Schwungvoll|Entraînante|Animada|Animada|Vivace|Animada|حيوية|जोशीली|アップテンポ|Шайыр|輕快',
  ht_music_cozy: 'Уютна|Уютная|Затишна|Cozy|Gemütlich|Douce|Acogedora|Acogedora|Accogliente|Aconchegante|دافئة|सुकूनभरी|くつろぎ|Жылуу|溫馨',
  ht_music_try: '▶ Чуй|▶ Слушать|▶ Слухати|▶ Listen|▶ Anhören|▶ Écouter|▶ Escuchar|▶ Escuchar|▶ Ascolta|▶ Ouvir|▶ استمع|▶ सुनें|▶ 試聴|▶ Угуу|▶ 試聽',
  ht_format: 'Формат на видеото|Формат видео|Формат відео|Video format|Videoformat|Format vidéo|Formato de vídeo|Formato de video|Formato video|Formato do vídeo|تنسيق الفيديو|वीडियो फ़ॉर्मेट|動画の形式|Видео формат|影片格式',
  ht_fmt_portrait: 'Вертикален 9:16|Вертикальный 9:16|Вертикальний 9:16|Vertical 9:16|Hochformat 9:16|Vertical 9:16|Vertical 9:16|Vertical 9:16|Verticale 9:16|Vertical 9:16|عمودي 9:16|वर्टिकल 9:16|縦 9:16|Тик 9:16|直式 9:16',
  ht_fmt_landscape: 'Хоризонтален 16:9|Горизонтальный 16:9|Горизонтальний 16:9|Horizontal 16:9|Querformat 16:9|Horizontal 16:9|Horizontal 16:9|Horizontal 16:9|Orizzontale 16:9|Horizontal 16:9|أفقي 16:9|हॉरिज़ॉन्टल 16:9|横 16:9|Туурасынан 16:9|橫式 16:9',
  ht_fmt_square: 'Квадрат 1:1|Квадрат 1:1|Квадрат 1:1|Square 1:1|Quadrat 1:1|Carré 1:1|Cuadrado 1:1|Cuadrado 1:1|Quadrato 1:1|Quadrado 1:1|مربع 1:1|वर्ग 1:1|正方形 1:1|Чарчы 1:1|方形 1:1',
  ht_fps: 'Плавност|Плавность|Плавність|Smoothness|Flüssigkeit|Fluidité|Fluidez|Fluidez|Fluidità|Fluidez|السلاسة|स्मूदनेस|なめらかさ|Жумшактык|流暢度',
  ht_fps_fast: 'Бързо изнасяне (10 кадъра/сек)|Быстро (10 кадров/с)|Швидко (10 кадрів/с)|Fast export (10 fps)|Schnell (10 B/s)|Rapide (10 i/s)|Rápido (10 fps)|Rápido (10 fps)|Veloce (10 fps)|Rápido (10 qps)|سريع (10 إطارات/ث)|तेज़ (10 fps)|高速（10 fps）|Тез (10 кадр/сек)|快速（10 fps）',
  ht_fps_smooth: 'Плавно (20 кадъра/сек)|Плавно (20 кадров/с)|Плавно (20 кадрів/с)|Smooth (20 fps)|Flüssig (20 B/s)|Fluide (20 i/s)|Fluido (20 fps)|Fluido (20 fps)|Fluido (20 fps)|Suave (20 qps)|سلس (20 إطارًا/ث)|स्मूद (20 fps)|なめらか（20 fps）|Жумшак (20 кадр/сек)|流暢（20 fps）',
  ht_export: 'Изнеси урока|Сохранить урок|Зберегти урок|Export the lesson|Lektion exportieren|Exporter la leçon|Exportar la lección|Exportar la lección|Esporta la lezione|Exportar a aula|تصدير الدرس|पाठ सहेजें|レッスンを書き出す|Сабакты сактоо|匯出教學',
  ht_exp_mp4: '🎬 Видео урок (MP4)|🎬 Видеоурок (MP4)|🎬 Відеоурок (MP4)|🎬 Video lesson (MP4)|🎬 Video-Lektion (MP4)|🎬 Leçon vidéo (MP4)|🎬 Videolección (MP4)|🎬 Videolección (MP4)|🎬 Video lezione (MP4)|🎬 Videoaula (MP4)|🎬 درس فيديو (MP4)|🎬 वीडियो पाठ (MP4)|🎬 動画レッスン（MP4）|🎬 Видео сабак (MP4)|🎬 影片教學（MP4）',
  ht_exp_gif: '🎞 GIF инструкция|🎞 GIF-инструкция|🎞 GIF-інструкція|🎞 GIF guide|🎞 GIF-Anleitung|🎞 Tutoriel GIF|🎞 Guía GIF|🎞 Guía GIF|🎞 Guida GIF|🎞 Guia em GIF|🎞 دليل GIF|🎞 GIF गाइड|🎞 GIF マニュアル|🎞 GIF нускама|🎞 GIF 教學',
  ht_exp_pdf: '📄 Лист за печат (PDF)|📄 Лист для печати (PDF)|📄 Аркуш для друку (PDF)|📄 Printable sheet (PDF)|📄 Druckblatt (PDF)|📄 Fiche à imprimer (PDF)|📄 Hoja para imprimir (PDF)|📄 Hoja para imprimir (PDF)|📄 Scheda da stampare (PDF)|📄 Folha para imprimir (PDF)|📄 ورقة للطباعة (PDF)|📄 प्रिंट शीट (PDF)|📄 印刷用シート（PDF）|📄 Басып чыгаруу барагы (PDF)|📄 列印說明單（PDF）',
  ht_exp_png: '🖼 Лист като снимка (PNG)|🖼 Лист как картинка (PNG)|🖼 Аркуш як зображення (PNG)|🖼 Sheet as image (PNG)|🖼 Blatt als Bild (PNG)|🖼 Fiche en image (PNG)|🖼 Hoja como imagen (PNG)|🖼 Hoja como imagen (PNG)|🖼 Scheda come immagine (PNG)|🖼 Folha como imagem (PNG)|🖼 الورقة كصورة (PNG)|🖼 शीट छवि के रूप में (PNG)|🖼 シートを画像で（PNG）|🖼 Барак сүрөт катары (PNG)|🖼 說明單圖片（PNG）',
  ht_drawing: 'Рисувам кадрите… {0}%|Рисую кадры… {0}%|Малюю кадри… {0}%|Drawing frames… {0}%|Bilder werden gezeichnet… {0}%|Dessin des images… {0}%|Dibujando fotogramas… {0}%|Dibujando cuadros… {0}%|Disegno i fotogrammi… {0}%|Desenhando quadros… {0}%|رسم اللقطات… {0}%|फ़्रेम बन रहे हैं… {0}%|フレームを描画中… {0}%|Кадрлар тартылууда… {0}%|繪製畫面中… {0}%',
  ht_mixing: 'Генерирам музиката и смесвам гласа…|Создаю музыку и свожу голос…|Створюю музику й зводжу голос…|Generating music and mixing the voice…|Musik wird erzeugt und Stimme gemischt…|Génération de la musique et mixage de la voix…|Generando música y mezclando la voz…|Generando música y mezclando la voz…|Genero la musica e mixo la voce…|Gerando música e mixando a voz…|توليد الموسيقى ومزج الصوت…|संगीत बन रहा है और आवाज़ मिलाई जा रही है…|音楽を生成し音声をミックス中…|Музыка түзүлүп, үн аралаштырылууда…|生成音樂並混合語音中…',
  ht_encoding: 'Кодирам… {0}%|Кодирую… {0}%|Кодую… {0}%|Encoding… {0}%|Kodiere… {0}%|Encodage… {0}%|Codificando… {0}%|Codificando… {0}%|Codifica… {0}%|Codificando… {0}%|جارٍ الترميز… {0}%|एन्कोड हो रहा… {0}%|エンコード中… {0}%|Коддолууда… {0}%|編碼中… {0}%',
  ht_engine: 'Зареждам видео двигателя (първия път отнема няколко секунди)…|Загружаю видеодвижок (в первый раз несколько секунд)…|Завантажую відеорушій (уперше кілька секунд)…|Loading the video engine (a few seconds the first time)…|Video-Engine wird geladen (beim ersten Mal einige Sekunden)…|Chargement du moteur vidéo (quelques secondes la première fois)…|Cargando el motor de vídeo (unos segundos la primera vez)…|Cargando el motor de video (unos segundos la primera vez)…|Carico il motore video (qualche secondo la prima volta)…|Carregando o motor de vídeo (alguns segundos na primeira vez)…|تحميل محرك الفيديو (بضع ثوانٍ في المرة الأولى)…|वीडियो इंजन लोड हो रहा है (पहली बार कुछ सेकंड)…|動画エンジンを読み込み中（初回は数秒）…|Видео кыймылдаткычы жүктөлүүдө (биринчи жолу бир нече секунд)…|載入影片引擎中（首次需數秒）…',
  ht_done: 'Готово! „{0}" ({1}) е записан/споделен.|Готово! «{0}» ({1}) сохранён/отправлен.|Готово! «{0}» ({1}) збережено/надіслано.|Done! “{0}” ({1}) was saved/shared.|Fertig! „{0}" ({1}) gespeichert/geteilt.|Terminé ! « {0} » ({1}) enregistré/partagé.|¡Listo! «{0}» ({1}) guardado/compartido.|¡Listo! «{0}» ({1}) guardado/compartido.|Fatto! «{0}» ({1}) salvato/condiviso.|Pronto! “{0}” ({1}) salvo/compartilhado.|تم! «{0}» ({1}) حُفظ/شورك.|हो गया! “{0}” ({1}) सहेजा/साझा किया गया।|完了！「{0}」（{1}）を保存/共有しました。|Даяр! «{0}» ({1}) сакталды/бөлүшүлдү.|完成！「{0}」（{1}）已儲存/分享。',
  ht_need_steps: 'Добави поне една стъпка.|Добавьте хотя бы один шаг.|Додайте хоча б один крок.|Add at least one step.|Füge mindestens einen Schritt hinzu.|Ajoutez au moins une étape.|Añade al menos un paso.|Agrega al menos un paso.|Aggiungi almeno un passaggio.|Adicione pelo menos um passo.|أضف خطوة واحدة على الأقل.|कम से कम एक चरण जोड़ें।|ステップを1つ以上追加してください。|Жок дегенде бир кадам кошуңуз.|請至少新增一個步驟。',
  ht_err: 'Грешка: {0}|Ошибка: {0}|Помилка: {0}|Error: {0}|Fehler: {0}|Erreur : {0}|Error: {0}|Error: {0}|Errore: {0}|Erro: {0}|خطأ: {0}|त्रुटि: {0}|エラー: {0}|Ката: {0}|錯誤：{0}',
  ht_mic_denied: 'Няма достъп до микрофона — разреши го в настройките на телефона.|Нет доступа к микрофону — разрешите его в настройках телефона.|Немає доступу до мікрофона — дозвольте його в налаштуваннях телефона.|No microphone access — allow it in the phone settings.|Kein Mikrofonzugriff — in den Telefoneinstellungen erlauben.|Pas d’accès au micro — autorisez-le dans les réglages du téléphone.|Sin acceso al micrófono: permítelo en los ajustes del teléfono.|Sin acceso al micrófono: permítelo en la configuración del teléfono.|Nessun accesso al microfono: consentilo nelle impostazioni del telefono.|Sem acesso ao microfone — permita nas configurações do telefone.|لا يوجد وصول إلى الميكروفون — اسمح به من إعدادات الهاتف.|माइक्रोफ़ोन की अनुमति नहीं — फ़ोन की सेटिंग में अनुमति दें।|マイクにアクセスできません — 端末の設定で許可してください。|Микрофонго уруксат жок — телефондун жөндөөлөрүнөн уруксат бериңиз.|無法使用麥克風 — 請在手機設定中允許。',
  ht_mic_none: 'Микрофонът не е достъпен на това устройство.|Микрофон недоступен на этом устройстве.|Мікрофон недоступний на цьому пристрої.|The microphone is not available on this device.|Das Mikrofon ist auf diesem Gerät nicht verfügbar.|Le micro n’est pas disponible sur cet appareil.|El micrófono no está disponible en este dispositivo.|El micrófono no está disponible en este dispositivo.|Il microfono non è disponibile su questo dispositivo.|O microfone não está disponível neste aparelho.|الميكروفون غير متاح على هذا الجهاز.|इस डिवाइस पर माइक्रोफ़ोन उपलब्ध नहीं है।|この端末ではマイクを使用できません。|Бул түзмөктө микрофон жеткиликсиз.|此裝置無法使用麥克風。',
  ht_tts_none: 'Синтезът на реч не е наличен на това устройство.|Синтез речи недоступен на этом устройстве.|Синтез мовлення недоступний на цьому пристрої.|Speech synthesis is not available on this device.|Sprachausgabe ist auf diesem Gerät nicht verfügbar.|La synthèse vocale n’est pas disponible sur cet appareil.|La síntesis de voz no está disponible en este dispositivo.|La síntesis de voz no está disponible en este dispositivo.|La sintesi vocale non è disponibile su questo dispositivo.|A síntese de voz não está disponível neste aparelho.|تركيب الكلام غير متاح على هذا الجهاز.|इस डिवाइस पर वाक् संश्लेषण उपलब्ध नहीं है।|この端末では音声合成を使用できません。|Бул түзмөктө кеп синтези жеткиликсиз.|此裝置無法使用語音合成。',
  ht_import_conv: 'Подготвям клипа „{0}" (еднократно преобразуване)…|Подготавливаю клип «{0}» (однократное преобразование)…|Готую кліп «{0}» (одноразове перетворення)…|Preparing clip “{0}” (one-time conversion)…|Clip „{0}" wird vorbereitet (einmalige Umwandlung)…|Préparation du clip « {0} » (conversion unique)…|Preparando el clip «{0}» (conversión única)…|Preparando el clip «{0}» (conversión única)…|Preparo la clip «{0}» (conversione una tantum)…|Preparando o clipe “{0}” (conversão única)…|تجهيز المقطع «{0}» (تحويل لمرة واحدة)…|क्लिप “{0}” तैयार हो रही है (एक बार का रूपांतरण)…|クリップ「{0}」を準備中（初回のみ変換）…|«{0}» клиби даярдалууда (бир жолку айландыруу)…|正在準備影片「{0}」（僅轉換一次）…',
  ht_import_err: 'Файлът „{0}" не може да се отвори.|Файл «{0}» не удаётся открыть.|Файл «{0}» не вдається відкрити.|The file “{0}” cannot be opened.|Die Datei „{0}" lässt sich nicht öffnen.|Impossible d’ouvrir le fichier « {0} ».|No se puede abrir el archivo «{0}».|No se puede abrir el archivo «{0}».|Impossibile aprire il file «{0}».|Não é possível abrir o arquivo “{0}”.|تعذّر فتح الملف «{0}».|फ़ाइल “{0}” नहीं खुल सकी।|ファイル「{0}」を開けません。|«{0}» файлын ачуу мүмкүн эмес.|無法開啟檔案「{0}」。',
  ht_saved_note: 'Работата се пази автоматично на устройството. Нищо не се качва в интернет.|Работа сохраняется автоматически на устройстве. Ничего не загружается в интернет.|Робота зберігається автоматично на пристрої. Нічого не завантажується в інтернет.|Your work is saved automatically on the device. Nothing is uploaded.|Die Arbeit wird automatisch auf dem Gerät gespeichert. Nichts wird hochgeladen.|Le travail est enregistré automatiquement sur l’appareil. Rien n’est envoyé en ligne.|El trabajo se guarda automáticamente en el dispositivo. No se sube nada.|El trabajo se guarda automáticamente en el dispositivo. No se sube nada.|Il lavoro si salva automaticamente sul dispositivo. Nulla viene caricato.|O trabalho é salvo automaticamente no aparelho. Nada é enviado.|يُحفظ عملك تلقائيًا على الجهاز. لا يُرفع أي شيء.|काम डिवाइस पर अपने-आप सहेजा जाता है। कुछ भी अपलोड नहीं होता।|作業は端末に自動保存されます。何もアップロードされません。|Иш түзмөктө автоматтык түрдө сакталат. Эч нерсе интернетке жүктөлбөйт.|作品會自動儲存在裝置上，不會上傳任何內容。',
  ht_result: 'Резултат|Результат|Результат|Result|Ergebnis|Résultat|Resultado|Resultado|Risultato|Resultado|النتيجة|परिणाम|結果|Жыйынтык|結果'
};

const DICT = {};
for (const k in RAW) {
  const parts = RAW[k].split('|');
  const row = {};
  ORDER.forEach((lg, i) => { row[lg] = parts[i] != null ? parts[i] : parts[3]; });
  DICT[k] = row;
}
register(DICT);
export const HT_KEYS = Object.keys(RAW);
// За проверка при разработка: колко части има всеки ключ (трябва да са 15).
export function htCheck() { return Object.keys(RAW).filter((k) => RAW[k].split('|').length !== 15); }
