// Version: 1.0001
// i18n.js — преводен слой за „Детегледачка" (baby-monitor) на 15-те езика на екосистемата.
// Език по подразбиране: руски (до избор от потребителя при първо стартиране).
// Самодостатъчен модул — приложението не споделя файлове с другите апове.
import { LANGUAGES, languageByCode, RTL_CODES } from './languages.js';

const LS_KEY = 'babymonitor.lang';
export const DEFAULT_LANG = 'ru';
export const FALLBACK_LANG = 'en';

export const STR = {
  // --- Избор на език / общо ---
  pick_lang: { bg:'Избери език', ru:'Выберите язык', uk:'Виберіть мову', en:'Choose language', de:'Sprache wählen', fr:'Choisir la langue', es:'Elegir idioma', 'es-MX':'Elegir idioma', it:'Scegli la lingua', pt:'Escolher idioma', ar:'اختر اللغة', hi:'भाषा चुनें', ja:'言語を選択', ky:'Тилди тандаңыз', 'zh-Hant':'選擇語言' },
  lang_btn: { bg:'🌐 Език', ru:'🌐 Язык', uk:'🌐 Мова', en:'🌐 Language', de:'🌐 Sprache', fr:'🌐 Langue', es:'🌐 Idioma', 'es-MX':'🌐 Idioma', it:'🌐 Lingua', pt:'🌐 Idioma', ar:'🌐 اللغة', hi:'🌐 भाषा', ja:'🌐 言語', ky:'🌐 Тил', 'zh-Hant':'🌐 語言' },
  start_app: { bg:'Стартирай', ru:'Запустить', uk:'Запустити', en:'Start', de:'Starten', fr:'Démarrer', es:'Iniciar', 'es-MX':'Iniciar', it:'Avvia', pt:'Iniciar', ar:'ابدأ', hi:'शुरू करें', ja:'開始', ky:'Баштоо', 'zh-Hant':'開始' },
  language: { bg:'Език', ru:'Язык', uk:'Мова', en:'Language', de:'Sprache', fr:'Langue', es:'Idioma', 'es-MX':'Idioma', it:'Lingua', pt:'Idioma', ar:'اللغة', hi:'भाषा', ja:'言語', ky:'Тил', 'zh-Hant':'語言' },
  save: { bg:'Запази', ru:'Сохранить', uk:'Зберегти', en:'Save', de:'Speichern', fr:'Enregistrer', es:'Guardar', 'es-MX':'Guardar', it:'Salva', pt:'Salvar', ar:'حفظ', hi:'सहेजें', ja:'保存', ky:'Сактоо', 'zh-Hant':'儲存' },
  saved: { bg:'Запазено', ru:'Сохранено', uk:'Збережено', en:'Saved', de:'Gespeichert', fr:'Enregistré', es:'Guardado', 'es-MX':'Guardado', it:'Salvato', pt:'Salvo', ar:'تم الحفظ', hi:'सहेजा गया', ja:'保存しました', ky:'Сакталды', 'zh-Hant':'已儲存' },

  // --- Заглавие на приложението ---
  app_title: { bg:'Детегледачка', ru:'Радионяня', uk:'Радіоняня', en:'Baby Monitor', de:'Babyphone', fr:'Babyphone', es:'Monitor de bebé', 'es-MX':'Monitor de bebé', it:'Baby monitor', pt:'Monitor de bebê', ar:'مراقب الطفل', hi:'बेबी मॉनिटर', ja:'ベビーモニター', ky:'Бала кароол', 'zh-Hant':'嬰兒監視器' },

  // --- Навигация (таб-бар) ---
  nav_watch: { bg:'Наблюдение', ru:'Наблюдение', uk:'Спостереження', en:'Watch', de:'Überwachen', fr:'Surveillance', es:'Vigilancia', 'es-MX':'Vigilancia', it:'Sorveglianza', pt:'Vigilância', ar:'المراقبة', hi:'निगरानी', ja:'監視', ky:'Көзөмөл', 'zh-Hant':'監看' },
  nav_log: { bg:'Дневник', ru:'Журнал', uk:'Журнал', en:'Log', de:'Protokoll', fr:'Journal', es:'Registro', 'es-MX':'Registro', it:'Registro', pt:'Registro', ar:'السجل', hi:'लॉग', ja:'ログ', ky:'Журнал', 'zh-Hant':'記錄' },
  nav_settings: { bg:'Настройки', ru:'Настройки', uk:'Налаштування', en:'Settings', de:'Einstellungen', fr:'Réglages', es:'Ajustes', 'es-MX':'Ajustes', it:'Impostazioni', pt:'Configurações', ar:'الإعدادات', hi:'सेटिंग्स', ja:'設定', ky:'Жөндөөлөр', 'zh-Hant':'設定' },

  // --- Предупреждение за безопасност (НЕ омекотявай) ---
  safety_strong: { bg:'Внимание: това НЕ е сертифицирано устройство за безопасност. ', ru:'Внимание: это НЕ сертифицированное устройство безопасности. ', uk:'Увага: це НЕ сертифікований пристрій безпеки. ', en:'Warning: this is NOT a certified safety device. ', de:'Achtung: Dies ist KEIN zertifiziertes Sicherheitsgerät. ', fr:'Attention : ceci n’est PAS un dispositif de sécurité certifié. ', es:'Atención: esto NO es un dispositivo de seguridad certificado. ', 'es-MX':'Atención: esto NO es un dispositivo de seguridad certificado. ', it:'Attenzione: questo NON è un dispositivo di sicurezza certificato. ', pt:'Atenção: isto NÃO é um dispositivo de segurança certificado. ', ar:'تنبيه: هذا ليس جهاز سلامة معتمدًا. ', hi:'चेतावनी: यह प्रमाणित सुरक्षा उपकरण नहीं है। ', ja:'警告: これは認証された安全装置ではありません。 ', ky:'Эскертүү: бул сертификацияланган коопсуздук түзмөгү ЭМЕС. ', 'zh-Hant':'警告：這不是經認證的安全裝置。 ' },
  safety_body: { bg:'Не разчитай на него за безопасността на детето. Това е помощно средство за информираност, а не бебефон или датчик за дим. Ползвай истински бебефон и датчик за дим.', ru:'Не полагайтесь на него для безопасности ребёнка. Это вспомогательное средство для осведомлённости, а не радионяня и не датчик дыма. Используйте настоящую радионяню и датчик дыма.', uk:'Не покладайтеся на нього для безпеки дитини. Це допоміжний засіб для обізнаності, а не радіоняня й не датчик диму. Використовуйте справжню радіоняню та датчик диму.', en:'Do not rely on it for your child’s safety. It is an awareness aid, not a baby monitor or smoke detector. Use a real baby monitor and smoke detector.', de:'Verlasse dich nicht darauf für die Sicherheit deines Kindes. Es ist eine Aufmerksamkeitshilfe, kein Babyphone und kein Rauchmelder. Nutze ein echtes Babyphone und einen Rauchmelder.', fr:'Ne comptez pas dessus pour la sécurité de votre enfant. C’est une aide à la vigilance, pas un babyphone ni un détecteur de fumée. Utilisez un vrai babyphone et un détecteur de fumée.', es:'No confíes en él para la seguridad de tu hijo. Es una ayuda de atención, no un monitor de bebé ni un detector de humo. Usa un monitor de bebé y un detector de humo reales.', 'es-MX':'No confíes en él para la seguridad de tu hijo. Es una ayuda de atención, no un monitor de bebé ni un detector de humo. Usa un monitor de bebé y un detector de humo reales.', it:'Non affidarti ad esso per la sicurezza del bambino. È un ausilio di attenzione, non un baby monitor né un rilevatore di fumo. Usa un vero baby monitor e un rilevatore di fumo.', pt:'Não dependa dele para a segurança da criança. É um auxílio de atenção, não um monitor de bebê nem um detector de fumaça. Use um monitor de bebê e um detector de fumaça reais.', ar:'لا تعتمد عليه لسلامة طفلك. إنه أداة مساعدة للانتباه، وليس مراقب طفل أو كاشف دخان. استخدم مراقب طفل وكاشف دخان حقيقيين.', hi:'अपने बच्चे की सुरक्षा के लिए इस पर निर्भर न रहें। यह जागरूकता सहायक है, बेबी मॉनिटर या धुआँ सेंसर नहीं। असली बेबी मॉनिटर और धुआँ सेंसर का उपयोग करें।', ja:'お子さまの安全をこれに頼らないでください。これは気づきを助ける補助であり、ベビーモニターや煙感知器ではありません。本物のベビーモニターと煙感知器を使ってください。', ky:'Балаңыздын коопсуздугу үчүн ага ишенбеңиз. Бул маалымдоо жардамчысы, радионяня же түтүн датчиги эмес. Чыныгы радионяня жана түтүн датчигин колдонуңуз.', 'zh-Hant':'請勿依賴它保障孩子安全。它只是提醒輔助，而非嬰兒監聽器或煙霧偵測器。請使用真正的嬰兒監聽器與煙霧偵測器。' },

  // --- Онбординг ---
  ob_tagline: { bg:'Нает робот, който пази спящото или играещото дете през камерата на телефона и те предупреждава.', ru:'Нанятый робот, который присматривает за спящим или играющим ребёнком через камеру телефона и предупреждает вас.', uk:'Найнятий робот, який наглядає за сплячою або граючою дитиною через камеру телефона й попереджає вас.', en:'A robot for rent that watches your sleeping or playing child through the phone camera and alerts you.', de:'Ein gemieteter Roboter, der dein schlafendes oder spielendes Kind über die Telefonkamera beobachtet und dich warnt.', fr:'Un robot en location qui surveille votre enfant endormi ou en train de jouer via la caméra du téléphone et vous alerte.', es:'Un robot de alquiler que vigila a tu hijo dormido o jugando a través de la cámara del teléfono y te avisa.', 'es-MX':'Un robot de alquiler que vigila a tu hijo dormido o jugando a través de la cámara del teléfono y te avisa.', it:'Un robot a noleggio che sorveglia il tuo bambino che dorme o gioca tramite la fotocamera del telefono e ti avvisa.', pt:'Um robô de aluguel que vigia seu filho dormindo ou brincando pela câmera do telefone e te avisa.', ar:'روبوت للإيجار يراقب طفلك النائم أو اللاعب عبر كاميرا الهاتف وينبّهك.', hi:'किराये का रोबोट जो फ़ोन कैमरे से आपके सोते या खेलते बच्चे पर नज़र रखता है और आपको सचेत करता है।', ja:'スマホのカメラで眠っている、または遊んでいるお子さまを見守り、あなたに知らせるレンタルロボットです。', ky:'Телефон камерасы аркылуу уктап жаткан же ойноп жаткан балаңызды кайтарып, сизди эскерткен ижарага алынган робот.', 'zh-Hant':'一個出租機器人，透過手機相機看顧您熟睡或玩耍的孩子並提醒您。' },
  ob_what_title: { bg:'Какво прави', ru:'Что делает', uk:'Що робить', en:'What it does', de:'Was es tut', fr:'Ce qu’il fait', es:'Qué hace', 'es-MX':'Qué hace', it:'Cosa fa', pt:'O que faz', ar:'ماذا يفعل', hi:'यह क्या करता है', ja:'できること', ky:'Эмне кылат', 'zh-Hant':'它的功能' },
  ob_li_motion: { bg:'Следи за движение: спи спокойно / размърдва се / „събуди се".', ru:'Следит за движением: спит спокойно / шевелится / «проснулся».', uk:'Стежить за рухом: спить спокійно / ворушиться / «прокинувся».', en:'Watches for motion: sleeping calmly / stirring / “awake”.', de:'Achtet auf Bewegung: schläft ruhig / regt sich / „wach".', fr:'Surveille le mouvement : dort calmement / s’agite / « réveillé ».', es:'Vigila el movimiento: duerme tranquilo / se mueve / «despierto».', 'es-MX':'Vigila el movimiento: duerme tranquilo / se mueve / «despierto».', it:'Sorveglia il movimento: dorme tranquillo / si agita / «sveglio».', pt:'Observa o movimento: dormindo calmo / se mexendo / “acordado”.', ar:'يراقب الحركة: نائم بهدوء / يتحرك / «استيقظ».', hi:'गति पर नज़र रखता है: शांति से सो रहा / हिल रहा / “जाग गया”।', ja:'動きを監視: 静かに就寝中 / もぞもぞ / 「起きた」。', ky:'Кыймылды байкайт: тынч уктап жатат / кыймылдайт / «ойгонду».', 'zh-Hant':'監測動作：安睡 / 蠕動 / 「醒了」。' },
  ob_li_stranger: { bg:'Подава сигнал, ако в стаята се появи втори човек (непознат?).', ru:'Подаёт сигнал, если в комнате появляется второй человек (незнакомец?).', uk:'Подає сигнал, якщо в кімнаті з’являється друга людина (незнайомець?).', en:'Alerts if a second person appears in the room (a stranger?).', de:'Warnt, wenn eine zweite Person im Raum erscheint (ein Fremder?).', fr:'Alerte si une deuxième personne apparaît dans la pièce (un inconnu ?).', es:'Avisa si aparece una segunda persona en la habitación (¿un desconocido?).', 'es-MX':'Avisa si aparece una segunda persona en la habitación (¿un desconocido?).', it:'Avvisa se appare una seconda persona nella stanza (uno sconosciuto?).', pt:'Alerta se uma segunda pessoa aparecer no quarto (um estranho?).', ar:'ينبّه إذا ظهر شخص ثانٍ في الغرفة (غريب؟).', hi:'अगर कमरे में दूसरा व्यक्ति दिखे तो सचेत करता है (अजनबी?)।', ja:'部屋に2人目が現れたら知らせます（見知らぬ人？）。', ky:'Бөлмөдө экинчи адам пайда болсо эскертет (бейтааныш?).', 'zh-Hant':'若房間出現第二人會提醒（陌生人？）。' },
  ob_li_left: { bg:'Подава сигнал, ако детето излезе от кадър.', ru:'Подаёт сигнал, если ребёнок выходит из кадра.', uk:'Подає сигнал, якщо дитина виходить з кадру.', en:'Alerts if the child leaves the frame.', de:'Warnt, wenn das Kind das Bild verlässt.', fr:'Alerte si l’enfant sort du cadre.', es:'Avisa si el niño sale del encuadre.', 'es-MX':'Avisa si el niño sale del encuadre.', it:'Avvisa se il bambino esce dall’inquadratura.', pt:'Alerta se a criança sair do quadro.', ar:'ينبّه إذا خرج الطفل من الإطار.', hi:'अगर बच्चा फ़्रेम से बाहर चला जाए तो सचेत करता है।', ja:'お子さまがフレームから出たら知らせます。', ky:'Бала кадрдан чыгып кетсе эскертет.', 'zh-Hant':'若孩子離開畫面會提醒。' },
  ob_li_notify: { bg:'Локално известие + звук + дневник със снимка на събитието.', ru:'Локальное уведомление + звук + журнал со снимком события.', uk:'Локальне сповіщення + звук + журнал зі знімком події.', en:'Local notification + sound + a log with a snapshot of the event.', de:'Lokale Benachrichtigung + Ton + Protokoll mit Schnappschuss des Ereignisses.', fr:'Notification locale + son + journal avec une photo de l’événement.', es:'Notificación local + sonido + registro con una captura del evento.', 'es-MX':'Notificación local + sonido + registro con una captura del evento.', it:'Notifica locale + suono + registro con un’istantanea dell’evento.', pt:'Notificação local + som + registro com uma captura do evento.', ar:'إشعار محلي + صوت + سجل مع لقطة للحدث.', hi:'स्थानीय सूचना + ध्वनि + घटना के स्नैपशॉट के साथ लॉग।', ja:'ローカル通知＋音＋イベントのスナップショット付きログ。', ky:'Жергиликтүү билдирүү + үн + окуянын сүрөтү менен журнал.', 'zh-Hant':'本地通知＋聲音＋附事件快照的記錄。' },
  ob_note: { bg:'Безплатно и on-device. Без акаунти, без контакти, без проследяване. Единствената мрежа е по избор (друга камера / relay) и безплатните тегла на модела.', ru:'Бесплатно и на устройстве. Без аккаунтов, без контактов, без слежки. Единственная сеть — по желанию (другая камера / relay) и бесплатные веса модели.', uk:'Безкоштовно й на пристрої. Без акаунтів, без контактів, без стеження. Єдина мережа — за бажанням (інша камера / relay) і безкоштовні ваги моделі.', en:'Free and on-device. No accounts, no contacts, no tracking. The only network is optional (another camera / relay) and the free model weights.', de:'Kostenlos und auf dem Gerät. Keine Konten, keine Kontakte, kein Tracking. Das einzige Netz ist optional (andere Kamera / Relay) und die kostenlosen Modellgewichte.', fr:'Gratuit et sur l’appareil. Sans comptes, sans contacts, sans suivi. Le seul réseau est optionnel (autre caméra / relais) et les poids gratuits du modèle.', es:'Gratis y en el dispositivo. Sin cuentas, sin contactos, sin rastreo. La única red es opcional (otra cámara / relay) y los pesos gratuitos del modelo.', 'es-MX':'Gratis y en el dispositivo. Sin cuentas, sin contactos, sin rastreo. La única red es opcional (otra cámara / relay) y los pesos gratuitos del modelo.', it:'Gratis e sul dispositivo. Nessun account, nessun contatto, nessun tracciamento. L’unica rete è opzionale (altra fotocamera / relay) e i pesi gratuiti del modello.', pt:'Grátis e no dispositivo. Sem contas, sem contatos, sem rastreamento. A única rede é opcional (outra câmera / relay) e os pesos gratuitos do modelo.', ar:'مجاني وعلى الجهاز. بلا حسابات، بلا جهات اتصال، بلا تتبّع. الشبكة الوحيدة اختيارية (كاميرا أخرى / relay) وأوزان النموذج المجانية.', hi:'मुफ़्त और डिवाइस पर। कोई खाता नहीं, कोई संपर्क नहीं, कोई ट्रैकिंग नहीं। एकमात्र नेटवर्क वैकल्पिक है (दूसरा कैमरा / relay) और मुफ़्त मॉडल वेट।', ja:'無料・端末内処理。アカウント・連絡先・追跡なし。唯一のネットワークは任意（別カメラ / relay）と無料のモデル重みのみ。', ky:'Акысыз жана түзмөктө. Аккаунтсуз, байланышсыз, көзөмөлсүз. Бирден-бир тармак — каалоо боюнча (башка камера / relay) жана модельдин акысыз салмактары.', 'zh-Hant':'免費且在裝置上執行。無帳戶、無聯絡人、無追蹤。唯一的網路為選用（另一相機 / relay）與免費的模型權重。' },
  ob_activate: { bg:'Активирай (безплатно)', ru:'Активировать (бесплатно)', uk:'Активувати (безкоштовно)', en:'Activate (free)', de:'Aktivieren (kostenlos)', fr:'Activer (gratuit)', es:'Activar (gratis)', 'es-MX':'Activar (gratis)', it:'Attiva (gratis)', pt:'Ativar (grátis)', ar:'تفعيل (مجانًا)', hi:'सक्रिय करें (मुफ़्त)', ja:'有効化（無料）', ky:'Активдештирүү (акысыз)', 'zh-Hant':'啟用（免費）' },

  // --- Настройки: Сдвояване ---
  pair_title: { bg:'🔗 Сдвояване (2 телефона)', ru:'🔗 Сопряжение (2 телефона)', uk:'🔗 Спарювання (2 телефони)', en:'🔗 Pairing (2 phones)', de:'🔗 Kopplung (2 Telefone)', fr:'🔗 Appairage (2 téléphones)', es:'🔗 Emparejamiento (2 teléfonos)', 'es-MX':'🔗 Emparejamiento (2 teléfonos)', it:'🔗 Abbinamento (2 telefoni)', pt:'🔗 Pareamento (2 telefones)', ar:'🔗 الاقتران (هاتفان)', hi:'🔗 पेयरिंग (2 फ़ोन)', ja:'🔗 ペア設定（2台）', ky:'🔗 Жупташтыруу (2 телефон)', 'zh-Hant':'🔗 配對（2 支手機）' },
  pair_desc: { bg:'Два телефона: единият до детето („Детегледачка" — гледа и праща), другият при теб („Наблюдаващ" — получава известията). Свържи ги с ЕДИН и същ ключ за двойката. „Сам" = един телефон (по подразбиране).', ru:'Два телефона: один у ребёнка («Няня» — смотрит и отправляет), другой у вас («Наблюдатель» — получает уведомления). Свяжите их ОДНИМ и тем же ключом пары. «Один» = один телефон (по умолчанию).', uk:'Два телефони: один біля дитини («Няня» — дивиться й надсилає), інший у вас («Спостерігач» — отримує сповіщення). З’єднайте їх ОДНИМ і тим самим ключем пари. «Один» = один телефон (за замовчуванням).', en:'Two phones: one by the child (“Monitor” — watches and sends), the other with you (“Watcher” — receives the alerts). Link them with the SAME pair key. “Solo” = one phone (default).', de:'Zwei Telefone: eines beim Kind („Monitor" — beobachtet und sendet), das andere bei dir („Beobachter" — empfängt die Warnungen). Verbinde sie mit DEMSELBEN Paarschlüssel. „Solo" = ein Telefon (Standard).', fr:'Deux téléphones : un près de l’enfant (« Moniteur » — surveille et envoie), l’autre avec vous (« Observateur » — reçoit les alertes). Reliez-les avec la MÊME clé de paire. « Solo » = un téléphone (par défaut).', es:'Dos teléfonos: uno junto al niño («Monitor» — vigila y envía), el otro contigo («Observador» — recibe las alertas). Enlázalos con la MISMA clave de pareja. «Solo» = un teléfono (predeterminado).', 'es-MX':'Dos teléfonos: uno junto al niño («Monitor» — vigila y envía), el otro contigo («Observador» — recibe las alertas). Enlázalos con la MISMA clave de pareja. «Solo» = un teléfono (predeterminado).', it:'Due telefoni: uno vicino al bambino («Monitor» — guarda e invia), l’altro con te («Osservatore» — riceve gli avvisi). Collegali con la STESSA chiave di coppia. «Solo» = un telefono (predefinito).', pt:'Dois telefones: um perto da criança (“Monitor” — observa e envia), o outro com você (“Observador” — recebe os alertas). Ligue-os com a MESMA chave de par. “Solo” = um telefone (padrão).', ar:'هاتفان: واحد قرب الطفل («المراقِب» — يشاهد ويرسل)، والآخر معك («المستقبِل» — يستقبل التنبيهات). اربطهما بنفس مفتاح الاقتران. «منفرد» = هاتف واحد (افتراضي).', hi:'दो फ़ोन: एक बच्चे के पास (“मॉनिटर” — देखता और भेजता है), दूसरा आपके पास (“वॉचर” — अलर्ट प्राप्त करता है)। उन्हें एक ही पेयर कुंजी से जोड़ें। “सोलो” = एक फ़ोन (डिफ़ॉल्ट)।', ja:'2台: 1台は子どものそば（「モニター」— 見て送信）、もう1台はあなた（「ウォッチャー」— 通知を受信）。同じペアキーで連携してください。「単独」=1台（既定）。', ky:'Эки телефон: бири баланын жанында («Кароол» — карайт жана жөнөтөт), экинчиси сизде («Байкоочу» — эскертүүлөрдү алат). Аларды БИРдей жуп ачкычы менен туташтырыңыз. «Жалгыз» = бир телефон (демейки).', 'zh-Hant':'兩支手機：一支在孩子旁（「監看端」— 觀看並傳送），另一支在您身邊（「接收端」— 收到提醒）。用相同的配對金鑰連結。「單機」=一支手機（預設）。' },
  pair_role: { bg:'Режим / роля', ru:'Режим / роль', uk:'Режим / роль', en:'Mode / role', de:'Modus / Rolle', fr:'Mode / rôle', es:'Modo / rol', 'es-MX':'Modo / rol', it:'Modalità / ruolo', pt:'Modo / função', ar:'الوضع / الدور', hi:'मोड / भूमिका', ja:'モード / 役割', ky:'Режим / роль', 'zh-Hant':'模式 / 角色' },
  role_solo: { bg:'Сам (един телефон)', ru:'Один (один телефон)', uk:'Один (один телефон)', en:'Solo (one phone)', de:'Solo (ein Telefon)', fr:'Solo (un téléphone)', es:'Solo (un teléfono)', 'es-MX':'Solo (un teléfono)', it:'Solo (un telefono)', pt:'Solo (um telefone)', ar:'منفرد (هاتف واحد)', hi:'सोलो (एक फ़ोन)', ja:'単独（1台）', ky:'Жалгыз (бир телефон)', 'zh-Hant':'單機（一支手機）' },
  role_monitor: { bg:'Детегледачка (до детето — праща)', ru:'Няня (у ребёнка — отправляет)', uk:'Няня (біля дитини — надсилає)', en:'Monitor (by the child — sends)', de:'Monitor (beim Kind — sendet)', fr:'Moniteur (près de l’enfant — envoie)', es:'Monitor (junto al niño — envía)', 'es-MX':'Monitor (junto al niño — envía)', it:'Monitor (vicino al bambino — invia)', pt:'Monitor (perto da criança — envia)', ar:'المراقِب (قرب الطفل — يرسل)', hi:'मॉनिटर (बच्चे के पास — भेजता है)', ja:'モニター（子どものそば — 送信）', ky:'Кароол (баланын жанында — жөнөтөт)', 'zh-Hant':'監看端（在孩子旁 — 傳送）' },
  role_watcher: { bg:'Наблюдаващ / Майка Тереза (получава)', ru:'Наблюдатель / Мать Тереза (получает)', uk:'Спостерігач / Мати Тереза (отримує)', en:'Watcher / Mother Teresa (receives)', de:'Beobachter / Mutter Teresa (empfängt)', fr:'Observateur / Mère Teresa (reçoit)', es:'Observador / Madre Teresa (recibe)', 'es-MX':'Observador / Madre Teresa (recibe)', it:'Osservatore / Madre Teresa (riceve)', pt:'Observador / Madre Teresa (recebe)', ar:'المستقبِل / الأم تيريزا (يستقبل)', hi:'वॉचर / मदर टेरेसा (प्राप्त करता है)', ja:'ウォッチャー / マザー・テレサ（受信）', ky:'Байкоочу / Эне Тереза (алат)', 'zh-Hant':'接收端 / 德蕾莎修女（接收）' },
  pair_key_label: { bg:'Ключ за двойката (еднакъв на двата телефона)', ru:'Ключ пары (одинаковый на обоих телефонах)', uk:'Ключ пари (однаковий на обох телефонах)', en:'Pair key (same on both phones)', de:'Paarschlüssel (gleich auf beiden Telefonen)', fr:'Clé de paire (identique sur les deux téléphones)', es:'Clave de pareja (igual en ambos teléfonos)', 'es-MX':'Clave de pareja (igual en ambos teléfonos)', it:'Chiave di coppia (uguale su entrambi i telefoni)', pt:'Chave de par (igual nos dois telefones)', ar:'مفتاح الاقتران (نفسه على الهاتفين)', hi:'पेयर कुंजी (दोनों फ़ोन पर समान)', ja:'ペアキー（両方の端末で同じ）', ky:'Жуп ачкычы (эки телефондо бирдей)', 'zh-Hant':'配對金鑰（兩支手機相同）' },
  pair_key_ph: { bg:'ключ за двойката', ru:'ключ пары', uk:'ключ пари', en:'pair key', de:'Paarschlüssel', fr:'clé de paire', es:'clave de pareja', 'es-MX':'clave de pareja', it:'chiave di coppia', pt:'chave de par', ar:'مفتاح الاقتران', hi:'पेयर कुंजी', ja:'ペアキー', ky:'жуп ачкычы', 'zh-Hant':'配對金鑰' },
  pair_gen_key: { bg:'Генерирай ключ', ru:'Сгенерировать ключ', uk:'Згенерувати ключ', en:'Generate key', de:'Schlüssel erzeugen', fr:'Générer une clé', es:'Generar clave', 'es-MX':'Generar clave', it:'Genera chiave', pt:'Gerar chave', ar:'توليد مفتاح', hi:'कुंजी बनाएं', ja:'キーを生成', ky:'Ачкыч түзүү', 'zh-Hant':'產生金鑰' },
  pair_relay_label: { bg:'Сървър (релей)', ru:'Сервер (релей)', uk:'Сервер (релей)', en:'Server (relay)', de:'Server (Relay)', fr:'Serveur (relais)', es:'Servidor (relay)', 'es-MX':'Servidor (relay)', it:'Server (relay)', pt:'Servidor (relay)', ar:'الخادم (relay)', hi:'सर्वर (relay)', ja:'サーバー（relay）', ky:'Сервер (релей)', 'zh-Hant':'伺服器（relay）' },
  pair_poll_label: { bg:'Проверка на всеки (сек) — за наблюдаващия', ru:'Проверять каждые (сек) — для наблюдателя', uk:'Перевіряти кожні (сек) — для спостерігача', en:'Check every (sec) — for the watcher', de:'Prüfen alle (Sek.) — für den Beobachter', fr:'Vérifier toutes les (sec) — pour l’observateur', es:'Comprobar cada (seg) — para el observador', 'es-MX':'Comprobar cada (seg) — para el observador', it:'Controlla ogni (sec) — per l’osservatore', pt:'Verificar a cada (seg) — para o observador', ar:'التحقق كل (ث) — للمستقبِل', hi:'हर (सेकंड) जाँचें — वॉचर के लिए', ja:'確認間隔（秒）— ウォッチャー用', ky:'Ар бир (сек) текшерүү — байкоочу үчүн', 'zh-Hant':'每隔（秒）檢查 — 供接收端' },
  pair_check: { bg:'Провери', ru:'Проверить', uk:'Перевірити', en:'Check', de:'Prüfen', fr:'Vérifier', es:'Comprobar', 'es-MX':'Comprobar', it:'Controlla', pt:'Verificar', ar:'تحقّق', hi:'जाँचें', ja:'確認', ky:'Текшерүү', 'zh-Hant':'檢查' },
  pair_saved: { bg:'Сдвояването е запазено.', ru:'Сопряжение сохранено.', uk:'Спарювання збережено.', en:'Pairing saved.', de:'Kopplung gespeichert.', fr:'Appairage enregistré.', es:'Emparejamiento guardado.', 'es-MX':'Emparejamiento guardado.', it:'Abbinamento salvato.', pt:'Pareamento salvo.', ar:'تم حفظ الاقتران.', hi:'पेयरिंग सहेजी गई।', ja:'ペア設定を保存しました。', ky:'Жупташтыруу сакталды.', 'zh-Hant':'已儲存配對。' },
  pair_checking: { bg:'проверявам…', ru:'проверяю…', uk:'перевіряю…', en:'checking…', de:'prüfe…', fr:'vérification…', es:'comprobando…', 'es-MX':'comprobando…', it:'controllo…', pt:'verificando…', ar:'جارٍ التحقق…', hi:'जाँच रहे…', ja:'確認中…', ky:'текшерүүдө…', 'zh-Hant':'檢查中…' },
  pair_ok: { bg:'връзката работи ✓', ru:'связь работает ✓', uk:'зв’язок працює ✓', en:'connection works ✓', de:'Verbindung funktioniert ✓', fr:'connexion établie ✓', es:'la conexión funciona ✓', 'es-MX':'la conexión funciona ✓', it:'connessione attiva ✓', pt:'conexão funciona ✓', ar:'الاتصال يعمل ✓', hi:'कनेक्शन काम कर रहा ✓', ja:'接続OK ✓', ky:'байланыш иштейт ✓', 'zh-Hant':'連線正常 ✓' },
  pair_none: { bg:'няма връзка', ru:'нет связи', uk:'немає зв’язку', en:'no connection', de:'keine Verbindung', fr:'pas de connexion', es:'sin conexión', 'es-MX':'sin conexión', it:'nessuna connessione', pt:'sem conexão', ar:'لا اتصال', hi:'कोई कनेक्शन नहीं', ja:'接続なし', ky:'байланыш жок', 'zh-Hant':'無連線' },
  pair_test_msg: { bg:'Тест от детегледачката', ru:'Тест от няни', uk:'Тест від няні', en:'Test from the monitor', de:'Test vom Monitor', fr:'Test du moniteur', es:'Prueba desde el monitor', 'es-MX':'Prueba desde el monitor', it:'Test dal monitor', pt:'Teste do monitor', ar:'اختبار من المراقِب', hi:'मॉनिटर से परीक्षण', ja:'モニターからのテスト', ky:'Каролдон сыноо', 'zh-Hant':'來自監看端的測試' },

  // --- Настройки: Камера ---
  camera_title: { bg:'Камера', ru:'Камера', uk:'Камера', en:'Camera', de:'Kamera', fr:'Caméra', es:'Cámara', 'es-MX':'Cámara', it:'Fotocamera', pt:'Câmera', ar:'الكاميرا', hi:'कैमरा', ja:'カメラ', ky:'Камера', 'zh-Hant':'相機' },
  camera_source: { bg:'Източник', ru:'Источник', uk:'Джерело', en:'Source', de:'Quelle', fr:'Source', es:'Fuente', 'es-MX':'Fuente', it:'Sorgente', pt:'Fonte', ar:'المصدر', hi:'स्रोत', ja:'ソース', ky:'Булак', 'zh-Hant':'來源' },
  cam_front: { bg:'Предна камера', ru:'Фронтальная камера', uk:'Фронтальна камера', en:'Front camera', de:'Frontkamera', fr:'Caméra avant', es:'Cámara frontal', 'es-MX':'Cámara frontal', it:'Fotocamera frontale', pt:'Câmera frontal', ar:'الكاميرا الأمامية', hi:'फ़्रंट कैमरा', ja:'フロントカメラ', ky:'Алдыңкы камера', 'zh-Hant':'前置相機' },
  cam_back: { bg:'Задна камера', ru:'Задняя камера', uk:'Задня камера', en:'Back camera', de:'Rückkamera', fr:'Caméra arrière', es:'Cámara trasera', 'es-MX':'Cámara trasera', it:'Fotocamera posteriore', pt:'Câmera traseira', ar:'الكاميرا الخلفية', hi:'बैक कैमरा', ja:'背面カメラ', ky:'Арткы камера', 'zh-Hant':'後置相機' },
  cam_other: { bg:'Друга камера (URL)', ru:'Другая камера (URL)', uk:'Інша камера (URL)', en:'Other camera (URL)', de:'Andere Kamera (URL)', fr:'Autre caméra (URL)', es:'Otra cámara (URL)', 'es-MX':'Otra cámara (URL)', it:'Altra fotocamera (URL)', pt:'Outra câmera (URL)', ar:'كاميرا أخرى (URL)', hi:'अन्य कैमरा (URL)', ja:'別のカメラ（URL）', ky:'Башка камера (URL)', 'zh-Hant':'其他相機（URL）' },
  cam_url_label: { bg:'URL на друга камера (по избор)', ru:'URL другой камеры (по желанию)', uk:'URL іншої камери (за бажанням)', en:'Other camera URL (optional)', de:'URL der anderen Kamera (optional)', fr:'URL de l’autre caméra (optionnel)', es:'URL de otra cámara (opcional)', 'es-MX':'URL de otra cámara (opcional)', it:'URL altra fotocamera (opzionale)', pt:'URL de outra câmera (opcional)', ar:'رابط الكاميرا الأخرى (اختياري)', hi:'अन्य कैमरा URL (वैकल्पिक)', ja:'別カメラのURL（任意）', ky:'Башка камеранын URL (каалоо боюнча)', 'zh-Hant':'其他相機 URL（選用）' },
  cam_url_ph: { bg:'https://… (HLS/MJPEG/.mp4, с CORS)', ru:'https://… (HLS/MJPEG/.mp4, с CORS)', uk:'https://… (HLS/MJPEG/.mp4, з CORS)', en:'https://… (HLS/MJPEG/.mp4, with CORS)', de:'https://… (HLS/MJPEG/.mp4, mit CORS)', fr:'https://… (HLS/MJPEG/.mp4, avec CORS)', es:'https://… (HLS/MJPEG/.mp4, con CORS)', 'es-MX':'https://… (HLS/MJPEG/.mp4, con CORS)', it:'https://… (HLS/MJPEG/.mp4, con CORS)', pt:'https://… (HLS/MJPEG/.mp4, com CORS)', ar:'‎https://… (HLS/MJPEG/.mp4، مع CORS)', hi:'https://… (HLS/MJPEG/.mp4, CORS के साथ)', ja:'https://…（HLS/MJPEG/.mp4、CORS対応）', ky:'https://… (HLS/MJPEG/.mp4, CORS менен)', 'zh-Hant':'https://…（HLS/MJPEG/.mp4，需 CORS）' },
  cam_honest: { bg:'Честно: браузърът свири само browser-playable потоци (HLS/MJPEG/.mp4) и чете пиксели само ако сървърът връща CORS. RTSP (повечето IP камери) изисква gateway/транскодиране.', ru:'Честно: браузер воспроизводит только browser-playable потоки (HLS/MJPEG/.mp4) и читает пиксели только если сервер отдаёт CORS. RTSP (большинство IP-камер) требует gateway/транскодирования.', uk:'Чесно: браузер відтворює лише browser-playable потоки (HLS/MJPEG/.mp4) і читає пікселі лише якщо сервер віддає CORS. RTSP (більшість IP-камер) потребує gateway/транскодування.', en:'Honest: the browser only plays browser-playable streams (HLS/MJPEG/.mp4) and reads pixels only if the server returns CORS. RTSP (most IP cameras) needs a gateway/transcoding.', de:'Ehrlich: Der Browser spielt nur browser-fähige Streams (HLS/MJPEG/.mp4) ab und liest Pixel nur, wenn der Server CORS liefert. RTSP (die meisten IP-Kameras) braucht ein Gateway/Transcoding.', fr:'Honnêtement : le navigateur ne lit que des flux compatibles (HLS/MJPEG/.mp4) et ne lit les pixels que si le serveur renvoie CORS. Le RTSP (la plupart des caméras IP) nécessite une passerelle/transcodage.', es:'Con franqueza: el navegador solo reproduce flujos compatibles (HLS/MJPEG/.mp4) y lee píxeles solo si el servidor devuelve CORS. RTSP (la mayoría de cámaras IP) requiere gateway/transcodificación.', 'es-MX':'Con franqueza: el navegador solo reproduce flujos compatibles (HLS/MJPEG/.mp4) y lee píxeles solo si el servidor devuelve CORS. RTSP (la mayoría de cámaras IP) requiere gateway/transcodificación.', it:'Onestamente: il browser riproduce solo stream compatibili (HLS/MJPEG/.mp4) e legge i pixel solo se il server restituisce CORS. RTSP (la maggior parte delle telecamere IP) richiede gateway/transcodifica.', pt:'Honestamente: o navegador só reproduz fluxos compatíveis (HLS/MJPEG/.mp4) e lê pixels apenas se o servidor retornar CORS. RTSP (maioria das câmeras IP) exige gateway/transcodificação.', ar:'بصراحة: المتصفّح يشغّل فقط البثوث المدعومة (HLS/MJPEG/.mp4) ويقرأ البكسلات فقط إذا أعاد الخادم CORS. RTSP (معظم كاميرات IP) يتطلّب gateway/تحويل ترميز.', hi:'ईमानदारी से: ब्राउज़र केवल browser-playable स्ट्रीम (HLS/MJPEG/.mp4) चलाता है और पिक्सेल तभी पढ़ता है जब सर्वर CORS लौटाए। RTSP (अधिकांश IP कैमरे) के लिए gateway/ट्रांसकोडिंग चाहिए।', ja:'正直に: ブラウザは再生可能なストリーム（HLS/MJPEG/.mp4）のみ再生し、サーバーがCORSを返す場合のみピクセルを読み取ります。RTSP（多くのIPカメラ）にはゲートウェイ/トランスコードが必要です。', ky:'Чынын айтсак: браузер браузерде ойнотула турган агымдарды гана (HLS/MJPEG/.mp4) ойнотот жана сервер CORS кайтарса гана пикселдерди окуйт. RTSP (көпчүлүк IP камералар) gateway/транскоддоону талап кылат.', 'zh-Hant':'坦白說：瀏覽器只能播放可播放的串流（HLS/MJPEG/.mp4），且僅在伺服器回傳 CORS 時讀取像素。RTSP（多數 IP 攝影機）需要閘道/轉碼。' },

  // --- Настройки: Движение ---
  motion_title: { bg:'Движение', ru:'Движение', uk:'Рух', en:'Motion', de:'Bewegung', fr:'Mouvement', es:'Movimiento', 'es-MX':'Movimiento', it:'Movimento', pt:'Movimento', ar:'الحركة', hi:'गति', ja:'動き', ky:'Кыймыл', 'zh-Hant':'動作' },
  sensitivity: { bg:'Чувствителност', ru:'Чувствительность', uk:'Чутливість', en:'Sensitivity', de:'Empfindlichkeit', fr:'Sensibilité', es:'Sensibilidad', 'es-MX':'Sensibilidad', it:'Sensibilità', pt:'Sensibilidade', ar:'الحساسية', hi:'संवेदनशीलता', ja:'感度', ky:'Сезгичтик', 'zh-Hant':'靈敏度' },
  calm_after: { bg:'Спокойствие → „спи" след', ru:'Спокойствие → «спит» через', uk:'Спокій → «спить» через', en:'Calm → “sleeping” after', de:'Ruhe → „schläft" nach', fr:'Calme → « endormi » après', es:'Calma → «durmiendo» tras', 'es-MX':'Calma → «durmiendo» tras', it:'Calma → «dorme» dopo', pt:'Calma → “dormindo” após', ar:'هدوء → «نائم» بعد', hi:'शांति → “सो रहा” के बाद', ja:'静か → 「就寝」まで', ky:'Тынчтык → «уктап жатат» кийин', 'zh-Hant':'平靜 → 「安睡」於' },
  seconds_short: { bg:'сек', ru:'сек', uk:'сек', en:'sec', de:'Sek.', fr:'sec', es:'seg', 'es-MX':'seg', it:'sec', pt:'seg', ar:'ث', hi:'सेकंड', ja:'秒', ky:'сек', 'zh-Hant':'秒' },

  // --- Настройки: Сигнали ---
  alerts_title: { bg:'Сигнали', ru:'Сигналы', uk:'Сигнали', en:'Alerts', de:'Warnungen', fr:'Alertes', es:'Alertas', 'es-MX':'Alertas', it:'Avvisi', pt:'Alertas', ar:'التنبيهات', hi:'अलर्ट', ja:'アラート', ky:'Сигналдар', 'zh-Hant':'警報' },
  alert_wake: { bg:'„Събуди се"', ru:'«Проснулся»', uk:'«Прокинувся»', en:'“Woke up”', de:'„Aufgewacht"', fr:'« Réveillé »', es:'«Despertó»', 'es-MX':'«Despertó»', it:'«Sveglio»', pt:'“Acordou”', ar:'«استيقظ»', hi:'“जाग गया”', ja:'「起きた」', ky:'«Ойгонду»', 'zh-Hant':'「醒了」' },
  alert_stranger: { bg:'„Непознат в стаята" (втори човек)', ru:'«Незнакомец в комнате» (второй человек)', uk:'«Незнайомець у кімнаті» (друга людина)', en:'“Stranger in the room” (second person)', de:'„Fremder im Raum" (zweite Person)', fr:'« Inconnu dans la pièce » (deuxième personne)', es:'«Desconocido en la habitación» (segunda persona)', 'es-MX':'«Desconocido en la habitación» (segunda persona)', it:'«Sconosciuto nella stanza» (seconda persona)', pt:'“Estranho no quarto” (segunda pessoa)', ar:'«غريب في الغرفة» (شخص ثانٍ)', hi:'“कमरे में अजनबी” (दूसरा व्यक्ति)', ja:'「部屋に見知らぬ人」（2人目）', ky:'«Бөлмөдө бейтааныш» (экинчи адам)', 'zh-Hant':'「房間有陌生人」（第二人）' },
  alert_stranger_hint: { bg:'Само „появи се втори човек" — НЕ е разпознаване на лице или анти-отвличане.', ru:'Только «появился второй человек» — НЕ распознавание лица и не защита от похищения.', uk:'Лише «з’явилася друга людина» — НЕ розпізнавання обличчя й не захист від викрадення.', en:'Only “a second person appeared” — NOT face recognition or anti-abduction.', de:'Nur „eine zweite Person erschien" — KEINE Gesichtserkennung oder Entführungsschutz.', fr:'Seulement « une deuxième personne est apparue » — PAS de reconnaissance faciale ni d’anti-enlèvement.', es:'Solo «apareció una segunda persona» — NO es reconocimiento facial ni anti-secuestro.', 'es-MX':'Solo «apareció una segunda persona» — NO es reconocimiento facial ni anti-secuestro.', it:'Solo «è apparsa una seconda persona» — NON è riconoscimento facciale né anti-rapimento.', pt:'Apenas “apareceu uma segunda pessoa” — NÃO é reconhecimento facial nem antissequestro.', ar:'فقط «ظهر شخص ثانٍ» — ليس تعرّفًا على الوجه ولا مكافحة اختطاف.', hi:'केवल “दूसरा व्यक्ति दिखा” — चेहरा पहचान या अपहरण-रोधी नहीं।', ja:'「2人目が現れた」だけ — 顔認識や誘拐防止ではありません。', ky:'Болгону «экинчи адам пайда болду» — жүздү таануу же уурдоого каршы ЭМЕС.', 'zh-Hant':'僅「出現第二人」— 並非臉部辨識或防綁架。' },
  alert_left: { bg:'„Детето излезе от кадър"', ru:'«Ребёнок вышел из кадра»', uk:'«Дитина вийшла з кадру»', en:'“Child left the frame”', de:'„Kind hat das Bild verlassen"', fr:'« L’enfant a quitté le cadre »', es:'«El niño salió del encuadre»', 'es-MX':'«El niño salió del encuadre»', it:'«Il bambino è uscito dall’inquadratura»', pt:'“A criança saiu do quadro”', ar:'«خرج الطفل من الإطار»', hi:'“बच्चा फ़्रेम से बाहर गया”', ja:'「子どもがフレームから出た」', ky:'«Бала кадрдан чыкты»', 'zh-Hant':'「孩子離開畫面」' },
  alert_fire: { bg:'„Възможен пожар" (груба евристика)', ru:'«Возможен пожар» (грубая эвристика)', uk:'«Можлива пожежа» (груба евристика)', en:'“Possible fire” (rough heuristic)', de:'„Möglicher Brand" (grobe Heuristik)', fr:'« Incendie possible » (heuristique grossière)', es:'«Posible incendio» (heurística aproximada)', 'es-MX':'«Posible incendio» (heurística aproximada)', it:'«Possibile incendio» (euristica grossolana)', pt:'“Possível incêndio” (heurística grosseira)', ar:'«حريق محتمل» (تقدير تقريبي)', hi:'“संभावित आग” (मोटा अनुमान)', ja:'「火災の可能性」（粗い推定）', ky:'«Мүмкүн өрт» (одоно эвристика)', 'zh-Hant':'「可能起火」（粗略判斷）' },
  alert_fire_hint: { bg:'ГРУБА евристика по яркост/трептене — НЕ заменя датчик за дим! Изключено по подразбиране.', ru:'ГРУБАЯ эвристика по яркости/мерцанию — НЕ заменяет датчик дыма! Выключено по умолчанию.', uk:'ГРУБА евристика за яскравістю/мерехтінням — НЕ замінює датчик диму! Вимкнено за замовчуванням.', en:'A ROUGH brightness/flicker heuristic — does NOT replace a smoke detector! Off by default.', de:'Eine GROBE Helligkeits-/Flacker-Heuristik — ersetzt KEINEN Rauchmelder! Standardmäßig aus.', fr:'Heuristique GROSSIÈRE de luminosité/scintillement — ne remplace PAS un détecteur de fumée ! Désactivé par défaut.', es:'Heurística APROXIMADA de brillo/parpadeo — ¡NO sustituye un detector de humo! Desactivado por defecto.', 'es-MX':'Heurística APROXIMADA de brillo/parpadeo — ¡NO sustituye un detector de humo! Desactivado por defecto.', it:'Euristica GROSSOLANA di luminosità/sfarfallio — NON sostituisce un rilevatore di fumo! Disattivato di default.', pt:'Heurística GROSSEIRA de brilho/cintilação — NÃO substitui um detector de fumaça! Desativado por padrão.', ar:'تقدير تقريبي للسطوع/الوميض — لا يحلّ محلّ كاشف الدخان! معطّل افتراضيًا.', hi:'चमक/टिमटिमाहट का मोटा अनुमान — धुआँ सेंसर की जगह नहीं लेता! डिफ़ॉल्ट रूप से बंद।', ja:'明るさ/ちらつきの粗い推定 — 煙感知器の代わりにはなりません！既定でオフ。', ky:'Жарыктык/жымыңдоо боюнча ОДОНО эвристика — түтүн датчигин алмаштырбайт! Демейде өчүк.', 'zh-Hant':'亮度/閃爍的粗略判斷 — 不能取代煙霧偵測器！預設關閉。' },

  // --- Настройки: Известия ---
  notify_title: { bg:'Известия', ru:'Уведомления', uk:'Сповіщення', en:'Notifications', de:'Benachrichtigungen', fr:'Notifications', es:'Notificaciones', 'es-MX':'Notificaciones', it:'Notifiche', pt:'Notificações', ar:'الإشعارات', hi:'सूचनाएँ', ja:'通知', ky:'Билдирүүлөр', 'zh-Hant':'通知' },
  sound: { bg:'Звук', ru:'Звук', uk:'Звук', en:'Sound', de:'Ton', fr:'Son', es:'Sonido', 'es-MX':'Sonido', it:'Suono', pt:'Som', ar:'الصوت', hi:'ध्वनि', ja:'音', ky:'Үн', 'zh-Hant':'聲音' },
  vibrate: { bg:'Вибрация', ru:'Вибрация', uk:'Вібрація', en:'Vibration', de:'Vibration', fr:'Vibration', es:'Vibración', 'es-MX':'Vibración', it:'Vibrazione', pt:'Vibração', ar:'الاهتزاز', hi:'कंपन', ja:'振動', ky:'Дирилдөө', 'zh-Hant':'震動' },
  relay_label: { bg:'Relay URL към друг телефон (по избор)', ru:'Relay URL на другой телефон (по желанию)', uk:'Relay URL на інший телефон (за бажанням)', en:'Relay URL to another phone (optional)', de:'Relay-URL zu einem anderen Telefon (optional)', fr:'URL de relais vers un autre téléphone (optionnel)', es:'URL de relay a otro teléfono (opcional)', 'es-MX':'URL de relay a otro teléfono (opcional)', it:'URL relay verso un altro telefono (opzionale)', pt:'URL de relay para outro telefone (opcional)', ar:'رابط relay إلى هاتف آخر (اختياري)', hi:'दूसरे फ़ोन के लिए Relay URL (वैकल्पिक)', ja:'別端末への Relay URL（任意）', ky:'Башка телефонго Relay URL (каалоо боюнча)', 'zh-Hant':'發送至另一支手機的 Relay URL（選用）' },
  relay_honest: { bg:'Честно: известие към ДРУГ телефон не може само on-device — нужен е твой relay/сървър (push). Без зададен URL не се изпраща нищо навън.', ru:'Честно: уведомление на ДРУГОЙ телефон невозможно только на устройстве — нужен ваш relay/сервер (push). Без указанного URL ничего наружу не отправляется.', uk:'Чесно: сповіщення на ІНШИЙ телефон неможливе лише на пристрої — потрібен ваш relay/сервер (push). Без вказаного URL нічого назовні не надсилається.', en:'Honest: a notification to ANOTHER phone cannot be on-device only — you need your own relay/server (push). Without a URL nothing is sent out.', de:'Ehrlich: Eine Benachrichtigung an ein ANDERES Telefon geht nicht nur auf dem Gerät — du brauchst deinen eigenen Relay/Server (Push). Ohne URL wird nichts nach außen gesendet.', fr:'Honnêtement : une notification vers un AUTRE téléphone ne peut pas être uniquement sur l’appareil — il faut votre propre relais/serveur (push). Sans URL, rien n’est envoyé.', es:'Con franqueza: una notificación a OTRO teléfono no puede ser solo en el dispositivo — necesitas tu propio relay/servidor (push). Sin una URL no se envía nada.', 'es-MX':'Con franqueza: una notificación a OTRO teléfono no puede ser solo en el dispositivo — necesitas tu propio relay/servidor (push). Sin una URL no se envía nada.', it:'Onestamente: una notifica a un ALTRO telefono non può essere solo sul dispositivo — serve un tuo relay/server (push). Senza URL non viene inviato nulla.', pt:'Honestamente: uma notificação para OUTRO telefone não pode ser só no dispositivo — você precisa do seu próprio relay/servidor (push). Sem URL nada é enviado.', ar:'بصراحة: لا يمكن إرسال إشعار إلى هاتف آخر على الجهاز فقط — تحتاج relay/خادمك الخاص (push). بدون رابط لا يُرسَل شيء.', hi:'ईमानदारी से: दूसरे फ़ोन को सूचना केवल डिवाइस पर संभव नहीं — आपको अपना relay/सर्वर (push) चाहिए। URL के बिना कुछ भी बाहर नहीं भेजा जाता।', ja:'正直に: 別の端末への通知は端末内だけでは不可能 — 自分の relay/サーバー（push）が必要です。URLがなければ外部へは何も送信されません。', ky:'Чынын айтсак: БАШКА телефонго билдирүү түзмөктө гана мүмкүн эмес — өзүңүздүн relay/серверыңыз (push) керек. URL жок болсо тышка эч нерсе жөнөтүлбөйт.', 'zh-Hant':'坦白說：發送通知到另一支手機無法僅靠裝置本身 — 需要你自己的 relay/伺服器（push）。未設定 URL 則不會對外傳送任何內容。' },
  to_permissions: { bg:'Напред към разрешения', ru:'Далее к разрешениям', uk:'Далі до дозволів', en:'Next: permissions', de:'Weiter zu Berechtigungen', fr:'Suivant : autorisations', es:'Siguiente: permisos', 'es-MX':'Siguiente: permisos', it:'Avanti: autorizzazioni', pt:'Avançar para permissões', ar:'التالي: الأذونات', hi:'आगे: अनुमतियाँ', ja:'次へ：権限', ky:'Уруксаттарга өтүү', 'zh-Hant':'下一步：權限' },

  // --- Разрешения ---
  perms_title: { bg:'Разрешения', ru:'Разрешения', uk:'Дозволи', en:'Permissions', de:'Berechtigungen', fr:'Autorisations', es:'Permisos', 'es-MX':'Permisos', it:'Autorizzazioni', pt:'Permissões', ar:'الأذونات', hi:'अनुमतियाँ', ja:'権限', ky:'Уруксаттар', 'zh-Hant':'權限' },
  perms_intro: { bg:'Нужни са само две неща. Не искаме контакти, местоположение или нещо за проследяване.', ru:'Нужны всего две вещи. Мы не запрашиваем контакты, местоположение или что-либо для слежки.', uk:'Потрібні лише дві речі. Ми не запитуємо контакти, місцезнаходження чи щось для стеження.', en:'Only two things are needed. We do not ask for contacts, location, or anything for tracking.', de:'Nur zwei Dinge sind nötig. Wir fragen nicht nach Kontakten, Standort oder etwas zum Tracking.', fr:'Seules deux choses sont nécessaires. Nous ne demandons pas de contacts, de localisation ni rien pour le suivi.', es:'Solo se necesitan dos cosas. No pedimos contactos, ubicación ni nada para rastreo.', 'es-MX':'Solo se necesitan dos cosas. No pedimos contactos, ubicación ni nada para rastreo.', it:'Servono solo due cose. Non chiediamo contatti, posizione o nulla per il tracciamento.', pt:'Apenas duas coisas são necessárias. Não pedimos contatos, localização ou nada para rastreamento.', ar:'يلزم شيئان فقط. لا نطلب جهات الاتصال أو الموقع أو أي شيء للتتبّع.', hi:'केवल दो चीज़ें चाहिए। हम संपर्क, स्थान या ट्रैकिंग के लिए कुछ नहीं माँगते।', ja:'必要なのは2つだけ。連絡先・位置情報・追跡用の権限は求めません。', ky:'Бар болгону эки нерсе керек. Биз байланыштарды, жайгашууну же көзөмөл үчүн эч нерсе сурабайбыз.', 'zh-Hant':'只需兩項。我們不索取聯絡人、位置或任何追蹤用途。' },
  perm_camera_title: { bg:'📷 Камера', ru:'📷 Камера', uk:'📷 Камера', en:'📷 Camera', de:'📷 Kamera', fr:'📷 Caméra', es:'📷 Cámara', 'es-MX':'📷 Cámara', it:'📷 Fotocamera', pt:'📷 Câmera', ar:'📷 الكاميرا', hi:'📷 कैमरा', ja:'📷 カメラ', ky:'📷 Камера', 'zh-Hant':'📷 相機' },
  perm_camera_desc: { bg:'За да гледа детето на живо. Видеото не напуска устройството.', ru:'Чтобы наблюдать за ребёнком вживую. Видео не покидает устройство.', uk:'Щоб спостерігати за дитиною наживо. Відео не залишає пристрій.', en:'To watch the child live. The video never leaves the device.', de:'Um das Kind live zu sehen. Das Video verlässt das Gerät nie.', fr:'Pour surveiller l’enfant en direct. La vidéo ne quitte jamais l’appareil.', es:'Para ver al niño en vivo. El video nunca sale del dispositivo.', 'es-MX':'Para ver al niño en vivo. El video nunca sale del dispositivo.', it:'Per vedere il bambino in diretta. Il video non lascia mai il dispositivo.', pt:'Para ver a criança ao vivo. O vídeo nunca sai do dispositivo.', ar:'لمشاهدة الطفل مباشرة. لا يغادر الفيديو الجهاز.', hi:'बच्चे को लाइव देखने के लिए। वीडियो डिवाइस से बाहर नहीं जाता।', ja:'お子さまをライブで見るため。映像は端末外に出ません。', ky:'Баланы түз көрүү үчүн. Видео түзмөктөн чыкпайт.', 'zh-Hant':'用於即時看顧孩子。影像絕不離開裝置。' },
  perm_camera_btn: { bg:'Разреши камера', ru:'Разрешить камеру', uk:'Дозволити камеру', en:'Allow camera', de:'Kamera erlauben', fr:'Autoriser la caméra', es:'Permitir cámara', 'es-MX':'Permitir cámara', it:'Consenti fotocamera', pt:'Permitir câmera', ar:'السماح بالكاميرا', hi:'कैमरा अनुमति दें', ja:'カメラを許可', ky:'Камерага уруксат', 'zh-Hant':'允許相機' },
  perm_notify_title: { bg:'🔔 Известия', ru:'🔔 Уведомления', uk:'🔔 Сповіщення', en:'🔔 Notifications', de:'🔔 Benachrichtigungen', fr:'🔔 Notifications', es:'🔔 Notificaciones', 'es-MX':'🔔 Notificaciones', it:'🔔 Notifiche', pt:'🔔 Notificações', ar:'🔔 الإشعارات', hi:'🔔 सूचनाएँ', ja:'🔔 通知', ky:'🔔 Билдирүүлөр', 'zh-Hant':'🔔 通知' },
  perm_notify_desc: { bg:'За да те предупреди при събитие (събуди се / непознат / излезе от кадър).', ru:'Чтобы предупредить вас о событии (проснулся / незнакомец / вышел из кадра).', uk:'Щоб попередити вас про подію (прокинувся / незнайомець / вийшов з кадру).', en:'To alert you on an event (woke up / stranger / left the frame).', de:'Um dich bei einem Ereignis zu warnen (aufgewacht / Fremder / Bild verlassen).', fr:'Pour vous alerter d’un événement (réveillé / inconnu / sorti du cadre).', es:'Para avisarte de un evento (despertó / desconocido / salió del encuadre).', 'es-MX':'Para avisarte de un evento (despertó / desconocido / salió del encuadre).', it:'Per avvisarti di un evento (sveglio / sconosciuto / uscito dall’inquadratura).', pt:'Para te avisar de um evento (acordou / estranho / saiu do quadro).', ar:'لتنبيهك عند حدث (استيقظ / غريب / خرج من الإطار).', hi:'घटना पर आपको सचेत करने के लिए (जाग गया / अजनबी / फ़्रेम से बाहर)।', ja:'イベント時に知らせるため（起きた / 見知らぬ人 / フレーム外）。', ky:'Окуяда сизди эскертүү үчүн (ойгонду / бейтааныш / кадрдан чыкты).', 'zh-Hant':'用於事件發生時提醒您（醒了 / 陌生人 / 離開畫面）。' },
  perm_notify_btn: { bg:'Разреши известия', ru:'Разрешить уведомления', uk:'Дозволити сповіщення', en:'Allow notifications', de:'Benachrichtigungen erlauben', fr:'Autoriser les notifications', es:'Permitir notificaciones', 'es-MX':'Permitir notificaciones', it:'Consenti notifiche', pt:'Permitir notificações', ar:'السماح بالإشعارات', hi:'सूचनाएँ अनुमति दें', ja:'通知を許可', ky:'Билдирүүлөргө уруксат', 'zh-Hant':'允許通知' },
  perm_to_watch: { bg:'Към наблюдението', ru:'К наблюдению', uk:'До спостереження', en:'To monitoring', de:'Zur Überwachung', fr:'Vers la surveillance', es:'A la vigilancia', 'es-MX':'A la vigilancia', it:'Alla sorveglianza', pt:'Para a vigilância', ar:'إلى المراقبة', hi:'निगरानी की ओर', ja:'監視へ', ky:'Көзөмөлгө', 'zh-Hant':'前往監看' },
  perm_skip_note: { bg:'Можеш да продължиш и без разрешения — тогава наблюдението просто няма да работи, докато ги дадеш.', ru:'Можно продолжить и без разрешений — тогда наблюдение просто не будет работать, пока вы их не дадите.', uk:'Можна продовжити й без дозволів — тоді спостереження просто не працюватиме, доки ви їх не надасте.', en:'You can continue without permissions — monitoring just won’t work until you grant them.', de:'Du kannst auch ohne Berechtigungen fortfahren — die Überwachung funktioniert dann erst, wenn du sie erteilst.', fr:'Vous pouvez continuer sans autorisations — la surveillance ne fonctionnera tout simplement pas tant que vous ne les accordez pas.', es:'Puedes continuar sin permisos — la vigilancia simplemente no funcionará hasta que los concedas.', 'es-MX':'Puedes continuar sin permisos — la vigilancia simplemente no funcionará hasta que los concedas.', it:'Puoi continuare senza autorizzazioni — la sorveglianza non funzionerà finché non le concedi.', pt:'Você pode continuar sem permissões — a vigilância só não funcionará até concedê-las.', ar:'يمكنك المتابعة دون أذونات — لكن المراقبة لن تعمل حتى تمنحها.', hi:'आप बिना अनुमतियों के भी जारी रख सकते हैं — तब तक निगरानी काम नहीं करेगी जब तक आप उन्हें न दें।', ja:'権限なしでも続行できます — 付与するまで監視は動作しません。', ky:'Уруксатсыз да улантсаңыз болот — бирок аларды бергениңизге чейин көзөмөл иштебейт.', 'zh-Hant':'您可以不授予權限繼續 — 但在授予前監看將無法運作。' },
  perm_not_granted: { bg:'не е дадено', ru:'не предоставлено', uk:'не надано', en:'not granted', de:'nicht erteilt', fr:'non accordé', es:'no concedido', 'es-MX':'no concedido', it:'non concesso', pt:'não concedido', ar:'غير ممنوح', hi:'नहीं दिया', ja:'未許可', ky:'берилген эмес', 'zh-Hant':'未授予' },
  perm_granted: { bg:'дадено ✓', ru:'предоставлено ✓', uk:'надано ✓', en:'granted ✓', de:'erteilt ✓', fr:'accordé ✓', es:'concedido ✓', 'es-MX':'concedido ✓', it:'concesso ✓', pt:'concedido ✓', ar:'ممنوح ✓', hi:'दिया गया ✓', ja:'許可済み ✓', ky:'берилди ✓', 'zh-Hant':'已授予 ✓' },
  perm_denied: { bg:'отказано', ru:'отклонено', uk:'відхилено', en:'denied', de:'abgelehnt', fr:'refusé', es:'denegado', 'es-MX':'denegado', it:'negato', pt:'negado', ar:'مرفوض', hi:'अस्वीकृत', ja:'拒否', ky:'четке кагылды', 'zh-Hant':'已拒絕' },
  perm_no_cam_env: { bg:'няма камера (среда)', ru:'нет камеры (среда)', uk:'немає камери (середовище)', en:'no camera (environment)', de:'keine Kamera (Umgebung)', fr:'pas de caméra (environnement)', es:'sin cámara (entorno)', 'es-MX':'sin cámara (entorno)', it:'nessuna fotocamera (ambiente)', pt:'sem câmera (ambiente)', ar:'لا كاميرا (البيئة)', hi:'कोई कैमरा नहीं (वातावरण)', ja:'カメラなし（環境）', ky:'камера жок (чөйрө)', 'zh-Hant':'無相機（環境）' },
  perm_no_cam_toast: { bg:'Тази среда няма камера', ru:'В этой среде нет камеры', uk:'У цьому середовищі немає камери', en:'This environment has no camera', de:'Diese Umgebung hat keine Kamera', fr:'Cet environnement n’a pas de caméra', es:'Este entorno no tiene cámara', 'es-MX':'Este entorno no tiene cámara', it:'Questo ambiente non ha una fotocamera', pt:'Este ambiente não tem câmera', ar:'هذه البيئة لا تحتوي كاميرا', hi:'इस वातावरण में कैमरा नहीं है', ja:'この環境にはカメラがありません', ky:'Бул чөйрөдө камера жок', 'zh-Hant':'此環境沒有相機' },
  perm_no_api_env: { bg:'няма API (среда)', ru:'нет API (среда)', uk:'немає API (середовище)', en:'no API (environment)', de:'kein API (Umgebung)', fr:'pas d’API (environnement)', es:'sin API (entorno)', 'es-MX':'sin API (entorno)', it:'nessuna API (ambiente)', pt:'sem API (ambiente)', ar:'لا توجد API (البيئة)', hi:'कोई API नहीं (वातावरण)', ja:'APIなし（環境）', ky:'API жок (чөйрө)', 'zh-Hant':'無 API（環境）' },
  perm_notify_denied_toast: { bg:'Известията са отказани — пак ще има звук и дневник.', ru:'Уведомления отклонены — звук и журнал всё равно будут.', uk:'Сповіщення відхилено — звук і журнал усе одно будуть.', en:'Notifications denied — there will still be sound and a log.', de:'Benachrichtigungen abgelehnt — Ton und Protokoll gibt es trotzdem.', fr:'Notifications refusées — il y aura quand même du son et un journal.', es:'Notificaciones denegadas — aun así habrá sonido y registro.', 'es-MX':'Notificaciones denegadas — aun así habrá sonido y registro.', it:'Notifiche negate — ci saranno comunque suono e registro.', pt:'Notificações negadas — ainda haverá som e registro.', ar:'تم رفض الإشعارات — سيظل هناك صوت وسجل.', hi:'सूचनाएँ अस्वीकृत — फिर भी ध्वनि और लॉग रहेगा।', ja:'通知が拒否されました — 音とログは引き続き利用できます。', ky:'Билдирүүлөр четке кагылды — баары бир үн жана журнал болот.', 'zh-Hant':'通知已拒絕 — 仍會有聲音與記錄。' },

  // --- Камера: причини за грешка (camera.js) ---
  cam_err_unsupported: { bg:'Това устройство/среда не поддържа камера (няма getUserMedia).', ru:'Это устройство/среда не поддерживает камеру (нет getUserMedia).', uk:'Цей пристрій/середовище не підтримує камеру (немає getUserMedia).', en:'This device/environment does not support a camera (no getUserMedia).', de:'Dieses Gerät/diese Umgebung unterstützt keine Kamera (kein getUserMedia).', fr:'Cet appareil/environnement ne prend pas en charge la caméra (pas de getUserMedia).', es:'Este dispositivo/entorno no admite cámara (sin getUserMedia).', 'es-MX':'Este dispositivo/entorno no admite cámara (sin getUserMedia).', it:'Questo dispositivo/ambiente non supporta la fotocamera (niente getUserMedia).', pt:'Este dispositivo/ambiente não suporta câmera (sem getUserMedia).', ar:'هذا الجهاز/البيئة لا يدعم الكاميرا (لا getUserMedia).', hi:'यह डिवाइस/वातावरण कैमरा समर्थित नहीं करता (getUserMedia नहीं)।', ja:'この端末/環境はカメラに対応していません（getUserMediaなし）。', ky:'Бул түзмөк/чөйрө камераны колдобойт (getUserMedia жок).', 'zh-Hant':'此裝置/環境不支援相機（無 getUserMedia）。' },
  cam_err_open: { bg:'Не успях да отворя камерата.', ru:'Не удалось открыть камеру.', uk:'Не вдалося відкрити камеру.', en:'Could not open the camera.', de:'Kamera konnte nicht geöffnet werden.', fr:'Impossible d’ouvrir la caméra.', es:'No se pudo abrir la cámara.', 'es-MX':'No se pudo abrir la cámara.', it:'Impossibile aprire la fotocamera.', pt:'Não foi possível abrir a câmera.', ar:'تعذّر فتح الكاميرا.', hi:'कैमरा नहीं खुल सका।', ja:'カメラを開けませんでした。', ky:'Камераны ача алган жокмун.', 'zh-Hant':'無法開啟相機。' },
  cam_err_denied: { bg:'Достъпът до камерата е отказан. Разреши камерата за приложението и опитай пак.', ru:'Доступ к камере отклонён. Разрешите камеру для приложения и попробуйте снова.', uk:'Доступ до камери відхилено. Дозвольте камеру для застосунку і спробуйте ще раз.', en:'Camera access denied. Allow the camera for the app and try again.', de:'Kamerazugriff abgelehnt. Erlaube die Kamera für die App und versuche es erneut.', fr:'Accès à la caméra refusé. Autorisez la caméra pour l’application et réessayez.', es:'Acceso a la cámara denegado. Permite la cámara para la app e inténtalo de nuevo.', 'es-MX':'Acceso a la cámara denegado. Permite la cámara para la app e inténtalo de nuevo.', it:'Accesso alla fotocamera negato. Consenti la fotocamera per l’app e riprova.', pt:'Acesso à câmera negado. Permita a câmera para o app e tente novamente.', ar:'تم رفض الوصول إلى الكاميرا. اسمح بالكاميرا للتطبيق وحاول مجددًا.', hi:'कैमरा एक्सेस अस्वीकृत। ऐप के लिए कैमरा अनुमति दें और फिर प्रयास करें।', ja:'カメラへのアクセスが拒否されました。アプリにカメラを許可して再試行してください。', ky:'Камерага мүмкүндүк четке кагылды. Колдонмого камераны уруксат берип, кайра аракет кылыңыз.', 'zh-Hant':'相機存取被拒。請為應用程式允許相機後再試。' },
  cam_err_notfound: { bg:'Не открих камера на това устройство.', ru:'Камера на этом устройстве не найдена.', uk:'Камеру на цьому пристрої не знайдено.', en:'No camera found on this device.', de:'Keine Kamera auf diesem Gerät gefunden.', fr:'Aucune caméra trouvée sur cet appareil.', es:'No se encontró cámara en este dispositivo.', 'es-MX':'No se encontró cámara en este dispositivo.', it:'Nessuna fotocamera trovata su questo dispositivo.', pt:'Nenhuma câmera encontrada neste dispositivo.', ar:'لم يُعثر على كاميرا في هذا الجهاز.', hi:'इस डिवाइस पर कोई कैमरा नहीं मिला।', ja:'この端末でカメラが見つかりません。', ky:'Бул түзмөктө камера табылган жок.', 'zh-Hant':'此裝置找不到相機。' },
  cam_err_busy: { bg:'Камерата е заета от друго приложение.', ru:'Камера занята другим приложением.', uk:'Камеру зайнято іншим застосунком.', en:'The camera is busy with another app.', de:'Die Kamera wird von einer anderen App verwendet.', fr:'La caméra est utilisée par une autre application.', es:'La cámara está ocupada por otra app.', 'es-MX':'La cámara está ocupada por otra app.', it:'La fotocamera è occupata da un’altra app.', pt:'A câmera está ocupada por outro app.', ar:'الكاميرا مشغولة بتطبيق آخر.', hi:'कैमरा दूसरे ऐप द्वारा व्यस्त है।', ja:'カメラは別のアプリで使用中です。', ky:'Камера башка колдонмо менен бош эмес.', 'zh-Hant':'相機正被另一個應用程式占用。' },
  cam_err_no_url: { bg:'Не е зададен URL за другата камера.', ru:'URL другой камеры не задан.', uk:'URL іншої камери не задано.', en:'No URL set for the other camera.', de:'Keine URL für die andere Kamera festgelegt.', fr:'Aucune URL définie pour l’autre caméra.', es:'No se estableció URL para la otra cámara.', 'es-MX':'No se estableció URL para la otra cámara.', it:'Nessun URL impostato per l’altra fotocamera.', pt:'Nenhuma URL definida para a outra câmera.', ar:'لم يُحدَّد رابط للكاميرا الأخرى.', hi:'अन्य कैमरे के लिए कोई URL सेट नहीं।', ja:'別カメラのURLが設定されていません。', ky:'Башка камера үчүн URL берилген эмес.', 'zh-Hant':'未設定其他相機的 URL。' },
  cam_err_rtsp: { bg:'RTSP не се поддържа от браузъра. Нужен е gateway/транскодиране до HLS/MJPEG.', ru:'RTSP не поддерживается браузером. Нужен gateway/транскодирование в HLS/MJPEG.', uk:'RTSP не підтримується браузером. Потрібен gateway/транскодування в HLS/MJPEG.', en:'RTSP is not supported by the browser. A gateway/transcoding to HLS/MJPEG is needed.', de:'RTSP wird vom Browser nicht unterstützt. Ein Gateway/Transcoding zu HLS/MJPEG ist nötig.', fr:'RTSP n’est pas pris en charge par le navigateur. Une passerelle/transcodage vers HLS/MJPEG est nécessaire.', es:'RTSP no es compatible con el navegador. Se necesita un gateway/transcodificación a HLS/MJPEG.', 'es-MX':'RTSP no es compatible con el navegador. Se necesita un gateway/transcodificación a HLS/MJPEG.', it:'RTSP non è supportato dal browser. Serve un gateway/transcodifica verso HLS/MJPEG.', pt:'RTSP não é suportado pelo navegador. É preciso um gateway/transcodificação para HLS/MJPEG.', ar:'RTSP غير مدعوم في المتصفّح. يلزم gateway/تحويل ترميز إلى HLS/MJPEG.', hi:'ब्राउज़र RTSP समर्थित नहीं करता। HLS/MJPEG में gateway/ट्रांसकोडिंग चाहिए।', ja:'RTSPはブラウザで非対応です。HLS/MJPEGへのゲートウェイ/トランスコードが必要です。', ky:'RTSP браузерде колдоого алынбайт. HLS/MJPEGге gateway/транскоддоо керек.', 'zh-Hant':'瀏覽器不支援 RTSP。需要轉換為 HLS/MJPEG 的閘道/轉碼。' },
  cam_err_load_url: { bg:'Не успях да заредя потока от URL. Провери адреса/CORS/формата.', ru:'Не удалось загрузить поток по URL. Проверьте адрес/CORS/формат.', uk:'Не вдалося завантажити потік за URL. Перевірте адресу/CORS/формат.', en:'Could not load the stream from the URL. Check the address/CORS/format.', de:'Stream von der URL konnte nicht geladen werden. Prüfe Adresse/CORS/Format.', fr:'Impossible de charger le flux depuis l’URL. Vérifiez l’adresse/CORS/format.', es:'No se pudo cargar el flujo desde la URL. Comprueba la dirección/CORS/formato.', 'es-MX':'No se pudo cargar el flujo desde la URL. Comprueba la dirección/CORS/formato.', it:'Impossibile caricare lo stream dall’URL. Controlla indirizzo/CORS/formato.', pt:'Não foi possível carregar o fluxo da URL. Verifique endereço/CORS/formato.', ar:'تعذّر تحميل البث من الرابط. تحقّق من العنوان/CORS/الصيغة.', hi:'URL से स्ट्रीम लोड नहीं हो सका। पता/CORS/फ़ॉर्मेट जाँचें।', ja:'URLからストリームを読み込めませんでした。アドレス/CORS/形式を確認してください。', ky:'URL дан агымды жүктөй албадым. Дарек/CORS/форматты текшериңиз.', 'zh-Hant':'無法從 URL 載入串流。請檢查網址/CORS/格式。' },

  // --- Dashboard / наблюдение ---
  state_calm: { bg:'Спи спокойно', ru:'Спит спокойно', uk:'Спить спокійно', en:'Sleeping calmly', de:'Schläft ruhig', fr:'Dort calmement', es:'Duerme tranquilo', 'es-MX':'Duerme tranquilo', it:'Dorme tranquillo', pt:'Dormindo calmo', ar:'نائم بهدوء', hi:'शांति से सो रहा', ja:'静かに就寝中', ky:'Тынч уктап жатат', 'zh-Hant':'安睡中' },
  state_stir: { bg:'Размърдва се', ru:'Шевелится', uk:'Ворушиться', en:'Stirring', de:'Regt sich', fr:'S’agite', es:'Se mueve', 'es-MX':'Se mueve', it:'Si agita', pt:'Se mexendo', ar:'يتحرّك', hi:'हिल रहा', ja:'もぞもぞ', ky:'Кыймылдайт', 'zh-Hant':'蠕動中' },
  state_awake: { bg:'Събуди се', ru:'Проснулся', uk:'Прокинувся', en:'Awake', de:'Wach', fr:'Réveillé', es:'Despierto', 'es-MX':'Despierto', it:'Sveglio', pt:'Acordado', ar:'مستيقظ', hi:'जाग गया', ja:'起きた', ky:'Ойгонду', 'zh-Hant':'醒了' },
  state_waiting: { bg:'Изчаквам…', ru:'Ожидание…', uk:'Очікування…', en:'Waiting…', de:'Warte…', fr:'En attente…', es:'Esperando…', 'es-MX':'Esperando…', it:'In attesa…', pt:'Aguardando…', ar:'في الانتظار…', hi:'प्रतीक्षा…', ja:'待機中…', ky:'Күтүүдө…', 'zh-Hant':'等待中…' },
  btn_start: { bg:'Старт', ru:'Старт', uk:'Старт', en:'Start', de:'Start', fr:'Démarrer', es:'Iniciar', 'es-MX':'Iniciar', it:'Avvia', pt:'Iniciar', ar:'ابدأ', hi:'शुरू', ja:'開始', ky:'Баштоо', 'zh-Hant':'開始' },
  btn_stop: { bg:'Стоп', ru:'Стоп', uk:'Стоп', en:'Stop', de:'Stopp', fr:'Arrêter', es:'Detener', 'es-MX':'Detener', it:'Ferma', pt:'Parar', ar:'إيقاف', hi:'रोकें', ja:'停止', ky:'Токтотуу', 'zh-Hant':'停止' },
  model_unloaded: { bg:'модел: не зареден', ru:'модель: не загружена', uk:'модель: не завантажена', en:'model: not loaded', de:'Modell: nicht geladen', fr:'modèle : non chargé', es:'modelo: no cargado', 'es-MX':'modelo: no cargado', it:'modello: non caricato', pt:'modelo: não carregado', ar:'النموذج: غير محمّل', hi:'मॉडल: लोड नहीं', ja:'モデル: 未読込', ky:'модель: жүктөлгөн жок', 'zh-Hant':'模型：未載入' },
  model_loading: { bg:'модел: зарежда…', ru:'модель: загрузка…', uk:'модель: завантаження…', en:'model: loading…', de:'Modell: lädt…', fr:'modèle : chargement…', es:'modelo: cargando…', 'es-MX':'modelo: cargando…', it:'modello: caricamento…', pt:'modelo: carregando…', ar:'النموذج: جارٍ التحميل…', hi:'मॉडल: लोड हो रहा…', ja:'モデル: 読込中…', ky:'модель: жүктөлүүдө…', 'zh-Hant':'模型：載入中…' },
  model_ready: { bg:'модел: готов ✓', ru:'модель: готова ✓', uk:'модель: готова ✓', en:'model: ready ✓', de:'Modell: bereit ✓', fr:'modèle : prêt ✓', es:'modelo: listo ✓', 'es-MX':'modelo: listo ✓', it:'modello: pronto ✓', pt:'modelo: pronto ✓', ar:'النموذج: جاهز ✓', hi:'मॉडल: तैयार ✓', ja:'モデル: 準備完了 ✓', ky:'модель: даяр ✓', 'zh-Hant':'模型：就緒 ✓' },
  model_unavailable: { bg:'модел: недостъпен (само движение)', ru:'модель: недоступна (только движение)', uk:'модель: недоступна (лише рух)', en:'model: unavailable (motion only)', de:'Modell: nicht verfügbar (nur Bewegung)', fr:'modèle : indisponible (mouvement seul)', es:'modelo: no disponible (solo movimiento)', 'es-MX':'modelo: no disponible (solo movimiento)', it:'modello: non disponibile (solo movimento)', pt:'modelo: indisponível (só movimento)', ar:'النموذج: غير متاح (الحركة فقط)', hi:'मॉडल: अनुपलब्ध (केवल गति)', ja:'モデル: 利用不可（動きのみ）', ky:'модель: жеткиликсиз (кыймыл гана)', 'zh-Hant':'模型：無法使用（僅動作）' },
  people_label: { bg:'хора', ru:'люди', uk:'люди', en:'people', de:'Personen', fr:'personnes', es:'personas', 'es-MX':'personas', it:'persone', pt:'pessoas', ar:'أشخاص', hi:'लोग', ja:'人数', ky:'адам', 'zh-Hant':'人數' },
  timeline_title: { bg:'Движение (последни кадри)', ru:'Движение (последние кадры)', uk:'Рух (останні кадри)', en:'Motion (recent frames)', de:'Bewegung (letzte Bilder)', fr:'Mouvement (dernières images)', es:'Movimiento (cuadros recientes)', 'es-MX':'Movimiento (cuadros recientes)', it:'Movimento (fotogrammi recenti)', pt:'Movimento (quadros recentes)', ar:'الحركة (الإطارات الأخيرة)', hi:'गति (हाल के फ़्रेम)', ja:'動き（直近のフレーム）', ky:'Кыймыл (акыркы кадрлар)', 'zh-Hant':'動作（最近畫面）' },
  recent_events: { bg:'Последни събития', ru:'Последние события', uk:'Останні події', en:'Recent events', de:'Letzte Ereignisse', fr:'Événements récents', es:'Eventos recientes', 'es-MX':'Eventos recientes', it:'Eventi recenti', pt:'Eventos recentes', ar:'الأحداث الأخيرة', hi:'हाल की घटनाएँ', ja:'最近のイベント', ky:'Акыркы окуялар', 'zh-Hant':'近期事件' },
  full_log: { bg:'Целият дневник', ru:'Весь журнал', uk:'Увесь журнал', en:'Full log', de:'Vollständiges Protokoll', fr:'Journal complet', es:'Registro completo', 'es-MX':'Registro completo', it:'Registro completo', pt:'Registro completo', ar:'السجل الكامل', hi:'पूरा लॉग', ja:'全ログ', ky:'Толук журнал', 'zh-Hant':'完整記錄' },
  no_events_yet: { bg:'Още няма събития.', ru:'Событий пока нет.', uk:'Подій поки немає.', en:'No events yet.', de:'Noch keine Ereignisse.', fr:'Pas encore d’événements.', es:'Aún no hay eventos.', 'es-MX':'Aún no hay eventos.', it:'Ancora nessun evento.', pt:'Ainda não há eventos.', ar:'لا أحداث بعد.', hi:'अभी कोई घटना नहीं।', ja:'まだイベントはありません。', ky:'Азырынча окуялар жок.', 'zh-Hant':'尚無事件。' },
  no_camera_toast: { bg:'Тази среда няма камера. Пусни на телефон или ползвай „Друга камера (URL)".', ru:'В этой среде нет камеры. Запустите на телефоне или используйте «Другая камера (URL)».', uk:'У цьому середовищі немає камери. Запустіть на телефоні або скористайтесь «Інша камера (URL)».', en:'This environment has no camera. Run on a phone or use “Other camera (URL)”.', de:'Diese Umgebung hat keine Kamera. Auf einem Telefon ausführen oder „Andere Kamera (URL)" nutzen.', fr:'Cet environnement n’a pas de caméra. Lancez sur un téléphone ou utilisez « Autre caméra (URL) ».', es:'Este entorno no tiene cámara. Ejecuta en un teléfono o usa «Otra cámara (URL)».', 'es-MX':'Este entorno no tiene cámara. Ejecuta en un teléfono o usa «Otra cámara (URL)».', it:'Questo ambiente non ha una fotocamera. Esegui su un telefono o usa «Altra fotocamera (URL)».', pt:'Este ambiente não tem câmera. Execute em um telefone ou use “Outra câmera (URL)”.', ar:'هذه البيئة لا تحتوي كاميرا. شغّله على هاتف أو استخدم «كاميرا أخرى (URL)».', hi:'इस वातावरण में कैमरा नहीं है। फ़ोन पर चलाएँ या “अन्य कैमरा (URL)” का उपयोग करें।', ja:'この環境にはカメラがありません。スマホで実行するか「別のカメラ（URL）」を使ってください。', ky:'Бул чөйрөдө камера жок. Телефондо иштетиңиз же «Башка камера (URL)» колдонуңуз.', 'zh-Hant':'此環境沒有相機。請在手機上執行，或使用「其他相機（URL）」。' },
  watch_started: { bg:'Наблюдението започна', ru:'Наблюдение началось', uk:'Спостереження почалося', en:'Monitoring started', de:'Überwachung gestartet', fr:'Surveillance démarrée', es:'Vigilancia iniciada', 'es-MX':'Vigilancia iniciada', it:'Sorveglianza avviata', pt:'Vigilância iniciada', ar:'بدأت المراقبة', hi:'निगरानी शुरू', ja:'監視を開始しました', ky:'Көзөмөл башталды', 'zh-Hant':'監看已開始' },
  watch_stopped: { bg:'Наблюдението спря', ru:'Наблюдение остановлено', uk:'Спостереження зупинено', en:'Monitoring stopped', de:'Überwachung gestoppt', fr:'Surveillance arrêtée', es:'Vigilancia detenida', 'es-MX':'Vigilancia detenida', it:'Sorveglianza fermata', pt:'Vigilância parada', ar:'تم إيقاف المراقبة', hi:'निगरानी रुकी', ja:'監視を停止しました', ky:'Көзөмөл токтоду', 'zh-Hant':'監看已停止' },

  // --- Типове събития (дневник) ---
  ev_wake: { bg:'Събуди се', ru:'Проснулся', uk:'Прокинувся', en:'Woke up', de:'Aufgewacht', fr:'Réveillé', es:'Despertó', 'es-MX':'Despertó', it:'Sveglio', pt:'Acordou', ar:'استيقظ', hi:'जाग गया', ja:'起きた', ky:'Ойгонду', 'zh-Hant':'醒了' },
  ev_stranger: { bg:'Непознат в стаята', ru:'Незнакомец в комнате', uk:'Незнайомець у кімнаті', en:'Stranger in the room', de:'Fremder im Raum', fr:'Inconnu dans la pièce', es:'Desconocido en la habitación', 'es-MX':'Desconocido en la habitación', it:'Sconosciuto nella stanza', pt:'Estranho no quarto', ar:'غريب في الغرفة', hi:'कमरे में अजनबी', ja:'部屋に見知らぬ人', ky:'Бөлмөдө бейтааныш', 'zh-Hant':'房間有陌生人' },
  ev_left: { bg:'Излезе от кадър', ru:'Вышел из кадра', uk:'Вийшов з кадру', en:'Left the frame', de:'Bild verlassen', fr:'Sorti du cadre', es:'Salió del encuadre', 'es-MX':'Salió del encuadre', it:'Uscito dall’inquadratura', pt:'Saiu do quadro', ar:'خرج من الإطار', hi:'फ़्रेम से बाहर', ja:'フレームから出た', ky:'Кадрдан чыкты', 'zh-Hant':'離開畫面' },
  ev_fire: { bg:'Възможен пожар (груба евристика)', ru:'Возможен пожар (грубая эвристика)', uk:'Можлива пожежа (груба евристика)', en:'Possible fire (rough heuristic)', de:'Möglicher Brand (grobe Heuristik)', fr:'Incendie possible (heuristique grossière)', es:'Posible incendio (heurística aproximada)', 'es-MX':'Posible incendio (heurística aproximada)', it:'Possibile incendio (euristica grossolana)', pt:'Possível incêndio (heurística grosseira)', ar:'حريق محتمل (تقدير تقريبي)', hi:'संभावित आग (मोटा अनुमान)', ja:'火災の可能性（粗い推定）', ky:'Мүмкүн өрт (одоно эвристика)', 'zh-Hant':'可能起火（粗略判斷）' },
  ev_generic: { bg:'Събитие', ru:'Событие', uk:'Подія', en:'Event', de:'Ereignis', fr:'Événement', es:'Evento', 'es-MX':'Evento', it:'Evento', pt:'Evento', ar:'حدث', hi:'घटना', ja:'イベント', ky:'Окуя', 'zh-Hant':'事件' },

  // --- Текстове на събитията (тялото на известието) ---
  evmsg_wake: { bg:'Детето се събуди (устойчиво движение).', ru:'Ребёнок проснулся (устойчивое движение).', uk:'Дитина прокинулася (стійкий рух).', en:'The child woke up (sustained motion).', de:'Das Kind ist aufgewacht (anhaltende Bewegung).', fr:'L’enfant s’est réveillé (mouvement soutenu).', es:'El niño se despertó (movimiento sostenido).', 'es-MX':'El niño se despertó (movimiento sostenido).', it:'Il bambino si è svegliato (movimento sostenuto).', pt:'A criança acordou (movimento contínuo).', ar:'استيقظ الطفل (حركة مستمرة).', hi:'बच्चा जाग गया (लगातार गति)।', ja:'子どもが起きました（継続的な動き）。', ky:'Бала ойгонду (туруктуу кыймыл).', 'zh-Hant':'孩子醒了（持續動作）。' },
  evmsg_fire: { bg:'Възможен ярък блясък (ГРУБА евристика — НЕ е датчик за дим!).', ru:'Возможна яркая вспышка (ГРУБАЯ эвристика — НЕ датчик дыма!).', uk:'Можливий яскравий спалах (ГРУБА евристика — НЕ датчик диму!).', en:'Possible bright flare (ROUGH heuristic — NOT a smoke detector!).', de:'Möglicher heller Schein (GROBE Heuristik — KEIN Rauchmelder!).', fr:'Éclat lumineux possible (heuristique GROSSIÈRE — PAS un détecteur de fumée !).', es:'Posible destello brillante (heurística APROXIMADA — ¡NO es un detector de humo!).', 'es-MX':'Posible destello brillante (heurística APROXIMADA — ¡NO es un detector de humo!).', it:'Possibile bagliore intenso (euristica GROSSOLANA — NON è un rilevatore di fumo!).', pt:'Possível clarão intenso (heurística GROSSEIRA — NÃO é um detector de fumaça!).', ar:'وميض ساطع محتمل (تقدير تقريبي — ليس كاشف دخان!).', hi:'संभावित तेज़ चमक (मोटा अनुमान — धुआँ सेंसर नहीं!)।', ja:'明るい閃光の可能性（粗い推定 — 煙感知器ではありません！）。', ky:'Мүмкүн жаркыраган жарык (ОДОНО эвристика — түтүн датчиги ЭМЕС!).', 'zh-Hant':'可能的強光閃爍（粗略判斷 — 並非煙霧偵測器！）。' },
  evmsg_stranger: { bg:'Втори човек в стаята (непознат?).', ru:'Второй человек в комнате (незнакомец?).', uk:'Друга людина в кімнаті (незнайомець?).', en:'A second person in the room (a stranger?).', de:'Eine zweite Person im Raum (ein Fremder?).', fr:'Une deuxième personne dans la pièce (un inconnu ?).', es:'Una segunda persona en la habitación (¿un desconocido?).', 'es-MX':'Una segunda persona en la habitación (¿un desconocido?).', it:'Una seconda persona nella stanza (uno sconosciuto?).', pt:'Uma segunda pessoa no quarto (um estranho?).', ar:'شخص ثانٍ في الغرفة (غريب؟).', hi:'कमरे में दूसरा व्यक्ति (अजनबी?)।', ja:'部屋に2人目（見知らぬ人？）。', ky:'Бөлмөдө экинчи адам (бейтааныш?).', 'zh-Hant':'房間裡有第二人（陌生人？）。' },
  evmsg_left: { bg:'Детето излезе от кадър.', ru:'Ребёнок вышел из кадра.', uk:'Дитина вийшла з кадру.', en:'The child left the frame.', de:'Das Kind hat das Bild verlassen.', fr:'L’enfant a quitté le cadre.', es:'El niño salió del encuadre.', 'es-MX':'El niño salió del encuadre.', it:'Il bambino è uscito dall’inquadratura.', pt:'A criança saiu do quadro.', ar:'خرج الطفل من الإطار.', hi:'बच्चा फ़्रेम से बाहर चला गया।', ja:'子どもがフレームから出ました。', ky:'Бала кадрдан чыкты.', 'zh-Hant':'孩子離開了畫面。' },

  // --- Дневник (екран) ---
  log_clear: { bg:'Изчисти', ru:'Очистить', uk:'Очистити', en:'Clear', de:'Leeren', fr:'Effacer', es:'Borrar', 'es-MX':'Borrar', it:'Cancella', pt:'Limpar', ar:'مسح', hi:'साफ़ करें', ja:'消去', ky:'Тазалоо', 'zh-Hant':'清除' },
  log_cleared: { bg:'Дневникът е изчистен', ru:'Журнал очищен', uk:'Журнал очищено', en:'Log cleared', de:'Protokoll geleert', fr:'Journal effacé', es:'Registro borrado', 'es-MX':'Registro borrado', it:'Registro cancellato', pt:'Registro limpo', ar:'تم مسح السجل', hi:'लॉग साफ़ हुआ', ja:'ログを消去しました', ky:'Журнал тазаланды', 'zh-Hant':'記錄已清除' },
  log_empty: { bg:'Няма записани събития. Стартирай наблюдението от „Наблюдение".', ru:'Нет записанных событий. Запустите наблюдение из «Наблюдение».', uk:'Немає записаних подій. Запустіть спостереження з «Спостереження».', en:'No recorded events. Start monitoring from “Watch”.', de:'Keine aufgezeichneten Ereignisse. Starte die Überwachung über „Überwachen".', fr:'Aucun événement enregistré. Démarrez la surveillance depuis « Surveillance ».', es:'Sin eventos registrados. Inicia la vigilancia desde «Vigilancia».', 'es-MX':'Sin eventos registrados. Inicia la vigilancia desde «Vigilancia».', it:'Nessun evento registrato. Avvia la sorveglianza da «Sorveglianza».', pt:'Nenhum evento registrado. Inicie a vigilância em “Vigilância”.', ar:'لا أحداث مسجّلة. ابدأ المراقبة من «المراقبة».', hi:'कोई दर्ज घटना नहीं। “निगरानी” से निगरानी शुरू करें।', ja:'記録されたイベントはありません。「監視」から監視を開始してください。', ky:'Жазылган окуялар жок. «Көзөмөл» бөлүмүнөн көзөмөлдү баштаңыз.', 'zh-Hant':'沒有記錄的事件。請從「監看」開始監看。' },

  // --- Наблюдаващ (watcher екран) ---
  w_title: { bg:'🔔 Наблюдаващ (Майка Тереза)', ru:'🔔 Наблюдатель (Мать Тереза)', uk:'🔔 Спостерігач (Мати Тереза)', en:'🔔 Watcher (Mother Teresa)', de:'🔔 Beobachter (Mutter Teresa)', fr:'🔔 Observateur (Mère Teresa)', es:'🔔 Observador (Madre Teresa)', 'es-MX':'🔔 Observador (Madre Teresa)', it:'🔔 Osservatore (Madre Teresa)', pt:'🔔 Observador (Madre Teresa)', ar:'🔔 المستقبِل (الأم تيريزا)', hi:'🔔 वॉचर (मदर टेरेसा)', ja:'🔔 ウォッチャー（マザー・テレサ）', ky:'🔔 Байкоочу (Эне Тереза)', 'zh-Hant':'🔔 接收端（德蕾莎修女）' },
  w_not_paired: { bg:'Още не е сдвоено. Отвори Настройки → „Сдвояване (2 телефона)" и въведи ключа за двойката (същия като на телефона-детегледачка).', ru:'Ещё не сопряжено. Откройте Настройки → «Сопряжение (2 телефона)» и введите ключ пары (тот же, что на телефоне-няне).', uk:'Ще не спарено. Відкрийте Налаштування → «Спарювання (2 телефони)» і введіть ключ пари (той самий, що на телефоні-няні).', en:'Not paired yet. Open Settings → “Pairing (2 phones)” and enter the pair key (the same as on the monitor phone).', de:'Noch nicht gekoppelt. Öffne Einstellungen → „Kopplung (2 Telefone)" und gib den Paarschlüssel ein (derselbe wie auf dem Monitor-Telefon).', fr:'Pas encore appairé. Ouvrez Réglages → « Appairage (2 téléphones) » et saisissez la clé de paire (la même que sur le téléphone moniteur).', es:'Aún no emparejado. Abre Ajustes → «Emparejamiento (2 teléfonos)» e introduce la clave de pareja (la misma que en el teléfono monitor).', 'es-MX':'Aún no emparejado. Abre Ajustes → «Emparejamiento (2 teléfonos)» e introduce la clave de pareja (la misma que en el teléfono monitor).', it:'Non ancora abbinato. Apri Impostazioni → «Abbinamento (2 telefoni)» e inserisci la chiave di coppia (la stessa del telefono monitor).', pt:'Ainda não pareado. Abra Configurações → “Pareamento (2 telefones)” e digite a chave de par (a mesma do telefone monitor).', ar:'لم يقترن بعد. افتح الإعدادات → «الاقتران (هاتفان)» وأدخل مفتاح الاقتران (نفسه في هاتف المراقِب).', hi:'अभी पेयर नहीं हुआ। सेटिंग्स → “पेयरिंग (2 फ़ोन)” खोलें और पेयर कुंजी दर्ज करें (मॉनिटर फ़ोन वाली ही)।', ja:'まだペア未設定です。設定 →「ペア設定（2台）」を開き、ペアキー（モニター端末と同じ）を入力してください。', ky:'Азырынча жупташпаган. Жөндөөлөр → «Жупташтыруу (2 телефон)» ачып, жуп ачкычын киргизиңиз (кароол телефондогудай эле).', 'zh-Hant':'尚未配對。開啟設定 →「配對（2 支手機）」並輸入配對金鑰（與監看端手機相同）。' },
  w_to_settings: { bg:'Към Настройки', ru:'К настройкам', uk:'До налаштувань', en:'To Settings', de:'Zu den Einstellungen', fr:'Vers les Réglages', es:'A Ajustes', 'es-MX':'A Ajustes', it:'Alle Impostazioni', pt:'Para Configurações', ar:'إلى الإعدادات', hi:'सेटिंग्स पर', ja:'設定へ', ky:'Жөндөөлөргө', 'zh-Hant':'前往設定' },
  w_paired_info: { bg:'Сдвоен. Проверявам за нови събития на всеки {0} сек. При събитие ще чуеш известие (критичните — с алармена мелодия) и ще видиш последния кадър от стаята.', ru:'Сопряжено. Проверяю новые события каждые {0} сек. При событии вы услышите уведомление (критические — с тревожной мелодией) и увидите последний кадр из комнаты.', uk:'Спарено. Перевіряю нові події кожні {0} сек. При події ви почуєте сповіщення (критичні — з тривожною мелодією) і побачите останній кадр із кімнати.', en:'Paired. Checking for new events every {0} sec. On an event you’ll hear a notification (critical ones with an alarm melody) and see the last frame from the room.', de:'Gekoppelt. Prüfe alle {0} Sek. auf neue Ereignisse. Bei einem Ereignis hörst du eine Benachrichtigung (kritische mit Alarmmelodie) und siehst das letzte Bild aus dem Raum.', fr:'Appairé. Vérification des nouveaux événements toutes les {0} sec. Lors d’un événement, vous entendrez une notification (critiques avec mélodie d’alarme) et verrez la dernière image de la pièce.', es:'Emparejado. Comprobando nuevos eventos cada {0} seg. En un evento oirás una notificación (los críticos con melodía de alarma) y verás el último cuadro de la habitación.', 'es-MX':'Emparejado. Comprobando nuevos eventos cada {0} seg. En un evento oirás una notificación (los críticos con melodía de alarma) y verás el último cuadro de la habitación.', it:'Abbinato. Controllo nuovi eventi ogni {0} sec. A un evento sentirai una notifica (quelli critici con melodia d’allarme) e vedrai l’ultimo fotogramma dalla stanza.', pt:'Pareado. Verificando novos eventos a cada {0} seg. Em um evento você ouvirá uma notificação (os críticos com melodia de alarme) e verá o último quadro do quarto.', ar:'مقترن. أتحقّق من الأحداث الجديدة كل {0} ث. عند حدث ستسمع إشعارًا (الحرجة بنغمة إنذار) وترى آخر إطار من الغرفة.', hi:'पेयर हो गया। हर {0} सेकंड में नई घटनाएँ जाँच रहा। घटना पर आपको सूचना सुनाई देगी (गंभीर — अलार्म धुन के साथ) और कमरे का अंतिम फ़्रेम दिखेगा।', ja:'ペア済み。{0}秒ごとに新しいイベントを確認します。イベント時には通知（重大なものはアラーム音）が鳴り、部屋の最後のフレームが表示されます。', ky:'Жупташты. Жаңы окуяларды ар {0} сек текшерем. Окуяда билдирүү угасыз (өтө маанилүүлөрү — дабыл обону менен) жана бөлмөнүн акыркы кадрын көрөсүз.', 'zh-Hant':'已配對。每 {0} 秒檢查新事件。發生事件時您會聽到通知（重大事件附警報旋律）並看到房間的最後畫面。' },
  w_connection: { bg:'Връзка:', ru:'Связь:', uk:'Зв’язок:', en:'Connection:', de:'Verbindung:', fr:'Connexion :', es:'Conexión:', 'es-MX':'Conexión:', it:'Connessione:', pt:'Conexão:', ar:'الاتصال:', hi:'कनेक्शन:', ja:'接続:', ky:'Байланыш:', 'zh-Hant':'連線：' },
  w_connecting: { bg:'свързвам…', ru:'подключаюсь…', uk:'підключаюсь…', en:'connecting…', de:'verbinde…', fr:'connexion…', es:'conectando…', 'es-MX':'conectando…', it:'connessione…', pt:'conectando…', ar:'جارٍ الاتصال…', hi:'जुड़ रहा…', ja:'接続中…', ky:'туташууда…', 'zh-Hant':'連線中…' },
  w_listening: { bg:'слуша ✓', ru:'слушает ✓', uk:'слухає ✓', en:'listening ✓', de:'höre ✓', fr:'à l’écoute ✓', es:'escuchando ✓', 'es-MX':'escuchando ✓', it:'in ascolto ✓', pt:'ouvindo ✓', ar:'يستمع ✓', hi:'सुन रहा ✓', ja:'待受中 ✓', ky:'угуп жатат ✓', 'zh-Hant':'監聽中 ✓' },
  w_no_events: { bg:'Още няма събития. Чакам сигнал от стаята…', ru:'Событий пока нет. Жду сигнал из комнаты…', uk:'Подій поки немає. Чекаю сигнал із кімнати…', en:'No events yet. Waiting for a signal from the room…', de:'Noch keine Ereignisse. Warte auf ein Signal aus dem Raum…', fr:'Pas encore d’événements. En attente d’un signal de la pièce…', es:'Aún no hay eventos. Esperando una señal de la habitación…', 'es-MX':'Aún no hay eventos. Esperando una señal de la habitación…', it:'Ancora nessun evento. In attesa di un segnale dalla stanza…', pt:'Ainda não há eventos. Aguardando um sinal do quarto…', ar:'لا أحداث بعد. في انتظار إشارة من الغرفة…', hi:'अभी कोई घटना नहीं। कमरे से संकेत की प्रतीक्षा…', ja:'まだイベントはありません。部屋からの信号を待っています…', ky:'Азырынча окуялар жок. Бөлмөдөн сигнал күтүүдө…', 'zh-Hant':'尚無事件。等待房間的訊號…' },
  w_last_frame: { bg:'Последен кадър от стаята', ru:'Последний кадр из комнаты', uk:'Останній кадр із кімнати', en:'Last frame from the room', de:'Letztes Bild aus dem Raum', fr:'Dernière image de la pièce', es:'Último cuadro de la habitación', 'es-MX':'Último cuadro de la habitación', it:'Ultimo fotogramma dalla stanza', pt:'Último quadro do quarto', ar:'آخر إطار من الغرفة', hi:'कमरे का अंतिम फ़्रेम', ja:'部屋の最後のフレーム', ky:'Бөлмөнүн акыркы кадры', 'zh-Hant':'房間的最後畫面' }
};

let current = detect();

function detect() {
  try { const s = localStorage.getItem(LS_KEY); if (s && STR.save[s] != null) return s; } catch (e) {}
  return DEFAULT_LANG;
}

export function hasLangChosen() {
  try { return !!localStorage.getItem(LS_KEY); } catch (e) { return false; }
}
export function getLang() { return current; }
export function setLang(code) {
  if (STR.save[code] == null) return;
  current = code;
  try { localStorage.setItem(LS_KEY, code); } catch (e) {}
  applyDir();
}
export function isRTL() { return RTL_CODES.indexOf(current) > -1; }
export function applyDir() {
  try {
    document.documentElement.setAttribute('dir', isRTL() ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', current);
  } catch (e) {}
}
export function t(key) {
  const row = STR[key];
  if (!row) return key;
  if (row[current] != null) return row[current];
  if (row[DEFAULT_LANG] != null) return row[DEFAULT_LANG];
  if (row[FALLBACK_LANG] != null) return row[FALLBACK_LANG];
  return key;
}
export function tf(key, ...vals) {
  let s = t(key);
  vals.forEach((v, i) => { s = s.replace(new RegExp('\\{' + i + '\\}', 'g'), String(v)); });
  return s;
}
export { LANGUAGES, languageByCode };
