// Version: 1.0018
// i18n.js — преводен слой на „Цена-робот" за 15-те езика на екосистемата.
// Език по подразбиране: руски (до избор от потребителя при първо стартиране).
// Резервна верига при липсващ ключ: текущ → ru → en → самият ключ.
// Бележка: приложението показва САМО ценова информация и известия — без търговия,
// без плащания. Текстовете говорят за цени/прагове/известия, не за сделки.
import { LANGUAGES, languageByCode, RTL_CODES } from './languages.js';

const LS_KEY = 'pricewatch.lang';
const DEFAULT_LANG = 'ru';
const FALLBACK_LANG = 'en';

const STR = {
  // --- Избор на език / общи ---
  pick_lang: { bg:'Избери език', ru:'Выберите язык', uk:'Виберіть мову', en:'Choose language', de:'Sprache wählen', fr:'Choisir la langue', es:'Elegir idioma', 'es-MX':'Elegir idioma', it:'Scegli la lingua', pt:'Escolher idioma', ar:'اختر اللغة', hi:'भाषा चुनें', ja:'言語を選択', ky:'Тилди тандаңыз', 'zh-Hant':'選擇語言' },
  start_app: { bg:'Стартирай', ru:'Запустить', uk:'Запустити', en:'Start', de:'Starten', fr:'Démarrer', es:'Iniciar', 'es-MX':'Iniciar', it:'Avvia', pt:'Iniciar', ar:'ابدأ', hi:'शुरू करें', ja:'開始', ky:'Баштоо', 'zh-Hant':'開始' },
  language: { bg:'Език', ru:'Язык', uk:'Мова', en:'Language', de:'Sprache', fr:'Langue', es:'Idioma', 'es-MX':'Idioma', it:'Lingua', pt:'Idioma', ar:'اللغة', hi:'भाषा', ja:'言語', ky:'Тил', 'zh-Hant':'語言' },
  delete: { bg:'Изтрий', ru:'Удалить', uk:'Видалити', en:'Delete', de:'Löschen', fr:'Supprimer', es:'Eliminar', 'es-MX':'Eliminar', it:'Elimina', pt:'Excluir', ar:'حذف', hi:'हटाएं', ja:'削除', ky:'Өчүрүү', 'zh-Hant':'刪除' },

  // --- Заглавие на приложението ---
  app_name: { bg:'KCY Market Pulse', ru:'KCY Market Pulse', uk:'KCY Market Pulse', en:'KCY Market Pulse', de:'KCY Market Pulse', fr:'KCY Market Pulse', es:'KCY Market Pulse', 'es-MX':'KCY Market Pulse', it:'KCY Market Pulse', pt:'KCY Market Pulse', ar:'KCY Market Pulse', hi:'KCY Market Pulse', ja:'KCY Market Pulse', ky:'KCY Market Pulse', 'zh-Hant':'KCY Market Pulse' },

  // --- ЗАДЪЛЖИТЕЛЕН DISCLAIMER (крипто/финанси) — показва се СЛЕД езика, ПРЕДИ апа ---
  legal_title: { bg:'Важно преди да продължиш', ru:'Важно перед началом', uk:'Важливо перед початком', en:'Important before you continue', de:'Wichtig, bevor du fortfährst', fr:'Important avant de continuer', es:'Importante antes de continuar', 'es-MX':'Importante antes de continuar', it:'Importante prima di continuare', pt:'Importante antes de continuar', ar:'مهم قبل المتابعة', hi:'जारी रखने से पहले ज़रूरी', ja:'続ける前に重要なこと', ky:'Улантаардан мурун маанилүү', 'zh-Hant':'繼續前的重要說明' },
  legal_disclaimer: {
    bg:'KCY Market Pulse е ОБРАЗОВАТЕЛНО приложение. То показва изводи от публични финансови данни и индикатори (цена, импулс, RSI, пазарно настроение). ТОВА НЕ Е ИНВЕСТИЦИОНЕН СЪВЕТ и не бива да се използва като основа за финансови решения. Пазарите са рискови и могат да направят ТОЧНО ОБРАТНОТО на това, което който и да е индикатор подсказва. Ти носиш пълната отговорност за решенията си. Миналите резултати не гарантират бъдещи.',
    ru:'KCY Market Pulse — ОБРАЗОВАТЕЛЬНОЕ приложение. Оно показывает выводы из публичных финансовых данных и индикаторов (цена, импульс, RSI, настроение рынка). ЭТО НЕ ИНВЕСТИЦИОННЫЙ СОВЕТ и не должно служить основой для финансовых решений. Рынки рискованны и могут сделать ПРЯМО ПРОТИВОПОЛОЖНОЕ тому, что подсказывает любой индикатор. Вся ответственность за решения — на вас. Прошлые результаты не гарантируют будущих.',
    uk:'KCY Market Pulse — ОСВІТНІЙ застосунок. Він показує висновки з публічних фінансових даних та індикаторів (ціна, імпульс, RSI, настрій ринку). ЦЕ НЕ ІНВЕСТИЦІЙНА ПОРАДА і не має бути основою для фінансових рішень. Ринки ризиковані й можуть зробити ПРЯМО ПРОТИЛЕЖНЕ до того, що підказує будь-який індикатор. Уся відповідальність за рішення — на вас. Минулі результати не гарантують майбутніх.',
    en:'KCY Market Pulse is an EDUCATIONAL app. It shows conclusions derived from public financial data and indicators (price, momentum, RSI, market sentiment). THIS IS NOT INVESTMENT ADVICE and must not be used as the basis for any financial decision. Markets are risky and can do the EXACT OPPOSITE of what any indicator suggests. You are solely responsible for your decisions. Past performance does not guarantee future results.',
    de:'KCY Market Pulse ist eine BILDUNGS-App. Sie zeigt Schlussfolgerungen aus öffentlichen Finanzdaten und Indikatoren (Preis, Momentum, RSI, Marktstimmung). DIES IST KEINE ANLAGEBERATUNG und darf nicht als Grundlage für Finanzentscheidungen dienen. Märkte sind riskant und können GENAU DAS GEGENTEIL dessen tun, was ein Indikator nahelegt. Du bist allein für deine Entscheidungen verantwortlich. Vergangene Ergebnisse garantieren keine künftigen.',
    fr:'KCY Market Pulse est une application ÉDUCATIVE. Elle montre des conclusions tirées de données financières publiques et d’indicateurs (prix, momentum, RSI, sentiment du marché). CECI N’EST PAS UN CONSEIL EN INVESTISSEMENT et ne doit pas servir de base à une décision financière. Les marchés sont risqués et peuvent faire EXACTEMENT L’INVERSE de ce qu’un indicateur suggère. Tu es seul responsable de tes décisions. Les performances passées ne garantissent pas les résultats futurs.',
    es:'KCY Market Pulse es una app EDUCATIVA. Muestra conclusiones derivadas de datos financieros públicos e indicadores (precio, momentum, RSI, sentimiento del mercado). ESTO NO ES ASESORAMIENTO DE INVERSIÓN y no debe usarse como base para ninguna decisión financiera. Los mercados son arriesgados y pueden hacer EXACTAMENTE LO CONTRARIO de lo que sugiere cualquier indicador. Tú eres el único responsable de tus decisiones. Los resultados pasados no garantizan los futuros.',
    'es-MX':'KCY Market Pulse es una app EDUCATIVA. Muestra conclusiones derivadas de datos financieros públicos e indicadores (precio, momentum, RSI, sentimiento del mercado). ESTO NO ES ASESORÍA DE INVERSIÓN y no debe usarse como base para ninguna decisión financiera. Los mercados son riesgosos y pueden hacer EXACTAMENTE LO CONTRARIO de lo que sugiere cualquier indicador. Tú eres el único responsable de tus decisiones. El desempeño pasado no garantiza resultados futuros.',
    it:'KCY Market Pulse è un’app EDUCATIVA. Mostra conclusioni derivate da dati finanziari pubblici e indicatori (prezzo, momentum, RSI, sentiment del mercato). QUESTO NON È UN CONSIGLIO DI INVESTIMENTO e non deve essere usato come base per decisioni finanziarie. I mercati sono rischiosi e possono fare ESATTAMENTE L’OPPOSTO di ciò che un indicatore suggerisce. Sei l’unico responsabile delle tue decisioni. I risultati passati non garantiscono quelli futuri.',
    pt:'KCY Market Pulse é um app EDUCATIVO. Mostra conclusões derivadas de dados financeiros públicos e indicadores (preço, momentum, RSI, sentimento do mercado). ISTO NÃO É ACONSELHAMENTO DE INVESTIMENTO e não deve ser usado como base para qualquer decisão financeira. Os mercados são arriscados e podem fazer EXATAMENTE O CONTRÁRIO do que qualquer indicador sugere. Você é o único responsável pelas suas decisões. Resultados passados não garantem resultados futuros.',
    ar:'‏KCY Market Pulse تطبيق تعليمي. يعرض استنتاجات من بيانات مالية عامة ومؤشرات (السعر، الزخم، مؤشر القوة النسبية RSI، معنويات السوق). هذا ليس نصيحة استثمارية ولا يجوز اتخاذه أساسًا لأي قرار مالي. الأسواق محفوفة بالمخاطر وقد تفعل عكس ما يوحي به أي مؤشر تمامًا. أنت وحدك المسؤول عن قراراتك. الأداء السابق لا يضمن النتائج المستقبلية.',
    hi:'KCY Market Pulse एक शैक्षिक ऐप है। यह सार्वजनिक वित्तीय डेटा और संकेतकों (कीमत, गति, RSI, बाज़ार भावना) से निष्कर्ष दिखाता है। यह निवेश सलाह नहीं है और किसी भी वित्तीय निर्णय का आधार नहीं होना चाहिए। बाज़ार जोखिमपूर्ण हैं और किसी भी संकेतक के सुझाव के ठीक विपरीत कर सकते हैं। आपके निर्णयों के लिए केवल आप ज़िम्मेदार हैं। पिछला प्रदर्शन भविष्य की गारंटी नहीं देता।',
    ja:'KCY Market Pulse は教育用アプリです。公開された金融データと指標（価格、モメンタム、RSI、市場心理）から得た結論を表示します。これは投資助言ではなく、いかなる金融判断の根拠にもしてはいけません。市場はリスクがあり、どの指標が示す内容とも正反対に動くことがあります。判断の責任はすべてあなたにあります。過去の実績は将来を保証しません。',
    ky:'KCY Market Pulse — БИЛИМ БЕРҮҮЧҮ колдонмо. Ал ачык каржы маалыматтарынан жана индикаторлордон (баа, импульс, RSI, рынок маанайы) чыгарылган жыйынтыктарды көрсөтөт. БУЛ ИНВЕСТИЦИЯЛЫК КЕҢЕШ ЭМЕС жана каржы чечимдерине негиз болбошу керек. Рынок тобокелдүү жана каалаган индикатор сунуштагандын тескерисин так жасашы мүмкүн. Чечимдериңиз үчүн жооптуу өзүңүз. Өткөн натыйжалар келечекти кепилдебейт.',
    'zh-Hant':'KCY Market Pulse 是一款教育應用程式。它顯示由公開財務數據與指標（價格、動能、RSI、市場情緒）得出的結論。這不是投資建議，不得作為任何財務決策的依據。市場有風險，且可能與任何指標的暗示完全相反。你需為自己的決策負全部責任。過往表現不保證未來結果。'
  },
  legal_accept: { bg:'Разбирам и приемам', ru:'Я понимаю и принимаю', uk:'Я розумію та приймаю', en:'I understand and accept', de:'Ich verstehe und akzeptiere', fr:'Je comprends et j’accepte', es:'Entiendo y acepto', 'es-MX':'Entiendo y acepto', it:'Capisco e accetto', pt:'Entendo e aceito', ar:'أفهم وأوافق', hi:'मैं समझता/समझती हूँ और स्वीकार करता/करती हूँ', ja:'理解して同意します', ky:'Түшүнөм жана кабыл алам', 'zh-Hant':'我了解並接受' },
  legal_privacy: { bg:'Политика за поверителност', ru:'Политика конфиденциальности', uk:'Політика конфіденційності', en:'Privacy Policy', de:'Datenschutz', fr:'Confidentialité', es:'Privacidad', 'es-MX':'Privacidad', it:'Privacy', pt:'Privacidade', ar:'سياسة الخصوصية', hi:'गोपनीयता नीति', ja:'プライバシーポリシー', ky:'Купуялык саясаты', 'zh-Hant':'私隱政策' },
  legal_terms: { bg:'Общи условия', ru:'Условия использования', uk:'Умови використання', en:'Terms & Conditions', de:'Nutzungsbedingungen', fr:'Conditions générales', es:'Términos y condiciones', 'es-MX':'Términos y condiciones', it:'Termini e condizioni', pt:'Termos e condições', ar:'الشروط والأحكام', hi:'नियम एवं शर्तें', ja:'利用規約', ky:'Колдонуу шарттары', 'zh-Hant':'條款與細則' },

  // --- Табло за анализ ---
  an_title: { bg:'Пазарен пулс', ru:'Пульс рынка', uk:'Пульс ринку', en:'Market pulse', de:'Marktpuls', fr:'Pouls du marché', es:'Pulso del mercado', 'es-MX':'Pulso del mercado', it:'Battito del mercato', pt:'Pulso do mercado', ar:'نبض السوق', hi:'बाज़ार की नब्ज़', ja:'市場の脈動', ky:'Рыноктун пульсу', 'zh-Hant':'市場脈動' },
  an_sentiment: { bg:'Настроение (Fear & Greed)', ru:'Настроение (Fear & Greed)', uk:'Настрій (Fear & Greed)', en:'Sentiment (Fear & Greed)', de:'Stimmung (Fear & Greed)', fr:'Sentiment (Fear & Greed)', es:'Sentimiento (Fear & Greed)', 'es-MX':'Sentimiento (Fear & Greed)', it:'Sentiment (Fear & Greed)', pt:'Sentimento (Fear & Greed)', ar:'المعنويات (الخوف والطمع)', hi:'भावना (Fear & Greed)', ja:'市場心理（Fear & Greed）', ky:'Маанай (Fear & Greed)', 'zh-Hant':'情緒（Fear & Greed）' },
  an_refresh: { bg:'Обнови', ru:'Обновить', uk:'Оновити', en:'Refresh', de:'Aktualisieren', fr:'Actualiser', es:'Actualizar', 'es-MX':'Actualizar', it:'Aggiorna', pt:'Atualizar', ar:'تحديث', hi:'ताज़ा करें', ja:'更新', ky:'Жаңылоо', 'zh-Hant':'重新整理' },
  an_loading: { bg:'Зареждам реални данни…', ru:'Загружаю реальные данные…', uk:'Завантажую реальні дані…', en:'Loading live data…', de:'Lade Live-Daten…', fr:'Chargement des données en direct…', es:'Cargando datos en vivo…', 'es-MX':'Cargando datos en vivo…', it:'Carico dati in tempo reale…', pt:'Carregando dados ao vivo…', ar:'جارٍ تحميل البيانات الحية…', hi:'लाइव डेटा लोड हो रहा है…', ja:'ライブデータを読み込み中…', ky:'Түз маалымат жүктөлүүдө…', 'zh-Hant':'正在載入即時數據…' },
  an_error: { bg:'Няма връзка с данните. Опитай пак.', ru:'Нет связи с данными. Попробуйте снова.', uk:'Немає звʼязку з даними. Спробуйте ще раз.', en:'No data connection. Try again.', de:'Keine Datenverbindung. Erneut versuchen.', fr:'Pas de connexion aux données. Réessaie.', es:'Sin conexión de datos. Inténtalo de nuevo.', 'es-MX':'Sin conexión de datos. Inténtalo de nuevo.', it:'Nessuna connessione ai dati. Riprova.', pt:'Sem conexão de dados. Tente novamente.', ar:'لا يوجد اتصال بالبيانات. حاول مجددًا.', hi:'डेटा कनेक्शन नहीं। पुनः प्रयास करें।', ja:'データに接続できません。再試行してください。', ky:'Маалымат байланышы жок. Кайра аракет кыл.', 'zh-Hant':'無數據連線。請再試一次。' },
  an_cached: { bg:'📵 Офлайн данни (последно свалени)', ru:'📵 Офлайн-данные (последние загруженные)', uk:'📵 Офлайн-дані (останні завантажені)', en:'📵 Offline data (last downloaded)', de:'📵 Offline-Daten (zuletzt geladen)', fr:'📵 Données hors ligne (dernières)', es:'📵 Datos sin conexión (últimos)', 'es-MX':'📵 Datos sin conexión (últimos)', it:'📵 Dati offline (ultimi)', pt:'📵 Dados offline (últimos)', ar:'📵 بيانات دون اتصال (آخر تنزيل)', hi:'📵 ऑफ़लाइन डेटा (अंतिम)', ja:'📵 オフラインデータ（最終取得）', ky:'📵 Офлайн маалымат (акыркы)', 'zh-Hant':'📵 離線數據（最後下載）' },

  // --- Образователна „прогноза" по исторически аналог ---
  fc_title: { bg:'Образователен изглед за напред', ru:'Образовательный взгляд вперёд', uk:'Освітній погляд уперед', en:'Educational outlook', de:'Bildungs-Ausblick', fr:'Perspective éducative', es:'Perspectiva educativa', 'es-MX':'Perspectiva educativa', it:'Prospettiva educativa', pt:'Perspetiva educativa', ar:'نظرة تعليمية للمستقبل', hi:'शैक्षिक दृष्टिकोण', ja:'教育的な見通し', ky:'Билим берүүчү болжам', 'zh-Hant':'教育性展望' },
  fc_tomorrow: { bg:'Утре', ru:'Завтра', uk:'Завтра', en:'Tomorrow', de:'Morgen', fr:'Demain', es:'Mañana', 'es-MX':'Mañana', it:'Domani', pt:'Amanhã', ar:'غدًا', hi:'कल', ja:'明日', ky:'Эртең', 'zh-Hant':'明天' },
  fc_month: { bg:'Този месец', ru:'Этот месяц', uk:'Цей місяць', en:'This month', de:'Diesen Monat', fr:'Ce mois', es:'Este mes', 'es-MX':'Este mes', it:'Questo mese', pt:'Este mês', ar:'هذا الشهر', hi:'इस माह', ja:'今月', ky:'Бул ай', 'zh-Hant':'本月' },
  fc_year: { bg:'Тази/следваща година', ru:'Этот/следующий год', uk:'Цей/наступний рік', en:'This/next year', de:'Dieses/nächstes Jahr', fr:'Cette/l’an prochain', es:'Este/próximo año', 'es-MX':'Este/próximo año', it:'Quest’anno/prossimo', pt:'Este/próximo ano', ar:'هذا/العام القادم', hi:'इस/अगले वर्ष', ja:'今年／来年', ky:'Быйыл/келерки жыл', 'zh-Hant':'今年／明年' },
  fc_up: { bg:'↑ Клони нагоре', ru:'↑ Склоняется вверх', uk:'↑ Схиляється вгору', en:'↑ Leaning up', de:'↑ Tendenz aufwärts', fr:'↑ Tendance à la hausse', es:'↑ Inclinación al alza', 'es-MX':'↑ Inclinación al alza', it:'↑ Tende al rialzo', pt:'↑ Tende a subir', ar:'↑ يميل للصعود', hi:'↑ ऊपर की ओर', ja:'↑ 上向き傾向', ky:'↑ Жогору карай', 'zh-Hant':'↑ 偏向上漲' },
  fc_down: { bg:'↓ Клони надолу', ru:'↓ Склоняется вниз', uk:'↓ Схиляється вниз', en:'↓ Leaning down', de:'↓ Tendenz abwärts', fr:'↓ Tendance à la baisse', es:'↓ Inclinación a la baja', 'es-MX':'↓ Inclinación a la baja', it:'↓ Tende al ribasso', pt:'↓ Tende a descer', ar:'↓ يميل للهبوط', hi:'↓ नीचे की ओर', ja:'↓ 下向き傾向', ky:'↓ Төмөн карай', 'zh-Hant':'↓ 偏向下跌' },
  fc_uncertain: { bg:'≈ Неясно', ru:'≈ Неясно', uk:'≈ Неясно', en:'≈ Uncertain', de:'≈ Unklar', fr:'≈ Incertain', es:'≈ Incierto', 'es-MX':'≈ Incierto', it:'≈ Incerto', pt:'≈ Incerto', ar:'≈ غير مؤكد', hi:'≈ अनिश्चित', ja:'≈ 不確実', ky:'≈ Белгисиз', 'zh-Hant':'≈ 不明' },
  fc_basis: { bg:'подобни минали ситуации', ru:'похожих прошлых ситуаций', uk:'схожих минулих ситуацій', en:'similar past setups', de:'ähnliche frühere Situationen', fr:'situations passées similaires', es:'situaciones pasadas similares', 'es-MX':'situaciones pasadas similares', it:'situazioni passate simili', pt:'situações passadas semelhantes', ar:'حالات مشابهة سابقة', hi:'समान पिछली स्थितियाँ', ja:'類似の過去のパターン', ky:'окшош өткөн учурлар', 'zh-Hant':'類似的過去情況' },
  ev_period: { bg:'Ключови събития в периода', ru:'Ключевые события периода', uk:'Ключові події періоду', en:'Key events in this period', de:'Schlüsselereignisse im Zeitraum', fr:'Événements clés de la période', es:'Eventos clave del período', 'es-MX':'Eventos clave del período', it:'Eventi chiave del periodo', pt:'Eventos-chave do período', ar:'أحداث رئيسية في الفترة', hi:'इस अवधि की मुख्य घटनाएँ', ja:'この期間の主な出来事', ky:'Мезгилдин негизги окуялары', 'zh-Hant':'該期間關鍵事件' },
  ev_sent: { bg:'Настроение от последните събития', ru:'Настроение последних событий', uk:'Настрій останніх подій', en:'Sentiment from recent events', de:'Stimmung der letzten Ereignisse', fr:'Sentiment des événements récents', es:'Sentimiento de eventos recientes', 'es-MX':'Sentimiento de eventos recientes', it:'Sentiment degli eventi recenti', pt:'Sentimento dos eventos recentes', ar:'المعنويات من الأحداث الأخيرة', hi:'हाल की घटनाओं की भावना', ja:'最近の出来事からの心理', ky:'Акыркы окуялардын маанайы', 'zh-Hant':'近期事件情緒' },
  fc_disc: { bg:'Само образователно — историята НЕ гарантира бъдещето.', ru:'Только образовательно — история НЕ гарантирует будущее.', uk:'Лише освітньо — історія НЕ гарантує майбутнє.', en:'Educational only — history does NOT guarantee the future.', de:'Nur Bildung — die Vergangenheit garantiert NICHT die Zukunft.', fr:'À but éducatif — le passé ne garantit PAS l’avenir.', es:'Solo educativo — el pasado NO garantiza el futuro.', 'es-MX':'Solo educativo — el pasado NO garantiza el futuro.', it:'Solo educativo — il passato NON garantisce il futuro.', pt:'Apenas educativo — o passado NÃO garante o futuro.', ar:'للتعليم فقط — الماضي لا يضمن المستقبل.', hi:'केवल शैक्षिक — इतिहास भविष्य की गारंटी नहीं।', ja:'教育目的のみ — 過去は将来を保証しません。', ky:'Билим үчүн гана — тарых келечекти кепилдебейт.', 'zh-Hant':'僅供教育 — 歷史不保證未來。' },
  band_accumulate: { bg:'Зона на натрупване (образователно)', ru:'Зона накопления (образовательно)', uk:'Зона накопичення (освітньо)', en:'Accumulation zone (educational)', de:'Akkumulationszone (Bildung)', fr:'Zone d’accumulation (éducatif)', es:'Zona de acumulación (educativo)', 'es-MX':'Zona de acumulación (educativo)', it:'Zona di accumulo (educativo)', pt:'Zona de acumulação (educativo)', ar:'منطقة تجميع (تعليمي)', hi:'संचय क्षेत्र (शैक्षिक)', ja:'集積ゾーン（教育目的）', ky:'Топтоо зонасы (билим)', 'zh-Hant':'累積區（教育性）' },
  band_neutral: { bg:'Неутрално (образователно)', ru:'Нейтрально (образовательно)', uk:'Нейтрально (освітньо)', en:'Neutral (educational)', de:'Neutral (Bildung)', fr:'Neutre (éducatif)', es:'Neutral (educativo)', 'es-MX':'Neutral (educativo)', it:'Neutro (educativo)', pt:'Neutro (educativo)', ar:'محايد (تعليمي)', hi:'तटस्थ (शैक्षिक)', ja:'中立（教育目的）', ky:'Нейтралдуу (билим)', 'zh-Hant':'中性（教育性）' },
  band_distribute: { bg:'Зона на разпределяне (образователно)', ru:'Зона распределения (образовательно)', uk:'Зона розподілу (освітньо)', en:'Distribution zone (educational)', de:'Distributionszone (Bildung)', fr:'Zone de distribution (éducatif)', es:'Zona de distribución (educativo)', 'es-MX':'Zona de distribución (educativo)', it:'Zona di distribuzione (educativo)', pt:'Zona de distribuição (educativo)', ar:'منطقة توزيع (تعليمي)', hi:'वितरण क्षेत्र (शैक्षिक)', ja:'分配ゾーン（教育目的）', ky:'Бөлүштүрүү зонасы (билим)', 'zh-Hant':'派發區（教育性）' },
  why_lth: { bg:'🏦 Дългосрочните притежатели са на значителна загуба (цената е {0}% под средната за последната година) — исторически това е белег за ДЪНО на пазара.', ru:'🏦 Долгосрочные держатели в значительном убытке (цена на {0}% ниже средней за последний год) — исторически это признак ДНА рынка.', uk:'🏦 Довгострокові власники у значному збитку (ціна на {0}% нижча за середню за останній рік) — історично це ознака ДНА ринку.', en:'🏦 Long-term holders are at a significant loss (price is {0}% below the one-year average) — historically a sign of a market BOTTOM.', de:'🏦 Langfristige Halter sind deutlich im Minus (Preis {0}% unter dem Jahresdurchschnitt) — historisch ein Zeichen für den BODEN des Marktes.', fr:'🏦 Les détenteurs de long terme sont en perte significative (prix {0}% sous la moyenne annuelle) — historiquement un signe de PLANCHER du marché.', es:'🏦 Los holders de largo plazo están en pérdida significativa (precio {0}% bajo la media anual) — históricamente señal de SUELO del mercado.', 'es-MX':'🏦 Los holders de largo plazo están en pérdida significativa (precio {0}% bajo la media anual) — históricamente señal de SUELO del mercado.', it:'🏦 I detentori di lungo periodo sono in perdita significativa (prezzo {0}% sotto la media annuale) — storicamente un segnale di FONDO del mercato.', pt:'🏦 Os detentores de longo prazo estão em perda significativa (preço {0}% abaixo da média anual) — historicamente sinal de FUNDO do mercado.', ar:'🏦 حاملو المدى الطويل في خسارة كبيرة (السعر أدنى بنسبة {0}% من متوسط السنة) — تاريخيًا علامة على قاع السوق.', hi:'🏦 दीर्घकालिक धारक बड़े घाटे में हैं (कीमत वार्षिक औसत से {0}% नीचे) — ऐतिहासिक रूप से बाज़ार के तल का संकेत।', ja:'🏦 長期保有者が大きな含み損（価格が1年平均より{0}%低い）— 歴史的に市場の底のサインです。', ky:'🏦 Узак мөөнөттүү ээлер олуттуу чыгымда (баа жылдык орточодон {0}% төмөн) — тарыхта бул рыноктун ТҮБҮНҮН белгиси.', 'zh-Hant':'🏦 長期持有者處於顯著虧損（價格低於一年均價 {0}%）— 歷史上是市場見底的訊號。' },
  why_extreme_fear: { bg:'😱 Индексът на страха е в КРАЙНА зона ({0}) — исторически при най-голям страх следва покачване; точно тогава се купува.', ru:'😱 Индекс страха в КРАЙНЕЙ зоне ({0}) — исторически при максимальном страхе следует рост; именно тогда покупают.', uk:'😱 Індекс страху в КРАЙНІЙ зоні ({0}) — історично за найбільшим страхом іде зростання; саме тоді купують.', en:'😱 The Fear index is in the EXTREME zone ({0}) — historically maximum fear is followed by a rise; that is when buying happens.', de:'😱 Der Angstindex ist in der EXTREM-Zone ({0}) — historisch folgt auf maximale Angst ein Anstieg; genau dann wird gekauft.', fr:'😱 L’indice de peur est en zone EXTRÊME ({0}) — historiquement la peur maximale est suivie d’une hausse ; c’est alors qu’on achète.', es:'😱 El índice de miedo está en zona EXTREMA ({0}) — históricamente al miedo máximo le sigue una subida; ahí es cuando se compra.', 'es-MX':'😱 El índice de miedo está en zona EXTREMA ({0}) — históricamente al miedo máximo le sigue una subida; ahí es cuando se compra.', it:'😱 L’indice della paura è in zona ESTREMA ({0}) — storicamente alla paura massima segue un rialzo; è allora che si compra.', pt:'😱 O índice de medo está na zona EXTREMA ({0}) — historicamente ao medo máximo segue-se uma alta; é aí que se compra.', ar:'😱 مؤشر الخوف في المنطقة القصوى ({0}) — تاريخيًا يعقب الخوفَ الأقصى صعودٌ؛ وحينها يكون الشراء.', hi:'😱 डर सूचकांक चरम क्षेत्र में है ({0}) — ऐतिहासिक रूप से अधिकतम डर के बाद बढ़त आती है; तभी खरीदा जाता है।', ja:'😱 恐怖指数が極端な水準（{0}）— 歴史的に恐怖の極みの後は上昇が続きます。買いはその時です。', ky:'😱 Коркунуч индекси ЧЕКТИК аймакта ({0}) — тарыхта эң чоң коркунучтан кийин көтөрүлүү келет; так ошондо сатып алышат.', 'zh-Hant':'😱 恐懼指數處於極端區（{0}）— 歷史上最大恐懼之後往往是上漲；買入正是在此時。' },
  why_ma200: { bg:'📉 Цената е {0}% ПОД 200-дневната плъзгаща средна — вероятността да последва покачване се повишава (стига активът да не се срива към нулата).', ru:'📉 Цена на {0}% НИЖЕ 200-дневной скользящей средней — вероятность последующего роста повышается (если актив не рушится к нулю).', uk:'📉 Ціна на {0}% НИЖЧЕ 200-денної ковзної середньої — імовірність подальшого зростання підвищується (якщо актив не валиться до нуля).', en:'📉 The price is {0}% BELOW the 200-day moving average — the probability of a subsequent rise increases (as long as the asset is not collapsing to zero).', de:'📉 Der Preis liegt {0}% UNTER dem 200-Tage-Durchschnitt — die Wahrscheinlichkeit eines Anstiegs steigt (sofern der Wert nicht gegen null stürzt).', fr:'📉 Le prix est {0}% SOUS la moyenne mobile à 200 jours — la probabilité d’une hausse augmente (tant que l’actif ne s’effondre pas vers zéro).', es:'📉 El precio está {0}% POR DEBAJO de la media móvil de 200 días — la probabilidad de subida aumenta (mientras el activo no colapse a cero).', 'es-MX':'📉 El precio está {0}% POR DEBAJO de la media móvil de 200 días — la probabilidad de subida aumenta (mientras el activo no colapse a cero).', it:'📉 Il prezzo è {0}% SOTTO la media mobile a 200 giorni — la probabilità di un rialzo aumenta (purché l’asset non crolli verso zero).', pt:'📉 O preço está {0}% ABAIXO da média móvel de 200 dias — a probabilidade de alta aumenta (desde que o ativo não desabe a zero).', ar:'📉 السعر أدنى بنسبة {0}% من المتوسط المتحرك لـ200 يوم — احتمال الصعود يرتفع (ما لم يكن الأصل منهارًا نحو الصفر).', hi:'📉 कीमत 200-दिवसीय मूविंग एवरेज से {0}% नीचे है — आगे बढ़त की संभावना बढ़ जाती है (बशर्ते संपत्ति शून्य की ओर न गिर रही हो)।', ja:'📉 価格が200日移動平均を{0}%下回っています — その後の上昇確率が高まります（資産がゼロへ崩壊していない限り）。', ky:'📉 Баа 200 күндүк орточодон {0}% ТӨМӨН — көтөрүлүү ыктымалдыгы жогорулайт (актив нөлгө кулап бара жатпаса).', 'zh-Hant':'📉 價格低於 200 日移動平均線 {0}% — 隨後上漲的機率提高（前提是資產不是正在崩向歸零）。' },
  why_freefall: { bg:'⚠ Цената е чак {0}% под 200-дневната средна — това вече прилича на СВОБОДНО ПАДАНЕ (риск активът да се срива към нулата), НЕ е сигнал за купуване.', ru:'⚠ Цена аж на {0}% ниже 200-дневной средней — это уже похоже на СВОБОДНОЕ ПАДЕНИЕ (риск обвала к нулю), это НЕ сигнал к покупке.', uk:'⚠ Ціна аж на {0}% нижча за 200-денну середню — це вже схоже на ВІЛЬНЕ ПАДІННЯ (ризик обвалу до нуля), це НЕ сигнал до купівлі.', en:'⚠ The price is a full {0}% below the 200-day average — this looks like FREEFALL (risk of collapsing to zero); it is NOT a buy signal.', de:'⚠ Der Preis liegt ganze {0}% unter dem 200-Tage-Durchschnitt — das sieht nach FREIEM FALL aus (Risiko eines Absturzes auf null); KEIN Kaufsignal.', fr:'⚠ Le prix est {0}% sous la moyenne à 200 jours — cela ressemble à une CHUTE LIBRE (risque d’effondrement vers zéro) ; ce n’est PAS un signal d’achat.', es:'⚠ El precio está {0}% bajo la media de 200 días — parece CAÍDA LIBRE (riesgo de colapso a cero); NO es señal de compra.', 'es-MX':'⚠ El precio está {0}% bajo la media de 200 días — parece CAÍDA LIBRE (riesgo de colapso a cero); NO es señal de compra.', it:'⚠ Il prezzo è ben {0}% sotto la media a 200 giorni — sembra CADUTA LIBERA (rischio di crollo verso zero); NON è un segnale d’acquisto.', pt:'⚠ O preço está {0}% abaixo da média de 200 dias — parece QUEDA LIVRE (risco de colapso a zero); NÃO é sinal de compra.', ar:'⚠ السعر أدنى بنسبة {0}% من متوسط 200 يوم — يشبه السقوط الحر (خطر الانهيار نحو الصفر)؛ ليست إشارة شراء.', hi:'⚠ कीमत 200-दिवसीय औसत से पूरे {0}% नीचे है — यह मुक्त-पतन जैसा है (शून्य की ओर गिरने का जोखिम); यह खरीद संकेत नहीं है।', ja:'⚠ 価格が200日平均を{0}%も下回っています — これは自由落下の様相（ゼロへ崩壊するリスク）であり、買いシグナルではありません。', ky:'⚠ Баа 200 күндүк орточодон {0}%га төмөн — бул ЭРКИН КУЛОО сыяктуу (нөлгө кулоо коркунучу); бул сатып алуу белгиси ЭМЕС.', 'zh-Hant':'⚠ 價格低於 200 日均線達 {0}% — 這更像自由落體（歸零風險），不是買入訊號。' },
  why_sth: { bg:'⏱ Цената е {0}% под реализираната цена на КРАТКОСРОЧНИТЕ притежатели (те губят) — сигнал евентуално само за КРАТКА печалба (отскок), не за дългосрочно дъно.', ru:'⏱ Цена на {0}% ниже реализованной цены КРАТКОСРОЧНЫХ держателей (они в убытке) — сигнал возможно лишь о КОРОТКОЙ прибыли (отскоке), не о долгосрочном дне.', uk:'⏱ Ціна на {0}% нижча за реалізовану ціну КОРОТКОСТРОКОВИХ власників (вони втрачають) — сигнал можливо лише про КОРОТКИЙ прибуток (відскок), не про довгострокове дно.', en:'⏱ The price is {0}% below the SHORT-TERM holders’ realized price (they are losing) — a signal possibly for only a SHORT profit (a bounce), not a long-term bottom.', de:'⏱ Der Preis liegt {0}% unter dem realisierten Preis der KURZFRIST-Halter (sie verlieren) — ein Signal womöglich nur für einen KURZEN Gewinn (Erholung), kein langfristiger Boden.', fr:'⏱ Le prix est {0}% sous le prix réalisé des détenteurs COURT TERME (ils perdent) — signal éventuellement d’un profit COURT (rebond), pas d’un plancher durable.', es:'⏱ El precio está {0}% bajo el precio realizado de los holders de CORTO plazo (están perdiendo) — señal posiblemente de solo una ganancia CORTA (rebote), no de un suelo duradero.', 'es-MX':'⏱ El precio está {0}% bajo el precio realizado de los holders de CORTO plazo (están perdiendo) — señal posiblemente de solo una ganancia CORTA (rebote), no de un suelo duradero.', it:'⏱ Il prezzo è {0}% sotto il prezzo realizzato dei detentori a BREVE termine (stanno perdendo) — segnale forse solo di un profitto BREVE (rimbalzo), non di un fondo di lungo periodo.', pt:'⏱ O preço está {0}% abaixo do preço realizado dos detentores de CURTO prazo (eles perdem) — sinal possivelmente de apenas um lucro CURTO (repique), não de fundo duradouro.', ar:'⏱ السعر أدنى بنسبة {0}% من السعر المحقق لحاملي المدى القصير (إنهم يخسرون) — إشارة ربما لربح قصير فقط (ارتداد)، لا لقاعٍ طويل الأمد.', hi:'⏱ कीमत अल्पकालिक धारकों की वास्तविक कीमत से {0}% नीचे है (वे घाटे में हैं) — संकेत संभवतः केवल छोटी बढ़त (उछाल) का, दीर्घकालिक तल का नहीं।', ja:'⏱ 価格が短期保有者の実現価格を{0}%下回っています（彼らは損失中）— 短期の利益（反発）のみのシグナルであり、長期の底とは限りません。', ky:'⏱ Баа КЫСКА мөөнөттүү ээлердин ишке ашкан баасынан {0}%га төмөн (алар утулууда) — балким КЫСКА пайда (секирик) гана болушу мүмкүн, узак мөөнөттүү түп эмес.', 'zh-Hant':'⏱ 價格低於短期持有者的已實現價格 {0}%（他們在虧損）— 可能只是短暫獲利（反彈）的訊號，而非長期底部。' },
  why_vanish: { bg:'☠ ВНИМАНИЕ: активът е {0}% под историческия си връх и трендът още пада — има ВЕРОЯТНОСТ ДА ИЗЧЕЗНЕ. Златното правило „под цената на дългосрочните" НЕ важи, докато активът не покаже, че се запазва.', ru:'☠ ВНИМАНИЕ: актив на {0}% ниже исторического максимума и тренд всё ещё падает — есть ВЕРОЯТНОСТЬ ИСЧЕЗНОВЕНИЯ. Золотое правило «ниже цены долгосрочных» НЕ действует, пока актив не докажет, что сохраняется.', uk:'☠ УВАГА: актив на {0}% нижчий за історичний максимум і тренд усе ще падає — є ЙМОВІРНІСТЬ ЗНИКНЕННЯ. Золоте правило «нижче ціни довгострокових» НЕ діє, доки актив не доведе, що зберігається.', en:'☠ WARNING: the asset is {0}% below its all-time high and the trend is still falling — there is a PROBABILITY IT DISAPPEARS. The golden rule “below the long-term holders’ price” does NOT apply until the asset proves it survives.', de:'☠ WARNUNG: der Wert liegt {0}% unter seinem Allzeithoch und der Trend fällt weiter — es besteht die WAHRSCHEINLICHKEIT DES VERSCHWINDENS. Die goldene Regel gilt NICHT, bis der Wert beweist, dass er bestehen bleibt.', fr:'☠ ATTENTION : l’actif est {0}% sous son plus haut historique et la tendance baisse encore — il y a une PROBABILITÉ DE DISPARITION. La règle en or ne s’applique PAS tant que l’actif ne prouve pas sa survie.', es:'☠ ATENCIÓN: el activo está {0}% bajo su máximo histórico y la tendencia sigue cayendo — hay PROBABILIDAD DE DESAPARICIÓN. La regla de oro NO aplica hasta que el activo demuestre que sobrevive.', 'es-MX':'☠ ATENCIÓN: el activo está {0}% bajo su máximo histórico y la tendencia sigue cayendo — hay PROBABILIDAD DE DESAPARICIÓN. La regla de oro NO aplica hasta que el activo demuestre que sobrevive.', it:'☠ ATTENZIONE: l’asset è {0}% sotto il massimo storico e il trend scende ancora — c’è PROBABILITÀ DI SCOMPARSA. La regola d’oro NON vale finché l’asset non dimostra di sopravvivere.', pt:'☠ ATENÇÃO: o ativo está {0}% abaixo da máxima histórica e a tendência ainda cai — há PROBABILIDADE DE DESAPARECER. A regra de ouro NÃO vale até o ativo provar que sobrevive.', ar:'☠ تحذير: الأصل أدنى بنسبة {0}% من قمته التاريخية والاتجاه ما زال هابطًا — هناك احتمال أن يختفي. القاعدة الذهبية لا تنطبق حتى يثبت الأصل بقاءه.', hi:'☠ चेतावनी: संपत्ति अपने सर्वकालिक शिखर से {0}% नीचे है और रुझान अभी भी गिर रहा है — इसके लुप्त होने की संभावना है। स्वर्णिम नियम तब तक लागू नहीं जब तक संपत्ति टिकना सिद्ध न करे।', ja:'☠ 警告：資産は史上最高値から{0}%下落し、トレンドはまだ下向きです — 消滅する可能性があります。資産の存続が確認されるまで、黄金ルールは適用されません。', ky:'☠ ЭСКЕРТҮҮ: актив тарыхый чокусунан {0}%га төмөн жана тренд дагы эле түшүүдө — ЖОГОЛУП КЕТҮҮ ыктымалдыгы бар. Алтын эреже актив сакталарын далилдегенге чейин колдонулбайт.', 'zh-Hant':'☠ 警告：資產低於歷史最高點 {0}% 且趨勢仍在下跌 — 存在歸零消失的可能。在資產證明能存續之前，黃金法則不適用。' },
  why_breakout: { bg:'🚀 Цената ПРОБИВА НАД реализираната цена на краткосрочните притежатели (+{0}%), след като доскоро беше под нея — исторически това бележи КРАЯ на мечия пазар / на падането.', ru:'🚀 Цена ПРОБИВАЕТ ВВЕРХ реализованную цену краткосрочных держателей (+{0}%), недавно быв ниже неё — исторически это отмечает КОНЕЦ медвежьего рынка / падения.', uk:'🚀 Ціна ПРОБИВАЄ ВГОРУ реалізовану ціну короткострокових власників (+{0}%), нещодавно бувши нижче неї — історично це позначає КІНЕЦЬ ведмежого ринку / падіння.', en:'🚀 The price is BREAKING ABOVE the short-term holders’ realized price (+{0}%) after recently being below it — historically this marks the END of the bear market / the decline.', de:'🚀 Der Preis BRICHT über den realisierten Preis der Kurzfrist-Halter (+{0}%), nachdem er kürzlich darunter lag — historisch markiert das das ENDE des Bärenmarktes / des Rückgangs.', fr:'🚀 Le prix FRANCHIT À LA HAUSSE le prix réalisé des détenteurs court terme (+{0}%) après avoir été dessous récemment — historiquement cela marque la FIN du marché baissier / de la baisse.', es:'🚀 El precio ROMPE POR ENCIMA del precio realizado de los holders de corto plazo (+{0}%) tras estar hace poco por debajo — históricamente marca el FIN del mercado bajista / de la caída.', 'es-MX':'🚀 El precio ROMPE POR ENCIMA del precio realizado de los holders de corto plazo (+{0}%) tras estar hace poco por debajo — históricamente marca el FIN del mercado bajista / de la caída.', it:'🚀 Il prezzo sta ROMPENDO SOPRA il prezzo realizzato dei detentori a breve termine (+{0}%) dopo esserne stato sotto di recente — storicamente segna la FINE del mercato ribassista / del calo.', pt:'🚀 O preço ROMPE ACIMA do preço realizado dos detentores de curto prazo (+{0}%) depois de há pouco estar abaixo — historicamente marca o FIM do mercado de baixa / da queda.', ar:'🚀 السعر يخترق صعودًا السعر المحقق لحاملي المدى القصير (+{0}%) بعد أن كان دونه مؤخرًا — تاريخيًا يعلن نهاية السوق الهابطة / الهبوط.', hi:'🚀 कीमत अल्पकालिक धारकों की वास्तविक कीमत के ऊपर टूट रही है (+{0}%), जबकि हाल तक उसके नीचे थी — ऐतिहासिक रूप से यह मंदी बाज़ार / गिरावट का अंत दर्शाता है।', ja:'🚀 価格が短期保有者の実現価格を上抜けています（+{0}%）。直近まで下にあった後の上抜けは、歴史的に弱気相場／下落の終わりを示します。', ky:'🚀 Баа кыска мөөнөттүү ээлердин ишке ашкан баасынан ЖОГОРУ жарып өтүүдө (+{0}%), жакында эле андан төмөн болгон — тарыхта бул аюу рыногунун / түшүүнүн АЯГЫН белгилейт.', 'zh-Hant':'🚀 價格正向上突破短期持有者的已實現價格（+{0}%），而不久前仍在其下 — 歷史上這標誌著熊市／下跌的結束。' },
  pt_title: { bg:'Таблица на вероятностите', ru:'Таблица вероятностей', uk:'Таблиця ймовірностей', en:'Probability table', de:'Wahrscheinlichkeitstabelle', fr:'Tableau des probabilités', es:'Tabla de probabilidades', 'es-MX':'Tabla de probabilidades', it:'Tabella delle probabilità', pt:'Tabela de probabilidades', ar:'جدول الاحتمالات', hi:'संभावना तालिका', ja:'確率テーブル', ky:'Ыктымалдык таблицасы', 'zh-Hant':'機率表' },
  pt_src_tech: { bg:'Технически анализ + реализирани цени', ru:'Теханализ + реализованные цены', uk:'Техааналіз + реалізовані ціни', en:'Technical analysis + realized prices', de:'Technische Analyse + realisierte Preise', fr:'Analyse technique + prix réalisés', es:'Análisis técnico + precios realizados', 'es-MX':'Análisis técnico + precios realizados', it:'Analisi tecnica + prezzi realizzati', pt:'Análise técnica + preços realizados', ar:'التحليل الفني + الأسعار المحققة', hi:'तकनीकी विश्लेषण + वास्तविक कीमतें', ja:'テクニカル分析＋実現価格', ky:'Техникалык талдоо + ишке ашкан баалар', 'zh-Hant':'技術分析＋已實現價格' },
  pt_src_sent: { bg:'Настроение (страхът = купуване)', ru:'Настроение (страх = покупка)', uk:'Настрій (страх = купівля)', en:'Sentiment (fear = buying)', de:'Stimmung (Angst = Kaufen)', fr:'Sentiment (peur = achat)', es:'Sentimiento (miedo = compra)', 'es-MX':'Sentimiento (miedo = compra)', it:'Sentiment (paura = acquisto)', pt:'Sentimento (medo = compra)', ar:'المزاج (الخوف = شراء)', hi:'भावना (डर = खरीद)', ja:'センチメント（恐怖＝買い）', ky:'Маанай (коркунуч = сатып алуу)', 'zh-Hant':'情緒（恐懼＝買入）' },
  pt_src_pred: { bg:'Прогнози на анализаторите', ru:'Прогнозы аналитиков', uk:'Прогнози аналітиків', en:'Analysts’ predictions', de:'Analysten-Prognosen', fr:'Prédictions des analystes', es:'Predicciones de analistas', 'es-MX':'Predicciones de analistas', it:'Previsioni degli analisti', pt:'Previsões dos analistas', ar:'توقعات المحللين', hi:'विश्लेषकों की भविष्यवाणियां', ja:'アナリスト予想', ky:'Аналитиктердин божомолдору', 'zh-Hant':'分析師預測' },
  pt_src_news: { bg:'Новините (тон на заглавията)', ru:'Новости (тон заголовков)', uk:'Новини (тон заголовків)', en:'News (headline tone)', de:'Nachrichten (Ton der Schlagzeilen)', fr:'Actualités (ton des titres)', es:'Noticias (tono de titulares)', 'es-MX':'Noticias (tono de titulares)', it:'Notizie (tono dei titoli)', pt:'Notícias (tom das manchetes)', ar:'الأخبار (نبرة العناوين)', hi:'समाचार (सुर्खियों का स्वर)', ja:'ニュース（見出しのトーン）', ky:'Жаңылыктар (аталыштардын мааниси)', 'zh-Hant':'新聞（標題語氣）' },
  pt_src_geo: { bg:'Глобални рискове (войни/бедствия)', ru:'Глобальные риски (войны/бедствия)', uk:'Глобальні ризики (війни/лиха)', en:'Global risks (wars/disasters)', de:'Globale Risiken (Kriege/Katastrophen)', fr:'Risques mondiaux (guerres/catastrophes)', es:'Riesgos globales (guerras/desastres)', 'es-MX':'Riesgos globales (guerras/desastres)', it:'Rischi globali (guerre/disastri)', pt:'Riscos globais (guerras/desastres)', ar:'مخاطر عالمية (حروب/كوارث)', hi:'वैश्विक जोखिम (युद्ध/आपदाएं)', ja:'グローバルリスク（戦争・災害）', ky:'Глобалдык тобокелдиктер (согуштар/кырсыктар)', 'zh-Hant':'全球風險（戰爭／災難）' },
  pt_src_inf: { bg:'Изказвания на влиятелни личности', ru:'Заявления влиятельных лиц', uk:'Заяви впливових осіб', en:'Statements by influential figures', de:'Aussagen einflussreicher Personen', fr:'Déclarations de personnalités influentes', es:'Declaraciones de figuras influyentes', 'es-MX':'Declaraciones de figuras influyentes', it:'Dichiarazioni di figure influenti', pt:'Declarações de figuras influentes', ar:'تصريحات شخصيات مؤثرة', hi:'प्रभावशाली हस्तियों के बयान', ja:'影響力ある人物の発言', ky:'Таасирдүү адамдардын билдирүүлөрү', 'zh-Hant':'有影響力人物的言論' },
  pt_src_comp: { bg:'Конкурентни активи (изяжда ли се пазарът)', ru:'Конкурирующие активы (съедается ли рынок)', uk:'Конкурентні активи (чи з’їдається ринок)', en:'Competing assets (is the market being eaten)', de:'Konkurrierende Werte (wird der Markt aufgefressen)', fr:'Actifs concurrents (le marché est-il mangé)', es:'Activos competidores (¿se comen el mercado?)', 'es-MX':'Activos competidores (¿se comen el mercado?)', it:'Asset concorrenti (il mercato viene mangiato?)', pt:'Ativos concorrentes (o mercado está sendo comido?)', ar:'أصول منافسة (هل يُلتهم السوق؟)', hi:'प्रतिस्पर्धी संपत्तियां (क्या बाज़ार खाया जा रहा है)', ja:'競合資産（市場が奪われていないか）', ky:'Атаандаш активдер (рынок жеп жатабы)', 'zh-Hant':'競爭資產（市場是否被蠶食）' },
  pt_src_liq: { bg:'Ликвидност (heatmap) — няма безплатен източник; виж „Финансови графики" (CoinGlass)', ru:'Ликвидность (heatmap) — нет бесплатного источника; см. «Финансовые графики» (CoinGlass)', uk:'Ліквідність (heatmap) — немає безкоштовного джерела; див. «Фінансові графіки» (CoinGlass)', en:'Liquidity (heatmap) — no free source; see “Finance charts” (CoinGlass)', de:'Liquidität (Heatmap) — keine kostenlose Quelle; siehe „Finanzcharts" (CoinGlass)', fr:'Liquidité (heatmap) — pas de source gratuite ; voir « Graphiques financiers » (CoinGlass)', es:'Liquidez (heatmap) — sin fuente gratuita; ver «Gráficos financieros» (CoinGlass)', 'es-MX':'Liquidez (heatmap) — sin fuente gratuita; ver «Gráficos financieros» (CoinGlass)', it:'Liquidità (heatmap) — nessuna fonte gratuita; vedi «Grafici finanziari» (CoinGlass)', pt:'Liquidez (heatmap) — sem fonte gratuita; ver “Gráficos financeiros” (CoinGlass)', ar:'السيولة (heatmap) — لا مصدر مجاني؛ انظر «الرسوم المالية» (CoinGlass)', hi:'तरलता (heatmap) — कोई मुफ़्त स्रोत नहीं; „वित्तीय चार्ट" (CoinGlass) देखें', ja:'流動性（ヒートマップ）— 無料ソースなし。「金融チャート」(CoinGlass) を参照', ky:'Ликвиддүүлүк (heatmap) — акысыз булак жок; «Каржы графиктери» (CoinGlass) кара', 'zh-Hant':'流動性（熱圖）— 無免費來源；請見「金融圖表」(CoinGlass)' },
  pt_prob: { bg:'Вероятност за покачване', ru:'Вероятность роста', uk:'Імовірність зростання', en:'Probability of a rise', de:'Wahrscheinlichkeit eines Anstiegs', fr:'Probabilité de hausse', es:'Probabilidad de subida', 'es-MX':'Probabilidad de subida', it:'Probabilità di rialzo', pt:'Probabilidade de alta', ar:'احتمال الصعود', hi:'बढ़त की संभावना', ja:'上昇確率', ky:'Көтөрүлүү ыктымалдыгы', 'zh-Hant':'上漲機率' },
  pt_yes: { bg:'ДА', ru:'ДА', uk:'ТАК', en:'YES', de:'JA', fr:'OUI', es:'SÍ', 'es-MX':'SÍ', it:'SÌ', pt:'SIM', ar:'نعم', hi:'हां', ja:'はい', ky:'ООБА', 'zh-Hant':'是' },
  pt_no: { bg:'НЕ', ru:'НЕТ', uk:'НІ', en:'NO', de:'NEIN', fr:'NON', es:'NO', 'es-MX':'NO', it:'NO', pt:'NÃO', ar:'لا', hi:'नहीं', ja:'いいえ', ky:'ЖОК', 'zh-Hant':'否' },
  pt_unsure: { bg:'НЕСИГУРНО', ru:'НЕОПРЕДЕЛЁННО', uk:'НЕВИЗНАЧЕНО', en:'UNCERTAIN', de:'UNSICHER', fr:'INCERTAIN', es:'INCIERTO', 'es-MX':'INCIERTO', it:'INCERTO', pt:'INCERTO', ar:'غير مؤكد', hi:'अनिश्चित', ja:'不確実', ky:'БЕЛГИСИЗ', 'zh-Hant':'不確定' },
  pt_note: { bg:'Претеглена сводка на всички източници по-горе. САМО за обучение — НЕ Е инвестиционен съвет.', ru:'Взвешенная сводка всех источников выше. ТОЛЬКО для обучения — НЕ инвестиционный совет.', uk:'Зважене зведення всіх джерел вище. ЛИШЕ для навчання — НЕ інвестиційна порада.', en:'A weighted summary of all sources above. EDUCATIONAL ONLY — NOT investment advice.', de:'Gewichtete Zusammenfassung aller Quellen oben. NUR zu Bildungszwecken — KEINE Anlageberatung.', fr:'Synthèse pondérée de toutes les sources ci-dessus. ÉDUCATIF UNIQUEMENT — PAS un conseil en investissement.', es:'Resumen ponderado de todas las fuentes anteriores. SOLO educativo — NO es asesoramiento de inversión.', 'es-MX':'Resumen ponderado de todas las fuentes anteriores. SOLO educativo — NO es asesoría de inversión.', it:'Sintesi ponderata di tutte le fonti sopra. SOLO educativo — NON è un consiglio di investimento.', pt:'Resumo ponderado de todas as fontes acima. APENAS educativo — NÃO é aconselhamento de investimento.', ar:'ملخص مُرجّح لكل المصادر أعلاه. تعليمي فقط — ليس نصيحة استثمارية.', hi:'ऊपर के सभी स्रोतों का भारित सारांश। केवल शैक्षिक — निवेश सलाह नहीं।', ja:'上記すべてのソースの加重サマリー。教育目的のみ — 投資助言ではありません。', ky:'Жогорудагы бардык булактардын салмактанган корутундусу. БИЛИМ ҮЧҮН ГАНА — инвестициялык кеңеш эмес.', 'zh-Hant':'以上所有來源的加權總結。僅供教育 — 非投資建議。' },
  pred_title: { bg:'Кой какво предсказва (събрано от публични анализи)', ru:'Кто что предсказывает (собрано из публичных анализов)', uk:'Хто що передбачає (зібрано з публічних аналізів)', en:'Who predicts what (collected from public analyses)', de:'Wer was vorhersagt (aus öffentlichen Analysen gesammelt)', fr:'Qui prédit quoi (collecté d’analyses publiques)', es:'Quién predice qué (recopilado de análisis públicos)', 'es-MX':'Quién predice qué (recopilado de análisis públicos)', it:'Chi prevede cosa (raccolto da analisi pubbliche)', pt:'Quem prevê o quê (coletado de análises públicas)', ar:'من يتوقع ماذا (مجموع من تحليلات عامة)', hi:'कौन क्या भविष्यवाणी करता है (सार्वजनिक विश्लेषणों से संकलित)', ja:'誰が何を予測しているか（公開分析から収集）', ky:'Ким эмнени божомолдойт (ачык талдоолордон чогултулган)', 'zh-Hant':'誰預測了什麼（自公開分析收集）' },
  pred_up: { bg:'ще се вдигне до', ru:'поднимется до', uk:'підніметься до', en:'will rise to', de:'wird steigen auf', fr:'montera à', es:'subirá a', 'es-MX':'subirá a', it:'salirà a', pt:'subirá para', ar:'سيرتفع إلى', hi:'तक बढ़ेगा', ja:'まで上昇する', ky:'чейин көтөрүлөт', 'zh-Hant':'將升至' },
  pred_down: { bg:'ще падне до', ru:'упадёт до', uk:'впаде до', en:'will fall to', de:'wird fallen auf', fr:'tombera à', es:'caerá a', 'es-MX':'caerá a', it:'scenderà a', pt:'cairá para', ar:'سيهبط إلى', hi:'तक गिरेगा', ja:'まで下落する', ky:'чейин түшөт', 'zh-Hant':'將跌至' },
  pred_target: { bg:'цел', ru:'цель', uk:'ціль', en:'target', de:'Ziel', fr:'cible', es:'objetivo', 'es-MX':'objetivo', it:'obiettivo', pt:'alvo', ar:'هدف', hi:'लक्ष्य', ja:'目標', ky:'максат', 'zh-Hant':'目標' },
  pred_note: { bg:'Събрано автоматично от субтитрите на публични видео анализи, с автор и линк. Чужди мнения — НЕ са съвет.', ru:'Собрано автоматически из субтитров публичных видеоанализов, с автором и ссылкой. Чужие мнения — НЕ совет.', uk:'Зібрано автоматично із субтитрів публічних відеоаналізів, з автором і посиланням. Чужі думки — НЕ порада.', en:'Collected automatically from the subtitles of public video analyses, with author and link. Other people’s opinions — NOT advice.', de:'Automatisch aus den Untertiteln öffentlicher Videoanalysen gesammelt, mit Autor und Link. Fremde Meinungen — KEIN Rat.', fr:'Collecté automatiquement depuis les sous-titres d’analyses vidéo publiques, avec auteur et lien. Des opinions d’autrui — PAS un conseil.', es:'Recopilado automáticamente de los subtítulos de análisis en video públicos, con autor y enlace. Opiniones ajenas — NO es consejo.', 'es-MX':'Recopilado automáticamente de los subtítulos de análisis en video públicos, con autor y enlace. Opiniones ajenas — NO es consejo.', it:'Raccolto automaticamente dai sottotitoli di analisi video pubbliche, con autore e link. Opinioni altrui — NON è un consiglio.', pt:'Coletado automaticamente das legendas de análises em vídeo públicas, com autor e link. Opiniões alheias — NÃO é conselho.', ar:'جُمع تلقائيًا من ترجمات تحليلات فيديو عامة، مع المؤلف والرابط. آراء الآخرين — ليست نصيحة.', hi:'सार्वजनिक वीडियो विश्लेषणों के उपशीर्षकों से स्वतः संकलित, लेखक और लिंक सहित। दूसरों की राय — सलाह नहीं।', ja:'公開動画分析の字幕から自動収集（著者・リンク付き）。他者の意見であり、助言ではありません。', ky:'Ачык видео талдоолордун субтитрлеринен автоматтык чогултулган (автору жана шилтемеси менен). Бирөөнүн пикири — кеңеш ЭМЕС.', 'zh-Hant':'自公開影片分析的字幕自動收集，附作者與連結。他人觀點 — 非建議。' },
  why_golden: { bg:'ЗЛАТНА ВЪЗМОЖНОСТ: цената е {0}% ПОД реализираната цена на ДЪЛГОСРОЧНИТЕ притежатели — най-добрият момент за покупка, В СЛУЧАЙ че активът се запази (вероятността за изчезване е проверена и е ниска).', ru:'ЗОЛОТАЯ ВОЗМОЖНОСТЬ: цена на {0}% НИЖЕ реализованной цены ДОЛГОСРОЧНЫХ держателей — лучший момент для покупки, ЕСЛИ актив сохранится (вероятность исчезновения проверена и низка).', uk:'ЗОЛОТА МОЖЛИВІСТЬ: ціна на {0}% НИЖЧА за реалізовану ціну ДОВГОСТРОКОВИХ власників — найкращий момент для купівлі, ЯКЩО актив збережеться (імовірність зникнення перевірена і низька).', en:'GOLDEN OPPORTUNITY: the price is {0}% BELOW the LONG-TERM holders’ realized price — the best moment to buy, PROVIDED the asset survives (the probability of it disappearing was checked and is low).', de:'GOLDENE GELEGENHEIT: der Preis liegt {0}% UNTER dem realisierten Preis der LANGFRIST-Halter — der beste Kaufmoment, SOFERN der Wert bestehen bleibt (die Verschwinde-Wahrscheinlichkeit wurde geprüft und ist niedrig).', fr:'OPPORTUNITÉ EN OR : le prix est {0}% SOUS le prix réalisé des détenteurs LONG TERME — le meilleur moment d’achat, À CONDITION que l’actif survive (la probabilité de disparition a été vérifiée et est faible).', es:'OPORTUNIDAD DE ORO: el precio está {0}% POR DEBAJO del precio realizado de los holders de LARGO plazo — el mejor momento de compra, SIEMPRE QUE el activo sobreviva (la probabilidad de desaparición fue revisada y es baja).', 'es-MX':'OPORTUNIDAD DE ORO: el precio está {0}% POR DEBAJO del precio realizado de los holders de LARGO plazo — el mejor momento de compra, SIEMPRE QUE el activo sobreviva (la probabilidad de desaparición fue revisada y es baja).', it:'OPPORTUNITÀ D’ORO: il prezzo è {0}% SOTTO il prezzo realizzato dei detentori di LUNGO periodo — il momento migliore per comprare, PURCHÉ l’asset sopravviva (la probabilità di scomparsa è stata verificata ed è bassa).', pt:'OPORTUNIDADE DE OURO: o preço está {0}% ABAIXO do preço realizado dos detentores de LONGO prazo — o melhor momento de compra, DESDE QUE o ativo sobreviva (a probabilidade de desaparecer foi checada e é baixa).', ar:'فرصة ذهبية: السعر أدنى بنسبة {0}% من السعر المحقق لحاملي المدى الطويل — أفضل لحظة للشراء، شرط بقاء الأصل (تم فحص احتمال اختفائه وهو منخفض).', hi:'सुनहरा अवसर: कीमत दीर्घकालिक धारकों की वास्तविक कीमत से {0}% नीचे है — खरीदने का सर्वोत्तम क्षण, बशर्ते संपत्ति बनी रहे (लुप्त होने की संभावना जांची गई है और कम है)।', ja:'ゴールデンチャンス：価格が長期保有者の実現価格を{0}%下回っています — 資産が存続する限り最良の買い場です（消滅の可能性は確認済みで低い）。', ky:'АЛТЫН МҮМКҮНЧҮЛҮК: баа УЗАК мөөнөттүү ээлердин ишке ашкан баасынан {0}%га төмөн — эң мыкты сатып алуу учуру, ЭГЕР актив сакталса (жоголуу ыктымалдыгы текшерилди жана төмөн).', 'zh-Hant':'黃金機會：價格低於長期持有者的已實現價格 {0}% — 最佳買入時機，前提是資產能存續（消失的可能性已檢查且偏低）。' },
  why_below_realized: { bg:'💰 Цената е {0}% ПОД реализираната цена на дългосрочните притежатели (средната им себестойност за последната година) — момент за купуване с цел печалба.', ru:'💰 Цена на {0}% НИЖЕ реализованной цены долгосрочных держателей (их средней себестоимости за последний год) — момент для покупки с целью прибыли.', uk:'💰 Ціна на {0}% НИЖЧА за реалізовану ціну довгострокових власників (їхню середню собівартість за останній рік) — момент для купівлі з метою прибутку.', en:'💰 The price is {0}% BELOW the long-term holders’ realized price (their one-year average cost basis) — a moment to buy for profit.', de:'💰 Der Preis liegt {0}% UNTER dem realisierten Preis der Langfrist-Halter (ihre durchschnittliche Jahres-Kostenbasis) — ein Moment, um mit Gewinnabsicht zu kaufen.', fr:'💰 Le prix est {0}% SOUS le prix réalisé des détenteurs de long terme (leur coût moyen sur un an) — un moment pour acheter en visant un profit.', es:'💰 El precio está {0}% POR DEBAJO del precio realizado de los holders de largo plazo (su costo medio anual) — momento de comprar buscando ganancia.', 'es-MX':'💰 El precio está {0}% POR DEBAJO del precio realizado de los holders de largo plazo (su costo medio anual) — momento de comprar buscando ganancia.', it:'💰 Il prezzo è {0}% SOTTO il prezzo realizzato dei detentori di lungo periodo (il loro costo medio annuale) — un momento per comprare puntando al profitto.', pt:'💰 O preço está {0}% ABAIXO do preço realizado dos detentores de longo prazo (seu custo médio anual) — momento de comprar visando lucro.', ar:'💰 السعر أدنى بنسبة {0}% من السعر المحقق لحاملي المدى الطويل (متوسط تكلفتهم السنوية) — لحظة شراء بهدف الربح.', hi:'💰 कीमत दीर्घकालिक धारकों की वास्तविक कीमत (उनकी वार्षिक औसत लागत) से {0}% नीचे है — लाभ हेतु खरीदने का क्षण।', ja:'💰 価格が長期保有者の実現価格（1年平均コスト）を{0}%下回っています — 利益を狙って買う局面です。', ky:'💰 Баа узак мөөнөттүү ээлердин ишке ашкан баасынан ({0}%га, жылдык орточо наркынан) төмөн — пайда үчүн сатып алуу учуру.', 'zh-Hant':'💰 價格低於長期持有者的已實現價格（其一年平均成本）{0}% — 是以獲利為目標的買入時機。' },
  why_lth_profit: { bg:'🔔 БИЧИ пазар: цената е {0}% НАД реализираната цена на дългосрочните притежатели и се покачи много бързо — те реализират търсената цена; исторически това е зона за ПРОДАВАНЕ.', ru:'🔔 БЫЧИЙ рынок: цена на {0}% ВЫШЕ реализованной цены долгосрочных держателей и выросла очень быстро — они реализуют желаемую цену; исторически это зона для ПРОДАЖИ.', uk:'🔔 БИЧАЧИЙ ринок: ціна на {0}% ВИЩА за реалізовану ціну довгострокових власників і зросла дуже швидко — вони реалізують бажану ціну; історично це зона для ПРОДАЖУ.', en:'🔔 BULL market: the price is {0}% ABOVE the long-term holders’ realized price and rose very fast — they are realizing their target price; historically a zone to SELL.', de:'🔔 BULLEN-Markt: der Preis liegt {0}% ÜBER dem realisierten Preis der Langfrist-Halter und stieg sehr schnell — sie realisieren ihren Zielpreis; historisch eine VERKAUFS-Zone.', fr:'🔔 Marché HAUSSIER : le prix est {0}% AU-DESSUS du prix réalisé des détenteurs de long terme et a monté très vite — ils réalisent leur prix visé ; historiquement une zone de VENTE.', es:'🔔 Mercado ALCISTA: el precio está {0}% POR ENCIMA del precio realizado de los holders de largo plazo y subió muy rápido — están realizando su precio objetivo; históricamente zona de VENTA.', 'es-MX':'🔔 Mercado ALCISTA: el precio está {0}% POR ENCIMA del precio realizado de los holders de largo plazo y subió muy rápido — están realizando su precio objetivo; históricamente zona de VENTA.', it:'🔔 Mercato RIALZISTA: il prezzo è {0}% SOPRA il prezzo realizzato dei detentori di lungo periodo ed è salito molto in fretta — stanno realizzando il prezzo desiderato; storicamente una zona di VENDITA.', pt:'🔔 Mercado de ALTA: o preço está {0}% ACIMA do preço realizado dos detentores de longo prazo e subiu muito rápido — eles realizam o preço desejado; historicamente zona de VENDA.', ar:'🔔 سوق صاعدة: السعر أعلى بنسبة {0}% من السعر المحقق لحاملي المدى الطويل وارتفع بسرعة كبيرة — إنهم يحققون سعرهم المستهدف؛ تاريخيًا منطقة بيع.', hi:'🔔 तेज़ी का बाज़ार: कीमत दीर्घकालिक धारकों की वास्तविक कीमत से {0}% ऊपर है और बहुत तेज़ी से बढ़ी — वे अपनी लक्षित कीमत साकार कर रहे हैं; ऐतिहासिक रूप से बेचने का क्षेत्र।', ja:'🔔 強気相場：価格が長期保有者の実現価格を{0}%上回り、非常に速く上昇 — 彼らは目標価格を実現しつつあります。歴史的に売りゾーンです。', ky:'🔔 ӨСҮҮЧҮ рынок: баа узак мөөнөттүү ээлердин ишке ашкан баасынан {0}%га жогору жана өтө тез көтөрүлдү — алар каалаган баасын ишке ашырууда; тарыхта бул САТУУ аймагы.', 'zh-Hant':'🔔 牛市：價格高於長期持有者的已實現價格 {0}% 且上漲極快 — 他們正在實現目標價；歷史上是賣出區。' },
  an_edu_note: { bg:'Само за обучение — не е инвестиционен съвет. Пазарът може да направи обратното.', ru:'Только для обучения — не инвестиционный совет. Рынок может сделать обратное.', uk:'Лише для навчання — не інвестиційна порада. Ринок може зробити навпаки.', en:'Educational only — not investment advice. The market may do the opposite.', de:'Nur zu Bildungszwecken — keine Anlageberatung. Der Markt kann das Gegenteil tun.', fr:'À but éducatif — pas un conseil en investissement. Le marché peut faire l’inverse.', es:'Solo educativo — no es asesoramiento de inversión. El mercado puede hacer lo contrario.', 'es-MX':'Solo educativo — no es asesoría de inversión. El mercado puede hacer lo contrario.', it:'Solo educativo — non è un consiglio di investimento. Il mercato può fare il contrario.', pt:'Apenas educativo — não é aconselhamento de investimento. O mercado pode fazer o contrário.', ar:'للتعليم فقط — ليست نصيحة استثمارية. قد يفعل السوق العكس.', hi:'केवल शैक्षिक — निवेश सलाह नहीं। बाज़ार उल्टा कर सकता है।', ja:'教育目的のみ — 投資助言ではありません。市場は逆に動くことがあります。', ky:'Билим үчүн гана — инвестициялык кеңеш эмес. Рынок тескерисинче болушу мүмкүн.', 'zh-Hant':'僅供教育 — 非投資建議。市場可能相反。' },

  // --- Пазари (дърво) ---
  pick_market: { bg:'Избери пазар', ru:'Выберите рынок', uk:'Виберіть ринок', en:'Choose a market', de:'Markt wählen', fr:'Choisir un marché', es:'Elige un mercado', 'es-MX':'Elige un mercado', it:'Scegli un mercato', pt:'Escolhe um mercado', ar:'اختر سوقًا', hi:'बाज़ार चुनें', ja:'市場を選ぶ', ky:'Рынок танда', 'zh-Hant':'選擇市場' },
  mk_crypto: { bg:'Криптовалути', ru:'Криптовалюты', uk:'Криптовалюти', en:'Cryptocurrencies', de:'Kryptowährungen', fr:'Cryptomonnaies', es:'Criptomonedas', 'es-MX':'Criptomonedas', it:'Criptovalute', pt:'Criptomoedas', ar:'العملات المشفرة', hi:'क्रिप्टोकरेंसी', ja:'暗号資産', ky:'Криптовалюталар', 'zh-Hant':'加密貨幣' },
  mk_gold: { bg:'Злато и метали', ru:'Золото и металлы', uk:'Золото і метали', en:'Gold & metals', de:'Gold & Metalle', fr:'Or et métaux', es:'Oro y metales', 'es-MX':'Oro y metales', it:'Oro e metalli', pt:'Ouro e metais', ar:'الذهب والمعادن', hi:'सोना और धातुएँ', ja:'金・貴金属', ky:'Алтын жана металлдар', 'zh-Hant':'黃金與金屬' },
  mk_stocks: { bg:'Борсови индекси', ru:'Биржевые индексы', uk:'Біржові індекси', en:'Stock indices', de:'Aktienindizes', fr:'Indices boursiers', es:'Índices bursátiles', 'es-MX':'Índices bursátiles', it:'Indici azionari', pt:'Índices de ações', ar:'مؤشرات الأسهم', hi:'शेयर सूचकांक', ja:'株価指数', ky:'Биржа индекстери', 'zh-Hant':'股票指數' },
  mk_realestate: { bg:'Имоти', ru:'Недвижимость', uk:'Нерухомість', en:'Real estate', de:'Immobilien', fr:'Immobilier', es:'Bienes raíces', 'es-MX':'Bienes raíces', it:'Immobiliare', pt:'Imóveis', ar:'العقارات', hi:'रियल एस्टेट', ja:'不動産', ky:'Кыймылсыз мүлк', 'zh-Hant':'房地產' },

  // --- Период ---
  an_period: { bg:'Период', ru:'Период', uk:'Період', en:'Period', de:'Zeitraum', fr:'Période', es:'Período', 'es-MX':'Período', it:'Periodo', pt:'Período', ar:'الفترة', hi:'अवधि', ja:'期間', ky:'Мезгил', 'zh-Hant':'期間' },
  rng_now: { bg:'Сега', ru:'Сейчас', uk:'Зараз', en:'Now', de:'Jetzt', fr:'Maintenant', es:'Ahora', 'es-MX':'Ahora', it:'Ora', pt:'Agora', ar:'الآن', hi:'अभी', ja:'現在', ky:'Азыр', 'zh-Hant':'現在' },
  rng_y1: { bg:'1 г. назад', ru:'1 г. назад', uk:'1 р. тому', en:'1 yr ago', de:'vor 1 J.', fr:'il y a 1 an', es:'hace 1 año', 'es-MX':'hace 1 año', it:'1 anno fa', pt:'há 1 ano', ar:'قبل سنة', hi:'1 वर्ष पूर्व', ja:'1年前', ky:'1 жыл мурун', 'zh-Hant':'1 年前' },
  rng_y2: { bg:'2 г. назад', ru:'2 г. назад', uk:'2 р. тому', en:'2 yrs ago', de:'vor 2 J.', fr:'il y a 2 ans', es:'hace 2 años', 'es-MX':'hace 2 años', it:'2 anni fa', pt:'há 2 anos', ar:'قبل سنتين', hi:'2 वर्ष पूर्व', ja:'2年前', ky:'2 жыл мурун', 'zh-Hant':'2 年前' },
  rng_y3: { bg:'3 г. назад', ru:'3 г. назад', uk:'3 р. тому', en:'3 yrs ago', de:'vor 3 J.', fr:'il y a 3 ans', es:'hace 3 años', 'es-MX':'hace 3 años', it:'3 anni fa', pt:'há 3 anos', ar:'قبل 3 سنوات', hi:'3 वर्ष पूर्व', ja:'3年前', ky:'3 жыл мурун', 'zh-Hant':'3 年前' },
  rng_y5: { bg:'5 г. назад', ru:'5 л. назад', uk:'5 р. тому', en:'5 yrs ago', de:'vor 5 J.', fr:'il y a 5 ans', es:'hace 5 años', 'es-MX':'hace 5 años', it:'5 anni fa', pt:'há 5 anos', ar:'قبل 5 سنوات', hi:'5 वर्ष पूर्व', ja:'5年前', ky:'5 жыл мурун', 'zh-Hant':'5 年前' },
  rng_custom: { bg:'По дата', ru:'По дате', uk:'За датою', en:'By date', de:'Nach Datum', fr:'Par date', es:'Por fecha', 'es-MX':'Por fecha', it:'Per data', pt:'Por data', ar:'حسب التاريخ', hi:'तिथि अनुसार', ja:'日付指定', ky:'Күнү боюнча', 'zh-Hant':'依日期' },
  an_change: { bg:'Промяна за периода', ru:'Изменение за период', uk:'Зміна за період', en:'Change over period', de:'Veränderung im Zeitraum', fr:'Variation sur la période', es:'Cambio en el período', 'es-MX':'Cambio en el período', it:'Variazione nel periodo', pt:'Variação no período', ar:'التغير خلال الفترة', hi:'अवधि में बदलाव', ja:'期間の変化', ky:'Мезгилдеги өзгөрүү', 'zh-Hant':'期間變化' },
  an_after: { bg:'Какво се случи след това', ru:'Что было потом', uk:'Що було потім', en:'What happened next', de:'Was danach geschah', fr:'Ce qui s’est passé ensuite', es:'Qué pasó después', 'es-MX':'Qué pasó después', it:'Cosa è successo dopo', pt:'O que aconteceu depois', ar:'ماذا حدث بعد ذلك', hi:'आगे क्या हुआ', ja:'その後どうなったか', ky:'Андан кийин эмне болду', 'zh-Hant':'之後發生了什麼' },

  // --- Новини ---
  news_current: { bg:'Текущи новини', ru:'Текущие новости', uk:'Поточні новини', en:'Current news', de:'Aktuelle Nachrichten', fr:'Actualités', es:'Noticias actuales', 'es-MX':'Noticias actuales', it:'Notizie attuali', pt:'Notícias atuais', ar:'الأخبار الحالية', hi:'वर्तमान समाचार', ja:'最新ニュース', ky:'Учурдагы жаңылыктар', 'zh-Hant':'目前新聞' },
  news_period: { bg:'Новини за периода', ru:'Новости за период', uk:'Новини за період', en:'News from this period', de:'Nachrichten aus diesem Zeitraum', fr:'Actualités de la période', es:'Noticias del período', 'es-MX':'Noticias del período', it:'Notizie del periodo', pt:'Notícias do período', ar:'أخبار الفترة', hi:'इस अवधि के समाचार', ja:'この期間のニュース', ky:'Мезгилдин жаңылыктары', 'zh-Hant':'該期間新聞' },
  news_none: { bg:'Няма намерени новини.', ru:'Новостей не найдено.', uk:'Новин не знайдено.', en:'No news found.', de:'Keine Nachrichten gefunden.', fr:'Aucune actualité trouvée.', es:'No se encontraron noticias.', 'es-MX':'No se encontraron noticias.', it:'Nessuna notizia trovata.', pt:'Nenhuma notícia encontrada.', ar:'لا توجد أخبار.', hi:'कोई समाचार नहीं मिला।', ja:'ニュースが見つかりません。', ky:'Жаңылык табылган жок.', 'zh-Hant':'找不到新聞。' },
  back: { bg:'Назад', ru:'Назад', uk:'Назад', en:'Back', de:'Zurück', fr:'Retour', es:'Atrás', 'es-MX':'Atrás', it:'Indietro', pt:'Voltar', ar:'رجوع', hi:'वापस', ja:'戻る', ky:'Артка', 'zh-Hant':'返回' },

  // --- Онбординг ---
  ob_headline: { bg:'Робот, който следи цените вместо теб', ru:'Робот, который следит за ценами вместо вас', uk:'Робот, який стежить за цінами замість вас', en:'A robot that watches prices for you', de:'Ein Roboter, der die Preise für dich beobachtet', fr:'Un robot qui surveille les prix pour vous', es:'Un robot que vigila los precios por ti', 'es-MX':'Un robot que vigila los precios por ti', it:'Un robot che controlla i prezzi al posto tuo', pt:'Um robô que vigia os preços por você', ar:'روبوت يراقب الأسعار نيابةً عنك', hi:'एक बॉट जो आपके लिए कीमतों पर नज़र रखता है', ja:'あなたの代わりに価格を見張るロボット', ky:'Сиздин ордуңузга бааларды көзөмөлдөгөн робот', 'zh-Hant':'替你盯緊價格的機器人' },
  ob_intro: { bg:'Този робот наблюдава избрани крипто и валутни курсове и те известява, щом цената падне под или се качи над зададен от теб праг.', ru:'Этот робот наблюдает за выбранными крипто- и валютными курсами и уведомляет вас, как только цена опустится ниже или поднимется выше заданного вами порога.', uk:'Цей робот спостерігає за обраними крипто- та валютними курсами й сповіщає вас, щойно ціна впаде нижче або підніметься вище заданого вами порога.', en:'This robot watches selected crypto and currency rates and notifies you as soon as a price drops below or rises above the threshold you set.', de:'Dieser Roboter beobachtet ausgewählte Krypto- und Währungskurse und benachrichtigt dich, sobald ein Preis unter oder über die von dir festgelegte Schwelle fällt bzw. steigt.', fr:'Ce robot surveille des taux crypto et de change choisis et vous avertit dès qu’un prix descend sous ou monte au-dessus du seuil que vous fixez.', es:'Este robot vigila tasas de cripto y divisas seleccionadas y te avisa en cuanto un precio baja por debajo o sube por encima del umbral que defines.', 'es-MX':'Este robot vigila tasas de cripto y divisas seleccionadas y te avisa en cuanto un precio baja por debajo o sube por encima del umbral que defines.', it:'Questo robot controlla tassi cripto e valutari selezionati e ti avvisa appena un prezzo scende sotto o sale sopra la soglia che imposti.', pt:'Este robô vigia taxas de cripto e moedas selecionadas e avisa você assim que um preço cai abaixo ou sobe acima do limite que você define.', ar:'يراقب هذا الروبوت أسعار العملات المشفّرة والعملات المختارة ويُنبّهك حالما يهبط السعر دون الحدّ الذي تحدده أو يتجاوزه.', hi:'यह बॉट चुनी हुई क्रिप्टो और मुद्रा दरों पर नज़र रखता है और जैसे ही कोई कीमत आपकी तय सीमा से नीचे गिरती है या ऊपर जाती है, आपको सूचित करता है।', ja:'このロボットは選んだ暗号資産・為替レートを監視し、価格が設定したしきい値を下回るか上回るとすぐに通知します。', ky:'Бул робот тандалган крипто жана валюта курстарын байкап, баа сиз койгон чектен төмөн түшкөндө же жогору чыкканда сизге кабарлайт.', 'zh-Hant':'此機器人監看你選定的加密貨幣與匯率，一旦價格跌破或漲過你設定的門檻就立即通知你。' },
  ob_what_title: { bg:'Какво прави роботът', ru:'Что делает робот', uk:'Що робить робот', en:'What the robot does', de:'Was der Roboter tut', fr:'Ce que fait le robot', es:'Qué hace el robot', 'es-MX':'Qué hace el robot', it:'Cosa fa il robot', pt:'O que o robô faz', ar:'ماذا يفعل الروبوت', hi:'बॉट क्या करता है', ja:'ロボットの機能', ky:'Робот эмне кылат', 'zh-Hant':'機器人會做什麼' },
  ob_feat1: { bg:'Следи BTC, ETH, BNB, SOL, XRP, ADA, DOGE и валути (EUR, GBP, RUB, …).', ru:'Следит за BTC, ETH, BNB, SOL, XRP, ADA, DOGE и валютами (EUR, GBP, RUB, …).', uk:'Стежить за BTC, ETH, BNB, SOL, XRP, ADA, DOGE та валютами (EUR, GBP, RUB, …).', en:'Watches BTC, ETH, BNB, SOL, XRP, ADA, DOGE and currencies (EUR, GBP, RUB, …).', de:'Beobachtet BTC, ETH, BNB, SOL, XRP, ADA, DOGE und Währungen (EUR, GBP, RUB, …).', fr:'Surveille BTC, ETH, BNB, SOL, XRP, ADA, DOGE et devises (EUR, GBP, RUB, …).', es:'Vigila BTC, ETH, BNB, SOL, XRP, ADA, DOGE y divisas (EUR, GBP, RUB, …).', 'es-MX':'Vigila BTC, ETH, BNB, SOL, XRP, ADA, DOGE y divisas (EUR, GBP, RUB, …).', it:'Controlla BTC, ETH, BNB, SOL, XRP, ADA, DOGE e valute (EUR, GBP, RUB, …).', pt:'Vigia BTC, ETH, BNB, SOL, XRP, ADA, DOGE e moedas (EUR, GBP, RUB, …).', ar:'يراقب BTC وETH وBNB وSOL وXRP وADA وDOGE والعملات (EUR وGBP وRUB …).', hi:'BTC, ETH, BNB, SOL, XRP, ADA, DOGE और मुद्राओं (EUR, GBP, RUB, …) पर नज़र रखता है।', ja:'BTC、ETH、BNB、SOL、XRP、ADA、DOGE と通貨（EUR、GBP、RUB …）を監視。', ky:'BTC, ETH, BNB, SOL, XRP, ADA, DOGE жана валюталарды (EUR, GBP, RUB, …) көзөмөлдөйт.', 'zh-Hant':'監看 BTC、ETH、BNB、SOL、XRP、ADA、DOGE 及貨幣（EUR、GBP、RUB …）。' },
  ob_feat2: { bg:'Проверява на 15 минути / 1 час / дневно — ти избираш.', ru:'Проверяет каждые 15 минут / 1 час / раз в день — вы выбираете.', uk:'Перевіряє кожні 15 хвилин / 1 годину / раз на день — ви обираєте.', en:'Checks every 15 minutes / 1 hour / daily — you choose.', de:'Prüft alle 15 Minuten / 1 Stunde / täglich — du wählst.', fr:'Vérifie toutes les 15 minutes / 1 heure / chaque jour — vous choisissez.', es:'Comprueba cada 15 minutos / 1 hora / a diario — tú eliges.', 'es-MX':'Revisa cada 15 minutos / 1 hora / a diario — tú eliges.', it:'Controlla ogni 15 minuti / 1 ora / al giorno — scegli tu.', pt:'Verifica a cada 15 minutos / 1 hora / por dia — você escolhe.', ar:'يتحقق كل ١٥ دقيقة / ساعة / يوميًا — أنت تختار.', hi:'हर 15 मिनट / 1 घंटे / रोज़ाना जाँचता है — आप चुनते हैं।', ja:'15分ごと／1時間ごと／毎日チェック — あなたが選びます。', ky:'Ар 15 мүнөттө / 1 саатта / күн сайын текшерет — сиз тандайсыз.', 'zh-Hant':'每 15 分鐘／1 小時／每日檢查一次——由你選擇。' },
  ob_feat3: { bg:'При достигнат праг праща <b>локално известие</b> на телефона.', ru:'При достижении порога отправляет <b>локальное уведомление</b> на телефон.', uk:'При досягненні порога надсилає <b>локальне сповіщення</b> на телефон.', en:'When the threshold is reached it sends a <b>local notification</b> to your phone.', de:'Bei Erreichen der Schwelle sendet er eine <b>lokale Benachrichtigung</b> an dein Telefon.', fr:'Quand le seuil est atteint, il envoie une <b>notification locale</b> sur votre téléphone.', es:'Cuando se alcanza el umbral envía una <b>notificación local</b> a tu teléfono.', 'es-MX':'Cuando se alcanza el umbral envía una <b>notificación local</b> a tu teléfono.', it:'Al raggiungimento della soglia invia una <b>notifica locale</b> sul telefono.', pt:'Quando o limite é atingido, envia uma <b>notificação local</b> ao seu telefone.', ar:'عند بلوغ الحدّ يرسل <b>إشعارًا محليًا</b> إلى هاتفك.', hi:'सीमा पर पहुँचने पर आपके फ़ोन पर <b>लोकल सूचना</b> भेजता है।', ja:'しきい値に達すると、端末に<b>ローカル通知</b>を送ります。', ky:'Чекке жеткенде телефонуңузга <b>жергиликтүү билдирүү</b> жөнөтөт.', 'zh-Hant':'達到門檻時，會向你的手機發送<b>本機通知</b>。' },
  ob_privacy: { bg:'Всичко работи на устройството. Без акаунт, без контакти, без проследяване. Цените идват от безплатни публични източници.', ru:'Всё работает на устройстве. Без аккаунта, без контактов, без слежки. Цены берутся из бесплатных публичных источников.', uk:'Усе працює на пристрої. Без акаунта, без контактів, без стеження. Ціни беруться з безкоштовних публічних джерел.', en:'Everything runs on the device. No account, no contacts, no tracking. Prices come from free public sources.', de:'Alles läuft auf dem Gerät. Kein Konto, keine Kontakte, kein Tracking. Die Preise stammen aus kostenlosen öffentlichen Quellen.', fr:'Tout fonctionne sur l’appareil. Sans compte, sans contacts, sans suivi. Les prix proviennent de sources publiques gratuites.', es:'Todo funciona en el dispositivo. Sin cuenta, sin contactos, sin rastreo. Los precios vienen de fuentes públicas gratuitas.', 'es-MX':'Todo funciona en el dispositivo. Sin cuenta, sin contactos, sin rastreo. Los precios vienen de fuentes públicas gratuitas.', it:'Tutto funziona sul dispositivo. Nessun account, nessun contatto, nessun tracciamento. I prezzi provengono da fonti pubbliche gratuite.', pt:'Tudo funciona no dispositivo. Sem conta, sem contatos, sem rastreamento. Os preços vêm de fontes públicas gratuitas.', ar:'كل شيء يعمل على الجهاز. بلا حساب، بلا جهات اتصال، بلا تتبّع. الأسعار من مصادر عامة مجانية.', hi:'सब कुछ डिवाइस पर चलता है। कोई खाता नहीं, कोई संपर्क नहीं, कोई ट्रैकिंग नहीं। कीमतें मुफ़्त सार्वजनिक स्रोतों से आती हैं।', ja:'すべて端末上で動作します。アカウント不要、連絡先不要、追跡なし。価格は無料の公開ソースから取得します。', ky:'Баары түзмөктө иштейт. Аккаунтсуз, байланыштарсыз, көзөмөлсүз. Баалар акысыз ачык булактардан алынат.', 'zh-Hant':'一切都在裝置上運行。無需帳戶、不存取聯絡人、不追蹤。價格來自免費的公開來源。' },
  ob_activate: { bg:'Активирай робота безплатно', ru:'Активировать робота бесплатно', uk:'Активувати робота безкоштовно', en:'Activate the robot for free', de:'Roboter kostenlos aktivieren', fr:'Activer le robot gratuitement', es:'Activar el robot gratis', 'es-MX':'Activar el robot gratis', it:'Attiva il robot gratis', pt:'Ativar o robô grátis', ar:'فعّل الروبوت مجانًا', hi:'बॉट मुफ़्त में सक्रिय करें', ja:'ロボットを無料で有効化', ky:'Роботту акысыз иштетүү', 'zh-Hant':'免費啟用機器人' },
  ob_all_free: { bg:'Всички функции са напълно безплатни.', ru:'Все функции полностью бесплатны.', uk:'Усі функції повністю безкоштовні.', en:'All features are completely free.', de:'Alle Funktionen sind völlig kostenlos.', fr:'Toutes les fonctions sont entièrement gratuites.', es:'Todas las funciones son completamente gratis.', 'es-MX':'Todas las funciones son completamente gratis.', it:'Tutte le funzioni sono completamente gratuite.', pt:'Todos os recursos são totalmente grátis.', ar:'كل الميزات مجانية تمامًا.', hi:'सभी सुविधाएँ पूरी तरह मुफ़्त हैं।', ja:'すべての機能は完全に無料です。', ky:'Бардык функциялар толугу менен акысыз.', 'zh-Hant':'所有功能完全免費。' },
  log_activated: { bg:'✅ Роботът е активиран', ru:'✅ Робот активирован', uk:'✅ Робота активовано', en:'✅ Robot activated', de:'✅ Roboter aktiviert', fr:'✅ Robot activé', es:'✅ Robot activado', 'es-MX':'✅ Robot activado', it:'✅ Robot attivato', pt:'✅ Robô ativado', ar:'✅ تم تفعيل الروبوت', hi:'✅ बॉट सक्रिय हुआ', ja:'✅ ロボットを有効化しました', ky:'✅ Робот иштетилди', 'zh-Hant':'✅ 機器人已啟用' },

  // --- Конфигурация ---
  cfg_title: { bg:'Настрой робота', ru:'Настройте робота', uk:'Налаштуйте робота', en:'Set up the robot', de:'Roboter einrichten', fr:'Configurer le robot', es:'Configura el robot', 'es-MX':'Configura el robot', it:'Configura il robot', pt:'Configure o robô', ar:'إعداد الروبوت', hi:'बॉट सेट करें', ja:'ロボットを設定', ky:'Роботту жөндөңүз', 'zh-Hant':'設定機器人' },
  cfg_intro: { bg:'Добави какво да следи роботът. Можеш да добавиш няколко.', ru:'Добавьте, за чем следить роботу. Можно добавить несколько.', uk:'Додайте, за чим стежити роботу. Можна додати кілька.', en:'Add what the robot should watch. You can add several.', de:'Füge hinzu, was der Roboter beobachten soll. Du kannst mehrere hinzufügen.', fr:'Ajoutez ce que le robot doit surveiller. Vous pouvez en ajouter plusieurs.', es:'Añade qué debe vigilar el robot. Puedes añadir varios.', 'es-MX':'Agrega qué debe vigilar el robot. Puedes agregar varios.', it:'Aggiungi cosa deve controllare il robot. Puoi aggiungerne diversi.', pt:'Adicione o que o robô deve vigiar. Você pode adicionar vários.', ar:'أضف ما يجب أن يراقبه الروبوت. يمكنك إضافة عدة عناصر.', hi:'जोड़ें कि बॉट को क्या देखना है। आप कई जोड़ सकते हैं।', ja:'ロボットが監視する対象を追加します。複数追加できます。', ky:'Робот эмнени көзөмөлдөшү керектигин кошуңуз. Бир нечесин кошсоңуз болот.', 'zh-Hant':'新增機器人要監看的對象，可新增多個。' },
  cfg_type: { bg:'Тип', ru:'Тип', uk:'Тип', en:'Type', de:'Typ', fr:'Type', es:'Tipo', 'es-MX':'Tipo', it:'Tipo', pt:'Tipo', ar:'النوع', hi:'प्रकार', ja:'タイプ', ky:'Түрү', 'zh-Hant':'類型' },
  cfg_crypto: { bg:'Крипто', ru:'Крипто', uk:'Крипто', en:'Crypto', de:'Krypto', fr:'Crypto', es:'Cripto', 'es-MX':'Cripto', it:'Cripto', pt:'Cripto', ar:'العملات المشفّرة', hi:'क्रिप्टो', ja:'暗号資産', ky:'Крипто', 'zh-Hant':'加密貨幣' },
  cfg_fx: { bg:'Валута (FX)', ru:'Валюта (FX)', uk:'Валюта (FX)', en:'Currency (FX)', de:'Währung (FX)', fr:'Devise (FX)', es:'Divisa (FX)', 'es-MX':'Divisa (FX)', it:'Valuta (FX)', pt:'Moeda (FX)', ar:'العملة (FX)', hi:'मुद्रा (FX)', ja:'通貨 (FX)', ky:'Валюта (FX)', 'zh-Hant':'貨幣 (FX)' },
  cfg_coin_label: { bg:'Монета (цена в USD)', ru:'Монета (цена в USD)', uk:'Монета (ціна в USD)', en:'Coin (price in USD)', de:'Coin (Preis in USD)', fr:'Pièce (prix en USD)', es:'Moneda (precio en USD)', 'es-MX':'Moneda (precio en USD)', it:'Moneta (prezzo in USD)', pt:'Moeda (preço em USD)', ar:'العملة (السعر بالدولار)', hi:'सिक्का (USD में कीमत)', ja:'コイン（USD価格）', ky:'Коин (баасы USD менен)', 'zh-Hant':'幣別（美元價格）' },
  cfg_fx_label: { bg:'Валута (за 1 USD)', ru:'Валюта (за 1 USD)', uk:'Валюта (за 1 USD)', en:'Currency (per 1 USD)', de:'Währung (pro 1 USD)', fr:'Devise (pour 1 USD)', es:'Divisa (por 1 USD)', 'es-MX':'Divisa (por 1 USD)', it:'Valuta (per 1 USD)', pt:'Moeda (por 1 USD)', ar:'العملة (لكل 1 دولار)', hi:'मुद्रा (प्रति 1 USD)', ja:'通貨（1 USD あたり）', ky:'Валюта (1 USD үчүн)', 'zh-Hant':'貨幣（每 1 美元）' },
  cfg_condition: { bg:'Условие', ru:'Условие', uk:'Умова', en:'Condition', de:'Bedingung', fr:'Condition', es:'Condición', 'es-MX':'Condición', it:'Condizione', pt:'Condição', ar:'الشرط', hi:'शर्त', ja:'条件', ky:'Шарт', 'zh-Hant':'條件' },
  cfg_below: { bg:'Падне под', ru:'Опустится ниже', uk:'Впаде нижче', en:'Drops below', de:'Fällt unter', fr:'Descend sous', es:'Baja por debajo', 'es-MX':'Baja por debajo', it:'Scende sotto', pt:'Cai abaixo', ar:'يهبط دون', hi:'नीचे गिरे', ja:'下回る', ky:'Төмөн түшөт', 'zh-Hant':'跌破' },
  cfg_above: { bg:'Качи се над', ru:'Поднимется выше', uk:'Підніметься вище', en:'Rises above', de:'Steigt über', fr:'Monte au-dessus', es:'Sube por encima', 'es-MX':'Sube por encima', it:'Sale sopra', pt:'Sobe acima', ar:'يتجاوز', hi:'ऊपर जाए', ja:'上回る', ky:'Жогору чыгат', 'zh-Hant':'漲過' },
  cfg_threshold: { bg:'Прагова стойност', ru:'Пороговое значение', uk:'Порогове значення', en:'Threshold value', de:'Schwellenwert', fr:'Valeur seuil', es:'Valor umbral', 'es-MX':'Valor umbral', it:'Valore soglia', pt:'Valor limite', ar:'القيمة الحدّية', hi:'सीमा मान', ja:'しきい値', ky:'Чектик маани', 'zh-Hant':'門檻值' },
  cfg_threshold_ph: { bg:'напр. 60000', ru:'напр. 60000', uk:'напр. 60000', en:'e.g. 60000', de:'z. B. 60000', fr:'p. ex. 60000', es:'p. ej. 60000', 'es-MX':'p. ej. 60000', it:'es. 60000', pt:'ex. 60000', ar:'مثل 60000', hi:'जैसे 60000', ja:'例: 60000', ky:'мис. 60000', 'zh-Hant':'例如 60000' },
  cfg_freq: { bg:'Честота на проверка', ru:'Частота проверки', uk:'Частота перевірки', en:'Check frequency', de:'Prüfhäufigkeit', fr:'Fréquence de vérification', es:'Frecuencia de comprobación', 'es-MX':'Frecuencia de revisión', it:'Frequenza di controllo', pt:'Frequência de verificação', ar:'تكرار الفحص', hi:'जाँच की आवृत्ति', ja:'チェック頻度', ky:'Текшерүү жыштыгы', 'zh-Hant':'檢查頻率' },
  freq_15min: { bg:'На 15 минути', ru:'Каждые 15 минут', uk:'Кожні 15 хвилин', en:'Every 15 minutes', de:'Alle 15 Minuten', fr:'Toutes les 15 minutes', es:'Cada 15 minutos', 'es-MX':'Cada 15 minutos', it:'Ogni 15 minuti', pt:'A cada 15 minutos', ar:'كل ١٥ دقيقة', hi:'हर 15 मिनट', ja:'15分ごと', ky:'Ар 15 мүнөттө', 'zh-Hant':'每 15 分鐘' },
  freq_1h: { bg:'На 1 час', ru:'Каждый час', uk:'Щогодини', en:'Every hour', de:'Stündlich', fr:'Toutes les heures', es:'Cada hora', 'es-MX':'Cada hora', it:'Ogni ora', pt:'A cada hora', ar:'كل ساعة', hi:'हर घंटे', ja:'1時間ごと', ky:'Ар саатта', 'zh-Hant':'每小時' },
  freq_daily: { bg:'Веднъж дневно', ru:'Раз в день', uk:'Раз на день', en:'Once a day', de:'Einmal täglich', fr:'Une fois par jour', es:'Una vez al día', 'es-MX':'Una vez al día', it:'Una volta al giorno', pt:'Uma vez por dia', ar:'مرة يوميًا', hi:'दिन में एक बार', ja:'1日1回', ky:'Күнүнө бир жолу', 'zh-Hant':'每天一次' },
  cfg_add: { bg:'Добави наблюдение', ru:'Добавить наблюдение', uk:'Додати спостереження', en:'Add a watch', de:'Beobachtung hinzufügen', fr:'Ajouter une surveillance', es:'Añadir seguimiento', 'es-MX':'Agregar seguimiento', it:'Aggiungi monitoraggio', pt:'Adicionar monitoramento', ar:'أضف مراقبة', hi:'निगरानी जोड़ें', ja:'ウォッチを追加', ky:'Көзөмөл кошуу', 'zh-Hant':'新增監看' },
  cfg_current_n: { bg:'Текущи наблюдения ({0})', ru:'Текущие наблюдения ({0})', uk:'Поточні спостереження ({0})', en:'Current watches ({0})', de:'Aktuelle Beobachtungen ({0})', fr:'Surveillances actuelles ({0})', es:'Seguimientos actuales ({0})', 'es-MX':'Seguimientos actuales ({0})', it:'Monitoraggi attuali ({0})', pt:'Monitoramentos atuais ({0})', ar:'المراقبات الحالية ({0})', hi:'वर्तमान निगरानी ({0})', ja:'現在のウォッチ ({0})', ky:'Учурдагы көзөмөлдөр ({0})', 'zh-Hant':'目前的監看 ({0})' },
  cfg_none_yet: { bg:'Още няма добавени наблюдения.', ru:'Пока нет добавленных наблюдений.', uk:'Поки немає доданих спостережень.', en:'No watches added yet.', de:'Noch keine Beobachtungen hinzugefügt.', fr:'Aucune surveillance ajoutée pour l’instant.', es:'Aún no hay seguimientos añadidos.', 'es-MX':'Aún no hay seguimientos agregados.', it:'Ancora nessun monitoraggio aggiunto.', pt:'Nenhum monitoramento adicionado ainda.', ar:'لا توجد مراقبات مضافة بعد.', hi:'अभी तक कोई निगरानी नहीं जोड़ी गई।', ja:'まだウォッチが追加されていません。', ky:'Азырынча кошулган көзөмөл жок.', 'zh-Hant':'尚未新增任何監看。' },
  cfg_to_perms: { bg:'Продължи към разрешения', ru:'Перейти к разрешениям', uk:'Перейти до дозволів', en:'Continue to permissions', de:'Weiter zu den Berechtigungen', fr:'Continuer vers les autorisations', es:'Continuar a permisos', 'es-MX':'Continuar a permisos', it:'Continua ai permessi', pt:'Continuar para permissões', ar:'المتابعة إلى الأذونات', hi:'अनुमतियों पर जाएँ', ja:'権限へ進む', ky:'Уруксаттарга өтүү', 'zh-Hant':'前往權限' },
  cfg_invalid: { bg:'Въведи валидна прагова стойност.', ru:'Введите корректное пороговое значение.', uk:'Введіть коректне порогове значення.', en:'Enter a valid threshold value.', de:'Gib einen gültigen Schwellenwert ein.', fr:'Saisissez une valeur seuil valide.', es:'Introduce un valor umbral válido.', 'es-MX':'Ingresa un valor umbral válido.', it:'Inserisci un valore soglia valido.', pt:'Insira um valor limite válido.', ar:'أدخل قيمة حدّية صحيحة.', hi:'मान्य सीमा मान दर्ज करें।', ja:'有効なしきい値を入力してください。', ky:'Жарактуу чектик маани киргизиңиз.', 'zh-Hant':'請輸入有效的門檻值。' },
  cfg_limit: { bg:'Достигнат лимит ({0}).', ru:'Достигнут лимит ({0}).', uk:'Досягнуто ліміту ({0}).', en:'Limit reached ({0}).', de:'Limit erreicht ({0}).', fr:'Limite atteinte ({0}).', es:'Límite alcanzado ({0}).', 'es-MX':'Límite alcanzado ({0}).', it:'Limite raggiunto ({0}).', pt:'Limite atingido ({0}).', ar:'تم بلوغ الحدّ ({0}).', hi:'सीमा पूरी हुई ({0}).', ja:'上限に達しました ({0})。', ky:'Чек ашты ({0}).', 'zh-Hant':'已達上限 ({0})。' },
  log_added: { bg:'➕ Добавено: {0} {1} {2}', ru:'➕ Добавлено: {0} {1} {2}', uk:'➕ Додано: {0} {1} {2}', en:'➕ Added: {0} {1} {2}', de:'➕ Hinzugefügt: {0} {1} {2}', fr:'➕ Ajouté : {0} {1} {2}', es:'➕ Añadido: {0} {1} {2}', 'es-MX':'➕ Agregado: {0} {1} {2}', it:'➕ Aggiunto: {0} {1} {2}', pt:'➕ Adicionado: {0} {1} {2}', ar:'➕ تمت الإضافة: {0} {1} {2}', hi:'➕ जोड़ा गया: {0} {1} {2}', ja:'➕ 追加: {0} {1} {2}', ky:'➕ Кошулду: {0} {1} {2}', 'zh-Hant':'➕ 已新增：{0} {1} {2}' },

  // --- Разрешения ---
  perm_title: { bg:'Разрешения', ru:'Разрешения', uk:'Дозволи', en:'Permissions', de:'Berechtigungen', fr:'Autorisations', es:'Permisos', 'es-MX':'Permisos', it:'Permessi', pt:'Permissões', ar:'الأذونات', hi:'अनुमतियाँ', ja:'権限', ky:'Уруксаттар', 'zh-Hant':'權限' },
  perm_intro: { bg:'Роботът иска само това, което му трябва. Нищо повече. Можеш да го промениш по всяко време.', ru:'Робот запрашивает только необходимое. Ничего лишнего. Это можно изменить в любой момент.', uk:'Робот запитує лише необхідне. Нічого зайвого. Це можна змінити будь-коли.', en:'The robot asks only for what it needs. Nothing more. You can change this any time.', de:'Der Roboter fragt nur nach dem, was er braucht. Nicht mehr. Du kannst das jederzeit ändern.', fr:'Le robot ne demande que ce dont il a besoin. Rien de plus. Vous pouvez le changer à tout moment.', es:'El robot pide solo lo que necesita. Nada más. Puedes cambiarlo cuando quieras.', 'es-MX':'El robot pide solo lo que necesita. Nada más. Puedes cambiarlo cuando quieras.', it:'Il robot chiede solo ciò che gli serve. Nulla di più. Puoi cambiarlo in qualsiasi momento.', pt:'O robô pede apenas o necessário. Nada mais. Você pode mudar isso a qualquer momento.', ar:'يطلب الروبوت ما يحتاجه فقط. لا أكثر. يمكنك تغيير ذلك في أي وقت.', hi:'बॉट केवल वही माँगता है जो उसे चाहिए। इससे ज़्यादा नहीं। आप इसे कभी भी बदल सकते हैं।', ja:'ロボットは必要なものだけを求めます。それ以上は不要です。いつでも変更できます。', ky:'Робот керектүүсүн гана сурайт. Ашыкчасы жок. Аны каалаган убакта өзгөртө аласыз.', 'zh-Hant':'機器人只要求必要的權限，別無其他。你可隨時更改。' },
  perm_notif_title: { bg:'🔔 Известия', ru:'🔔 Уведомления', uk:'🔔 Сповіщення', en:'🔔 Notifications', de:'🔔 Benachrichtigungen', fr:'🔔 Notifications', es:'🔔 Notificaciones', 'es-MX':'🔔 Notificaciones', it:'🔔 Notifiche', pt:'🔔 Notificações', ar:'🔔 الإشعارات', hi:'🔔 सूचनाएँ', ja:'🔔 通知', ky:'🔔 Билдирүүлөр', 'zh-Hant':'🔔 通知' },
  perm_notif_desc: { bg:'За да те уведоми, когато цена достигне твоя праг. Известията са локални — не минават през сървър.', ru:'Чтобы уведомить вас, когда цена достигнет вашего порога. Уведомления локальные — не проходят через сервер.', uk:'Щоб сповістити вас, коли ціна досягне вашого порога. Сповіщення локальні — не проходять через сервер.', en:'To notify you when a price reaches your threshold. Notifications are local — they do not go through a server.', de:'Um dich zu benachrichtigen, wenn ein Preis deine Schwelle erreicht. Die Benachrichtigungen sind lokal — sie laufen nicht über einen Server.', fr:'Pour vous prévenir quand un prix atteint votre seuil. Les notifications sont locales — elles ne passent pas par un serveur.', es:'Para avisarte cuando un precio alcance tu umbral. Las notificaciones son locales — no pasan por un servidor.', 'es-MX':'Para avisarte cuando un precio alcance tu umbral. Las notificaciones son locales — no pasan por un servidor.', it:'Per avvisarti quando un prezzo raggiunge la tua soglia. Le notifiche sono locali — non passano da un server.', pt:'Para avisar você quando um preço atingir seu limite. As notificações são locais — não passam por um servidor.', ar:'لتنبيهك عندما يبلغ السعر حدّك. الإشعارات محلية — لا تمرّ عبر خادم.', hi:'जब कोई कीमत आपकी सीमा तक पहुँचे तो आपको सूचित करने के लिए। सूचनाएँ लोकल हैं — किसी सर्वर से नहीं जातीं।', ja:'価格がしきい値に達したときに通知するためです。通知はローカルで、サーバーを経由しません。', ky:'Баа сиздин чекке жеткенде кабарлоо үчүн. Билдирүүлөр жергиликтүү — сервер аркылуу өтпөйт.', 'zh-Hant':'在價格達到你的門檻時通知你。通知為本機通知，不經過伺服器。' },
  perm_net_title: { bg:'🌐 Достъп до интернет', ru:'🌐 Доступ к интернету', uk:'🌐 Доступ до інтернету', en:'🌐 Internet access', de:'🌐 Internetzugang', fr:'🌐 Accès à Internet', es:'🌐 Acceso a Internet', 'es-MX':'🌐 Acceso a Internet', it:'🌐 Accesso a Internet', pt:'🌐 Acesso à Internet', ar:'🌐 الوصول إلى الإنترنت', hi:'🌐 इंटरनेट एक्सेस', ja:'🌐 インターネット接続', ky:'🌐 Интернетке мүмкүндүк', 'zh-Hant':'🌐 網路存取' },
  perm_net_desc: { bg:'За да чете цените от безплатните публични източници (Binance, CoinGecko, open.er-api.com). Без него роботът не може да проверява цени.', ru:'Чтобы читать цены из бесплатных публичных источников (Binance, CoinGecko, open.er-api.com). Без него робот не может проверять цены.', uk:'Щоб читати ціни з безкоштовних публічних джерел (Binance, CoinGecko, open.er-api.com). Без нього робот не може перевіряти ціни.', en:'To read prices from the free public sources (Binance, CoinGecko, open.er-api.com). Without it the robot cannot check prices.', de:'Um die Preise aus den kostenlosen öffentlichen Quellen (Binance, CoinGecko, open.er-api.com) zu lesen. Ohne ihn kann der Roboter keine Preise prüfen.', fr:'Pour lire les prix depuis les sources publiques gratuites (Binance, CoinGecko, open.er-api.com). Sans cela, le robot ne peut pas vérifier les prix.', es:'Para leer los precios de las fuentes públicas gratuitas (Binance, CoinGecko, open.er-api.com). Sin él, el robot no puede comprobar precios.', 'es-MX':'Para leer los precios de las fuentes públicas gratuitas (Binance, CoinGecko, open.er-api.com). Sin él, el robot no puede revisar precios.', it:'Per leggere i prezzi dalle fonti pubbliche gratuite (Binance, CoinGecko, open.er-api.com). Senza, il robot non può controllare i prezzi.', pt:'Para ler os preços das fontes públicas gratuitas (Binance, CoinGecko, open.er-api.com). Sem ele, o robô não consegue verificar preços.', ar:'لقراءة الأسعار من المصادر العامة المجانية (Binance وCoinGecko وopen.er-api.com). بدونه لا يستطيع الروبوت فحص الأسعار.', hi:'मुफ़्त सार्वजनिक स्रोतों (Binance, CoinGecko, open.er-api.com) से कीमतें पढ़ने के लिए। इसके बिना बॉट कीमतें जाँच नहीं सकता।', ja:'無料の公開ソース（Binance、CoinGecko、open.er-api.com）から価格を読み取るためです。これがないとロボットは価格を確認できません。', ky:'Бааларды акысыз ачык булактардан (Binance, CoinGecko, open.er-api.com) окуу үчүн. Ансыз робот бааларды текшере албайт.', 'zh-Hant':'用於從免費公開來源（Binance、CoinGecko、open.er-api.com）讀取價格。沒有它，機器人無法檢查價格。' },
  perm_needed: { bg:'нужно', ru:'необходимо', uk:'потрібно', en:'required', de:'erforderlich', fr:'requis', es:'necesario', 'es-MX':'necesario', it:'necessario', pt:'necessário', ar:'مطلوب', hi:'आवश्यक', ja:'必須', ky:'керек', 'zh-Hant':'必要' },
  perm_not_asked: { bg:'❌ Роботът НЕ иска: контакти, местоположение, камера, файлове, реклами или анализи.', ru:'❌ Робот НЕ запрашивает: контакты, местоположение, камеру, файлы, рекламу или аналитику.', uk:'❌ Робот НЕ запитує: контакти, місцезнаходження, камеру, файли, рекламу чи аналітику.', en:'❌ The robot does NOT ask for: contacts, location, camera, files, ads or analytics.', de:'❌ Der Roboter fragt NICHT nach: Kontakten, Standort, Kamera, Dateien, Werbung oder Analyse.', fr:'❌ Le robot ne demande PAS : contacts, localisation, caméra, fichiers, publicités ou analyses.', es:'❌ El robot NO pide: contactos, ubicación, cámara, archivos, anuncios ni analíticas.', 'es-MX':'❌ El robot NO pide: contactos, ubicación, cámara, archivos, anuncios ni analíticas.', it:'❌ Il robot NON chiede: contatti, posizione, fotocamera, file, pubblicità o analisi.', pt:'❌ O robô NÃO pede: contatos, localização, câmera, arquivos, anúncios ou análises.', ar:'❌ الروبوت لا يطلب: جهات الاتصال أو الموقع أو الكاميرا أو الملفات أو الإعلانات أو التحليلات.', hi:'❌ बॉट नहीं माँगता: संपर्क, स्थान, कैमरा, फ़ाइलें, विज्ञापन या एनालिटिक्स।', ja:'❌ ロボットは要求しません：連絡先、位置情報、カメラ、ファイル、広告、分析。', ky:'❌ Робот сурабайт: байланыштар, жайгашуу, камера, файлдар, жарнама же аналитика.', 'zh-Hant':'❌ 機器人不會要求：聯絡人、位置、相機、檔案、廣告或分析。' },
  perm_done: { bg:'Готово — към таблото', ru:'Готово — к панели', uk:'Готово — до панелі', en:'Done — to the dashboard', de:'Fertig — zum Dashboard', fr:'Terminé — vers le tableau de bord', es:'Listo — al panel', 'es-MX':'Listo — al panel', it:'Fatto — alla dashboard', pt:'Pronto — para o painel', ar:'تم — إلى اللوحة', hi:'हो गया — डैशबोर्ड पर', ja:'完了 — ダッシュボードへ', ky:'Даяр — башкаруу панелине', 'zh-Hant':'完成 — 前往儀表板' },

  // --- Табло ---
  dash_title: { bg:'Табло на робота', ru:'Панель робота', uk:'Панель робота', en:'Robot dashboard', de:'Roboter-Dashboard', fr:'Tableau de bord du robot', es:'Panel del robot', 'es-MX':'Panel del robot', it:'Dashboard del robot', pt:'Painel do robô', ar:'لوحة الروبوت', hi:'बॉट डैशबोर्ड', ja:'ロボットのダッシュボード', ky:'Робот панели', 'zh-Hant':'機器人儀表板' },
  dash_master: { bg:'Главен ключ', ru:'Главный выключатель', uk:'Головний вимикач', en:'Master switch', de:'Hauptschalter', fr:'Interrupteur principal', es:'Interruptor principal', 'es-MX':'Interruptor principal', it:'Interruttore principale', pt:'Interruptor principal', ar:'المفتاح الرئيسي', hi:'मुख्य स्विच', ja:'メインスイッチ', ky:'Башкы өчүргүч', 'zh-Hant':'主開關' },
  dash_on: { bg:'Роботът следи цените', ru:'Робот следит за ценами', uk:'Робот стежить за цінами', en:'The robot is watching prices', de:'Der Roboter beobachtet die Preise', fr:'Le robot surveille les prix', es:'El robot vigila los precios', 'es-MX':'El robot vigila los precios', it:'Il robot controlla i prezzi', pt:'O robô está vigiando os preços', ar:'الروبوت يراقب الأسعار', hi:'बॉट कीमतों पर नज़र रख रहा है', ja:'ロボットが価格を監視中', ky:'Робот бааларды көзөмөлдөп жатат', 'zh-Hant':'機器人正在監看價格' },
  dash_off: { bg:'Роботът е спрян', ru:'Робот остановлен', uk:'Робот зупинено', en:'The robot is stopped', de:'Der Roboter ist gestoppt', fr:'Le robot est arrêté', es:'El robot está detenido', 'es-MX':'El robot está detenido', it:'Il robot è fermo', pt:'O robô está parado', ar:'الروبوت متوقف', hi:'बॉट रुका हुआ है', ja:'ロボットは停止中', ky:'Робот токтотулду', 'zh-Hant':'機器人已停止' },
  dash_check_now: { bg:'Провери сега', ru:'Проверить сейчас', uk:'Перевірити зараз', en:'Check now', de:'Jetzt prüfen', fr:'Vérifier maintenant', es:'Comprobar ahora', 'es-MX':'Revisar ahora', it:'Controlla ora', pt:'Verificar agora', ar:'افحص الآن', hi:'अभी जाँचें', ja:'今すぐ確認', ky:'Азыр текшерүү', 'zh-Hant':'立即檢查' },
  dash_add_more: { bg:'+ Добави наблюдение', ru:'+ Добавить наблюдение', uk:'+ Додати спостереження', en:'+ Add a watch', de:'+ Beobachtung hinzufügen', fr:'+ Ajouter une surveillance', es:'+ Añadir seguimiento', 'es-MX':'+ Agregar seguimiento', it:'+ Aggiungi monitoraggio', pt:'+ Adicionar monitoramento', ar:'+ أضف مراقبة', hi:'+ निगरानी जोड़ें', ja:'+ ウォッチを追加', ky:'+ Көзөмөл кошуу', 'zh-Hant':'+ 新增監看' },
  dash_watches_n: { bg:'Наблюдения ({0})', ru:'Наблюдения ({0})', uk:'Спостереження ({0})', en:'Watches ({0})', de:'Beobachtungen ({0})', fr:'Surveillances ({0})', es:'Seguimientos ({0})', 'es-MX':'Seguimientos ({0})', it:'Monitoraggi ({0})', pt:'Monitoramentos ({0})', ar:'المراقبات ({0})', hi:'निगरानी ({0})', ja:'ウォッチ ({0})', ky:'Көзөмөлдөр ({0})', 'zh-Hant':'監看 ({0})' },
  dash_no_watches: { bg:'Няма наблюдения. Натисни „+ Добави наблюдение".', ru:'Нет наблюдений. Нажмите «+ Добавить наблюдение».', uk:'Немає спостережень. Натисніть «+ Додати спостереження».', en:'No watches. Tap “+ Add a watch”.', de:'Keine Beobachtungen. Tippe auf „+ Beobachtung hinzufügen".', fr:'Aucune surveillance. Touchez « + Ajouter une surveillance ».', es:'Sin seguimientos. Toca «+ Añadir seguimiento».', 'es-MX':'Sin seguimientos. Toca «+ Agregar seguimiento».', it:'Nessun monitoraggio. Tocca “+ Aggiungi monitoraggio".', pt:'Sem monitoramentos. Toque em “+ Adicionar monitoramento".', ar:'لا مراقبات. اضغط «+ أضف مراقبة».', hi:'कोई निगरानी नहीं। “+ निगरानी जोड़ें" दबाएँ।', ja:'ウォッチがありません。「+ ウォッチを追加」をタップ。', ky:'Көзөмөл жок. «+ Көзөмөл кошуу» басыңыз.', 'zh-Hant':'沒有監看。點擊「+ 新增監看」。' },
  dash_last: { bg:'последно:', ru:'последнее:', uk:'останнє:', en:'last:', de:'zuletzt:', fr:'dernier :', es:'último:', 'es-MX':'último:', it:'ultimo:', pt:'último:', ar:'الأخير:', hi:'अंतिम:', ja:'最新:', ky:'акыркы:', 'zh-Hant':'最新：' },
  dash_log: { bg:'Дневник', ru:'Журнал', uk:'Журнал', en:'Log', de:'Protokoll', fr:'Journal', es:'Registro', 'es-MX':'Registro', it:'Registro', pt:'Registro', ar:'السجل', hi:'लॉग', ja:'ログ', ky:'Журнал', 'zh-Hant':'紀錄' },
  dash_log_empty: { bg:'Дневникът е празен.', ru:'Журнал пуст.', uk:'Журнал порожній.', en:'The log is empty.', de:'Das Protokoll ist leer.', fr:'Le journal est vide.', es:'El registro está vacío.', 'es-MX':'El registro está vacío.', it:'Il registro è vuoto.', pt:'O registro está vazio.', ar:'السجل فارغ.', hi:'लॉग खाली है।', ja:'ログは空です。', ky:'Журнал бош.', 'zh-Hant':'紀錄為空。' },
  pause: { bg:'Пауза', ru:'Пауза', uk:'Пауза', en:'Pause', de:'Pause', fr:'Pause', es:'Pausa', 'es-MX':'Pausa', it:'Pausa', pt:'Pausar', ar:'إيقاف مؤقت', hi:'रोकें', ja:'一時停止', ky:'Тыныгуу', 'zh-Hant':'暫停' },
  resume: { bg:'Пусни', ru:'Возобновить', uk:'Відновити', en:'Resume', de:'Fortsetzen', fr:'Reprendre', es:'Reanudar', 'es-MX':'Reanudar', it:'Riprendi', pt:'Retomar', ar:'استئناف', hi:'फिर शुरू करें', ja:'再開', ky:'Улантуу', 'zh-Hant':'繼續' },

  // --- Значки за състояние ---
  badge_paused: { bg:'на пауза', ru:'на паузе', uk:'на паузі', en:'paused', de:'pausiert', fr:'en pause', es:'en pausa', 'es-MX':'en pausa', it:'in pausa', pt:'em pausa', ar:'متوقف مؤقتًا', hi:'रुका हुआ', ja:'一時停止中', ky:'тыныгууда', 'zh-Hant':'已暫停' },
  badge_error: { bg:'грешка', ru:'ошибка', uk:'помилка', en:'error', de:'Fehler', fr:'erreur', es:'error', 'es-MX':'error', it:'errore', pt:'erro', ar:'خطأ', hi:'त्रुटि', ja:'エラー', ky:'ката', 'zh-Hant':'錯誤' },
  badge_hit: { bg:'праг достигнат', ru:'порог достигнут', uk:'поріг досягнуто', en:'threshold reached', de:'Schwelle erreicht', fr:'seuil atteint', es:'umbral alcanzado', 'es-MX':'umbral alcanzado', it:'soglia raggiunta', pt:'limite atingido', ar:'بلغ الحدّ', hi:'सीमा पर पहुँचा', ja:'しきい値到達', ky:'чекке жетти', 'zh-Hant':'已達門檻' },
  badge_watching: { bg:'следи', ru:'следит', uk:'стежить', en:'watching', de:'beobachtet', fr:'surveille', es:'vigilando', 'es-MX':'vigilando', it:'in osservazione', pt:'vigiando', ar:'يراقب', hi:'निगरानी में', ja:'監視中', ky:'көзөмөлдөөдө', 'zh-Hant':'監看中' },

  // --- Долна навигация ---
  nav_dashboard: { bg:'Табло', ru:'Панель', uk:'Панель', en:'Dashboard', de:'Dashboard', fr:'Tableau', es:'Panel', 'es-MX':'Panel', it:'Dashboard', pt:'Painel', ar:'اللوحة', hi:'डैशबोर्ड', ja:'ダッシュボード', ky:'Панель', 'zh-Hant':'儀表板' },
  nav_settings: { bg:'Настройки', ru:'Настройки', uk:'Налаштування', en:'Settings', de:'Einstellungen', fr:'Réglages', es:'Ajustes', 'es-MX':'Ajustes', it:'Impostazioni', pt:'Configurações', ar:'الإعدادات', hi:'सेटिंग्स', ja:'設定', ky:'Жөндөөлөр', 'zh-Hant':'設定' },
  nav_permissions: { bg:'Разрешения', ru:'Разрешения', uk:'Дозволи', en:'Permissions', de:'Berechtigungen', fr:'Autorisations', es:'Permisos', 'es-MX':'Permisos', it:'Permessi', pt:'Permissões', ar:'الأذونات', hi:'अनुमतियाँ', ja:'権限', ky:'Уруксаттар', 'zh-Hant':'權限' },

  // --- Известия и журнал на планировчика ---
  notif_title: { bg:'Цена-робот: праг достигнат', ru:'Цена-робот: порог достигнут', uk:'Цінова-стежка: поріг досягнуто', en:'Price-Watch Bot: threshold reached', de:'Preis-Robot: Schwelle erreicht', fr:'Robot des prix : seuil atteint', es:'Robot de precios: umbral alcanzado', 'es-MX':'Robot de precios: umbral alcanzado', it:'Robot dei prezzi: soglia raggiunta', pt:'Robô de preços: limite atingido', ar:'روبوت الأسعار: بلغ الحدّ', hi:'मूल्य-निगरानी बॉट: सीमा पर पहुँचा', ja:'価格ウォッチボット：しきい値到達', ky:'Баа-робот: чекке жетти', 'zh-Hant':'價格監看機器人：已達門檻' },
  notif_body: { bg:'{0} — сега {1}', ru:'{0} — сейчас {1}', uk:'{0} — зараз {1}', en:'{0} — now {1}', de:'{0} — jetzt {1}', fr:'{0} — maintenant {1}', es:'{0} — ahora {1}', 'es-MX':'{0} — ahora {1}', it:'{0} — ora {1}', pt:'{0} — agora {1}', ar:'{0} — الآن {1}', hi:'{0} — अभी {1}', ja:'{0} — 現在 {1}', ky:'{0} — азыр {1}', 'zh-Hant':'{0} — 目前 {1}' },
  log_hit: { bg:'🔔 {0} достигнат — стойност {1}', ru:'🔔 {0} достигнут — значение {1}', uk:'🔔 {0} досягнуто — значення {1}', en:'🔔 {0} reached — value {1}', de:'🔔 {0} erreicht — Wert {1}', fr:'🔔 {0} atteint — valeur {1}', es:'🔔 {0} alcanzado — valor {1}', 'es-MX':'🔔 {0} alcanzado — valor {1}', it:'🔔 {0} raggiunto — valore {1}', pt:'🔔 {0} atingido — valor {1}', ar:'🔔 {0} تحقق — القيمة {1}', hi:'🔔 {0} पहुँचा — मान {1}', ja:'🔔 {0} 到達 — 値 {1}', ky:'🔔 {0} жетти — маани {1}', 'zh-Hant':'🔔 {0} 已達 — 數值 {1}' },
  log_error: { bg:'⚠️ {0}: {1}', ru:'⚠️ {0}: {1}', uk:'⚠️ {0}: {1}', en:'⚠️ {0}: {1}', de:'⚠️ {0}: {1}', fr:'⚠️ {0} : {1}', es:'⚠️ {0}: {1}', 'es-MX':'⚠️ {0}: {1}', it:'⚠️ {0}: {1}', pt:'⚠️ {0}: {1}', ar:'⚠️ {0}: {1}', hi:'⚠️ {0}: {1}', ja:'⚠️ {0}：{1}', ky:'⚠️ {0}: {1}', 'zh-Hant':'⚠️ {0}：{1}' },
  log_started: { bg:'▶️ Роботът е пуснат', ru:'▶️ Робот запущен', uk:'▶️ Робота запущено', en:'▶️ Robot started', de:'▶️ Roboter gestartet', fr:'▶️ Robot démarré', es:'▶️ Robot iniciado', 'es-MX':'▶️ Robot iniciado', it:'▶️ Robot avviato', pt:'▶️ Robô iniciado', ar:'▶️ تم تشغيل الروبوت', hi:'▶️ बॉट चालू हुआ', ja:'▶️ ロボットを開始', ky:'▶️ Робот иштеди', 'zh-Hant':'▶️ 機器人已啟動' },
  log_stopped: { bg:'⏸️ Роботът е спрян', ru:'⏸️ Робот остановлен', uk:'⏸️ Робота зупинено', en:'⏸️ Robot stopped', de:'⏸️ Roboter gestoppt', fr:'⏸️ Robot arrêté', es:'⏸️ Robot detenido', 'es-MX':'⏸️ Robot detenido', it:'⏸️ Robot fermato', pt:'⏸️ Robô parado', ar:'⏸️ تم إيقاف الروبوت', hi:'⏸️ बॉट रुका', ja:'⏸️ ロボットを停止', ky:'⏸️ Робот токтотулду', 'zh-Hant':'⏸️ 機器人已停止' },
  log_manual_check: { bg:'🔄 Ръчна проверка…', ru:'🔄 Ручная проверка…', uk:'🔄 Ручна перевірка…', en:'🔄 Manual check…', de:'🔄 Manuelle Prüfung…', fr:'🔄 Vérification manuelle…', es:'🔄 Comprobación manual…', 'es-MX':'🔄 Revisión manual…', it:'🔄 Controllo manuale…', pt:'🔄 Verificação manual…', ar:'🔄 فحص يدوي…', hi:'🔄 मैनुअल जाँच…', ja:'🔄 手動チェック…', ky:'🔄 Кол менен текшерүү…', 'zh-Hant':'🔄 手動檢查…' },
  err_generic: { bg:'грешка', ru:'ошибка', uk:'помилка', en:'error', de:'Fehler', fr:'erreur', es:'error', 'es-MX':'error', it:'errore', pt:'erro', ar:'خطأ', hi:'त्रुटि', ja:'エラー', ky:'ката', 'zh-Hant':'錯誤' },

  // --- Стартова грешка (main.js) ---
  boot_error: { bg:'Стартова грешка: {0}', ru:'Ошибка запуска: {0}', uk:'Помилка запуску: {0}', en:'Startup error: {0}', de:'Startfehler: {0}', fr:'Erreur de démarrage : {0}', es:'Error de inicio: {0}', 'es-MX':'Error de inicio: {0}', it:'Errore di avvio: {0}', pt:'Erro de inicialização: {0}', ar:'خطأ في بدء التشغيل: {0}', hi:'स्टार्टअप त्रुटि: {0}', ja:'起動エラー: {0}', ky:'Баштоо катасы: {0}', 'zh-Hant':'啟動錯誤：{0}' },
  err_unknown: { bg:'неизвестна', ru:'неизвестная', uk:'невідома', en:'unknown', de:'unbekannt', fr:'inconnue', es:'desconocido', 'es-MX':'desconocido', it:'sconosciuto', pt:'desconhecido', ar:'غير معروف', hi:'अज्ञात', ja:'不明', ky:'белгисиз', 'zh-Hant':'未知' },

  // --- Грешки при четене на цени (api.js) ---
  err_unknown_symbol: { bg:'Непознат символ: {0}', ru:'Неизвестный символ: {0}', uk:'Невідомий символ: {0}', en:'Unknown symbol: {0}', de:'Unbekanntes Symbol: {0}', fr:'Symbole inconnu : {0}', es:'Símbolo desconocido: {0}', 'es-MX':'Símbolo desconocido: {0}', it:'Simbolo sconosciuto: {0}', pt:'Símbolo desconhecido: {0}', ar:'رمز غير معروف: {0}', hi:'अज्ञात प्रतीक: {0}', ja:'不明なシンボル: {0}', ky:'Белгисиз символ: {0}', 'zh-Hant':'未知代號：{0}' },
  err_bad_value: { bg:'лоша стойност', ru:'неверное значение', uk:'неправильне значення', en:'bad value', de:'ungültiger Wert', fr:'valeur incorrecte', es:'valor incorrecto', 'es-MX':'valor incorrecto', it:'valore non valido', pt:'valor inválido', ar:'قيمة غير صالحة', hi:'गलत मान', ja:'不正な値', ky:'жараксыз маани', 'zh-Hant':'數值無效' },
  err_no_price: { bg:'Няма цена за {0}', ru:'Нет цены для {0}', uk:'Немає ціни для {0}', en:'No price for {0}', de:'Kein Preis für {0}', fr:'Aucun prix pour {0}', es:'Sin precio para {0}', 'es-MX':'Sin precio para {0}', it:'Nessun prezzo per {0}', pt:'Sem preço para {0}', ar:'لا سعر لـ {0}', hi:'{0} के लिए कोई कीमत नहीं', ja:'{0} の価格がありません', ky:'{0} үчүн баа жок', 'zh-Hant':'{0} 無價格' },
  err_fx_unavailable: { bg:'FX недостъпен', ru:'FX недоступен', uk:'FX недоступний', en:'FX unavailable', de:'FX nicht verfügbar', fr:'FX indisponible', es:'FX no disponible', 'es-MX':'FX no disponible', it:'FX non disponibile', pt:'FX indisponível', ar:'أسعار الصرف غير متاحة', hi:'FX उपलब्ध नहीं', ja:'為替が利用できません', ky:'FX жеткиликсиз', 'zh-Hant':'匯率不可用' },
  err_no_rate: { bg:'Няма курс за {0}', ru:'Нет курса для {0}', uk:'Немає курсу для {0}', en:'No rate for {0}', de:'Kein Kurs für {0}', fr:'Aucun taux pour {0}', es:'Sin tasa para {0}', 'es-MX':'Sin tasa para {0}', it:'Nessun tasso per {0}', pt:'Sem taxa para {0}', ar:'لا سعر صرف لـ {0}', hi:'{0} के लिए कोई दर नहीं', ja:'{0} のレートがありません', ky:'{0} үчүн курс жок', 'zh-Hant':'{0} 無匯率' },
  err_unknown_watch: { bg:'Непознат тип наблюдение', ru:'Неизвестный тип наблюдения', uk:'Невідомий тип спостереження', en:'Unknown watch type', de:'Unbekannter Beobachtungstyp', fr:'Type de surveillance inconnu', es:'Tipo de seguimiento desconocido', 'es-MX':'Tipo de seguimiento desconocido', it:'Tipo di monitoraggio sconosciuto', pt:'Tipo de monitoramento desconhecido', ar:'نوع مراقبة غير معروف', hi:'अज्ञात निगरानी प्रकार', ja:'不明なウォッチタイプ', ky:'Белгисиз көзөмөл түрү', 'zh-Hant':'未知的監看類型' }
};

let current = detect();

function detect() {
  try { const s = localStorage.getItem(LS_KEY); if (s && STR.app_name[s] != null) return s; } catch (e) {}
  return DEFAULT_LANG;
}

export function hasLangChosen() {
  try { return !!localStorage.getItem(LS_KEY); } catch (e) { return false; }
}
export function getLang() { return current; }
export function setLang(code) {
  if (STR.app_name[code] == null) return;
  current = code;
  try { localStorage.setItem(LS_KEY, code); } catch (e) {}
  applyDir();
}
export function isRTL() { return RTL_CODES.indexOf(current) > -1; }
export function applyDir() {
  try {
    document.documentElement.setAttribute('dir', isRTL() ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', current);
  } catch (e) {}
}
export function t(key) {
  const row = STR[key];
  if (!row) return key;
  if (row[current] != null) return row[current];
  if (row[DEFAULT_LANG] != null) return row[DEFAULT_LANG];
  if (row[FALLBACK_LANG] != null) return row[FALLBACK_LANG];
  return key;
}
export function tf(key, ...vals) {
  let s = t(key);
  vals.forEach((v, i) => { s = s.replace(new RegExp('\\{' + i + '\\}', 'g'), String(v)); });
  return s;
}
export { LANGUAGES, languageByCode };
