// Version: 1.0021
// „FAQ: забравена парола / ключ / ключалка" (09.09.2026, по искане): постоянно попълвана сбирка от ЛЕГАЛНИ съвети
// за възстановяване на достъп — акаунти (Google/Apple/Microsoft), телефон (официално нулиране), Windows/BitLocker,
// Wi-Fi/рутер, файлове (ZIP/PDF/Office), 2FA резервни кодове, крипто портфейли (seed фраза, Ledger/Trezor/MetaMask),
// физически ключалки (куфар TSA, катинар с код, велосипед), ключ за кола. За всяка тема: проверени официални източници
// (винаги с линк) + „най-новото от мрежата" — резултати от търсене (DuckDuckGo през relay), теглени ВЕДНЪЖ на пускане
// на приложението (политика на трафика) и пазени офлайн. Само собствени устройства/акаунти — без заобикаляне на чужди.
import { esc } from '../core/ui.js';
import { t, register, getLang } from '../core/i18n.js';

register({
  pf_title: { bg:'FAQ: забравена парола / ключ / ключалка', ru:'FAQ: забытый пароль / ключ / замок', uk:'FAQ: забутий пароль / ключ / замок', en:'FAQ: forgotten password / key / lock', de:'FAQ: Passwort / Schlüssel / Schloss vergessen', fr:'FAQ : mot de passe / clé / cadenas oublié', es:'FAQ: contraseña / llave / cerradura olvidada', 'es-MX':'FAQ: contraseña / llave / cerradura olvidada', it:'FAQ: password / chiave / lucchetto dimenticati', pt:'FAQ: palavra-passe / chave / cadeado esquecidos', ar:'الأسئلة الشائعة: نسيت كلمة المرور / المفتاح / القفل', hi:'FAQ: भूला पासवर्ड / चाबी / ताला', ja:'FAQ：パスワード・鍵・ロックを忘れた', ky:'FAQ: унутулган сырсөз / ачкыч / кулпу', 'zh-Hant':'FAQ：忘記密碼／鑰匙／鎖' },
  pf_hint: { bg:'Само законни начини за СОБСТВЕНИ акаунти, устройства и ключалки: официални процедури за възстановяване + най-новото от мрежата (с линк към източника). Обновява се веднъж при пускане на приложението и се пази офлайн.', ru:'Только законные способы для СОБСТВЕННЫХ аккаунтов, устройств и замков: официальные процедуры восстановления + свежее из сети (со ссылкой на источник). Обновляется раз при запуске и хранится офлайн.', uk:'Лише законні способи для ВЛАСНИХ акаунтів, пристроїв і замків: офіційні процедури відновлення + найновіше з мережі (з посиланням на джерело). Оновлюється раз при запуску і зберігається офлайн.', en:'Only lawful ways for YOUR OWN accounts, devices and locks: official recovery procedures + the latest from the web (always with a source link). Refreshed once per app launch and kept offline.', de:'Nur legale Wege für EIGENE Konten, Geräte und Schlösser: offizielle Wiederherstellung + Neues aus dem Netz (immer mit Quelle). Einmal pro Start aktualisiert, offline gespeichert.', fr:'Uniquement des moyens légaux pour VOS PROPRES comptes, appareils et cadenas : procédures officielles + nouveautés du web (toujours avec la source). Actualisé une fois par lancement, conservé hors ligne.', es:'Solo formas legales para TUS PROPIAS cuentas, dispositivos y cerraduras: procedimientos oficiales + lo último de la web (siempre con fuente). Se actualiza una vez por inicio y se guarda sin conexión.', 'es-MX':'Solo formas legales para TUS PROPIAS cuentas, dispositivos y cerraduras: procedimientos oficiales + lo último de la web (siempre con fuente). Se actualiza una vez por inicio y se guarda sin conexión.', it:'Solo modi legali per i TUOI account, dispositivi e lucchetti: procedure ufficiali + novità dal web (sempre con fonte). Aggiornato una volta per avvio, salvato offline.', pt:'Só formas legais para as SUAS contas, dispositivos e cadeados: procedimentos oficiais + o mais recente da web (sempre com fonte). Atualizado uma vez por arranque, guardado offline.', ar:'طرق قانونية فقط لحساباتك وأجهزتك وأقفالك الخاصة: إجراءات الاسترداد الرسمية + الأحدث من الويب (مع رابط المصدر دائماً). يُحدَّث مرة عند التشغيل ويُحفظ دون اتصال.', hi:'केवल आपके अपने खातों, डिवाइस और तालों के लिए वैध तरीके: आधिकारिक रिकवरी प्रक्रियाएँ + वेब से ताज़ा (हमेशा स्रोत लिंक के साथ)। हर लॉन्च पर एक बार अपडेट, ऑफ़लाइन सहेजा।', ja:'自分のアカウント・端末・鍵に限った合法的な方法のみ：公式の復旧手順＋ウェブの最新情報（必ず出典リンク付き）。起動ごとに一度更新し、オフライン保存。', ky:'ӨЗҮҢДҮН аккаунттарың, түзмөктөрүң жана кулпуларың үчүн мыйзамдуу жолдор гана: расмий калыбына келтирүү + тармактан жаңылары (булак шилтемеси менен). Ачылганда бир жолу жаңырат, офлайн сакталат.', 'zh-Hant':'僅限您自己的帳號、裝置與鎖的合法方式：官方恢復程序＋網路最新資訊（一律附來源連結）。每次啟動更新一次並離線保存。' },
  pf_official: { bg:'Официални източници', ru:'Официальные источники', uk:'Офіційні джерела', en:'Official sources', de:'Offizielle Quellen', fr:'Sources officielles', es:'Fuentes oficiales', 'es-MX':'Fuentes oficiales', it:'Fonti ufficiali', pt:'Fontes oficiais', ar:'مصادر رسمية', hi:'आधिकारिक स्रोत', ja:'公式ソース', ky:'Расмий булактар', 'zh-Hant':'官方來源' },
  pf_web: { bg:'Най-новото от мрежата', ru:'Свежее из сети', uk:'Найновіше з мережі', en:'Latest from the web', de:'Neues aus dem Netz', fr:'Nouveautés du web', es:'Lo último de la web', 'es-MX':'Lo último de la web', it:'Novità dal web', pt:'O mais recente da web', ar:'الأحدث من الويب', hi:'वेब से ताज़ा', ja:'ウェブの最新', ky:'Тармактан жаңылары', 'zh-Hant':'網路最新' },
  pf_loading: { bg:'Зареждане…', ru:'Загрузка…', uk:'Завантаження…', en:'Loading…', de:'Laden…', fr:'Chargement…', es:'Cargando…', 'es-MX':'Cargando…', it:'Caricamento…', pt:'A carregar…', ar:'جارٍ التحميل…', hi:'लोड हो रहा है…', ja:'読み込み中…', ky:'Жүктөлүүдө…', 'zh-Hant':'載入中…' },
  pf_none: { bg:'Няма нови резултати (офлайн?) — виж официалните източници.', ru:'Нет новых результатов (офлайн?) — см. официальные источники.', uk:'Немає нових результатів (офлайн?) — див. офіційні джерела.', en:'No new results (offline?) — see the official sources.', de:'Keine neuen Ergebnisse (offline?) — siehe offizielle Quellen.', fr:'Pas de nouveaux résultats (hors ligne ?) — voir les sources officielles.', es:'Sin resultados nuevos (¿sin conexión?) — mira las fuentes oficiales.', 'es-MX':'Sin resultados nuevos (¿sin conexión?) — mira las fuentes oficiales.', it:'Nessun nuovo risultato (offline?) — vedi le fonti ufficiali.', pt:'Sem novos resultados (offline?) — veja as fontes oficiais.', ar:'لا نتائج جديدة (دون اتصال؟) — انظر المصادر الرسمية.', hi:'कोई नया परिणाम नहीं (ऑफ़लाइन?) — आधिकारिक स्रोत देखें।', ja:'新しい結果なし（オフライン？）— 公式ソースをご覧ください。', ky:'Жаңы натыйжа жок (офлайн?) — расмий булактарды кара.', 'zh-Hant':'沒有新結果（離線？）— 請看官方來源。' },
  pf_updated: { bg:'обновено', ru:'обновлено', uk:'оновлено', en:'updated', de:'aktualisiert', fr:'mis à jour', es:'actualizado', 'es-MX':'actualizado', it:'aggiornato', pt:'atualizado', ar:'تم التحديث', hi:'अपडेट', ja:'更新', ky:'жаңырды', 'zh-Hant':'更新於' },
  pf_promo: { bg:'Пази паролите си сигурно: Pupikes Authenticator & Passwords (2FA кодове + пароли + крипто портфейли, внос от Chrome/Edge/Firefox).', ru:'Храните пароли безопасно: Pupikes Authenticator & Passwords (2FA-коды + пароли + крипто-кошельки, импорт из Chrome/Edge/Firefox).', uk:'Зберігайте паролі безпечно: Pupikes Authenticator & Passwords (2FA-коди + паролі + крипто-гаманці, імпорт із Chrome/Edge/Firefox).', en:'Keep your passwords safe: Pupikes Authenticator & Passwords (2FA codes + passwords + crypto wallets, import from Chrome/Edge/Firefox).', de:'Passwörter sicher aufbewahren: Pupikes Authenticator & Passwords (2FA-Codes + Passwörter + Krypto-Wallets, Import aus Chrome/Edge/Firefox).', fr:'Gardez vos mots de passe en sécurité : Pupikes Authenticator & Passwords (codes 2FA + mots de passe + portefeuilles crypto, import Chrome/Edge/Firefox).', es:'Guarda tus contraseñas con seguridad: Pupikes Authenticator & Passwords (códigos 2FA + contraseñas + carteras cripto, importación desde Chrome/Edge/Firefox).', 'es-MX':'Guarda tus contraseñas con seguridad: Pupikes Authenticator & Passwords (códigos 2FA + contraseñas + carteras cripto, importación desde Chrome/Edge/Firefox).', it:'Conserva le password in sicurezza: Pupikes Authenticator & Passwords (codici 2FA + password + wallet crypto, importazione da Chrome/Edge/Firefox).', pt:'Guarde as palavras-passe em segurança: Pupikes Authenticator & Passwords (códigos 2FA + palavras-passe + carteiras cripto, importação de Chrome/Edge/Firefox).', ar:'احفظ كلمات مرورك بأمان: Pupikes Authenticator & Passwords (رموز 2FA + كلمات مرور + محافظ رقمية، استيراد من Chrome/Edge/Firefox).', hi:'पासवर्ड सुरक्षित रखें: Pupikes Authenticator & Passwords (2FA कोड + पासवर्ड + क्रिप्टो वॉलेट, Chrome/Edge/Firefox से आयात)।', ja:'パスワードを安全に：Pupikes Authenticator & Passwords（2FAコード＋パスワード＋暗号資産ウォレット、Chrome/Edge/Firefoxから取り込み）。', ky:'Сырсөздөрүңдү коопсуз сакта: Pupikes Authenticator & Passwords (2FA коддор + сырсөздөр + крипто капчыктар, Chrome/Edge/Firefoxтон импорт).', 'zh-Hant':'安全保存密碼：Pupikes Authenticator & Passwords（2FA 驗證碼＋密碼＋加密錢包，可從 Chrome/Edge/Firefox 匯入）。' }
});

export const title = 'FAQ: forgotten password / key / lock';

// Теми: заглавие (bg/ru/en; другите езици → en), заявка за търсене, официални източници (винаги с линк).
const TOPICS = [
  { id: 'google', t: { bg: 'Забравена парола за Google акаунт', ru: 'Забыт пароль от аккаунта Google', en: 'Forgotten Google account password' }, q: 'recover Google account forgotten password official', src: [['Google Account Recovery', 'https://accounts.google.com/signin/recovery'], ['Google Help: Fix problems signing in', 'https://support.google.com/accounts/answer/7682439']] },
  { id: 'apple', t: { bg: 'Забравена парола за Apple ID / iPhone код', ru: 'Забыт пароль Apple ID / код iPhone', en: 'Forgotten Apple ID password / iPhone passcode' }, q: 'forgot iPhone passcode reset official Apple support', src: [['iForgot (Apple ID)', 'https://iforgot.apple.com/'], ['Apple Support: If you forgot your iPhone passcode', 'https://support.apple.com/HT204306']] },
  { id: 'microsoft', t: { bg: 'Забравена парола за Microsoft / Windows акаунт', ru: 'Забыт пароль Microsoft / Windows', en: 'Forgotten Microsoft / Windows account password' }, q: 'reset forgotten Windows password Microsoft account official', src: [['Microsoft account recovery', 'https://account.live.com/password/reset'], ['Microsoft Support: Reset a Windows local account password', 'https://support.microsoft.com/windows/reset-your-windows-local-account-password']] },
  { id: 'android', t: { bg: 'Заключен Android телефон (собствен)', ru: 'Заблокирован свой Android', en: 'Locked Android phone (your own)' }, q: 'forgot Android screen lock official reset Find My Device', src: [['Google Find My Device', 'https://www.google.com/android/find'], ['Google Help: Can\'t unlock your Android device', 'https://support.google.com/android/answer/7663172'], ['Huawei: Forgot lock screen password', 'https://consumer.huawei.com/en/support/content/en-us00695098/']] },
  { id: 'wifi', t: { bg: 'Забравена Wi-Fi парола / рутер', ru: 'Забыт пароль Wi-Fi / роутер', en: 'Forgotten Wi-Fi password / router' }, q: 'find saved wifi password router reset official', src: [['Microsoft: Find your Wi-Fi network password', 'https://support.microsoft.com/windows/find-your-wi-fi-network-password-in-windows'], ['Apple: See saved Wi-Fi passwords', 'https://support.apple.com/guide/iphone/see-your-wi-fi-network-password-iph42a6fe5e9/ios']] },
  { id: 'bitlocker', t: { bg: 'BitLocker ключ за възстановяване', ru: 'Ключ восстановления BitLocker', en: 'BitLocker recovery key' }, q: 'find BitLocker recovery key Microsoft account', src: [['Microsoft: Find your BitLocker recovery key', 'https://support.microsoft.com/windows/finding-your-bitlocker-recovery-key-in-windows']] },
  { id: 'twofa', t: { bg: 'Загубен 2FA / резервни кодове', ru: 'Потерян 2FA / резервные коды', en: 'Lost 2FA / backup codes' }, q: 'lost two-factor authentication device recovery codes', src: [['Google: 2-Step Verification backup codes', 'https://support.google.com/accounts/answer/1187538'], ['GitHub: Recovering your account if you lose 2FA', 'https://docs.github.com/authentication/securing-your-account-with-two-factor-authentication-2fa/recovering-your-account-if-you-lose-your-2fa-credentials']] },
  { id: 'crypto', t: { bg: 'Крипто портфейл: seed фраза / ключ', ru: 'Крипто-кошелёк: seed-фраза / ключ', en: 'Crypto wallet: seed phrase / key' }, q: 'recover crypto wallet seed phrase official guide', src: [['MetaMask: Secret Recovery Phrase', 'https://support.metamask.io/privacy-and-security/how-to-reveal-your-secret-recovery-phrase/'], ['Ledger: Recovery phrase', 'https://support.ledger.com/article/4415198323089-zd'], ['Trezor: Recovery seed', 'https://trezor.io/learn/a/what-is-a-recovery-seed']] },
  { id: 'files', t: { bg: 'Забравена парола на файл (ZIP / PDF / Office)', ru: 'Забыт пароль файла (ZIP / PDF / Office)', en: 'Forgotten file password (ZIP / PDF / Office)' }, q: 'forgot password protected Excel PDF ZIP own file recover', src: [['Microsoft: Protect a document with a password', 'https://support.microsoft.com/office/protect-a-document-with-a-password-05084cc3-300d-4c1a-8416-38d3e37d6826'], ['Adobe: Remove password from PDF', 'https://helpx.adobe.com/acrobat/using/securing-pdfs-passwords.html']] },
  { id: 'tsa', t: { bg: 'Куфар с TSA ключалка (забравен код)', ru: 'Чемодан с TSA-замком (забыт код)', en: 'Suitcase TSA lock (forgotten code)' }, q: 'reset TSA luggage lock forgotten combination manufacturer', src: [['Samsonite: Reset your lock', 'https://www.samsonite.com/luggage-lock-instructions'], ['Travel Sentry FAQ', 'https://www.travelsentry.org/faq/']] },
  { id: 'padlock', t: { bg: 'Катинар / велосипедна ключалка с код', ru: 'Кодовый замок / велозамок', en: 'Combination padlock / bike lock' }, q: 'reset combination padlock bike lock forgotten code manufacturer', src: [['Master Lock: Lost combinations', 'https://www.masterlock.com/support/category/lost-combinations'], ['ABUS: Combination locks FAQ', 'https://www.abus.com/eng/Service/FAQ']] },
  { id: 'car', t: { bg: 'Ключ за кола (батерия / загубен)', ru: 'Ключ от машины (батарейка / потерян)', en: 'Car key (battery / lost)' }, q: 'car key fob battery replace lost key dealer official', src: [['AA: Lost car keys', 'https://www.theaa.com/breakdown-cover/advice/lost-car-keys']] },
  { id: 'social', t: { bg: 'Facebook / Instagram / X — възстановяване', ru: 'Facebook / Instagram / X — восстановление', en: 'Facebook / Instagram / X — recovery' }, q: 'recover hacked forgotten Facebook Instagram account official help', src: [['Facebook: Recover your account', 'https://www.facebook.com/login/identify'], ['Instagram Help: Login', 'https://help.instagram.com/374546259294234'], ['X Help: Password reset', 'https://help.x.com/managing-your-account/forgotten-or-lost-password-reset']] },
  { id: 'bank', t: { bg: 'Банкиране / карта PIN', ru: 'Банкинг / PIN карты', en: 'Banking / card PIN' }, q: 'forgot bank card PIN reset official', src: [['Visa: Forgot your PIN?', 'https://www.visa.com/en_us/support/consumer/security.html']] }
];
const RELAY = 'https://pupikes.app/api/relay/get?url=';
const LS = 'pwfaq.v1';
let session = null;   // { ts, results: { topicId: [{title,url}] } } — веднъж на пускане
function load() { try { return JSON.parse(localStorage.getItem(LS) || 'null'); } catch (_) { return null; } }
async function getText(url) {
  const CH = (window.Capacitor && window.Capacitor.Plugins && window.Capacitor.Plugins.CapacitorHttp) || window.CapacitorHttp;
  const tmo = new Promise((_, rej) => setTimeout(() => rej(new Error('timeout')), 15000));
  if (CH && CH.get) { const r = await Promise.race([CH.get({ url, headers: { Accept: 'text/html' } }), tmo]); return typeof r.data === 'string' ? r.data : ''; }
  const r = await Promise.race([fetch(url), tmo]); return await r.text();
}
async function searchTopic(q) {
  const html = await getText(RELAY + encodeURIComponent('https://html.duckduckgo.com/html/?q=' + encodeURIComponent(q)));
  const out = []; const re = /class="result__a"[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/g; let m;
  while ((m = re.exec(html)) && out.length < 6) { let u = m[1]; const uddg = u.match(/uddg=([^&]+)/); if (uddg) u = decodeURIComponent(uddg[1]); const title = m[2].replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim(); if (/^https?:/.test(u) && title) out.push({ title, url: u }); }
  return out;
}
// Веднъж на пускане: всички теми (последователно, щадящо); резултатът е снимка в localStorage за офлайн.
export async function refreshOnce() {
  if (session) return session;
  session = load() || { ts: 0, results: {} };
  const fresh = { ts: Date.now(), results: Object.assign({}, session.results) };
  for (const tp of TOPICS) { try { const r = await searchTopic(tp.q); if (r.length) fresh.results[tp.id] = r; } catch (_) {} }
  session = fresh; try { localStorage.setItem(LS, JSON.stringify(fresh)); } catch (_) {}
  return session;
}
function openUrl(u) { try { const C = window.Capacitor && window.Capacitor.Plugins && window.Capacitor.Plugins.Browser; if (C && C.open) { C.open({ url: u }); return; } } catch (_) {} window.open(u, '_blank'); }

export function render(root) {
  const lg = getLang(); const tt = (tp) => tp.t[lg] || tp.t[String(lg).split('-')[0]] || tp.t.en;
  root.innerHTML = `
    <div class="tool-card">
      <p class="hint">${esc(t('pf_hint'))}</p>
      <div style="padding:8px 10px;border:1px solid rgba(127,127,127,.35);border-radius:10px;margin-bottom:8px;font-size:13px">🔐 ${esc(t('pf_promo'))} <a href="https://pupikes.app/" id="pf-promo">pupikes.app</a></div>
      <div id="pf-list"></div>
    </div>`;
  root.querySelector('#pf-promo').addEventListener('click', (e) => { e.preventDefault(); openUrl('https://pupikes.app/'); });
  const list = root.querySelector('#pf-list');
  const cached = load();
  TOPICS.forEach((tp) => {
    const d = document.createElement('details'); d.style.cssText = 'margin:6px 0;border:1px solid rgba(127,127,127,.3);border-radius:10px;padding:6px 10px';
    d.innerHTML = `<summary style="cursor:pointer;font-weight:600">${esc(tt(tp))}</summary>
      <div style="margin-top:6px"><b>${esc(t('pf_official'))}:</b><ul style="margin:4px 0 0 18px">${tp.src.map(([n, u]) => `<li><a href="${esc(u)}" data-u="${esc(u)}">${esc(n)}</a></li>`).join('')}</ul></div>
      <div style="margin-top:6px"><b>${esc(t('pf_web'))}:</b> <span class="hint" data-ts></span><ul style="margin:4px 0 0 18px" data-web>${(cached && cached.results[tp.id] || []).map((r) => `<li><a href="${esc(r.url)}" data-u="${esc(r.url)}">${esc(r.title)}</a></li>`).join('') || `<li class="hint">${esc(t('pf_loading'))}</li>`}</ul></div>`;
    list.appendChild(d);
  });
  list.addEventListener('click', (e) => { const a = e.target.closest('a[data-u]'); if (a) { e.preventDefault(); openUrl(a.getAttribute('data-u')); } });
  refreshOnce().then((s) => {
    const nodes = list.querySelectorAll('details');
    TOPICS.forEach((tp, i) => { const ul = nodes[i].querySelector('[data-web]'); const ts = nodes[i].querySelector('[data-ts]'); const r = s.results[tp.id] || []; ts.textContent = s.ts ? '(' + t('pf_updated') + ' ' + new Date(s.ts).toLocaleDateString() + ')' : ''; ul.innerHTML = r.length ? r.map((x) => `<li><a href="${esc(x.url)}" data-u="${esc(x.url)}">${esc(x.title)}</a></li>`).join('') : `<li class="hint">${esc(t('pf_none'))}</li>`; });
  });
}
