// i18n.js — преводен слой за „KCY Authenticator" на 15-те езика на екосистемата.
// Език по подразбиране: руски (до избор от потребителя при първо стартиране).
import { LANGUAGES, languageByCode, RTL_CODES } from './languages.js';

const LS_KEY = 'kcyauth.lang';
const DEFAULT_LANG = 'ru';
const FALLBACK_LANG = 'en';

const STR = {
  pick_lang: { bg:'Избери език', ru:'Выберите язык', uk:'Виберіть мову', en:'Choose language', de:'Sprache wählen', fr:'Choisir la langue', es:'Elegir idioma', 'es-MX':'Elegir idioma', it:'Scegli la lingua', pt:'Escolher idioma', ar:'اختر اللغة', hi:'भाषा चुनें', ja:'言語を選択', ky:'Тилди тандаңыз', 'zh-Hant':'選擇語言' },
  lang_btn: { bg:'🌐 Език', ru:'🌐 Язык', uk:'🌐 Мова', en:'🌐 Language', de:'🌐 Sprache', fr:'🌐 Langue', es:'🌐 Idioma', 'es-MX':'🌐 Idioma', it:'🌐 Lingua', pt:'🌐 Idioma', ar:'🌐 اللغة', hi:'🌐 भाषा', ja:'🌐 言語', ky:'🌐 Тил', 'zh-Hant':'🌐 語言' },

  setup_title: { bg:'Създай master парола', ru:'Создайте мастер-пароль', uk:'Створіть майстер-пароль', en:'Create a master password', de:'Master-Passwort erstellen', fr:'Créer un mot de passe maître', es:'Crea una contraseña maestra', 'es-MX':'Crea una contraseña maestra', it:'Crea una password principale', pt:'Crie uma senha mestra', ar:'أنشئ كلمة مرور رئيسية', hi:'मास्टर पासवर्ड बनाएं', ja:'マスターパスワードを作成', ky:'Башкы сырсөз түзүңүз', 'zh-Hant':'建立主密碼' },
  setup_desc: { bg:'Сейфът се шифрова с тази парола. Без нея няма достъп до кодовете.', ru:'Хранилище шифруется этим паролем. Без него доступа к кодам нет.', uk:'Сховище шифрується цим паролем. Без нього доступу до кодів немає.', en:'The vault is encrypted with this password. Without it there is no access to your codes.', de:'Der Tresor wird mit diesem Passwort verschlüsselt. Ohne es gibt es keinen Zugriff auf die Codes.', fr:'Le coffre est chiffré avec ce mot de passe. Sans lui, aucun accès aux codes.', es:'La bóveda se cifra con esta contraseña. Sin ella no hay acceso a tus códigos.', 'es-MX':'La bóveda se cifra con esta contraseña. Sin ella no hay acceso a tus códigos.', it:'La cassaforte è cifrata con questa password. Senza, niente accesso ai codici.', pt:'O cofre é cifrado com esta senha. Sem ela não há acesso aos códigos.', ar:'يُشفَّر الخزنة بهذه الكلمة. بدونها لا وصول إلى الرموز.', hi:'वॉल्ट इस पासवर्ड से एन्क्रिप्ट होता है। इसके बिना कोड तक पहुँच नहीं।', ja:'保管庫はこのパスワードで暗号化されます。これがないとコードにアクセスできません。', ky:'Сейф ушул сырсөз менен шифрленет. Ансыз коддорго мүмкүндүк жок.', 'zh-Hant':'保險庫以此密碼加密。沒有它就無法存取代碼。' },
  password: { bg:'Парола', ru:'Пароль', uk:'Пароль', en:'Password', de:'Passwort', fr:'Mot de passe', es:'Contraseña', 'es-MX':'Contraseña', it:'Password', pt:'Senha', ar:'كلمة المرور', hi:'पासवर्ड', ja:'パスワード', ky:'Сырсөз', 'zh-Hant':'密碼' },
  confirm_password: { bg:'Повтори паролата', ru:'Повторите пароль', uk:'Повторіть пароль', en:'Repeat password', de:'Passwort wiederholen', fr:'Répéter le mot de passe', es:'Repite la contraseña', 'es-MX':'Repite la contraseña', it:'Ripeti la password', pt:'Repita a senha', ar:'كرّر كلمة المرور', hi:'पासवर्ड दोहराएं', ja:'パスワードを再入力', ky:'Сырсөздү кайталаңыз', 'zh-Hant':'再次輸入密碼' },
  password_min: { bg:'Поне 6 символа', ru:'Минимум 6 символов', uk:'Щонайменше 6 символів', en:'At least 6 characters', de:'Mindestens 6 Zeichen', fr:'Au moins 6 caractères', es:'Al menos 6 caracteres', 'es-MX':'Al menos 6 caracteres', it:'Almeno 6 caratteri', pt:'Pelo menos 6 caracteres', ar:'٦ أحرف على الأقل', hi:'कम से कम 6 अक्षर', ja:'6文字以上', ky:'Кеминде 6 белги', 'zh-Hant':'至少 6 個字元' },
  passwords_mismatch: { bg:'Паролите не съвпадат', ru:'Пароли не совпадают', uk:'Паролі не збігаються', en:'Passwords do not match', de:'Passwörter stimmen nicht überein', fr:'Les mots de passe ne correspondent pas', es:'Las contraseñas no coinciden', 'es-MX':'Las contraseñas no coinciden', it:'Le password non coincidono', pt:'As senhas não coincidem', ar:'كلمتا المرور غير متطابقتين', hi:'पासवर्ड मेल नहीं खाते', ja:'パスワードが一致しません', ky:'Сырсөздөр дал келбейт', 'zh-Hant':'密碼不一致' },
  create_vault: { bg:'Създай сейф', ru:'Создать хранилище', uk:'Створити сховище', en:'Create vault', de:'Tresor erstellen', fr:'Créer le coffre', es:'Crear bóveda', 'es-MX':'Crear bóveda', it:'Crea cassaforte', pt:'Criar cofre', ar:'أنشئ الخزنة', hi:'वॉल्ट बनाएं', ja:'保管庫を作成', ky:'Сейф түзүү', 'zh-Hant':'建立保險庫' },

  unlock_title: { bg:'Отключи сейфа', ru:'Разблокируйте хранилище', uk:'Розблокуйте сховище', en:'Unlock the vault', de:'Tresor entsperren', fr:'Déverrouiller le coffre', es:'Desbloquea la bóveda', 'es-MX':'Desbloquea la bóveda', it:'Sblocca la cassaforte', pt:'Desbloqueie o cofre', ar:'افتح الخزنة', hi:'वॉल्ट अनलॉक करें', ja:'保管庫を解除', ky:'Сейфти ачуу', 'zh-Hant':'解鎖保險庫' },
  unlock: { bg:'Отключи', ru:'Разблокировать', uk:'Розблокувати', en:'Unlock', de:'Entsperren', fr:'Déverrouiller', es:'Desbloquear', 'es-MX':'Desbloquear', it:'Sblocca', pt:'Desbloquear', ar:'افتح', hi:'अनलॉक', ja:'解除', ky:'Ачуу', 'zh-Hant':'解鎖' },
  wrong_password: { bg:'Грешна парола', ru:'Неверный пароль', uk:'Невірний пароль', en:'Wrong password', de:'Falsches Passwort', fr:'Mot de passe incorrect', es:'Contraseña incorrecta', 'es-MX':'Contraseña incorrecta', it:'Password errata', pt:'Senha incorreta', ar:'كلمة مرور خاطئة', hi:'गलत पासवर्ड', ja:'パスワードが違います', ky:'Сырсөз туура эмес', 'zh-Hant':'密碼錯誤' },
  use_biometric: { bg:'Отключи с пръстов отпечатък', ru:'Разблокировать отпечатком', uk:'Розблокувати відбитком', en:'Unlock with fingerprint', de:'Mit Fingerabdruck entsperren', fr:'Déverrouiller par empreinte', es:'Desbloquear con huella', 'es-MX':'Desbloquear con huella', it:'Sblocca con impronta', pt:'Desbloquear com digital', ar:'افتح ببصمة الإصبع', hi:'फिंगरप्रिंट से अनलॉक', ja:'指紋で解除', ky:'Манжа изи менен ачуу', 'zh-Hant':'用指紋解鎖' },

  empty_title: { bg:'Няма акаунти', ru:'Нет аккаунтов', uk:'Немає акаунтів', en:'No accounts', de:'Keine Konten', fr:'Aucun compte', es:'Sin cuentas', 'es-MX':'Sin cuentas', it:'Nessun account', pt:'Sem contas', ar:'لا حسابات', hi:'कोई खाता नहीं', ja:'アカウントなし', ky:'Аккаунттар жок', 'zh-Hant':'沒有帳戶' },
  empty_desc: { bg:'Добави първия си акаунт с бутона +', ru:'Добавьте первый аккаунт кнопкой +', uk:'Додайте перший акаунт кнопкою +', en:'Add your first account with the + button', de:'Füge dein erstes Konto mit + hinzu', fr:'Ajoute ton premier compte avec le bouton +', es:'Añade tu primera cuenta con el botón +', 'es-MX':'Agrega tu primera cuenta con el botón +', it:'Aggiungi il primo account con il pulsante +', pt:'Adicione sua primeira conta com o botão +', ar:'أضف حسابك الأول بزر +', hi:'+ बटन से अपना पहला खाता जोड़ें', ja:'＋ボタンで最初のアカウントを追加', ky:'+ баскычы менен биринчи аккаунтту кошуңуз', 'zh-Hant':'用 + 按鈕新增第一個帳戶' },
  search_ph: { bg:'Търси…', ru:'Поиск…', uk:'Пошук…', en:'Search…', de:'Suchen…', fr:'Rechercher…', es:'Buscar…', 'es-MX':'Buscar…', it:'Cerca…', pt:'Buscar…', ar:'بحث…', hi:'खोजें…', ja:'検索…', ky:'Издөө…', 'zh-Hant':'搜尋…' },
  add_account: { bg:'Добави акаунт', ru:'Добавить аккаунт', uk:'Додати акаунт', en:'Add account', de:'Konto hinzufügen', fr:'Ajouter un compte', es:'Añadir cuenta', 'es-MX':'Agregar cuenta', it:'Aggiungi account', pt:'Adicionar conta', ar:'أضف حسابًا', hi:'खाता जोड़ें', ja:'アカウントを追加', ky:'Аккаунт кошуу', 'zh-Hant':'新增帳戶' },
  copied: { bg:'Копирано', ru:'Скопировано', uk:'Скопійовано', en:'Copied', de:'Kopiert', fr:'Copié', es:'Copiado', 'es-MX':'Copiado', it:'Copiato', pt:'Copiado', ar:'تم النسخ', hi:'कॉपी हो गया', ja:'コピーしました', ky:'Көчүрүлдү', 'zh-Hant':'已複製' },
  tap_copy: { bg:'Докосни за копиране', ru:'Нажмите, чтобы скопировать', uk:'Натисніть, щоб скопіювати', en:'Tap to copy', de:'Zum Kopieren tippen', fr:'Touchez pour copier', es:'Toca para copiar', 'es-MX':'Toca para copiar', it:'Tocca per copiare', pt:'Toque para copiar', ar:'انقر للنسخ', hi:'कॉपी के लिए टैप करें', ja:'タップしてコピー', ky:'Көчүрүү үчүн басыңыз', 'zh-Hant':'點擊以複製' },
  next_code: { bg:'Следващ код', ru:'Следующий код', uk:'Наступний код', en:'Next code', de:'Nächster Code', fr:'Code suivant', es:'Código siguiente', 'es-MX':'Código siguiente', it:'Codice successivo', pt:'Próximo código', ar:'الرمز التالي', hi:'अगला कोड', ja:'次のコード', ky:'Кийинки код', 'zh-Hant':'下一個代碼' },

  add_title: { bg:'Нов акаунт', ru:'Новый аккаунт', uk:'Новий акаунт', en:'New account', de:'Neues Konto', fr:'Nouveau compte', es:'Nueva cuenta', 'es-MX':'Nueva cuenta', it:'Nuovo account', pt:'Nova conta', ar:'حساب جديد', hi:'नया खाता', ja:'新しいアカウント', ky:'Жаңы аккаунт', 'zh-Hant':'新帳戶' },
  scan_qr: { bg:'Сканирай QR код', ru:'Сканировать QR-код', uk:'Сканувати QR-код', en:'Scan QR code', de:'QR-Code scannen', fr:'Scanner un QR code', es:'Escanear código QR', 'es-MX':'Escanear código QR', it:'Scansiona QR code', pt:'Escanear QR code', ar:'امسح رمز QR', hi:'QR कोड स्कैन करें', ja:'QRコードをスキャン', ky:'QR кодду скандоо', 'zh-Hant':'掃描 QR 碼' },
  enter_manually: { bg:'Въведи ръчно', ru:'Ввести вручную', uk:'Ввести вручну', en:'Enter manually', de:'Manuell eingeben', fr:'Saisir manuellement', es:'Ingresar manualmente', 'es-MX':'Ingresar manualmente', it:'Inserisci manualmente', pt:'Inserir manualmente', ar:'إدخال يدوي', hi:'मैन्युअल रूप से दर्ज करें', ja:'手動で入力', ky:'Кол менен киргизүү', 'zh-Hant':'手動輸入' },
  paste_uri: { bg:'или постави otpauth:// линк', ru:'или вставьте ссылку otpauth://', uk:'або вставте посилання otpauth://', en:'or paste an otpauth:// link', de:'oder otpauth://-Link einfügen', fr:'ou collez un lien otpauth://', es:'o pega un enlace otpauth://', 'es-MX':'o pega un enlace otpauth://', it:'o incolla un link otpauth://', pt:'ou cole um link otpauth://', ar:'أو الصق رابط ‎otpauth://', hi:'या otpauth:// लिंक पेस्ट करें', ja:'または otpauth:// リンクを貼り付け', ky:'же otpauth:// шилтемесин коюңуз', 'zh-Hant':'或貼上 otpauth:// 連結' },
  issuer: { bg:'Издател (напр. Google)', ru:'Сервис (напр. Google)', uk:'Сервіс (напр. Google)', en:'Issuer (e.g. Google)', de:'Anbieter (z. B. Google)', fr:'Émetteur (ex. Google)', es:'Emisor (p. ej. Google)', 'es-MX':'Emisor (p. ej. Google)', it:'Servizio (es. Google)', pt:'Emissor (ex. Google)', ar:'الجهة (مثل Google)', hi:'जारीकर्ता (जैसे Google)', ja:'発行元（例: Google）', ky:'Кызмат (мис. Google)', 'zh-Hant':'發行方（如 Google）' },
  account: { bg:'Акаунт (напр. имейл)', ru:'Аккаунт (напр. эл. почта)', uk:'Акаунт (напр. ел. пошта)', en:'Account (e.g. email)', de:'Konto (z. B. E-Mail)', fr:'Compte (ex. e-mail)', es:'Cuenta (p. ej. correo)', 'es-MX':'Cuenta (p. ej. correo)', it:'Account (es. email)', pt:'Conta (ex. e-mail)', ar:'الحساب (مثل البريد)', hi:'खाता (जैसे ईमेल)', ja:'アカウント（例: メール）', ky:'Аккаунт (мис. эл. почта)', 'zh-Hant':'帳戶（如電子郵件）' },
  secret: { bg:'Тайна (Base32)', ru:'Секрет (Base32)', uk:'Секрет (Base32)', en:'Secret (Base32)', de:'Geheimnis (Base32)', fr:'Secret (Base32)', es:'Secreto (Base32)', 'es-MX':'Secreto (Base32)', it:'Segreto (Base32)', pt:'Segredo (Base32)', ar:'السر (Base32)', hi:'सीक्रेट (Base32)', ja:'シークレット（Base32）', ky:'Сыр (Base32)', 'zh-Hant':'金鑰（Base32）' },
  type: { bg:'Тип', ru:'Тип', uk:'Тип', en:'Type', de:'Typ', fr:'Type', es:'Tipo', 'es-MX':'Tipo', it:'Tipo', pt:'Tipo', ar:'النوع', hi:'प्रकार', ja:'タイプ', ky:'Түрү', 'zh-Hant':'類型' },
  advanced: { bg:'Разширени', ru:'Дополнительно', uk:'Додатково', en:'Advanced', de:'Erweitert', fr:'Avancé', es:'Avanzado', 'es-MX':'Avanzado', it:'Avanzate', pt:'Avançado', ar:'متقدم', hi:'उन्नत', ja:'詳細', ky:'Кошумча', 'zh-Hant':'進階' },
  algorithm: { bg:'Алгоритъм', ru:'Алгоритм', uk:'Алгоритм', en:'Algorithm', de:'Algorithmus', fr:'Algorithme', es:'Algoritmo', 'es-MX':'Algoritmo', it:'Algoritmo', pt:'Algoritmo', ar:'الخوارزمية', hi:'एल्गोरिदम', ja:'アルゴリズム', ky:'Алгоритм', 'zh-Hant':'演算法' },
  digits: { bg:'Цифри', ru:'Цифры', uk:'Цифри', en:'Digits', de:'Stellen', fr:'Chiffres', es:'Dígitos', 'es-MX':'Dígitos', it:'Cifre', pt:'Dígitos', ar:'الأرقام', hi:'अंक', ja:'桁数', ky:'Сандар', 'zh-Hant':'位數' },
  period: { bg:'Период (сек)', ru:'Период (сек)', uk:'Період (сек)', en:'Period (sec)', de:'Intervall (Sek.)', fr:'Période (sec)', es:'Período (seg)', 'es-MX':'Período (seg)', it:'Periodo (sec)', pt:'Período (seg)', ar:'الفترة (ث)', hi:'अवधि (सेकंड)', ja:'周期（秒）', ky:'Мезгил (сек)', 'zh-Hant':'週期（秒）' },
  counter: { bg:'Брояч', ru:'Счётчик', uk:'Лічильник', en:'Counter', de:'Zähler', fr:'Compteur', es:'Contador', 'es-MX':'Contador', it:'Contatore', pt:'Contador', ar:'العدّاد', hi:'काउंटर', ja:'カウンター', ky:'Эсептегич', 'zh-Hant':'計數器' },
  save: { bg:'Запази', ru:'Сохранить', uk:'Зберегти', en:'Save', de:'Speichern', fr:'Enregistrer', es:'Guardar', 'es-MX':'Guardar', it:'Salva', pt:'Salvar', ar:'حفظ', hi:'सहेजें', ja:'保存', ky:'Сактоо', 'zh-Hant':'儲存' },
  cancel: { bg:'Отказ', ru:'Отмена', uk:'Скасувати', en:'Cancel', de:'Abbrechen', fr:'Annuler', es:'Cancelar', 'es-MX':'Cancelar', it:'Annulla', pt:'Cancelar', ar:'إلغاء', hi:'रद्द करें', ja:'キャンセル', ky:'Жокко чыгаруу', 'zh-Hant':'取消' },
  invalid_secret: { bg:'Невалидна тайна', ru:'Неверный секрет', uk:'Невірний секрет', en:'Invalid secret', de:'Ungültiges Geheimnis', fr:'Secret invalide', es:'Secreto inválido', 'es-MX':'Secreto inválido', it:'Segreto non valido', pt:'Segredo inválido', ar:'سر غير صالح', hi:'अमान्य सीक्रेट', ja:'無効なシークレット', ky:'Жараксыз сыр', 'zh-Hant':'金鑰無效' },
  scan_hint: { bg:'Насочи камерата към QR кода', ru:'Наведите камеру на QR-код', uk:'Наведіть камеру на QR-код', en:'Point the camera at the QR code', de:'Richte die Kamera auf den QR-Code', fr:'Pointe la caméra vers le QR code', es:'Apunta la cámara al código QR', 'es-MX':'Apunta la cámara al código QR', it:'Inquadra il QR code con la fotocamera', pt:'Aponte a câmera para o QR code', ar:'وجّه الكاميرا نحو رمز QR', hi:'कैमरे को QR कोड पर रखें', ja:'カメラをQRコードに向けてください', ky:'Камераны QR кодго багыттаңыз', 'zh-Hant':'將相機對準 QR 碼' },
  camera_denied: { bg:'Няма достъп до камерата', ru:'Нет доступа к камере', uk:'Немає доступу до камери', en:'No camera access', de:'Kein Kamerazugriff', fr:'Pas d’accès à la caméra', es:'Sin acceso a la cámara', 'es-MX':'Sin acceso a la cámara', it:'Nessun accesso alla fotocamera', pt:'Sem acesso à câmera', ar:'لا وصول إلى الكاميرا', hi:'कैमरा एक्सेस नहीं', ja:'カメラにアクセスできません', ky:'Камерага мүмкүндүк жок', 'zh-Hant':'無法存取相機' },

  edit_title: { bg:'Редактирай', ru:'Редактировать', uk:'Редагувати', en:'Edit', de:'Bearbeiten', fr:'Modifier', es:'Editar', 'es-MX':'Editar', it:'Modifica', pt:'Editar', ar:'تعديل', hi:'संपादित करें', ja:'編集', ky:'Түзөтүү', 'zh-Hant':'編輯' },
  delete: { bg:'Изтрий', ru:'Удалить', uk:'Видалити', en:'Delete', de:'Löschen', fr:'Supprimer', es:'Eliminar', 'es-MX':'Eliminar', it:'Elimina', pt:'Excluir', ar:'حذف', hi:'हटाएं', ja:'削除', ky:'Өчүрүү', 'zh-Hant':'刪除' },
  delete_confirm: { bg:'Да изтрия ли този акаунт?', ru:'Удалить этот аккаунт?', uk:'Видалити цей акаунт?', en:'Delete this account?', de:'Dieses Konto löschen?', fr:'Supprimer ce compte ?', es:'¿Eliminar esta cuenta?', 'es-MX':'¿Eliminar esta cuenta?', it:'Eliminare questo account?', pt:'Excluir esta conta?', ar:'حذف هذا الحساب؟', hi:'यह खाता हटाएं?', ja:'このアカウントを削除しますか？', ky:'Бул аккаунтту өчүрөсүзбү?', 'zh-Hant':'刪除此帳戶？' },

  settings_title: { bg:'Настройки', ru:'Настройки', uk:'Налаштування', en:'Settings', de:'Einstellungen', fr:'Réglages', es:'Ajustes', 'es-MX':'Ajustes', it:'Impostazioni', pt:'Configurações', ar:'الإعدادات', hi:'सेटिंग्स', ja:'設定', ky:'Жөндөөлөр', 'zh-Hant':'設定' },
  codes_tab: { bg:'Кодове', ru:'Коды', uk:'Коди', en:'Codes', de:'Codes', fr:'Codes', es:'Códigos', 'es-MX':'Códigos', it:'Codici', pt:'Códigos', ar:'الرموز', hi:'कोड', ja:'コード', ky:'Коддор', 'zh-Hant':'代碼' },
  autolock: { bg:'Авто-заключване', ru:'Автоблокировка', uk:'Автоблокування', en:'Auto-lock', de:'Auto-Sperre', fr:'Verrouillage auto', es:'Bloqueo automático', 'es-MX':'Bloqueo automático', it:'Blocco automatico', pt:'Bloqueio automático', ar:'القفل التلقائي', hi:'ऑटो-लॉक', ja:'自動ロック', ky:'Авто-кулпулоо', 'zh-Hant':'自動鎖定' },
  never: { bg:'Никога', ru:'Никогда', uk:'Ніколи', en:'Never', de:'Nie', fr:'Jamais', es:'Nunca', 'es-MX':'Nunca', it:'Mai', pt:'Nunca', ar:'أبدًا', hi:'कभी नहीं', ja:'なし', ky:'Эч качан', 'zh-Hant':'永不' },
  minutes: { bg:'{0} мин', ru:'{0} мин', uk:'{0} хв', en:'{0} min', de:'{0} Min.', fr:'{0} min', es:'{0} min', 'es-MX':'{0} min', it:'{0} min', pt:'{0} min', ar:'{0} د', hi:'{0} मिनट', ja:'{0} 分', ky:'{0} мүн', 'zh-Hant':'{0} 分鐘' },
  lock_now: { bg:'Заключи сега', ru:'Заблокировать сейчас', uk:'Заблокувати зараз', en:'Lock now', de:'Jetzt sperren', fr:'Verrouiller maintenant', es:'Bloquear ahora', 'es-MX':'Bloquear ahora', it:'Blocca ora', pt:'Bloquear agora', ar:'اقفل الآن', hi:'अभी लॉक करें', ja:'今すぐロック', ky:'Азыр кулпулоо', 'zh-Hant':'立即鎖定' },
  biometric_unlock: { bg:'Биометрично отключване', ru:'Биометрическая разблокировка', uk:'Біометричне розблокування', en:'Biometric unlock', de:'Biometrische Entsperrung', fr:'Déverrouillage biométrique', es:'Desbloqueo biométrico', 'es-MX':'Desbloqueo biométrico', it:'Sblocco biometrico', pt:'Desbloqueio biométrico', ar:'فتح بيومتري', hi:'बायोमेट्रिक अनलॉक', ja:'生体認証で解除', ky:'Биометрикалык ачуу', 'zh-Hant':'生物辨識解鎖' },
  change_password: { bg:'Смени паролата', ru:'Сменить пароль', uk:'Змінити пароль', en:'Change password', de:'Passwort ändern', fr:'Changer le mot de passe', es:'Cambiar contraseña', 'es-MX':'Cambiar contraseña', it:'Cambia password', pt:'Alterar senha', ar:'تغيير كلمة المرور', hi:'पासवर्ड बदलें', ja:'パスワードを変更', ky:'Сырсөздү алмаштыруу', 'zh-Hant':'更改密碼' },
  new_password: { bg:'Нова парола', ru:'Новый пароль', uk:'Новий пароль', en:'New password', de:'Neues Passwort', fr:'Nouveau mot de passe', es:'Nueva contraseña', 'es-MX':'Nueva contraseña', it:'Nuova password', pt:'Nova senha', ar:'كلمة مرور جديدة', hi:'नया पासवर्ड', ja:'新しいパスワード', ky:'Жаңы сырсөз', 'zh-Hant':'新密碼' },
  password_changed: { bg:'Паролата е сменена', ru:'Пароль изменён', uk:'Пароль змінено', en:'Password changed', de:'Passwort geändert', fr:'Mot de passe changé', es:'Contraseña cambiada', 'es-MX':'Contraseña cambiada', it:'Password cambiata', pt:'Senha alterada', ar:'تم تغيير كلمة المرور', hi:'पासवर्ड बदल गया', ja:'パスワードを変更しました', ky:'Сырсөз алмаштырылды', 'zh-Hant':'密碼已更改' },
  language: { bg:'Език', ru:'Язык', uk:'Мова', en:'Language', de:'Sprache', fr:'Langue', es:'Idioma', 'es-MX':'Idioma', it:'Lingua', pt:'Idioma', ar:'اللغة', hi:'भाषा', ja:'言語', ky:'Тил', 'zh-Hant':'語言' },
  export_json: { bg:'Експорт (.json)', ru:'Экспорт (.json)', uk:'Експорт (.json)', en:'Export (.json)', de:'Export (.json)', fr:'Exporter (.json)', es:'Exportar (.json)', 'es-MX':'Exportar (.json)', it:'Esporta (.json)', pt:'Exportar (.json)', ar:'تصدير (.json)', hi:'निर्यात (.json)', ja:'エクスポート (.json)', ky:'Экспорт (.json)', 'zh-Hant':'匯出 (.json)' },
  import_json: { bg:'Импорт (.json)', ru:'Импорт (.json)', uk:'Імпорт (.json)', en:'Import (.json)', de:'Import (.json)', fr:'Importer (.json)', es:'Importar (.json)', 'es-MX':'Importar (.json)', it:'Importa (.json)', pt:'Importar (.json)', ar:'استيراد (.json)', hi:'आयात (.json)', ja:'インポート (.json)', ky:'Импорт (.json)', 'zh-Hant':'匯入 (.json)' },
  export_warning: { bg:'Файлът съдържа тайните ти НЕшифровани. Пази го на сигурно.', ru:'Файл содержит ваши секреты БЕЗ шифрования. Храните его в безопасности.', uk:'Файл містить ваші секрети БЕЗ шифрування. Зберігайте його в безпеці.', en:'The file holds your secrets UNENCRYPTED. Keep it safe.', de:'Die Datei enthält deine Geheimnisse UNVERSCHLÜSSELT. Bewahre sie sicher auf.', fr:'Le fichier contient tes secrets NON chiffrés. Garde-le en sécurité.', es:'El archivo contiene tus secretos SIN cifrar. Guárdalo a salvo.', 'es-MX':'El archivo contiene tus secretos SIN cifrar. Guárdalo a salvo.', it:'Il file contiene i tuoi segreti NON cifrati. Conservalo al sicuro.', pt:'O arquivo contém seus segredos SEM criptografia. Guarde-o em segurança.', ar:'الملف يحتوي أسرارك غير مشفّرة. احفظه بأمان.', hi:'फ़ाइल में आपके सीक्रेट बिना एन्क्रिप्शन के हैं। इसे सुरक्षित रखें।', ja:'ファイルにはシークレットが暗号化されずに含まれます。安全に保管してください。', ky:'Файлда сырларыңыз ШИФРЛЕНБЕГЕН түрдө. Аны коопсуз сактаңыз.', 'zh-Hant':'檔案含有未加密的金鑰，請妥善保管。' },
  import_done: { bg:'Импортирани {0} акаунта', ru:'Импортировано {0} аккаунтов', uk:'Імпортовано {0} акаунтів', en:'Imported {0} accounts', de:'{0} Konten importiert', fr:'{0} comptes importés', es:'{0} cuentas importadas', 'es-MX':'{0} cuentas importadas', it:'{0} account importati', pt:'{0} contas importadas', ar:'تم استيراد {0} حساب', hi:'{0} खाते आयात किए', ja:'{0} 件のアカウントをインポート', ky:'{0} аккаунт импорттолду', 'zh-Hant':'已匯入 {0} 個帳戶' },
  import_failed: { bg:'Неуспешен импорт', ru:'Импорт не удался', uk:'Імпорт не вдався', en:'Import failed', de:'Import fehlgeschlagen', fr:'Échec de l’import', es:'Error al importar', 'es-MX':'Error al importar', it:'Importazione fallita', pt:'Falha na importação', ar:'فشل الاستيراد', hi:'आयात विफल', ja:'インポートに失敗', ky:'Импорт ишке ашкан жок', 'zh-Hant':'匯入失敗' },
  wipe: { bg:'Изтрий целия сейф', ru:'Удалить всё хранилище', uk:'Видалити все сховище', en:'Delete entire vault', de:'Gesamten Tresor löschen', fr:'Supprimer tout le coffre', es:'Eliminar toda la bóveda', 'es-MX':'Eliminar toda la bóveda', it:'Elimina tutta la cassaforte', pt:'Excluir todo o cofre', ar:'حذف الخزنة بالكامل', hi:'पूरा वॉल्ट हटाएं', ja:'保管庫を全削除', ky:'Бүт сейфти өчүрүү', 'zh-Hant':'刪除整個保險庫' },
  wipe_confirm: { bg:'Това трие ВСИЧКИ акаунти безвъзвратно. Сигурен ли си?', ru:'Это безвозвратно удалит ВСЕ аккаунты. Вы уверены?', uk:'Це безповоротно видалить ВСІ акаунти. Ви впевнені?', en:'This permanently deletes ALL accounts. Are you sure?', de:'Dies löscht ALLE Konten unwiderruflich. Bist du sicher?', fr:'Ceci supprime DÉFINITIVEMENT tous les comptes. Es-tu sûr ?', es:'Esto elimina TODAS las cuentas para siempre. ¿Estás seguro?', 'es-MX':'Esto elimina TODAS las cuentas para siempre. ¿Estás seguro?', it:'Questo elimina TUTTI gli account per sempre. Sei sicuro?', pt:'Isto exclui TODAS as contas para sempre. Tem certeza?', ar:'هذا يحذف كل الحسابات نهائيًا. هل أنت متأكد؟', hi:'यह सभी खाते स्थायी रूप से हटा देगा। क्या आप निश्चित हैं?', ja:'すべてのアカウントを完全に削除します。よろしいですか？', ky:'Бул БАРДЫК аккаунттарды биротоло өчүрөт. Ишенесизби?', 'zh-Hant':'這將永久刪除所有帳戶。確定嗎？' },

  type_totp: { bg:'Време (TOTP)', ru:'Время (TOTP)', uk:'Час (TOTP)', en:'Time (TOTP)', de:'Zeit (TOTP)', fr:'Temps (TOTP)', es:'Tiempo (TOTP)', 'es-MX':'Tiempo (TOTP)', it:'Tempo (TOTP)', pt:'Tempo (TOTP)', ar:'زمني (TOTP)', hi:'समय (TOTP)', ja:'時刻 (TOTP)', ky:'Убакыт (TOTP)', 'zh-Hant':'時間 (TOTP)' },
  type_hotp: { bg:'Брояч (HOTP)', ru:'Счётчик (HOTP)', uk:'Лічильник (HOTP)', en:'Counter (HOTP)', de:'Zähler (HOTP)', fr:'Compteur (HOTP)', es:'Contador (HOTP)', 'es-MX':'Contador (HOTP)', it:'Contatore (HOTP)', pt:'Contador (HOTP)', ar:'عدّاد (HOTP)', hi:'काउंटर (HOTP)', ja:'カウンター (HOTP)', ky:'Эсептегич (HOTP)', 'zh-Hant':'計數 (HOTP)' },
  type_steam: { bg:'Steam', ru:'Steam', uk:'Steam', en:'Steam', de:'Steam', fr:'Steam', es:'Steam', 'es-MX':'Steam', it:'Steam', pt:'Steam', ar:'Steam', hi:'Steam', ja:'Steam', ky:'Steam', 'zh-Hant':'Steam' },
  back: { bg:'Назад', ru:'Назад', uk:'Назад', en:'Back', de:'Zurück', fr:'Retour', es:'Atrás', 'es-MX':'Atrás', it:'Indietro', pt:'Voltar', ar:'رجوع', hi:'वापस', ja:'戻る', ky:'Артка', 'zh-Hant':'返回' },

  upload_file: { bg:'Качи файл с QR', ru:'Загрузить файл с QR', uk:'Завантажити файл з QR', en:'Upload QR file', de:'QR-Datei hochladen', fr:'Importer un fichier QR', es:'Subir archivo QR', 'es-MX':'Subir archivo QR', it:'Carica file QR', pt:'Enviar arquivo QR', ar:'تحميل ملف QR', hi:'QR फ़ाइल अपलोड करें', ja:'QRファイルをアップロード', ky:'QR файлын жүктөө', 'zh-Hant':'上傳 QR 檔案' },
  export_all_qr: { bg:'Експортирай всички (QR)', ru:'Экспорт всех (QR)', uk:'Експорт усіх (QR)', en:'Export all (QR)', de:'Alle exportieren (QR)', fr:'Tout exporter (QR)', es:'Exportar todo (QR)', 'es-MX':'Exportar todo (QR)', it:'Esporta tutti (QR)', pt:'Exportar tudo (QR)', ar:'تصدير الكل (QR)', hi:'सभी निर्यात (QR)', ja:'すべてエクスポート（QR）', ky:'Баарын экспорт (QR)', 'zh-Hant':'匯出全部 (QR)' },
  export_all_desc: { bg:'Сваля всяка авторизация като отделна QR картинка в един .zip.', ru:'Скачивает каждую запись отдельной QR-картинкой в одном .zip.', uk:'Завантажує кожен запис окремою QR-картинкою в одному .zip.', en:'Downloads each account as a separate QR image in one .zip.', de:'Lädt jedes Konto als separates QR-Bild in einer .zip herunter.', fr:'Télécharge chaque compte en image QR séparée dans un .zip.', es:'Descarga cada cuenta como imagen QR separada en un .zip.', 'es-MX':'Descarga cada cuenta como imagen QR separada en un .zip.', it:'Scarica ogni account come immagine QR separata in uno .zip.', pt:'Baixa cada conta como imagem QR separada em um .zip.', ar:'ينزّل كل حساب كصورة QR منفصلة في ملف .zip.', hi:'हर खाते को अलग QR छवि के रूप में एक .zip में डाउनलोड करता है।', ja:'各アカウントを個別のQR画像として1つの.zipでダウンロード。', ky:'Ар бир аккаунтту өзүнчө QR сүрөт катары бир .zip ичинде жүктөйт.', 'zh-Hant':'將每個帳戶以獨立 QR 圖片下載到一個 .zip。' },
  duplicates: { bg:'Дубликати', ru:'Дубликаты', uk:'Дублікати', en:'Duplicates', de:'Duplikate', fr:'Doublons', es:'Duplicados', 'es-MX':'Duplicados', it:'Duplicati', pt:'Duplicados', ar:'مكرّرات', hi:'डुप्लिकेट', ja:'重複', ky:'Кайталанмалар', 'zh-Hant':'重複項' },
  find_duplicates: { bg:'Намери дубликати', ru:'Найти дубликаты', uk:'Знайти дублікати', en:'Find duplicates', de:'Duplikate finden', fr:'Trouver les doublons', es:'Buscar duplicados', 'es-MX':'Buscar duplicados', it:'Trova duplicati', pt:'Encontrar duplicados', ar:'البحث عن المكرّرات', hi:'डुप्लिकेट खोजें', ja:'重複を検索', ky:'Кайталанмаларды табуу', 'zh-Hant':'尋找重複項' },
  no_duplicates: { bg:'Няма дубликати', ru:'Дубликатов нет', uk:'Дублікатів немає', en:'No duplicates', de:'Keine Duplikate', fr:'Aucun doublon', es:'Sin duplicados', 'es-MX':'Sin duplicados', it:'Nessun duplicato', pt:'Sem duplicados', ar:'لا مكرّرات', hi:'कोई डुप्लिकेट नहीं', ja:'重複なし', ky:'Кайталанма жок', 'zh-Hant':'沒有重複項' },
  dup_same_secret: { bg:'Еднаква тайна', ru:'Одинаковый секрет', uk:'Однаковий секрет', en:'Same secret', de:'Gleiches Geheimnis', fr:'Même secret', es:'Mismo secreto', 'es-MX':'Mismo secreto', it:'Stesso segreto', pt:'Mesmo segredo', ar:'السر نفسه', hi:'समान सीक्रेट', ja:'同じシークレット', ky:'Бирдей сыр', 'zh-Hant':'相同金鑰' },
  dup_similar: { bg:'Подобни имена', ru:'Похожие имена', uk:'Схожі імена', en:'Similar names', de:'Ähnliche Namen', fr:'Noms similaires', es:'Nombres similares', 'es-MX':'Nombres similares', it:'Nomi simili', pt:'Nomes parecidos', ar:'أسماء متشابهة', hi:'मिलते-जुलते नाम', ja:'類似した名前', ky:'Окшош аттар', 'zh-Hant':'相似名稱' },
  select_all: { bg:'Избери всички', ru:'Выбрать все', uk:'Вибрати всі', en:'Select all', de:'Alle auswählen', fr:'Tout sélectionner', es:'Seleccionar todo', 'es-MX':'Seleccionar todo', it:'Seleziona tutto', pt:'Selecionar tudo', ar:'تحديد الكل', hi:'सभी चुनें', ja:'すべて選択', ky:'Баарын тандоо', 'zh-Hant':'全選' },
  delete_selected: { bg:'Изтрий избраните', ru:'Удалить выбранные', uk:'Видалити вибрані', en:'Delete selected', de:'Auswahl löschen', fr:'Supprimer la sélection', es:'Eliminar seleccionados', 'es-MX':'Eliminar seleccionados', it:'Elimina selezionati', pt:'Excluir selecionados', ar:'حذف المحدد', hi:'चयनित हटाएं', ja:'選択を削除', ky:'Тандалгандарды өчүрүү', 'zh-Hant':'刪除所選' },
  deleted_n: { bg:'Изтрити {0}', ru:'Удалено {0}', uk:'Видалено {0}', en:'Deleted {0}', de:'{0} gelöscht', fr:'{0} supprimés', es:'{0} eliminados', 'es-MX':'{0} eliminados', it:'{0} eliminati', pt:'{0} excluídos', ar:'تم حذف {0}', hi:'{0} हटाए', ja:'{0} 件削除', ky:'{0} өчүрүлдү', 'zh-Hant':'已刪除 {0}' },
  decoded_ok: { bg:'QR разчетен ✓', ru:'QR распознан ✓', uk:'QR розпізнано ✓', en:'QR decoded ✓', de:'QR erkannt ✓', fr:'QR décodé ✓', es:'QR leído ✓', 'es-MX':'QR leído ✓', it:'QR letto ✓', pt:'QR lido ✓', ar:'تم قراءة QR ✓', hi:'QR पढ़ा ✓', ja:'QR読取 ✓', ky:'QR окулду ✓', 'zh-Hant':'QR 已解碼 ✓' },
  qr_not_found: { bg:'Не е намерен QR код в картинката', ru:'QR-код в изображении не найден', uk:'QR-код у зображенні не знайдено', en:'No QR code found in the image', de:'Kein QR-Code im Bild gefunden', fr:'Aucun QR code trouvé dans l’image', es:'No se encontró QR en la imagen', 'es-MX':'No se encontró QR en la imagen', it:'Nessun QR trovato nell’immagine', pt:'Nenhum QR encontrado na imagem', ar:'لم يُعثر على رمز QR في الصورة', hi:'छवि में कोई QR कोड नहीं मिला', ja:'画像にQRコードが見つかりません', ky:'Сүрөттө QR код табылган жок', 'zh-Hant':'圖片中找不到 QR 碼' },
  nothing_to_export: { bg:'Няма какво да се експортира', ru:'Нечего экспортировать', uk:'Нема чого експортувати', en:'Nothing to export', de:'Nichts zu exportieren', fr:'Rien à exporter', es:'Nada que exportar', 'es-MX':'Nada que exportar', it:'Niente da esportare', pt:'Nada para exportar', ar:'لا شيء للتصدير', hi:'निर्यात के लिए कुछ नहीं', ja:'エクスポートするものがありません', ky:'Экспорттоого эч нерсе жок', 'zh-Hant':'沒有可匯出的項目' },
  exporting: { bg:'Експортиране…', ru:'Экспорт…', uk:'Експорт…', en:'Exporting…', de:'Exportieren…', fr:'Exportation…', es:'Exportando…', 'es-MX':'Exportando…', it:'Esportazione…', pt:'Exportando…', ar:'جارٍ التصدير…', hi:'निर्यात हो रहा…', ja:'エクスポート中…', ky:'Экспорттолууда…', 'zh-Hant':'匯出中…' },

  tab_auth: { bg:'Аутентикация', ru:'Аутентификация', uk:'Автентифікація', en:'Authentication', de:'Authentifizierung', fr:'Authentification', es:'Autenticación', 'es-MX':'Autenticación', it:'Autenticazione', pt:'Autenticação', ar:'المصادقة', hi:'प्रमाणीकरण', ja:'認証', ky:'Аутентификация', 'zh-Hant':'驗證' },
  tab_collection: { bg:'Колекция', ru:'Коллекция', uk:'Колекція', en:'Collection', de:'Sammlung', fr:'Collection', es:'Colección', 'es-MX':'Colección', it:'Collezione', pt:'Coleção', ar:'المجموعة', hi:'संग्रह', ja:'コレクション', ky:'Коллекция', 'zh-Hant':'收藏' },
  tab_passwords: { bg:'Пароли', ru:'Пароли', uk:'Паролі', en:'Passwords', de:'Passwörter', fr:'Mots de passe', es:'Contraseñas', 'es-MX':'Contraseñas', it:'Password', pt:'Senhas', ar:'كلمات المرور', hi:'पासवर्ड', ja:'パスワード', ky:'Сырсөздөр', 'zh-Hant':'密碼' },
  title: { bg:'Заглавие', ru:'Название', uk:'Назва', en:'Title', de:'Titel', fr:'Titre', es:'Título', 'es-MX':'Título', it:'Titolo', pt:'Título', ar:'العنوان', hi:'शीर्षक', ja:'タイトル', ky:'Аталышы', 'zh-Hant':'標題' },
  login: { bg:'Логин', ru:'Логин', uk:'Логін', en:'Login', de:'Login', fr:'Identifiant', es:'Usuario', 'es-MX':'Usuario', it:'Accesso', pt:'Login', ar:'اسم الدخول', hi:'लॉगिन', ja:'ログイン', ky:'Логин', 'zh-Hant':'登入帳號' },
  note: { bg:'Допълнително описание', ru:'Дополнительное описание', uk:'Додатковий опис', en:'Additional description', de:'Zusätzliche Beschreibung', fr:'Description supplémentaire', es:'Descripción adicional', 'es-MX':'Descripción adicional', it:'Descrizione aggiuntiva', pt:'Descrição adicional', ar:'وصف إضافي', hi:'अतिरिक्त विवरण', ja:'追加説明', ky:'Кошумча сүрөттөмө', 'zh-Hant':'附加說明' },
  copy: { bg:'Копиране', ru:'Копировать', uk:'Копіювати', en:'Copy', de:'Kopieren', fr:'Copier', es:'Copiar', 'es-MX':'Copiar', it:'Copia', pt:'Copiar', ar:'نسخ', hi:'कॉपी', ja:'コピー', ky:'Көчүрүү', 'zh-Hant':'複製' },
  col_add_title: { bg:'Добави в колекцията', ru:'Добавить в коллекцию', uk:'Додати до колекції', en:'Add to collection', de:'Zur Sammlung hinzufügen', fr:'Ajouter à la collection', es:'Añadir a la colección', 'es-MX':'Agregar a la colección', it:'Aggiungi alla collezione', pt:'Adicionar à coleção', ar:'أضف إلى المجموعة', hi:'संग्रह में जोड़ें', ja:'コレクションに追加', ky:'Коллекцияга кошуу', 'zh-Hant':'加入收藏' },
  pwd_add_title: { bg:'Нов запис за парола', ru:'Новая запись пароля', uk:'Новий запис пароля', en:'New password entry', de:'Neuer Passworteintrag', fr:'Nouvelle entrée de mot de passe', es:'Nueva entrada de contraseña', 'es-MX':'Nueva entrada de contraseña', it:'Nuova voce password', pt:'Nova entrada de senha', ar:'إدخال كلمة مرور جديد', hi:'नई पासवर्ड प्रविष्टि', ja:'新しいパスワード項目', ky:'Жаңы сырсөз жазуусу', 'zh-Hant':'新增密碼項目' },
  empty_col_title: { bg:'Няма запазени кодове', ru:'Нет сохранённых кодов', uk:'Немає збережених кодів', en:'No saved codes', de:'Keine gespeicherten Codes', fr:'Aucun code enregistré', es:'Sin códigos guardados', 'es-MX':'Sin códigos guardados', it:'Nessun codice salvato', pt:'Sem códigos salvos', ar:'لا رموز محفوظة', hi:'कोई सहेजा कोड नहीं', ja:'保存されたコードなし', ky:'Сакталган коддор жок', 'zh-Hant':'沒有已儲存的代碼' },
  empty_col_desc: { bg:'Качи или сканирай QR код и му дай заглавие', ru:'Загрузите или отсканируйте QR-код и дайте ему название', uk:'Завантажте або відскануйте QR-код і дайте йому назву', en:'Upload or scan a QR code and give it a title', de:'Lade einen QR-Code hoch oder scanne ihn und gib ihm einen Titel', fr:'Importe ou scanne un QR code et donne-lui un titre', es:'Sube o escanea un código QR y ponle un título', 'es-MX':'Sube o escanea un código QR y ponle un título', it:'Carica o scansiona un QR code e dagli un titolo', pt:'Envie ou escaneie um QR code e dê um título', ar:'حمّل أو امسح رمز QR وأعطه عنوانًا', hi:'QR कोड अपलोड या स्कैन करें और शीर्षक दें', ja:'QRコードをアップロードまたはスキャンしてタイトルを付けます', ky:'QR кодду жүктөңүз же скандаңыз жана аталыш бериңиз', 'zh-Hant':'上傳或掃描 QR 碼並命名' },
  empty_pwd_title: { bg:'Няма запазени пароли', ru:'Нет сохранённых паролей', uk:'Немає збережених паролів', en:'No saved passwords', de:'Keine gespeicherten Passwörter', fr:'Aucun mot de passe enregistré', es:'Sin contraseñas guardadas', 'es-MX':'Sin contraseñas guardadas', it:'Nessuna password salvata', pt:'Sem senhas salvas', ar:'لا كلمات مرور محفوظة', hi:'कोई सहेजा पासवर्ड नहीं', ja:'保存されたパスワードなし', ky:'Сакталган сырсөздөр жок', 'zh-Hant':'沒有已儲存的密碼' },
  empty_pwd_desc: { bg:'Добави заглавие, логин и парола', ru:'Добавьте название, логин и пароль', uk:'Додайте назву, логін і пароль', en:'Add a title, login and password', de:'Füge Titel, Login und Passwort hinzu', fr:'Ajoute un titre, un identifiant et un mot de passe', es:'Añade título, usuario y contraseña', 'es-MX':'Agrega título, usuario y contraseña', it:'Aggiungi titolo, accesso e password', pt:'Adicione título, login e senha', ar:'أضف عنوانًا واسم دخول وكلمة مرور', hi:'शीर्षक, लॉगिन और पासवर्ड जोड़ें', ja:'タイトル、ログイン、パスワードを追加', ky:'Аталыш, логин жана сырсөз кошуңуз', 'zh-Hant':'新增標題、登入帳號與密碼' },
  title_required: { bg:'Заглавието е задължително', ru:'Название обязательно', uk:'Назва обов’язкова', en:'Title is required', de:'Titel ist erforderlich', fr:'Le titre est requis', es:'El título es obligatorio', 'es-MX':'El título es obligatorio', it:'Il titolo è obbligatorio', pt:'O título é obrigatório', ar:'العنوان مطلوب', hi:'शीर्षक आवश्यक है', ja:'タイトルは必須です', ky:'Аталыш милдеттүү', 'zh-Hant':'必須填寫標題' }
};

let current = detect();

function detect() {
  try { const s = localStorage.getItem(LS_KEY); if (s && STR.save[s] != null) return s; } catch (e) {}
  return DEFAULT_LANG;
}

export function hasLangChosen() {
  try { return !!localStorage.getItem(LS_KEY); } catch (e) { return false; }
}
export function getLang() { return current; }
export function setLang(code) {
  if (STR.save[code] == null) return;
  current = code;
  try { localStorage.setItem(LS_KEY, code); } catch (e) {}
  applyDir();
}
export function isRTL() { return RTL_CODES.indexOf(current) > -1; }
export function applyDir() {
  try {
    document.documentElement.setAttribute('dir', isRTL() ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', current);
  } catch (e) {}
}
export function t(key) {
  const row = STR[key];
  if (!row) return key;
  if (row[current] != null) return row[current];
  if (row[DEFAULT_LANG] != null) return row[DEFAULT_LANG];
  if (row[FALLBACK_LANG] != null) return row[FALLBACK_LANG];
  return key;
}
export function tf(key, ...vals) {
  let s = t(key);
  vals.forEach((v, i) => { s = s.replace(new RegExp('\\{' + i + '\\}', 'g'), String(v)); });
  return s;
}
export { LANGUAGES, languageByCode };
