// ─────────────────────────────────────────────────────────────────────────────
// FILL DATA · Чат авто-отговори — банки с НАМЕРЕНИЯ и ОТГОВОРИ (15 езика).
// Ползва се от fill-system-replies.js. Системните потребители (is_system=1)
// отговарят на реални хора на ЕЗИКА на държавата си.
//
// Намерения: greeting, howareyou, work, compliment (20 варианта: кратки→груби→
// словоизлияния), other. Банки: bg en ru uk ky de fr it es pt hi ja zh ar
// (es покрива и es-MX). Дозапълва се лесно — нов ключ по език.
// ─────────────────────────────────────────────────────────────────────────────

// Ключови думи за разпознаване на намерението на РЕАЛНИЯ потребител (lowercase).
const KEYWORDS = {
  greeting: ['здравей', 'здрасти', 'привет', 'добър ден', 'добро утро', 'ало', 'хей', 'здравейте',
    'hi', 'hello', 'hey', 'good morning', 'good evening', 'yo',
    'здравствуй', 'здравствуйте', 'добрый день', 'доброе утро',
    'привіт', 'вітаю', 'доброго дня', 'салам', 'салом', 'salam', 'salom',
    'ciao', 'salve', 'hola', 'buenos', 'bonjour', 'salut', 'hallo', 'guten tag', 'olá', 'oi',
    'こんにちは', 'こんにちわ', 'おはよう', 'やあ', 'こんばんは', 'もしもし', '你好', '您好', '嗨', '哈喽', '早上好', '晚上好', 'مرحبا', 'السلام', 'اهلا', 'أهلين', 'صباح الخير', 'مساء الخير', 'هاي', 'नमस्ते', 'हाय', 'नमस्कार', 'हैलो',
    'доброго ранку', 'саламатсызбы', 'салоом', 'ассалам', 'guten morgen', 'servus', 'moin', 'coucou', 'bonsoir', 'buongiorno', 'buonasera', 'buenas tardes', 'bom dia', 'boa tarde'],
  howareyou: ['как си', 'как е', 'какво правиш', 'как върви', 'как сте',
    'how are you', 'how r u', 'how are u', 'whats up', "what's up", 'how do you do', 'how is it going',
    'как дела', 'как ты', 'как поживаешь', 'як справи', 'як ти', 'кандай', 'кандайсыз',
    'come stai', 'cómo estás', 'como estas', 'qué tal', 'comment ca va', 'comment ça va', 'wie geht', 'como vai', 'tudo bem',
    'お元気', 'げんき', '元気', '調子どう', 'お元気ですか', '你好吗', '最近怎么样', '最近好吗', '过得怎么样', '怎么样', 'كيف حالك', 'كيفك', 'شلونك', 'كيف الحال', 'اخبارك', 'कैसे हो', 'कैसी हो', 'क्या हाल', 'कैसे हैं',
    'кандайсың', 'иштер кандай', 'як життя', 'що нового', "wie geht's", 'alles gut', 'comment vas-tu', 'quoi de neuf', 'come va', 'tutto bene', 'cómo te va', 'cómo andas', 'como está', 'beleza'],
  work: ['с какво се занимаваш', 'какво работиш', 'каква работа', 'къде работиш', 'професия', 'с какво се занимавате',
    'what do you do', 'what is your job', "what's your job", 'where do you work', 'your work', 'your job', 'profession',
    'кем работаешь', 'чем занимаешься', 'твоя работа', 'ким болуп иштейсиң', 'чим займаєшся', 'де працюєш',
    'che lavoro', 'qué haces', 'que haces', 'a qué te dedicas', 'que fais tu', 'was machst du', 'o que você faz', 'qual seu trabalho',
    '仕事', 'お仕事', '何してる', '職業', 'どんな仕事', '工作', '做什么工作', '你的工作', '在哪工作', '职业', '做什么的', 'ما عملك', 'ماذا تعمل', 'ما مهنتك', 'أين تعمل', 'شو شغلك', 'क्या काम', 'क्या करते हो', 'पेशा', 'कहाँ काम',
    'ким працюєш', 'твоя робота', 'кайда иштейсиң', 'кесибиң', 'was arbeitest du', 'wo arbeitest du', 'quel est ton métier', 'ton travail', 'dove lavori', 'di cosa ti occupi', 'en qué trabajas', 'dónde trabajas', 'onde trabalha', 'sua profissão'],
  compliment: ['готин', 'готина', 'хубав', 'хубава', 'красив', 'красива', 'красавица', 'сладък', 'сладка',
    'секси', 'прекрасна', 'прекрасен', 'умен', 'умна', 'умница', 'очарователна', 'мил', 'мила', 'обичам те', 'харесвам те',
    'cute', 'hot', 'beautiful', 'handsome', 'gorgeous', 'sexy', 'pretty', 'lovely', 'smart', 'amazing', 'charming', 'sweet', 'i love you', 'i like you', 'wow',
    'красивая', 'красивый', 'красотка', 'милый', 'милая', 'обожаю', 'нравишься', 'прелесть',
    'красива', 'гарна', 'гарний', 'кохаю', 'подобаєшся', 'сулуу', 'жакшы',
    'bella', 'bello', 'guapa', 'guapo', 'hermosa', 'hermoso', 'linda', 'lindo', 'preciosa', 'belle', 'beau', 'mignon', 'mignonne',
    'schön', 'hübsch', 'süß', 'linda', 'gata', 'gato', 'gostosa',
    'かわいい', '可愛い', 'きれい', '美人', 'セクシー', 'かっこいい', '愛してる', '好き', '可爱', '漂亮', '美女', '帅', '好看', '喜欢你', '爱你', '性感', 'جميلة', 'جميل', 'حلوة', 'حلو', 'وسيم', 'جذابة', 'أحبك', 'معجب', 'सुंदर', 'खूबसूरत', 'प्यारी', 'प्यारा', 'हसीन', 'स्मार्ट', 'प्यार',
    'красивий', 'мила', 'милий', 'чарівна', 'сүйкүмдүү', 'жакшы көрөм', 'сонун', 'toll', 'bezaubernd', 'heiß', 'ich liebe dich', 'ich mag dich', 'jolie', 'joli', 'charmante', "je t'aime", "je t'adore", 'carina', 'carino', 'stupenda', 'ti amo', 'mi piaci', 'te quiero', 'me gustas', 'bonita', 'bonito', 'te amo', 'gosto de você', 'adorable', 'stunning'],
};

// 20 варианта комплименти-отговори: ~5 кратки/учтиви · ~5 закачливи · ~5 груби · ~5 словоизлияния.
const BANKS = {
  bg: {
    greeting: ['Здравей! 🙂', 'Привет!', 'Здрасти, как си?', 'Ало, тук съм 👋', 'Хей! Радвам се да те видя.', 'Здравей, добре дошъл!'],
    howareyou: ['Добре съм, благодаря! Ти как си?', 'Горе-долу, върви се. При теб?', 'Супер съм днес 😄', 'Бива, не се оплаквам.', 'Малко уморен/а, но добре. Ти?',
      'Отлично! Денят е хубав.', 'Нормално, както винаги 🙂', 'Чудесно, благодаря че питаш!', 'Преживявам 😅 Ти?', 'Все по-добре. А ти как я караш?'],
    work: ['Занимавам се с малък бизнес у дома.', 'Работя в сферата на услугите.', 'Имам собствена работилница.', 'В момента съм между две работи 🙂',
      'Помагам на хора с дребни задачи.', 'Уча и работя на половин ден.', 'Имам семеен бизнес — търговия.', 'Свободна практика съм, върша по малко от всичко.',
      'В строителството съм от години.', 'Грижа се за дома и подкарвам нещо отстрани.', 'Програмист съм, работя от вкъщи.', 'Продавам ръчно изработени неща.',
      'Шофьор съм, обикалям доста.', 'Бачкам в ресторант, обичам хора.', 'Земеделие — имам малко стопанство.', 'Фризьор/ка съм, харесва ми занаята.',
      'Електротехник, оправям каквото гръмне 😄', 'Учител/ка съм.', 'Шивач/ка — правя дрехи по поръчка.', 'Туризъм — водя хора по красиви места.'],
    compliment: ['Мерси 🙂', 'Благодаря!', 'Колко мило 😊', 'Ти също!', 'Аха, знам 😎',
      'Леле, директен/на си.', 'Спокойно, не бързай толкова.', 'Хаха, опитай пак по-късно.', 'Първо ме почерпи 😄', 'Това на всички ли го пишеш?',
      'Стига де, изчервявам се 🙈', 'Е, не съм чак толкова, но мерси.', 'Чаровник 😉', 'Знаеш как да започнеш разговор!', 'Окей, имаш точка 😏',
      'Думите ти са като топъл вятър в студен ден — стопляш ме, непознати човече, но нека първо се опознаем.', 'Ех, ако комплиментите се продаваха, щеше да си богат с тоя 😄',
      'Сладки приказки, но действията говорят повече — какво умееш освен да ласкаеш?', 'Поласкан/а съм, наистина; рядко някой намира точните думи.', 'Олеле, още малко и ще ми се завърти главата — кажи нещо за теб сега.'],
    other: ['Интересно! Разкажи още.', 'Хмм, не съм сигурен/на. Ти как мислиш?', 'Аха 🙂', 'Може би. Какво те води насам?', 'Разбирам. И после?', 'Любопитно. Продължавай.'],
  },
  en: {
    greeting: ['Hi! 🙂', 'Hello there!', 'Hey, how are you?', 'Yo 👋', 'Hi, nice to see you!', 'Hey hey!'],
    howareyou: ["I'm good, thanks! You?", 'Not bad, getting by. You?', "I'm great today 😄", "Can't complain.", 'A bit tired but fine. You?',
      'Doing excellent!', 'Same as always 🙂', 'Wonderful, thanks for asking!', 'Surviving 😅 You?', 'Better every day. How about you?'],
    work: ['I run a small home business.', 'I work in services.', 'I have my own little workshop.', 'Between two jobs right now 🙂',
      'I help people with small tasks.', 'I study and work part-time.', 'Family business — trading.', 'Freelancer, I do a bit of everything.',
      'Been in construction for years.', 'I keep the home and earn a little on the side.', "I'm a programmer, work from home.", 'I sell handmade things.',
      'I drive a lot for work.', 'I work in a restaurant, I love people.', 'Farming — I have a small plot.', "I'm a hairdresser.",
      'Electrician, I fix whatever breaks 😄', "I'm a teacher.", 'Tailor — I make custom clothes.', 'Tourism — I guide people to beautiful places.'],
    compliment: ['Thanks 🙂', 'Thank you!', 'How sweet 😊', 'You too!', 'Yeah, I know 😎',
      'Wow, straight to the point.', 'Easy there, slow down.', 'Haha, try again later.', 'Buy me a coffee first 😄', 'Do you write that to everyone?',
      "Stop it, I'm blushing 🙈", "Eh, I'm not all that, but thanks.", 'Charmer 😉', 'You know how to start a conversation!', 'Okay, you got a point 😏',
      'Your words are like warm wind on a cold day — you melt me, stranger, but let us get to know each other first.', 'If compliments were money, you would be rich with that one 😄',
      'Sweet talk, but actions speak louder — what can you do besides flatter?', "I'm flattered, truly; few people find the right words.", 'Careful, my head is starting to spin — now tell me something about you.'],
    other: ['Interesting! Tell me more.', "Hmm, not sure. What do you think?", 'I see 🙂', 'Maybe. What brings you here?', 'Got it. And then?', 'Curious. Go on.'],
  },
  ru: {
    greeting: ['Привет! 🙂', 'Здравствуй!', 'Привет, как ты?', 'Йо 👋', 'Привет, рад/а тебя видеть!', 'Хей!'],
    howareyou: ['Хорошо, спасибо! А ты?', 'Нормально, потихоньку. У тебя?', 'Отлично сегодня 😄', 'Не жалуюсь.', 'Немного устал/а, но в порядке. Ты?',
      'Прекрасно!', 'Как всегда 🙂', 'Замечательно, спасибо что спросил/а!', 'Выживаю 😅 Ты?', 'Всё лучше и лучше. А ты как?'],
    work: ['У меня небольшой бизнес из дома.', 'Работаю в сфере услуг.', 'У меня своя мастерская.', 'Сейчас между двумя работами 🙂',
      'Помогаю людям с мелкими задачами.', 'Учусь и подрабатываю.', 'Семейный бизнес — торговля.', 'Фрилансер, делаю понемногу всё.',
      'Много лет в строительстве.', 'Веду дом и подрабатываю.', 'Я программист, работаю из дома.', 'Продаю изделия ручной работы.',
      'Я водитель, много в дороге.', 'Работаю в ресторане, люблю людей.', 'Сельское хозяйство — небольшой участок.', 'Я парикмахер.',
      'Электрик, чиню что сломается 😄', 'Я учитель.', 'Портной — шью на заказ.', 'Туризм — вожу людей по красивым местам.'],
    compliment: ['Спасибо 🙂', 'Благодарю!', 'Как мило 😊', 'Ты тоже!', 'Ага, знаю 😎',
      'Ого, сразу к делу.', 'Полегче, не спеши.', 'Ха-ха, попробуй позже.', 'Сначала угости кофе 😄', 'Ты это всем пишешь?',
      'Перестань, я краснею 🙈', 'Ну, не так уж, но спасибо.', 'Льстец 😉', 'Умеешь начать разговор!', 'Ладно, тут ты прав/а 😏',
      'Твои слова как тёплый ветер в холодный день — ты согреваешь меня, незнакомец, но давай сначала познакомимся.', 'Если бы комплименты были деньгами, ты бы разбогател на этом 😄',
      'Сладкие речи, но дела важнее слов — что ты умеешь, кроме как льстить?', 'Мне льстит, правда; мало кто находит нужные слова.', 'Осторожно, голова кружится — теперь расскажи о себе.'],
    other: ['Интересно! Расскажи ещё.', 'Хм, не уверен/а. Ты как думаешь?', 'Понятно 🙂', 'Может быть. Что привело тебя сюда?', 'Ясно. И что потом?', 'Любопытно. Продолжай.'],
  },
  uk: {
    greeting: ['Привіт! 🙂', 'Вітаю!', 'Привіт, як ти?', 'Хей 👋', 'Привіт, радий/рада тебе бачити!', 'Доброго дня!'],
    howareyou: ['Добре, дякую! А ти?', 'Нормально, потроху. У тебе?', 'Чудово сьогодні 😄', 'Не скаржусь.', 'Трохи втомився/лась, але добре. Ти?',
      'Прекрасно!', 'Як завжди 🙂', 'Чудово, дякую що спитав/ла!', 'Виживаю 😅 Ти?', 'Все краще і краще. А ти як?'],
    work: ['Маю невеликий бізнес із дому.', 'Працюю у сфері послуг.', 'Маю власну майстерню.', 'Зараз між двома роботами 🙂',
      'Допомагаю людям із дрібними справами.', 'Навчаюсь і підробляю.', 'Сімейний бізнес — торгівля.', 'Фрілансер, роблю потроху все.',
      'Багато років у будівництві.', 'Веду дім і підробляю.', 'Я програміст, працюю з дому.', 'Продаю вироби ручної роботи.',
      'Я водій, багато в дорозі.', 'Працюю в ресторані, люблю людей.', 'Сільське господарство — невелика ділянка.', 'Я перукар.',
      'Електрик, лагоджу що зламається 😄', 'Я вчитель.', 'Кравець — шию на замовлення.', 'Туризм — воджу людей гарними місцями.'],
    compliment: ['Дякую 🙂', 'Дякую!', 'Як мило 😊', 'Ти теж!', 'Ага, знаю 😎',
      'Ого, одразу до справи.', 'Спокійніше, не поспішай.', 'Ха-ха, спробуй пізніше.', 'Спершу пригости кавою 😄', 'Ти це всім пишеш?',
      'Припини, я червонію 🙈', 'Ну, не так уже, але дякую.', 'Підлесник 😉', 'Умієш почати розмову!', 'Гаразд, тут ти маєш рацію 😏',
      'Твої слова як теплий вітер у холодний день — ти зігріваєш мене, незнайомцю, але давай спершу познайомимось.', 'Якби компліменти були грошима, ти б розбагатів на цьому 😄',
      'Солодкі слова, але дії важливіші — що ти вмієш, окрім лестощів?', 'Мені лестить, справді; мало хто знаходить потрібні слова.', 'Обережно, голова паморочиться — тепер розкажи про себе.'],
    other: ['Цікаво! Розкажи ще.', 'Хм, не впевнений/а. Ти як гадаєш?', 'Зрозуміло 🙂', 'Можливо. Що тебе привело сюди?', 'Ясно. І що потім?', 'Цікаво. Продовжуй.'],
  },
  ky: {
    greeting: ['Салам! 🙂', 'Саламатсызбы!', 'Салам, кандайсың?', 'Хей 👋', 'Салам, көргөнүмө кубанычтамын!', 'Кутмандуу күн!'],
    howareyou: ['Жакшы, рахмат! Өзүң кандайсың?', 'Жакшы эле, акырындап. Сенде кандай?', 'Бүгүн сонун 😄', 'Арызым жок.', 'Бир аз чарчадым, бирок жакшы. Сен?',
      'Эң жакшы!', 'Дайыма эле 🙂', 'Сонун, сураганыңа рахмат!', 'Жашап жатам 😅 Сен?', 'Күндөн күнгө жакшы. Сен кандай?'],
    work: ['Үйдөн чакан бизнес кылам.', 'Кызмат көрсөтүү тармагында иштейм.', 'Өзүмдүн устаканам бар.', 'Азыр эки жумуштун ортосундамын 🙂',
      'Адамдарга майда иштерде жардам берем.', 'Окуйм жана жарым күн иштейм.', 'Үй-бүлөлүк бизнес — соода.', 'Фрилансермин, баарынан бир аз кылам.',
      'Курулушта көп жылдан бери.', 'Үйдү карайм жана кошумча иштейм.', 'Программистмин, үйдөн иштейм.', 'Кол өнөрчүлүк буюмдарын сатам.',
      'Айдоочумун, жолдо көп жүрөм.', 'Ресторанда иштейм, адамдарды жакшы көрөм.', 'Айыл чарба — кичине жерим бар.', 'Чач тарачмын.',
      'Электрик, бузулганын оңдойм 😄', 'Мугалиммин.', 'Тигүүчүмүн — буйрутма боюнча тигем.', 'Туризм — адамдарды кооз жерлерге алып барам.'],
    compliment: ['Рахмат 🙂', 'Чоң рахмат!', 'Кандай жагымдуу 😊', 'Сен дагы!', 'Ооба, билем 😎',
      'Оо, түз эле айттың.', 'Жайыраак, шашпа.', 'Ха-ха, кийинчерээк кайра аракет кыл.', 'Адегенде кофе алып бер 😄', 'Муну баарына жазасыңбы?',
      'Койчу, кызарып кеттим 🙈', 'Анча эмесмин, бирок рахмат.', 'Алдамчы 😉', 'Сүйлөшүүнү баштаганды билесиң!', 'Макул, туура айтасың 😏',
      'Сөздөрүң суук күндөгү жылуу шамалдай — мени жылытасың, бейтааныш, бирок адегенде таанышалы.', 'Эгер мактоолор акча болсо, сен ушуну менен байыйт элең 😄',
      'Таттуу сөздөр, бирок иш сөздөн маанилүү — мактоодон башка эмнени билесиң?', 'Мактанганыма кубанычтамын; туура сөз тапкан адам аз.', 'Этият бол, башым айланып баратат — эми өзүң жөнүндө айт.'],
    other: ['Кызык! Дагы айтып бер.', 'Хм, ишенбейм. Сен кандай ойлойсуң?', 'Түшүнүктүү 🙂', 'Балким. Бул жакка эмне алып келди?', 'Жакшы. Анан эмне?', 'Кызык. Уланта бер.'],
  },
  de: {
    greeting: ['Hi! 🙂', 'Hallo!', 'Hey, wie geht es dir?', 'Yo 👋', 'Hallo, schön dich zu sehen!', 'Guten Tag!'],
    howareyou: ['Gut, danke! Und dir?', 'Nicht schlecht, geht so. Bei dir?', 'Heute super 😄', 'Kann nicht klagen.', 'Etwas müde, aber gut. Du?',
      'Ausgezeichnet!', 'Wie immer 🙂', 'Wunderbar, danke der Nachfrage!', 'Ich überlebe 😅 Du?', 'Jeden Tag besser. Und du?'],
    work: ['Ich habe ein kleines Heimgeschäft.', 'Ich arbeite im Dienstleistungsbereich.', 'Ich habe eine eigene kleine Werkstatt.', 'Gerade zwischen zwei Jobs 🙂',
      'Ich helfe Leuten bei kleinen Aufgaben.', 'Ich studiere und arbeite Teilzeit.', 'Familienbetrieb — Handel.', 'Freiberufler, ich mache von allem etwas.',
      'Seit Jahren im Bau.', 'Ich kümmere mich um das Haus und verdiene nebenbei.', 'Ich bin Programmierer, arbeite von zu Hause.', 'Ich verkaufe handgemachte Sachen.',
      'Ich fahre viel beruflich.', 'Ich arbeite im Restaurant, ich mag Menschen.', 'Landwirtschaft — ich habe ein kleines Stück Land.', 'Ich bin Friseur/in.',
      'Elektriker, ich repariere was kaputtgeht 😄', 'Ich bin Lehrer/in.', 'Schneider/in — ich nähe auf Maß.', 'Tourismus — ich führe Leute zu schönen Orten.'],
    compliment: ['Danke 🙂', 'Vielen Dank!', 'Wie süß 😊', 'Du auch!', 'Ja, ich weiß 😎',
      'Wow, direkt zur Sache.', 'Ganz ruhig, langsam.', 'Haha, versuch es später nochmal.', 'Erst einen Kaffee 😄', 'Schreibst du das allen?',
      'Hör auf, ich werde rot 🙈', 'Na ja, so toll bin ich nicht, aber danke.', 'Charmeur 😉', 'Du weißt, wie man ein Gespräch beginnt!', 'Okay, da hast du recht 😏',
      'Deine Worte sind wie warmer Wind an einem kalten Tag — du wärmst mich, Fremder, aber lass uns erst kennenlernen.', 'Wären Komplimente Geld, wärst du reich mit dem 😄',
      'Schöne Worte, aber Taten zählen mehr — was kannst du außer schmeicheln?', 'Ich fühle mich geschmeichelt; wenige finden die richtigen Worte.', 'Vorsicht, mir wird schwindelig — jetzt erzähl von dir.'],
    other: ['Interessant! Erzähl mehr.', 'Hmm, nicht sicher. Was meinst du?', 'Verstehe 🙂', 'Vielleicht. Was führt dich her?', 'Alles klar. Und dann?', 'Spannend. Mach weiter.'],
  },
  fr: {
    greeting: ['Salut ! 🙂', 'Bonjour !', 'Hé, comment vas-tu ?', 'Yo 👋', 'Salut, content de te voir !', 'Bonne journée !'],
    howareyou: ['Bien, merci ! Et toi ?', 'Pas mal, ça va. Et toi ?', "Super aujourd'hui 😄", 'Je ne me plains pas.', 'Un peu fatigué, mais ça va. Toi ?',
      'Excellent !', 'Comme toujours 🙂', 'Très bien, merci de demander !', 'Je survis 😅 Toi ?', 'De mieux en mieux. Et toi ?'],
    work: ['Je tiens une petite affaire à domicile.', 'Je travaille dans les services.', "J'ai mon propre petit atelier.", 'Entre deux emplois en ce moment 🙂',
      "J'aide les gens pour de petites tâches.", "J'étudie et je travaille à mi-temps.", 'Entreprise familiale — le commerce.', 'Freelance, je fais un peu de tout.',
      'Dans le bâtiment depuis des années.', "Je m'occupe de la maison et je gagne un peu à côté.", 'Je suis programmeur, je travaille de chez moi.', 'Je vends des objets faits main.',
      'Je conduis beaucoup pour le travail.', "Je travaille au restaurant, j'aime les gens.", "Agriculture — j'ai un petit terrain.", 'Je suis coiffeur/euse.',
      'Électricien, je répare ce qui casse 😄', 'Je suis enseignant/e.', 'Tailleur — je fais des vêtements sur mesure.', 'Tourisme — je guide les gens vers de beaux endroits.'],
    compliment: ['Merci 🙂', 'Merci beaucoup !', 'Comme c’est gentil 😊', 'Toi aussi !', 'Oui, je sais 😎',
      'Wow, droit au but.', 'Doucement, ralentis.', 'Haha, réessaie plus tard.', "Offre-moi un café d'abord 😄", 'Tu écris ça à tout le monde ?',
      'Arrête, je rougis 🙈', 'Bon, pas tant que ça, mais merci.', 'Charmeur 😉', 'Tu sais comment lancer une conversation !', "D'accord, tu marques un point 😏",
      'Tes mots sont comme un vent chaud un jour froid — tu me réchauffes, inconnu, mais apprenons d’abord à nous connaître.', 'Si les compliments étaient de l’argent, tu serais riche avec celui-là 😄',
      'Belles paroles, mais les actes comptent plus — que sais-tu faire à part flatter ?', 'Je suis flatté ; peu de gens trouvent les bons mots.', 'Attention, la tête me tourne — parle-moi de toi maintenant.'],
    other: ['Intéressant ! Raconte.', 'Hmm, pas sûr. Tu en penses quoi ?', 'Je vois 🙂', 'Peut-être. Qu’est-ce qui t’amène ?', 'Compris. Et ensuite ?', 'Curieux. Continue.'],
  },
  it: {
    greeting: ['Ciao! 🙂', 'Salve!', 'Ehi, come stai?', 'Yo 👋', 'Ciao, piacere di vederti!', 'Buona giornata!'],
    howareyou: ['Bene, grazie! E tu?', 'Non male, si tira avanti. Tu?', 'Oggi alla grande 😄', 'Non mi lamento.', 'Un po’ stanco, ma bene. Tu?',
      'Benissimo!', 'Come sempre 🙂', 'Benissimo, grazie di chiedere!', 'Sopravvivo 😅 Tu?', 'Sempre meglio. E tu?'],
    work: ['Ho una piccola attività da casa.', 'Lavoro nei servizi.', 'Ho un mio piccolo laboratorio.', 'In questo momento tra due lavori 🙂',
      'Aiuto le persone con piccoli compiti.', 'Studio e lavoro part-time.', 'Attività di famiglia — commercio.', 'Freelance, faccio un po’ di tutto.',
      'Nell’edilizia da anni.', 'Mi occupo della casa e guadagno qualcosa a parte.', 'Sono programmatore, lavoro da casa.', 'Vendo oggetti fatti a mano.',
      'Guido molto per lavoro.', 'Lavoro in un ristorante, amo la gente.', 'Agricoltura — ho un piccolo terreno.', 'Sono parrucchiere/a.',
      'Elettricista, riparo ciò che si rompe 😄', 'Sono insegnante.', 'Sarto — faccio vestiti su misura.', 'Turismo — porto le persone in posti belli.'],
    compliment: ['Grazie 🙂', 'Grazie mille!', 'Che dolce 😊', 'Anche tu!', 'Sì, lo so 😎',
      'Wow, dritto al punto.', 'Piano, non correre.', 'Ahah, riprova più tardi.', 'Prima offrimi un caffè 😄', 'Lo scrivi a tutti?',
      'Smettila, arrossisco 🙈', 'Beh, non così tanto, ma grazie.', 'Che farfallone 😉', 'Sai come iniziare una conversazione!', 'Ok, hai ragione 😏',
      'Le tue parole sono come vento caldo in un giorno freddo — mi scaldi, sconosciuto, ma prima conosciamoci.', 'Se i complimenti fossero denaro, saresti ricco con quello 😄',
      'Belle parole, ma i fatti contano di più — cosa sai fare oltre ad adulare?', 'Mi lusinghi; in pochi trovano le parole giuste.', 'Attento, mi gira la testa — ora parlami di te.'],
    other: ['Interessante! Raccontami di più.', 'Mmh, non sono sicuro. Tu che ne pensi?', 'Capisco 🙂', 'Forse. Cosa ti porta qui?', 'Capito. E poi?', 'Curioso. Continua.'],
  },
  es: {
    greeting: ['¡Hola! 🙂', '¡Buenas!', 'Hey, ¿cómo estás?', 'Yo 👋', '¡Hola, qué gusto verte!', '¡Buen día!'],
    howareyou: ['¡Bien, gracias! ¿Y tú?', 'No me quejo, ahí vamos. ¿Tú?', 'Hoy genial 😄', 'Todo en orden.', 'Un poco cansado, pero bien. ¿Tú?',
      '¡Excelente!', 'Como siempre 🙂', '¡Muy bien, gracias por preguntar!', 'Sobreviviendo 😅 ¿Tú?', 'Cada día mejor. ¿Y tú?'],
    work: ['Tengo un pequeño negocio en casa.', 'Trabajo en servicios.', 'Tengo mi propio taller.', 'Ahora entre dos trabajos 🙂',
      'Ayudo a la gente con tareas pequeñas.', 'Estudio y trabajo medio tiempo.', 'Negocio familiar — comercio.', 'Freelance, hago un poco de todo.',
      'En la construcción desde hace años.', 'Cuido la casa y gano algo aparte.', 'Soy programador, trabajo desde casa.', 'Vendo cosas hechas a mano.',
      'Manejo mucho por trabajo.', 'Trabajo en un restaurante, me gusta la gente.', 'Agricultura — tengo un terreno pequeño.', 'Soy peluquero/a.',
      'Electricista, arreglo lo que se rompa 😄', 'Soy maestro/a.', 'Sastre — hago ropa a medida.', 'Turismo — llevo gente a lugares bonitos.'],
    compliment: ['Gracias 🙂', '¡Muchas gracias!', 'Qué lindo 😊', '¡Tú también!', 'Sí, lo sé 😎',
      'Vaya, directo al grano.', 'Tranquilo, no corras.', 'Jaja, inténtalo más tarde.', 'Primero invítame un café 😄', '¿Eso le escribes a todos?',
      'Para, me sonrojo 🙈', 'Bueno, no tanto, pero gracias.', 'Qué coqueto 😉', '¡Sabes cómo empezar una charla!', 'Vale, tienes razón 😏',
      'Tus palabras son como viento cálido en un día frío — me derrites, desconocido, pero conozcámonos primero.', 'Si los cumplidos fueran dinero, serías rico con ese 😄',
      'Bonitas palabras, pero los hechos valen más — ¿qué sabes hacer además de halagar?', 'Me halagas; pocos encuentran las palabras justas.', 'Cuidado, me mareo — ahora cuéntame de ti.'],
    other: ['¡Interesante! Cuéntame más.', 'Mmm, no estoy seguro. ¿Tú qué crees?', 'Ya veo 🙂', 'Quizá. ¿Qué te trae por aquí?', 'Entendido. ¿Y luego?', 'Curioso. Sigue.'],
  },
  pt: {
    greeting: ['Oi! 🙂', 'Olá!', 'Ei, como vai?', 'Yo 👋', 'Oi, prazer em te ver!', 'Bom dia!'],
    howareyou: ['Bem, obrigado! E você?', 'Levando, tudo certo. E você?', 'Hoje ótimo 😄', 'Não posso reclamar.', 'Um pouco cansado, mas bem. Você?',
      'Excelente!', 'Como sempre 🙂', 'Muito bem, obrigado por perguntar!', 'Sobrevivendo 😅 Você?', 'Cada dia melhor. E você?'],
    work: ['Tenho um pequeno negócio em casa.', 'Trabalho com serviços.', 'Tenho minha própria oficina.', 'Agora entre dois empregos 🙂',
      'Ajudo as pessoas com pequenas tarefas.', 'Estudo e trabalho meio período.', 'Negócio de família — comércio.', 'Freelancer, faço um pouco de tudo.',
      'Na construção há anos.', 'Cuido da casa e ganho algo à parte.', 'Sou programador, trabalho de casa.', 'Vendo coisas feitas à mão.',
      'Dirijo muito a trabalho.', 'Trabalho num restaurante, gosto de gente.', 'Agricultura — tenho um terreno pequeno.', 'Sou cabeleireiro/a.',
      'Eletricista, conserto o que quebra 😄', 'Sou professor/a.', 'Alfaiate — faço roupas sob medida.', 'Turismo — levo pessoas a lugares lindos.'],
    compliment: ['Obrigado 🙂', 'Muito obrigado!', 'Que fofo 😊', 'Você também!', 'Sim, eu sei 😎',
      'Uau, direto ao ponto.', 'Calma, devagar.', 'Haha, tente de novo mais tarde.', 'Primeiro me paga um café 😄', 'Você escreve isso pra todo mundo?',
      'Para, estou corando 🙈', 'Bem, nem tanto, mas obrigado.', 'Que charmoso 😉', 'Você sabe como começar uma conversa!', 'Ok, você tem razão 😏',
      'Suas palavras são como vento quente num dia frio — você me aquece, estranho, mas vamos nos conhecer primeiro.', 'Se elogios fossem dinheiro, você ficaria rico com esse 😄',
      'Palavras doces, mas atos valem mais — o que você sabe fazer além de elogiar?', 'Fico lisonjeado; poucos acham as palavras certas.', 'Cuidado, minha cabeça está girando — agora fale de você.'],
    other: ['Interessante! Conte mais.', 'Hmm, não tenho certeza. O que você acha?', 'Entendi 🙂', 'Talvez. O que te traz aqui?', 'Entendido. E depois?', 'Curioso. Continue.'],
  },
  hi: {
    greeting: ['नमस्ते! 🙂', 'हैलो!', 'हे, कैसे हो?', 'यो 👋', 'नमस्ते, तुमसे मिलकर अच्छा लगा!', 'शुभ दिन!'],
    howareyou: ['मैं ठीक हूँ, धन्यवाद! तुम?', 'बस चल रहा है। तुम्हारा?', 'आज बढ़िया 😄', 'कोई शिकायत नहीं।', 'थोड़ा थका हूँ, पर ठीक। तुम?',
      'बहुत बढ़िया!', 'हमेशा की तरह 🙂', 'शानदार, पूछने के लिए शुक्रिया!', 'गुज़ारा चल रहा है 😅 तुम?', 'दिन-ब-दिन बेहतर। और तुम?'],
    work: ['घर से छोटा कारोबार करता/ती हूँ।', 'सेवा क्षेत्र में काम करता/ती हूँ।', 'मेरी अपनी छोटी वर्कशॉप है।', 'अभी दो नौकरियों के बीच हूँ 🙂',
      'लोगों के छोटे कामों में मदद करता/ती हूँ।', 'पढ़ाई और पार्ट-टाइम काम।', 'पारिवारिक कारोबार — व्यापार।', 'फ्रीलांसर हूँ, थोड़ा सब कुछ करता/ती हूँ।',
      'सालों से निर्माण में हूँ।', 'घर संभालता/ती हूँ और थोड़ा अलग से कमाता/ती हूँ।', 'प्रोग्रामर हूँ, घर से काम करता/ती हूँ।', 'हाथ से बनी चीज़ें बेचता/ती हूँ।',
      'काम के लिए बहुत गाड़ी चलाता/ती हूँ।', 'रेस्तरां में काम करता/ती हूँ, लोग पसंद हैं।', 'खेती — मेरा छोटा खेत है।', 'मैं नाई/हेयरड्रेसर हूँ।',
      'इलेक्ट्रीशियन, जो खराब हो ठीक करता/ती हूँ 😄', 'मैं शिक्षक हूँ।', 'दर्ज़ी — नाप के कपड़े बनाता/ती हूँ।', 'पर्यटन — लोगों को सुंदर जगहें दिखाता/ती हूँ।'],
    compliment: ['शुक्रिया 🙂', 'बहुत धन्यवाद!', 'कितना प्यारा 😊', 'तुम भी!', 'हाँ, पता है 😎',
      'वाह, सीधे मुद्दे पर।', 'आराम से, जल्दी मत करो।', 'हाहा, बाद में फिर कोशिश करो।', 'पहले कॉफ़ी पिलाओ 😄', 'यह सबको लिखते हो क्या?',
      'बस करो, मैं शरमा रहा/रही हूँ 🙈', 'अरे, इतना भी नहीं, पर शुक्रिया।', 'चालू हो 😉', 'बातचीत शुरू करना आता है तुम्हें!', 'ठीक है, बात तो सही है 😏',
      'तुम्हारे शब्द ठंडे दिन की गर्म हवा जैसे हैं — तुम मुझे गर्म कर देते हो, अजनबी, पर पहले एक-दूसरे को जान लें।', 'अगर तारीफ़ें पैसा होतीं, तो इससे तुम अमीर हो जाते 😄',
      'मीठी बातें, पर काम ज़्यादा बोलते हैं — चापलूसी के अलावा क्या आता है?', 'अच्छा लगा सच में; कम लोग सही शब्द ढूँढ पाते हैं।', 'संभलो, सिर घूम रहा है — अब अपने बारे में बताओ।'],
    other: ['दिलचस्प! और बताओ।', 'हम्म, यकीन नहीं। तुम क्या सोचते हो?', 'समझा 🙂', 'शायद। यहाँ क्या लाया तुम्हें?', 'ठीक है। फिर?', 'जिज्ञासा हुई। जारी रखो।'],
  },
  ja: {
    greeting: ['こんにちは！🙂', 'やあ！', 'ねえ、元気？', 'よっ 👋', 'こんにちは、会えてうれしいです！', 'いい一日を！'],
    howareyou: ['元気だよ、ありがとう！君は？', 'まあまあかな。君は？', '今日は最高 😄', '不満はないよ。', 'ちょっと疲れたけど元気。君は？',
      '絶好調！', 'いつも通り 🙂', 'とてもいいよ、聞いてくれてありがとう！', 'なんとか生きてる 😅 君は？', '日に日に良くなってる。君は？'],
    work: ['家で小さなビジネスをしてるよ。', 'サービス業で働いてる。', '自分の小さな工房がある。', '今は二つの仕事の間 🙂',
      '人の小さな用事を手伝ってる。', '勉強しながらバイト。', '家族の商売 — 物販。', 'フリーランスで、いろいろやってる。',
      '建設の仕事を何年も。', '家のことをしながら副業も。', 'プログラマーで在宅勤務。', '手作りの物を売ってる。',
      '仕事で運転が多い。', 'レストランで働いてる、人が好き。', '農業 — 小さな畑がある。', '美容師だよ。',
      '電気工、壊れたら直す 😄', '教師をしてる。', '仕立て屋 — オーダーメイド。', '観光 — きれいな場所へ案内するよ。'],
    compliment: ['ありがとう 🙂', 'どうも！', '優しいね 😊', '君もね！', 'うん、知ってる 😎',
      'おっと、ストレートだね。', 'まあ落ち着いて。', 'はは、また後でね。', 'まずコーヒーおごって 😄', 'それ皆に言ってる？',
      'やめてよ、照れる 🙈', 'いや、そんなでもないけど、ありがとう。', '口がうまいね 😉', '会話の始め方を知ってるね！', 'なるほど、一理ある 😏',
      '君の言葉は寒い日の暖かい風みたい — 知らない人なのに温めてくれる、でもまずは知り合おう。', 'お世辞がお金なら、それで大金持ちだね 😄',
      '甘い言葉だけど、行動のほうが大事 — お世辞以外に何ができる？', '本当にうれしいよ、ちゃんとした言葉を選べる人は少ない。', '危ない、くらくらしてきた — 今度は君のことを聞かせて。'],
    other: ['面白い！もっと聞かせて。', 'うーん、わからないな。君はどう思う？', 'なるほど 🙂', 'たぶんね。何の用？', '了解。それで？', '気になるね。続けて。'],
  },
  zh: {
    greeting: ['你好！🙂', '嗨！', '嘿，最近怎么样？', '哟 👋', '你好，很高兴见到你！', '祝你今天愉快！'],
    howareyou: ['我很好，谢谢！你呢？', '还行，凑合过。你呢？', '今天很棒 😄', '没什么好抱怨的。', '有点累，但还好。你呢？',
      '好极了！', '老样子 🙂', '很好，谢谢关心！', '还活着呢 😅 你呢？', '一天比一天好。你呢？'],
    work: ['我在家做点小生意。', '我做服务行业。', '我有自己的小作坊。', '现在在两份工作之间 🙂',
      '我帮人做些小事。', '一边读书一边兼职。', '家族生意 — 做买卖。', '自由职业，什么都做一点。',
      '在建筑行业干了好多年。', '管着家，顺便挣点外快。', '我是程序员，在家工作。', '我卖手工做的东西。',
      '工作要常开车。', '在餐厅上班，喜欢和人打交道。', '务农 — 有一小块地。', '我是理发师。',
      '电工，哪坏了修哪 😄', '我是老师。', '裁缝 — 量身做衣服。', '旅游 — 带人去漂亮的地方。'],
    compliment: ['谢谢 🙂', '多谢！', '真贴心 😊', '你也是！', '嗯，我知道 😎',
      '哇，挺直接的。', '别急，慢慢来。', '哈哈，等会儿再试。', '先请我喝杯咖啡 😄', '这话你跟谁都说吧？',
      '别说了，我脸红了 🙈', '没那么好啦，不过谢谢。', '真会说 😉', '你很会找话题嘛！', '行吧，有点道理 😏',
      '你的话像寒冬里的暖风 — 陌生人却让我心暖，不过先认识认识吧。', '要是夸奖能当钱，你光凭这句就发财了 😄',
      '甜言蜜语，但行动更重要 — 除了恭维你还会什么？', '真的受宠若惊；很少有人能说到点上。', '小心，我有点头晕了 — 现在说说你自己吧。'],
    other: ['有意思！再多说点。', '嗯，不确定。你怎么看？', '原来如此 🙂', '也许吧。什么风把你吹来的？', '明白了。然后呢？', '好奇。继续说。'],
  },
  ar: {
    greeting: ['مرحبا! 🙂', 'أهلا!', 'هاي، كيف حالك؟', 'يا 👋', 'مرحبا، سعيد برؤيتك!', 'يوم سعيد!'],
    howareyou: ['بخير، شكرا! وأنت؟', 'لا بأس، نتدبر أمورنا. وأنت؟', 'اليوم رائع 😄', 'لا أشكو من شيء.', 'متعب قليلا لكن بخير. وأنت؟',
      'ممتاز!', 'كالعادة 🙂', 'بأحسن حال، شكرا لسؤالك!', 'أحاول الصمود 😅 وأنت؟', 'أفضل كل يوم. وأنت؟'],
    work: ['لدي عمل صغير من المنزل.', 'أعمل في مجال الخدمات.', 'لدي ورشتي الصغيرة.', 'حاليا بين عملين 🙂',
      'أساعد الناس في مهام صغيرة.', 'أدرس وأعمل بدوام جزئي.', 'عمل عائلي — تجارة.', 'أعمل حرّ، أقوم بقليل من كل شيء.',
      'في البناء منذ سنوات.', 'أعتني بالبيت وأكسب القليل جانبيا.', 'أنا مبرمج، أعمل من المنزل.', 'أبيع أشياء مصنوعة يدويا.',
      'أقود كثيرا في عملي.', 'أعمل في مطعم، أحب الناس.', 'زراعة — لدي قطعة أرض صغيرة.', 'أنا حلاق.',
      'كهربائي، أصلح ما يتعطل 😄', 'أنا معلم.', 'خياط — أفصّل الملابس حسب الطلب.', 'سياحة — أرشد الناس إلى أماكن جميلة.'],
    compliment: ['شكرا 🙂', 'شكرا جزيلا!', 'كم أنت لطيف 😊', 'وأنت أيضا!', 'نعم، أعرف 😎',
      'واو، مباشرة إلى الهدف.', 'على مهلك، لا تتعجل.', 'هههه، حاول لاحقا.', 'اشترِ لي قهوة أولا 😄', 'هل تكتب هذا للجميع؟',
      'توقف، أنا أحمرّ خجلا 🙈', 'لست بهذه الروعة، لكن شكرا.', 'يا لك من معسول اللسان 😉', 'تعرف كيف تبدأ حديثا!', 'حسنا، كلامك صحيح 😏',
      'كلماتك كنسيم دافئ في يوم بارد — تدفّئني أيها الغريب، لكن لنتعارف أولا.', 'لو كانت المجاملات نقودا لأصبحت ثريا بهذه الواحدة 😄',
      'كلام معسول، لكن الأفعال أبلغ — ماذا تتقن غير المديح؟', 'أنا ممتن حقا؛ قليلون من يجدون الكلمات المناسبة.', 'احذر، بدأ رأسي يدور — والآن حدثني عن نفسك.'],
    other: ['مثير للاهتمام! أخبرني المزيد.', 'همم، لست متأكدا. ما رأيك؟', 'فهمت 🙂', 'ربما. ما الذي جاء بك إلى هنا؟', 'حسنا. ثم؟', 'مثير للفضول. تابع.'],
  },
};

// Език по код на държава (системният отговаря на ЕЗИКА на държавата си).
const COUNTRY_LANG = { BG: 'bg', RU: 'ru', UA: 'uk', KG: 'ky', DE: 'de', FR: 'fr', IT: 'it', ES: 'es', MX: 'es', US: 'en', IN: 'hi', JP: 'ja', CN: 'zh', BR: 'pt', SA: 'ar' };

function classify(text) {
  const t = String(text || '').toLowerCase();
  for (const intent of ['compliment', 'work', 'howareyou', 'greeting']) {
    if (KEYWORDS[intent].some(k => t.includes(k))) return intent;
  }
  return 'other';
}

// Системният отговаря на ЕЗИКА на държавата си (естествено за бот „от" дадена страна).
function pickReply(text, systemCountryCode) {
  const intent = classify(text);
  let lang = COUNTRY_LANG[systemCountryCode] || 'en';
  if (!BANKS[lang]) lang = 'en';
  const bank = BANKS[lang] || BANKS.en;
  const arr = bank[intent] || bank.other;
  return { intent, lang, text: arr[Math.floor(Math.random() * arr.length)] };
}

module.exports = { classify, pickReply, KEYWORDS, BANKS, COUNTRY_LANG };
