// Version: 1.0001
// i18n.js — преводен слой на „KCY Price Watch" за 15-те езика на екосистемата.
// Език по подразбиране: руски (до избор от потребителя при първо стартиране).
// Резервна верига при липсващ ключ: текущ → ru → en → самият ключ.
// Бележка: приложението показва САМО ценова информация и известия — без търговия,
// без плащания. Текстовете говорят за цени/прагове/известия, не за сделки.
import { LANGUAGES, languageByCode, RTL_CODES } from './languages.js';

const LS_KEY = 'pricewatch.lang';
const DEFAULT_LANG = 'ru';
const FALLBACK_LANG = 'en';

const STR = {
  // --- Избор на език / общи ---
  pick_lang: { bg:'Избери език', ru:'Выберите язык', uk:'Виберіть мову', en:'Choose language', de:'Sprache wählen', fr:'Choisir la langue', es:'Elegir idioma', 'es-MX':'Elegir idioma', it:'Scegli la lingua', pt:'Escolher idioma', ar:'اختر اللغة', hi:'भाषा चुनें', ja:'言語を選択', ky:'Тилди тандаңыз', 'zh-Hant':'選擇語言' },
  start_app: { bg:'Стартирай', ru:'Запустить', uk:'Запустити', en:'Start', de:'Starten', fr:'Démarrer', es:'Iniciar', 'es-MX':'Iniciar', it:'Avvia', pt:'Iniciar', ar:'ابدأ', hi:'शुरू करें', ja:'開始', ky:'Баштоо', 'zh-Hant':'開始' },
  language: { bg:'Език', ru:'Язык', uk:'Мова', en:'Language', de:'Sprache', fr:'Langue', es:'Idioma', 'es-MX':'Idioma', it:'Lingua', pt:'Idioma', ar:'اللغة', hi:'भाषा', ja:'言語', ky:'Тил', 'zh-Hant':'語言' },
  delete: { bg:'Изтрий', ru:'Удалить', uk:'Видалити', en:'Delete', de:'Löschen', fr:'Supprimer', es:'Eliminar', 'es-MX':'Eliminar', it:'Elimina', pt:'Excluir', ar:'حذف', hi:'हटाएं', ja:'削除', ky:'Өчүрүү', 'zh-Hant':'刪除' },

  // --- Заглавие на приложението ---
  app_name: { bg:'KCY Price Watch', ru:'KCY Price Watch', uk:'Цінова-стежка', en:'Price-Watch Bot', de:'Preis-Robot', fr:'Robot des prix', es:'Robot de precios', 'es-MX':'Robot de precios', it:'Robot dei prezzi', pt:'Robô de preços', ar:'روبوت مراقبة الأسعار', hi:'मूल्य-निगरानी बॉट', ja:'価格ウォッチボット', ky:'Баа-робот', 'zh-Hant':'價格監看機器人' },

  // --- Онбординг ---
  ob_headline: { bg:'Робот, който следи цените вместо теб', ru:'Робот, который следит за ценами вместо вас', uk:'Робот, який стежить за цінами замість вас', en:'A robot that watches prices for you', de:'Ein Roboter, der die Preise für dich beobachtet', fr:'Un robot qui surveille les prix pour vous', es:'Un robot que vigila los precios por ti', 'es-MX':'Un robot que vigila los precios por ti', it:'Un robot che controlla i prezzi al posto tuo', pt:'Um robô que vigia os preços por você', ar:'روبوت يراقب الأسعار نيابةً عنك', hi:'एक बॉट जो आपके लिए कीमतों पर नज़र रखता है', ja:'あなたの代わりに価格を見張るロボット', ky:'Сиздин ордуңузга бааларды көзөмөлдөгөн робот', 'zh-Hant':'替你盯緊價格的機器人' },
  ob_intro: { bg:'Този робот наблюдава избрани крипто и валутни курсове и те известява, щом цената падне под или се качи над зададен от теб праг.', ru:'Этот робот наблюдает за выбранными крипто- и валютными курсами и уведомляет вас, как только цена опустится ниже или поднимется выше заданного вами порога.', uk:'Цей робот спостерігає за обраними крипто- та валютними курсами й сповіщає вас, щойно ціна впаде нижче або підніметься вище заданого вами порога.', en:'This robot watches selected crypto and currency rates and notifies you as soon as a price drops below or rises above the threshold you set.', de:'Dieser Roboter beobachtet ausgewählte Krypto- und Währungskurse und benachrichtigt dich, sobald ein Preis unter oder über die von dir festgelegte Schwelle fällt bzw. steigt.', fr:'Ce robot surveille des taux crypto et de change choisis et vous avertit dès qu’un prix descend sous ou monte au-dessus du seuil que vous fixez.', es:'Este robot vigila tasas de cripto y divisas seleccionadas y te avisa en cuanto un precio baja por debajo o sube por encima del umbral que defines.', 'es-MX':'Este robot vigila tasas de cripto y divisas seleccionadas y te avisa en cuanto un precio baja por debajo o sube por encima del umbral que defines.', it:'Questo robot controlla tassi cripto e valutari selezionati e ti avvisa appena un prezzo scende sotto o sale sopra la soglia che imposti.', pt:'Este robô vigia taxas de cripto e moedas selecionadas e avisa você assim que um preço cai abaixo ou sobe acima do limite que você define.', ar:'يراقب هذا الروبوت أسعار العملات المشفّرة والعملات المختارة ويُنبّهك حالما يهبط السعر دون الحدّ الذي تحدده أو يتجاوزه.', hi:'यह बॉट चुनी हुई क्रिप्टो और मुद्रा दरों पर नज़र रखता है और जैसे ही कोई कीमत आपकी तय सीमा से नीचे गिरती है या ऊपर जाती है, आपको सूचित करता है।', ja:'このロボットは選んだ暗号資産・為替レートを監視し、価格が設定したしきい値を下回るか上回るとすぐに通知します。', ky:'Бул робот тандалган крипто жана валюта курстарын байкап, баа сиз койгон чектен төмөн түшкөндө же жогору чыкканда сизге кабарлайт.', 'zh-Hant':'此機器人監看你選定的加密貨幣與匯率，一旦價格跌破或漲過你設定的門檻就立即通知你。' },
  ob_what_title: { bg:'Какво прави роботът', ru:'Что делает робот', uk:'Що робить робот', en:'What the robot does', de:'Was der Roboter tut', fr:'Ce que fait le robot', es:'Qué hace el robot', 'es-MX':'Qué hace el robot', it:'Cosa fa il robot', pt:'O que o robô faz', ar:'ماذا يفعل الروبوت', hi:'बॉट क्या करता है', ja:'ロボットの機能', ky:'Робот эмне кылат', 'zh-Hant':'機器人會做什麼' },
  ob_feat1: { bg:'Следи BTC, ETH, BNB, SOL, XRP, ADA, DOGE и валути (EUR, GBP, RUB, …).', ru:'Следит за BTC, ETH, BNB, SOL, XRP, ADA, DOGE и валютами (EUR, GBP, RUB, …).', uk:'Стежить за BTC, ETH, BNB, SOL, XRP, ADA, DOGE та валютами (EUR, GBP, RUB, …).', en:'Watches BTC, ETH, BNB, SOL, XRP, ADA, DOGE and currencies (EUR, GBP, RUB, …).', de:'Beobachtet BTC, ETH, BNB, SOL, XRP, ADA, DOGE und Währungen (EUR, GBP, RUB, …).', fr:'Surveille BTC, ETH, BNB, SOL, XRP, ADA, DOGE et devises (EUR, GBP, RUB, …).', es:'Vigila BTC, ETH, BNB, SOL, XRP, ADA, DOGE y divisas (EUR, GBP, RUB, …).', 'es-MX':'Vigila BTC, ETH, BNB, SOL, XRP, ADA, DOGE y divisas (EUR, GBP, RUB, …).', it:'Controlla BTC, ETH, BNB, SOL, XRP, ADA, DOGE e valute (EUR, GBP, RUB, …).', pt:'Vigia BTC, ETH, BNB, SOL, XRP, ADA, DOGE e moedas (EUR, GBP, RUB, …).', ar:'يراقب BTC وETH وBNB وSOL وXRP وADA وDOGE والعملات (EUR وGBP وRUB …).', hi:'BTC, ETH, BNB, SOL, XRP, ADA, DOGE और मुद्राओं (EUR, GBP, RUB, …) पर नज़र रखता है।', ja:'BTC、ETH、BNB、SOL、XRP、ADA、DOGE と通貨（EUR、GBP、RUB …）を監視。', ky:'BTC, ETH, BNB, SOL, XRP, ADA, DOGE жана валюталарды (EUR, GBP, RUB, …) көзөмөлдөйт.', 'zh-Hant':'監看 BTC、ETH、BNB、SOL、XRP、ADA、DOGE 及貨幣（EUR、GBP、RUB …）。' },
  ob_feat2: { bg:'Проверява на 15 минути / 1 час / дневно — ти избираш.', ru:'Проверяет каждые 15 минут / 1 час / раз в день — вы выбираете.', uk:'Перевіряє кожні 15 хвилин / 1 годину / раз на день — ви обираєте.', en:'Checks every 15 minutes / 1 hour / daily — you choose.', de:'Prüft alle 15 Minuten / 1 Stunde / täglich — du wählst.', fr:'Vérifie toutes les 15 minutes / 1 heure / chaque jour — vous choisissez.', es:'Comprueba cada 15 minutos / 1 hora / a diario — tú eliges.', 'es-MX':'Revisa cada 15 minutos / 1 hora / a diario — tú eliges.', it:'Controlla ogni 15 minuti / 1 ora / al giorno — scegli tu.', pt:'Verifica a cada 15 minutos / 1 hora / por dia — você escolhe.', ar:'يتحقق كل ١٥ دقيقة / ساعة / يوميًا — أنت تختار.', hi:'हर 15 मिनट / 1 घंटे / रोज़ाना जाँचता है — आप चुनते हैं।', ja:'15分ごと／1時間ごと／毎日チェック — あなたが選びます。', ky:'Ар 15 мүнөттө / 1 саатта / күн сайын текшерет — сиз тандайсыз.', 'zh-Hant':'每 15 分鐘／1 小時／每日檢查一次——由你選擇。' },
  ob_feat3: { bg:'При достигнат праг праща <b>локално известие</b> на телефона.', ru:'При достижении порога отправляет <b>локальное уведомление</b> на телефон.', uk:'При досягненні порога надсилає <b>локальне сповіщення</b> на телефон.', en:'When the threshold is reached it sends a <b>local notification</b> to your phone.', de:'Bei Erreichen der Schwelle sendet er eine <b>lokale Benachrichtigung</b> an dein Telefon.', fr:'Quand le seuil est atteint, il envoie une <b>notification locale</b> sur votre téléphone.', es:'Cuando se alcanza el umbral envía una <b>notificación local</b> a tu teléfono.', 'es-MX':'Cuando se alcanza el umbral envía una <b>notificación local</b> a tu teléfono.', it:'Al raggiungimento della soglia invia una <b>notifica locale</b> sul telefono.', pt:'Quando o limite é atingido, envia uma <b>notificação local</b> ao seu telefone.', ar:'عند بلوغ الحدّ يرسل <b>إشعارًا محليًا</b> إلى هاتفك.', hi:'सीमा पर पहुँचने पर आपके फ़ोन पर <b>लोकल सूचना</b> भेजता है।', ja:'しきい値に達すると、端末に<b>ローカル通知</b>を送ります。', ky:'Чекке жеткенде телефонуңузга <b>жергиликтүү билдирүү</b> жөнөтөт.', 'zh-Hant':'達到門檻時，會向你的手機發送<b>本機通知</b>。' },
  ob_privacy: { bg:'Всичко работи на устройството. Без акаунт, без контакти, без проследяване. Цените идват от безплатни публични източници.', ru:'Всё работает на устройстве. Без аккаунта, без контактов, без слежки. Цены берутся из бесплатных публичных источников.', uk:'Усе працює на пристрої. Без акаунта, без контактів, без стеження. Ціни беруться з безкоштовних публічних джерел.', en:'Everything runs on the device. No account, no contacts, no tracking. Prices come from free public sources.', de:'Alles läuft auf dem Gerät. Kein Konto, keine Kontakte, kein Tracking. Die Preise stammen aus kostenlosen öffentlichen Quellen.', fr:'Tout fonctionne sur l’appareil. Sans compte, sans contacts, sans suivi. Les prix proviennent de sources publiques gratuites.', es:'Todo funciona en el dispositivo. Sin cuenta, sin contactos, sin rastreo. Los precios vienen de fuentes públicas gratuitas.', 'es-MX':'Todo funciona en el dispositivo. Sin cuenta, sin contactos, sin rastreo. Los precios vienen de fuentes públicas gratuitas.', it:'Tutto funziona sul dispositivo. Nessun account, nessun contatto, nessun tracciamento. I prezzi provengono da fonti pubbliche gratuite.', pt:'Tudo funciona no dispositivo. Sem conta, sem contatos, sem rastreamento. Os preços vêm de fontes públicas gratuitas.', ar:'كل شيء يعمل على الجهاز. بلا حساب، بلا جهات اتصال، بلا تتبّع. الأسعار من مصادر عامة مجانية.', hi:'सब कुछ डिवाइस पर चलता है। कोई खाता नहीं, कोई संपर्क नहीं, कोई ट्रैकिंग नहीं। कीमतें मुफ़्त सार्वजनिक स्रोतों से आती हैं।', ja:'すべて端末上で動作します。アカウント不要、連絡先不要、追跡なし。価格は無料の公開ソースから取得します。', ky:'Баары түзмөктө иштейт. Аккаунтсуз, байланыштарсыз, көзөмөлсүз. Баалар акысыз ачык булактардан алынат.', 'zh-Hant':'一切都在裝置上運行。無需帳戶、不存取聯絡人、不追蹤。價格來自免費的公開來源。' },
  ob_activate: { bg:'Активирай робота безплатно', ru:'Активировать робота бесплатно', uk:'Активувати робота безкоштовно', en:'Activate the robot for free', de:'Roboter kostenlos aktivieren', fr:'Activer le robot gratuitement', es:'Activar el robot gratis', 'es-MX':'Activar el robot gratis', it:'Attiva il robot gratis', pt:'Ativar o robô grátis', ar:'فعّل الروبوت مجانًا', hi:'बॉट मुफ़्त में सक्रिय करें', ja:'ロボットを無料で有効化', ky:'Роботту акысыз иштетүү', 'zh-Hant':'免費啟用機器人' },
  ob_all_free: { bg:'Всички функции са напълно безплатни.', ru:'Все функции полностью бесплатны.', uk:'Усі функції повністю безкоштовні.', en:'All features are completely free.', de:'Alle Funktionen sind völlig kostenlos.', fr:'Toutes les fonctions sont entièrement gratuites.', es:'Todas las funciones son completamente gratis.', 'es-MX':'Todas las funciones son completamente gratis.', it:'Tutte le funzioni sono completamente gratuite.', pt:'Todos os recursos são totalmente grátis.', ar:'كل الميزات مجانية تمامًا.', hi:'सभी सुविधाएँ पूरी तरह मुफ़्त हैं।', ja:'すべての機能は完全に無料です。', ky:'Бардык функциялар толугу менен акысыз.', 'zh-Hant':'所有功能完全免費。' },
  log_activated: { bg:'✅ Роботът е активиран', ru:'✅ Робот активирован', uk:'✅ Робота активовано', en:'✅ Robot activated', de:'✅ Roboter aktiviert', fr:'✅ Robot activé', es:'✅ Robot activado', 'es-MX':'✅ Robot activado', it:'✅ Robot attivato', pt:'✅ Robô ativado', ar:'✅ تم تفعيل الروبوت', hi:'✅ बॉट सक्रिय हुआ', ja:'✅ ロボットを有効化しました', ky:'✅ Робот иштетилди', 'zh-Hant':'✅ 機器人已啟用' },

  // --- Конфигурация ---
  cfg_title: { bg:'Настрой робота', ru:'Настройте робота', uk:'Налаштуйте робота', en:'Set up the robot', de:'Roboter einrichten', fr:'Configurer le robot', es:'Configura el robot', 'es-MX':'Configura el robot', it:'Configura il robot', pt:'Configure o robô', ar:'إعداد الروبوت', hi:'बॉट सेट करें', ja:'ロボットを設定', ky:'Роботту жөндөңүз', 'zh-Hant':'設定機器人' },
  cfg_intro: { bg:'Добави какво да следи роботът. Можеш да добавиш няколко.', ru:'Добавьте, за чем следить роботу. Можно добавить несколько.', uk:'Додайте, за чим стежити роботу. Можна додати кілька.', en:'Add what the robot should watch. You can add several.', de:'Füge hinzu, was der Roboter beobachten soll. Du kannst mehrere hinzufügen.', fr:'Ajoutez ce que le robot doit surveiller. Vous pouvez en ajouter plusieurs.', es:'Añade qué debe vigilar el robot. Puedes añadir varios.', 'es-MX':'Agrega qué debe vigilar el robot. Puedes agregar varios.', it:'Aggiungi cosa deve controllare il robot. Puoi aggiungerne diversi.', pt:'Adicione o que o robô deve vigiar. Você pode adicionar vários.', ar:'أضف ما يجب أن يراقبه الروبوت. يمكنك إضافة عدة عناصر.', hi:'जोड़ें कि बॉट को क्या देखना है। आप कई जोड़ सकते हैं।', ja:'ロボットが監視する対象を追加します。複数追加できます。', ky:'Робот эмнени көзөмөлдөшү керектигин кошуңуз. Бир нечесин кошсоңуз болот.', 'zh-Hant':'新增機器人要監看的對象，可新增多個。' },
  cfg_type: { bg:'Тип', ru:'Тип', uk:'Тип', en:'Type', de:'Typ', fr:'Type', es:'Tipo', 'es-MX':'Tipo', it:'Tipo', pt:'Tipo', ar:'النوع', hi:'प्रकार', ja:'タイプ', ky:'Түрү', 'zh-Hant':'類型' },
  cfg_crypto: { bg:'Крипто', ru:'Крипто', uk:'Крипто', en:'Crypto', de:'Krypto', fr:'Crypto', es:'Cripto', 'es-MX':'Cripto', it:'Cripto', pt:'Cripto', ar:'العملات المشفّرة', hi:'क्रिप्टो', ja:'暗号資産', ky:'Крипто', 'zh-Hant':'加密貨幣' },
  cfg_fx: { bg:'Валута (FX)', ru:'Валюта (FX)', uk:'Валюта (FX)', en:'Currency (FX)', de:'Währung (FX)', fr:'Devise (FX)', es:'Divisa (FX)', 'es-MX':'Divisa (FX)', it:'Valuta (FX)', pt:'Moeda (FX)', ar:'العملة (FX)', hi:'मुद्रा (FX)', ja:'通貨 (FX)', ky:'Валюта (FX)', 'zh-Hant':'貨幣 (FX)' },
  cfg_coin_label: { bg:'Монета (цена в USD)', ru:'Монета (цена в USD)', uk:'Монета (ціна в USD)', en:'Coin (price in USD)', de:'Coin (Preis in USD)', fr:'Pièce (prix en USD)', es:'Moneda (precio en USD)', 'es-MX':'Moneda (precio en USD)', it:'Moneta (prezzo in USD)', pt:'Moeda (preço em USD)', ar:'العملة (السعر بالدولار)', hi:'सिक्का (USD में कीमत)', ja:'コイン（USD価格）', ky:'Коин (баасы USD менен)', 'zh-Hant':'幣別（美元價格）' },
  cfg_fx_label: { bg:'Валута (за 1 USD)', ru:'Валюта (за 1 USD)', uk:'Валюта (за 1 USD)', en:'Currency (per 1 USD)', de:'Währung (pro 1 USD)', fr:'Devise (pour 1 USD)', es:'Divisa (por 1 USD)', 'es-MX':'Divisa (por 1 USD)', it:'Valuta (per 1 USD)', pt:'Moeda (por 1 USD)', ar:'العملة (لكل 1 دولار)', hi:'मुद्रा (प्रति 1 USD)', ja:'通貨（1 USD あたり）', ky:'Валюта (1 USD үчүн)', 'zh-Hant':'貨幣（每 1 美元）' },
  cfg_condition: { bg:'Условие', ru:'Условие', uk:'Умова', en:'Condition', de:'Bedingung', fr:'Condition', es:'Condición', 'es-MX':'Condición', it:'Condizione', pt:'Condição', ar:'الشرط', hi:'शर्त', ja:'条件', ky:'Шарт', 'zh-Hant':'條件' },
  cfg_below: { bg:'Падне под', ru:'Опустится ниже', uk:'Впаде нижче', en:'Drops below', de:'Fällt unter', fr:'Descend sous', es:'Baja por debajo', 'es-MX':'Baja por debajo', it:'Scende sotto', pt:'Cai abaixo', ar:'يهبط دون', hi:'नीचे गिरे', ja:'下回る', ky:'Төмөн түшөт', 'zh-Hant':'跌破' },
  cfg_above: { bg:'Качи се над', ru:'Поднимется выше', uk:'Підніметься вище', en:'Rises above', de:'Steigt über', fr:'Monte au-dessus', es:'Sube por encima', 'es-MX':'Sube por encima', it:'Sale sopra', pt:'Sobe acima', ar:'يتجاوز', hi:'ऊपर जाए', ja:'上回る', ky:'Жогору чыгат', 'zh-Hant':'漲過' },
  cfg_threshold: { bg:'Прагова стойност', ru:'Пороговое значение', uk:'Порогове значення', en:'Threshold value', de:'Schwellenwert', fr:'Valeur seuil', es:'Valor umbral', 'es-MX':'Valor umbral', it:'Valore soglia', pt:'Valor limite', ar:'القيمة الحدّية', hi:'सीमा मान', ja:'しきい値', ky:'Чектик маани', 'zh-Hant':'門檻值' },
  cfg_threshold_ph: { bg:'напр. 60000', ru:'напр. 60000', uk:'напр. 60000', en:'e.g. 60000', de:'z. B. 60000', fr:'p. ex. 60000', es:'p. ej. 60000', 'es-MX':'p. ej. 60000', it:'es. 60000', pt:'ex. 60000', ar:'مثل 60000', hi:'जैसे 60000', ja:'例: 60000', ky:'мис. 60000', 'zh-Hant':'例如 60000' },
  cfg_freq: { bg:'Честота на проверка', ru:'Частота проверки', uk:'Частота перевірки', en:'Check frequency', de:'Prüfhäufigkeit', fr:'Fréquence de vérification', es:'Frecuencia de comprobación', 'es-MX':'Frecuencia de revisión', it:'Frequenza di controllo', pt:'Frequência de verificação', ar:'تكرار الفحص', hi:'जाँच की आवृत्ति', ja:'チェック頻度', ky:'Текшерүү жыштыгы', 'zh-Hant':'檢查頻率' },
  freq_15min: { bg:'На 15 минути', ru:'Каждые 15 минут', uk:'Кожні 15 хвилин', en:'Every 15 minutes', de:'Alle 15 Minuten', fr:'Toutes les 15 minutes', es:'Cada 15 minutos', 'es-MX':'Cada 15 minutos', it:'Ogni 15 minuti', pt:'A cada 15 minutos', ar:'كل ١٥ دقيقة', hi:'हर 15 मिनट', ja:'15分ごと', ky:'Ар 15 мүнөттө', 'zh-Hant':'每 15 分鐘' },
  freq_1h: { bg:'На 1 час', ru:'Каждый час', uk:'Щогодини', en:'Every hour', de:'Stündlich', fr:'Toutes les heures', es:'Cada hora', 'es-MX':'Cada hora', it:'Ogni ora', pt:'A cada hora', ar:'كل ساعة', hi:'हर घंटे', ja:'1時間ごと', ky:'Ар саатта', 'zh-Hant':'每小時' },
  freq_daily: { bg:'Веднъж дневно', ru:'Раз в день', uk:'Раз на день', en:'Once a day', de:'Einmal täglich', fr:'Une fois par jour', es:'Una vez al día', 'es-MX':'Una vez al día', it:'Una volta al giorno', pt:'Uma vez por dia', ar:'مرة يوميًا', hi:'दिन में एक बार', ja:'1日1回', ky:'Күнүнө бир жолу', 'zh-Hant':'每天一次' },
  cfg_add: { bg:'Добави наблюдение', ru:'Добавить наблюдение', uk:'Додати спостереження', en:'Add a watch', de:'Beobachtung hinzufügen', fr:'Ajouter une surveillance', es:'Añadir seguimiento', 'es-MX':'Agregar seguimiento', it:'Aggiungi monitoraggio', pt:'Adicionar monitoramento', ar:'أضف مراقبة', hi:'निगरानी जोड़ें', ja:'ウォッチを追加', ky:'Көзөмөл кошуу', 'zh-Hant':'新增監看' },
  cfg_current_n: { bg:'Текущи наблюдения ({0})', ru:'Текущие наблюдения ({0})', uk:'Поточні спостереження ({0})', en:'Current watches ({0})', de:'Aktuelle Beobachtungen ({0})', fr:'Surveillances actuelles ({0})', es:'Seguimientos actuales ({0})', 'es-MX':'Seguimientos actuales ({0})', it:'Monitoraggi attuali ({0})', pt:'Monitoramentos atuais ({0})', ar:'المراقبات الحالية ({0})', hi:'वर्तमान निगरानी ({0})', ja:'現在のウォッチ ({0})', ky:'Учурдагы көзөмөлдөр ({0})', 'zh-Hant':'目前的監看 ({0})' },
  cfg_none_yet: { bg:'Още няма добавени наблюдения.', ru:'Пока нет добавленных наблюдений.', uk:'Поки немає доданих спостережень.', en:'No watches added yet.', de:'Noch keine Beobachtungen hinzugefügt.', fr:'Aucune surveillance ajoutée pour l’instant.', es:'Aún no hay seguimientos añadidos.', 'es-MX':'Aún no hay seguimientos agregados.', it:'Ancora nessun monitoraggio aggiunto.', pt:'Nenhum monitoramento adicionado ainda.', ar:'لا توجد مراقبات مضافة بعد.', hi:'अभी तक कोई निगरानी नहीं जोड़ी गई।', ja:'まだウォッチが追加されていません。', ky:'Азырынча кошулган көзөмөл жок.', 'zh-Hant':'尚未新增任何監看。' },
  cfg_to_perms: { bg:'Продължи към разрешения', ru:'Перейти к разрешениям', uk:'Перейти до дозволів', en:'Continue to permissions', de:'Weiter zu den Berechtigungen', fr:'Continuer vers les autorisations', es:'Continuar a permisos', 'es-MX':'Continuar a permisos', it:'Continua ai permessi', pt:'Continuar para permissões', ar:'المتابعة إلى الأذونات', hi:'अनुमतियों पर जाएँ', ja:'権限へ進む', ky:'Уруксаттарга өтүү', 'zh-Hant':'前往權限' },
  cfg_invalid: { bg:'Въведи валидна прагова стойност.', ru:'Введите корректное пороговое значение.', uk:'Введіть коректне порогове значення.', en:'Enter a valid threshold value.', de:'Gib einen gültigen Schwellenwert ein.', fr:'Saisissez une valeur seuil valide.', es:'Introduce un valor umbral válido.', 'es-MX':'Ingresa un valor umbral válido.', it:'Inserisci un valore soglia valido.', pt:'Insira um valor limite válido.', ar:'أدخل قيمة حدّية صحيحة.', hi:'मान्य सीमा मान दर्ज करें।', ja:'有効なしきい値を入力してください。', ky:'Жарактуу чектик маани киргизиңиз.', 'zh-Hant':'請輸入有效的門檻值。' },
  cfg_limit: { bg:'Достигнат лимит ({0}).', ru:'Достигнут лимит ({0}).', uk:'Досягнуто ліміту ({0}).', en:'Limit reached ({0}).', de:'Limit erreicht ({0}).', fr:'Limite atteinte ({0}).', es:'Límite alcanzado ({0}).', 'es-MX':'Límite alcanzado ({0}).', it:'Limite raggiunto ({0}).', pt:'Limite atingido ({0}).', ar:'تم بلوغ الحدّ ({0}).', hi:'सीमा पूरी हुई ({0}).', ja:'上限に達しました ({0})。', ky:'Чек ашты ({0}).', 'zh-Hant':'已達上限 ({0})。' },
  log_added: { bg:'➕ Добавено: {0} {1} {2}', ru:'➕ Добавлено: {0} {1} {2}', uk:'➕ Додано: {0} {1} {2}', en:'➕ Added: {0} {1} {2}', de:'➕ Hinzugefügt: {0} {1} {2}', fr:'➕ Ajouté : {0} {1} {2}', es:'➕ Añadido: {0} {1} {2}', 'es-MX':'➕ Agregado: {0} {1} {2}', it:'➕ Aggiunto: {0} {1} {2}', pt:'➕ Adicionado: {0} {1} {2}', ar:'➕ تمت الإضافة: {0} {1} {2}', hi:'➕ जोड़ा गया: {0} {1} {2}', ja:'➕ 追加: {0} {1} {2}', ky:'➕ Кошулду: {0} {1} {2}', 'zh-Hant':'➕ 已新增：{0} {1} {2}' },

  // --- Разрешения ---
  perm_title: { bg:'Разрешения', ru:'Разрешения', uk:'Дозволи', en:'Permissions', de:'Berechtigungen', fr:'Autorisations', es:'Permisos', 'es-MX':'Permisos', it:'Permessi', pt:'Permissões', ar:'الأذونات', hi:'अनुमतियाँ', ja:'権限', ky:'Уруксаттар', 'zh-Hant':'權限' },
  perm_intro: { bg:'Роботът иска само това, което му трябва. Нищо повече. Можеш да го промениш по всяко време.', ru:'Робот запрашивает только необходимое. Ничего лишнего. Это можно изменить в любой момент.', uk:'Робот запитує лише необхідне. Нічого зайвого. Це можна змінити будь-коли.', en:'The robot asks only for what it needs. Nothing more. You can change this any time.', de:'Der Roboter fragt nur nach dem, was er braucht. Nicht mehr. Du kannst das jederzeit ändern.', fr:'Le robot ne demande que ce dont il a besoin. Rien de plus. Vous pouvez le changer à tout moment.', es:'El robot pide solo lo que necesita. Nada más. Puedes cambiarlo cuando quieras.', 'es-MX':'El robot pide solo lo que necesita. Nada más. Puedes cambiarlo cuando quieras.', it:'Il robot chiede solo ciò che gli serve. Nulla di più. Puoi cambiarlo in qualsiasi momento.', pt:'O robô pede apenas o necessário. Nada mais. Você pode mudar isso a qualquer momento.', ar:'يطلب الروبوت ما يحتاجه فقط. لا أكثر. يمكنك تغيير ذلك في أي وقت.', hi:'बॉट केवल वही माँगता है जो उसे चाहिए। इससे ज़्यादा नहीं। आप इसे कभी भी बदल सकते हैं।', ja:'ロボットは必要なものだけを求めます。それ以上は不要です。いつでも変更できます。', ky:'Робот керектүүсүн гана сурайт. Ашыкчасы жок. Аны каалаган убакта өзгөртө аласыз.', 'zh-Hant':'機器人只要求必要的權限，別無其他。你可隨時更改。' },
  perm_notif_title: { bg:'🔔 Известия', ru:'🔔 Уведомления', uk:'🔔 Сповіщення', en:'🔔 Notifications', de:'🔔 Benachrichtigungen', fr:'🔔 Notifications', es:'🔔 Notificaciones', 'es-MX':'🔔 Notificaciones', it:'🔔 Notifiche', pt:'🔔 Notificações', ar:'🔔 الإشعارات', hi:'🔔 सूचनाएँ', ja:'🔔 通知', ky:'🔔 Билдирүүлөр', 'zh-Hant':'🔔 通知' },
  perm_notif_desc: { bg:'За да те уведоми, когато цена достигне твоя праг. Известията са локални — не минават през сървър.', ru:'Чтобы уведомить вас, когда цена достигнет вашего порога. Уведомления локальные — не проходят через сервер.', uk:'Щоб сповістити вас, коли ціна досягне вашого порога. Сповіщення локальні — не проходять через сервер.', en:'To notify you when a price reaches your threshold. Notifications are local — they do not go through a server.', de:'Um dich zu benachrichtigen, wenn ein Preis deine Schwelle erreicht. Die Benachrichtigungen sind lokal — sie laufen nicht über einen Server.', fr:'Pour vous prévenir quand un prix atteint votre seuil. Les notifications sont locales — elles ne passent pas par un serveur.', es:'Para avisarte cuando un precio alcance tu umbral. Las notificaciones son locales — no pasan por un servidor.', 'es-MX':'Para avisarte cuando un precio alcance tu umbral. Las notificaciones son locales — no pasan por un servidor.', it:'Per avvisarti quando un prezzo raggiunge la tua soglia. Le notifiche sono locali — non passano da un server.', pt:'Para avisar você quando um preço atingir seu limite. As notificações são locais — não passam por um servidor.', ar:'لتنبيهك عندما يبلغ السعر حدّك. الإشعارات محلية — لا تمرّ عبر خادم.', hi:'जब कोई कीमत आपकी सीमा तक पहुँचे तो आपको सूचित करने के लिए। सूचनाएँ लोकल हैं — किसी सर्वर से नहीं जातीं।', ja:'価格がしきい値に達したときに通知するためです。通知はローカルで、サーバーを経由しません。', ky:'Баа сиздин чекке жеткенде кабарлоо үчүн. Билдирүүлөр жергиликтүү — сервер аркылуу өтпөйт.', 'zh-Hant':'在價格達到你的門檻時通知你。通知為本機通知，不經過伺服器。' },
  perm_net_title: { bg:'🌐 Достъп до интернет', ru:'🌐 Доступ к интернету', uk:'🌐 Доступ до інтернету', en:'🌐 Internet access', de:'🌐 Internetzugang', fr:'🌐 Accès à Internet', es:'🌐 Acceso a Internet', 'es-MX':'🌐 Acceso a Internet', it:'🌐 Accesso a Internet', pt:'🌐 Acesso à Internet', ar:'🌐 الوصول إلى الإنترنت', hi:'🌐 इंटरनेट एक्सेस', ja:'🌐 インターネット接続', ky:'🌐 Интернетке мүмкүндүк', 'zh-Hant':'🌐 網路存取' },
  perm_net_desc: { bg:'За да чете цените от безплатните публични източници (Binance, CoinGecko, open.er-api.com). Без него роботът не може да проверява цени.', ru:'Чтобы читать цены из бесплатных публичных источников (Binance, CoinGecko, open.er-api.com). Без него робот не может проверять цены.', uk:'Щоб читати ціни з безкоштовних публічних джерел (Binance, CoinGecko, open.er-api.com). Без нього робот не може перевіряти ціни.', en:'To read prices from the free public sources (Binance, CoinGecko, open.er-api.com). Without it the robot cannot check prices.', de:'Um die Preise aus den kostenlosen öffentlichen Quellen (Binance, CoinGecko, open.er-api.com) zu lesen. Ohne ihn kann der Roboter keine Preise prüfen.', fr:'Pour lire les prix depuis les sources publiques gratuites (Binance, CoinGecko, open.er-api.com). Sans cela, le robot ne peut pas vérifier les prix.', es:'Para leer los precios de las fuentes públicas gratuitas (Binance, CoinGecko, open.er-api.com). Sin él, el robot no puede comprobar precios.', 'es-MX':'Para leer los precios de las fuentes públicas gratuitas (Binance, CoinGecko, open.er-api.com). Sin él, el robot no puede revisar precios.', it:'Per leggere i prezzi dalle fonti pubbliche gratuite (Binance, CoinGecko, open.er-api.com). Senza, il robot non può controllare i prezzi.', pt:'Para ler os preços das fontes públicas gratuitas (Binance, CoinGecko, open.er-api.com). Sem ele, o robô não consegue verificar preços.', ar:'لقراءة الأسعار من المصادر العامة المجانية (Binance وCoinGecko وopen.er-api.com). بدونه لا يستطيع الروبوت فحص الأسعار.', hi:'मुफ़्त सार्वजनिक स्रोतों (Binance, CoinGecko, open.er-api.com) से कीमतें पढ़ने के लिए। इसके बिना बॉट कीमतें जाँच नहीं सकता।', ja:'無料の公開ソース（Binance、CoinGecko、open.er-api.com）から価格を読み取るためです。これがないとロボットは価格を確認できません。', ky:'Бааларды акысыз ачык булактардан (Binance, CoinGecko, open.er-api.com) окуу үчүн. Ансыз робот бааларды текшере албайт.', 'zh-Hant':'用於從免費公開來源（Binance、CoinGecko、open.er-api.com）讀取價格。沒有它，機器人無法檢查價格。' },
  perm_needed: { bg:'нужно', ru:'необходимо', uk:'потрібно', en:'required', de:'erforderlich', fr:'requis', es:'necesario', 'es-MX':'necesario', it:'necessario', pt:'necessário', ar:'مطلوب', hi:'आवश्यक', ja:'必須', ky:'керек', 'zh-Hant':'必要' },
  perm_not_asked: { bg:'❌ Роботът НЕ иска: контакти, местоположение, камера, файлове, реклами или анализи.', ru:'❌ Робот НЕ запрашивает: контакты, местоположение, камеру, файлы, рекламу или аналитику.', uk:'❌ Робот НЕ запитує: контакти, місцезнаходження, камеру, файли, рекламу чи аналітику.', en:'❌ The robot does NOT ask for: contacts, location, camera, files, ads or analytics.', de:'❌ Der Roboter fragt NICHT nach: Kontakten, Standort, Kamera, Dateien, Werbung oder Analyse.', fr:'❌ Le robot ne demande PAS : contacts, localisation, caméra, fichiers, publicités ou analyses.', es:'❌ El robot NO pide: contactos, ubicación, cámara, archivos, anuncios ni analíticas.', 'es-MX':'❌ El robot NO pide: contactos, ubicación, cámara, archivos, anuncios ni analíticas.', it:'❌ Il robot NON chiede: contatti, posizione, fotocamera, file, pubblicità o analisi.', pt:'❌ O robô NÃO pede: contatos, localização, câmera, arquivos, anúncios ou análises.', ar:'❌ الروبوت لا يطلب: جهات الاتصال أو الموقع أو الكاميرا أو الملفات أو الإعلانات أو التحليلات.', hi:'❌ बॉट नहीं माँगता: संपर्क, स्थान, कैमरा, फ़ाइलें, विज्ञापन या एनालिटिक्स।', ja:'❌ ロボットは要求しません：連絡先、位置情報、カメラ、ファイル、広告、分析。', ky:'❌ Робот сурабайт: байланыштар, жайгашуу, камера, файлдар, жарнама же аналитика.', 'zh-Hant':'❌ 機器人不會要求：聯絡人、位置、相機、檔案、廣告或分析。' },
  perm_done: { bg:'Готово — към таблото', ru:'Готово — к панели', uk:'Готово — до панелі', en:'Done — to the dashboard', de:'Fertig — zum Dashboard', fr:'Terminé — vers le tableau de bord', es:'Listo — al panel', 'es-MX':'Listo — al panel', it:'Fatto — alla dashboard', pt:'Pronto — para o painel', ar:'تم — إلى اللوحة', hi:'हो गया — डैशबोर्ड पर', ja:'完了 — ダッシュボードへ', ky:'Даяр — башкаруу панелине', 'zh-Hant':'完成 — 前往儀表板' },

  // --- Табло ---
  dash_title: { bg:'Табло на робота', ru:'Панель робота', uk:'Панель робота', en:'Robot dashboard', de:'Roboter-Dashboard', fr:'Tableau de bord du robot', es:'Panel del robot', 'es-MX':'Panel del robot', it:'Dashboard del robot', pt:'Painel do robô', ar:'لوحة الروبوت', hi:'बॉट डैशबोर्ड', ja:'ロボットのダッシュボード', ky:'Робот панели', 'zh-Hant':'機器人儀表板' },
  dash_master: { bg:'Главен ключ', ru:'Главный выключатель', uk:'Головний вимикач', en:'Master switch', de:'Hauptschalter', fr:'Interrupteur principal', es:'Interruptor principal', 'es-MX':'Interruptor principal', it:'Interruttore principale', pt:'Interruptor principal', ar:'المفتاح الرئيسي', hi:'मुख्य स्विच', ja:'メインスイッチ', ky:'Башкы өчүргүч', 'zh-Hant':'主開關' },
  dash_on: { bg:'Роботът следи цените', ru:'Робот следит за ценами', uk:'Робот стежить за цінами', en:'The robot is watching prices', de:'Der Roboter beobachtet die Preise', fr:'Le robot surveille les prix', es:'El robot vigila los precios', 'es-MX':'El robot vigila los precios', it:'Il robot controlla i prezzi', pt:'O robô está vigiando os preços', ar:'الروبوت يراقب الأسعار', hi:'बॉट कीमतों पर नज़र रख रहा है', ja:'ロボットが価格を監視中', ky:'Робот бааларды көзөмөлдөп жатат', 'zh-Hant':'機器人正在監看價格' },
  dash_off: { bg:'Роботът е спрян', ru:'Робот остановлен', uk:'Робот зупинено', en:'The robot is stopped', de:'Der Roboter ist gestoppt', fr:'Le robot est arrêté', es:'El robot está detenido', 'es-MX':'El robot está detenido', it:'Il robot è fermo', pt:'O robô está parado', ar:'الروبوت متوقف', hi:'बॉट रुका हुआ है', ja:'ロボットは停止中', ky:'Робот токтотулду', 'zh-Hant':'機器人已停止' },
  dash_check_now: { bg:'Провери сега', ru:'Проверить сейчас', uk:'Перевірити зараз', en:'Check now', de:'Jetzt prüfen', fr:'Vérifier maintenant', es:'Comprobar ahora', 'es-MX':'Revisar ahora', it:'Controlla ora', pt:'Verificar agora', ar:'افحص الآن', hi:'अभी जाँचें', ja:'今すぐ確認', ky:'Азыр текшерүү', 'zh-Hant':'立即檢查' },
  dash_add_more: { bg:'+ Добави наблюдение', ru:'+ Добавить наблюдение', uk:'+ Додати спостереження', en:'+ Add a watch', de:'+ Beobachtung hinzufügen', fr:'+ Ajouter une surveillance', es:'+ Añadir seguimiento', 'es-MX':'+ Agregar seguimiento', it:'+ Aggiungi monitoraggio', pt:'+ Adicionar monitoramento', ar:'+ أضف مراقبة', hi:'+ निगरानी जोड़ें', ja:'+ ウォッチを追加', ky:'+ Көзөмөл кошуу', 'zh-Hant':'+ 新增監看' },
  dash_watches_n: { bg:'Наблюдения ({0})', ru:'Наблюдения ({0})', uk:'Спостереження ({0})', en:'Watches ({0})', de:'Beobachtungen ({0})', fr:'Surveillances ({0})', es:'Seguimientos ({0})', 'es-MX':'Seguimientos ({0})', it:'Monitoraggi ({0})', pt:'Monitoramentos ({0})', ar:'المراقبات ({0})', hi:'निगरानी ({0})', ja:'ウォッチ ({0})', ky:'Көзөмөлдөр ({0})', 'zh-Hant':'監看 ({0})' },
  dash_no_watches: { bg:'Няма наблюдения. Натисни „+ Добави наблюдение".', ru:'Нет наблюдений. Нажмите «+ Добавить наблюдение».', uk:'Немає спостережень. Натисніть «+ Додати спостереження».', en:'No watches. Tap “+ Add a watch”.', de:'Keine Beobachtungen. Tippe auf „+ Beobachtung hinzufügen".', fr:'Aucune surveillance. Touchez « + Ajouter une surveillance ».', es:'Sin seguimientos. Toca «+ Añadir seguimiento».', 'es-MX':'Sin seguimientos. Toca «+ Agregar seguimiento».', it:'Nessun monitoraggio. Tocca “+ Aggiungi monitoraggio".', pt:'Sem monitoramentos. Toque em “+ Adicionar monitoramento".', ar:'لا مراقبات. اضغط «+ أضف مراقبة».', hi:'कोई निगरानी नहीं। “+ निगरानी जोड़ें" दबाएँ।', ja:'ウォッチがありません。「+ ウォッチを追加」をタップ。', ky:'Көзөмөл жок. «+ Көзөмөл кошуу» басыңыз.', 'zh-Hant':'沒有監看。點擊「+ 新增監看」。' },
  dash_last: { bg:'последно:', ru:'последнее:', uk:'останнє:', en:'last:', de:'zuletzt:', fr:'dernier :', es:'último:', 'es-MX':'último:', it:'ultimo:', pt:'último:', ar:'الأخير:', hi:'अंतिम:', ja:'最新:', ky:'акыркы:', 'zh-Hant':'最新：' },
  dash_log: { bg:'Дневник', ru:'Журнал', uk:'Журнал', en:'Log', de:'Protokoll', fr:'Journal', es:'Registro', 'es-MX':'Registro', it:'Registro', pt:'Registro', ar:'السجل', hi:'लॉग', ja:'ログ', ky:'Журнал', 'zh-Hant':'紀錄' },
  dash_log_empty: { bg:'Дневникът е празен.', ru:'Журнал пуст.', uk:'Журнал порожній.', en:'The log is empty.', de:'Das Protokoll ist leer.', fr:'Le journal est vide.', es:'El registro está vacío.', 'es-MX':'El registro está vacío.', it:'Il registro è vuoto.', pt:'O registro está vazio.', ar:'السجل فارغ.', hi:'लॉग खाली है।', ja:'ログは空です。', ky:'Журнал бош.', 'zh-Hant':'紀錄為空。' },
  pause: { bg:'Пауза', ru:'Пауза', uk:'Пауза', en:'Pause', de:'Pause', fr:'Pause', es:'Pausa', 'es-MX':'Pausa', it:'Pausa', pt:'Pausar', ar:'إيقاف مؤقت', hi:'रोकें', ja:'一時停止', ky:'Тыныгуу', 'zh-Hant':'暫停' },
  resume: { bg:'Пусни', ru:'Возобновить', uk:'Відновити', en:'Resume', de:'Fortsetzen', fr:'Reprendre', es:'Reanudar', 'es-MX':'Reanudar', it:'Riprendi', pt:'Retomar', ar:'استئناف', hi:'फिर शुरू करें', ja:'再開', ky:'Улантуу', 'zh-Hant':'繼續' },

  // --- Значки за състояние ---
  badge_paused: { bg:'на пауза', ru:'на паузе', uk:'на паузі', en:'paused', de:'pausiert', fr:'en pause', es:'en pausa', 'es-MX':'en pausa', it:'in pausa', pt:'em pausa', ar:'متوقف مؤقتًا', hi:'रुका हुआ', ja:'一時停止中', ky:'тыныгууда', 'zh-Hant':'已暫停' },
  badge_error: { bg:'грешка', ru:'ошибка', uk:'помилка', en:'error', de:'Fehler', fr:'erreur', es:'error', 'es-MX':'error', it:'errore', pt:'erro', ar:'خطأ', hi:'त्रुटि', ja:'エラー', ky:'ката', 'zh-Hant':'錯誤' },
  badge_hit: { bg:'праг достигнат', ru:'порог достигнут', uk:'поріг досягнуто', en:'threshold reached', de:'Schwelle erreicht', fr:'seuil atteint', es:'umbral alcanzado', 'es-MX':'umbral alcanzado', it:'soglia raggiunta', pt:'limite atingido', ar:'بلغ الحدّ', hi:'सीमा पर पहुँचा', ja:'しきい値到達', ky:'чекке жетти', 'zh-Hant':'已達門檻' },
  badge_watching: { bg:'следи', ru:'следит', uk:'стежить', en:'watching', de:'beobachtet', fr:'surveille', es:'vigilando', 'es-MX':'vigilando', it:'in osservazione', pt:'vigiando', ar:'يراقب', hi:'निगरानी में', ja:'監視中', ky:'көзөмөлдөөдө', 'zh-Hant':'監看中' },

  // --- Долна навигация ---
  nav_dashboard: { bg:'Табло', ru:'Панель', uk:'Панель', en:'Dashboard', de:'Dashboard', fr:'Tableau', es:'Panel', 'es-MX':'Panel', it:'Dashboard', pt:'Painel', ar:'اللوحة', hi:'डैशबोर्ड', ja:'ダッシュボード', ky:'Панель', 'zh-Hant':'儀表板' },
  nav_settings: { bg:'Настройки', ru:'Настройки', uk:'Налаштування', en:'Settings', de:'Einstellungen', fr:'Réglages', es:'Ajustes', 'es-MX':'Ajustes', it:'Impostazioni', pt:'Configurações', ar:'الإعدادات', hi:'सेटिंग्स', ja:'設定', ky:'Жөндөөлөр', 'zh-Hant':'設定' },
  nav_permissions: { bg:'Разрешения', ru:'Разрешения', uk:'Дозволи', en:'Permissions', de:'Berechtigungen', fr:'Autorisations', es:'Permisos', 'es-MX':'Permisos', it:'Permessi', pt:'Permissões', ar:'الأذونات', hi:'अनुमतियाँ', ja:'権限', ky:'Уруксаттар', 'zh-Hant':'權限' },

  // --- Известия и журнал на планировчика ---
  notif_title: { bg:'KCY Price Watch: праг достигнат', ru:'KCY Price Watch: порог достигнут', uk:'Цінова-стежка: поріг досягнуто', en:'Price-Watch Bot: threshold reached', de:'Preis-Robot: Schwelle erreicht', fr:'Robot des prix : seuil atteint', es:'Robot de precios: umbral alcanzado', 'es-MX':'Robot de precios: umbral alcanzado', it:'Robot dei prezzi: soglia raggiunta', pt:'Robô de preços: limite atingido', ar:'روبوت الأسعار: بلغ الحدّ', hi:'मूल्य-निगरानी बॉट: सीमा पर पहुँचा', ja:'価格ウォッチボット：しきい値到達', ky:'Баа-робот: чекке жетти', 'zh-Hant':'價格監看機器人：已達門檻' },
  notif_body: { bg:'{0} — сега {1}', ru:'{0} — сейчас {1}', uk:'{0} — зараз {1}', en:'{0} — now {1}', de:'{0} — jetzt {1}', fr:'{0} — maintenant {1}', es:'{0} — ahora {1}', 'es-MX':'{0} — ahora {1}', it:'{0} — ora {1}', pt:'{0} — agora {1}', ar:'{0} — الآن {1}', hi:'{0} — अभी {1}', ja:'{0} — 現在 {1}', ky:'{0} — азыр {1}', 'zh-Hant':'{0} — 目前 {1}' },
  log_hit: { bg:'🔔 {0} достигнат — стойност {1}', ru:'🔔 {0} достигнут — значение {1}', uk:'🔔 {0} досягнуто — значення {1}', en:'🔔 {0} reached — value {1}', de:'🔔 {0} erreicht — Wert {1}', fr:'🔔 {0} atteint — valeur {1}', es:'🔔 {0} alcanzado — valor {1}', 'es-MX':'🔔 {0} alcanzado — valor {1}', it:'🔔 {0} raggiunto — valore {1}', pt:'🔔 {0} atingido — valor {1}', ar:'🔔 {0} تحقق — القيمة {1}', hi:'🔔 {0} पहुँचा — मान {1}', ja:'🔔 {0} 到達 — 値 {1}', ky:'🔔 {0} жетти — маани {1}', 'zh-Hant':'🔔 {0} 已達 — 數值 {1}' },
  log_error: { bg:'⚠️ {0}: {1}', ru:'⚠️ {0}: {1}', uk:'⚠️ {0}: {1}', en:'⚠️ {0}: {1}', de:'⚠️ {0}: {1}', fr:'⚠️ {0} : {1}', es:'⚠️ {0}: {1}', 'es-MX':'⚠️ {0}: {1}', it:'⚠️ {0}: {1}', pt:'⚠️ {0}: {1}', ar:'⚠️ {0}: {1}', hi:'⚠️ {0}: {1}', ja:'⚠️ {0}：{1}', ky:'⚠️ {0}: {1}', 'zh-Hant':'⚠️ {0}：{1}' },
  log_started: { bg:'▶️ Роботът е пуснат', ru:'▶️ Робот запущен', uk:'▶️ Робота запущено', en:'▶️ Robot started', de:'▶️ Roboter gestartet', fr:'▶️ Robot démarré', es:'▶️ Robot iniciado', 'es-MX':'▶️ Robot iniciado', it:'▶️ Robot avviato', pt:'▶️ Robô iniciado', ar:'▶️ تم تشغيل الروبوت', hi:'▶️ बॉट चालू हुआ', ja:'▶️ ロボットを開始', ky:'▶️ Робот иштеди', 'zh-Hant':'▶️ 機器人已啟動' },
  log_stopped: { bg:'⏸️ Роботът е спрян', ru:'⏸️ Робот остановлен', uk:'⏸️ Робота зупинено', en:'⏸️ Robot stopped', de:'⏸️ Roboter gestoppt', fr:'⏸️ Robot arrêté', es:'⏸️ Robot detenido', 'es-MX':'⏸️ Robot detenido', it:'⏸️ Robot fermato', pt:'⏸️ Robô parado', ar:'⏸️ تم إيقاف الروبوت', hi:'⏸️ बॉट रुका', ja:'⏸️ ロボットを停止', ky:'⏸️ Робот токтотулду', 'zh-Hant':'⏸️ 機器人已停止' },
  log_manual_check: { bg:'🔄 Ръчна проверка…', ru:'🔄 Ручная проверка…', uk:'🔄 Ручна перевірка…', en:'🔄 Manual check…', de:'🔄 Manuelle Prüfung…', fr:'🔄 Vérification manuelle…', es:'🔄 Comprobación manual…', 'es-MX':'🔄 Revisión manual…', it:'🔄 Controllo manuale…', pt:'🔄 Verificação manual…', ar:'🔄 فحص يدوي…', hi:'🔄 मैनुअल जाँच…', ja:'🔄 手動チェック…', ky:'🔄 Кол менен текшерүү…', 'zh-Hant':'🔄 手動檢查…' },
  err_generic: { bg:'грешка', ru:'ошибка', uk:'помилка', en:'error', de:'Fehler', fr:'erreur', es:'error', 'es-MX':'error', it:'errore', pt:'erro', ar:'خطأ', hi:'त्रुटि', ja:'エラー', ky:'ката', 'zh-Hant':'錯誤' },

  // --- Стартова грешка (main.js) ---
  boot_error: { bg:'Стартова грешка: {0}', ru:'Ошибка запуска: {0}', uk:'Помилка запуску: {0}', en:'Startup error: {0}', de:'Startfehler: {0}', fr:'Erreur de démarrage : {0}', es:'Error de inicio: {0}', 'es-MX':'Error de inicio: {0}', it:'Errore di avvio: {0}', pt:'Erro de inicialização: {0}', ar:'خطأ في بدء التشغيل: {0}', hi:'स्टार्टअप त्रुटि: {0}', ja:'起動エラー: {0}', ky:'Баштоо катасы: {0}', 'zh-Hant':'啟動錯誤：{0}' },
  err_unknown: { bg:'неизвестна', ru:'неизвестная', uk:'невідома', en:'unknown', de:'unbekannt', fr:'inconnue', es:'desconocido', 'es-MX':'desconocido', it:'sconosciuto', pt:'desconhecido', ar:'غير معروف', hi:'अज्ञात', ja:'不明', ky:'белгисиз', 'zh-Hant':'未知' },

  // --- Грешки при четене на цени (api.js) ---
  err_unknown_symbol: { bg:'Непознат символ: {0}', ru:'Неизвестный символ: {0}', uk:'Невідомий символ: {0}', en:'Unknown symbol: {0}', de:'Unbekanntes Symbol: {0}', fr:'Symbole inconnu : {0}', es:'Símbolo desconocido: {0}', 'es-MX':'Símbolo desconocido: {0}', it:'Simbolo sconosciuto: {0}', pt:'Símbolo desconhecido: {0}', ar:'رمز غير معروف: {0}', hi:'अज्ञात प्रतीक: {0}', ja:'不明なシンボル: {0}', ky:'Белгисиз символ: {0}', 'zh-Hant':'未知代號：{0}' },
  err_bad_value: { bg:'лоша стойност', ru:'неверное значение', uk:'неправильне значення', en:'bad value', de:'ungültiger Wert', fr:'valeur incorrecte', es:'valor incorrecto', 'es-MX':'valor incorrecto', it:'valore non valido', pt:'valor inválido', ar:'قيمة غير صالحة', hi:'गलत मान', ja:'不正な値', ky:'жараксыз маани', 'zh-Hant':'數值無效' },
  err_no_price: { bg:'Няма цена за {0}', ru:'Нет цены для {0}', uk:'Немає ціни для {0}', en:'No price for {0}', de:'Kein Preis für {0}', fr:'Aucun prix pour {0}', es:'Sin precio para {0}', 'es-MX':'Sin precio para {0}', it:'Nessun prezzo per {0}', pt:'Sem preço para {0}', ar:'لا سعر لـ {0}', hi:'{0} के लिए कोई कीमत नहीं', ja:'{0} の価格がありません', ky:'{0} үчүн баа жок', 'zh-Hant':'{0} 無價格' },
  err_fx_unavailable: { bg:'FX недостъпен', ru:'FX недоступен', uk:'FX недоступний', en:'FX unavailable', de:'FX nicht verfügbar', fr:'FX indisponible', es:'FX no disponible', 'es-MX':'FX no disponible', it:'FX non disponibile', pt:'FX indisponível', ar:'أسعار الصرف غير متاحة', hi:'FX उपलब्ध नहीं', ja:'為替が利用できません', ky:'FX жеткиликсиз', 'zh-Hant':'匯率不可用' },
  err_no_rate: { bg:'Няма курс за {0}', ru:'Нет курса для {0}', uk:'Немає курсу для {0}', en:'No rate for {0}', de:'Kein Kurs für {0}', fr:'Aucun taux pour {0}', es:'Sin tasa para {0}', 'es-MX':'Sin tasa para {0}', it:'Nessun tasso per {0}', pt:'Sem taxa para {0}', ar:'لا سعر صرف لـ {0}', hi:'{0} के लिए कोई दर नहीं', ja:'{0} のレートがありません', ky:'{0} үчүн курс жок', 'zh-Hant':'{0} 無匯率' },
  err_unknown_watch: { bg:'Непознат тип наблюдение', ru:'Неизвестный тип наблюдения', uk:'Невідомий тип спостереження', en:'Unknown watch type', de:'Unbekannter Beobachtungstyp', fr:'Type de surveillance inconnu', es:'Tipo de seguimiento desconocido', 'es-MX':'Tipo de seguimiento desconocido', it:'Tipo di monitoraggio sconosciuto', pt:'Tipo de monitoramento desconhecido', ar:'نوع مراقبة غير معروف', hi:'अज्ञात निगरानी प्रकार', ja:'不明なウォッチタイプ', ky:'Белгисиз көзөмөл түрү', 'zh-Hant':'未知的監看類型' }
};

let current = detect();

function detect() {
  try { const s = localStorage.getItem(LS_KEY); if (s && STR.app_name[s] != null) return s; } catch (e) {}
  return DEFAULT_LANG;
}

export function hasLangChosen() {
  try { return !!localStorage.getItem(LS_KEY); } catch (e) { return false; }
}
export function getLang() { return current; }
export function setLang(code) {
  if (STR.app_name[code] == null) return;
  current = code;
  try { localStorage.setItem(LS_KEY, code); } catch (e) {}
  applyDir();
}
export function isRTL() { return RTL_CODES.indexOf(current) > -1; }
export function applyDir() {
  try {
    document.documentElement.setAttribute('dir', isRTL() ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', current);
  } catch (e) {}
}
export function t(key) {
  const row = STR[key];
  if (!row) return key;
  if (row[current] != null) return row[current];
  if (row[DEFAULT_LANG] != null) return row[DEFAULT_LANG];
  if (row[FALLBACK_LANG] != null) return row[FALLBACK_LANG];
  return key;
}
export function tf(key, ...vals) {
  let s = t(key);
  vals.forEach((v, i) => { s = s.replace(new RegExp('\\{' + i + '\\}', 'g'), String(v)); });
  return s;
}
export { LANGUAGES, languageByCode };
