// i18n.js — преводен слой на „Stay Informed" за 15-те езика на екосистемата.
// Език по подразбиране: руски (до избор от потребителя при първо стартиране).
// Резервна верига при липсващ ключ: текущ → ru → en → самият ключ.
// Бележка: тук се превежда ИНТЕРФЕЙСЪТ. Самите новинарски заглавия се превеждат отделно,
// наживо, през core/translate.js (MyMemory).
import { LANGUAGES, languageByCode, RTL_CODES } from './languages.js';

const LS_KEY = 'stayinformed.lang';
const DEFAULT_LANG = 'ru';
const FALLBACK_LANG = 'en';

const STR = {
app_name: { bg:'Stay Informed', ru:'Stay Informed', uk:'Stay Informed', en:'Stay Informed', de:'Stay Informed', fr:'Stay Informed', es:'Stay Informed', 'es-MX':'Stay Informed', it:'Stay Informed', pt:'Stay Informed', ar:'Stay Informed', hi:'Stay Informed', ja:'Stay Informed', ky:'Stay Informed', 'zh-Hant':'Stay Informed' },
app_tagline: { bg:'Световни новини, по държави, на твоя език', ru:'Мировые новости, по странам, на вашем языке', uk:'Світові новини, за країнами, вашою мовою', en:'World news, by country, in your language', de:'Weltnachrichten, nach Land, in deiner Sprache', fr:'L’actualité mondiale, par pays, dans votre langue', es:'Noticias del mundo, por país, en tu idioma', 'es-MX':'Noticias del mundo, por país, en tu idioma', it:'Notizie dal mondo, per Paese, nella tua lingua', pt:'Notícias do mundo, por país, no seu idioma', ar:'أخبار العالم، حسب الدولة، بلغتك', hi:'दुनिया की खबरें, देश के अनुसार, आपकी भाषा में', ja:'世界のニュースを、国別に、あなたの言語で', ky:'Дүйнө жаңылыктары, өлкө боюнча, өз тилиңизде', 'zh-Hant':'世界新聞，依國家分類，以您的語言呈現' },
pick_lang: { bg:'Избери език', ru:'Выберите язык', uk:'Виберіть мову', en:'Choose language', de:'Sprache wählen', fr:'Choisir la langue', es:'Elegir idioma', 'es-MX':'Elegir idioma', it:'Scegli la lingua', pt:'Escolher idioma', ar:'اختر اللغة', hi:'भाषा चुनें', ja:'言語を選択', ky:'Тилди тандаңыз', 'zh-Hant':'選擇語言' },
language: { bg:'Език', ru:'Язык', uk:'Мова', en:'Language', de:'Sprache', fr:'Langue', es:'Idioma', 'es-MX':'Idioma', it:'Lingua', pt:'Idioma', ar:'اللغة', hi:'भाषा', ja:'言語', ky:'Тил', 'zh-Hant':'語言' },
nav_news: { bg:'Новини', ru:'Новости', uk:'Новини', en:'News', de:'Nachrichten', fr:'Actualités', es:'Noticias', 'es-MX':'Noticias', it:'Notizie', pt:'Notícias', ar:'الأخبار', hi:'समाचार', ja:'ニュース', ky:'Жаңылыктар', 'zh-Hant':'新聞' },
nav_countries: { bg:'Държави', ru:'Страны', uk:'Країни', en:'Countries', de:'Länder', fr:'Pays', es:'Países', 'es-MX':'Países', it:'Paesi', pt:'Países', ar:'الدول', hi:'देश', ja:'国', ky:'Өлкөлөр', 'zh-Hant':'國家' },
nav_settings: { bg:'Настройки', ru:'Настройки', uk:'Налаштування', en:'Settings', de:'Einstellungen', fr:'Réglages', es:'Ajustes', 'es-MX':'Configuración', it:'Impostazioni', pt:'Configurações', ar:'الإعدادات', hi:'सेटिंग्स', ja:'設定', ky:'Жөндөөлөр', 'zh-Hant':'設定' },
ob_title: { bg:'Stay Informed', ru:'Stay Informed', uk:'Stay Informed', en:'Stay Informed', de:'Stay Informed', fr:'Stay Informed', es:'Stay Informed', 'es-MX':'Stay Informed', it:'Stay Informed', pt:'Stay Informed', ar:'Stay Informed', hi:'Stay Informed', ja:'Stay Informed', ky:'Stay Informed', 'zh-Hant':'Stay Informed' },
ob_desc: { bg:'Чети новините на коя да е държава по света — преведени на твоя език или прочетени на глас.', ru:'Читайте новости любой страны мира — переведённые на ваш язык или озвученные вслух.', uk:'Читайте новини будь-якої країни світу — перекладені вашою мовою або озвучені вголос.', en:'Read the news of any country in the world — translated into your language, or read aloud to you.', de:'Lies die Nachrichten jedes Landes der Welt — in deine Sprache übersetzt oder dir vorgelesen.', fr:'Lisez l’actualité de n’importe quel pays du monde — traduite dans votre langue ou lue à voix haute.', es:'Lee las noticias de cualquier país del mundo — traducidas a tu idioma o leídas en voz alta.', 'es-MX':'Lee las noticias de cualquier país del mundo — traducidas a tu idioma o leídas en voz alta.', it:'Leggi le notizie di qualsiasi Paese del mondo — tradotte nella tua lingua o lette ad alta voce.', pt:'Leia as notícias de qualquer país do mundo — traduzidas para o seu idioma ou lidas em voz alta.', ar:'اقرأ أخبار أي دولة في العالم — مترجمة إلى لغتك أو مقروءة لك بصوت عالٍ.', hi:'दुनिया के किसी भी देश की खबरें पढ़ें — आपकी भाषा में अनुवादित, या आपको पढ़कर सुनाई गई।', ja:'世界のどの国のニュースも読めます。あなたの言語に翻訳したり、音声で読み上げたりします。', ky:'Дүйнөнүн каалаган өлкөсүнүн жаңылыктарын окуңуз — өз тилиңизге которулган же үн менен окулган.', 'zh-Hant':'閱讀世界上任何國家的新聞——翻譯成您的語言，或為您朗讀。' },
ob_start: { bg:'Начало', ru:'Начать', uk:'Почати', en:'Get started', de:'Loslegen', fr:'Commencer', es:'Empezar', 'es-MX':'Comenzar', it:'Inizia', pt:'Começar', ar:'ابدأ', hi:'शुरू करें', ja:'始める', ky:'Баштоо', 'zh-Hant':'開始使用' },
choose_country: { bg:'Избери държава', ru:'Выберите страну', uk:'Виберіть країну', en:'Choose a country', de:'Land wählen', fr:'Choisir un pays', es:'Elegir un país', 'es-MX':'Elegir un país', it:'Scegli un Paese', pt:'Escolher um país', ar:'اختر دولة', hi:'एक देश चुनें', ja:'国を選択', ky:'Өлкө тандаңыз', 'zh-Hant':'選擇國家' },
search_country: { bg:'Търси държава…', ru:'Поиск страны…', uk:'Пошук країни…', en:'Search country…', de:'Land suchen…', fr:'Rechercher un pays…', es:'Buscar país…', 'es-MX':'Buscar país…', it:'Cerca Paese…', pt:'Pesquisar país…', ar:'ابحث عن دولة…', hi:'देश खोजें…', ja:'国を検索…', ky:'Өлкө издөө…', 'zh-Hant':'搜尋國家…' },
country_chosen: { bg:'Държава: {0}', ru:'Страна: {0}', uk:'Країна: {0}', en:'Country: {0}', de:'Land: {0}', fr:'Pays : {0}', es:'País: {0}', 'es-MX':'País: {0}', it:'Paese: {0}', pt:'País: {0}', ar:'الدولة: {0}', hi:'देश: {0}', ja:'国: {0}', ky:'Өлкө: {0}', 'zh-Hant':'國家：{0}' },
empty_pick_country: { bg:'Избери държава, за да видиш новините ѝ', ru:'Выберите страну, чтобы увидеть её новости', uk:'Виберіть країну, щоб побачити її новини', en:'Pick a country to see its news', de:'Wähle ein Land, um seine Nachrichten zu sehen', fr:'Choisissez un pays pour voir son actualité', es:'Elige un país para ver sus noticias', 'es-MX':'Elige un país para ver sus noticias', it:'Scegli un Paese per vederne le notizie', pt:'Escolha um país para ver as suas notícias', ar:'اختر دولة لعرض أخبارها', hi:'इसकी खबरें देखने के लिए एक देश चुनें', ja:'国を選ぶとそのニュースが表示されます', ky:'Жаңылыктарын көрүү үчүн өлкө тандаңыз', 'zh-Hant':'選擇一個國家以查看其新聞' },
region_africa: { bg:'Африка', ru:'Африка', uk:'Африка', en:'Africa', de:'Afrika', fr:'Afrique', es:'África', 'es-MX':'África', it:'Africa', pt:'África', ar:'أفريقيا', hi:'अफ्रीका', ja:'アフリカ', ky:'Африка', 'zh-Hant':'非洲' },
region_americas: { bg:'Америка', ru:'Америка', uk:'Америка', en:'Americas', de:'Amerika', fr:'Amériques', es:'América', 'es-MX':'América', it:'Americhe', pt:'Américas', ar:'الأمريكتان', hi:'अमेरिका', ja:'南北アメリカ', ky:'Америка', 'zh-Hant':'美洲' },
region_asia: { bg:'Азия', ru:'Азия', uk:'Азія', en:'Asia', de:'Asien', fr:'Asie', es:'Asia', 'es-MX':'Asia', it:'Asia', pt:'Ásia', ar:'آسيا', hi:'एशिया', ja:'アジア', ky:'Азия', 'zh-Hant':'亞洲' },
region_europe: { bg:'Европа', ru:'Европа', uk:'Європа', en:'Europe', de:'Europa', fr:'Europe', es:'Europa', 'es-MX':'Europa', it:'Europa', pt:'Europa', ar:'أوروبا', hi:'यूरोप', ja:'ヨーロッパ', ky:'Европа', 'zh-Hant':'歐洲' },
region_oceania: { bg:'Океания', ru:'Океания', uk:'Океанія', en:'Oceania', de:'Ozeanien', fr:'Océanie', es:'Oceanía', 'es-MX':'Oceanía', it:'Oceania', pt:'Oceania', ar:'أوقيانوسيا', hi:'ओशिनिया', ja:'オセアニア', ky:'Океания', 'zh-Hant':'大洋洲' },
region_middle_east: { bg:'Близък изток', ru:'Ближний Восток', uk:'Близький Схід', en:'Middle East', de:'Naher Osten', fr:'Moyen-Orient', es:'Oriente Medio', 'es-MX':'Medio Oriente', it:'Medio Oriente', pt:'Médio Oriente', ar:'الشرق الأوسط', hi:'मध्य पूर्व', ja:'中東', ky:'Жакынкы Чыгыш', 'zh-Hant':'中東' },
all_countries: { bg:'Всички държави', ru:'Все страны', uk:'Усі країни', en:'All countries', de:'Alle Länder', fr:'Tous les pays', es:'Todos los países', 'es-MX':'Todos los países', it:'Tutti i Paesi', pt:'Todos os países', ar:'كل الدول', hi:'सभी देश', ja:'すべての国', ky:'Бардык өлкөлөр', 'zh-Hant':'所有國家' },
named_sources: { bg:'Именувани източници', ru:'Названные источники', uk:'Названі джерела', en:'Named sources', de:'Benannte Quellen', fr:'Sources nommées', es:'Fuentes con nombre', 'es-MX':'Fuentes con nombre', it:'Fonti con nome', pt:'Fontes identificadas', ar:'مصادر محددة', hi:'नामित स्रोत', ja:'指定ソース', ky:'Аталган булактар', 'zh-Hant':'指定來源' },
general_only: { bg:'Общ поток', ru:'Общая лента', uk:'Загальна стрічка', en:'General feed', de:'Allgemeiner Feed', fr:'Flux général', es:'Feed general', 'es-MX':'Feed general', it:'Feed generale', pt:'Feed geral', ar:'الموجز العام', hi:'सामान्य फ़ीड', ja:'一般フィード', ky:'Жалпы лента', 'zh-Hant':'綜合動態' },
loading_news: { bg:'Зареждане на новините…', ru:'Загрузка новостей…', uk:'Завантаження новин…', en:'Loading the news…', de:'Nachrichten werden geladen…', fr:'Chargement de l’actualité…', es:'Cargando las noticias…', 'es-MX':'Cargando las noticias…', it:'Caricamento notizie…', pt:'A carregar as notícias…', ar:'جارٍ تحميل الأخبار…', hi:'समाचार लोड हो रहे हैं…', ja:'ニュースを読み込み中…', ky:'Жаңылыктар жүктөлүүдө…', 'zh-Hant':'正在載入新聞…' },
refresh: { bg:'Обнови', ru:'Обновить', uk:'Оновити', en:'Refresh', de:'Aktualisieren', fr:'Actualiser', es:'Actualizar', 'es-MX':'Actualizar', it:'Aggiorna', pt:'Atualizar', ar:'تحديث', hi:'रिफ़्रेश', ja:'更新', ky:'Жаңыртуу', 'zh-Hant':'重新整理' },
no_news: { bg:'Няма новини в момента — пробвай Обнови', ru:'Сейчас новостей нет — попробуйте Обновить', uk:'Зараз новин немає — спробуйте Оновити', en:'No news right now — try Refresh', de:'Gerade keine Nachrichten — versuch Aktualisieren', fr:'Aucune actualité pour l’instant — essayez Actualiser', es:'No hay noticias ahora — prueba Actualizar', 'es-MX':'No hay noticias ahora — prueba Actualizar', it:'Nessuna notizia al momento — prova Aggiorna', pt:'Sem notícias agora — tente Atualizar', ar:'لا توجد أخبار الآن — جرّب التحديث', hi:'अभी कोई समाचार नहीं — रिफ़्रेश आज़माएं', ja:'今ニュースはありません — 更新をお試しください', ky:'Азыр жаңылык жок — Жаңыртууну байкап көрүңүз', 'zh-Hant':'目前沒有新聞——請試試重新整理' },
news_error: { bg:'Новините не се заредиха. Провери връзката и опитай пак.', ru:'Не удалось загрузить новости. Проверьте соединение и повторите.', uk:'Не вдалося завантажити новини. Перевірте з’єднання та спробуйте ще раз.', en:'Could not load the news. Check your connection and try again.', de:'Nachrichten konnten nicht geladen werden. Prüfe deine Verbindung und versuch es erneut.', fr:'Impossible de charger l’actualité. Vérifiez votre connexion et réessayez.', es:'No se pudieron cargar las noticias. Comprueba tu conexión e inténtalo de nuevo.', 'es-MX':'No se pudieron cargar las noticias. Revisa tu conexión e inténtalo de nuevo.', it:'Impossibile caricare le notizie. Controlla la connessione e riprova.', pt:'Não foi possível carregar as notícias. Verifique a ligação e tente novamente.', ar:'تعذّر تحميل الأخبار. تحقّق من اتصالك وحاول مرة أخرى.', hi:'समाचार लोड नहीं हो सके। अपना कनेक्शन जांचें और फिर से कोशिश करें।', ja:'ニュースを読み込めませんでした。接続を確認して、もう一度お試しください。', ky:'Жаңылыктар жүктөлгөн жок. Туташууну текшерип, кайра аракет кылыңыз.', 'zh-Hant':'無法載入新聞。請檢查您的連線後再試一次。' },
no_internet: { bg:'Няма интернет връзка', ru:'Нет подключения к интернету', uk:'Немає підключення до інтернету', en:'No internet connection', de:'Keine Internetverbindung', fr:'Aucune connexion Internet', es:'Sin conexión a Internet', 'es-MX':'Sin conexión a Internet', it:'Nessuna connessione a Internet', pt:'Sem ligação à Internet', ar:'لا يوجد اتصال بالإنترنت', hi:'कोई इंटरनेट कनेक्शन नहीं', ja:'インターネット接続がありません', ky:'Интернет байланышы жок', 'zh-Hant':'無網際網路連線' },
source_official: { bg:'Официален', ru:'Официальный', uk:'Офіційний', en:'Official', de:'Offiziell', fr:'Officiel', es:'Oficial', 'es-MX':'Oficial', it:'Ufficiale', pt:'Oficial', ar:'رسمي', hi:'आधिकारिक', ja:'公式', ky:'Расмий', 'zh-Hant':'官方' },
source_unofficial: { bg:'Неофициален', ru:'Неофициальный', uk:'Неофіційний', en:'Unofficial', de:'Inoffiziell', fr:'Non officiel', es:'No oficial', 'es-MX':'No oficial', it:'Non ufficiale', pt:'Não oficial', ar:'غير رسمي', hi:'अनौपचारिक', ja:'非公式', ky:'Расмий эмес', 'zh-Hant':'非官方' },
source_aggregator: { bg:'Агрегатор', ru:'Агрегатор', uk:'Агрегатор', en:'Aggregator', de:'Aggregator', fr:'Agrégateur', es:'Agregador', 'es-MX':'Agregador', it:'Aggregatore', pt:'Agregador', ar:'مُجمِّع', hi:'एग्रीगेटर', ja:'アグリゲーター', ky:'Топтоштуруучу', 'zh-Hant':'聚合器' },
filter_all: { bg:'Всички', ru:'Все', uk:'Усі', en:'All', de:'Alle', fr:'Tous', es:'Todos', 'es-MX':'Todos', it:'Tutti', pt:'Todos', ar:'الكل', hi:'सभी', ja:'すべて', ky:'Баары', 'zh-Hant':'全部' },
filter_official: { bg:'Само официални', ru:'Только официальные', uk:'Лише офіційні', en:'Official only', de:'Nur offiziell', fr:'Officiels uniquement', es:'Solo oficiales', 'es-MX':'Solo oficiales', it:'Solo ufficiali', pt:'Apenas oficiais', ar:'الرسمية فقط', hi:'केवल आधिकारिक', ja:'公式のみ', ky:'Расмийлер гана', 'zh-Hant':'僅官方' },
open_article: { bg:'Отвори', ru:'Открыть', uk:'Відкрити', en:'Open', de:'Öffnen', fr:'Ouvrir', es:'Abrir', 'es-MX':'Abrir', it:'Apri', pt:'Abrir', ar:'فتح', hi:'खोलें', ja:'開く', ky:'Ачуу', 'zh-Hant':'開啟' },
read_aloud: { bg:'Прочети на глас', ru:'Прочитать вслух', uk:'Прочитати вголос', en:'Read aloud', de:'Vorlesen', fr:'Lire à voix haute', es:'Leer en voz alta', 'es-MX':'Leer en voz alta', it:'Leggi ad alta voce', pt:'Ler em voz alta', ar:'اقرأ بصوت عالٍ', hi:'ज़ोर से पढ़ें', ja:'読み上げ', ky:'Үн менен окуу', 'zh-Hant':'朗讀' },
read_all: { bg:'Прочети всички', ru:'Прочитать все', uk:'Прочитати всі', en:'Read all', de:'Alle vorlesen', fr:'Tout lire', es:'Leer todo', 'es-MX':'Leer todo', it:'Leggi tutto', pt:'Ler tudo', ar:'اقرأ الكل', hi:'सभी पढ़ें', ja:'すべて読み上げ', ky:'Баарын окуу', 'zh-Hant':'全部朗讀' },
stop_reading: { bg:'Спри', ru:'Стоп', uk:'Стоп', en:'Stop', de:'Stopp', fr:'Arrêter', es:'Detener', 'es-MX':'Detener', it:'Ferma', pt:'Parar', ar:'إيقاف', hi:'रोकें', ja:'停止', ky:'Токтотуу', 'zh-Hant':'停止' },
reading: { bg:'Чете се…', ru:'Чтение…', uk:'Читання…', en:'Reading…', de:'Wird vorgelesen…', fr:'Lecture…', es:'Leyendo…', 'es-MX':'Leyendo…', it:'Lettura…', pt:'A ler…', ar:'جارٍ القراءة…', hi:'पढ़ रहा है…', ja:'読み上げ中…', ky:'Окулууда…', 'zh-Hant':'朗讀中…' },
translate: { bg:'Преведи', ru:'Перевести', uk:'Перекласти', en:'Translate', de:'Übersetzen', fr:'Traduire', es:'Traducir', 'es-MX':'Traducir', it:'Traduci', pt:'Traduzir', ar:'ترجمة', hi:'अनुवाद करें', ja:'翻訳', ky:'Которуу', 'zh-Hant':'翻譯' },
show_original: { bg:'Оригинал', ru:'Оригинал', uk:'Оригінал', en:'Original', de:'Original', fr:'Original', es:'Original', 'es-MX':'Original', it:'Originale', pt:'Original', ar:'الأصل', hi:'मूल', ja:'原文', ky:'Түпнуска', 'zh-Hant':'原文' },
translated_label: { bg:'преведено', ru:'переведено', uk:'перекладено', en:'translated', de:'übersetzt', fr:'traduit', es:'traducido', 'es-MX':'traducido', it:'tradotto', pt:'traduzido', ar:'مُترجَم', hi:'अनुवादित', ja:'翻訳済み', ky:'которулган', 'zh-Hant':'已翻譯' },
translating: { bg:'Превеждане…', ru:'Перевод…', uk:'Переклад…', en:'Translating…', de:'Wird übersetzt…', fr:'Traduction…', es:'Traduciendo…', 'es-MX':'Traduciendo…', it:'Traduzione…', pt:'A traduzir…', ar:'جارٍ الترجمة…', hi:'अनुवाद हो रहा है…', ja:'翻訳中…', ky:'Которулууда…', 'zh-Hant':'翻譯中…' },
translate_unavailable: { bg:'Преводът не е достъпен в момента', ru:'Перевод сейчас недоступен', uk:'Переклад зараз недоступний', en:'Translation unavailable right now', de:'Übersetzung gerade nicht verfügbar', fr:'Traduction indisponible pour le moment', es:'Traducción no disponible en este momento', 'es-MX':'Traducción no disponible en este momento', it:'Traduzione non disponibile al momento', pt:'Tradução indisponível neste momento', ar:'الترجمة غير متاحة حالياً', hi:'अभी अनुवाद उपलब्ध नहीं है', ja:'現在、翻訳を利用できません', ky:'Учурда которуу жеткиликсиз', 'zh-Hant':'目前無法翻譯' },
tts_unavailable: { bg:'Гласовото четене не е налично на това устройство', ru:'Голосовое чтение недоступно на этом устройстве', uk:'Голосове читання недоступне на цьому пристрої', en:'Voice reading is not available on this device', de:'Vorlesen ist auf diesem Gerät nicht verfügbar', fr:'La lecture vocale n’est pas disponible sur cet appareil', es:'La lectura por voz no está disponible en este dispositivo', 'es-MX':'La lectura por voz no está disponible en este dispositivo', it:'La lettura vocale non è disponibile su questo dispositivo', pt:'A leitura por voz não está disponível neste dispositivo', ar:'القراءة الصوتية غير متاحة على هذا الجهاز', hi:'इस डिवाइस पर आवाज़ से पढ़ना उपलब्ध नहीं है', ja:'このデバイスでは音声読み上げを利用できません', ky:'Бул түзмөктө үн менен окуу жеткиликсиз', 'zh-Hant':'此裝置無法使用語音朗讀' },
by_source: { bg:'Източник: {0}', ru:'Источник: {0}', uk:'Джерело: {0}', en:'Source: {0}', de:'Quelle: {0}', fr:'Source : {0}', es:'Fuente: {0}', 'es-MX':'Fuente: {0}', it:'Fonte: {0}', pt:'Fonte: {0}', ar:'المصدر: {0}', hi:'स्रोत: {0}', ja:'ソース: {0}', ky:'Булак: {0}', 'zh-Hant':'來源：{0}' },
sources_count: { bg:'{0} източника', ru:'{0} источников', uk:'{0} джерел', en:'{0} sources', de:'{0} Quellen', fr:'{0} sources', es:'{0} fuentes', 'es-MX':'{0} fuentes', it:'{0} fonti', pt:'{0} fontes', ar:'{0} مصادر', hi:'{0} स्रोत', ja:'{0} 件のソース', ky:'{0} булак', 'zh-Hant':'{0} 個來源' },
just_now: { bg:'току-що', ru:'только что', uk:'щойно', en:'just now', de:'gerade eben', fr:'à l’instant', es:'justo ahora', 'es-MX':'justo ahora', it:'proprio ora', pt:'agora mesmo', ar:'الآن', hi:'अभी', ja:'たった今', ky:'азыр эле', 'zh-Hant':'剛剛' },
minutes_ago: { bg:'преди {0} мин', ru:'{0} мин назад', uk:'{0} хв тому', en:'{0} min ago', de:'vor {0} Min', fr:'il y a {0} min', es:'hace {0} min', 'es-MX':'hace {0} min', it:'{0} min fa', pt:'há {0} min', ar:'قبل {0} د', hi:'{0} मिनट पहले', ja:'{0} 分前', ky:'{0} мүн мурун', 'zh-Hant':'{0} 分鐘前' },
hours_ago: { bg:'преди {0} ч', ru:'{0} ч назад', uk:'{0} год тому', en:'{0} h ago', de:'vor {0} Std', fr:'il y a {0} h', es:'hace {0} h', 'es-MX':'hace {0} h', it:'{0} h fa', pt:'há {0} h', ar:'قبل {0} س', hi:'{0} घंटे पहले', ja:'{0} 時間前', ky:'{0} саат мурун', 'zh-Hant':'{0} 小時前' },
days_ago: { bg:'преди {0} дни', ru:'{0} дн назад', uk:'{0} дн тому', en:'{0} d ago', de:'vor {0} Tg', fr:'il y a {0} j', es:'hace {0} d', 'es-MX':'hace {0} d', it:'{0} g fa', pt:'há {0} d', ar:'قبل {0} ي', hi:'{0} दिन पहले', ja:'{0} 日前', ky:'{0} күн мурун', 'zh-Hant':'{0} 天前' },
updated: { bg:'Обновено {0}', ru:'Обновлено {0}', uk:'Оновлено {0}', en:'Updated {0}', de:'Aktualisiert {0}', fr:'Mis à jour {0}', es:'Actualizado {0}', 'es-MX':'Actualizado {0}', it:'Aggiornato {0}', pt:'Atualizado {0}', ar:'تم التحديث {0}', hi:'अपडेट किया गया {0}', ja:'更新 {0}', ky:'Жаңыртылды {0}', 'zh-Hant':'已更新 {0}' },
set_autotranslate: { bg:'Авто-превод на заглавията', ru:'Автоперевод заголовков', uk:'Автопереклад заголовків', en:'Auto-translate headlines', de:'Schlagzeilen automatisch übersetzen', fr:'Traduire automatiquement les titres', es:'Traducir titulares automáticamente', 'es-MX':'Traducir titulares automáticamente', it:'Traduci automaticamente i titoli', pt:'Traduzir títulos automaticamente', ar:'ترجمة العناوين تلقائياً', hi:'सुर्खियों का स्वतः अनुवाद', ja:'見出しを自動翻訳', ky:'Башаттарды авто-которуу', 'zh-Hant':'自動翻譯標題' },
set_autotranslate_desc: { bg:'Превеждай заглавията на новините на твоя език автоматично.', ru:'Автоматически переводить заголовки новостей на ваш язык.', uk:'Автоматично перекладати заголовки новин вашою мовою.', en:'Translate news titles into your language automatically.', de:'Nachrichtentitel automatisch in deine Sprache übersetzen.', fr:'Traduire automatiquement les titres dans votre langue.', es:'Traduce los títulos de las noticias a tu idioma automáticamente.', 'es-MX':'Traduce los títulos de las noticias a tu idioma automáticamente.', it:'Traduci automaticamente i titoli delle notizie nella tua lingua.', pt:'Traduz automaticamente os títulos das notícias para o seu idioma.', ar:'ترجمة عناوين الأخبار إلى لغتك تلقائياً.', hi:'समाचार शीर्षकों को स्वचालित रूप से आपकी भाषा में अनुवाद करें।', ja:'ニュースのタイトルを自動的にあなたの言語へ翻訳します。', ky:'Жаңылыктардын аталыштарын автоматтык түрдө өз тилиңизге которот.', 'zh-Hant':'自動將新聞標題翻譯成您的語言。' },
set_tts: { bg:'Прочети на глас', ru:'Чтение вслух', uk:'Читання вголос', en:'Read aloud', de:'Vorlesen', fr:'Lecture à voix haute', es:'Leer en voz alta', 'es-MX':'Leer en voz alta', it:'Leggi ad alta voce', pt:'Ler em voz alta', ar:'القراءة بصوت عالٍ', hi:'ज़ोर से पढ़ें', ja:'読み上げ', ky:'Үн менен окуу', 'zh-Hant':'朗讀' },
set_tts_desc: { bg:'Позволи на приложението да ти чете новините.', ru:'Разрешите приложению читать вам новости.', uk:'Дозвольте застосунку читати вам новини.', en:'Let the app read the news to you.', de:'Lass die App dir die Nachrichten vorlesen.', fr:'Laissez l’application vous lire l’actualité.', es:'Deja que la app te lea las noticias.', 'es-MX':'Deja que la app te lea las noticias.', it:'Lascia che l’app ti legga le notizie.', pt:'Deixe a aplicação ler-lhe as notícias.', ar:'دع التطبيق يقرأ لك الأخبار.', hi:'ऐप को आपको समाचार पढ़कर सुनाने दें।', ja:'アプリにニュースを読み上げてもらいます。', ky:'Колдонмого жаңылыктарды окуп берүүгө уруксат бериңиз.', 'zh-Hant':'讓應用程式為您朗讀新聞。' },
set_language: { bg:'Език на приложението', ru:'Язык приложения', uk:'Мова застосунку', en:'App language', de:'App-Sprache', fr:'Langue de l’application', es:'Idioma de la app', 'es-MX':'Idioma de la app', it:'Lingua dell’app', pt:'Idioma da aplicação', ar:'لغة التطبيق', hi:'ऐप की भाषा', ja:'アプリの言語', ky:'Колдонмонун тили', 'zh-Hant':'應用程式語言' },
set_country: { bg:'Държава', ru:'Страна', uk:'Країна', en:'Country', de:'Land', fr:'Pays', es:'País', 'es-MX':'País', it:'Paese', pt:'País', ar:'الدولة', hi:'देश', ja:'国', ky:'Өлкө', 'zh-Hant':'國家' },
set_about: { bg:'Относно', ru:'О приложении', uk:'Про застосунок', en:'About', de:'Über', fr:'À propos', es:'Acerca de', 'es-MX':'Acerca de', it:'Informazioni', pt:'Sobre', ar:'حول', hi:'के बारे में', ja:'アプリについて', ky:'Колдонмо жөнүндө', 'zh-Hant':'關於' },
set_about_text: { bg:'Stay Informed събира публични новини за всяка държава от официални и няколко неофициални източника. Източниците принадлежат на своите собственици; това приложение е независим четец и не е свързано с тях.', ru:'Stay Informed собирает публичные новости по каждой стране из официальных и нескольких неофициальных источников. Источники принадлежат их владельцам; это приложение — независимая читалка и не связано с ними.', uk:'Stay Informed збирає публічні новини щодо кожної країни з офіційних і кількох неофіційних джерел. Джерела належать їхнім власникам; цей застосунок — незалежний читач і не пов’язаний з ними.', en:'Stay Informed gathers public news for every country from official and a few unofficial sources. The sources belong to their owners; this app is an independent reader and is not affiliated with them.', de:'Stay Informed sammelt öffentliche Nachrichten für jedes Land aus offiziellen und einigen inoffiziellen Quellen. Die Quellen gehören ihren Eigentümern; diese App ist ein unabhängiger Reader und steht in keiner Verbindung zu ihnen.', fr:'Stay Informed rassemble l’actualité publique de chaque pays à partir de sources officielles et de quelques sources non officielles. Les sources appartiennent à leurs propriétaires ; cette application est un lecteur indépendant et n’y est pas affiliée.', es:'Stay Informed reúne noticias públicas de cada país a partir de fuentes oficiales y algunas no oficiales. Las fuentes pertenecen a sus propietarios; esta app es un lector independiente y no está afiliada a ellas.', 'es-MX':'Stay Informed reúne noticias públicas de cada país a partir de fuentes oficiales y algunas no oficiales. Las fuentes pertenecen a sus propietarios; esta app es un lector independiente y no está afiliada a ellas.', it:'Stay Informed raccoglie notizie pubbliche di ogni Paese da fonti ufficiali e da alcune fonti non ufficiali. Le fonti appartengono ai rispettivi proprietari; questa app è un lettore indipendente e non è affiliata ad esse.', pt:'O Stay Informed reúne notícias públicas de cada país a partir de fontes oficiais e de algumas não oficiais. As fontes pertencem aos seus proprietários; esta aplicação é um leitor independente e não tem qualquer afiliação com elas.', ar:'يجمع Stay Informed الأخبار العامة لكل دولة من مصادر رسمية وبعض المصادر غير الرسمية. تعود المصادر إلى أصحابها؛ وهذا التطبيق قارئ مستقل وغير تابع لها.', hi:'Stay Informed हर देश की सार्वजनिक खबरें आधिकारिक और कुछ अनौपचारिक स्रोतों से एकत्र करता है। स्रोत उनके मालिकों के हैं; यह ऐप एक स्वतंत्र रीडर है और उनसे संबद्ध नहीं है।', ja:'Stay Informed は、各国の公開ニュースを公式および一部の非公式ソースから集めます。ソースはそれぞれの所有者に帰属します。本アプリは独立したリーダーであり、それらと提携していません。', ky:'Stay Informed ар бир өлкөнүн ачык жаңылыктарын расмий жана бир нече расмий эмес булактардан чогултат. Булактар өз ээлерине таандык; бул колдонмо көз карандысыз окуучу жана алар менен байланышы жок.', 'zh-Hant':'Stay Informed 從官方及少數非官方來源彙整每個國家的公開新聞。這些來源歸其各自所有者所有；本應用程式為獨立閱讀器，與其並無隸屬關係。' },
news_disclaimer: { bg:'Обобщени публични новини. Всички права принадлежат на съответните източници.', ru:'Агрегированные публичные новости. Все права принадлежат соответствующим источникам.', uk:'Агреговані публічні новини. Усі права належать відповідним джерелам.', en:'Aggregated public news. All rights belong to the respective sources.', de:'Aggregierte öffentliche Nachrichten. Alle Rechte liegen bei den jeweiligen Quellen.', fr:'Actualités publiques agrégées. Tous les droits appartiennent aux sources respectives.', es:'Noticias públicas agregadas. Todos los derechos pertenecen a las fuentes respectivas.', 'es-MX':'Noticias públicas agregadas. Todos los derechos pertenecen a las fuentes respectivas.', it:'Notizie pubbliche aggregate. Tutti i diritti appartengono alle rispettive fonti.', pt:'Notícias públicas agregadas. Todos os direitos pertencem às respetivas fontes.', ar:'أخبار عامة مُجمَّعة. جميع الحقوق تعود للمصادر المعنية.', hi:'समेकित सार्वजनिक समाचार। सभी अधिकार संबंधित स्रोतों के हैं।', ja:'集約された公開ニュースです。すべての権利は各ソースに帰属します。', ky:'Топтоштурулган ачык жаңылыктар. Бардык укуктар тиешелүү булактарга таандык.', 'zh-Hant':'彙整的公開新聞。所有權利歸各來源所有。' },
boot_error: { bg:'Грешка при стартиране: {0}', ru:'Ошибка запуска: {0}', uk:'Помилка запуску: {0}', en:'Startup error: {0}', de:'Startfehler: {0}', fr:'Erreur de démarrage : {0}', es:'Error de inicio: {0}', 'es-MX':'Error de inicio: {0}', it:'Errore di avvio: {0}', pt:'Erro de arranque: {0}', ar:'خطأ في بدء التشغيل: {0}', hi:'स्टार्टअप त्रुटि: {0}', ja:'起動エラー: {0}', ky:'Иштетүү катасы: {0}', 'zh-Hant':'啟動錯誤：{0}' },
err_unknown: { bg:'неизвестна', ru:'неизвестно', uk:'невідомо', en:'unknown', de:'unbekannt', fr:'inconnue', es:'desconocido', 'es-MX':'desconocido', it:'sconosciuto', pt:'desconhecido', ar:'غير معروف', hi:'अज्ञात', ja:'不明', ky:'белгисиз', 'zh-Hant':'未知' }
};

let current = detect();

function detect() {
  try { const s = localStorage.getItem(LS_KEY); if (s && STR.app_name[s] != null) return s; } catch (e) {}
  return DEFAULT_LANG;
}

export function hasLangChosen() {
  try { return !!localStorage.getItem(LS_KEY); } catch (e) { return false; }
}
export function getLang() { return current; }
export function setLang(code) {
  if (STR.app_name[code] == null) return;
  current = code;
  try { localStorage.setItem(LS_KEY, code); } catch (e) {}
  applyDir();
}
export function isRTL() { return RTL_CODES.indexOf(current) > -1; }
export function applyDir() {
  try {
    document.documentElement.setAttribute('dir', isRTL() ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', current);
  } catch (e) {}
}
export function t(key) {
  const row = STR[key];
  if (!row) return key;
  if (row[current] != null) return row[current];
  if (row[DEFAULT_LANG] != null) return row[DEFAULT_LANG];
  if (row[FALLBACK_LANG] != null) return row[FALLBACK_LANG];
  return key;
}
export function tf(key, ...vals) {
  let s = t(key);
  vals.forEach((v, i) => { s = s.replace(new RegExp('\\{' + i + '\\}', 'g'), String(v)); });
  return s;
}
export { LANGUAGES, languageByCode };
