// Version: 1.0001
// i18n.js — преводен слой за „Рутина-робот" на 15-те езика на екосистемата.
//
// ВАЖНО разграничение (две НЕЗАВИСИМИ настройки):
//   • Този модул управлява ЕЗИКА НА ИНТЕРФЕЙСА (бутони, етикети, екрани).
//     Пази се в localStorage['routinebot.lang']. По подразбиране: руски.
//   • Гласът, на който роботът ИЗГОВАРЯ бележките (TTS), е ОТДЕЛНА настройка
//     (KEYS.ttsLang в storage) и НЕ се влияе от избора тук. Виж notes.js.
//
// Списъкът с езици идва от СЪЩЕСТВУВАЩИЯ ./languages.js (без дублиране).
// Резервна верига при липсващ превод: текущ → руски → английски → самия ключ.
//
// Употреба:
//   import { t, tf, getLang, setLang, hasLangChosen } from '../core/i18n.js';
//   t('save')                 -> „Сохранить" на текущия език
//   tf('imported_n', count)   -> с вмъкнато число
import { LANGUAGES, languageByCode, RTL_CODES } from './languages.js';

const LS_KEY = 'routinebot.lang';   // отделен ключ — НЕ се бърка с TTS езика на бележките
const DEFAULT_LANG = 'ru';          // език по подразбиране до избор от потребителя
const FALLBACK_LANG = 'en';         // вторичен резерв при липсващ превод

// Речник: ключ -> { код-на-език: текст }. Руският е по подразбиране, английският — резерв.
const STR = {
  // --- Избор на език ---
  pick_lang: { bg:'Избери език', ru:'Выберите язык', uk:'Виберіть мову', en:'Choose language', de:'Sprache wählen', fr:'Choisir la langue', es:'Elegir idioma', 'es-MX':'Elegir idioma', it:'Scegli la lingua', pt:'Escolher idioma', ar:'اختر اللغة', hi:'भाषा चुनें', ja:'言語を選択', ky:'Тилди тандаңыз', 'zh-Hant':'選擇語言' },
  lang_btn: { bg:'🌐 Език', ru:'🌐 Язык', uk:'🌐 Мова', en:'🌐 Language', de:'🌐 Sprache', fr:'🌐 Langue', es:'🌐 Idioma', 'es-MX':'🌐 Idioma', it:'🌐 Lingua', pt:'🌐 Idioma', ar:'🌐 اللغة', hi:'🌐 भाषा', ja:'🌐 言語', ky:'🌐 Тил', 'zh-Hant':'🌐 語言' },
  start_app: { bg:'Стартирай', ru:'Запустить', uk:'Запустити', en:'Start', de:'Starten', fr:'Démarrer', es:'Iniciar', 'es-MX':'Iniciar', it:'Avvia', pt:'Iniciar', ar:'ابدأ', hi:'शुरू करें', ja:'開始', ky:'Баштоо', 'zh-Hant':'開始' },

  // --- Общи ---
  save: { bg:'Запази', ru:'Сохранить', uk:'Зберегти', en:'Save', de:'Speichern', fr:'Enregistrer', es:'Guardar', 'es-MX':'Guardar', it:'Salva', pt:'Salvar', ar:'حفظ', hi:'सहेजें', ja:'保存', ky:'Сактоо', 'zh-Hant':'儲存' },
  cancel: { bg:'Отказ', ru:'Отмена', uk:'Скасувати', en:'Cancel', de:'Abbrechen', fr:'Annuler', es:'Cancelar', 'es-MX':'Cancelar', it:'Annulla', pt:'Cancelar', ar:'إلغاء', hi:'रद्द करें', ja:'キャンセル', ky:'Жокко чыгаруу', 'zh-Hant':'取消' },
  delete: { bg:'Изтрий', ru:'Удалить', uk:'Видалити', en:'Delete', de:'Löschen', fr:'Supprimer', es:'Eliminar', 'es-MX':'Eliminar', it:'Elimina', pt:'Excluir', ar:'حذف', hi:'हटाएं', ja:'削除', ky:'Өчүрүү', 'zh-Hant':'刪除' },
  add: { bg:'Добави', ru:'Добавить', uk:'Додати', en:'Add', de:'Hinzufügen', fr:'Ajouter', es:'Añadir', 'es-MX':'Agregar', it:'Aggiungi', pt:'Adicionar', ar:'إضافة', hi:'जोड़ें', ja:'追加', ky:'Кошуу', 'zh-Hant':'新增' },
  done_btn: { bg:'Готово', ru:'Готово', uk:'Готово', en:'Done', de:'Fertig', fr:'Terminé', es:'Listo', 'es-MX':'Listo', it:'Fatto', pt:'Concluído', ar:'تم', hi:'पूर्ण', ja:'完了', ky:'Даяр', 'zh-Hant':'完成' },
  title_field: { bg:'Заглавие', ru:'Название', uk:'Назва', en:'Title', de:'Titel', fr:'Titre', es:'Título', 'es-MX':'Título', it:'Titolo', pt:'Título', ar:'العنوان', hi:'शीर्षक', ja:'タイトル', ky:'Аталышы', 'zh-Hant':'標題' },

  // --- Долна навигация ---
  nav_dashboard: { bg:'Табло', ru:'Панель', uk:'Панель', en:'Home', de:'Start', fr:'Accueil', es:'Inicio', 'es-MX':'Inicio', it:'Home', pt:'Início', ar:'الرئيسية', hi:'होम', ja:'ホーム', ky:'Башкы', 'zh-Hant':'首頁' },
  nav_notes: { bg:'Бележки', ru:'Заметки', uk:'Нотатки', en:'Notes', de:'Notizen', fr:'Notes', es:'Notas', 'es-MX':'Notas', it:'Note', pt:'Notas', ar:'الملاحظات', hi:'नोट्स', ja:'メモ', ky:'Эскертүүлөр', 'zh-Hant':'筆記' },
  nav_routine: { bg:'Рутина', ru:'Рутина', uk:'Рутина', en:'Routine', de:'Routine', fr:'Routine', es:'Rutina', 'es-MX':'Rutina', it:'Routine', pt:'Rotina', ar:'الروتين', hi:'दिनचर्या', ja:'ルーティン', ky:'Күн тартиби', 'zh-Hant':'例程' },
  nav_perms: { bg:'Разрешения', ru:'Разрешения', uk:'Дозволи', en:'Permissions', de:'Berechtigungen', fr:'Autorisations', es:'Permisos', 'es-MX':'Permisos', it:'Permessi', pt:'Permissões', ar:'الأذونات', hi:'अनुमतियाँ', ja:'権限', ky:'Уруксаттар', 'zh-Hant':'權限' },

  // --- Онбординг ---
  onb_title: { bg:'Твоят личен робот', ru:'Ваш личный робот', uk:'Ваш особистий робот', en:'Your personal robot', de:'Dein persönlicher Roboter', fr:'Ton robot personnel', es:'Tu robot personal', 'es-MX':'Tu robot personal', it:'Il tuo robot personale', pt:'Seu robô pessoal', ar:'روبوتك الشخصي', hi:'आपका निजी रोबोट', ja:'あなた専用のロボット', ky:'Жеке роботуңуз', 'zh-Hant':'你的私人機器人' },
  onb_intro: { bg:'{0} е твоят личен дневен робот. Активираш го веднъж и всеки ден той изпълнява рутина: сутрешен брифинг, напомняния и (по избор) вечерно резюме — и те известява.', ru:'{0} — ваш личный ежедневный робот. Активируйте его один раз, и каждый день он выполняет рутину: утренний брифинг, напоминания и (по желанию) вечернюю сводку — и уведомляет вас.', uk:'{0} — ваш особистий щоденний робот. Активуйте його один раз, і щодня він виконує рутину: ранковий брифінг, нагадування і (за бажанням) вечірню зведення — і сповіщає вас.', en:'{0} is your personal daily robot. Activate it once and every day it runs a routine: a morning briefing, reminders and (optionally) an evening summary — and notifies you.', de:'{0} ist dein persönlicher Tagesroboter. Einmal aktivieren und jeden Tag erledigt er eine Routine: Morgen-Briefing, Erinnerungen und (optional) Abendzusammenfassung — und benachrichtigt dich.', fr:'{0} est ton robot quotidien personnel. Active-le une fois et chaque jour il exécute une routine : briefing du matin, rappels et (en option) résumé du soir — et te notifie.', es:'{0} es tu robot diario personal. Actívalo una vez y cada día ejecuta una rutina: resumen matutino, recordatorios y (opcional) resumen nocturno — y te avisa.', 'es-MX':'{0} es tu robot diario personal. Actívalo una vez y cada día ejecuta una rutina: resumen matutino, recordatorios y (opcional) resumen nocturno — y te avisa.', it:'{0} è il tuo robot quotidiano personale. Attivalo una volta e ogni giorno esegue una routine: briefing mattutino, promemoria e (facoltativo) riepilogo serale — e ti avvisa.', pt:'{0} é o seu robô diário pessoal. Ative-o uma vez e todo dia ele executa uma rotina: resumo matinal, lembretes e (opcional) resumo noturno — e avisa você.', ar:'{0} روبوتك اليومي الشخصي. فعّله مرة واحدة وكل يوم ينفّذ روتينًا: موجز صباحي وتذكيرات و(اختياريًا) ملخص مسائي — وينبّهك.', hi:'{0} आपका निजी दैनिक रोबोट है। इसे एक बार सक्रिय करें और हर दिन यह एक दिनचर्या चलाता है: सुबह की ब्रीफिंग, रिमाइंडर और (वैकल्पिक) शाम का सारांश — और आपको सूचित करता है।', ja:'{0} はあなた専用の毎日のロボットです。一度有効にすれば、毎日ルーティンを実行します：朝のブリーフィング、リマインダー、（任意で）夜のまとめ — そして通知します。', ky:'{0} — сиздин жеке күнүмдүк роботуңуз. Бир жолу иштетиңиз, ал ар күнү тартипти аткарат: эртеңки брифинг, эскертүүлөр жана (тандоо боюнча) кечки корутунду — жана сизге кабарлайт.', 'zh-Hant':'{0} 是你的私人每日機器人。啟用一次，它每天就會執行例程：早晨簡報、提醒以及（可選的）晚間總結 — 並通知你。' },
  onb_what_title: { bg:'Какво прави роботът', ru:'Что делает робот', uk:'Що робить робот', en:'What the robot does', de:'Was der Roboter tut', fr:'Ce que fait le robot', es:'Qué hace el robot', 'es-MX':'Qué hace el robot', it:'Cosa fa il robot', pt:'O que o robô faz', ar:'ماذا يفعل الروبوت', hi:'रोबोट क्या करता है', ja:'ロボットの役割', ky:'Робот эмне кылат', 'zh-Hant':'機器人做什麼' },
  onb_feat_morning: { bg:'🌤️ Сутрешен брифинг: време, днешна програма и мотивация', ru:'🌤️ Утренний брифинг: погода, программа дня и мотивация', uk:'🌤️ Ранковий брифінг: погода, програма дня і мотивація', en:'🌤️ Morning briefing: weather, today’s agenda and motivation', de:'🌤️ Morgen-Briefing: Wetter, Tagesplan und Motivation', fr:'🌤️ Briefing du matin : météo, programme du jour et motivation', es:'🌤️ Resumen matutino: clima, agenda del día y motivación', 'es-MX':'🌤️ Resumen matutino: clima, agenda del día y motivación', it:'🌤️ Briefing mattutino: meteo, agenda del giorno e motivazione', pt:'🌤️ Resumo matinal: clima, agenda do dia e motivação', ar:'🌤️ موجز صباحي: الطقس وجدول اليوم وتحفيز', hi:'🌤️ सुबह की ब्रीफिंग: मौसम, आज का कार्यक्रम और प्रेरणा', ja:'🌤️ 朝のブリーフィング：天気、今日の予定、モチベーション', ky:'🌤️ Эртеңки брифинг: аба ырайы, бүгүнкү программа жана мотивация', 'zh-Hant':'🌤️ 早晨簡報：天氣、今日行程與激勵' },
  onb_feat_reminders: { bg:'⏰ Напомняния: лекарства, навици, задачи — с часове и дни', ru:'⏰ Напоминания: лекарства, привычки, задачи — с временем и днями', uk:'⏰ Нагадування: ліки, звички, завдання — з часом і днями', en:'⏰ Reminders: medication, habits, tasks — with times and days', de:'⏰ Erinnerungen: Medikamente, Gewohnheiten, Aufgaben — mit Zeiten und Tagen', fr:'⏰ Rappels : médicaments, habitudes, tâches — avec heures et jours', es:'⏰ Recordatorios: medicación, hábitos, tareas — con horas y días', 'es-MX':'⏰ Recordatorios: medicación, hábitos, tareas — con horas y días', it:'⏰ Promemoria: farmaci, abitudini, attività — con orari e giorni', pt:'⏰ Lembretes: remédios, hábitos, tarefas — com horários e dias', ar:'⏰ تذكيرات: الأدوية والعادات والمهام — بالأوقات والأيام', hi:'⏰ रिमाइंडर: दवा, आदतें, कार्य — समय और दिनों के साथ', ja:'⏰ リマインダー：薬、習慣、タスク — 時刻と曜日つき', ky:'⏰ Эскертүүлөр: дары, адаттар, тапшырмалар — убакыт жана күндөр менен', 'zh-Hant':'⏰ 提醒：藥物、習慣、任務 — 含時間與日期' },
  onb_feat_evening: { bg:'🌙 Вечерно резюме (по избор)', ru:'🌙 Вечерняя сводка (по желанию)', uk:'🌙 Вечірнє зведення (за бажанням)', en:'🌙 Evening summary (optional)', de:'🌙 Abendzusammenfassung (optional)', fr:'🌙 Résumé du soir (en option)', es:'🌙 Resumen nocturno (opcional)', 'es-MX':'🌙 Resumen nocturno (opcional)', it:'🌙 Riepilogo serale (facoltativo)', pt:'🌙 Resumo noturno (opcional)', ar:'🌙 ملخص مسائي (اختياري)', hi:'🌙 शाम का सारांश (वैकल्पिक)', ja:'🌙 夜のまとめ（任意）', ky:'🌙 Кечки корутунду (тандоо боюнча)', 'zh-Hant':'🌙 晚間總結（可選）' },
  onb_privacy: { bg:'Всичко е на устройството ти. Без акаунти, без проследяване.', ru:'Всё на вашем устройстве. Без аккаунтов, без отслеживания.', uk:'Усе на вашому пристрої. Без акаунтів, без стеження.', en:'Everything stays on your device. No accounts, no tracking.', de:'Alles bleibt auf deinem Gerät. Keine Konten, kein Tracking.', fr:'Tout reste sur ton appareil. Pas de comptes, pas de suivi.', es:'Todo permanece en tu dispositivo. Sin cuentas, sin rastreo.', 'es-MX':'Todo permanece en tu dispositivo. Sin cuentas, sin rastreo.', it:'Tutto resta sul tuo dispositivo. Nessun account, nessun tracciamento.', pt:'Tudo fica no seu dispositivo. Sem contas, sem rastreamento.', ar:'كل شيء يبقى على جهازك. لا حسابات ولا تتبّع.', hi:'सब कुछ आपके डिवाइस पर रहता है। कोई खाता नहीं, कोई ट्रैकिंग नहीं।', ja:'すべて端末内に保存。アカウント不要、追跡なし。', ky:'Баары түзмөгүңүздө калат. Аккаунтсуз, көзөмөлсүз.', 'zh-Hant':'一切都留在你的裝置上。無帳戶、無追蹤。' },
  onb_activate: { bg:'Активирай робота — безплатно', ru:'Активировать робота — бесплатно', uk:'Активувати робота — безкоштовно', en:'Activate the robot — free', de:'Roboter aktivieren — kostenlos', fr:'Activer le robot — gratuit', es:'Activar el robot — gratis', 'es-MX':'Activar el robot — gratis', it:'Attiva il robot — gratis', pt:'Ativar o robô — grátis', ar:'فعّل الروبوت — مجانًا', hi:'रोबोट सक्रिय करें — निःशुल्क', ja:'ロボットを有効化 — 無料', ky:'Роботту иштетүү — акысыз', 'zh-Hant':'啟用機器人 — 免費' },

  // --- Конфигурация на рутината ---
  cfg_title: { bg:'Настрой рутината', ru:'Настройте рутину', uk:'Налаштуйте рутину', en:'Set up the routine', de:'Routine einrichten', fr:'Configurer la routine', es:'Configura la rutina', 'es-MX':'Configura la rutina', it:'Configura la routine', pt:'Configure a rotina', ar:'إعداد الروتين', hi:'दिनचर्या सेट करें', ja:'ルーティンを設定', ky:'Тартипти жөндөңүз', 'zh-Hant':'設定例程' },
  cfg_sub: { bg:'Кога и какво да включва сутрешният брифинг.', ru:'Когда и что включает утренний брифинг.', uk:'Коли і що містить ранковий брифінг.', en:'When and what the morning briefing includes.', de:'Wann und was das Morgen-Briefing enthält.', fr:'Quand et quoi inclut le briefing du matin.', es:'Cuándo y qué incluye el resumen matutino.', 'es-MX':'Cuándo y qué incluye el resumen matutino.', it:'Quando e cosa include il briefing mattutino.', pt:'Quando e o que o resumo matinal inclui.', ar:'متى وماذا يتضمّن الموجز الصباحي.', hi:'सुबह की ब्रीफिंग कब और क्या शामिल करती है।', ja:'朝のブリーフィングの時刻と内容。', ky:'Эртеңки брифинг качан жана эмнени камтыйт.', 'zh-Hant':'早晨簡報的時間與內容。' },
  cfg_morning_time: { bg:'Час на сутрешния брифинг', ru:'Время утреннего брифинга', uk:'Час ранкового брифінгу', en:'Morning briefing time', de:'Zeit des Morgen-Briefings', fr:'Heure du briefing du matin', es:'Hora del resumen matutino', 'es-MX':'Hora del resumen matutino', it:'Orario del briefing mattutino', pt:'Hora do resumo matinal', ar:'وقت الموجز الصباحي', hi:'सुबह की ब्रीफिंग का समय', ja:'朝のブリーフィングの時刻', ky:'Эртеңки брифингдин убактысы', 'zh-Hant':'早晨簡報時間' },
  cfg_include_title: { bg:'Какво да включва', ru:'Что включать', uk:'Що включати', en:'What to include', de:'Was enthalten sein soll', fr:'Que faut-il inclure', es:'Qué incluir', 'es-MX':'Qué incluir', it:'Cosa includere', pt:'O que incluir', ar:'ما الذي يُضمّن', hi:'क्या शामिल करें', ja:'含める内容', ky:'Эмнени камтуу керек', 'zh-Hant':'包含哪些內容' },
  cfg_weather: { bg:'🌤️ Време', ru:'🌤️ Погода', uk:'🌤️ Погода', en:'🌤️ Weather', de:'🌤️ Wetter', fr:'🌤️ Météo', es:'🌤️ Clima', 'es-MX':'🌤️ Clima', it:'🌤️ Meteo', pt:'🌤️ Clima', ar:'🌤️ الطقس', hi:'🌤️ मौसम', ja:'🌤️ 天気', ky:'🌤️ Аба ырайы', 'zh-Hant':'🌤️ 天氣' },
  cfg_agenda: { bg:'📋 Днешна програма', ru:'📋 Программа дня', uk:'📋 Програма дня', en:'📋 Today’s agenda', de:'📋 Tagesprogramm', fr:'📋 Programme du jour', es:'📋 Agenda del día', 'es-MX':'📋 Agenda del día', it:'📋 Agenda del giorno', pt:'📋 Agenda do dia', ar:'📋 برنامج اليوم', hi:'📋 आज का कार्यक्रम', ja:'📋 今日の予定', ky:'📋 Бүгүнкү программа', 'zh-Hant':'📋 今日行程' },
  cfg_quote: { bg:'💡 Мотивация', ru:'💡 Мотивация', uk:'💡 Мотивація', en:'💡 Motivation', de:'💡 Motivation', fr:'💡 Motivation', es:'💡 Motivación', 'es-MX':'💡 Motivación', it:'💡 Motivazione', pt:'💡 Motivação', ar:'💡 تحفيز', hi:'💡 प्रेरणा', ja:'💡 モチベーション', ky:'💡 Мотивация', 'zh-Hant':'💡 激勵' },
  cfg_evening: { bg:'🌙 Вечерно резюме', ru:'🌙 Вечерняя сводка', uk:'🌙 Вечірнє зведення', en:'🌙 Evening summary', de:'🌙 Abendzusammenfassung', fr:'🌙 Résumé du soir', es:'🌙 Resumen nocturno', 'es-MX':'🌙 Resumen nocturno', it:'🌙 Riepilogo serale', pt:'🌙 Resumo noturno', ar:'🌙 ملخص مسائي', hi:'🌙 शाम का सारांश', ja:'🌙 夜のまとめ', ky:'🌙 Кечки корутунду', 'zh-Hant':'🌙 晚間總結' },
  cfg_evening_time: { bg:'Час на вечерното резюме', ru:'Время вечерней сводки', uk:'Час вечірнього зведення', en:'Evening summary time', de:'Zeit der Abendzusammenfassung', fr:'Heure du résumé du soir', es:'Hora del resumen nocturno', 'es-MX':'Hora del resumen nocturno', it:'Orario del riepilogo serale', pt:'Hora do resumo noturno', ar:'وقت الملخص المسائي', hi:'शाम के सारांश का समय', ja:'夜のまとめの時刻', ky:'Кечки корутундунун убактысы', 'zh-Hant':'晚間總結時間' },
  cfg_next: { bg:'Напред към напомнянията', ru:'Далее к напоминаниям', uk:'Далі до нагадувань', en:'Next: reminders', de:'Weiter zu den Erinnerungen', fr:'Suite : les rappels', es:'Siguiente: recordatorios', 'es-MX':'Siguiente: recordatorios', it:'Avanti: promemoria', pt:'Próximo: lembretes', ar:'التالي: التذكيرات', hi:'आगे: रिमाइंडर', ja:'次へ：リマインダー', ky:'Алга: эскертүүлөр', 'zh-Hant':'下一步：提醒' },

  // --- Напомняния ---
  rem_title: { bg:'Напомняния', ru:'Напоминания', uk:'Нагадування', en:'Reminders', de:'Erinnerungen', fr:'Rappels', es:'Recordatorios', 'es-MX':'Recordatorios', it:'Promemoria', pt:'Lembretes', ar:'التذكيرات', hi:'रिमाइंडर', ja:'リマインダー', ky:'Эскертүүлөр', 'zh-Hant':'提醒' },
  rem_setup_sub: { bg:'Добави напомняния за лекарства, навици или задачи. Можеш и да пропуснеш.', ru:'Добавьте напоминания о лекарствах, привычках или задачах. Можно и пропустить.', uk:'Додайте нагадування про ліки, звички чи завдання. Можна й пропустити.', en:'Add reminders for medication, habits or tasks. You can also skip.', de:'Füge Erinnerungen für Medikamente, Gewohnheiten oder Aufgaben hinzu. Du kannst auch überspringen.', fr:'Ajoute des rappels pour médicaments, habitudes ou tâches. Tu peux aussi passer.', es:'Añade recordatorios de medicación, hábitos o tareas. También puedes omitir.', 'es-MX':'Agrega recordatorios de medicación, hábitos o tareas. También puedes omitir.', it:'Aggiungi promemoria per farmaci, abitudini o attività. Puoi anche saltare.', pt:'Adicione lembretes de remédios, hábitos ou tarefas. Você também pode pular.', ar:'أضف تذكيرات للأدوية أو العادات أو المهام. يمكنك أيضًا التخطّي.', hi:'दवा, आदतों या कार्यों के लिए रिमाइंडर जोड़ें। आप छोड़ भी सकते हैं।', ja:'薬・習慣・タスクのリマインダーを追加。スキップも可能です。', ky:'Дары, адаттар же тапшырмалар үчүн эскертүүлөрдү кошуңуз. Өткөрүп жибере аласыз.', 'zh-Hant':'為藥物、習慣或任務新增提醒。也可以略過。' },
  rem_next: { bg:'Напред към разрешенията', ru:'Далее к разрешениям', uk:'Далі до дозволів', en:'Next: permissions', de:'Weiter zu den Berechtigungen', fr:'Suite : les autorisations', es:'Siguiente: permisos', 'es-MX':'Siguiente: permisos', it:'Avanti: permessi', pt:'Próximo: permissões', ar:'التالي: الأذونات', hi:'आगे: अनुमतियाँ', ja:'次へ：権限', ky:'Алга: уруксаттар', 'zh-Hant':'下一步：權限' },
  rem_new: { bg:'Ново напомняне', ru:'Новое напоминание', uk:'Нове нагадування', en:'New reminder', de:'Neue Erinnerung', fr:'Nouveau rappel', es:'Nuevo recordatorio', 'es-MX':'Nuevo recordatorio', it:'Nuovo promemoria', pt:'Novo lembrete', ar:'تذكير جديد', hi:'नया रिमाइंडर', ja:'新しいリマインダー', ky:'Жаңы эскертүү', 'zh-Hant':'新增提醒' },
  rem_title_ph: { bg:'напр. Витамин D', ru:'напр. Витамин D', uk:'напр. Вітамін D', en:'e.g. Vitamin D', de:'z. B. Vitamin D', fr:'ex. Vitamine D', es:'p. ej. Vitamina D', 'es-MX':'p. ej. Vitamina D', it:'es. Vitamina D', pt:'ex. Vitamina D', ar:'مثال: فيتامين D', hi:'जैसे विटामिन D', ja:'例: ビタミンD', ky:'мис. Витамин D', 'zh-Hant':'例如 維生素D' },
  rem_note_label: { bg:'Бележка (по избор)', ru:'Заметка (по желанию)', uk:'Нотатка (за бажанням)', en:'Note (optional)', de:'Notiz (optional)', fr:'Note (facultatif)', es:'Nota (opcional)', 'es-MX':'Nota (opcional)', it:'Nota (facoltativo)', pt:'Nota (opcional)', ar:'ملاحظة (اختياري)', hi:'नोट (वैकल्पिक)', ja:'メモ（任意）', ky:'Эскертме (тандоо боюнча)', 'zh-Hant':'備註（可選）' },
  rem_note_ph: { bg:'след закуска', ru:'после завтрака', uk:'після сніданку', en:'after breakfast', de:'nach dem Frühstück', fr:'après le petit-déjeuner', es:'después del desayuno', 'es-MX':'después del desayuno', it:'dopo colazione', pt:'após o café da manhã', ar:'بعد الفطور', hi:'नाश्ते के बाद', ja:'朝食後', ky:'эртең мененки тамактан кийин', 'zh-Hant':'早餐後' },
  rem_time_label: { bg:'Час', ru:'Время', uk:'Час', en:'Time', de:'Zeit', fr:'Heure', es:'Hora', 'es-MX':'Hora', it:'Ora', pt:'Hora', ar:'الوقت', hi:'समय', ja:'時刻', ky:'Убакыт', 'zh-Hant':'時間' },
  rem_days_label: { bg:'Дни', ru:'Дни', uk:'Дні', en:'Days', de:'Tage', fr:'Jours', es:'Días', 'es-MX':'Días', it:'Giorni', pt:'Dias', ar:'الأيام', hi:'दिन', ja:'曜日', ky:'Күндөр', 'zh-Hant':'日期' },
  rem_add: { bg:'Добави напомняне', ru:'Добавить напоминание', uk:'Додати нагадування', en:'Add reminder', de:'Erinnerung hinzufügen', fr:'Ajouter un rappel', es:'Añadir recordatorio', 'es-MX':'Agregar recordatorio', it:'Aggiungi promemoria', pt:'Adicionar lembrete', ar:'إضافة تذكير', hi:'रिमाइंडर जोड़ें', ja:'リマインダーを追加', ky:'Эскертүү кошуу', 'zh-Hant':'新增提醒' },
  rem_empty: { bg:'Все още няма напомняния.', ru:'Пока нет напоминаний.', uk:'Поки немає нагадувань.', en:'No reminders yet.', de:'Noch keine Erinnerungen.', fr:'Aucun rappel pour l’instant.', es:'Aún no hay recordatorios.', 'es-MX':'Aún no hay recordatorios.', it:'Ancora nessun promemoria.', pt:'Ainda sem lembretes.', ar:'لا تذكيرات بعد.', hi:'अभी कोई रिमाइंडर नहीं।', ja:'まだリマインダーがありません。', ky:'Азырынча эскертүүлөр жок.', 'zh-Hant':'尚無提醒。' },
  rem_everyday: { bg:'всеки ден', ru:'каждый день', uk:'щодня', en:'every day', de:'jeden Tag', fr:'tous les jours', es:'todos los días', 'es-MX':'todos los días', it:'ogni giorno', pt:'todos os dias', ar:'كل يوم', hi:'हर दिन', ja:'毎日', ky:'күн сайын', 'zh-Hant':'每天' },
  rem_pause: { bg:'Пауза', ru:'Пауза', uk:'Пауза', en:'Pause', de:'Pause', fr:'Pause', es:'Pausar', 'es-MX':'Pausar', it:'Pausa', pt:'Pausar', ar:'إيقاف مؤقت', hi:'रोकें', ja:'一時停止', ky:'Тыныгуу', 'zh-Hant':'暫停' },
  rem_resume: { bg:'Възобнови', ru:'Возобновить', uk:'Відновити', en:'Resume', de:'Fortsetzen', fr:'Reprendre', es:'Reanudar', 'es-MX':'Reanudar', it:'Riprendi', pt:'Retomar', ar:'استئناف', hi:'फिर शुरू करें', ja:'再開', ky:'Улантуу', 'zh-Hant':'繼續' },

  // --- Дни от седмицата (кратки) ---
  day_sun: { bg:'Нд', ru:'Вс', uk:'Нд', en:'Sun', de:'So', fr:'Dim', es:'Dom', 'es-MX':'Dom', it:'Dom', pt:'Dom', ar:'أحد', hi:'रवि', ja:'日', ky:'Жк', 'zh-Hant':'日' },
  day_mon: { bg:'Пн', ru:'Пн', uk:'Пн', en:'Mon', de:'Mo', fr:'Lun', es:'Lun', 'es-MX':'Lun', it:'Lun', pt:'Seg', ar:'إثن', hi:'सोम', ja:'月', ky:'Дш', 'zh-Hant':'一' },
  day_tue: { bg:'Вт', ru:'Вт', uk:'Вт', en:'Tue', de:'Di', fr:'Mar', es:'Mar', 'es-MX':'Mar', it:'Mar', pt:'Ter', ar:'ثلا', hi:'मंगल', ja:'火', ky:'Шш', 'zh-Hant':'二' },
  day_wed: { bg:'Ср', ru:'Ср', uk:'Ср', en:'Wed', de:'Mi', fr:'Mer', es:'Mié', 'es-MX':'Mié', it:'Mer', pt:'Qua', ar:'أرب', hi:'बुध', ja:'水', ky:'Шр', 'zh-Hant':'三' },
  day_thu: { bg:'Чт', ru:'Чт', uk:'Чт', en:'Thu', de:'Do', fr:'Jeu', es:'Jue', 'es-MX':'Jue', it:'Gio', pt:'Qui', ar:'خمي', hi:'गुरु', ja:'木', ky:'Бш', 'zh-Hant':'四' },
  day_fri: { bg:'Пт', ru:'Пт', uk:'Пт', en:'Fri', de:'Fr', fr:'Ven', es:'Vie', 'es-MX':'Vie', it:'Ven', pt:'Sex', ar:'جمع', hi:'शुक्र', ja:'金', ky:'Жм', 'zh-Hant':'五' },
  day_sat: { bg:'Сб', ru:'Сб', uk:'Сб', en:'Sat', de:'Sa', fr:'Sam', es:'Sáb', 'es-MX':'Sáb', it:'Sab', pt:'Sáb', ar:'سبت', hi:'शनि', ja:'土', ky:'Иш', 'zh-Hant':'六' },

  // --- Събития / задачи ---
  ev_new: { bg:'Ново събитие / задача', ru:'Новое событие / задача', uk:'Нова подія / завдання', en:'New event / task', de:'Neues Ereignis / Aufgabe', fr:'Nouvel événement / tâche', es:'Nuevo evento / tarea', 'es-MX':'Nuevo evento / tarea', it:'Nuovo evento / attività', pt:'Novo evento / tarefa', ar:'حدث / مهمة جديدة', hi:'नया इवेंट / कार्य', ja:'新しい予定 / タスク', ky:'Жаңы окуя / тапшырма', 'zh-Hant':'新增事件 / 任務' },
  ev_title_ph: { bg:'напр. Среща с екипа', ru:'напр. Встреча с командой', uk:'напр. Зустріч з командою', en:'e.g. Team meeting', de:'z. B. Team-Meeting', fr:'ex. Réunion d’équipe', es:'p. ej. Reunión de equipo', 'es-MX':'p. ej. Junta de equipo', it:'es. Riunione del team', pt:'ex. Reunião da equipe', ar:'مثال: اجتماع الفريق', hi:'जैसे टीम मीटिंग', ja:'例: チーム会議', ky:'мис. Команда менен жолугушуу', 'zh-Hant':'例如 團隊會議' },
  ev_date: { bg:'Дата', ru:'Дата', uk:'Дата', en:'Date', de:'Datum', fr:'Date', es:'Fecha', 'es-MX':'Fecha', it:'Data', pt:'Data', ar:'التاريخ', hi:'तारीख', ja:'日付', ky:'Күн', 'zh-Hant':'日期' },
  ev_time_opt: { bg:'Час (по избор)', ru:'Время (по желанию)', uk:'Час (за бажанням)', en:'Time (optional)', de:'Zeit (optional)', fr:'Heure (facultatif)', es:'Hora (opcional)', 'es-MX':'Hora (opcional)', it:'Ora (facoltativo)', pt:'Hora (opcional)', ar:'الوقت (اختياري)', hi:'समय (वैकल्पिक)', ja:'時刻（任意）', ky:'Убакыт (тандоо боюнча)', 'zh-Hant':'時間（可選）' },
  ev_empty: { bg:'Няма събития.', ru:'Нет событий.', uk:'Немає подій.', en:'No events.', de:'Keine Ereignisse.', fr:'Aucun événement.', es:'Sin eventos.', 'es-MX':'Sin eventos.', it:'Nessun evento.', pt:'Sem eventos.', ar:'لا أحداث.', hi:'कोई इवेंट नहीं।', ja:'予定なし。', ky:'Окуялар жок.', 'zh-Hant':'沒有事件。' },
  ev_done_pill: { bg:'готово', ru:'готово', uk:'готово', en:'done', de:'erledigt', fr:'fait', es:'hecho', 'es-MX':'hecho', it:'fatto', pt:'feito', ar:'تم', hi:'पूर्ण', ja:'完了', ky:'бүттү', 'zh-Hant':'已完成' },
  ev_open_pill: { bg:'отворено', ru:'открыто', uk:'відкрито', en:'open', de:'offen', fr:'ouvert', es:'abierto', 'es-MX':'abierto', it:'aperto', pt:'aberto', ar:'مفتوح', hi:'खुला', ja:'未完了', ky:'ачык', 'zh-Hant':'進行中' },
  ev_mark_done: { bg:'Готово', ru:'Готово', uk:'Готово', en:'Done', de:'Erledigt', fr:'Fait', es:'Hecho', 'es-MX':'Hecho', it:'Fatto', pt:'Feito', ar:'تم', hi:'पूर्ण', ja:'完了', ky:'Бүттү', 'zh-Hant':'完成' },
  ev_undo: { bg:'Отмени', ru:'Отменить', uk:'Скасувати', en:'Undo', de:'Rückgängig', fr:'Annuler', es:'Deshacer', 'es-MX':'Deshacer', it:'Annulla', pt:'Desfazer', ar:'تراجع', hi:'पूर्ववत करें', ja:'取り消し', ky:'Кайтаруу', 'zh-Hant':'復原' },

  // --- Табло ---
  dash_robot: { bg:'🤖 Роботът', ru:'🤖 Робот', uk:'🤖 Робот', en:'🤖 The robot', de:'🤖 Der Roboter', fr:'🤖 Le robot', es:'🤖 El robot', 'es-MX':'🤖 El robot', it:'🤖 Il robot', pt:'🤖 O robô', ar:'🤖 الروبوت', hi:'🤖 रोबोट', ja:'🤖 ロボット', ky:'🤖 Робот', 'zh-Hant':'🤖 機器人' },
  dash_active: { bg:'АКТИВЕН', ru:'АКТИВЕН', uk:'АКТИВНИЙ', en:'ACTIVE', de:'AKTIV', fr:'ACTIF', es:'ACTIVO', 'es-MX':'ACTIVO', it:'ATTIVO', pt:'ATIVO', ar:'نشط', hi:'सक्रिय', ja:'稼働中', ky:'ИШТЕП ЖАТАТ', 'zh-Hant':'運作中' },
  dash_stopped: { bg:'СПРЯН', ru:'ОСТАНОВЛЕН', uk:'ЗУПИНЕНИЙ', en:'STOPPED', de:'GESTOPPT', fr:'ARRÊTÉ', es:'DETENIDO', 'es-MX':'DETENIDO', it:'FERMO', pt:'PARADO', ar:'متوقف', hi:'रुका हुआ', ja:'停止中', ky:'ТОКТОТУЛДУ', 'zh-Hant':'已停止' },
  dash_active_note: { bg:'Роботът изпълнява рутината ти.', ru:'Робот выполняет вашу рутину.', uk:'Робот виконує вашу рутину.', en:'The robot is running your routine.', de:'Der Roboter führt deine Routine aus.', fr:'Le robot exécute ta routine.', es:'El robot está ejecutando tu rutina.', 'es-MX':'El robot está ejecutando tu rutina.', it:'Il robot sta eseguendo la tua routine.', pt:'O robô está executando sua rotina.', ar:'الروبوت ينفّذ روتينك.', hi:'रोबोट आपकी दिनचर्या चला रहा है।', ja:'ロボットがあなたのルーティンを実行中です。', ky:'Робот сиздин тартибиңизди аткарып жатат.', 'zh-Hant':'機器人正在執行你的例程。' },
  dash_paused_note: { bg:'Роботът е на пауза.', ru:'Робот на паузе.', uk:'Робот на паузі.', en:'The robot is paused.', de:'Der Roboter ist pausiert.', fr:'Le robot est en pause.', es:'El robot está en pausa.', 'es-MX':'El robot está en pausa.', it:'Il robot è in pausa.', pt:'O robô está em pausa.', ar:'الروبوت في وضع الإيقاف المؤقت.', hi:'रोबोट रुका हुआ है।', ja:'ロボットは一時停止中です。', ky:'Робот тыныгууда.', 'zh-Hant':'機器人已暫停。' },
  dash_stop: { bg:'Спри робота', ru:'Остановить робота', uk:'Зупинити робота', en:'Stop the robot', de:'Roboter stoppen', fr:'Arrêter le robot', es:'Detener el robot', 'es-MX':'Detener el robot', it:'Ferma il robot', pt:'Parar o robô', ar:'إيقاف الروبوت', hi:'रोबोट रोकें', ja:'ロボットを停止', ky:'Роботту токтотуу', 'zh-Hant':'停止機器人' },
  dash_start: { bg:'Стартирай робота', ru:'Запустить робота', uk:'Запустити робота', en:'Start the robot', de:'Roboter starten', fr:'Démarrer le robot', es:'Iniciar el robot', 'es-MX':'Iniciar el robot', it:'Avvia il robot', pt:'Iniciar o robô', ar:'تشغيل الروبوت', hi:'रोबोट शुरू करें', ja:'ロボットを起動', ky:'Роботту иштетүү', 'zh-Hant':'啟動機器人' },
  dash_preview: { bg:'👁️ Преглед на брифинга сега', ru:'👁️ Предпросмотр брифинга сейчас', uk:'👁️ Перегляд брифінгу зараз', en:'👁️ Preview the briefing now', de:'👁️ Briefing jetzt ansehen', fr:'👁️ Aperçu du briefing maintenant', es:'👁️ Vista previa del resumen ahora', 'es-MX':'👁️ Vista previa del resumen ahora', it:'👁️ Anteprima del briefing ora', pt:'👁️ Pré-visualizar o resumo agora', ar:'👁️ معاينة الموجز الآن', hi:'👁️ अभी ब्रीफिंग देखें', ja:'👁️ ブリーフィングを今すぐプレビュー', ky:'👁️ Брифингди азыр көрүү', 'zh-Hant':'👁️ 立即預覽簡報' },
  dash_bg_title: { bg:'🔋 Фонов режим', ru:'🔋 Фоновый режим', uk:'🔋 Фоновий режим', en:'🔋 Background mode', de:'🔋 Hintergrundmodus', fr:'🔋 Mode arrière-plan', es:'🔋 Modo en segundo plano', 'es-MX':'🔋 Modo en segundo plano', it:'🔋 Modalità in background', pt:'🔋 Modo em segundo plano', ar:'🔋 وضع الخلفية', hi:'🔋 बैकग्राउंड मोड', ja:'🔋 バックグラウンド動作', ky:'🔋 Фондук режим', 'zh-Hant':'🔋 背景模式' },
  dash_bg_native: { bg:'Когато роботът е АКТИВЕН, напомнянията и брифингът се доставят дори при ЗАТВОРЕНО приложение (нативно планирани известия). Не е нужно да го държиш отворен. Изисква разрешение за известия.', ru:'Когда робот АКТИВЕН, напоминания и брифинг доставляются даже при ЗАКРЫТОМ приложении (нативно запланированные уведомления). Держать открытым не нужно. Требуется разрешение на уведомления.', uk:'Коли робот АКТИВНИЙ, нагадування і брифінг доставляються навіть при ЗАКРИТОМУ застосунку (нативно заплановані сповіщення). Тримати відкритим не потрібно. Потрібен дозвіл на сповіщення.', en:'When the robot is ACTIVE, reminders and the briefing are delivered even when the app is CLOSED (natively scheduled notifications). No need to keep it open. Requires notification permission.', de:'Wenn der Roboter AKTIV ist, werden Erinnerungen und Briefing auch bei GESCHLOSSENER App geliefert (nativ geplante Benachrichtigungen). Du musst sie nicht offen halten. Erfordert Benachrichtigungsberechtigung.', fr:'Quand le robot est ACTIF, les rappels et le briefing sont livrés même appli FERMÉE (notifications programmées nativement). Pas besoin de la garder ouverte. Nécessite l’autorisation de notifications.', es:'Cuando el robot está ACTIVO, los recordatorios y el resumen llegan incluso con la app CERRADA (notificaciones programadas de forma nativa). No hace falta mantenerla abierta. Requiere permiso de notificaciones.', 'es-MX':'Cuando el robot está ACTIVO, los recordatorios y el resumen llegan incluso con la app CERRADA (notificaciones programadas de forma nativa). No hace falta mantenerla abierta. Requiere permiso de notificaciones.', it:'Quando il robot è ATTIVO, promemoria e briefing arrivano anche ad app CHIUSA (notifiche pianificate in modo nativo). Non serve tenerla aperta. Richiede il permesso per le notifiche.', pt:'Quando o robô está ATIVO, lembretes e resumo são entregues mesmo com o app FECHADO (notificações agendadas nativamente). Não precisa mantê-lo aberto. Requer permissão de notificações.', ar:'عندما يكون الروبوت نشطًا، تُسلَّم التذكيرات والموجز حتى عند إغلاق التطبيق (إشعارات مجدولة محليًا). لا حاجة لإبقائه مفتوحًا. يتطلب إذن الإشعارات.', hi:'जब रोबोट सक्रिय है, ऐप बंद होने पर भी रिमाइंडर और ब्रीफिंग पहुँचते हैं (मूल रूप से शेड्यूल किए गए नोटिफ़िकेशन)। इसे खुला रखने की ज़रूरत नहीं। नोटिफ़िकेशन अनुमति आवश्यक।', ja:'ロボットが稼働中なら、アプリを閉じていてもリマインダーとブリーフィングが届きます（ネイティブにスケジュールされた通知）。開いたままにする必要はありません。通知権限が必要です。', ky:'Робот ИШТЕП жатканда, эскертүүлөр жана брифинг колдонмо ЖАБЫК болсо да жеткирилет (нативдик пландалган билдирүүлөр). Ачык кармоонун кереги жок. Билдирүү уруксаты талап кылынат.', 'zh-Hant':'機器人運作時，即使應用程式關閉，提醒與簡報仍會送達（原生排程通知）。無需保持開啟。需要通知權限。' },
  dash_bg_web: { bg:'В браузър напомнянията работят само докато приложението е отворено. На телефона (инсталирано) работят и при затворено — нативно планирани известия.', ru:'В браузере напоминания работают, только пока приложение открыто. На телефоне (установленное) работают и при закрытом — нативно запланированные уведомления.', uk:'У браузері нагадування працюють лише поки застосунок відкритий. На телефоні (встановлений) працюють і при закритому — нативно заплановані сповіщення.', en:'In a browser, reminders work only while the app is open. On a phone (installed) they also work when closed — natively scheduled notifications.', de:'Im Browser funktionieren Erinnerungen nur, solange die App offen ist. Auf dem Handy (installiert) auch bei geschlossener App — nativ geplante Benachrichtigungen.', fr:'Dans un navigateur, les rappels ne fonctionnent que tant que l’appli est ouverte. Sur téléphone (installée), aussi fermée — notifications programmées nativement.', es:'En un navegador, los recordatorios funcionan solo mientras la app está abierta. En un teléfono (instalada) también funcionan cerrada — notificaciones programadas de forma nativa.', 'es-MX':'En un navegador, los recordatorios funcionan solo mientras la app está abierta. En un teléfono (instalada) también funcionan cerrada — notificaciones programadas de forma nativa.', it:'In un browser i promemoria funzionano solo finché l’app è aperta. Su telefono (installata) anche da chiusa — notifiche pianificate in modo nativo.', pt:'No navegador, os lembretes funcionam apenas com o app aberto. No celular (instalado) funcionam também fechado — notificações agendadas nativamente.', ar:'في المتصفح تعمل التذكيرات فقط أثناء فتح التطبيق. على الهاتف (مثبَّت) تعمل أيضًا عند الإغلاق — إشعارات مجدولة محليًا.', hi:'ब्राउज़र में रिमाइंडर केवल ऐप खुला रहने पर काम करते हैं। फ़ोन पर (इंस्टॉल) बंद होने पर भी काम करते हैं — मूल रूप से शेड्यूल किए नोटिफ़िकेशन।', ja:'ブラウザではアプリを開いている間だけリマインダーが動作します。スマホ（インストール版）では閉じていても動作します — ネイティブにスケジュールされた通知。', ky:'Браузерде эскертүүлөр колдонмо ачык турганда гана иштейт. Телефондо (орнотулган) жабык болсо да иштейт — нативдик пландалган билдирүүлөр.', 'zh-Hant':'在瀏覽器中，提醒僅在應用程式開啟時有效。手機上（已安裝）關閉時也有效 — 原生排程通知。' },
  dash_reset_routine: { bg:'Нулирай настройките на рутината', ru:'Сбросить настройки рутины', uk:'Скинути налаштування рутини', en:'Reset routine settings', de:'Routine-Einstellungen zurücksetzen', fr:'Réinitialiser les réglages de la routine', es:'Restablecer ajustes de la rutina', 'es-MX':'Restablecer ajustes de la rutina', it:'Reimposta le impostazioni della routine', pt:'Redefinir configurações da rotina', ar:'إعادة ضبط إعدادات الروتين', hi:'दिनचर्या सेटिंग्स रीसेट करें', ja:'ルーティン設定をリセット', ky:'Тартип жөндөөлөрүн баштапкы абалга келтирүү', 'zh-Hant':'重設例程設定' },
  dash_timeline: { bg:'Времева линия на деня', ru:'Расписание дня', uk:'Розклад дня', en:'Day timeline', de:'Tagesablauf', fr:'Chronologie du jour', es:'Línea de tiempo del día', 'es-MX':'Línea de tiempo del día', it:'Cronologia della giornata', pt:'Linha do tempo do dia', ar:'الخط الزمني لليوم', hi:'दिन की समयरेखा', ja:'1日のタイムライン', ky:'Күндүн убакыт сызыгы', 'zh-Hant':'當日時間軸' },
  dash_timeline_empty: { bg:'Празна линия — добави елементи.', ru:'Расписание пусто — добавьте элементы.', uk:'Розклад порожній — додайте елементи.', en:'Empty timeline — add some items.', de:'Leerer Ablauf — füge Einträge hinzu.', fr:'Chronologie vide — ajoute des éléments.', es:'Línea de tiempo vacía — añade elementos.', 'es-MX':'Línea de tiempo vacía — agrega elementos.', it:'Cronologia vuota — aggiungi elementi.', pt:'Linha do tempo vazia — adicione itens.', ar:'الخط الزمني فارغ — أضف عناصر.', hi:'समयरेखा खाली है — आइटम जोड़ें।', ja:'タイムラインが空です — 項目を追加してください。', ky:'Убакыт сызыгы бош — элементтерди кошуңуз.', 'zh-Hant':'時間軸是空的 — 新增項目。' },
  dash_tl_morning: { bg:'🌤️ Сутрешен брифинг', ru:'🌤️ Утренний брифинг', uk:'🌤️ Ранковий брифінг', en:'🌤️ Morning briefing', de:'🌤️ Morgen-Briefing', fr:'🌤️ Briefing du matin', es:'🌤️ Resumen matutino', 'es-MX':'🌤️ Resumen matutino', it:'🌤️ Briefing mattutino', pt:'🌤️ Resumo matinal', ar:'🌤️ موجز صباحي', hi:'🌤️ सुबह की ब्रीफिंग', ja:'🌤️ 朝のブリーフィング', ky:'🌤️ Эртеңки брифинг', 'zh-Hant':'🌤️ 早晨簡報' },
  dash_tl_evening: { bg:'🌙 Вечерно резюме', ru:'🌙 Вечерняя сводка', uk:'🌙 Вечірнє зведення', en:'🌙 Evening summary', de:'🌙 Abendzusammenfassung', fr:'🌙 Résumé du soir', es:'🌙 Resumen nocturno', 'es-MX':'🌙 Resumen nocturno', it:'🌙 Riepilogo serale', pt:'🌙 Resumo noturno', ar:'🌙 ملخص مسائي', hi:'🌙 शाम का सारांश', ja:'🌙 夜のまとめ', ky:'🌙 Кечки корутунду', 'zh-Hant':'🌙 晚間總結' },
  dash_reminders: { bg:'Напомняния', ru:'Напоминания', uk:'Нагадування', en:'Reminders', de:'Erinnerungen', fr:'Rappels', es:'Recordatorios', 'es-MX':'Recordatorios', it:'Promemoria', pt:'Lembretes', ar:'التذكيرات', hi:'रिमाइंडर', ja:'リマインダー', ky:'Эскертүүлөр', 'zh-Hant':'提醒' },
  dash_events: { bg:'Събития и задачи', ru:'События и задачи', uk:'Події та завдання', en:'Events and tasks', de:'Ereignisse und Aufgaben', fr:'Événements et tâches', es:'Eventos y tareas', 'es-MX':'Eventos y tareas', it:'Eventi e attività', pt:'Eventos e tarefas', ar:'الأحداث والمهام', hi:'इवेंट और कार्य', ja:'予定とタスク', ky:'Окуялар жана тапшырмалар', 'zh-Hant':'事件與任務' },
  dash_log: { bg:'Дневник на активността', ru:'Журнал активности', uk:'Журнал активності', en:'Activity log', de:'Aktivitätsprotokoll', fr:'Journal d’activité', es:'Registro de actividad', 'es-MX':'Registro de actividad', it:'Registro attività', pt:'Registro de atividade', ar:'سجل النشاط', hi:'गतिविधि लॉग', ja:'アクティビティ履歴', ky:'Аракеттер журналы', 'zh-Hant':'活動紀錄' },
  dash_log_empty: { bg:'Все още няма записи.', ru:'Пока нет записей.', uk:'Поки немає записів.', en:'No entries yet.', de:'Noch keine Einträge.', fr:'Aucune entrée pour l’instant.', es:'Aún no hay registros.', 'es-MX':'Aún no hay registros.', it:'Ancora nessuna voce.', pt:'Ainda sem registros.', ar:'لا إدخالات بعد.', hi:'अभी कोई प्रविष्टि नहीं।', ja:'まだ記録がありません。', ky:'Азырынча жазуулар жок.', 'zh-Hant':'尚無紀錄。' },
  dash_reset_app: { bg:'Нулирай приложението', ru:'Сбросить приложение', uk:'Скинути застосунок', en:'Reset the app', de:'App zurücksetzen', fr:'Réinitialiser l’appli', es:'Restablecer la app', 'es-MX':'Restablecer la app', it:'Reimposta l’app', pt:'Redefinir o app', ar:'إعادة ضبط التطبيق', hi:'ऐप रीसेट करें', ja:'アプリをリセット', ky:'Колдонмону баштапкы абалга келтирүү', 'zh-Hant':'重設應用程式' },
  toast_routine: { bg:'Рутина', ru:'Рутина', uk:'Рутина', en:'Routine', de:'Routine', fr:'Routine', es:'Rutina', 'es-MX':'Rutina', it:'Routine', pt:'Rotina', ar:'الروتين', hi:'दिनचर्या', ja:'ルーティン', ky:'Күн тартиби', 'zh-Hant':'例程' },
  toast_routine_reset: { bg:'Настройките на рутината са върнати по подразбиране.', ru:'Настройки рутины возвращены к значениям по умолчанию.', uk:'Налаштування рутини повернено до типових.', en:'Routine settings restored to defaults.', de:'Routine-Einstellungen auf Standard zurückgesetzt.', fr:'Réglages de la routine remis par défaut.', es:'Ajustes de la rutina restaurados por defecto.', 'es-MX':'Ajustes de la rutina restaurados por defecto.', it:'Impostazioni della routine ripristinate ai valori predefiniti.', pt:'Configurações da rotina restauradas ao padrão.', ar:'أُعيدت إعدادات الروتين إلى الوضع الافتراضي.', hi:'दिनचर्या सेटिंग्स डिफ़ॉल्ट पर बहाल।', ja:'ルーティン設定を初期値に戻しました。', ky:'Тартип жөндөөлөрү демейкиге кайтарылды.', 'zh-Hant':'例程設定已還原為預設值。' },
  toast_preview_title: { bg:'🤖 Брифинг (преглед)', ru:'🤖 Брифинг (предпросмотр)', uk:'🤖 Брифінг (перегляд)', en:'🤖 Briefing (preview)', de:'🤖 Briefing (Vorschau)', fr:'🤖 Briefing (aperçu)', es:'🤖 Resumen (vista previa)', 'es-MX':'🤖 Resumen (vista previa)', it:'🤖 Briefing (anteprima)', pt:'🤖 Resumo (prévia)', ar:'🤖 الموجز (معاينة)', hi:'🤖 ब्रीफिंग (पूर्वावलोकन)', ja:'🤖 ブリーフィング（プレビュー）', ky:'🤖 Брифинг (көрүү)', 'zh-Hant':'🤖 簡報（預覽）' },

  // --- Бележки ---
  notes_title: { bg:'📝 Бележки', ru:'📝 Заметки', uk:'📝 Нотатки', en:'📝 Notes', de:'📝 Notizen', fr:'📝 Notes', es:'📝 Notas', 'es-MX':'📝 Notas', it:'📝 Note', pt:'📝 Notas', ar:'📝 الملاحظات', hi:'📝 नोट्स', ja:'📝 メモ', ky:'📝 Эскертүүлөр', 'zh-Hant':'📝 筆記' },
  notes_intro: { bg:'Запиши бележки, които роботът да помни — и да ти ги ИЗГОВАРЯ на избрания език (един от 15-те на екосистемата).', ru:'Записывайте заметки, которые робот запомнит — и будет ПРОИЗНОСИТЬ их на выбранном языке (одном из 15 в экосистеме).', uk:'Записуйте нотатки, які робот запам’ятає — і ОЗВУЧУВАТИМЕ їх обраною мовою (однією з 15 в екосистемі).', en:'Write notes the robot will remember — and SPEAK them aloud in the language you choose (one of the 15 in the ecosystem).', de:'Schreibe Notizen, die der Roboter sich merkt — und sie in der gewählten Sprache VORLIEST (eine der 15 im Ökosystem).', fr:'Écris des notes que le robot retiendra — et qu’il LIRA à voix haute dans la langue choisie (l’une des 15 de l’écosystème).', es:'Escribe notas que el robot recordará — y las DIRÁ en voz alta en el idioma que elijas (uno de los 15 del ecosistema).', 'es-MX':'Escribe notas que el robot recordará — y las DIRÁ en voz alta en el idioma que elijas (uno de los 15 del ecosistema).', it:'Scrivi note che il robot ricorderà — e le LEGGERÀ ad alta voce nella lingua scelta (una delle 15 dell’ecosistema).', pt:'Escreva notas que o robô vai lembrar — e FALAR em voz alta no idioma escolhido (um dos 15 do ecossistema).', ar:'اكتب ملاحظات يتذكّرها الروبوت — وينطقها بصوت عالٍ باللغة التي تختارها (إحدى الـ15 في المنظومة).', hi:'ऐसे नोट्स लिखें जो रोबोट याद रखे — और चुनी हुई भाषा (इकोसिस्टम की 15 में से) में बोलकर सुनाए।', ja:'ロボットが覚えるメモを書くと、選んだ言語（エコシステムの15言語のいずれか）で読み上げます。', ky:'Робот эстеп кала турган эскертүүлөрдү жазыңыз — жана аларды тандалган тилде (экосистеманын 15 тилинин бири) АЙТЫП берет.', 'zh-Hant':'寫下機器人會記住的筆記 — 並以你選的語言（生態系 15 種之一）朗讀出來。' },
  notes_new: { bg:'Нова бележка', ru:'Новая заметка', uk:'Нова нотатка', en:'New note', de:'Neue Notiz', fr:'Nouvelle note', es:'Nueva nota', 'es-MX':'Nueva nota', it:'Nuova nota', pt:'Nova nota', ar:'ملاحظة جديدة', hi:'नया नोट', ja:'新しいメモ', ky:'Жаңы эскертүү', 'zh-Hant':'新增筆記' },
  notes_text_ph: { bg:'напр. Купи хляб и мляко; обади се на мама в 18:00', ru:'напр. Купить хлеб и молоко; позвонить маме в 18:00', uk:'напр. Купити хліб і молоко; подзвонити мамі о 18:00', en:'e.g. Buy bread and milk; call mom at 18:00', de:'z. B. Brot und Milch kaufen; Mama um 18:00 anrufen', fr:'ex. Acheter du pain et du lait ; appeler maman à 18h00', es:'p. ej. Comprar pan y leche; llamar a mamá a las 18:00', 'es-MX':'p. ej. Comprar pan y leche; llamar a mamá a las 18:00', it:'es. Comprare pane e latte; chiamare mamma alle 18:00', pt:'ex. Comprar pão e leite; ligar para a mãe às 18:00', ar:'مثال: اشترِ خبزًا وحليبًا؛ اتصل بأمي الساعة 18:00', hi:'जैसे ब्रेड और दूध खरीदें; 18:00 बजे माँ को कॉल करें', ja:'例: パンと牛乳を買う；18時にお母さんに電話', ky:'мис. Нан жана сүт сатып ал; 18:00дө апама чал', 'zh-Hant':'例如 買麵包和牛奶；18:00 打給媽媽' },
  notes_speak_lang: { bg:'Език за изговаряне', ru:'Язык произношения', uk:'Мова озвучення', en:'Speaking language', de:'Sprechsprache', fr:'Langue de lecture', es:'Idioma de voz', 'es-MX':'Idioma de voz', it:'Lingua di lettura', pt:'Idioma de fala', ar:'لغة النطق', hi:'बोलने की भाषा', ja:'読み上げ言語', ky:'Айтуу тили', 'zh-Hant':'朗讀語言' },
  notes_add: { bg:'Добави бележка', ru:'Добавить заметку', uk:'Додати нотатку', en:'Add note', de:'Notiz hinzufügen', fr:'Ajouter une note', es:'Añadir nota', 'es-MX':'Agregar nota', it:'Aggiungi nota', pt:'Adicionar nota', ar:'إضافة ملاحظة', hi:'नोट जोड़ें', ja:'メモを追加', ky:'Эскертүү кошуу', 'zh-Hant':'新增筆記' },
  notes_no_tts: { bg:'⚠ Гласът не е наличен на това устройство — бележките пак се пазят.', ru:'⚠ Голос недоступен на этом устройстве — заметки всё равно сохраняются.', uk:'⚠ Голос недоступний на цьому пристрої — нотатки все одно зберігаються.', en:'⚠ Voice is not available on this device — notes are still saved.', de:'⚠ Sprache auf diesem Gerät nicht verfügbar — Notizen werden trotzdem gespeichert.', fr:'⚠ La voix n’est pas disponible sur cet appareil — les notes sont quand même enregistrées.', es:'⚠ La voz no está disponible en este dispositivo — las notas igual se guardan.', 'es-MX':'⚠ La voz no está disponible en este dispositivo — las notas igual se guardan.', it:'⚠ La voce non è disponibile su questo dispositivo — le note vengono comunque salvate.', pt:'⚠ A voz não está disponível neste dispositivo — as notas ainda são salvas.', ar:'⚠ الصوت غير متاح على هذا الجهاز — تُحفظ الملاحظات على أي حال.', hi:'⚠ इस डिवाइस पर वॉइस उपलब्ध नहीं — नोट्स फिर भी सहेजे जाते हैं।', ja:'⚠ この端末では音声が利用できません — メモは保存されます。', ky:'⚠ Бул түзмөктө добуш жок — эскертүүлөр баары бир сакталат.', 'zh-Hant':'⚠ 此裝置無法使用語音 — 筆記仍會儲存。' },
  notes_empty: { bg:'Още няма бележки.', ru:'Пока нет заметок.', uk:'Поки немає нотаток.', en:'No notes yet.', de:'Noch keine Notizen.', fr:'Aucune note pour l’instant.', es:'Aún no hay notas.', 'es-MX':'Aún no hay notas.', it:'Ancora nessuna nota.', pt:'Ainda sem notas.', ar:'لا ملاحظات بعد.', hi:'अभी कोई नोट नहीं।', ja:'まだメモがありません。', ky:'Азырынча эскертүүлөр жок.', 'zh-Hant':'尚無筆記。' },
  notes_speak: { bg:'▶️ Изговори', ru:'▶️ Произнести', uk:'▶️ Озвучити', en:'▶️ Speak', de:'▶️ Vorlesen', fr:'▶️ Lire', es:'▶️ Decir', 'es-MX':'▶️ Decir', it:'▶️ Leggi', pt:'▶️ Falar', ar:'▶️ انطق', hi:'▶️ बोलें', ja:'▶️ 読み上げ', ky:'▶️ Айтуу', 'zh-Hant':'▶️ 朗讀' },
  notes_delete: { bg:'🗑️ Изтрий', ru:'🗑️ Удалить', uk:'🗑️ Видалити', en:'🗑️ Delete', de:'🗑️ Löschen', fr:'🗑️ Supprimer', es:'🗑️ Eliminar', 'es-MX':'🗑️ Eliminar', it:'🗑️ Elimina', pt:'🗑️ Excluir', ar:'🗑️ حذف', hi:'🗑️ हटाएं', ja:'🗑️ 削除', ky:'🗑️ Өчүрүү', 'zh-Hant':'🗑️ 刪除' },

  // --- Разрешения ---
  perms_title: { bg:'Разрешения', ru:'Разрешения', uk:'Дозволи', en:'Permissions', de:'Berechtigungen', fr:'Autorisations', es:'Permisos', 'es-MX':'Permisos', it:'Permessi', pt:'Permissões', ar:'الأذونات', hi:'अनुमतियाँ', ja:'権限', ky:'Уруксаттар', 'zh-Hant':'權限' },
  perms_sub: { bg:'Прозрачно и под твой контрол. Нищо не напуска устройството.', ru:'Прозрачно и под вашим контролем. Ничего не покидает устройство.', uk:'Прозоро і під вашим контролем. Нічого не залишає пристрій.', en:'Transparent and under your control. Nothing leaves the device.', de:'Transparent und unter deiner Kontrolle. Nichts verlässt das Gerät.', fr:'Transparent et sous ton contrôle. Rien ne quitte l’appareil.', es:'Transparente y bajo tu control. Nada sale del dispositivo.', 'es-MX':'Transparente y bajo tu control. Nada sale del dispositivo.', it:'Trasparente e sotto il tuo controllo. Nulla lascia il dispositivo.', pt:'Transparente e sob seu controle. Nada sai do dispositivo.', ar:'شفّاف وتحت سيطرتك. لا شيء يغادر الجهاز.', hi:'पारदर्शी और आपके नियंत्रण में। कुछ भी डिवाइस से बाहर नहीं जाता।', ja:'透明であなたの管理下にあります。端末から何も出ません。', ky:'Ачык жана сиздин көзөмөлүңүздө. Эч нерсе түзмөктөн чыкпайт.', 'zh-Hant':'透明且由你掌控。任何資料都不會離開裝置。' },
  perms_notif: { bg:'🔔 Известия', ru:'🔔 Уведомления', uk:'🔔 Сповіщення', en:'🔔 Notifications', de:'🔔 Benachrichtigungen', fr:'🔔 Notifications', es:'🔔 Notificaciones', 'es-MX':'🔔 Notificaciones', it:'🔔 Notifiche', pt:'🔔 Notificações', ar:'🔔 الإشعارات', hi:'🔔 नोटिफ़िकेशन', ja:'🔔 通知', ky:'🔔 Билдирүүлөр', 'zh-Hant':'🔔 通知' },
  perms_notif_desc: { bg:'За да те известява роботът по график.', ru:'Чтобы робот уведомлял вас по расписанию.', uk:'Щоб робот сповіщав вас за розкладом.', en:'So the robot can notify you on schedule.', de:'Damit der Roboter dich planmäßig benachrichtigt.', fr:'Pour que le robot te notifie selon l’horaire.', es:'Para que el robot te avise según el horario.', 'es-MX':'Para que el robot te avise según el horario.', it:'Affinché il robot ti avvisi secondo l’orario.', pt:'Para o robô avisar você no horário.', ar:'لكي ينبّهك الروبوت حسب الجدول.', hi:'ताकि रोबोट निर्धारित समय पर सूचित कर सके।', ja:'ロボットがスケジュール通りに通知できるように。', ky:'Робот сизди график боюнча кабарлашы үчүн.', 'zh-Hant':'讓機器人能依排程通知你。' },
  perms_notif_off: { bg:'изключено', ru:'выключено', uk:'вимкнено', en:'off', de:'aus', fr:'désactivé', es:'desactivado', 'es-MX':'desactivado', it:'disattivato', pt:'desligado', ar:'مُعطّل', hi:'बंद', ja:'オフ', ky:'өчүк', 'zh-Hant':'已關閉' },
  perms_notif_on: { bg:'разрешено', ru:'разрешено', uk:'дозволено', en:'allowed', de:'erlaubt', fr:'autorisé', es:'permitido', 'es-MX':'permitido', it:'consentito', pt:'permitido', ar:'مسموح', hi:'अनुमत', ja:'許可済み', ky:'уруксат берилген', 'zh-Hant':'已允許' },
  perms_notif_ask: { bg:'Разреши известия', ru:'Разрешить уведомления', uk:'Дозволити сповіщення', en:'Allow notifications', de:'Benachrichtigungen erlauben', fr:'Autoriser les notifications', es:'Permitir notificaciones', 'es-MX':'Permitir notificaciones', it:'Consenti notifiche', pt:'Permitir notificações', ar:'السماح بالإشعارات', hi:'नोटिफ़िकेशन की अनुमति दें', ja:'通知を許可', ky:'Билдирүүлөргө уруксат берүү', 'zh-Hant':'允許通知' },
  perms_loc: { bg:'📍 Локация', ru:'📍 Местоположение', uk:'📍 Місцезнаходження', en:'📍 Location', de:'📍 Standort', fr:'📍 Localisation', es:'📍 Ubicación', 'es-MX':'📍 Ubicación', it:'📍 Posizione', pt:'📍 Localização', ar:'📍 الموقع', hi:'📍 स्थान', ja:'📍 位置情報', ky:'📍 Жайгашкан жер', 'zh-Hant':'📍 位置' },
  perms_loc_desc: { bg:'САМО за времето. По избор — можеш и ръчно.', ru:'ТОЛЬКО для погоды. По желанию — можно и вручную.', uk:'ЛИШЕ для погоди. За бажанням — можна й вручну.', en:'ONLY for the weather. Optional — you can also enter it manually.', de:'NUR für das Wetter. Optional — auch manuell möglich.', fr:'UNIQUEMENT pour la météo. Facultatif — possible aussi manuellement.', es:'SOLO para el clima. Opcional — también manual.', 'es-MX':'SOLO para el clima. Opcional — también manual.', it:'SOLO per il meteo. Facoltativo — anche manuale.', pt:'APENAS para o clima. Opcional — também manual.', ar:'للطقس فقط. اختياري — يمكن إدخاله يدويًا أيضًا.', hi:'केवल मौसम के लिए। वैकल्पिक — मैन्युअल रूप से भी।', ja:'天気のためだけ。任意 — 手動入力も可能。', ky:'ТЕК аба ырайы үчүн. Тандоо боюнча — кол менен да болот.', 'zh-Hant':'僅用於天氣。可選 — 也可手動輸入。' },
  perms_loc_optional: { bg:'по избор', ru:'по желанию', uk:'за бажанням', en:'optional', de:'optional', fr:'facultatif', es:'opcional', 'es-MX':'opcional', it:'facoltativo', pt:'opcional', ar:'اختياري', hi:'वैकल्पिक', ja:'任意', ky:'тандоо боюнча', 'zh-Hant':'可選' },
  perms_loc_set: { bg:'зададена', ru:'задано', uk:'задано', en:'set', de:'gesetzt', fr:'défini', es:'definida', 'es-MX':'definida', it:'impostata', pt:'definida', ar:'محدّد', hi:'सेट', ja:'設定済み', ky:'белгиленген', 'zh-Hant':'已設定' },
  perms_use_device_loc: { bg:'Използвай локацията на устройството', ru:'Использовать местоположение устройства', uk:'Використати місцезнаходження пристрою', en:'Use the device location', de:'Gerätestandort verwenden', fr:'Utiliser la localisation de l’appareil', es:'Usar la ubicación del dispositivo', 'es-MX':'Usar la ubicación del dispositivo', it:'Usa la posizione del dispositivo', pt:'Usar a localização do dispositivo', ar:'استخدام موقع الجهاز', hi:'डिवाइस का स्थान उपयोग करें', ja:'端末の位置情報を使う', ky:'Түзмөктүн жайгашкан жерин колдонуу', 'zh-Hant':'使用裝置位置' },
  perms_or_city: { bg:'Или въведи град ръчно:', ru:'Или введите город вручную:', uk:'Або введіть місто вручну:', en:'Or enter a city manually:', de:'Oder Stadt manuell eingeben:', fr:'Ou saisis une ville manuellement :', es:'O ingresa una ciudad manualmente:', 'es-MX':'O ingresa una ciudad manualmente:', it:'Oppure inserisci una città manualmente:', pt:'Ou digite uma cidade manualmente:', ar:'أو أدخل مدينة يدويًا:', hi:'या शहर मैन्युअल रूप से दर्ज करें:', ja:'または都市を手動で入力:', ky:'Же шаарды кол менен киргизиңиз:', 'zh-Hant':'或手動輸入城市：' },
  perms_city_ph: { bg:'напр. София', ru:'напр. Москва', uk:'напр. Київ', en:'e.g. London', de:'z. B. Berlin', fr:'ex. Paris', es:'p. ej. Madrid', 'es-MX':'p. ej. Ciudad de México', it:'es. Roma', pt:'ex. Lisboa', ar:'مثال: القاهرة', hi:'जैसे दिल्ली', ja:'例: 東京', ky:'мис. Бишкек', 'zh-Hant':'例如 台北' },
  perms_find_city: { bg:'Намери по град', ru:'Найти по городу', uk:'Знайти за містом', en:'Find by city', de:'Nach Stadt suchen', fr:'Rechercher par ville', es:'Buscar por ciudad', 'es-MX':'Buscar por ciudad', it:'Cerca per città', pt:'Buscar por cidade', ar:'البحث بالمدينة', hi:'शहर से खोजें', ja:'都市で検索', ky:'Шаар боюнча табуу', 'zh-Hant':'依城市搜尋' },
  perms_or_coords: { bg:'Или точни координати:', ru:'Или точные координаты:', uk:'Або точні координати:', en:'Or exact coordinates:', de:'Oder genaue Koordinaten:', fr:'Ou coordonnées exactes :', es:'O coordenadas exactas:', 'es-MX':'O coordenadas exactas:', it:'Oppure coordinate esatte:', pt:'Ou coordenadas exatas:', ar:'أو إحداثيات دقيقة:', hi:'या सटीक निर्देशांक:', ja:'または正確な座標:', ky:'Же так координаталар:', 'zh-Hant':'或精確座標：' },
  perms_save_coords: { bg:'Запази координати', ru:'Сохранить координаты', uk:'Зберегти координати', en:'Save coordinates', de:'Koordinaten speichern', fr:'Enregistrer les coordonnées', es:'Guardar coordenadas', 'es-MX':'Guardar coordenadas', it:'Salva coordinate', pt:'Salvar coordenadas', ar:'حفظ الإحداثيات', hi:'निर्देशांक सहेजें', ja:'座標を保存', ky:'Координаталарды сактоо', 'zh-Hant':'儲存座標' },
  perms_finish_wizard: { bg:'Завърши и стартирай робота', ru:'Завершить и запустить робота', uk:'Завершити і запустити робота', en:'Finish and start the robot', de:'Fertigstellen und Roboter starten', fr:'Terminer et démarrer le robot', es:'Finalizar e iniciar el robot', 'es-MX':'Finalizar e iniciar el robot', it:'Termina e avvia il robot', pt:'Concluir e iniciar o robô', ar:'إنهاء وتشغيل الروبوت', hi:'समाप्त करें और रोबोट शुरू करें', ja:'完了してロボットを起動', ky:'Бүтүрүп, роботту иштетүү', 'zh-Hant':'完成並啟動機器人' },
  perms_waiting: { bg:'Изчаквам разрешение…', ru:'Ожидаю разрешение…', uk:'Очікую дозвіл…', en:'Waiting for permission…', de:'Warte auf Berechtigung…', fr:'En attente d’autorisation…', es:'Esperando permiso…', 'es-MX':'Esperando permiso…', it:'In attesa del permesso…', pt:'Aguardando permissão…', ar:'بانتظار الإذن…', hi:'अनुमति की प्रतीक्षा…', ja:'許可を待っています…', ky:'Уруксат күтүлүүдө…', 'zh-Hant':'等待權限中…' },
  perms_loc_denied: { bg:'Локацията е отказана — използвай ръчния вариант.', ru:'В местоположении отказано — используйте ручной вариант.', uk:'У місцезнаходженні відмовлено — скористайтеся ручним варіантом.', en:'Location denied — use the manual option.', de:'Standort verweigert — nutze die manuelle Option.', fr:'Localisation refusée — utilise l’option manuelle.', es:'Ubicación denegada — usa la opción manual.', 'es-MX':'Ubicación denegada — usa la opción manual.', it:'Posizione negata — usa l’opzione manuale.', pt:'Localização negada — use a opção manual.', ar:'رُفض الموقع — استخدم الخيار اليدوي.', hi:'स्थान अस्वीकृत — मैन्युअल विकल्प उपयोग करें।', ja:'位置情報が拒否されました — 手動オプションを使ってください。', ky:'Жайгашкан жер четке кагылды — кол менен вариантты колдонуңуз.', 'zh-Hant':'位置被拒絕 — 請使用手動選項。' },
  perms_loc_noaccess: { bg:'Няма достъп до локация — използвай ръчния вариант.', ru:'Нет доступа к местоположению — используйте ручной вариант.', uk:'Немає доступу до місцезнаходження — скористайтеся ручним варіантом.', en:'No location access — use the manual option.', de:'Kein Standortzugriff — nutze die manuelle Option.', fr:'Pas d’accès à la localisation — utilise l’option manuelle.', es:'Sin acceso a la ubicación — usa la opción manual.', 'es-MX':'Sin acceso a la ubicación — usa la opción manual.', it:'Nessun accesso alla posizione — usa l’opzione manuale.', pt:'Sem acesso à localização — use a opção manual.', ar:'لا وصول إلى الموقع — استخدم الخيار اليدوي.', hi:'स्थान तक पहुँच नहीं — मैन्युअल विकल्प उपयोग करें।', ja:'位置情報にアクセスできません — 手動オプションを使ってください。', ky:'Жайгашкан жерге мүмкүндүк жок — кол менен вариантты колдонуңуз.', 'zh-Hant':'無法存取位置 — 請使用手動選項。' },
  perms_loc_saved: { bg:'Локацията е запазена.', ru:'Местоположение сохранено.', uk:'Місцезнаходження збережено.', en:'Location saved.', de:'Standort gespeichert.', fr:'Localisation enregistrée.', es:'Ubicación guardada.', 'es-MX':'Ubicación guardada.', it:'Posizione salvata.', pt:'Localização salva.', ar:'تم حفظ الموقع.', hi:'स्थान सहेजा गया।', ja:'位置情報を保存しました。', ky:'Жайгашкан жер сакталды.', 'zh-Hant':'位置已儲存。' },
  perms_loc_fail: { bg:'Неуспех — използвай ръчния вариант (град или координати).', ru:'Неудача — используйте ручной вариант (город или координаты).', uk:'Невдача — скористайтеся ручним варіантом (місто або координати).', en:'Failed — use the manual option (city or coordinates).', de:'Fehlgeschlagen — nutze die manuelle Option (Stadt oder Koordinaten).', fr:'Échec — utilise l’option manuelle (ville ou coordonnées).', es:'Falló — usa la opción manual (ciudad o coordenadas).', 'es-MX':'Falló — usa la opción manual (ciudad o coordenadas).', it:'Non riuscito — usa l’opzione manuale (città o coordinate).', pt:'Falhou — use a opção manual (cidade ou coordenadas).', ar:'فشل — استخدم الخيار اليدوي (مدينة أو إحداثيات).', hi:'विफल — मैन्युअल विकल्प (शहर या निर्देशांक) उपयोग करें।', ja:'失敗しました — 手動オプション（都市または座標）を使ってください。', ky:'Ишке ашкан жок — кол менен вариантты колдонуңуз (шаар же координаталар).', 'zh-Hant':'失敗 — 請使用手動選項（城市或座標）。' },
  perms_searching: { bg:'Търся…', ru:'Поиск…', uk:'Пошук…', en:'Searching…', de:'Suche…', fr:'Recherche…', es:'Buscando…', 'es-MX':'Buscando…', it:'Ricerca…', pt:'Buscando…', ar:'جارٍ البحث…', hi:'खोज रहे हैं…', ja:'検索中…', ky:'Изделүүдө…', 'zh-Hant':'搜尋中…' },
  perms_error: { bg:'Грешка: {0}', ru:'Ошибка: {0}', uk:'Помилка: {0}', en:'Error: {0}', de:'Fehler: {0}', fr:'Erreur : {0}', es:'Error: {0}', 'es-MX':'Error: {0}', it:'Errore: {0}', pt:'Erro: {0}', ar:'خطأ: {0}', hi:'त्रुटि: {0}', ja:'エラー: {0}', ky:'Ката: {0}', 'zh-Hant':'錯誤：{0}' },
  perms_saved_city: { bg:'Запазено: {0}', ru:'Сохранено: {0}', uk:'Збережено: {0}', en:'Saved: {0}', de:'Gespeichert: {0}', fr:'Enregistré : {0}', es:'Guardado: {0}', 'es-MX':'Guardado: {0}', it:'Salvato: {0}', pt:'Salvo: {0}', ar:'محفوظ: {0}', hi:'सहेजा गया: {0}', ja:'保存しました: {0}', ky:'Сакталды: {0}', 'zh-Hant':'已儲存：{0}' },
  perms_bad_coords: { bg:'Невалидни координати.', ru:'Неверные координаты.', uk:'Невірні координати.', en:'Invalid coordinates.', de:'Ungültige Koordinaten.', fr:'Coordonnées invalides.', es:'Coordenadas inválidas.', 'es-MX':'Coordenadas inválidas.', it:'Coordinate non valide.', pt:'Coordenadas inválidas.', ar:'إحداثيات غير صالحة.', hi:'अमान्य निर्देशांक।', ja:'座標が無効です。', ky:'Жараксыз координаталар.', 'zh-Hant':'座標無效。' },
  perms_coords_saved: { bg:'Координатите са запазени.', ru:'Координаты сохранены.', uk:'Координати збережено.', en:'Coordinates saved.', de:'Koordinaten gespeichert.', fr:'Coordonnées enregistrées.', es:'Coordenadas guardadas.', 'es-MX':'Coordenadas guardadas.', it:'Coordinate salvate.', pt:'Coordenadas salvas.', ar:'تم حفظ الإحداثيات.', hi:'निर्देशांक सहेजे गए।', ja:'座標を保存しました。', ky:'Координаталар сакталды.', 'zh-Hant':'座標已儲存。' },
  loc_current: { bg:'Текуща локация', ru:'Текущее местоположение', uk:'Поточне місцезнаходження', en:'Current location', de:'Aktueller Standort', fr:'Localisation actuelle', es:'Ubicación actual', 'es-MX':'Ubicación actual', it:'Posizione attuale', pt:'Localização atual', ar:'الموقع الحالي', hi:'वर्तमान स्थान', ja:'現在地', ky:'Учурдагы жайгашкан жер', 'zh-Hant':'目前位置' },
  loc_manual: { bg:'Ръчни координати', ru:'Ручные координаты', uk:'Ручні координати', en:'Manual coordinates', de:'Manuelle Koordinaten', fr:'Coordonnées manuelles', es:'Coordenadas manuales', 'es-MX':'Coordenadas manuales', it:'Coordinate manuali', pt:'Coordenadas manuais', ar:'إحداثيات يدوية', hi:'मैन्युअल निर्देशांक', ja:'手動座標', ky:'Кол менен координаталар', 'zh-Hant':'手動座標' },

  // --- Грешки от мрежата/времето (от weather-api) ---
  err_empty_city: { bg:'Празно име на град', ru:'Пустое название города', uk:'Порожня назва міста', en:'Empty city name', de:'Leerer Städtename', fr:'Nom de ville vide', es:'Nombre de ciudad vacío', 'es-MX':'Nombre de ciudad vacío', it:'Nome città vuoto', pt:'Nome da cidade vazio', ar:'اسم المدينة فارغ', hi:'शहर का नाम खाली', ja:'都市名が空です', ky:'Шаардын аты бош', 'zh-Hant':'城市名稱為空' },
  err_city_notfound: { bg:'Градът не е намерен', ru:'Город не найден', uk:'Місто не знайдено', en:'City not found', de:'Stadt nicht gefunden', fr:'Ville introuvable', es:'Ciudad no encontrada', 'es-MX':'Ciudad no encontrada', it:'Città non trovata', pt:'Cidade não encontrada', ar:'المدينة غير موجودة', hi:'शहर नहीं मिला', ja:'都市が見つかりません', ky:'Шаар табылган жок', 'zh-Hant':'找不到城市' },
  err_no_network: { bg:'Няма връзка с мрежата', ru:'Нет связи с сетью', uk:'Немає зв’язку з мережею', en:'No network connection', de:'Keine Netzwerkverbindung', fr:'Pas de connexion réseau', es:'Sin conexión de red', 'es-MX':'Sin conexión de red', it:'Nessuna connessione di rete', pt:'Sem conexão de rede', ar:'لا اتصال بالشبكة', hi:'नेटवर्क कनेक्शन नहीं', ja:'ネットワーク接続がありません', ky:'Тармак байланышы жок', 'zh-Hant':'無網路連線' },
  err_no_coords: { bg:'Липсват координати', ru:'Отсутствуют координаты', uk:'Відсутні координати', en:'Coordinates missing', de:'Koordinaten fehlen', fr:'Coordonnées manquantes', es:'Faltan coordenadas', 'es-MX':'Faltan coordenadas', it:'Coordinate mancanti', pt:'Coordenadas ausentes', ar:'الإحداثيات مفقودة', hi:'निर्देशांक गायब', ja:'座標がありません', ky:'Координаталар жок', 'zh-Hant':'缺少座標' },

  // --- Брифинг (тялото на известието) ---
  brief_weather_nolink: { bg:'🌡️ Времето: няма връзка', ru:'🌡️ Погода: нет связи', uk:'🌡️ Погода: немає зв’язку', en:'🌡️ Weather: no connection', de:'🌡️ Wetter: keine Verbindung', fr:'🌡️ Météo : pas de connexion', es:'🌡️ Clima: sin conexión', 'es-MX':'🌡️ Clima: sin conexión', it:'🌡️ Meteo: nessuna connessione', pt:'🌡️ Clima: sem conexão', ar:'🌡️ الطقس: لا اتصال', hi:'🌡️ मौसम: कनेक्शन नहीं', ja:'🌡️ 天気：接続なし', ky:'🌡️ Аба ырайы: байланыш жок', 'zh-Hant':'🌡️ 天氣：無連線' },
  brief_weather_setloc: { bg:'🌡️ Времето: задай локация в настройките', ru:'🌡️ Погода: задайте местоположение в настройках', uk:'🌡️ Погода: задайте місцезнаходження в налаштуваннях', en:'🌡️ Weather: set a location in settings', de:'🌡️ Wetter: Standort in den Einstellungen festlegen', fr:'🌡️ Météo : définis une localisation dans les réglages', es:'🌡️ Clima: define una ubicación en ajustes', 'es-MX':'🌡️ Clima: define una ubicación en ajustes', it:'🌡️ Meteo: imposta una posizione nelle impostazioni', pt:'🌡️ Clima: defina uma localização nas configurações', ar:'🌡️ الطقس: حدّد موقعًا في الإعدادات', hi:'🌡️ मौसम: सेटिंग्स में स्थान सेट करें', ja:'🌡️ 天気：設定で位置を指定してください', ky:'🌡️ Аба ырайы: жөндөөлөрдөн жайгашкан жерди белгилеңиз', 'zh-Hant':'🌡️ 天氣：請在設定中設定位置' },
  brief_weather_line: { bg:'{0} {1}, {2}{3} (макс {4}/мин {5})', ru:'{0} {1}, {2}{3} (макс {4}/мин {5})', uk:'{0} {1}, {2}{3} (макс {4}/мін {5})', en:'{0} {1}, {2}{3} (max {4}/min {5})', de:'{0} {1}, {2}{3} (max. {4}/min. {5})', fr:'{0} {1}, {2}{3} (max {4}/min {5})', es:'{0} {1}, {2}{3} (máx {4}/mín {5})', 'es-MX':'{0} {1}, {2}{3} (máx {4}/mín {5})', it:'{0} {1}, {2}{3} (max {4}/min {5})', pt:'{0} {1}, {2}{3} (máx {4}/mín {5})', ar:'{0} {1}، {2}{3} (الأقصى {4}/الأدنى {5})', hi:'{0} {1}, {2}{3} (अधि {4}/न्यून {5})', ja:'{0} {1}、{2}{3}（最高 {4}/最低 {5}）', ky:'{0} {1}, {2}{3} (макс {4}/мин {5})', 'zh-Hant':'{0} {1}，{2}{3}（最高 {4}/最低 {5}）' },
  brief_agenda_today: { bg:'📋 Днес: {0}', ru:'📋 Сегодня: {0}', uk:'📋 Сьогодні: {0}', en:'📋 Today: {0}', de:'📋 Heute: {0}', fr:'📋 Aujourd’hui : {0}', es:'📋 Hoy: {0}', 'es-MX':'📋 Hoy: {0}', it:'📋 Oggi: {0}', pt:'📋 Hoje: {0}', ar:'📋 اليوم: {0}', hi:'📋 आज: {0}', ja:'📋 今日: {0}', ky:'📋 Бүгүн: {0}', 'zh-Hant':'📋 今天：{0}' },
  brief_agenda_none: { bg:'📋 Днес: няма събития', ru:'📋 Сегодня: нет событий', uk:'📋 Сьогодні: немає подій', en:'📋 Today: no events', de:'📋 Heute: keine Ereignisse', fr:'📋 Aujourd’hui : aucun événement', es:'📋 Hoy: sin eventos', 'es-MX':'📋 Hoy: sin eventos', it:'📋 Oggi: nessun evento', pt:'📋 Hoje: sem eventos', ar:'📋 اليوم: لا أحداث', hi:'📋 आज: कोई इवेंट नहीं', ja:'📋 今日: 予定なし', ky:'📋 Бүгүн: окуялар жок', 'zh-Hant':'📋 今天：沒有事件' },
  brief_default: { bg:'Добро утро! Рутината е активна.', ru:'Доброе утро! Рутина активна.', uk:'Доброго ранку! Рутина активна.', en:'Good morning! The routine is active.', de:'Guten Morgen! Die Routine ist aktiv.', fr:'Bonjour ! La routine est active.', es:'¡Buenos días! La rutina está activa.', 'es-MX':'¡Buenos días! La rutina está activa.', it:'Buongiorno! La routine è attiva.', pt:'Bom dia! A rotina está ativa.', ar:'صباح الخير! الروتين نشط.', hi:'सुप्रभात! दिनचर्या सक्रिय है।', ja:'おはようございます！ルーティンが有効です。', ky:'Кайырлуу таң! Тартип иштеп жатат.', 'zh-Hant':'早安！例程已啟用。' },
  notif_morning_title: { bg:'🤖 Сутрешен брифинг', ru:'🤖 Утренний брифинг', uk:'🤖 Ранковий брифінг', en:'🤖 Morning briefing', de:'🤖 Morgen-Briefing', fr:'🤖 Briefing du matin', es:'🤖 Resumen matutino', 'es-MX':'🤖 Resumen matutino', it:'🤖 Briefing mattutino', pt:'🤖 Resumo matinal', ar:'🤖 موجز صباحي', hi:'🤖 सुबह की ब्रीफिंग', ja:'🤖 朝のブリーフィング', ky:'🤖 Эртеңки брифинг', 'zh-Hant':'🤖 早晨簡報' },
  notif_morning_body: { bg:'Вашата рутина е готова. Отворете за подробности.', ru:'Ваша рутина готова. Откройте для подробностей.', uk:'Ваша рутина готова. Відкрийте для подробиць.', en:'Your routine is ready. Open for details.', de:'Deine Routine ist bereit. Zum Anzeigen öffnen.', fr:'Ta routine est prête. Ouvre pour les détails.', es:'Tu rutina está lista. Abre para ver detalles.', 'es-MX':'Tu rutina está lista. Abre para ver detalles.', it:'La tua routine è pronta. Apri per i dettagli.', pt:'Sua rotina está pronta. Abra para detalhes.', ar:'روتينك جاهز. افتح للتفاصيل.', hi:'आपकी दिनचर्या तैयार है। विवरण के लिए खोलें।', ja:'ルーティンの準備ができました。詳細を開いてください。', ky:'Тартибиңиз даяр. Чоо-жайын ачыңыз.', 'zh-Hant':'你的例程已就緒。開啟查看詳情。' },
  notif_evening_title: { bg:'🌙 Вечерно резюме', ru:'🌙 Вечерняя сводка', uk:'🌙 Вечірнє зведення', en:'🌙 Evening summary', de:'🌙 Abendzusammenfassung', fr:'🌙 Résumé du soir', es:'🌙 Resumen nocturno', 'es-MX':'🌙 Resumen nocturno', it:'🌙 Riepilogo serale', pt:'🌙 Resumo noturno', ar:'🌙 ملخص مسائي', hi:'🌙 शाम का सारांश', ja:'🌙 夜のまとめ', ky:'🌙 Кечки корутунду', 'zh-Hant':'🌙 晚間總結' },
  notif_evening_body: { bg:'Прегледай деня и планирай утрешния.', ru:'Просмотрите день и спланируйте завтрашний.', uk:'Перегляньте день і сплануйте завтрашній.', en:'Review the day and plan tomorrow.', de:'Sieh dir den Tag an und plane morgen.', fr:'Passe en revue la journée et planifie demain.', es:'Repasa el día y planifica mañana.', 'es-MX':'Repasa el día y planifica mañana.', it:'Rivedi la giornata e pianifica domani.', pt:'Revise o dia e planeje o amanhã.', ar:'راجع يومك وخطّط للغد.', hi:'दिन की समीक्षा करें और कल की योजना बनाएं।', ja:'1日を振り返り、明日を計画しましょう。', ky:'Күндү карап чыгып, эртеңкини пландаштырыңыз.', 'zh-Hant':'回顧今天並規劃明天。' },
  notif_reminder_default: { bg:'Напомняне', ru:'Напоминание', uk:'Нагадування', en:'Reminder', de:'Erinnerung', fr:'Rappel', es:'Recordatorio', 'es-MX':'Recordatorio', it:'Promemoria', pt:'Lembrete', ar:'تذكير', hi:'रिमाइंडर', ja:'リマインダー', ky:'Эскертүү', 'zh-Hant':'提醒' },
  notif_reminder_body: { bg:'Време е!', ru:'Пора!', uk:'Час настав!', en:'It’s time!', de:'Es ist Zeit!', fr:'C’est l’heure !', es:'¡Es la hora!', 'es-MX':'¡Es la hora!', it:'È ora!', pt:'Está na hora!', ar:'حان الوقت!', hi:'समय हो गया!', ja:'時間です！', ky:'Убакыт болду!', 'zh-Hant':'時間到了！' },
  notif_preview_title: { bg:'🤖 Преглед: Сутрешен брифинг', ru:'🤖 Предпросмотр: Утренний брифинг', uk:'🤖 Перегляд: Ранковий брифінг', en:'🤖 Preview: Morning briefing', de:'🤖 Vorschau: Morgen-Briefing', fr:'🤖 Aperçu : Briefing du matin', es:'🤖 Vista previa: Resumen matutino', 'es-MX':'🤖 Vista previa: Resumen matutino', it:'🤖 Anteprima: Briefing mattutino', pt:'🤖 Prévia: Resumo matinal', ar:'🤖 معاينة: موجز صباحي', hi:'🤖 पूर्वावलोकन: सुबह की ब्रीफिंग', ja:'🤖 プレビュー：朝のブリーフィング', ky:'🤖 Көрүү: Эртеңки брифинг', 'zh-Hant':'🤖 預覽：早晨簡報' },

  // --- Стартова грешка ---
  boot_title: { bg:'Робот за рутини', ru:'Робот для рутин', uk:'Робот для рутин', en:'Routine robot', de:'Routine-Roboter', fr:'Robot de routine', es:'Robot de rutinas', 'es-MX':'Robot de rutinas', it:'Robot delle routine', pt:'Robô de rotinas', ar:'روبوت الروتين', hi:'दिनचर्या रोबोट', ja:'ルーティンロボット', ky:'Тартип роботу', 'zh-Hant':'例程機器人' },
  boot_error: { bg:'Стартова грешка: {0}', ru:'Ошибка запуска: {0}', uk:'Помилка запуску: {0}', en:'Startup error: {0}', de:'Startfehler: {0}', fr:'Erreur de démarrage : {0}', es:'Error de inicio: {0}', 'es-MX':'Error de inicio: {0}', it:'Errore di avvio: {0}', pt:'Erro de inicialização: {0}', ar:'خطأ في البدء: {0}', hi:'स्टार्टअप त्रुटि: {0}', ja:'起動エラー: {0}', ky:'Иштетүү катасы: {0}', 'zh-Hant':'啟動錯誤：{0}' },
  boot_unknown: { bg:'неизвестна', ru:'неизвестно', uk:'невідомо', en:'unknown', de:'unbekannt', fr:'inconnue', es:'desconocido', 'es-MX':'desconocido', it:'sconosciuto', pt:'desconhecido', ar:'غير معروف', hi:'अज्ञात', ja:'不明', ky:'белгисиз', 'zh-Hant':'未知' },

  // --- Дневник на активността (текст на записите) ---
  log_web_notif: { bg:'Известие (уеб): {0}', ru:'Уведомление (веб): {0}', uk:'Сповіщення (веб): {0}', en:'Notification (web): {0}', de:'Benachrichtigung (Web): {0}', fr:'Notification (web) : {0}', es:'Notificación (web): {0}', 'es-MX':'Notificación (web): {0}', it:'Notifica (web): {0}', pt:'Notificação (web): {0}', ar:'إشعار (ويب): {0}', hi:'नोटिफ़िकेशन (वेब): {0}', ja:'通知（ウェブ）: {0}', ky:'Билдирүү (веб): {0}', 'zh-Hant':'通知（網頁）：{0}' },
  log_rescheduled: { bg:'Графикът е презареден: {0} елемента', ru:'Расписание перезагружено: элементов — {0}', uk:'Розклад перезавантажено: елементів — {0}', en:'Schedule reloaded: {0} items', de:'Zeitplan neu geladen: {0} Einträge', fr:'Planning rechargé : {0} éléments', es:'Programación recargada: {0} elementos', 'es-MX':'Programación recargada: {0} elementos', it:'Pianificazione ricaricata: {0} elementi', pt:'Agenda recarregada: {0} itens', ar:'أُعيد تحميل الجدول: {0} عنصرًا', hi:'शेड्यूल पुनः लोड: {0} आइटम', ja:'スケジュールを再読み込み: {0} 件', ky:'График кайра жүктөлдү: {0} элемент', 'zh-Hant':'排程已重新載入：{0} 個項目' },
  log_preview: { bg:'Преглед на брифинга', ru:'Предпросмотр брифинга', uk:'Перегляд брифінгу', en:'Briefing preview', de:'Briefing-Vorschau', fr:'Aperçu du briefing', es:'Vista previa del resumen', 'es-MX':'Vista previa del resumen', it:'Anteprima del briefing', pt:'Prévia do resumo', ar:'معاينة الموجز', hi:'ब्रीफिंग पूर्वावलोकन', ja:'ブリーフィングのプレビュー', ky:'Брифингди көрүү', 'zh-Hant':'簡報預覽' },

  // --- Описания на времето (WMO кодове) ---
  weather_unknown: { bg:'Неизвестно', ru:'Неизвестно', uk:'Невідомо', en:'Unknown', de:'Unbekannt', fr:'Inconnu', es:'Desconocido', 'es-MX':'Desconocido', it:'Sconosciuto', pt:'Desconhecido', ar:'غير معروف', hi:'अज्ञात', ja:'不明', ky:'Белгисиз', 'zh-Hant':'未知' },
  wmo_clear: { bg:'Ясно', ru:'Ясно', uk:'Ясно', en:'Clear', de:'Klar', fr:'Ciel clair', es:'Despejado', 'es-MX':'Despejado', it:'Sereno', pt:'Céu limpo', ar:'صافٍ', hi:'साफ़', ja:'快晴', ky:'Ачык', 'zh-Hant':'晴朗' },
  wmo_mainly_clear: { bg:'Предимно ясно', ru:'Преимущественно ясно', uk:'Переважно ясно', en:'Mainly clear', de:'Überwiegend klar', fr:'Plutôt clair', es:'Mayormente despejado', 'es-MX':'Mayormente despejado', it:'Prevalentemente sereno', pt:'Predominantemente limpo', ar:'صافٍ غالبًا', hi:'अधिकतर साफ़', ja:'おおむね晴れ', ky:'Негизинен ачык', 'zh-Hant':'大致晴朗' },
  wmo_partly_cloudy: { bg:'Променлива облачност', ru:'Переменная облачность', uk:'Мінлива хмарність', en:'Partly cloudy', de:'Teils bewölkt', fr:'Partiellement nuageux', es:'Parcialmente nublado', 'es-MX':'Parcialmente nublado', it:'Parzialmente nuvoloso', pt:'Parcialmente nublado', ar:'غائم جزئيًا', hi:'आंशिक रूप से बादल', ja:'晴れ時々曇り', ky:'Аздан булуттуу', 'zh-Hant':'局部多雲' },
  wmo_overcast: { bg:'Облачно', ru:'Пасмурно', uk:'Хмарно', en:'Overcast', de:'Bedeckt', fr:'Couvert', es:'Nublado', 'es-MX':'Nublado', it:'Coperto', pt:'Nublado', ar:'غائم', hi:'बादल', ja:'曇り', ky:'Булуттуу', 'zh-Hant':'陰天' },
  wmo_fog: { bg:'Мъгла', ru:'Туман', uk:'Туман', en:'Fog', de:'Nebel', fr:'Brouillard', es:'Niebla', 'es-MX':'Niebla', it:'Nebbia', pt:'Nevoeiro', ar:'ضباب', hi:'कोहरा', ja:'霧', ky:'Туман', 'zh-Hant':'霧' },
  wmo_rime_fog: { bg:'Скреж/мъгла', ru:'Изморозь/туман', uk:'Паморозь/туман', en:'Rime fog', de:'Reifnebel', fr:'Brouillard givrant', es:'Niebla con escarcha', 'es-MX':'Niebla con escarcha', it:'Nebbia con brina', pt:'Nevoeiro com geada', ar:'ضباب جليدي', hi:'तुषार कोहरा', ja:'霧氷の霧', ky:'Кыроо/туман', 'zh-Hant':'霧凇' },
  wmo_light_drizzle: { bg:'Слаб ръмеж', ru:'Слабая морось', uk:'Слабка мряка', en:'Light drizzle', de:'Leichter Nieselregen', fr:'Bruine légère', es:'Llovizna ligera', 'es-MX':'Llovizna ligera', it:'Pioviggine leggera', pt:'Garoa fraca', ar:'رذاذ خفيف', hi:'हल्की बूंदाबांदी', ja:'弱い霧雨', ky:'Жеңил жамгыр', 'zh-Hant':'小毛毛雨' },
  wmo_drizzle: { bg:'Ръмеж', ru:'Морось', uk:'Мряка', en:'Drizzle', de:'Nieselregen', fr:'Bruine', es:'Llovizna', 'es-MX':'Llovizna', it:'Pioviggine', pt:'Garoa', ar:'رذاذ', hi:'बूंदाबांदी', ja:'霧雨', ky:'Жамгыр', 'zh-Hant':'毛毛雨' },
  wmo_heavy_drizzle: { bg:'Силен ръмеж', ru:'Сильная морось', uk:'Сильна мряка', en:'Heavy drizzle', de:'Starker Nieselregen', fr:'Bruine forte', es:'Llovizna intensa', 'es-MX':'Llovizna intensa', it:'Pioviggine intensa', pt:'Garoa forte', ar:'رذاذ غزير', hi:'तेज़ बूंदाबांदी', ja:'強い霧雨', ky:'Күчтүү жамгыр', 'zh-Hant':'大毛毛雨' },
  wmo_light_rain: { bg:'Слаб дъжд', ru:'Слабый дождь', uk:'Слабкий дощ', en:'Light rain', de:'Leichter Regen', fr:'Pluie légère', es:'Lluvia ligera', 'es-MX':'Lluvia ligera', it:'Pioggia leggera', pt:'Chuva fraca', ar:'مطر خفيف', hi:'हल्की बारिश', ja:'弱い雨', ky:'Жеңил жаан', 'zh-Hant':'小雨' },
  wmo_rain: { bg:'Дъжд', ru:'Дождь', uk:'Дощ', en:'Rain', de:'Regen', fr:'Pluie', es:'Lluvia', 'es-MX':'Lluvia', it:'Pioggia', pt:'Chuva', ar:'مطر', hi:'बारिश', ja:'雨', ky:'Жаан', 'zh-Hant':'雨' },
  wmo_heavy_rain: { bg:'Силен дъжд', ru:'Сильный дождь', uk:'Сильний дощ', en:'Heavy rain', de:'Starker Regen', fr:'Pluie forte', es:'Lluvia intensa', 'es-MX':'Lluvia intensa', it:'Pioggia intensa', pt:'Chuva forte', ar:'مطر غزير', hi:'भारी बारिश', ja:'強い雨', ky:'Күчтүү жаан', 'zh-Hant':'大雨' },
  wmo_light_snow: { bg:'Слаб сняг', ru:'Слабый снег', uk:'Слабкий сніг', en:'Light snow', de:'Leichter Schnee', fr:'Neige légère', es:'Nieve ligera', 'es-MX':'Nieve ligera', it:'Neve leggera', pt:'Neve fraca', ar:'ثلج خفيف', hi:'हल्की बर्फ़', ja:'弱い雪', ky:'Жеңил кар', 'zh-Hant':'小雪' },
  wmo_snow: { bg:'Сняг', ru:'Снег', uk:'Сніг', en:'Snow', de:'Schnee', fr:'Neige', es:'Nieve', 'es-MX':'Nieve', it:'Neve', pt:'Neve', ar:'ثلج', hi:'बर्फ़', ja:'雪', ky:'Кар', 'zh-Hant':'雪' },
  wmo_heavy_snow: { bg:'Силен сняг', ru:'Сильный снег', uk:'Сильний сніг', en:'Heavy snow', de:'Starker Schnee', fr:'Neige forte', es:'Nieve intensa', 'es-MX':'Nieve intensa', it:'Neve intensa', pt:'Neve forte', ar:'ثلج كثيف', hi:'भारी बर्फ़', ja:'強い雪', ky:'Күчтүү кар', 'zh-Hant':'大雪' },
  wmo_snow_grains: { bg:'Снежни зърна', ru:'Снежные зёрна', uk:'Снігова крупа', en:'Snow grains', de:'Schneegriesel', fr:'Grains de neige', es:'Granos de nieve', 'es-MX':'Granos de nieve', it:'Granuli di neve', pt:'Grãos de neve', ar:'حبيبات ثلجية', hi:'बर्फ़ के कण', ja:'霧雪', ky:'Кар данчалары', 'zh-Hant':'雪粒' },
  wmo_showers: { bg:'Превалявания', ru:'Ливни', uk:'Зливи', en:'Showers', de:'Schauer', fr:'Averses', es:'Chubascos', 'es-MX':'Chubascos', it:'Rovesci', pt:'Pancadas de chuva', ar:'زخّات', hi:'बौछारें', ja:'にわか雨', ky:'Нөшөр', 'zh-Hant':'陣雨' },
  wmo_heavy_showers: { bg:'Силни превалявания', ru:'Сильные ливни', uk:'Сильні зливи', en:'Heavy showers', de:'Starke Schauer', fr:'Averses fortes', es:'Chubascos intensos', 'es-MX':'Chubascos intensos', it:'Rovesci intensi', pt:'Pancadas fortes', ar:'زخّات غزيرة', hi:'तेज़ बौछारें', ja:'激しいにわか雨', ky:'Күчтүү нөшөр', 'zh-Hant':'強陣雨' },
  wmo_snow_showers: { bg:'Снежни превалявания', ru:'Снежные ливни', uk:'Снігові зливи', en:'Snow showers', de:'Schneeschauer', fr:'Averses de neige', es:'Chubascos de nieve', 'es-MX':'Chubascos de nieve', it:'Rovesci di neve', pt:'Pancadas de neve', ar:'زخّات ثلجية', hi:'बर्फ़ की बौछारें', ja:'にわか雪', ky:'Кар нөшөрү', 'zh-Hant':'陣雪' },
  wmo_thunderstorm: { bg:'Гръмотевична буря', ru:'Гроза', uk:'Гроза', en:'Thunderstorm', de:'Gewitter', fr:'Orage', es:'Tormenta', 'es-MX':'Tormenta', it:'Temporale', pt:'Trovoada', ar:'عاصفة رعدية', hi:'आंधी-तूफ़ान', ja:'雷雨', ky:'Чагылган', 'zh-Hant':'雷暴' },
  wmo_thunderstorm_hail: { bg:'Буря с градушка', ru:'Гроза с градом', uk:'Гроза з градом', en:'Thunderstorm with hail', de:'Gewitter mit Hagel', fr:'Orage avec grêle', es:'Tormenta con granizo', 'es-MX':'Tormenta con granizo', it:'Temporale con grandine', pt:'Trovoada com granizo', ar:'عاصفة رعدية مع برَد', hi:'ओलों के साथ आंधी', ja:'雹を伴う雷雨', ky:'Мөндүрлүү чагылган', 'zh-Hant':'雷暴伴冰雹' },
  wmo_thunderstorm_heavy_hail: { bg:'Силна буря с градушка', ru:'Сильная гроза с градом', uk:'Сильна гроза з градом', en:'Heavy thunderstorm with hail', de:'Starkes Gewitter mit Hagel', fr:'Orage violent avec grêle', es:'Tormenta fuerte con granizo', 'es-MX':'Tormenta fuerte con granizo', it:'Forte temporale con grandine', pt:'Trovoada forte com granizo', ar:'عاصفة رعدية قوية مع برَد', hi:'ओलों के साथ तेज़ आंधी', ja:'雹を伴う激しい雷雨', ky:'Мөндүрлүү күчтүү чагылган', 'zh-Hant':'強雷暴伴冰雹' }
};

let current = detect();

function detect() {
  try {
    const saved = localStorage.getItem(LS_KEY);
    if (saved && STR.save[saved] != null) return saved;
  } catch (e) {}
  return DEFAULT_LANG;
}

// Дали потребителят вече е избирал ЕЗИК НА ИНТЕРФЕЙСА (за да решим дали да показваме екрана).
export function hasLangChosen() {
  try { return !!localStorage.getItem(LS_KEY); } catch (e) { return false; }
}

export function getLang() { return current; }

export function setLang(code) {
  if (STR.save[code] == null) return;     // непознат код — игнорирай
  current = code;
  try { localStorage.setItem(LS_KEY, code); } catch (e) {}
  applyDir();
}

export function isRTL() { return RTL_CODES.indexOf(current) > -1; }

// Прилага посоката (rtl/ltr) и lang атрибута върху <html>.
export function applyDir() {
  try {
    document.documentElement.setAttribute('dir', isRTL() ? 'rtl' : 'ltr');
    document.documentElement.setAttribute('lang', current);
  } catch (e) {}
}

// Превод по ключ. Резервна верига: текущ → руски → английски → самия ключ.
export function t(key) {
  const row = STR[key];
  if (!row) return key;
  if (row[current] != null) return row[current];
  if (row[DEFAULT_LANG] != null) return row[DEFAULT_LANG];
  if (row[FALLBACK_LANG] != null) return row[FALLBACK_LANG];
  return key;
}

// Превод с вмъкване на стойности на местата {0}, {1}, ...
export function tf(key, ...vals) {
  let s = t(key);
  vals.forEach((v, i) => { s = s.replace(new RegExp('\\{' + i + '\\}', 'g'), String(v)); });
  return s;
}

export { LANGUAGES, languageByCode };
