// Version: 1.0021
// i18n.js — преводен слой за Pupikes Toolkit на 15-те езика. Дефолт руски.
import { LANGUAGES } from './languages.js';

const LS_KEY = 'servicestoolkit.lang';
const DEFAULT_LANG = 'ru';
const FALLBACK_LANG = 'en';
const RTL = ['ar'];

const STR = {
  pick_lang: { bg:'Избери език', ru:'Выберите язык', uk:'Виберіть мову', en:'Choose language', de:'Sprache wählen', fr:'Choisir la langue', es:'Elegir idioma', 'es-MX':'Elegir idioma', it:'Scegli la lingua', pt:'Escolher idioma', ar:'اختر اللغة', hi:'भाषा चुनें', ja:'言語を選択', ky:'Тилди тандаңыз', 'zh-Hant':'選擇語言' },
  lang_btn: { bg:'🌐 Език', ru:'🌐 Язык', uk:'🌐 Мова', en:'🌐 Language', de:'🌐 Sprache', fr:'🌐 Langue', es:'🌐 Idioma', 'es-MX':'🌐 Idioma', it:'🌐 Lingua', pt:'🌐 Idioma', ar:'🌐 اللغة', hi:'🌐 भाषा', ja:'🌐 言語', ky:'🌐 Тил', 'zh-Hant':'🌐 語言' },
  start_app: { bg:'Стартирай', ru:'Запустить', uk:'Запустити', en:'Start', de:'Starten', fr:'Démarrer', es:'Iniciar', 'es-MX':'Iniciar', it:'Avvia', pt:'Iniciar', ar:'ابدأ', hi:'शुरू करें', ja:'開始', ky:'Баштоо', 'zh-Hant':'開始' },
  home_sub: { bg:'Цялото семейство Pupikes Toolkit в едно приложение: 55 инструмента в 10 раздела — всичко на устройството.', ru:'Всё семейство Pupikes Toolkit в одном приложении: 55 инструментов в 10 разделах — всё на устройстве.', uk:'Уся родина Pupikes Toolkit в одному застосунку: 55 інструментів у 10 розділах — усе на пристрої.', en:'The whole Pupikes Toolkit family in one app: 55 tools in 10 sections — everything on your device.', de:'Die ganze Pupikes-Toolkit-Familie in einer App: 55 Werkzeuge in 10 Bereichen – alles auf dem Gerät.', fr:'Toute la famille Pupikes Toolkit dans une seule appli : 55 outils en 10 sections – tout sur l’appareil.', es:'Toda la familia Pupikes Toolkit en una sola app: 55 herramientas en 10 secciones — todo en tu dispositivo.', 'es-MX':'Toda la familia Pupikes Toolkit en una sola app: 55 herramientas en 10 secciones — todo en tu dispositivo.', it:'Tutta la famiglia Pupikes Toolkit in un’unica app: 55 strumenti in 10 sezioni — tutto sul dispositivo.', pt:'Toda a família Pupikes Toolkit numa só app: 55 ferramentas em 10 secções — tudo no dispositivo.', ar:'عائلة Pupikes Toolkit كاملة في تطبيق واحد: 55 أداة في 10 أقسام — كل شيء على جهازك.', hi:'पूरा Pupikes Toolkit परिवार एक ऐप में: 10 खंडों में 55 टूल — सब कुछ आपके डिवाइस पर।', ja:'Pupikes Toolkit ファミリーをひとつのアプリに：10セクション・55ツール、すべて端末内で動作。', ky:'Бүт Pupikes Toolkit үй-бүлөсү бир колдонмодо: 10 бөлүмдө 55 курал — баары түзмөктө.', 'zh-Hant':'整個 Pupikes Toolkit 系列集於一個應用程式：10 個分區、55 個工具——全部在裝置上運作。' },
  search_ph: { bg:'Търси инструмент…', ru:'Поиск инструмента…', uk:'Пошук інструмента…', en:'Search a tool…', de:'Werkzeug suchen…', fr:'Rechercher un outil…', es:'Buscar herramienta…', 'es-MX':'Buscar herramienta…', it:'Cerca uno strumento…', pt:'Buscar ferramenta…', ar:'ابحث عن أداة…', hi:'टूल खोजें…', ja:'ツールを検索…', ky:'Куралды издөө…', 'zh-Hant':'搜尋工具…' },
  no_matches: { bg:'Няма съвпадения.', ru:'Совпадений нет.', uk:'Збігів немає.', en:'No matches.', de:'Keine Treffer.', fr:'Aucun résultat.', es:'Sin coincidencias.', 'es-MX':'Sin coincidencias.', it:'Nessuna corrispondenza.', pt:'Sem correspondências.', ar:'لا نتائج.', hi:'कोई मिलान नहीं।', ja:'一致なし。', ky:'Дал келүү жок.', 'zh-Hant':'沒有相符項目。' },
  online_tag: { bg:'онлайн', ru:'онлайн', uk:'онлайн', en:'online', de:'online', fr:'en ligne', es:'en línea', 'es-MX':'en línea', it:'online', pt:'online', ar:'متصل', hi:'ऑनलाइन', ja:'オンライン', ky:'онлайн', 'zh-Hant':'線上' },
  back: { bg:'Назад', ru:'Назад', uk:'Назад', en:'Back', de:'Zurück', fr:'Retour', es:'Atrás', 'es-MX':'Atrás', it:'Indietro', pt:'Voltar', ar:'رجوع', hi:'वापस', ja:'戻る', ky:'Артка', 'zh-Hant':'返回' },
  loading: { bg:'Зареждам…', ru:'Загрузка…', uk:'Завантаження…', en:'Loading…', de:'Laden…', fr:'Chargement…', es:'Cargando…', 'es-MX':'Cargando…', it:'Caricamento…', pt:'Carregando…', ar:'جارٍ التحميل…', hi:'लोड हो रहा…', ja:'読み込み中…', ky:'Жүктөлүүдө…', 'zh-Hant':'載入中…' },
  load_error: { bg:'Грешка при зареждане на инструмента:', ru:'Ошибка загрузки инструмента:', uk:'Помилка завантаження інструмента:', en:'Error loading the tool:', de:'Fehler beim Laden des Werkzeugs:', fr:'Erreur de chargement de l’outil :', es:'Error al cargar la herramienta:', 'es-MX':'Error al cargar la herramienta:', it:'Errore nel caricamento dello strumento:', pt:'Erro ao carregar a ferramenta:', ar:'خطأ في تحميل الأداة:', hi:'टूल लोड करने में त्रुटि:', ja:'ツールの読み込みエラー:', ky:'Куралды жүктөөдө ката:', 'zh-Hant':'載入工具時發生錯誤：' },
  t_qr_name: { bg:'QR код', ru:'QR-код', uk:'QR-код', en:'QR code', de:'QR-Code', fr:'Code QR', es:'Código QR', 'es-MX':'Código QR', it:'Codice QR', pt:'Código QR', ar:'رمز QR', hi:'QR कोड', ja:'QRコード', ky:'QR код', 'zh-Hant':'QR 碼' },
  t_qr_desc: { bg:'Генерирай и разчети QR кодове', ru:'Создавай и сканируй QR-коды', uk:'Створюй і скануй QR-коди', en:'Generate and read QR codes', de:'QR-Codes erstellen und lesen', fr:'Générer et lire des codes QR', es:'Genera y lee códigos QR', 'es-MX':'Genera y lee códigos QR', it:'Genera e leggi codici QR', pt:'Gere e leia códigos QR', ar:'أنشئ واقرأ رموز QR', hi:'QR कोड बनाएं और पढ़ें', ja:'QRコードの生成と読み取り', ky:'QR коддорду түзүү жана окуу', 'zh-Hant':'產生與讀取 QR 碼' },
  t_password_name: { bg:'Генератор на пароли', ru:'Генератор паролей', uk:'Генератор паролів', en:'Password generator', de:'Passwortgenerator', fr:'Générateur de mots de passe', es:'Generador de contraseñas', 'es-MX':'Generador de contraseñas', it:'Generatore di password', pt:'Gerador de senhas', ar:'مولّد كلمات المرور', hi:'पासवर्ड जेनरेटर', ja:'パスワード生成', ky:'Сырсөз генератору', 'zh-Hant':'密碼產生器' },
  t_password_desc: { bg:'Силни пароли с 9 метода', ru:'Надёжные пароли, 9 методов', uk:'Надійні паролі, 9 методів', en:'Strong passwords, 9 methods', de:'Starke Passwörter, 9 Methoden', fr:'Mots de passe forts, 9 méthodes', es:'Contraseñas fuertes, 9 métodos', 'es-MX':'Contraseñas fuertes, 9 métodos', it:'Password forti, 9 metodi', pt:'Senhas fortes, 9 métodos', ar:'كلمات مرور قوية، ٤ طرق', hi:'मज़बूत पासवर्ड, 9 तरीके', ja:'強力なパスワード・9方式', ky:'Күчтүү сырсөздөр, 9 ыкма', 'zh-Hant':'強密碼，9 種方式' },
  t_calc_name: { bg:'Калкулатори', ru:'Калькуляторы', uk:'Калькулятори', en:'Calculators', de:'Rechner', fr:'Calculatrices', es:'Calculadoras', 'es-MX':'Calculadoras', it:'Calcolatrici', pt:'Calculadoras', ar:'حاسبات', hi:'कैलकुलेटर', ja:'計算ツール', ky:'Эсептегичтер', 'zh-Hant':'計算機' },
  t_calc_desc: { bg:'Заем, ДДС, лихва, проценти', ru:'Кредит, НДС, проценты', uk:'Кредит, ПДВ, відсотки', en:'Loan, VAT, interest, percentages', de:'Kredit, MwSt., Zinsen, Prozente', fr:'Prêt, TVA, intérêts, pourcentages', es:'Préstamo, IVA, interés, porcentajes', 'es-MX':'Préstamo, IVA, interés, porcentajes', it:'Prestito, IVA, interessi, percentuali', pt:'Empréstimo, IVA, juros, percentagens', ar:'قرض، ضريبة، فائدة، نسب', hi:'ऋण, वैट, ब्याज, प्रतिशत', ja:'ローン・税・利息・割合', ky:'Насыя, КНС, пайыз', 'zh-Hant':'貸款、增值稅、利息、百分比' },
  t_text_name: { bg:'Текстови инструменти', ru:'Текстовые инструменты', uk:'Текстові інструменти', en:'Text tools', de:'Text-Werkzeuge', fr:'Outils de texte', es:'Herramientas de texto', 'es-MX':'Herramientas de texto', it:'Strumenti di testo', pt:'Ferramentas de texto', ar:'أدوات النصوص', hi:'टेक्स्ट टूल', ja:'テキストツール', ky:'Текст куралдары', 'zh-Hant':'文字工具' },
  t_text_desc: { bg:'Брояч, форматиране, Base64', ru:'Счётчик, форматирование, Base64', uk:'Лічильник, форматування, Base64', en:'Counter, formatting, Base64', de:'Zähler, Formatierung, Base64', fr:'Compteur, mise en forme, Base64', es:'Contador, formato, Base64', 'es-MX':'Contador, formato, Base64', it:'Contatore, formattazione, Base64', pt:'Contador, formatação, Base64', ar:'عدّاد، تنسيق، Base64', hi:'काउंटर, फ़ॉर्मेटिंग, Base64', ja:'カウント・整形・Base64', ky:'Эсептегич, форматтоо, Base64', 'zh-Hant':'計數、格式化、Base64' },
  t_image_name: { bg:'Компресор на снимки', ru:'Сжатие изображений', uk:'Стиснення зображень', en:'Image compressor', de:'Bildkompressor', fr:'Compresseur d’images', es:'Compresor de imágenes', 'es-MX':'Compresor de imágenes', it:'Compressore immagini', pt:'Compressor de imagens', ar:'ضاغط الصور', hi:'इमेज कंप्रेसर', ja:'画像圧縮', ky:'Сүрөт кысуу', 'zh-Hant':'圖片壓縮' },
  t_image_desc: { bg:'Намали JPEG / PNG / WebP', ru:'Уменьши JPEG / PNG / WebP', uk:'Зменши JPEG / PNG / WebP', en:'Shrink JPEG / PNG / WebP', de:'JPEG / PNG / WebP verkleinern', fr:'Réduire JPEG / PNG / WebP', es:'Reduce JPEG / PNG / WebP', 'es-MX':'Reduce JPEG / PNG / WebP', it:'Riduci JPEG / PNG / WebP', pt:'Reduza JPEG / PNG / WebP', ar:'صغّر JPEG / PNG / WebP', hi:'JPEG / PNG / WebP छोटा करें', ja:'JPEG / PNG / WebP を縮小', ky:'JPEG / PNG / WebP кичирейтүү', 'zh-Hant':'縮小 JPEG / PNG / WebP' },
  t_ev_name: { bg:'Снимки като доказателство', ru:'Фото как доказательство', uk:'Фото як доказ', en:'Photo evidence', de:'Fotos als Beweis', fr:'Photos comme preuve', es:'Fotos como prueba', 'es-MX':'Fotos como prueba', it:'Foto come prova', pt:'Fotos como prova', ar:'الصور كدليل', hi:'सबूत के तौर पर फ़ोटो', ja:'証拠写真', ky:'Сүрөт далил катары', 'zh-Hant':'照片證據' },
  t_ev_desc: { bg:'Воден знак с дата и място, SHA-256 дневник, проверка за промяна, подписан PDF', ru:'Водяной знак с датой и местом, журнал SHA-256, проверка изменений, подписанный PDF', uk:'Водяний знак із датою й місцем, журнал SHA-256, перевірка змін, підписаний PDF', en:'Date & place watermark, SHA-256 journal, tamper check, signed PDF', de:'Wasserzeichen mit Datum und Ort, SHA-256-Protokoll, Änderungsprüfung, signiertes PDF', fr:'Filigrane date et lieu, journal SHA-256, contrôle de retouche, PDF signé', es:'Marca de agua con fecha y lugar, registro SHA-256, detección de cambios, PDF firmado', 'es-MX':'Marca de agua con fecha y lugar, registro SHA-256, detección de cambios, PDF firmado', it:'Filigrana con data e luogo, registro SHA-256, verifica modifiche, PDF firmato', pt:'Marca de água com data e local, registo SHA-256, deteção de alterações, PDF assinado', ar:'علامة مائية بالتاريخ والمكان، سجل SHA-256، كشف التعديل، PDF موقّع', hi:'तारीख और जगह का वॉटरमार्क, SHA-256 लॉग, बदलाव की जाँच, हस्ताक्षरित PDF', ja:'日時・場所の透かし、SHA-256 ログ、改ざん検出、署名入り PDF', ky:'Күн жана жер суу белгиси, SHA-256 журналы, өзгөртүүнү текшерүү, кол коюлган PDF', 'zh-Hant':'日期與地點浮水印、SHA-256 日誌、竄改檢查、簽名 PDF' },
  t_rotate3d_name: { bg:'Хартиен 3D', ru:'Бумажное 3D', uk:'Паперове 3D', en:'Paper 3D', de:'Papier-3D', fr:'Papier 3D', es:'Papel 3D', 'es-MX':'Papel 3D', it:'Carta 3D', pt:'Papel 3D', ar:'ورق ثلاثي الأبعاد', hi:'पेपर 3D', ja:'ペーパー3D', ky:'Кагаз 3D', 'zh-Hant':'紙藝 3D' },
  t_rotate3d_desc: { bg:'От снимка до хартиена фигура: шаблон за печат, 3D преглед, стерео карта', ru:'От фото до бумажной фигуры: шаблон для печати, 3D-просмотр, стереокарта', uk:'Від фото до паперової фігури: шаблон для друку, 3D-перегляд, стереокартка', en:'From a photo to a paper figure: print template, 3D preview, stereo card', de:'Vom Foto zur Papierfigur: Druckvorlage, 3D-Vorschau, Stereokarte', fr:'De la photo à la figure en papier : gabarit à imprimer, aperçu 3D, carte stéréo', es:'De la foto a la figura de papel: plantilla para imprimir, vista 3D, tarjeta estéreo', 'es-MX':'De la foto a la figura de papel: plantilla para imprimir, vista 3D, tarjeta estéreo', it:'Dalla foto alla figura di carta: sagoma da stampare, anteprima 3D, scheda stereo', pt:'Da foto à figura de papel: molde para imprimir, pré-visualização 3D, cartão estéreo', ar:'من الصورة إلى شكل ورقي: قالب للطباعة، معاينة ثلاثية الأبعاد، بطاقة مجسّمة', hi:'फ़ोटो से कागज़ की आकृति तक: प्रिंट टेम्पलेट, 3D पूर्वावलोकन, स्टीरियो कार्ड', ja:'写真から紙の立体へ：印刷用型紙、3Dプレビュー、ステレオカード', ky:'Сүрөттөн кагаз фигурага: басма үлгү, 3D көрүү, стерео карта', 'zh-Hant':'從照片到紙藝圖形：列印模板、3D 預覽、立體卡' },
  t_pdf_name: { bg:'PDF инструменти', ru:'PDF-инструменты', uk:'PDF-інструменти', en:'PDF tools', de:'PDF-Werkzeuge', fr:'Outils PDF', es:'Herramientas PDF', 'es-MX':'Herramientas PDF', it:'Strumenti PDF', pt:'Ferramentas PDF', ar:'أدوات PDF', hi:'PDF टूल', ja:'PDFツール', ky:'PDF куралдары', 'zh-Hant':'PDF 工具' },
  t_pdf_desc: { bg:'Сливане, разделяне, воден знак', ru:'Объединение, разделение, водяной знак', uk:'Об’єднання, поділ, водяний знак', en:'Merge, split, watermark', de:'Zusammenführen, teilen, Wasserzeichen', fr:'Fusionner, diviser, filigrane', es:'Unir, dividir, marca de agua', 'es-MX':'Unir, dividir, marca de agua', it:'Unisci, dividi, filigrana', pt:'Juntar, dividir, marca d’água', ar:'دمج، تقسيم، علامة مائية', hi:'मर्ज, विभाजन, वॉटरमार्क', ja:'結合・分割・透かし', ky:'Бириктирүү, бөлүү, суу белгиси', 'zh-Hant':'合併、分割、浮水印' },
  t_pdfc_name: { bg:'Свиване на PDF', ru:'Сжатие PDF', uk:'Стиснення PDF', en:'PDF compress', de:'PDF komprimieren', fr:'Compresser PDF', es:'Comprimir PDF', 'es-MX':'Comprimir PDF', it:'Comprimi PDF', pt:'Comprimir PDF', ar:'ضغط PDF', hi:'PDF संपीड़न', ja:'PDF圧縮', ky:'PDF кысуу', 'zh-Hant':'PDF 壓縮' },
  t_pdfc_desc: { bg:'Растеризира страниците за по-малък размер', ru:'Растрирует страницы для меньшего размера', uk:'Растеризує сторінки для меншого розміру', en:'Rasterizes pages for a smaller size', de:'Rastert Seiten für kleinere Größe', fr:'Rastérise les pages pour réduire la taille', es:'Rasteriza páginas para reducir tamaño', 'es-MX':'Rasteriza páginas para reducir tamaño', it:'Rasterizza le pagine per ridurre la dimensione', pt:'Rasteriza páginas para reduzir o tamanho', ar:'يحوّل الصفحات إلى صور لتصغير الحجم', hi:'छोटे आकार हेतु पेज रास्टराइज़ करता है', ja:'ページをラスタライズして縮小', ky:'Барактарды кичирейтүү үчүн растрлайт', 'zh-Hant':'點陣化頁面以縮小體積' },
  t_crypto_name: { bg:'Крипто графики', ru:'Крипто-графики', uk:'Крипто-графіки', en:'Crypto charts', de:'Krypto-Charts', fr:'Graphiques crypto', es:'Gráficos cripto', 'es-MX':'Gráficos cripto', it:'Grafici cripto', pt:'Gráficos cripto', ar:'مخططات الكريبتو', hi:'क्रिप्टो चार्ट', ja:'暗号資産チャート', ky:'Крипто графиктер', 'zh-Hant':'加密貨幣圖表' },
  t_crypto_desc: { bg:'RSI, Fibonacci, BTC/ETH по периоди (Binance/CoinGecko)', ru:'RSI, Фибоначчи, BTC/ETH по периодам (Binance/CoinGecko)', uk:'RSI, Фібоначчі, BTC/ETH за періоди (Binance/CoinGecko)', en:'RSI, Fibonacci, BTC/ETH over periods (Binance/CoinGecko)', de:'RSI, Fibonacci, BTC/ETH über Zeiträume (Binance/CoinGecko)', fr:'RSI, Fibonacci, BTC/ETH par périodes (Binance/CoinGecko)', es:'RSI, Fibonacci, BTC/ETH por periodos (Binance/CoinGecko)', 'es-MX':'RSI, Fibonacci, BTC/ETH por periodos (Binance/CoinGecko)', it:'RSI, Fibonacci, BTC/ETH per periodi (Binance/CoinGecko)', pt:'RSI, Fibonacci, BTC/ETH por períodos (Binance/CoinGecko)', ar:'RSI، فيبوناتشي، BTC/ETH عبر الفترات (Binance/CoinGecko)', hi:'RSI, फिबोनाची, BTC/ETH अवधि अनुसार (Binance/CoinGecko)', ja:'RSI・フィボナッチ・BTC/ETH 期間別（Binance/CoinGecko）', ky:'RSI, Фибоначчи, BTC/ETH мезгилдер боюнча (Binance/CoinGecko)', 'zh-Hant':'RSI、費波那契、BTC/ETH 各週期（Binance/CoinGecko）' },
  t_fx_name: { bg:'Валутни курсове', ru:'Курсы валют', uk:'Курси валют', en:'Currency rates', de:'Wechselkurse', fr:'Taux de change', es:'Tipos de cambio', 'es-MX':'Tipos de cambio', it:'Tassi di cambio', pt:'Taxas de câmbio', ar:'أسعار العملات', hi:'मुद्रा दरें', ja:'為替レート', ky:'Валюта курстары', 'zh-Hant':'匯率' },
  t_fx_desc: { bg:'Конвертор и курсове на живо', ru:'Конвертер и курсы в реальном времени', uk:'Конвертер і курси в реальному часі', en:'Converter and live rates', de:'Umrechner und Live-Kurse', fr:'Convertisseur et taux en direct', es:'Conversor y tasas en vivo', 'es-MX':'Conversor y tasas en vivo', it:'Convertitore e tassi live', pt:'Conversor e taxas ao vivo', ar:'محوّل وأسعار حية', hi:'कन्वर्टर और लाइव दरें', ja:'コンバーターとライブレート', ky:'Конвертер жана түз курстар', 'zh-Hant':'換算器與即時匯率' },
  t_auth_name: { bg:'Authenticator (2FA)', ru:'Authenticator (2FA)', uk:'Authenticator (2FA)', en:'Authenticator (2FA)', de:'Authenticator (2FA)', fr:'Authenticator (2FA)', es:'Authenticator (2FA)', 'es-MX':'Authenticator (2FA)', it:'Authenticator (2FA)', pt:'Authenticator (2FA)', ar:'Authenticator (2FA)', hi:'Authenticator (2FA)', ja:'Authenticator (2FA)', ky:'Authenticator (2FA)', 'zh-Hant':'Authenticator (2FA)' },
  t_auth_desc: { bg:'2FA кодове, пароли, портфейли — шифриран сейф', ru:'2FA-коды, пароли, кошельки — шифрованное хранилище', uk:'2FA-коди, паролі, гаманці — шифроване сховище', en:'2FA codes, passwords, wallets — encrypted vault', de:'2FA-Codes, Passwörter, Wallets — verschlüsselter Tresor', fr:'Codes 2FA, mots de passe, portefeuilles — coffre chiffré', es:'Códigos 2FA, contraseñas, carteras — bóveda cifrada', 'es-MX':'Códigos 2FA, contraseñas, carteras — bóveda cifrada', it:'Codici 2FA, password, portafogli — cassaforte cifrata', pt:'Códigos 2FA, senhas, carteiras — cofre cifrado', ar:'رموز 2FA وكلمات مرور ومحافظ — خزنة مشفّرة', hi:'2FA कोड, पासवर्ड, वॉलेट — एन्क्रिप्टेड वॉल्ट', ja:'2FAコード・パスワード・ウォレット — 暗号化保管庫', ky:'2FA коддор, сырсөздөр, капчыктар — шифрленген сейф', 'zh-Hant':'2FA 代碼、密碼、錢包 — 加密保險庫' },
  t_howto_name: { bg:'Видео инструкция', ru:'Видеоинструкция', uk:'Відеоінструкція', en:'How-to video', de:'Video-Anleitung', fr:'Tutoriel vidéo', es:'Videotutorial', 'es-MX':'Videotutorial', it:'Video guida', pt:'Vídeo tutorial', ar:'فيديو تعليمي', hi:'वीडियो गाइड', ja:'動画マニュアル', ky:'Видео нускама', 'zh-Hant':'影片教學' },
  t_howto_desc: { bg:'Снимай стъпките — апът ги прави на видео урок, GIF и лист за печат', ru:'Снимите шаги — приложение сделает видеоурок, GIF и лист для печати', uk:'Зніміть кроки — застосунок зробить відеоурок, GIF і аркуш для друку', en:'Shoot the steps — the app turns them into a video lesson, GIF and printable sheet', de:'Schritte filmen — die App macht daraus Video-Lektion, GIF und Druckblatt', fr:'Filmez les étapes — l’appli en fait une leçon vidéo, un GIF et une fiche', es:'Graba los pasos: la app los convierte en videolección, GIF y hoja imprimible', 'es-MX':'Graba los pasos: la app los convierte en videolección, GIF y hoja imprimible', it:'Riprendi i passaggi: l’app crea video lezione, GIF e scheda da stampare', pt:'Grave os passos — o app cria videoaula, GIF e folha para imprimir', ar:'صوّر الخطوات — يحوّلها التطبيق إلى درس فيديو وGIF وورقة للطباعة', hi:'चरण शूट करें — ऐप उन्हें वीडियो पाठ, GIF और प्रिंट शीट बनाता है', ja:'手順を撮影 — 動画レッスン・GIF・印刷用シートに', ky:'Кадамдарды тартыңыз — колдонмо видео сабак, GIF жана барак жасайт', 'zh-Hant':'拍下步驟 — App 做成影片教學、GIF 與列印說明單' },
  t_vid_name: { bg:'Видео инструменти', ru:'Видео инструменты', uk:'Відео інструменти', en:'Video tools', de:'Video-Werkzeuge', fr:'Outils vidéo', es:'Herramientas de vídeo', 'es-MX':'Herramientas de video', it:'Strumenti video', pt:'Ferramentas de vídeo', ar:'أدوات الفيديو', hi:'वीडियो उपकरण', ja:'動画ツール', ky:'Видео куралдар', 'zh-Hant':'影片工具' },
  t_vid_desc: { bg:'Изрязване, MP3, завъртане, скорост, 720p, компресия, кадър, GIF, формати', ru:'Обрезка, MP3, поворот, скорость, 720p, сжатие, кадр, GIF, форматы', uk:'Обрізання, MP3, поворот, швидкість, 720p, стиснення, кадр, GIF, формати', en:'Trim, MP3, rotate, speed, 720p, compress, frame, GIF, formats', de:'Schneiden, MP3, Drehen, Tempo, 720p, Komprimieren, Standbild, GIF, Formate', fr:'Couper, MP3, rotation, vitesse, 720p, compression, image, GIF, formats', es:'Recortar, MP3, girar, velocidad, 720p, comprimir, fotograma, GIF, formatos', 'es-MX':'Recortar, MP3, girar, velocidad, 720p, comprimir, cuadro, GIF, formatos', it:'Taglia, MP3, ruota, velocità, 720p, comprimi, fotogramma, GIF, formati', pt:'Cortar, MP3, girar, velocidade, 720p, comprimir, quadro, GIF, formatos', ar:'قص، MP3، تدوير، سرعة، 720p، ضغط، لقطة، GIF، صيغ', hi:'ट्रिम, MP3, घुमाएँ, गति, 720p, संपीड़न, फ़्रेम, GIF, फ़ॉर्मेट', ja:'トリム・MP3・回転・速度・720p・圧縮・静止画・GIF・形式', ky:'Кесүү, MP3, буруу, ылдамдык, 720p, кысуу, кадр, GIF, форматтар', 'zh-Hant':'剪輯、MP3、旋轉、速度、720p、壓縮、截圖、GIF、格式' },
  t_snd_name: { bg:'Студио за звук и глас', ru:'Студия звука и голоса', uk:'Студія звуку та голосу', en:'Sound & Voice Studio', de:'Sound- & Stimm-Studio', fr:'Studio son et voix', es:'Estudio de sonido y voz', 'es-MX':'Estudio de sonido y voz', it:'Studio suono e voce', pt:'Estúdio de som e voz', ar:'استوديو الصوت والكلام', hi:'साउंड और वॉइस स्टूडियो', ja:'サウンド＆ボイススタジオ', ky:'Үн жана добуш студиясы', 'zh-Hant':'聲音與人聲工作室' },
  t_snd_desc: { bg:'Ефекти и модулатори на глас, запис, преди/след, конвертор — офлайн', ru:'Эффекты и модуляторы голоса, запись, до/после, конвертер — офлайн', uk:'Ефекти й модулятори голосу, запис, до/після, конвертер — офлайн', en:'Voice effects & modulators, recording, before/after, converter — offline', de:'Stimm-Effekte & Modulatoren, Aufnahme, Vorher/Nachher, Konverter — offline', fr:'Effets et modulateurs de voix, enregistrement, avant/après, convertisseur — hors ligne', es:'Efectos y moduladores de voz, grabación, antes/después, conversor — sin conexión', 'es-MX':'Efectos y moduladores de voz, grabación, antes/después, conversor — sin conexión', it:'Effetti e modulatori vocali, registrazione, prima/dopo, convertitore — offline', pt:'Efeitos e moduladores de voz, gravação, antes/depois, conversor — offline', ar:'مؤثرات ومعدّلات صوت، تسجيل، قبل/بعد، محوّل — دون اتصال', hi:'वॉइस इफ़ेक्ट व मॉड्युलेटर, रिकॉर्डिंग, पहले/बाद, कन्वर्टर — ऑफ़लाइन', ja:'声のエフェクトとモジュレーター、録音、前後比較、変換 — オフライン', ky:'Добуш эффекттери жана модуляторлор, жазуу, чейин/кийин, конвертер — оффлайн', 'zh-Hant':'人聲效果與調變器、錄音、前後對比、轉換器 — 離線' },
  t_pdfd_name: { bg:'PDF към Word', ru:'PDF в Word', uk:'PDF у Word', en:'PDF to Word', de:'PDF zu Word', fr:'PDF vers Word', es:'PDF a Word', 'es-MX':'PDF a Word', it:'Da PDF a Word', pt:'PDF para Word', ar:'PDF إلى Word', hi:'PDF से Word', ja:'PDF から Word', ky:'PDF → Word', 'zh-Hant':'PDF 轉 Word' },
  t_pdfd_desc: { bg:'Извлича текста и прави .docx файл', ru:'Извлекает текст и создаёт файл .docx', uk:'Витягує текст і створює файл .docx', en:'Extracts the text into a .docx file', de:'Extrahiert den Text in eine .docx-Datei', fr:'Extrait le texte vers un fichier .docx', es:'Extrae el texto a un archivo .docx', 'es-MX':'Extrae el texto a un archivo .docx', it:'Estrae il testo in un file .docx', pt:'Extrai o texto para um arquivo .docx', ar:'يستخرج النص إلى ملف ‎.docx', hi:'टेक्स्ट निकालकर .docx फ़ाइल बनाता है', ja:'テキストを .docx に抽出', ky:'Текстти .docx файлга чыгарат', 'zh-Hant':'將文字擷取為 .docx 檔' },
  t_pw_name: { bg:'Price Watch — следи цени', ru:'Price Watch — следи за ценами', uk:'Price Watch — стеж за цінами', en:'Price Watch — track prices', de:'Price Watch — Preise beobachten', fr:'Price Watch — suivre les prix', es:'Price Watch — vigila precios', 'es-MX':'Price Watch — vigila precios', it:'Price Watch — monitora i prezzi', pt:'Price Watch — acompanhe preços', ar:'Price Watch — راقب الأسعار', hi:'Price Watch — कीमतें देखें', ja:'Price Watch — 価格を監視', ky:'Price Watch — бааларды байкоо', 'zh-Hant':'Price Watch — 追蹤價格' },
  t_pw_desc: { bg:'Прагове на крипто/валути с известия', ru:'Пороги на крипто/валюты с уведомлениями', uk:'Пороги на крипто/валюти зі сповіщеннями', en:'Crypto/currency thresholds with alerts', de:'Krypto-/Währungsschwellen mit Alarmen', fr:'Seuils crypto/devises avec alertes', es:'Umbrales cripto/divisas con avisos', 'es-MX':'Umbrales cripto/divisas con avisos', it:'Soglie cripto/valute con avvisi', pt:'Limites cripto/moedas com alertas', ar:'حدود للكريبتو/العملات مع تنبيهات', hi:'क्रिप्टो/मुद्रा सीमाएं और सूचनाएं', ja:'暗号資産・通貨のしきい値と通知', ky:'Крипто/валюта чектери жана билдирүүлөр', 'zh-Hant':'加密貨幣／貨幣門檻與通知' },
  t_watch20_name: { bg:'Наблюдавай 20 валути', ru:'Следи за 20 валютами', uk:'Стеж за 20 валютами', en:'Watch 20 currencies', de:'20 Währungen beobachten', fr:'Surveiller 20 devises', es:'Vigila 20 monedas', 'es-MX':'Vigila 20 monedas', it:'Monitora 20 valute', pt:'Acompanhe 20 moedas', ar:'راقب ٢٠ عملة', hi:'20 मुद्राएं देखें', ja:'20通貨を監視', ky:'20 валютаны байкоо', 'zh-Hant':'監看 20 種貨幣' },
  t_watch20_desc: { bg:'Прагове с известие и звук за до 20 двойки', ru:'Пороги с уведомлением и звуком до 20 пар', uk:'Пороги зі сповіщенням і звуком до 20 пар', en:'Alert + sound thresholds for up to 20 pairs', de:'Schwellen mit Hinweis und Ton für bis zu 20 Paare', fr:'Seuils avec alerte et son pour 20 paires', es:'Umbrales con aviso y sonido para hasta 20 pares', 'es-MX':'Umbrales con aviso y sonido para hasta 20 pares', it:'Soglie con avviso e suono fino a 20 coppie', pt:'Limiares com aviso e som para até 20 pares', ar:'حدود مع تنبيه وصوت حتى ٢٠ زوجًا', hi:'20 जोड़ियों तक अलर्ट + ध्वनि सीमाएं', ja:'最大20ペアの通知・音しきい値', ky:'20 жупка чейин эскертүү жана үн чеги', 'zh-Hant':'最多 20 組的提醒與聲音門檻' },
  t_scraper_name: { bg:'Web скрапер', ru:'Веб-скрапер', uk:'Веб-скрапер', en:'Web scraper', de:'Web-Scraper', fr:'Scraper web', es:'Web scraper', 'es-MX':'Web scraper', it:'Web scraper', pt:'Web scraper', ar:'كاشط ويب', hi:'वेब स्क्रैपर', ja:'ウェブスクレイパー', ky:'Веб скрапер', 'zh-Hant':'網頁擷取器' },
  t_scraper_desc: { bg:'Извличане на заглавие/текст/връзки', ru:'Извлечение заголовка/текста/ссылок', uk:'Витяг заголовка/тексту/посилань', en:'Extract title/text/links', de:'Titel/Text/Links extrahieren', fr:'Extraire titre/texte/liens', es:'Extraer título/texto/enlaces', 'es-MX':'Extraer título/texto/enlaces', it:'Estrai titolo/testo/link', pt:'Extrair título/texto/links', ar:'استخراج العنوان/النص/الروابط', hi:'शीर्षक/टेक्स्ट/लिंक निकालें', ja:'タイトル/本文/リンクを抽出', ky:'Аталыш/текст/шилтемелерди алуу', 'zh-Hant':'擷取標題／文字／連結' },
  t_ai_name: { bg:'AI генератор на текст', ru:'AI-генератор текста', uk:'AI-генератор тексту', en:'AI text generator', de:'KI-Textgenerator', fr:'Générateur de texte IA', es:'Generador de texto IA', 'es-MX':'Generador de texto IA', it:'Generatore di testo IA', pt:'Gerador de texto IA', ar:'مولّد نصوص بالذكاء الاصطناعي', hi:'AI टेक्स्ट जेनरेटर', ja:'AIテキスト生成', ky:'AI текст генератору', 'zh-Hant':'AI 文字產生器' },
  t_ai_desc: { bg:'Пиши, обобщавай, превеждай (безплатно)', ru:'Пиши, обобщай, переводи (бесплатно)', uk:'Пиши, узагальнюй, перекладай (безкоштовно)', en:'Write, summarize, translate (free)', de:'Schreiben, zusammenfassen, übersetzen (gratis)', fr:'Écrire, résumer, traduire (gratuit)', es:'Escribe, resume, traduce (gratis)', 'es-MX':'Escribe, resume, traduce (gratis)', it:'Scrivi, riassumi, traduci (gratis)', pt:'Escreva, resuma, traduza (grátis)', ar:'اكتب، لخّص، ترجم (مجانًا)', hi:'लिखें, सारांश, अनुवाद (मुफ़्त)', ja:'作成・要約・翻訳（無料）', ky:'Жаз, жыйынтыкта, котор (акысыз)', 'zh-Hant':'撰寫、摘要、翻譯（免費）' },
  t_textcase_name: { bg:'Регистър и редове', ru:'Регистр и строки', uk:'Регістр і рядки', en:'Case & lines', de:'Groß/Klein & Zeilen', fr:'Casse et lignes', es:'Mayúsculas y líneas', 'es-MX':'Mayúsculas y líneas', it:'Maiuscole e righe', pt:'Maiúsculas e linhas', ar:'الحالة والأسطر', hi:'केस और पंक्तियाँ', ja:'大小文字と行', ky:'Регистр жана саптар', 'zh-Hant':'大小寫與行' },
  t_textcase_desc: { bg:'ГЛАВНИ/малки/Заглавие, сортиране, без дубли, номериране, slug', ru:'ПРОПИСНЫЕ/строчные/Заголовок, сортировка, без дублей, нумерация, slug', uk:'ВЕЛИКІ/малі/Заголовок, сортування, без дублів, нумерація, slug', en:'UPPER/lower/Title, sort, dedupe, numbering, slug', de:'GROSS/klein/Titel, sortieren, Duplikate, Nummerierung, Slug', fr:'MAJ/min/Titre, tri, doublons, numérotation, slug', es:'MAYÚS/minús/Título, ordenar, duplicados, numeración, slug', 'es-MX':'MAYÚS/minús/Título, ordenar, duplicados, numeración, slug', it:'MAIUSC/minusc/Titolo, ordina, duplicati, numerazione, slug', pt:'MAIÚS/minús/Título, ordenar, duplicados, numeração, slug', ar:'كبيرة/صغيرة/عنوان، ترتيب، إزالة المكرر، ترقيم، slug', hi:'बड़े/छोटे/शीर्षक, क्रम, डुप्लिकेट, नंबरिंग, slug', ja:'大文字/小文字/タイトル・並替・重複削除・行番号・slug', ky:'БАШ/кичине/Аталыш, иреттөө, кайталоосуз, номерлөө, slug', 'zh-Hant':'大寫/小寫/標題、排序、去重、行號、slug' },
  t_textencode_name: { bg:'Кодиране/декодиране', ru:'Кодирование/декодирование', uk:'Кодування/декодування', en:'Encode/Decode', de:'Kodieren/Dekodieren', fr:'Encoder/Décoder', es:'Codificar/Decodificar', 'es-MX':'Codificar/Decodificar', it:'Codifica/Decodifica', pt:'Codificar/Decodificar', ar:'ترميز/فك ترميز', hi:'एन्कोड/डिकोड', ja:'エンコード/デコード', ky:'Коддоо/Декоддоо', 'zh-Hant':'編碼/解碼' },
  t_textencode_desc: { bg:'URL, HTML, ROT13, Морзов код, двоично, шестнайсетично', ru:'URL, HTML, ROT13, Морзе, двоичное, шестнадцатеричное', uk:'URL, HTML, ROT13, Морзе, двійкове, шістнадцяткове', en:'URL, HTML, ROT13, Morse, binary, hex', de:'URL, HTML, ROT13, Morse, binär, hex', fr:'URL, HTML, ROT13, Morse, binaire, hex', es:'URL, HTML, ROT13, Morse, binario, hex', 'es-MX':'URL, HTML, ROT13, Morse, binario, hex', it:'URL, HTML, ROT13, Morse, binario, hex', pt:'URL, HTML, ROT13, Morse, binário, hex', ar:'URL، HTML، ROT13، مورس، ثنائي، ست عشري', hi:'URL, HTML, ROT13, मोर्स, बाइनरी, हेक्स', ja:'URL・HTML・ROT13・モールス・2進・16進', ky:'URL, HTML, ROT13, Морзе, экилик, он алтылык', 'zh-Hant':'URL、HTML、ROT13、摩斯、二進位、十六進位' },
  t_textgen_name: { bg:'Генератори', ru:'Генераторы', uk:'Генератори', en:'Generators', de:'Generatoren', fr:'Générateurs', es:'Generadores', 'es-MX':'Generadores', it:'Generatori', pt:'Geradores', ar:'مولدات', hi:'जनरेटर', ja:'ジェネレーター', ky:'Генераторлор', 'zh-Hant':'產生器' },
  t_textgen_desc: { bg:'Парола, UUID, Lorem ipsum, SHA хешове', ru:'Пароль, UUID, Lorem ipsum, SHA-хеши', uk:'Пароль, UUID, Lorem ipsum, SHA-хеші', en:'Password, UUID, Lorem ipsum, SHA hashes', de:'Passwort, UUID, Lorem ipsum, SHA-Hashes', fr:'Mot de passe, UUID, Lorem ipsum, hachages SHA', es:'Contraseña, UUID, Lorem ipsum, hashes SHA', 'es-MX':'Contraseña, UUID, Lorem ipsum, hashes SHA', it:'Password, UUID, Lorem ipsum, hash SHA', pt:'Senha, UUID, Lorem ipsum, hashes SHA', ar:'كلمة مرور، UUID، Lorem ipsum، تجزئات SHA', hi:'पासवर्ड, UUID, Lorem ipsum, SHA हैश', ja:'パスワード・UUID・Lorem ipsum・SHAハッシュ', ky:'Сырсөз, UUID, Lorem ipsum, SHA хештер', 'zh-Hant':'密碼、UUID、Lorem ipsum、SHA 雜湊' },
  t_textextract_name: { bg:'Извличане', ru:'Извлечение', uk:'Витягання', en:'Extract', de:'Extrahieren', fr:'Extraction', es:'Extraer', 'es-MX':'Extraer', it:'Estrai', pt:'Extrair', ar:'استخراج', hi:'निकालें', ja:'抽出', ky:'Чыгаруу', 'zh-Hant':'擷取' },
  t_textextract_desc: { bg:'Имейли, URL-и, числа, хаштагове, споменавания, IP', ru:'Эл. почты, URL, числа, хэштеги, упоминания, IP', uk:'Ел. пошти, URL, числа, хештеги, згадки, IP', en:'Emails, URLs, numbers, hashtags, mentions, IPs', de:'E-Mails, URLs, Zahlen, Hashtags, Erwähnungen, IPs', fr:'E-mails, URL, nombres, hashtags, mentions, IP', es:'Correos, URLs, números, hashtags, menciones, IP', 'es-MX':'Correos, URLs, números, hashtags, menciones, IP', it:'E-mail, URL, numeri, hashtag, menzioni, IP', pt:'E-mails, URLs, números, hashtags, menções, IPs', ar:'إيميلات، روابط، أرقام، وسوم، إشارات، IP', hi:'ईमेल, URL, संख्याएं, हैशटैग, मेंशन, IP', ja:'メール・URL・数値・ハッシュタグ・メンション・IP', ky:'Эл. почталар, URL, сандар, хэштегдер, эскерүүлөр, IP', 'zh-Hant':'電子郵件、網址、數字、標籤、提及、IP' },
  t_textdiff_name: { bg:'Разлика (diff)', ru:'Разница (diff)', uk:'Різниця (diff)', en:'Diff', de:'Diff', fr:'Diff', es:'Diff', 'es-MX':'Diff', it:'Diff', pt:'Diff', ar:'الفرق', hi:'डिफ़', ja:'差分', ky:'Айырма', 'zh-Hant':'差異' },
  t_textdiff_desc: { bg:'Сравни два текста ред по ред — добавени/премахнати', ru:'Сравни два текста построчно — добавлено/удалено', uk:'Порівняй два тексти по рядках — додано/видалено', en:'Compare two texts line by line — added/removed', de:'Zwei Texte zeilenweise vergleichen — hinzugefügt/entfernt', fr:'Compare deux textes ligne par ligne — ajouté/supprimé', es:'Compara dos textos línea por línea — añadido/eliminado', 'es-MX':'Compara dos textos línea por línea — añadido/eliminado', it:'Confronta due testi riga per riga — aggiunto/rimosso', pt:'Compare dois textos linha a linha — adicionado/removido', ar:'قارن نصين سطرًا بسطر — مضاف/محذوف', hi:'दो टेक्स्ट पंक्ति-दर-पंक्ति तुलना — जोड़ा/हटाया', ja:'2つのテキストを行単位で比較 — 追加/削除', ky:'Эки текстти сап-сап салыштыр — кошулган/өчүрүлгөн', 'zh-Hant':'逐行比較兩段文字 — 新增/移除' },
  t_textuni_name: { bg:'Unicode стил', ru:'Unicode стиль', uk:'Unicode стиль', en:'Unicode style', de:'Unicode-Stil', fr:'Style Unicode', es:'Estilo Unicode', 'es-MX':'Estilo Unicode', it:'Stile Unicode', pt:'Estilo Unicode', ar:'نمط يونيكود', hi:'यूनिकोड शैली', ja:'Unicodeスタイル', ky:'Unicode стили', 'zh-Hant':'Unicode 樣式' },
  t_textuni_desc: { bg:'𝐔𝐝𝐞𝐛𝐞𝐥𝐞𝐧, з̶а̶ч̶е̶р̶т̶а̶н̶, п̲о̲д̲ч̲е̲р̲т̲а̲н̲, широк — за социални мрежи', ru:'𝐖𝐢𝐫𝐧𝐰𝐟, з̶а̶ч̶ё̶р̶к̶н̶у̶т̶о̶, п̲о̲д̲ч̲ё̲р̲к̲н̲у̲т̲о̲ — для соцсетей', uk:'жирний, з̶а̶к̶р̶е̶с̶л̶е̶н̶о̶, п̲і̲д̲к̲р̲е̲с̲л̲е̲н̲о̲ — для соцмереж', en:'𝐁𝐨𝐥𝐝, s̶t̶r̶i̶k̶e̶, u̲n̲d̲e̲r̲l̲i̲n̲e̲, wide — for social media', de:'𝐅𝐞𝐭𝐭, durchgestrichen, unterstrichen, breit — für soziale Medien', fr:'𝐆𝐫𝐚𝐬, barré, souligné, large — pour réseaux sociaux', es:'𝐍𝐞𝐠𝐫𝐢𝐭𝐚, tachado, subrayado, ancho — para redes sociales', 'es-MX':'𝐍𝐞𝐠𝐫𝐢𝐭𝐚, tachado, subrayado, ancho — para redes sociales', it:'𝐆𝐫𝐚𝐬𝐬𝐞𝐭𝐭𝐨, barrato, sottolineato, largo — per i social', pt:'𝐍𝐞𝐠𝐫𝐢𝐭𝐨, tachado, sublinhado, largo — para redes sociais', ar:'عريض، مشطوب، مسطر، واسع — لوسائل التواصل', hi:'बोल्ड, स्ट्राइक, रेखांकित, चौड़ा — सोशल मीडिया हेतु', ja:'太字・取り消し線・下線・全角 — SNS向け', ky:'Калың, сызылган, асты сызылган, кенен — соцтармактар үчүн', 'zh-Hant':'粗體、刪除線、底線、全形 — 用於社群' },
  t_textjson_name: { bg:'JSON / CSV', ru:'JSON / CSV', uk:'JSON / CSV', en:'JSON / CSV', de:'JSON / CSV', fr:'JSON / CSV', es:'JSON / CSV', 'es-MX':'JSON / CSV', it:'JSON / CSV', pt:'JSON / CSV', ar:'JSON / CSV', hi:'JSON / CSV', ja:'JSON / CSV', ky:'JSON / CSV', 'zh-Hant':'JSON / CSV' },
  t_textjson_desc: { bg:'Форматирай/сгъсти/провери JSON и превърни JSON↔CSV', ru:'Формат/сжатие/проверка JSON и JSON↔CSV', uk:'Формат/стиснення/перевірка JSON та JSON↔CSV', en:'Prettify/minify/validate JSON and JSON↔CSV', de:'JSON formatieren/minimieren/prüfen und JSON↔CSV', fr:'Formater/minifier/valider JSON et JSON↔CSV', es:'Formatear/minificar/validar JSON y JSON↔CSV', 'es-MX':'Formatear/minificar/validar JSON y JSON↔CSV', it:'Formatta/minimizza/valida JSON e JSON↔CSV', pt:'Formatar/minificar/validar JSON e JSON↔CSV', ar:'تنسيق/تصغير/تحقق JSON و JSON↔CSV', hi:'JSON फ़ॉर्मेट/मिनिफ़ाई/जाँच और JSON↔CSV', ja:'JSON整形/圧縮/検証、JSON↔CSV', ky:'JSON форматтоо/кысуу/текшерүү жана JSON↔CSV', 'zh-Hant':'JSON 美化/壓縮/驗證與 JSON↔CSV' },
  t_textfreq_name: { bg:'Честота на думи', ru:'Частота слов', uk:'Частота слів', en:'Word frequency', de:'Worthäufigkeit', fr:'Fréquence des mots', es:'Frecuencia de palabras', 'es-MX':'Frecuencia de palabras', it:'Frequenza parole', pt:'Frequência de palavras', ar:'تكرار الكلمات', hi:'शब्द आवृत्ति', ja:'単語頻度', ky:'Сөз жыштыгы', 'zh-Hant':'字詞頻率' },
  t_textfreq_desc: { bg:'Най-чести думи с ленти + общо/уникални/знаци', ru:'Самые частые слова с полосами + всего/уникальных/символов', uk:'Найчастіші слова зі смугами + всього/унікальних/символів', en:'Top words with bars + total/unique/characters', de:'Häufigste Wörter mit Balken + gesamt/eindeutig/Zeichen', fr:'Mots fréquents avec barres + total/uniques/caractères', es:'Palabras frecuentes con barras + total/únicas/caracteres', 'es-MX':'Palabras frecuentes con barras + total/únicas/caracteres', it:'Parole frequenti con barre + totale/uniche/caratteri', pt:'Palavras frequentes com barras + total/únicas/caracteres', ar:'أكثر الكلمات مع أشرطة + إجمالي/فريدة/أحرف', hi:'शीर्ष शब्द बार के साथ + कुल/अद्वितीय/वर्ण', ja:'頻出単語をバー表示＋合計/ユニーク/文字数', ky:'Эң көп сөздөр тилкелер менен + жалпы/уникалдуу/символ', 'zh-Hant':'高頻字詞含長條＋總數/不重複/字元' },
  t_textroman_name: { bg:'Римски цифри', ru:'Римские цифры', uk:'Римські цифри', en:'Roman numerals', de:'Römische Zahlen', fr:'Chiffres romains', es:'Números romanos', 'es-MX':'Números romanos', it:'Numeri romani', pt:'Números romanos', ar:'أرقام رومانية', hi:'रोमन अंक', ja:'ローマ数字', ky:'Римдик сандар', 'zh-Hant':'羅馬數字' },
  t_textroman_desc: { bg:'Число ↔ римско (1–3999), авто-разпознаване', ru:'Число ↔ римское (1–3999), автоопределение', uk:'Число ↔ римське (1–3999), автовизначення', en:'Number ↔ Roman (1–3999), auto-detect', de:'Zahl ↔ Römisch (1–3999), Auto-Erkennung', fr:'Nombre ↔ romain (1–3999), détection auto', es:'Número ↔ romano (1–3999), autodetección', 'es-MX':'Número ↔ romano (1–3999), autodetección', it:'Numero ↔ romano (1–3999), rilevamento auto', pt:'Número ↔ romano (1–3999), autodetecção', ar:'رقم ↔ روماني (1–3999)، كشف تلقائي', hi:'संख्या ↔ रोमन (1–3999), स्वतः पहचान', ja:'数字 ↔ ローマ数字 (1–3999)、自動判別', ky:'Сан ↔ римдик (1–3999), авто-аныктоо', 'zh-Hant':'數字 ↔ 羅馬 (1–3999)，自動辨識' },
  t_textnb_name: { bg:'Бройни системи', ru:'Системы счисления', uk:'Системи числення', en:'Number bases', de:'Zahlensysteme', fr:'Bases numériques', es:'Bases numéricas', 'es-MX':'Bases numéricas', it:'Basi numeriche', pt:'Bases numéricas', ar:'أنظمة العد', hi:'संख्या आधार', ja:'基数変換', ky:'Сан системалары', 'zh-Hant':'進位轉換' },
  t_textnb_desc: { bg:'Двоично / осмично / десетично / шестнайсетично (BigInt)', ru:'Двоичное / восьмеричное / десятичное / шестнадцатеричное (BigInt)', uk:'Двійкове / вісімкове / десяткове / шістнадцяткове (BigInt)', en:'Binary / octal / decimal / hex (BigInt)', de:'Binär / oktal / dezimal / hex (BigInt)', fr:'Binaire / octal / décimal / hex (BigInt)', es:'Binario / octal / decimal / hex (BigInt)', 'es-MX':'Binario / octal / decimal / hex (BigInt)', it:'Binario / ottale / decimale / hex (BigInt)', pt:'Binário / octal / decimal / hex (BigInt)', ar:'ثنائي / ثماني / عشري / ست عشري (BigInt)', hi:'बाइनरी / ऑक्टल / दशमलव / हेक्स (BigInt)', ja:'2進/8進/10進/16進 (BigInt)', ky:'Экилик / сегиздик / ондук / он алтылык (BigInt)', 'zh-Hant':'二/八/十/十六進位 (BigInt)' },
  t_textwrap_name: { bg:'Пренасяне и префикс', ru:'Перенос и префикс', uk:'Перенос і префікс', en:'Wrap & prefix', de:'Umbruch & Präfix', fr:'Retour à la ligne et préfixe', es:'Ajuste y prefijo', 'es-MX':'Ajuste y prefijo', it:'A capo e prefisso', pt:'Quebra e prefixo', ar:'التفاف وبادئة', hi:'रैप और उपसर्ग', ja:'折返しと接頭辞', ky:'Сындыруу жана префикс', 'zh-Hant':'換行與前綴' },
  t_textwrap_desc: { bg:'Пренеси на N знака, префикс на ред (цитат/коментар), разгъни', ru:'Перенос на N символов, префикс строки (цитата/коммент), развернуть', uk:'Перенос на N символів, префікс рядка (цитата/коментар), розгорнути', en:'Wrap at N chars, per-line prefix (quote/comment), unwrap', de:'Umbruch bei N Zeichen, Zeilen-Präfix (Zitat/Kommentar), entfalten', fr:'Retour à N car., préfixe par ligne (citation/commentaire), déplier', es:'Ajuste a N caracteres, prefijo por línea (cita/comentario), desenvolver', 'es-MX':'Ajuste a N caracteres, prefijo por línea (cita/comentario), desenvolver', it:'A capo a N caratteri, prefisso per riga (citazione/commento), srotola', pt:'Quebra em N caracteres, prefixo por linha (citação/comentário), desdobrar', ar:'التفاف عند N حرف، بادئة لكل سطر (اقتباس/تعليق)، فك', hi:'N वर्ण पर रैप, प्रति पंक्ति उपसर्ग (उद्धरण/टिप्पणी), अनरैप', ja:'N文字で折返し・行接頭辞（引用/コメント）・展開', ky:'N символда сынуу, сапка префикс (цитата/комментарий), жайуу', 'zh-Hant':'於 N 字換行、每行前綴（引用/註解）、取消換行' },
  t_textcolor_name: { bg:'Цветове', ru:'Цвета', uk:'Кольори', en:'Colors', de:'Farben', fr:'Couleurs', es:'Colores', 'es-MX':'Colores', it:'Colori', pt:'Cores', ar:'الألوان', hi:'रंग', ja:'色', ky:'Түстөр', 'zh-Hant':'顏色' },
  t_textcolor_desc: { bg:'HEX ↔ RGB ↔ HSL с визуална проба и избор', ru:'HEX ↔ RGB ↔ HSL с образцом и выбором', uk:'HEX ↔ RGB ↔ HSL зі зразком і вибором', en:'HEX ↔ RGB ↔ HSL with swatch & picker', de:'HEX ↔ RGB ↔ HSL mit Muster & Auswahl', fr:'HEX ↔ RGB ↔ HSL avec échantillon et sélecteur', es:'HEX ↔ RGB ↔ HSL con muestra y selector', 'es-MX':'HEX ↔ RGB ↔ HSL con muestra y selector', it:'HEX ↔ RGB ↔ HSL con campione e selettore', pt:'HEX ↔ RGB ↔ HSL com amostra e seletor', ar:'HEX ↔ RGB ↔ HSL مع عيّنة ومنتقٍ', hi:'HEX ↔ RGB ↔ HSL स्वैच और पिकर के साथ', ja:'HEX ↔ RGB ↔ HSL、見本とピッカー付き', ky:'HEX ↔ RGB ↔ HSL үлгү жана тандагыч менен', 'zh-Hant':'HEX ↔ RGB ↔ HSL 附色樣與選色器' },
  t_textts_name: { bg:'Времеви печат', ru:'Метка времени', uk:'Мітка часу', en:'Timestamp', de:'Zeitstempel', fr:'Horodatage', es:'Marca de tiempo', 'es-MX':'Marca de tiempo', it:'Timestamp', pt:'Carimbo de tempo', ar:'الطابع الزمني', hi:'टाइमस्टैम्प', ja:'タイムスタンプ', ky:'Убакыт белгиси', 'zh-Hant':'時間戳' },
  t_textts_desc: { bg:'Unix ↔ дата (локална/UTC/ISO), бутон „Сега"', ru:'Unix ↔ дата (местная/UTC/ISO), кнопка «Сейчас»', uk:'Unix ↔ дата (місцева/UTC/ISO), кнопка «Зараз»', en:'Unix ↔ date (local/UTC/ISO), “Now” button', de:'Unix ↔ Datum (lokal/UTC/ISO), „Jetzt"-Taste', fr:'Unix ↔ date (locale/UTC/ISO), bouton « Maintenant »', es:'Unix ↔ fecha (local/UTC/ISO), botón «Ahora»', 'es-MX':'Unix ↔ fecha (local/UTC/ISO), botón «Ahora»', it:'Unix ↔ data (locale/UTC/ISO), pulsante «Ora»', pt:'Unix ↔ data (local/UTC/ISO), botão “Agora”', ar:'Unix ↔ تاريخ (محلي/UTC/ISO)، زر «الآن»', hi:'Unix ↔ तिथि (स्थानीय/UTC/ISO), “अभी” बटन', ja:'Unix ↔ 日付（現地/UTC/ISO）、「現在」ボタン', ky:'Unix ↔ дата (жергиликтүү/UTC/ISO), «Азыр» баскычы', 'zh-Hant':'Unix ↔ 日期（當地/UTC/ISO），「現在」鈕' },
  t_sealed_name: { bg:'Затворен кръг', ru:'Закрытый круг', uk:'Закрите коло', en:'Closed circle', de:'Geschlossener Kreis', fr:'Cercle fermé', es:'Círculo cerrado', 'es-MX':'Círculo cerrado', it:'Cerchio chiuso', pt:'Círculo fechado', ar:'الدائرة المغلقة', hi:'बंद घेरा', ja:'閉じた輪', ky:'Жабык чөйрө', 'zh-Hant':'封閉圈子' },
  t_sealed_desc: { bg:'Шифровани документи между близки: ключове по QR, подпис на подателя, без сървър', ru:'Зашифрованные документы между близкими: ключи по QR, подпись отправителя, без сервера', uk:'Зашифровані документи між близькими: ключі по QR, підпис відправника, без сервера', en:'Encrypted documents between trusted people: keys by QR, sender signature, no server', de:'Verschlüsselte Dokumente unter Vertrauten: Schlüssel per QR, Absendersignatur, kein Server', fr:'Documents chiffrés entre proches : clés par QR, signature de l’expéditeur, sans serveur', es:'Documentos cifrados entre personas de confianza: claves por QR, firma del remitente, sin servidor', 'es-MX':'Documentos cifrados entre personas de confianza: claves por QR, firma del remitente, sin servidor', it:'Documenti cifrati tra persone fidate: chiavi via QR, firma del mittente, nessun server', pt:'Documentos cifrados entre pessoas de confiança: chaves por QR, assinatura do remetente, sem servidor', ar:'مستندات مشفّرة بين المقرّبين: مفاتيح عبر QR، توقيع المرسل، بلا خادم', hi:'भरोसेमंद लोगों के बीच एन्क्रिप्टेड दस्तावेज़: QR कुंजियाँ, भेजने वाले का हस्ताक्षर, कोई सर्वर नहीं', ja:'信頼できる相手との暗号化書類：QR鍵、送信者署名、サーバーなし', ky:'Ишенимдүү адамдар арасында шифрленген документтер: QR ачкычтар, жөнөтүүчүнүн кол тамгасы, серверсиз', 'zh-Hant':'信任者之間的加密文件：QR 金鑰、寄件者簽章、無伺服器' },
  sd_more_tools: { bg:'Още инструменти (PDF)', ru:'Другие инструменты (PDF)', uk:'Інші інструменти (PDF)', en:'More tools (PDF)', de:'Weitere Werkzeuge (PDF)', fr:'Autres outils (PDF)', es:'Más herramientas (PDF)', 'es-MX':'Más herramientas (PDF)', it:'Altri strumenti (PDF)', pt:'Mais ferramentas (PDF)', ar:'أدوات أخرى (PDF)', hi:'और टूल (PDF)', ja:'その他のツール (PDF)', ky:'Дагы куралдар (PDF)', 'zh-Hant':'更多工具 (PDF)' },
  t_pdfo_name: { bg:'PDF студио', ru:'PDF-студия', uk:'PDF-студія', en:'PDF studio', de:'PDF-Studio', fr:'Studio PDF', es:'Estudio PDF', 'es-MX':'Estudio PDF', it:'Studio PDF', pt:'Estúdio PDF', ar:'استوديو PDF', hi:'PDF स्टूडियो', ja:'PDFスタジオ', ky:'PDF студиясы', 'zh-Hant':'PDF 工作室' },
  t_pdfo_desc: { bg:'Страници с миниатюри, снимки/текст → PDF, печат, N на лист, данни', ru:'Страницы с миниатюрами, фото/текст → PDF, штамп, N на лист, сведения', uk:'Сторінки з мініатюрами, фото/текст → PDF, штамп, N на аркуш, відомості', en:'Pages with thumbnails, photos/text → PDF, stamp, N per sheet, info', de:'Seiten mit Miniaturen, Fotos/Text → PDF, Stempel, N pro Blatt, Infos', fr:'Pages en miniatures, photos/texte → PDF, tampon, N par feuille, infos', es:'Páginas con miniaturas, fotos/texto → PDF, sello, N por hoja, datos', 'es-MX':'Páginas con miniaturas, fotos/texto → PDF, sello, N por hoja, datos', it:'Pagine con miniature, foto/testo → PDF, timbro, N per foglio, dati', pt:'Páginas com miniaturas, fotos/texto → PDF, carimbo, N por folha, dados', ar:'صفحات بمصغّرات، صور/نص ← PDF، ختم، N في الورقة، معلومات', hi:'थंबनेल वाले पेज, फ़ोटो/टेक्स्ट → PDF, स्टाम्प, N प्रति शीट, जानकारी', ja:'サムネイル付きページ、写真/テキスト → PDF、スタンプ、N ページ/枚、情報', ky:'Миниатюралуу барактар, сүрөт/текст → PDF, мөөр, баракка N, маалымат', 'zh-Hant':'縮圖頁面、照片/文字 → PDF、印章、每張 N 頁、資訊' },
  t_labels_name: { bg:'QR етикети', ru:'QR-этикетки', uk:'QR-етикетки', en:'QR labels', de:'QR-Etiketten', fr:'Étiquettes QR', es:'Etiquetas QR', 'es-MX':'Etiquetas QR', it:'Etichette QR', pt:'Etiquetas QR', ar:'ملصقات QR', hi:'QR लेबल', ja:'QRラベル', ky:'QR этикеткалар', 'zh-Hant':'QR 標籤' },
  t_labels_desc: { bg:'Етикети за дома и инвентара: печат, залепи, сканирай → карта на предмета', ru:'Этикетки для дома и инвентаря: печать, наклей, сканируй → карточка предмета', uk:'Етикетки для дому та інвентарю: друк, наклей, скануй → картка предмета', en:'Labels for home and inventory: print, stick, scan → item card', de:'Etiketten für Zuhause und Inventar: drucken, aufkleben, scannen → Gegenstandskarte', fr:'Étiquettes maison et inventaire : imprimer, coller, scanner → fiche de l’objet', es:'Etiquetas para casa e inventario: imprime, pega, escanea → ficha del objeto', 'es-MX':'Etiquetas para casa e inventario: imprime, pega, escanea → ficha del objeto', it:'Etichette per casa e inventario: stampa, attacca, scansiona → scheda oggetto', pt:'Etiquetas para casa e inventário: imprime, cola, digitaliza → ficha do item', ar:'ملصقات للمنزل والجرد: اطبع، ألصق، امسح ← بطاقة الغرض', hi:'घर और इन्वेंटरी के लेबल: प्रिंट, चिपकाएँ, स्कैन → वस्तु कार्ड', ja:'家と持ち物のラベル：印刷・貼付・スキャン → アイテムカード', ky:'Үй жана инвентарь этикеткалары: басып чыгар, чапта, сканерле → буюм картасы', 'zh-Hant':'居家與物品清單標籤：列印、貼上、掃描 → 物品卡' },
  all_tools: { bg:'Всички инструменти', ru:'Все инструменты', uk:'Усі інструменти', en:'All tools', de:'Alle Werkzeuge', fr:'Tous les outils', es:'Todas las herramientas', 'es-MX':'Todas las herramientas', it:'Tutti gli strumenti', pt:'Todas as ferramentas', ar:'كل الأدوات', hi:'सभी टूल', ja:'すべてのツール', ky:'Бардык куралдар', 'zh-Hant':'所有工具' },
  t_qrlib_name: { bg:'Моите QR кодове', ru:'Мои QR-коды', uk:'Мої QR-коди', en:'My QR codes', de:'Meine QR-Codes', fr:'Mes codes QR', es:'Mis códigos QR', 'es-MX':'Mis códigos QR', it:'I miei codici QR', pt:'Meus códigos QR', ar:'رموز QR الخاصة بي', hi:'मेरे QR कोड', ja:'マイQRコード', ky:'Менин QR коддорум', 'zh-Hant':'我的 QR 碼' },
  t_qrlib_desc: { bg:'Наименувани кодове: плащания, Wi-Fi, контакти — запазени и подредени', ru:'Именованные коды: платежи, Wi-Fi, контакты — сохранённые и упорядоченные', uk:'Іменовані коди: платежі, Wi-Fi, контакти — збережені й упорядковані', en:'Named codes: payments, Wi-Fi, contacts — saved and organized', de:'Benannte Codes: Zahlungen, WLAN, Kontakte — gespeichert und geordnet', fr:'Codes nommés : paiements, Wi-Fi, contacts — enregistrés et organisés', es:'Códigos con nombre: pagos, Wi-Fi, contactos — guardados y ordenados', 'es-MX':'Códigos con nombre: pagos, Wi-Fi, contactos — guardados y ordenados', it:'Codici con nome: pagamenti, Wi-Fi, contatti — salvati e ordinati', pt:'Códigos nomeados: pagamentos, Wi-Fi, contatos — salvos e organizados', ar:'رموز مسمّاة: مدفوعات، واي فاي، جهات اتصال — محفوظة ومنظمة', hi:'नामित कोड: भुगतान, वाई-फाई, संपर्क — सहेजे और व्यवस्थित', ja:'名前付きコード：支払い・Wi-Fi・連絡先を保存して整理', ky:'Аталган коддор: төлөмдөр, Wi-Fi, байланыштар — сакталып иреттелген', 'zh-Hant':'具名代碼：付款、Wi-Fi、聯絡人 — 已儲存並分類' },
  t_qrbatch_name: { bg:'Партиден QR', ru:'Пакетный QR', uk:'Пакетний QR', en:'Batch QR', de:'Stapel-QR', fr:'QR par lot', es:'QR por lotes', 'es-MX':'QR por lotes', it:'QR in blocco', pt:'QR em lote', ar:'QR بالدفعة', hi:'बैच QR', ja:'一括QR', ky:'Партиялык QR', 'zh-Hant':'批次 QR' },
  t_qrbatch_desc: { bg:'Много кодове наведнъж — по един на ред, сваляне поединично или всички', ru:'Много кодов сразу — по одному на строку, скачивание по одному или все', uk:'Багато кодів одразу — по одному на рядок, завантаження поодинці або всі', en:'Many codes at once — one per line, download individually or all', de:'Viele Codes auf einmal — einer pro Zeile, einzeln oder alle laden', fr:'Plusieurs codes d’un coup — un par ligne, téléchargement individuel ou tout', es:'Muchos códigos a la vez — uno por línea, descarga individual o todos', 'es-MX':'Muchos códigos a la vez — uno por línea, descarga individual o todos', it:'Molti codici insieme — uno per riga, scarica singoli o tutti', pt:'Vários códigos de uma vez — um por linha, baixar individual ou todos', ar:'عدة رموز دفعة واحدة — واحد لكل سطر، تنزيل فردي أو الكل', hi:'एक साथ कई कोड — प्रति पंक्ति एक, अलग या सभी डाउनलोड', ja:'一度に多数のコード — 1行1件、個別または全部ダウンロード', ky:'Бир эле убакта көп код — ар сапка бирден, өзүнчө же баарын жүктөө', 'zh-Hant':'一次多個代碼 — 每行一個，可個別或全部下載' },
  t_qrstyle_name: { bg:'Стилизиран QR', ru:'Стилизованный QR', uk:'Стилізований QR', en:'Styled QR', de:'Stil-QR', fr:'QR stylisé', es:'QR con estilo', 'es-MX':'QR con estilo', it:'QR stilizzato', pt:'QR estilizado', ar:'QR منسّق', hi:'स्टाइल QR', ja:'装飾QR', ky:'Стилдүү QR', 'zh-Hant':'樣式 QR' },
  t_qrstyle_desc: { bg:'Цвят на кода/фона + лого в центъра', ru:'Цвет кода/фона + логотип в центре', uk:'Колір коду/фону + лого в центрі', en:'Code/background color + center logo', de:'Code-/Hintergrundfarbe + Logo in der Mitte', fr:'Couleur code/fond + logo central', es:'Color de código/fondo + logo central', 'es-MX':'Color de código/fondo + logo central', it:'Colore codice/sfondo + logo centrale', pt:'Cor do código/fundo + logo central', ar:'لون الرمز/الخلفية + شعار في الوسط', hi:'कोड/पृष्ठभूमि रंग + केंद्र लोगो', ja:'コード/背景色＋中央ロゴ', ky:'Код/фон түсү + борбордо лого', 'zh-Hant':'代碼/背景顏色＋中央標誌' },
  t_qrpay_name: { bg:'Плащане QR', ru:'QR для оплаты', uk:'QR для оплати', en:'Payment QR', de:'Zahlungs-QR', fr:'QR de paiement', es:'QR de pago', 'es-MX':'QR de pago', it:'QR di pagamento', pt:'QR de pagamento', ar:'QR للدفع', hi:'भुगतान QR', ja:'支払いQR', ky:'Төлөм QR', 'zh-Hant':'付款 QR' },
  t_qrpay_desc: { bg:'Банков превод SEPA/IBAN (EPC), UPI, крипто адрес, линк за плащане — със сума', ru:'Перевод SEPA/IBAN (EPC), UPI, крипто-адрес, ссылка на оплату — с суммой', uk:'Переказ SEPA/IBAN (EPC), UPI, крипто-адреса, посилання на оплату — із сумою', en:'SEPA/IBAN bank transfer (EPC), UPI, crypto address, payment link — with amount', de:'SEPA/IBAN-Überweisung (EPC), UPI, Krypto-Adresse, Zahlungslink — mit Betrag', fr:'Virement SEPA/IBAN (EPC), UPI, adresse crypto, lien de paiement — avec montant', es:'Transferencia SEPA/IBAN (EPC), UPI, dirección cripto, enlace de pago — con importe', 'es-MX':'Transferencia SEPA/IBAN (EPC), UPI, dirección cripto, enlace de pago — con monto', it:'Bonifico SEPA/IBAN (EPC), UPI, indirizzo crypto, link di pagamento — con importo', pt:'Transferência SEPA/IBAN (EPC), UPI, endereço cripto, ligação de pagamento — com montante', ar:'تحويل SEPA/IBAN (EPC)، UPI، عنوان عملة رقمية، رابط دفع — مع المبلغ', hi:'SEPA/IBAN ट्रांसफ़र (EPC), UPI, क्रिप्टो पता, भुगतान लिंक — राशि सहित', ja:'SEPA/IBAN振込（EPC）、UPI、暗号資産アドレス、支払いリンク — 金額付き', ky:'SEPA/IBAN которуу (EPC), UPI, крипто дарек, төлөм шилтемеси — сумма менен', 'zh-Hant':'SEPA/IBAN 轉帳（EPC）、UPI、加密地址、付款連結 — 含金額' },
  t_qrwifi_name: { bg:'Wi-Fi QR', ru:'Wi-Fi QR', uk:'Wi-Fi QR', en:'Wi-Fi QR', de:'WLAN-QR', fr:'QR Wi-Fi', es:'QR Wi-Fi', 'es-MX':'QR Wi-Fi', it:'QR Wi-Fi', pt:'QR Wi-Fi', ar:'QR واي فاي', hi:'वाई-फाई QR', ja:'Wi-Fi QR', ky:'Wi-Fi QR', 'zh-Hant':'Wi-Fi QR' },
  t_qrwifi_desc: { bg:'Сподели Wi-Fi — сканиране и телефонът се свързва сам', ru:'Поделись Wi-Fi — сканирование и телефон подключается сам', uk:'Поділись Wi-Fi — сканування і телефон під’єднується сам', en:'Share Wi-Fi — scan and the phone connects itself', de:'WLAN teilen — scannen und das Handy verbindet sich selbst', fr:'Partage le Wi-Fi — scanner et le téléphone se connecte seul', es:'Comparte Wi-Fi — escanea y el teléfono se conecta solo', 'es-MX':'Comparte Wi-Fi — escanea y el teléfono se conecta solo', it:'Condividi il Wi-Fi — scansiona e il telefono si connette da solo', pt:'Compartilhe Wi-Fi — escaneie e o telefone conecta sozinho', ar:'شارك الواي فاي — امسح ويتصل الهاتف تلقائيًا', hi:'वाई-फाई साझा करें — स्कैन करें और फ़ोन स्वयं कनेक्ट', ja:'Wi-Fiを共有 — スキャンで自動接続', ky:'Wi-Fi бөлүш — скандаганда телефон өзү туташат', 'zh-Hant':'分享 Wi-Fi — 掃描後手機自動連線' },
  t_qrcontact_name: { bg:'Контакт QR', ru:'Контакт QR', uk:'Контакт QR', en:'Contact QR', de:'Kontakt-QR', fr:'QR contact', es:'QR de contacto', 'es-MX':'QR de contacto', it:'QR contatto', pt:'QR de contato', ar:'QR جهة اتصال', hi:'संपर्क QR', ja:'連絡先QR', ky:'Байланыш QR', 'zh-Hant':'聯絡人 QR' },
  t_qrcontact_desc: { bg:'Визитка (vCard): име, фирма, телефон, имейл — сканиране записва контакта', ru:'Визитка (vCard): имя, компания, телефон, эл. почта — скан сохраняет контакт', uk:'Візитка (vCard): ім’я, компанія, телефон, ел. пошта — скан зберігає контакт', en:'Business card (vCard): name, company, phone, email — scan saves the contact', de:'Visitenkarte (vCard): Name, Firma, Telefon, E-Mail — Scan speichert Kontakt', fr:'Carte de visite (vCard) : nom, société, téléphone, e-mail — le scan enregistre le contact', es:'Tarjeta (vCard): nombre, empresa, teléfono, correo — escanear guarda el contacto', 'es-MX':'Tarjeta (vCard): nombre, empresa, teléfono, correo — escanear guarda el contacto', it:'Biglietto (vCard): nome, azienda, telefono, e-mail — la scansione salva il contatto', pt:'Cartão (vCard): nome, empresa, telefone, e-mail — escanear salva o contato', ar:'بطاقة (vCard): الاسم، الشركة، الهاتف، البريد — المسح يحفظ جهة الاتصال', hi:'विज़िटिंग कार्ड (vCard): नाम, कंपनी, फ़ोन, ईमेल — स्कैन संपर्क सहेजता है', ja:'名刺 (vCard)：名前・会社・電話・メール — スキャンで連絡先保存', ky:'Визитка (vCard): аты, компания, телефон, эл. почта — скан байланышты сактайт', 'zh-Hant':'名片 (vCard)：姓名、公司、電話、電子郵件 — 掃描即存聯絡人' },
  t_qrevent_name: { bg:'Събитие QR', ru:'Событие QR', uk:'Подія QR', en:'Event QR', de:'Termin-QR', fr:'QR événement', es:'QR de evento', 'es-MX':'QR de evento', it:'QR evento', pt:'QR de evento', ar:'QR حدث', hi:'इवेंट QR', ja:'イベントQR', ky:'Окуя QR', 'zh-Hant':'活動 QR' },
  t_qrevent_desc: { bg:'Календарно събитие (заглавие, място, начало/край) — сканиране добавя в календара', ru:'Событие календаря (название, место, начало/конец) — скан добавляет в календарь', uk:'Подія календаря (назва, місце, початок/кінець) — скан додає в календар', en:'Calendar event (title, place, start/end) — scan adds to calendar', de:'Kalendertermin (Titel, Ort, Beginn/Ende) — Scan fügt zum Kalender hinzu', fr:'Événement (titre, lieu, début/fin) — le scan ajoute au calendrier', es:'Evento (título, lugar, inicio/fin) — escanear añade al calendario', 'es-MX':'Evento (título, lugar, inicio/fin) — escanear añade al calendario', it:'Evento (titolo, luogo, inizio/fine) — la scansione aggiunge al calendario', pt:'Evento (título, local, início/fim) — escanear adiciona ao calendário', ar:'حدث تقويم (عنوان، مكان، بداية/نهاية) — المسح يضيفه للتقويم', hi:'कैलेंडर इवेंट (शीर्षक, स्थान, आरंभ/अंत) — स्कैन कैलेंडर में जोड़ता है', ja:'カレンダー予定（題名・場所・開始/終了）— スキャンで追加', ky:'Календарь окуясы (аталыш, жай, башталыш/аяк) — скан календарга кошот', 'zh-Hant':'行事曆活動（標題、地點、起訖）— 掃描加入行事曆' },
  t_qrgeo_name: { bg:'Локация QR', ru:'Локация QR', uk:'Локація QR', en:'Location QR', de:'Standort-QR', fr:'QR localisation', es:'QR de ubicación', 'es-MX':'QR de ubicación', it:'QR posizione', pt:'QR de local', ar:'QR الموقع', hi:'स्थान QR', ja:'位置QR', ky:'Жайгашкан жер QR', 'zh-Hant':'位置 QR' },
  t_qrgeo_desc: { bg:'Координати (geo:) или линк към карта; „Моята локация" по GPS', ru:'Координаты (geo:) или ссылка на карту; «Моё местоположение» по GPS', uk:'Координати (geo:) або посилання на карту; «Моє місцезнаходження» за GPS', en:'Coordinates (geo:) or map link; “My location” via GPS', de:'Koordinaten (geo:) oder Karten-Link; „Mein Standort" per GPS', fr:'Coordonnées (geo:) ou lien carte ; « Ma position » via GPS', es:'Coordenadas (geo:) o enlace de mapa; «Mi ubicación» por GPS', 'es-MX':'Coordenadas (geo:) o enlace de mapa; «Mi ubicación» por GPS', it:'Coordinate (geo:) o link mappa; «La mia posizione» via GPS', pt:'Coordenadas (geo:) ou link do mapa; “Minha localização” via GPS', ar:'إحداثيات (geo:) أو رابط خريطة؛ «موقعي» عبر GPS', hi:'निर्देशांक (geo:) या मानचित्र लिंक; GPS से “मेरा स्थान”', ja:'座標 (geo:) または地図リンク；GPSで「現在地」', ky:'Координаттар (geo:) же карта шилтемеси; GPS менен «Менин жайым»', 'zh-Hant':'座標 (geo:) 或地圖連結；GPS「我的位置」' },
  t_pwcrypt_name: { bg:'Криптиране на текст', ru:'Шифрование текста', uk:'Шифрування тексту', en:'Text encryption', de:'Textverschlüsselung', fr:'Chiffrement de texte', es:'Cifrado de texto', 'es-MX':'Cifrado de texto', it:'Cifratura del testo', pt:'Cifragem de texto', ar:'تشفير النص', hi:'टेक्स्ट एन्क्रिप्शन', ja:'テキスト暗号化', ky:'Текстти шифрлөө', 'zh-Hant':'文字加密' },
  t_pwcrypt_desc: { bg:'AES-256-GCM с парола — прати криптиран текст навсякъде', ru:'AES-256-GCM с паролем — отправляйте зашифрованный текст куда угодно', uk:'AES-256-GCM з паролем — надсилайте зашифрований текст будь-куди', en:'AES-256-GCM with a password — send encrypted text anywhere', de:'AES-256-GCM mit Passwort — verschlüsselten Text überallhin senden', fr:'AES-256-GCM avec mot de passe — envoyez du texte chiffré partout', es:'AES-256-GCM con contraseña — envía texto cifrado a cualquier sitio', 'es-MX':'AES-256-GCM con contraseña — envía texto cifrado a cualquier lugar', it:'AES-256-GCM con password — invia testo cifrato ovunque', pt:'AES-256-GCM com palavra-passe — envie texto cifrado para qualquer lado', ar:'AES-256-GCM بكلمة مرور — أرسل نصاً مشفراً إلى أي مكان', hi:'पासवर्ड के साथ AES-256-GCM — एन्क्रिप्टेड टेक्स्ट कहीं भी भेजें', ja:'パスワード付きAES-256-GCM — 暗号化テキストをどこへでも', ky:'Сырсөз менен AES-256-GCM — шифрленген текстти каалаган жерге жөнөт', 'zh-Hant':'使用密碼的 AES-256-GCM — 將加密文字傳送到任何地方' },
  t_pwhash_name: { bg:'Хешове, кодиране, парола за сайт', ru:'Хеши, кодирование, пароль для сайта', uk:'Хеші, кодування, пароль для сайту', en:'Hashes, encoding, site password', de:'Hashes, Kodierung, Website-Passwort', fr:'Hachages, encodage, mot de passe de site', es:'Hashes, codificación, contraseña de sitio', 'es-MX':'Hashes, codificación, contraseña de sitio', it:'Hash, codifica, password per sito', pt:'Hashes, codificação, palavra-passe de site', ar:'تجزئة، ترميز، كلمة مرور للموقع', hi:'हैश, एन्कोडिंग, साइट पासवर्ड', ja:'ハッシュ・エンコード・サイト用パスワード', ky:'Хэш, коддоо, сайт үчүн сырсөз', 'zh-Hant':'雜湊、編碼、網站密碼' },
  t_pwhash_desc: { bg:'SHA-256/384/512, HMAC, Base64/Hex/URL, детерминирана парола от главна', ru:'SHA-256/384/512, HMAC, Base64/Hex/URL, детерминированный пароль из главного', uk:'SHA-256/384/512, HMAC, Base64/Hex/URL, детермінований пароль із головного', en:'SHA-256/384/512, HMAC, Base64/Hex/URL, deterministic password from a master', de:'SHA-256/384/512, HMAC, Base64/Hex/URL, deterministisches Passwort aus Master', fr:'SHA-256/384/512, HMAC, Base64/Hex/URL, mot de passe déterministe depuis un maître', es:'SHA-256/384/512, HMAC, Base64/Hex/URL, contraseña determinista desde una maestra', 'es-MX':'SHA-256/384/512, HMAC, Base64/Hex/URL, contraseña determinista desde una maestra', it:'SHA-256/384/512, HMAC, Base64/Hex/URL, password deterministica da una principale', pt:'SHA-256/384/512, HMAC, Base64/Hex/URL, palavra-passe determinística a partir de uma mestra', ar:'SHA-256/384/512، HMAC، Base64/Hex/URL، كلمة مرور حتمية من رئيسية', hi:'SHA-256/384/512, HMAC, Base64/Hex/URL, मास्टर से निश्चित पासवर्ड', ja:'SHA-256/384/512、HMAC、Base64/Hex/URL、マスターからの決定的パスワード', ky:'SHA-256/384/512, HMAC, Base64/Hex/URL, башкыдан детерминдик сырсөз', 'zh-Hant':'SHA-256/384/512、HMAC、Base64/Hex/URL、由主密碼決定的密碼' },
  t_pwbrowsers_name: { bg:'Пароли от браузъри', ru:'Пароли из браузеров', uk:'Паролі з браузерів', en:'Browser passwords', de:'Browser-Passwörter', fr:'Mots de passe des navigateurs', es:'Contraseñas de navegadores', 'es-MX':'Contraseñas de navegadores', it:'Password dei browser', pt:'Palavras-passe dos browsers', ar:'كلمات مرور المتصفحات', hi:'ब्राउज़र पासवर्ड', ja:'ブラウザのパスワード', ky:'Браузер сырсөздөрү', 'zh-Hant':'瀏覽器密碼' },
  t_pwbrowsers_desc: { bg:'Износ/внос по табове (телефон/компютър, 7 браузъра) + проверка на CSV', ru:'Экспорт/импорт по вкладкам (телефон/компьютер, 7 браузеров) + проверка CSV', uk:'Експорт/імпорт за вкладками (телефон/комп’ютер, 7 браузерів) + перевірка CSV', en:'Export/import by tabs (phone/computer, 7 browsers) + CSV check', de:'Export/Import nach Tabs (Telefon/Computer, 7 Browser) + CSV-Prüfung', fr:'Export/import par onglets (téléphone/ordinateur, 7 navigateurs) + vérification CSV', es:'Exportar/importar por pestañas (teléfono/ordenador, 7 navegadores) + comprobación CSV', 'es-MX':'Exportar/importar por pestañas (teléfono/computadora, 7 navegadores) + comprobación CSV', it:'Esporta/importa per schede (telefono/computer, 7 browser) + verifica CSV', pt:'Exportar/importar por separadores (telemóvel/computador, 7 browsers) + verificação CSV', ar:'تصدير/استيراد حسب التبويبات (هاتف/حاسوب، 7 متصفحات) + فحص CSV', hi:'टैब से निर्यात/आयात (फ़ोन/कंप्यूटर, 7 ब्राउज़र) + CSV जाँच', ja:'タブ別エクスポート/インポート（スマホ/PC、7ブラウザ）＋CSV検査', ky:'Табдар боюнча экспорт/импорт (телефон/компьютер, 7 браузер) + CSV текшерүү', 'zh-Hant':'依分頁匯出/匯入（手機/電腦，7 種瀏覽器）＋CSV 檢查' },
  t_pwfaq_name: { bg:'FAQ: забравена парола / ключ / ключалка', ru:'FAQ: забытый пароль / ключ / замок', uk:'FAQ: забутий пароль / ключ / замок', en:'FAQ: forgotten password / key / lock', de:'FAQ: Passwort / Schlüssel / Schloss vergessen', fr:'FAQ : mot de passe / clé / cadenas oublié', es:'FAQ: contraseña / llave / cerradura olvidada', 'es-MX':'FAQ: contraseña / llave / cerradura olvidada', it:'FAQ: password / chiave / lucchetto dimenticati', pt:'FAQ: palavra-passe / chave / cadeado esquecidos', ar:'الأسئلة الشائعة: نسيت كلمة المرور / المفتاح / القفل', hi:'FAQ: भूला पासवर्ड / चाबी / ताला', ja:'FAQ：パスワード・鍵・ロックを忘れた', ky:'FAQ: унутулган сырсөз / ачкыч / кулпу', 'zh-Hant':'FAQ：忘記密碼／鑰匙／鎖' },
  t_pwfaq_desc: { bg:'Законни начини за възстановяване: официални източници + най-новото от мрежата (с линк)', ru:'Законные способы восстановления: официальные источники + свежее из сети (со ссылкой)', uk:'Законні способи відновлення: офіційні джерела + найновіше з мережі (з посиланням)', en:'Lawful recovery: official sources + latest from the web (with links)', de:'Legale Wiederherstellung: offizielle Quellen + Neues aus dem Netz (mit Links)', fr:'Récupération légale : sources officielles + nouveautés du web (avec liens)', es:'Recuperación legal: fuentes oficiales + lo último de la web (con enlaces)', 'es-MX':'Recuperación legal: fuentes oficiales + lo último de la web (con enlaces)', it:'Recupero legale: fonti ufficiali + novità dal web (con link)', pt:'Recuperação legal: fontes oficiais + o mais recente da web (com ligações)', ar:'استرداد قانوني: مصادر رسمية + الأحدث من الويب (مع روابط)', hi:'वैध रिकवरी: आधिकारिक स्रोत + वेब से ताज़ा (लिंक सहित)', ja:'合法的な復旧：公式ソース＋ウェブ最新（リンク付き）', ky:'Мыйзамдуу калыбына келтирүү: расмий булактар + тармактан жаңылары (шилтеме менен)', 'zh-Hant':'合法恢復：官方來源＋網路最新（附連結）' },
  t_pwstr_name: { bg:'Анализатор на пароли', ru:'Анализатор паролей', uk:'Аналізатор паролів', en:'Password analyzer', de:'Passwort-Analyse', fr:'Analyseur de mots de passe', es:'Analizador de contraseñas', 'es-MX':'Analizador de contraseñas', it:'Analizzatore password', pt:'Analisador de palavras-passe', ar:'محلل كلمات المرور', hi:'पासवर्ड विश्लेषक', ja:'パスワード分析', ky:'Сырсөз анализатору', 'zh-Hant':'密碼分析器' },
  t_pwstr_desc: { bg:'Ентропия, време за разбиване, слабости, проверка в изтекли бази', ru:'Энтропия, время взлома, слабости, проверка в утечках', uk:'Ентропія, час злому, слабкості, перевірка у витоках', en:'Entropy, crack time, weaknesses, leak check', de:'Entropie, Knackzeit, Schwächen, Leak-Prüfung', fr:'Entropie, temps de cassage, faiblesses, fuites', es:'Entropía, tiempo de descifrado, debilidades, filtraciones', 'es-MX':'Entropía, tiempo de descifrado, debilidades, filtraciones', it:'Entropia, tempo di cracking, debolezze, violazioni', pt:'Entropia, tempo de quebra, fraquezas, fugas', ar:'الإنتروبيا، زمن الكسر، نقاط الضعف، فحص التسريبات', hi:'एन्ट्रॉपी, क्रैक समय, कमज़ोरियाँ, लीक जाँच', ja:'エントロピー、解読時間、弱点、漏洩確認', ky:'Энтропия, бузуу убактысы, алсыздыктар, агып кетүү текшерүү', 'zh-Hant':'熵、破解時間、弱點、外洩檢查' },
  t_pwphr_name: { bg:'Парола-фраза', ru:'Парольная фраза', uk:'Парольна фраза', en:'Passphrase', de:'Passphrase', fr:'Phrase de passe', es:'Frase de contraseña', 'es-MX':'Frase de contraseña', it:'Passphrase', pt:'Frase-passe', ar:'عبارة مرور', hi:'पासफ़्रेज़', ja:'パスフレーズ', ky:'Сырсөз-фраза', 'zh-Hant':'密語' },
  t_pwphr_desc: { bg:'Случайни думи на 6 езика — лесна за помнене, много силна', ru:'Случайные слова на 6 языках — легко запомнить, очень надёжно', uk:'Випадкові слова 6 мовами — легко запам’ятати, дуже надійно', en:'Random words in 6 languages — memorable and very strong', de:'Zufallswörter in 6 Sprachen — merkbar und sehr stark', fr:'Mots aléatoires en 6 langues — mémorisable et très forte', es:'Palabras aleatorias en 6 idiomas — fácil de recordar y muy fuerte', 'es-MX':'Palabras aleatorias en 6 idiomas — fácil de recordar y muy fuerte', it:'Parole casuali in 6 lingue — memorabile e molto forte', pt:'Palavras aleatórias em 6 idiomas — memorável e muito forte', ar:'كلمات عشوائية بـ6 لغات — سهلة التذكر وقوية جداً', hi:'6 भाषाओं में यादृच्छिक शब्द — याद रखने योग्य और बहुत मज़बूत', ja:'6言語のランダム単語 — 覚えやすく非常に強力', ky:'6 тилде кокус сөздөр — эстөө оңой, абдан күчтүү', 'zh-Hant':'6 種語言的隨機單字 — 好記且非常強' },
  t_pwbulk_name: { bg:'Пакетни пароли + политика', ru:'Пакет паролей + политика', uk:'Пакет паролів + політика', en:'Bulk passwords + policy', de:'Passwort-Stapel + Richtlinie', fr:'Mots de passe en lot + politique', es:'Contraseñas en lote + política', 'es-MX':'Contraseñas en lote + política', it:'Password in blocco + policy', pt:'Palavras-passe em lote + política', ar:'كلمات مرور بالجملة + سياسة', hi:'बल्क पासवर्ड + नीति', ja:'一括パスワード＋ポリシー', ky:'Топтоп сырсөздөр + саясат', 'zh-Hant':'批次密碼＋政策' },
  t_pwbulk_desc: { bg:'До 100 пароли по правила, проверени, износ CSV', ru:'До 100 паролей по правилам, проверены, экспорт CSV', uk:'До 100 паролів за правилами, перевірені, експорт CSV', en:'Up to 100 passwords by policy, checked, CSV export', de:'Bis zu 100 Passwörter nach Richtlinie, geprüft, CSV-Export', fr:'Jusqu’à 100 mots de passe selon une politique, vérifiés, export CSV', es:'Hasta 100 contraseñas por política, comprobadas, exportación CSV', 'es-MX':'Hasta 100 contraseñas por política, comprobadas, exportación CSV', it:'Fino a 100 password per policy, verificate, esportazione CSV', pt:'Até 100 palavras-passe por política, verificadas, exportação CSV', ar:'حتى 100 كلمة مرور وفق سياسة، مفحوصة، تصدير CSV', hi:'नीति के अनुसार 100 तक पासवर्ड, जाँचे हुए, CSV निर्यात', ja:'ポリシーに沿って最大100件、チェック済み、CSV出力', ky:'Саясат боюнча 100гө чейин сырсөз, текшерилген, CSV экспорт', 'zh-Hant':'依政策最多 100 組密碼，已檢查，匯出 CSV' },
  more_tools: { bg:'Още инструменти', ru:'Ещё инструменты', uk:'Ще інструменти', en:'More tools', de:'Weitere Tools', fr:'Autres outils', es:'Más herramientas', 'es-MX':'Más herramientas', it:'Altri strumenti', pt:'Mais ferramentas', ar:'أدوات أخرى', hi:'और टूल', ja:'その他のツール', ky:'Дагы куралдар', 'zh-Hant':'更多工具' },
  t_life_name: { bg:'Стойност в живот', ru:'Стоимость в жизни', uk:'Вартість у житті', en:'Cost in life', de:'Preis in Lebenszeit', fr:'Coût en vie', es:'Coste en vida', 'es-MX':'Costo en vida', it:'Costo in vita', pt:'Custo em vida', ar:'الثمن من حياتك', hi:'जीवन में कीमत', ja:'人生換算の価格', ky:'Өмүрдөгү баа', 'zh-Hant':'生命成本' },
  t_life_desc: { bg:'Колко работни часа, дни и месеци от живота ти струва една покупка — и докога ти стигат парите без работа', ru:'Сколько рабочих часов, дней и месяцев жизни стоит покупка — и на сколько хватит денег без работы', uk:'Скільки робочих годин, днів і місяців життя коштує покупка — і на скільки вистачить грошей без роботи', en:'How many working hours, days and months of your life a purchase costs — and how long your money lasts without work', de:'Wie viele Arbeitsstunden, Tage und Monate deines Lebens ein Kauf kostet — und wie lange dein Geld ohne Arbeit reicht', fr:'Combien d’heures, de jours et de mois de votre vie coûte un achat — et combien de temps votre argent dure sans travail', es:'Cuántas horas, días y meses de tu vida cuesta una compra — y cuánto dura tu dinero sin trabajar', 'es-MX':'Cuántas horas, días y meses de tu vida cuesta una compra — y cuánto dura tu dinero sin trabajar', it:'Quante ore, giorni e mesi della tua vita costa un acquisto — e quanto durano i tuoi soldi senza lavoro', pt:'Quantas horas, dias e meses da sua vida custa uma compra — e quanto dura o seu dinheiro sem trabalho', ar:'كم ساعة عمل ويومًا وشهرًا من حياتك يكلّف شراء ما — وكم يدوم مالك بلا عمل', hi:'एक खरीद आपके जीवन के कितने कार्य घंटे, दिन और महीने लेती है — और बिना काम पैसा कब तक चलेगा', ja:'買い物が人生の労働時間・日数・月数でいくらか — 働かずにお金がどれだけもつか', ky:'Бир сатып алуу өмүрүңдүн канча иш саатын, күнүн жана айын алат — жана ишсиз акча канчага жетет', 'zh-Hant':'一次購買花掉你人生多少工作小時、天數與月份 — 以及不工作時錢能撐多久' },
  t_budget_name: { bg:'Личен бюджет', ru:'Личный бюджет', uk:'Особистий бюджет', en:'Personal budget', de:'Persönliches Budget', fr:'Budget personnel', es:'Presupuesto personal', 'es-MX':'Presupuesto personal', it:'Bilancio personale', pt:'Orçamento pessoal', ar:'الميزانية الشخصية', hi:'व्यक्तिगत बजट', ja:'家計簿', ky:'Жеке бюджет', 'zh-Hant':'個人預算' },
  t_budget_desc: { bg:'Пликове с лимит, абонаменти, отчети, нетна стойност', ru:'Конверты с лимитом, подписки, отчёты, чистая стоимость', uk:'Конверти з лімітом, підписки, звіти, чиста вартість', en:'Envelopes with limits, recurring bills, reports, net worth', de:'Umschläge mit Limit, Abos, Berichte, Nettovermögen', fr:'Enveloppes à limite, récurrents, rapports, valeur nette', es:'Sobres con límite, recurrentes, informes, patrimonio neto', 'es-MX':'Sobres con límite, recurrentes, reportes, patrimonio neto', it:'Buste con limite, ricorrenti, report, patrimonio netto', pt:'Envelopes com limite, recorrentes, relatórios, património', ar:'مظاريف بحدود، مدفوعات متكررة، تقارير، صافي الثروة', hi:'सीमा वाले लिफ़ाफ़े, आवर्ती बिल, रिपोर्ट, शुद्ध संपत्ति', ja:'上限付き封筒・定期支払い・レポート・純資産', ky:'Лимиттүү конверттер, кайталануучу төлөмдөр, отчёттор, таза баалуулук', 'zh-Hant':'限額信封、定期付款、報表、淨資產' },
  t_planner_name: { bg:'Финансов планировчик', ru:'Финансовый планировщик', uk:'Фінансовий планувальник', en:'Financial planner', de:'Finanzplaner', fr:'Planificateur financier', es:'Planificador financiero', 'es-MX':'Planificador financiero', it:'Pianificatore finanziario', pt:'Planeador financeiro', ar:'المخطط المالي', hi:'वित्तीय योजनाकार', ja:'ファイナンシャルプランナー', ky:'Каржы пландоочу', 'zh-Hant':'理財規劃' },
  t_planner_desc: { bg:'Ипотека с погасителен план, цел за спестяване, дългове', ru:'Ипотека с графиком, цель накопления, долги', uk:'Іпотека з графіком, ціль заощадження, борги', en:'Mortgage schedule, savings goal, debt payoff', de:'Tilgungsplan, Sparziel, Schuldenabbau', fr:'Tableau d’amortissement, objectif d’épargne, dettes', es:'Amortización, meta de ahorro, deudas', 'es-MX':'Amortización, meta de ahorro, deudas', it:'Piano mutuo, obiettivo di risparmio, debiti', pt:'Plano de amortização, meta de poupança, dívidas', ar:'جدول الرهن، هدف الادخار، سداد الديون', hi:'बंधक अनुसूची, बचत लक्ष्य, क़र्ज़ चुकौती', ja:'返済計画・貯蓄目標・借金返済', ky:'Ипотека графиги, топтоо максаты, карыздар', 'zh-Hant':'房貸計畫、儲蓄目標、債務清償' },
  t_pwatch_name: { bg:'Наблюдател на страници', ru:'Наблюдатель страниц', uk:'Спостерігач сторінок', en:'Page watcher', de:'Seiten-Beobachter', fr:'Surveillance de pages', es:'Vigilante de páginas', 'es-MX':'Vigilante de páginas', it:'Osservatore di pagine', pt:'Vigilante de páginas', ar:'مراقب الصفحات', hi:'पेज वॉचर', ja:'ページ監視', ky:'Барак байкоочу', 'zh-Hant':'頁面監看器' },
  t_pwatch_desc: { bg:'Запазени цели → сканирай отново, история, ново/изчезнало/променено, известия, CSV', ru:'Сохранённые цели → повторное сканирование, история, новое/исчезло/изменено, уведомления, CSV', uk:'Збережені цілі → повторне сканування, історія, нове/зникло/змінено, сповіщення, CSV', en:'Saved targets → re-scan, history, new/gone/changed, alerts, CSV', de:'Gespeicherte Ziele → neu scannen, Verlauf, neu/weg/geändert, Hinweise, CSV', fr:'Cibles enregistrées → rescanner, historique, nouveau/disparu/modifié, alertes, CSV', es:'Objetivos guardados → reescanear, historial, nuevo/desaparecido/cambiado, avisos, CSV', 'es-MX':'Objetivos guardados → reescanear, historial, nuevo/desaparecido/cambiado, avisos, CSV', it:'Obiettivi salvati → riscansiona, cronologia, nuovo/sparito/cambiato, avvisi, CSV', pt:'Alvos guardados → reanalisar, histórico, novo/desaparecido/alterado, alertas, CSV', ar:'أهداف محفوظة → إعادة فحص، سجل، جديد/مختفٍ/متغيّر، تنبيهات، CSV', hi:'सहेजे लक्ष्य → दोबारा स्कैन, इतिहास, नया/गायब/बदला, अलर्ट, CSV', ja:'保存した対象 → 再スキャン、履歴、新規/消滅/変更、通知、CSV', ky:'Сакталган максаттар → кайра скандоо, тарых, жаңы/жоголду/өзгөрдү, эскертүү, CSV', 'zh-Hant':'已存目標 → 重新掃描、歷史、新增/消失/變更、通知、CSV' },
  t_scrlite_name: { bg:'Скрапер на устройството', ru:'Скрапер на устройстве', uk:'Скрапер на пристрої', en:'On-device scraper', de:'Scraper auf dem Gerät', fr:'Scraper sur l’appareil', es:'Scraper en el dispositivo', 'es-MX':'Scraper en el dispositivo', it:'Scraper sul dispositivo', pt:'Scraper no dispositivo', ar:'كاشط على الجهاز', hi:'डिवाइस पर स्क्रैपर', ja:'端末内スクレイパー', ky:'Түзмөктөгү скрепер', 'zh-Hant':'裝置端擷取器' },
  t_scrlite_desc: { bg:'Без сървър: адреси или търсене → имейли, телефони, връзки, тип, CSV', ru:'Без сервера: адреса или поиск → email, телефоны, ссылки, тип, CSV', uk:'Без сервера: адреси або пошук → email, телефони, посилання, тип, CSV', en:'No server: URLs or search → emails, phones, links, type, CSV', de:'Ohne Server: URLs oder Suche → E-Mails, Telefone, Links, Typ, CSV', fr:'Sans serveur : URL ou recherche → e-mails, téléphones, liens, type, CSV', es:'Sin servidor: URL o búsqueda → correos, teléfonos, enlaces, tipo, CSV', 'es-MX':'Sin servidor: URL o búsqueda → correos, teléfonos, enlaces, tipo, CSV', it:'Senza server: URL o ricerca → email, telefoni, link, tipo, CSV', pt:'Sem servidor: URLs ou pesquisa → e-mails, telefones, ligações, tipo, CSV', ar:'بدون خادم: عناوين أو بحث → بريد، هواتف، روابط، نوع، CSV', hi:'बिना सर्वर: URL या खोज → ईमेल, फ़ोन, लिंक, प्रकार, CSV', ja:'サーバー不要：URLまたは検索 → メール、電話、リンク、種類、CSV', ky:'Серверсиз: даректер же издөө → email, телефон, шилтеме, түр, CSV', 'zh-Hant':'無需伺服器：網址或搜尋 → 電郵、電話、連結、類型、CSV' },
  t_camp_name: { bg:'Кампании с известия', ru:'Кампании объявлений', uk:'Кампанії оголошень', en:'Announcement campaigns', de:'Anzeigen-Kampagnen', fr:'Campagnes d’annonces', es:'Campañas de anuncios', 'es-MX':'Campañas de anuncios', it:'Campagne di annunci', pt:'Campanhas de anúncios', ar:'حملات الإعلانات', hi:'घोषणा अभियान', ja:'お知らせキャンペーン', ky:'Жарнама кампаниялары', 'zh-Hant':'公告活動' },
  t_camp_desc: { bg:'Генерирай известие (и офлайн), планирай канал и дата, следи история и статистика', ru:'Создай объявление (и офлайн), запланируй канал и дату, следи за историей и статистикой', uk:'Створи оголошення (і офлайн), заплануй канал і дату, стеж за історією та статистикою', en:'Generate an announcement (also offline), schedule channel and date, track history and stats', de:'Anzeige erstellen (auch offline), Kanal und Datum planen, Verlauf und Statistik verfolgen', fr:'Génère une annonce (même hors ligne), planifie canal et date, suis historique et statistiques', es:'Genera un anuncio (también sin conexión), programa canal y fecha, sigue historial y estadísticas', 'es-MX':'Genera un anuncio (también sin conexión), programa canal y fecha, sigue historial y estadísticas', it:'Genera un annuncio (anche offline), pianifica canale e data, segui cronologia e statistiche', pt:'Gere um anúncio (também offline), agende canal e data, acompanhe histórico e estatísticas', ar:'أنشئ إعلانًا (حتى دون اتصال)، خطّط القناة والتاريخ، تابع السجل والإحصاءات', hi:'घोषणा बनाएँ (ऑफ़लाइन भी), माध्यम और तारीख तय करें, इतिहास और आँकड़े देखें', ja:'お知らせを生成（オフラインでも）、チャネルと日時を予約、履歴と統計を確認', ky:'Жарнама түз (офлайн да), канал менен датаны пландa, тарых менен статистиканы көзөмөлдө', 'zh-Hant':'產生公告（離線亦可）、排程管道與日期、追蹤歷史與統計' },

  // --- Обединено приложение (v1.0021): раздели на решетката + вериги от инструменти ---
  grp_docs: { bg:'Документи', ru:'Документы', uk:'Документи', en:'Documents', de:'Dokumente', fr:'Documents', es:'Documentos', 'es-MX':'Documentos', it:'Documenti', pt:'Documentos', ar:'المستندات', hi:'दस्तावेज़', ja:'ドキュメント', ky:'Документтер', 'zh-Hant':'文件' },
  grp_text: { bg:'Текст', ru:'Текст', uk:'Текст', en:'Text', de:'Text', fr:'Texte', es:'Texto', 'es-MX':'Texto', it:'Testo', pt:'Texto', ar:'النص', hi:'टेक्स्ट', ja:'テキスト', ky:'Текст', 'zh-Hant':'文字' },
  grp_keys: { bg:'Пароли и ключове', ru:'Пароли и ключи', uk:'Паролі та ключі', en:'Passwords & keys', de:'Passwörter & Schlüssel', fr:'Mots de passe et clés', es:'Contraseñas y claves', 'es-MX':'Contraseñas y claves', it:'Password e chiavi', pt:'Senhas e chaves', ar:'كلمات المرور والمفاتيح', hi:'पासवर्ड और कुंजियाँ', ja:'パスワードと鍵', ky:'Сырсөздөр жана ачкычтар', 'zh-Hant':'密碼與金鑰' },
  grp_media: { bg:'Снимки и видео', ru:'Фото и видео', uk:'Фото і відео', en:'Photos & video', de:'Fotos & Video', fr:'Photos et vidéo', es:'Fotos y vídeo', 'es-MX':'Fotos y video', it:'Foto e video', pt:'Fotos e vídeo', ar:'الصور والفيديو', hi:'फ़ोटो और वीडियो', ja:'写真と動画', ky:'Сүрөт жана видео', 'zh-Hant':'照片與影片' },
  grp_sound: { bg:'Звук', ru:'Звук', uk:'Звук', en:'Sound', de:'Ton', fr:'Son', es:'Sonido', 'es-MX':'Sonido', it:'Audio', pt:'Som', ar:'الصوت', hi:'ध्वनि', ja:'サウンド', ky:'Үн', 'zh-Hant':'聲音' },
  grp_finance: { bg:'Финанси', ru:'Финансы', uk:'Фінанси', en:'Finance', de:'Finanzen', fr:'Finances', es:'Finanzas', 'es-MX':'Finanzas', it:'Finanze', pt:'Finanças', ar:'المالية', hi:'वित्त', ja:'ファイナンス', ky:'Каржы', 'zh-Hant':'財務' },
  grp_qr: { bg:'QR кодове', ru:'QR-коды', uk:'QR-коди', en:'QR codes', de:'QR-Codes', fr:'Codes QR', es:'Códigos QR', 'es-MX':'Códigos QR', it:'Codici QR', pt:'Códigos QR', ar:'رموز QR', hi:'QR कोड', ja:'QRコード', ky:'QR коддор', 'zh-Hant':'QR 碼' },
  grp_web: { bg:'Уеб', ru:'Веб', uk:'Веб', en:'Web', de:'Web', fr:'Web', es:'Web', 'es-MX':'Web', it:'Web', pt:'Web', ar:'الويب', hi:'वेब', ja:'ウェブ', ky:'Веб', 'zh-Hant':'網頁' },
  grp_3d: { bg:'3D', ru:'3D', uk:'3D', en:'3D', de:'3D', fr:'3D', es:'3D', 'es-MX':'3D', it:'3D', pt:'3D', ar:'ثلاثي الأبعاد', hi:'3D', ja:'3D', ky:'3D', 'zh-Hant':'3D' },
  grp_ai: { bg:'ИИ и текстове за бизнеса', ru:'ИИ и тексты для бизнеса', uk:'ШІ та тексти для бізнесу', en:'AI & business texts', de:'KI & Geschäftstexte', fr:'IA et textes pro', es:'IA y textos de negocio', 'es-MX':'IA y textos de negocio', it:'IA e testi aziendali', pt:'IA e textos de negócio', ar:'الذكاء الاصطناعي ونصوص الأعمال', hi:'AI और व्यावसायिक टेक्स्ट', ja:'AIとビジネス文書', ky:'ЖИ жана бизнес тексттер', 'zh-Hant':'AI 與商務文案' },
  grp_count: { bg:'{0} инструмента', ru:'{0} инструментов', uk:'{0} інструментів', en:'{0} tools', de:'{0} Werkzeuge', fr:'{0} outils', es:'{0} herramientas', 'es-MX':'{0} herramientas', it:'{0} strumenti', pt:'{0} ferramentas', ar:'{0} أداة', hi:'{0} टूल', ja:'{0} ツール', ky:'{0} курал', 'zh-Hant':'{0} 個工具' },
  grp_count1: { bg:'1 инструмент', ru:'1 инструмент', uk:'1 інструмент', en:'1 tool', de:'1 Werkzeug', fr:'1 outil', es:'1 herramienta', 'es-MX':'1 herramienta', it:'1 strumento', pt:'1 ferramenta', ar:'أداة واحدة', hi:'1 टूल', ja:'1 ツール', ky:'1 курал', 'zh-Hant':'1 個工具' },
  t_chains_name: { bg:'Вериги от инструменти', ru:'Цепочки инструментов', uk:'Ланцюжки інструментів', en:'Tool chains', de:'Werkzeugketten', fr:'Chaînes d’outils', es:'Cadenas de herramientas', 'es-MX':'Cadenas de herramientas', it:'Catene di strumenti', pt:'Cadeias de ferramentas', ar:'سلاسل الأدوات', hi:'टूल चेन', ja:'ツールチェーン', ky:'Курал чынжырлары', 'zh-Hant':'工具鏈' },
  t_chains_desc: { bg:'Изходът на един инструмент е вход на следващия: 6 готови вериги + свои', ru:'Результат одного инструмента — вход для следующего: 6 готовых цепочек + свои', uk:'Результат одного інструмента — вхід для наступного: 6 готових ланцюжків + свої', en:'One tool’s output feeds the next: 6 ready chains + your own', de:'Die Ausgabe eines Werkzeugs ist die Eingabe des nächsten: 6 fertige Ketten + eigene', fr:'La sortie d’un outil alimente le suivant : 6 chaînes prêtes + les vôtres', es:'La salida de una herramienta alimenta la siguiente: 6 cadenas listas + las tuyas', 'es-MX':'La salida de una herramienta alimenta la siguiente: 6 cadenas listas + las tuyas', it:'L’output di uno strumento alimenta il successivo: 6 catene pronte + le tue', pt:'A saída de uma ferramenta alimenta a seguinte: 6 cadeias prontas + as suas', ar:'مخرج أداة يصبح مدخل التالية: 6 سلاسل جاهزة + سلاسلك', hi:'एक टूल का आउटपुट अगले का इनपुट: 6 तैयार चेन + अपनी', ja:'ツールの出力が次の入力に：6つの既製チェーン＋自作', ky:'Бир куралдын чыгышы кийинкинин кириши: 6 даяр чынжыр + өзүңдүкү', 'zh-Hant':'一個工具的輸出即下一個的輸入：6 條現成工具鏈＋自訂' },
  chain_bar: { bg:'Верига „{0}" — стъпка {1} от {2}', ru:'Цепочка «{0}» — шаг {1} из {2}', uk:'Ланцюжок «{0}» — крок {1} з {2}', en:'Chain “{0}” — step {1} of {2}', de:'Kette „{0}“ – Schritt {1} von {2}', fr:'Chaîne « {0} » – étape {1} sur {2}', es:'Cadena «{0}» — paso {1} de {2}', 'es-MX':'Cadena «{0}» — paso {1} de {2}', it:'Catena «{0}» — passo {1} di {2}', pt:'Cadeia «{0}» — passo {1} de {2}', ar:'السلسلة «{0}» — الخطوة {1} من {2}', hi:'चेन “{0}” — चरण {1}/{2}', ja:'チェーン「{0}」— ステップ {1}/{2}', ky:'Чынжыр «{0}» — {2} кадамдын {1}-си', 'zh-Hant':'工具鏈「{0}」— 第 {1} 步，共 {2} 步' },
  chain_next: { bg:'Следваща стъпка →', ru:'Следующий шаг →', uk:'Наступний крок →', en:'Next step →', de:'Nächster Schritt →', fr:'Étape suivante →', es:'Siguiente paso →', 'es-MX':'Siguiente paso →', it:'Passo successivo →', pt:'Próximo passo →', ar:'الخطوة التالية ←', hi:'अगला चरण →', ja:'次のステップ →', ky:'Кийинки кадам →', 'zh-Hant':'下一步 →' },
  chain_finish: { bg:'Завърши веригата ✓', ru:'Завершить цепочку ✓', uk:'Завершити ланцюжок ✓', en:'Finish chain ✓', de:'Kette abschließen ✓', fr:'Terminer la chaîne ✓', es:'Terminar cadena ✓', 'es-MX':'Terminar cadena ✓', it:'Termina catena ✓', pt:'Concluir cadeia ✓', ar:'إنهاء السلسلة ✓', hi:'चेन पूरी करें ✓', ja:'チェーンを完了 ✓', ky:'Чынжырды бүтүрүү ✓', 'zh-Hant':'完成工具鏈 ✓' },
  chain_stop: { bg:'Прекрати', ru:'Прервать', uk:'Перервати', en:'Stop', de:'Abbrechen', fr:'Arrêter', es:'Detener', 'es-MX':'Detener', it:'Interrompi', pt:'Parar', ar:'إيقاف', hi:'रोकें', ja:'中止', ky:'Токтотуу', 'zh-Hant':'停止' },
  chain_done_msg: { bg:'Веригата е завършена. Всички резултати са записани на устройството.', ru:'Цепочка завершена. Все результаты сохранены на устройстве.', uk:'Ланцюжок завершено. Усі результати збережено на пристрої.', en:'Chain finished. All results are saved on the device.', de:'Kette abgeschlossen. Alle Ergebnisse sind auf dem Gerät gespeichert.', fr:'Chaîne terminée. Tous les résultats sont enregistrés sur l’appareil.', es:'Cadena terminada. Todos los resultados están guardados en el dispositivo.', 'es-MX':'Cadena terminada. Todos los resultados están guardados en el dispositivo.', it:'Catena completata. Tutti i risultati sono salvati sul dispositivo.', pt:'Cadeia concluída. Todos os resultados estão guardados no dispositivo.', ar:'اكتملت السلسلة. جميع النتائج محفوظة على الجهاز.', hi:'चेन पूरी हुई। सभी परिणाम डिवाइस पर सहेजे गए हैं।', ja:'チェーンが完了しました。すべての結果は端末に保存されています。', ky:'Чынжыр бүттү. Бардык натыйжалар түзмөктө сакталды.', 'zh-Hant':'工具鏈已完成。所有結果都已儲存在裝置上。' },
};

let current = detect();
// Език по локала на устройството (навигатора) → наш код от 15-те; '' ако няма съвпадение.
function deviceLang() {
  var SUP = ['bg','ru','uk','en','de','fr','es','es-MX','it','pt','ar','hi','ja','ky','zh-Hant'];
  function pick(tag) {
    if (!tag) return ''; var low = String(tag).toLowerCase();
    if (low.indexOf('zh') === 0) return 'zh-Hant';           // наличен е само традиционен китайски
    if (low.indexOf('pt') === 0) return 'pt';
    if (low.indexOf('es') === 0) return (low.indexOf('mx') > -1 || low.indexOf('419') > -1 || low.indexOf('us') > -1) ? 'es-MX' : 'es';
    var two = low.slice(0, 2);
    for (var i = 0; i < SUP.length; i++) if (SUP[i] === two) return SUP[i];
    return '';
  }
  try {
    var arr = (navigator.languages && navigator.languages.length) ? navigator.languages : [navigator.language || navigator.userLanguage || navigator.browserLanguage || ''];
    for (var i = 0; i < arr.length; i++) { var m = pick(arr[i]); if (m) return m; }
  } catch (e) {}
  return '';
}
function detect() { try { const s = localStorage.getItem(LS_KEY); if (s && STR.back[s] != null) return s; } catch (e) {} return deviceLang() || DEFAULT_LANG; }
export function hasLangChosen() { try { return !!localStorage.getItem(LS_KEY); } catch (e) { return false; } }
export function getLang() { return current; }
export function setLang(c) { if (STR.back[c] == null) return; current = c; try { localStorage.setItem(LS_KEY, c); } catch (e) {} applyDir(); }
export function isRTL() { return RTL.indexOf(current) > -1; }
export function applyDir() { try { document.documentElement.setAttribute('dir', isRTL() ? 'rtl' : 'ltr'); document.documentElement.setAttribute('lang', current); } catch (e) {} }
// Инструментите регистрират своите низове сами (за да не пипат този файл едновременно).
export function register(dict) { for (const k in dict) STR[k] = dict[k]; }
export function t(key) { const r = STR[key]; if (!r) return key; if (r[current] != null) return r[current]; if (r[DEFAULT_LANG] != null) return r[DEFAULT_LANG]; if (r[FALLBACK_LANG] != null) return r[FALLBACK_LANG]; return key; }
export function tf(key, ...vals) { let s = t(key); vals.forEach((v, i) => { s = s.replace(new RegExp('\\{' + i + '\\}', 'g'), String(v)); }); return s; }
export { LANGUAGES };
