// Version: 1.0001
// i18n.js — преводен слой за Services Toolkit на 15-те езика. Дефолт руски.
import { LANGUAGES } from './languages.js';

const LS_KEY = 'servicestoolkit.lang';
const DEFAULT_LANG = 'ru';
const FALLBACK_LANG = 'en';
const RTL = ['ar'];

const STR = {
  pick_lang: { bg:'Избери език', ru:'Выберите язык', uk:'Виберіть мову', en:'Choose language', de:'Sprache wählen', fr:'Choisir la langue', es:'Elegir idioma', 'es-MX':'Elegir idioma', it:'Scegli la lingua', pt:'Escolher idioma', ar:'اختر اللغة', hi:'भाषा चुनें', ja:'言語を選択', ky:'Тилди тандаңыз', 'zh-Hant':'選擇語言' },
  lang_btn: { bg:'🌐 Език', ru:'🌐 Язык', uk:'🌐 Мова', en:'🌐 Language', de:'🌐 Sprache', fr:'🌐 Langue', es:'🌐 Idioma', 'es-MX':'🌐 Idioma', it:'🌐 Lingua', pt:'🌐 Idioma', ar:'🌐 اللغة', hi:'🌐 भाषा', ja:'🌐 言語', ky:'🌐 Тил', 'zh-Hant':'🌐 語言' },
  start_app: { bg:'Стартирай', ru:'Запустить', uk:'Запустити', en:'Start', de:'Starten', fr:'Démarrer', es:'Iniciar', 'es-MX':'Iniciar', it:'Avvia', pt:'Iniciar', ar:'ابدأ', hi:'शुरू करें', ja:'開始', ky:'Баштоо', 'zh-Hant':'開始' },
  home_sub: { bg:'Полезни офлайн инструменти — всичко работи на устройството.', ru:'Полезные офлайн-инструменты — всё работает на устройстве.', uk:'Корисні офлайн-інструменти — усе працює на пристрої.', en:'Handy offline tools — everything runs on your device.', de:'Praktische Offline-Tools — alles läuft auf dem Gerät.', fr:'Outils hors-ligne pratiques — tout fonctionne sur l’appareil.', es:'Útiles herramientas sin conexión — todo funciona en el dispositivo.', 'es-MX':'Útiles herramientas sin conexión — todo funciona en el dispositivo.', it:'Comodi strumenti offline — tutto gira sul dispositivo.', pt:'Ferramentas offline úteis — tudo roda no dispositivo.', ar:'أدوات مفيدة دون اتصال — كل شيء يعمل على جهازك.', hi:'उपयोगी ऑफ़लाइन टूल — सब कुछ डिवाइस पर चलता है।', ja:'便利なオフラインツール — すべて端末上で動作。', ky:'Пайдалуу оффлайн куралдар — баары түзмөктө иштейт.', 'zh-Hant':'實用的離線工具 — 一切都在裝置上執行。' },
  search_ph: { bg:'Търси инструмент…', ru:'Поиск инструмента…', uk:'Пошук інструмента…', en:'Search a tool…', de:'Werkzeug suchen…', fr:'Rechercher un outil…', es:'Buscar herramienta…', 'es-MX':'Buscar herramienta…', it:'Cerca uno strumento…', pt:'Buscar ferramenta…', ar:'ابحث عن أداة…', hi:'टूल खोजें…', ja:'ツールを検索…', ky:'Куралды издөө…', 'zh-Hant':'搜尋工具…' },
  no_matches: { bg:'Няма съвпадения.', ru:'Совпадений нет.', uk:'Збігів немає.', en:'No matches.', de:'Keine Treffer.', fr:'Aucun résultat.', es:'Sin coincidencias.', 'es-MX':'Sin coincidencias.', it:'Nessuna corrispondenza.', pt:'Sem correspondências.', ar:'لا نتائج.', hi:'कोई मिलान नहीं।', ja:'一致なし。', ky:'Дал келүү жок.', 'zh-Hant':'沒有相符項目。' },
  online_tag: { bg:'онлайн', ru:'онлайн', uk:'онлайн', en:'online', de:'online', fr:'en ligne', es:'en línea', 'es-MX':'en línea', it:'online', pt:'online', ar:'متصل', hi:'ऑनलाइन', ja:'オンライン', ky:'онлайн', 'zh-Hant':'線上' },
  back: { bg:'Назад', ru:'Назад', uk:'Назад', en:'Back', de:'Zurück', fr:'Retour', es:'Atrás', 'es-MX':'Atrás', it:'Indietro', pt:'Voltar', ar:'رجوع', hi:'वापस', ja:'戻る', ky:'Артка', 'zh-Hant':'返回' },
  loading: { bg:'Зареждам…', ru:'Загрузка…', uk:'Завантаження…', en:'Loading…', de:'Laden…', fr:'Chargement…', es:'Cargando…', 'es-MX':'Cargando…', it:'Caricamento…', pt:'Carregando…', ar:'جارٍ التحميل…', hi:'लोड हो रहा…', ja:'読み込み中…', ky:'Жүктөлүүдө…', 'zh-Hant':'載入中…' },
  load_error: { bg:'Грешка при зареждане на инструмента:', ru:'Ошибка загрузки инструмента:', uk:'Помилка завантаження інструмента:', en:'Error loading the tool:', de:'Fehler beim Laden des Werkzeugs:', fr:'Erreur de chargement de l’outil :', es:'Error al cargar la herramienta:', 'es-MX':'Error al cargar la herramienta:', it:'Errore nel caricamento dello strumento:', pt:'Erro ao carregar a ferramenta:', ar:'خطأ في تحميل الأداة:', hi:'टूल लोड करने में त्रुटि:', ja:'ツールの読み込みエラー:', ky:'Куралды жүктөөдө ката:', 'zh-Hant':'載入工具時發生錯誤：' },

  t_qr_name: { bg:'QR код', ru:'QR-код', uk:'QR-код', en:'QR code', de:'QR-Code', fr:'Code QR', es:'Código QR', 'es-MX':'Código QR', it:'Codice QR', pt:'Código QR', ar:'رمز QR', hi:'QR कोड', ja:'QRコード', ky:'QR код', 'zh-Hant':'QR 碼' },
  t_qr_desc: { bg:'Генерирай и разчети QR кодове', ru:'Создавай и сканируй QR-коды', uk:'Створюй і скануй QR-коди', en:'Generate and read QR codes', de:'QR-Codes erstellen und lesen', fr:'Générer et lire des codes QR', es:'Genera y lee códigos QR', 'es-MX':'Genera y lee códigos QR', it:'Genera e leggi codici QR', pt:'Gere e leia códigos QR', ar:'أنشئ واقرأ رموز QR', hi:'QR कोड बनाएं और पढ़ें', ja:'QRコードの生成と読み取り', ky:'QR коддорду түзүү жана окуу', 'zh-Hant':'產生與讀取 QR 碼' },
  t_password_name: { bg:'Генератор на пароли', ru:'Генератор паролей', uk:'Генератор паролів', en:'Password generator', de:'Passwortgenerator', fr:'Générateur de mots de passe', es:'Generador de contraseñas', 'es-MX':'Generador de contraseñas', it:'Generatore di password', pt:'Gerador de senhas', ar:'مولّد كلمات المرور', hi:'पासवर्ड जेनरेटर', ja:'パスワード生成', ky:'Сырсөз генератору', 'zh-Hant':'密碼產生器' },
  t_password_desc: { bg:'Силни пароли с 4 метода', ru:'Надёжные пароли, 4 метода', uk:'Надійні паролі, 4 методи', en:'Strong passwords, 4 methods', de:'Starke Passwörter, 4 Methoden', fr:'Mots de passe forts, 4 méthodes', es:'Contraseñas fuertes, 4 métodos', 'es-MX':'Contraseñas fuertes, 4 métodos', it:'Password forti, 4 metodi', pt:'Senhas fortes, 4 métodos', ar:'كلمات مرور قوية، ٤ طرق', hi:'मज़बूत पासवर्ड, 4 तरीके', ja:'強力なパスワード・4方式', ky:'Күчтүү сырсөздөр, 4 ыкма', 'zh-Hant':'強密碼，4 種方式' },
  t_calc_name: { bg:'Калкулатори', ru:'Калькуляторы', uk:'Калькулятори', en:'Calculators', de:'Rechner', fr:'Calculatrices', es:'Calculadoras', 'es-MX':'Calculadoras', it:'Calcolatrici', pt:'Calculadoras', ar:'حاسبات', hi:'कैलकुलेटर', ja:'計算ツール', ky:'Эсептегичтер', 'zh-Hant':'計算機' },
  t_calc_desc: { bg:'Заем, ДДС, лихва, проценти', ru:'Кредит, НДС, проценты', uk:'Кредит, ПДВ, відсотки', en:'Loan, VAT, interest, percentages', de:'Kredit, MwSt., Zinsen, Prozente', fr:'Prêt, TVA, intérêts, pourcentages', es:'Préstamo, IVA, interés, porcentajes', 'es-MX':'Préstamo, IVA, interés, porcentajes', it:'Prestito, IVA, interessi, percentuali', pt:'Empréstimo, IVA, juros, percentagens', ar:'قرض، ضريبة، فائدة، نسب', hi:'ऋण, वैट, ब्याज, प्रतिशत', ja:'ローン・税・利息・割合', ky:'Насыя, КНС, пайыз', 'zh-Hant':'貸款、增值稅、利息、百分比' },
  t_text_name: { bg:'Текстови инструменти', ru:'Текстовые инструменты', uk:'Текстові інструменти', en:'Text tools', de:'Text-Werkzeuge', fr:'Outils de texte', es:'Herramientas de texto', 'es-MX':'Herramientas de texto', it:'Strumenti di testo', pt:'Ferramentas de texto', ar:'أدوات النصوص', hi:'टेक्स्ट टूल', ja:'テキストツール', ky:'Текст куралдары', 'zh-Hant':'文字工具' },
  t_text_desc: { bg:'Брояч, форматиране, Base64', ru:'Счётчик, форматирование, Base64', uk:'Лічильник, форматування, Base64', en:'Counter, formatting, Base64', de:'Zähler, Formatierung, Base64', fr:'Compteur, mise en forme, Base64', es:'Contador, formato, Base64', 'es-MX':'Contador, formato, Base64', it:'Contatore, formattazione, Base64', pt:'Contador, formatação, Base64', ar:'عدّاد، تنسيق، Base64', hi:'काउंटर, फ़ॉर्मेटिंग, Base64', ja:'カウント・整形・Base64', ky:'Эсептегич, форматтоо, Base64', 'zh-Hant':'計數、格式化、Base64' },
  t_image_name: { bg:'Компресор на снимки', ru:'Сжатие изображений', uk:'Стиснення зображень', en:'Image compressor', de:'Bildkompressor', fr:'Compresseur d’images', es:'Compresor de imágenes', 'es-MX':'Compresor de imágenes', it:'Compressore immagini', pt:'Compressor de imagens', ar:'ضاغط الصور', hi:'इमेज कंप्रेसर', ja:'画像圧縮', ky:'Сүрөт кысуу', 'zh-Hant':'圖片壓縮' },
  t_image_desc: { bg:'Намали JPEG / PNG / WebP', ru:'Уменьши JPEG / PNG / WebP', uk:'Зменши JPEG / PNG / WebP', en:'Shrink JPEG / PNG / WebP', de:'JPEG / PNG / WebP verkleinern', fr:'Réduire JPEG / PNG / WebP', es:'Reduce JPEG / PNG / WebP', 'es-MX':'Reduce JPEG / PNG / WebP', it:'Riduci JPEG / PNG / WebP', pt:'Reduza JPEG / PNG / WebP', ar:'صغّر JPEG / PNG / WebP', hi:'JPEG / PNG / WebP छोटा करें', ja:'JPEG / PNG / WebP を縮小', ky:'JPEG / PNG / WebP кичирейтүү', 'zh-Hant':'縮小 JPEG / PNG / WebP' },
  t_pdf_name: { bg:'PDF инструменти', ru:'PDF-инструменты', uk:'PDF-інструменти', en:'PDF tools', de:'PDF-Werkzeuge', fr:'Outils PDF', es:'Herramientas PDF', 'es-MX':'Herramientas PDF', it:'Strumenti PDF', pt:'Ferramentas PDF', ar:'أدوات PDF', hi:'PDF टूल', ja:'PDFツール', ky:'PDF куралдары', 'zh-Hant':'PDF 工具' },
  t_pdf_desc: { bg:'Сливане, разделяне, воден знак', ru:'Объединение, разделение, водяной знак', uk:'Об’єднання, поділ, водяний знак', en:'Merge, split, watermark', de:'Zusammenführen, teilen, Wasserzeichen', fr:'Fusionner, diviser, filigrane', es:'Unir, dividir, marca de agua', 'es-MX':'Unir, dividir, marca de agua', it:'Unisci, dividi, filigrana', pt:'Juntar, dividir, marca d’água', ar:'دمج، تقسيم، علامة مائية', hi:'मर्ज, विभाजन, वॉटरमार्क', ja:'結合・分割・透かし', ky:'Бириктирүү, бөлүү, суу белгиси', 'zh-Hant':'合併、分割、浮水印' },
  t_pdfc_name: { bg:'Свиване на PDF', ru:'Сжатие PDF', uk:'Стиснення PDF', en:'PDF compress', de:'PDF komprimieren', fr:'Compresser PDF', es:'Comprimir PDF', 'es-MX':'Comprimir PDF', it:'Comprimi PDF', pt:'Comprimir PDF', ar:'ضغط PDF', hi:'PDF संपीड़न', ja:'PDF圧縮', ky:'PDF кысуу', 'zh-Hant':'PDF 壓縮' },
  t_pdfc_desc: { bg:'Растеризира страниците за по-малък размер', ru:'Растрирует страницы для меньшего размера', uk:'Растеризує сторінки для меншого розміру', en:'Rasterizes pages for a smaller size', de:'Rastert Seiten für kleinere Größe', fr:'Rastérise les pages pour réduire la taille', es:'Rasteriza páginas para reducir tamaño', 'es-MX':'Rasteriza páginas para reducir tamaño', it:'Rasterizza le pagine per ridurre la dimensione', pt:'Rasteriza páginas para reduzir o tamanho', ar:'يحوّل الصفحات إلى صور لتصغير الحجم', hi:'छोटे आकार हेतु पेज रास्टराइज़ करता है', ja:'ページをラスタライズして縮小', ky:'Барактарды кичирейтүү үчүн растрлайт', 'zh-Hant':'點陣化頁面以縮小體積' },
  t_crypto_name: { bg:'Крипто графики', ru:'Крипто-графики', uk:'Крипто-графіки', en:'Crypto charts', de:'Krypto-Charts', fr:'Graphiques crypto', es:'Gráficos cripto', 'es-MX':'Gráficos cripto', it:'Grafici cripto', pt:'Gráficos cripto', ar:'مخططات الكريبتو', hi:'क्रिप्टो चार्ट', ja:'暗号資産チャート', ky:'Крипто графиктер', 'zh-Hant':'加密貨幣圖表' },
  t_crypto_desc: { bg:'RSI, Fibonacci, BTC/ETH по периоди (Binance/CoinGecko)', ru:'RSI, Фибоначчи, BTC/ETH по периодам (Binance/CoinGecko)', uk:'RSI, Фібоначчі, BTC/ETH за періоди (Binance/CoinGecko)', en:'RSI, Fibonacci, BTC/ETH over periods (Binance/CoinGecko)', de:'RSI, Fibonacci, BTC/ETH über Zeiträume (Binance/CoinGecko)', fr:'RSI, Fibonacci, BTC/ETH par périodes (Binance/CoinGecko)', es:'RSI, Fibonacci, BTC/ETH por periodos (Binance/CoinGecko)', 'es-MX':'RSI, Fibonacci, BTC/ETH por periodos (Binance/CoinGecko)', it:'RSI, Fibonacci, BTC/ETH per periodi (Binance/CoinGecko)', pt:'RSI, Fibonacci, BTC/ETH por períodos (Binance/CoinGecko)', ar:'RSI، فيبوناتشي، BTC/ETH عبر الفترات (Binance/CoinGecko)', hi:'RSI, फिबोनाची, BTC/ETH अवधि अनुसार (Binance/CoinGecko)', ja:'RSI・フィボナッチ・BTC/ETH 期間別（Binance/CoinGecko）', ky:'RSI, Фибоначчи, BTC/ETH мезгилдер боюнча (Binance/CoinGecko)', 'zh-Hant':'RSI、費波那契、BTC/ETH 各週期（Binance/CoinGecko）' },
  t_fx_name: { bg:'Валутни курсове', ru:'Курсы валют', uk:'Курси валют', en:'Currency rates', de:'Wechselkurse', fr:'Taux de change', es:'Tipos de cambio', 'es-MX':'Tipos de cambio', it:'Tassi di cambio', pt:'Taxas de câmbio', ar:'أسعار العملات', hi:'मुद्रा दरें', ja:'為替レート', ky:'Валюта курстары', 'zh-Hant':'匯率' },
  t_fx_desc: { bg:'Конвертор и курсове на живо', ru:'Конвертер и курсы в реальном времени', uk:'Конвертер і курси в реальному часі', en:'Converter and live rates', de:'Umrechner und Live-Kurse', fr:'Convertisseur et taux en direct', es:'Conversor y tasas en vivo', 'es-MX':'Conversor y tasas en vivo', it:'Convertitore e tassi live', pt:'Conversor e taxas ao vivo', ar:'محوّل وأسعار حية', hi:'कन्वर्टर और लाइव दरें', ja:'コンバーターとライブレート', ky:'Конвертер жана түз курстар', 'zh-Hant':'換算器與即時匯率' },
  t_watch20_name: { bg:'Наблюдавай 20 валути', ru:'Следи за 20 валютами', uk:'Стеж за 20 валютами', en:'Watch 20 currencies', de:'20 Währungen beobachten', fr:'Surveiller 20 devises', es:'Vigila 20 monedas', 'es-MX':'Vigila 20 monedas', it:'Monitora 20 valute', pt:'Acompanhe 20 moedas', ar:'راقب ٢٠ عملة', hi:'20 मुद्राएं देखें', ja:'20通貨を監視', ky:'20 валютаны байкоо', 'zh-Hant':'監看 20 種貨幣' },
  t_watch20_desc: { bg:'Прагове с известие и звук за до 20 двойки', ru:'Пороги с уведомлением и звуком до 20 пар', uk:'Пороги зі сповіщенням і звуком до 20 пар', en:'Alert + sound thresholds for up to 20 pairs', de:'Schwellen mit Hinweis und Ton für bis zu 20 Paare', fr:'Seuils avec alerte et son pour 20 paires', es:'Umbrales con aviso y sonido para hasta 20 pares', 'es-MX':'Umbrales con aviso y sonido para hasta 20 pares', it:'Soglie con avviso e suono fino a 20 coppie', pt:'Limiares com aviso e som para até 20 pares', ar:'حدود مع تنبيه وصوت حتى ٢٠ زوجًا', hi:'20 जोड़ियों तक अलर्ट + ध्वनि सीमाएं', ja:'最大20ペアの通知・音しきい値', ky:'20 жупка чейин эскертүү жана үн чеги', 'zh-Hant':'最多 20 組的提醒與聲音門檻' },
  t_scraper_name: { bg:'Web скрапер', ru:'Веб-скрапер', uk:'Веб-скрапер', en:'Web scraper', de:'Web-Scraper', fr:'Scraper web', es:'Web scraper', 'es-MX':'Web scraper', it:'Web scraper', pt:'Web scraper', ar:'كاشط ويب', hi:'वेब स्क्रैपर', ja:'ウェブスクレイパー', ky:'Веб скрапер', 'zh-Hant':'網頁擷取器' },
  t_scraper_desc: { bg:'Извличане на заглавие/текст/връзки', ru:'Извлечение заголовка/текста/ссылок', uk:'Витяг заголовка/тексту/посилань', en:'Extract title/text/links', de:'Titel/Text/Links extrahieren', fr:'Extraire titre/texte/liens', es:'Extraer título/texto/enlaces', 'es-MX':'Extraer título/texto/enlaces', it:'Estrai titolo/testo/link', pt:'Extrair título/texto/links', ar:'استخراج العنوان/النص/الروابط', hi:'शीर्षक/टेक्स्ट/लिंक निकालें', ja:'タイトル/本文/リンクを抽出', ky:'Аталыш/текст/шилтемелерди алуу', 'zh-Hant':'擷取標題／文字／連結' },
  t_ai_name: { bg:'AI генератор на текст', ru:'AI-генератор текста', uk:'AI-генератор тексту', en:'AI text generator', de:'KI-Textgenerator', fr:'Générateur de texte IA', es:'Generador de texto IA', 'es-MX':'Generador de texto IA', it:'Generatore di testo IA', pt:'Gerador de texto IA', ar:'مولّد نصوص بالذكاء الاصطناعي', hi:'AI टेक्स्ट जेनरेटर', ja:'AIテキスト生成', ky:'AI текст генератору', 'zh-Hant':'AI 文字產生器' },
  t_ai_desc: { bg:'Пиши, обобщавай, превеждай (безплатно)', ru:'Пиши, обобщай, переводи (бесплатно)', uk:'Пиши, узагальнюй, перекладай (безкоштовно)', en:'Write, summarize, translate (free)', de:'Schreiben, zusammenfassen, übersetzen (gratis)', fr:'Écrire, résumer, traduire (gratuit)', es:'Escribe, resume, traduce (gratis)', 'es-MX':'Escribe, resume, traduce (gratis)', it:'Scrivi, riassumi, traduci (gratis)', pt:'Escreva, resuma, traduza (grátis)', ar:'اكتب، لخّص، ترجم (مجانًا)', hi:'लिखें, सारांश, अनुवाद (मुफ़्त)', ja:'作成・要約・翻訳（無料）', ky:'Жаз, жыйынтыкта, котор (акысыз)', 'zh-Hant':'撰寫、摘要、翻譯（免費）' }
};

let current = detect();
function detect() { try { const s = localStorage.getItem(LS_KEY); if (s && STR.back[s] != null) return s; } catch (e) {} return DEFAULT_LANG; }
export function hasLangChosen() { try { return !!localStorage.getItem(LS_KEY); } catch (e) { return false; } }
export function getLang() { return current; }
export function setLang(c) { if (STR.back[c] == null) return; current = c; try { localStorage.setItem(LS_KEY, c); } catch (e) {} applyDir(); }
export function isRTL() { return RTL.indexOf(current) > -1; }
export function applyDir() { try { document.documentElement.setAttribute('dir', isRTL() ? 'rtl' : 'ltr'); document.documentElement.setAttribute('lang', current); } catch (e) {} }
// Инструментите регистрират своите низове сами (за да не пипат този файл едновременно).
export function register(dict) { for (const k in dict) STR[k] = dict[k]; }
export function t(key) { const r = STR[key]; if (!r) return key; if (r[current] != null) return r[current]; if (r[DEFAULT_LANG] != null) return r[DEFAULT_LANG]; if (r[FALLBACK_LANG] != null) return r[FALLBACK_LANG]; return key; }
export function tf(key, ...vals) { let s = t(key); vals.forEach((v, i) => { s = s.replace(new RegExp('\\{' + i + '\\}', 'g'), String(v)); }); return s; }
export { LANGUAGES };
